### ISSUE TITLE
kubeapps install without internet

### ISSUE THREAD

**Issue by prabhurs123** [kubeapps/kubeapps#1002]
HI Team,

Need help to deploy kubeapps in local environment without internet.

I have installed Kubernetes,helm without internet but I am not able to install kubeapps without internet.

Could you please guide how can I achieve this.

**Comment by andresmgot** [comment]
Hi @prabhurs123,

It's not supported to run Kubeapps without any internet connection. When running Kubeapps, it's necessary to download some CSS and font files. You may be able to still use that if you set up a proxy for those specific URLs.

Apart from that, to install/use Kubeapps, an internet connection is needed for:

 - Download the images of the Kubeapps chart. You can see the list of images used in the chart [values.yaml](https://github.com/bitnami/charts/blob/master/bitnami/kubeapps/values.yaml). As you can see there, the images uses docker.io as a registry so if you need to do so offline you need to copy the images to a private repository and change the reference there to your registry URL.
 - Sync the list of charts. By default, Kubeapps will look for charts in the repositories described [here](https://github.com/bitnami/charts/blob/master/bitnami/kubeapps/values.yaml#L108). If you don't want to use those you will need to have a private registry with the charts you want to use and configure its URL in the `values.yaml` file.

Then, when installing charts, if you are using the official charts, they are configured again to download images from the docker hub. If you want to avoid that you will need to perform the same step than with Kubeapps images (change the references to docker.io to a private docker registry).

I may be missing something but those are the most important issues if you try to run Kubeapps without an internet connection.

**Comment by prabhurs123** [comment]
Thanks Andres, I have tried like downloaded all the required kubeapps images and uploaded to my local registry and then updated the urls in values.yaml, but it did not work.

**Comment by andresmgot** [comment]
What error are you receiving @prabhurs123? Does it fail when installing the chart?

**Comment by arapulido** [comment]
@prabhurs123 We are closing the issue, as it is not a case we support. Let us know if we can help in any other way

**Comment by michaelabdo** [comment]
Hey @prabhurs123 

Did you eventually get this working?

**Comment by Yi-jiunTang** [comment]
Hi @andresmgot , we have the same issue here.
We need to deploy and use Kubeapps with no internet. I read your reply above that you don't support  running Kubeapps without internet. 
Although the chance is slim, if you have plan to support situation with no internet?
Or please point me out where the CSS and font files will save, maybe i can download them first to satisfy offline environment. 
Anyway, thanks a lot!

**Comment by andresmgot** [comment]
> Hi @andresmgot , we have the same issue here.
> We need to deploy and use Kubeapps with no internet. I read your reply above that you don't support running Kubeapps without internet.
> Although the chance is slim, if you have plan to support situation with no internet?

Unfortunately that's not in our roadmap at the moment.

> Or please point me out where the CSS and font files will save, maybe i can download them first to satisfy offline environment.
> Anyway, thanks a lot!

You can find the link to the fonts and the css source in the index.scss:

https://github.com/kubeapps/kubeapps/blob/master/dashboard/src/index.scss#L1

But even if those are mirrored and changed, it's likely that you will need more changes. For example, all the charts in the configured registries should be configured to work offline. In any case, if you give it a try we can help you to try to workaround possible errors.

Hope it helps,
