### ISSUE TITLE
Traefik chart image link is broken

### ISSUE THREAD

**Issue by StiviiK** [kubeapps/kubeapps#1003]
The url for the Traefik chart image is not available any more:
![image](https://user-images.githubusercontent.com/8115642/55162511-4ce47500-5168-11e9-9519-be0da80a7d18.png)
https://traefik.io/traefik.logo.png

**Comment by andresmgot** [comment]
Hi @StiviiK,

Thanks for the issue! We don't actually maintain the traefik chart we are getting the info from the chart in the stable repository: https://github.com/helm/charts/blob/master/stable/traefik/Chart.yaml#L25

Do you mind opening a issue there and ping the owners of the chart? If you submit a PR will be even better :)

**Comment by StiviiK** [comment]
Oh i missed that, i'll will do that.
