### ISSUE TITLE
kubeapps GUI does not get the chart details

### ISSUE THREAD

**Issue by ArunN85** [kubeapps/kubeapps#1004]
Have installed kubeapps when try to get the App Repositories, it fails with the below error. 

![image](https://user-images.githubusercontent.com/49278966/55559433-d1f10080-570b-11e9-8adf-12c1a7dd9bc5.png)

Initially since I was not able to access the dashboard, exposed the deployment of dashboard.
[root@cwe1 ~]$ kubectl get svc -n kubeapps
NAME                             TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
kubeapps                         ClusterIP   10.254.21.122    <none>        80/TCP           6h44m
kubeapps-internal-chartsvc       ClusterIP   10.254.67.143    <none>        8080/TCP         6h44m
kubeapps-internal-dashboard      ClusterIP   10.254.140.248   <none>        8080/TCP         6h44m
kubeapps-internal-tiller-proxy   ClusterIP   10.254.221.158   <none>        8080/TCP         6h44m
kubeapps-mongodb                 ClusterIP   10.254.64.131    <none>        27017/TCP        6h44m
kubeapps1                        NodePort    10.254.66.139    <none>        8080:31721/TCP   16m

[root@cwe1 ~]$ kubectl get crd
NAME                           CREATED AT
apprepositories.kubeapps.com   2019-04-04T06:35:38Z

POD status :
[root@cwe1 ~]$ kubectl get pods -o wide -n kubeapps
NAME                                                          READY   STATUS    RESTARTS   AGE     IP                NODE   NOMINATED NODE
kubeapps-9699fc54-kndk4                                       1/1     Running   0          4h32m   192.160.132.212   cwe1   <none>
kubeapps-9699fc54-v28kz                                       1/1     Running   0          6h56m   192.160.40.132    we2    <none>
kubeapps-internal-apprepository-controller-768bfc696f-ggk7j   1/1     Running   0          4h32m   192.160.40.131    we2    <none>
kubeapps-internal-chartsvc-55b768f59d-7t9n4                   1/1     Running   1          6h56m   192.160.132.247   cwe1   <none>
kubeapps-internal-chartsvc-55b768f59d-h9585                   1/1     Running   1          6h56m   192.160.40.169    we2    <none>
kubeapps-internal-dashboard-77749b47fc-lt5xx                  1/1     Running   0          6h56m   192.160.182.225   we1    <none>
kubeapps-internal-dashboard-77749b47fc-s9nd9                  1/1     Running   0          6h56m   192.160.35.91     cwe2   <none>
kubeapps-internal-tiller-proxy-cdf6f4b54-kj99p                1/1     Running   0          6h56m   192.160.182.238   we1    <none>
kubeapps-internal-tiller-proxy-cdf6f4b54-xthxh                1/1     Running   0          6h56m   192.160.132.220   cwe1   <none>
kubeapps-mongodb-89c57f6f9-45lpr                              1/1     Running   0          4h32m   192.160.35.87     cwe2   <none>
[root@cwe1 ~]$ 

Anything i missed to configure which is causing this problem.

**Comment by ArunN85** [comment]
Figured it out. There was issue with the POD with deployment which had exposed. Now solved.
Thanks

**Comment by gintest** [comment]
@ArunN85 : I am facing the same issue, can you explain the solution more in detail please? 
That would be helpful indeed.

**Comment by andresmgot** [comment]
hi @gintest do you have more details about your specific issue? Maybe the cause is different.

Do you see that error only when getting AppRepositories? How have you installed kubeapps? Does the browser console show any more info about the error?
