### ISSUE TITLE
Extend image format support for chart icons

### ISSUE THREAD

**Issue by acottais** [kubeapps/kubeapps#1007]
Maybe more a question than an issue. I have set up a private chartmuseum instance to host my own helm charts. I have then added this repository in kubeapps. Everything works fines except that my private charts does not display the logo when selecting the charts in the catalog. When the package is deployed the logo is correctly displayed.

So how do you package the logo of your private charts repository in order to display them in the catalog ?

**Comment by andresmgot** [comment]
Hi @acottais, it seems that the service is not able to process the icon while populating the catalog but it's able to do so from the release information. Can you check the logs of the `apprepo` sync job that is executed to populate the charts of your chartmuseum? There you should able to see the cause of the error:

```
kubectl logs -n kubeapps apprepo-sync-<repo-name>-<hash>
```

**Comment by acottais** [comment]
I think I found the error. I use data Uri for the icon and the sync job does not seems to support this scheme

`time="2019-04-17T10:00:02Z" level=error msg="failed to import icon" error="Get data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0...Zz4K: unsupported protocol scheme \"data\"" name=monitoring-stack` 

I will change to an absolute URL to see if it fixes my problem.

**Comment by andresmgot** [comment]
Yes, right now the support for formats is quite limited. A full URL to a PNG file should work though.

**Comment by prydonius** [comment]
For the catalog, we currently fetch and process each chart icon. When viewing a release of a chart, we simply load the icon directly from the Chart.yaml file. This is probably why you're seeing the logo for the release but not in the catalog.

Ideally we would use the icon we fetched for the catalog for the releases too, which would avoid having to hotlink to an external icon. The problem is that Helm doesn't store information about what repository a chart release is from, so we can't reliably get the icon. Also, you might have installed a chart from your local filesystem or from a repository not synced in Kubeapps so the icon might not be there.

**Comment by arapulido** [comment]
@prydonius Can you check how many charts have their icon as SVG, please?

**Comment by prydonius** [comment]
Looking at a log from a recent sync, there are 32 chart icons just in stable that we cannot import. I haven't checked all of them, but they seem to mostly be SVGs. I suggest we add support for SVG images (we would need to handle this differently for SVGs in chart-repo: https://github.com/helm/monocular/blob/master/cmd/chart-repo/utils.go#L313).

We should also be able to add support for base64 encoded formats (see https://github.com/disintegration/imaging/issues/85#issuecomment-453308308).

```
time="2019-04-22T11:00:20Z" level=error msg="failed to import icon" error="image: unknown format" name=elastic-stack
time="2019-04-22T11:00:20Z" level=error msg="failed to import icon" error="image: unknown format" name=sonarqube
time="2019-04-22T11:00:20Z" level=error msg="failed to import icon" error="image: unknown format" name=apm-server
time="2019-04-22T11:00:20Z" level=error msg="failed to import icon" error="image: unknown format" name=bookstack
time="2019-04-22T11:00:20Z" level=error msg="failed to import icon" error="image: unknown format" name=kubernetes-dashboard
time="2019-04-22T11:00:20Z" level=error msg="failed to import icon" error="image: unknown format" name=logstash
time="2019-04-22T11:00:20Z" level=error msg="failed to import icon" error="image: unknown format" name=msoms
time="2019-04-22T11:00:21Z" level=error msg="failed to import icon" error="image: unknown format" name=distributed-jmeter
time="2019-04-22T11:00:21Z" level=error msg="failed to import icon" error="image: unknown format" name=filebeat
time="2019-04-22T11:00:21Z" level=error msg="failed to import icon" error="image: unknown format" name=newrelic-infrastructure
time="2019-04-22T11:00:21Z" level=error msg="failed to import icon" error="image: unknown format" name=sapho
time="2019-04-22T11:00:21Z" level=error msg="failed to import icon" error="image: unknown format" name=auditbeat
time="2019-04-22T11:00:22Z" level=error msg="failed to import icon" error="image: unknown format" name=vault-operator
time="2019-04-22T11:00:22Z" level=error msg="failed to import icon" error="image: unknown format" name=elasticsearch
time="2019-04-22T11:00:22Z" level=error msg="failed to import icon" error="image: unknown format" name=risk-advisor
time="2019-04-22T11:00:22Z" level=error msg="failed to import icon" error="image: unknown format" name=ignite
time="2019-04-22T11:00:22Z" level=error msg="failed to import icon" error="image: unknown format" name=kube-slack
time="2019-04-22T11:00:22Z" level=error msg="failed to import icon" error="image: unknown format" name=sonatype-nexus
time="2019-04-22T11:00:23Z" level=error msg="failed to import icon" error="image: unknown format" name=cerebro
time="2019-04-22T11:00:23Z" level=error msg="failed to import icon" error="image: unknown format" name=coredns
time="2019-04-22T11:00:23Z" level=error msg="failed to import icon" error="image: unknown format" name=mercure
time="2019-04-22T11:00:23Z" level=error msg="failed to import icon" error="image: unknown format" name=elastalert
time="2019-04-22T11:00:23Z" level=error msg="failed to import icon" error="image: unknown format" name=cluster-autoscaler
time="2019-04-22T11:00:24Z" level=error msg="failed to import icon" error="image: unknown format" name=metabase
time="2019-04-22T11:00:24Z" level=error msg="failed to import icon" error="image: unknown format" name=metricbeat
time="2019-04-22T11:00:24Z" level=error msg="failed to import icon" error="image: unknown format" name=docker-registry
time="2019-04-22T11:00:24Z" level=error msg="failed to import icon" error="image: unknown format" name=jaeger-operator
time="2019-04-22T11:00:24Z" level=error msg="failed to import icon" error="image: unknown format" name=rocketchat
time="2019-04-22T11:00:24Z" level=error msg="failed to import icon" error="image: unknown format" name=heartbeat
time="2019-04-22T11:00:25Z" level=error msg="failed to import icon" error="image: unknown format" name=nextcloud
time="2019-04-22T11:00:25Z" level=error msg="failed to import icon" error="image: unknown format" name=rookout
time="2019-04-22T11:00:25Z" level=error msg="failed to import icon" error="image: unknown format" name=signalsciences
```
