### ISSUE TITLE
504 when installing slow chart

### ISSUE THREAD

**Issue by LP0101** [kubeapps/kubeapps#1009]
We have some charts that take upward of 2 minutes to deploy (ie: according to the readiness probe). When deploying them via Kubeapps, it will show the loading animation for about 60-90 seconds, then return to the deployment page with this error: `Request failed with status code 504`. However, the chart is still being deployed by helm, and the deployment will eventually be succesful.

I imagine this is caused by a timeout if a chart takes too long to deploy. Is it possible to increase this timeout to prevent this error from showing up?

**Comment by andresmgot** [comment]
Hi @LP0101,

By default, the minimum timeout that we set for contacting Tiller (helm server side) is 180s:

https://github.com/kubeapps/kubeapps/blob/master/pkg/chart/chart.go#L45

Having said that, it's true that the timeout needs to be configured as well at the Ingress level if you are using an Ingress controller. By default we configure it for the Nginx Ingress controller but if you are using a different one you may need to change the annotation we set (we set it to 10 minutes):

https://github.com/kubeapps/kubeapps/blob/master/chart/kubeapps/values.yaml#L31

We also set that in the configuration for the Nginx service that is serving the Dashboard:

https://github.com/kubeapps/kubeapps/blob/master/chart/kubeapps/templates/kubeapps-frontend-config.yaml#L60

How are you accessing the application? Does the web browser console show more info about who is returning the timeout? To check if `tiller-proxy` (the tool that we use to contact tiller) is the one dropping the connection you can check the logs of that pod too.

**Comment by LP0101** [comment]
Hm, the issue seems to have resolved itself by reinstalling kubeapps, unfortunately can't get any logs on what was causing it anymore.

Closing this ticket, I'll reopen it if I experience it once more.

**Comment by LP0101** [comment]
Spoke too soon, apparently.

So, we're using Haproxy as an ingress. The issue doesn't seem to arise from the tiller-proxy pod, as there's no errors there, and the pod does report a successful deployment, despite the frontend showing a 504.

The chart we're deploying uses a post-install container, which takes between 80-120 seconds to execute. This delay is what's causing the problem.

Here's the log from the javascript console:
```
POST https://kubeapps.cxpt.sap.corp/api/tiller-deploy/v1/namespaces/test-whitestar-kubeapps-deploy/releases 504

  | (anonymous) | @ | xhr.js:178
-- | -- | -- | --
  | e.exports | @ | xhr.js:12
  | e.exports | @ | dispatchRequest.js:57
  | Promise.then (async) |   |  
  | s.request | @ | Axios.js:51
  | s.(anonymous function) | @ | Axios.js:71
  | (anonymous) | @ | bind.js:9
  | (anonymous) | @ | App.ts:35
  | (anonymous) | @ | semver.js:1351
  | (anonymous) | @ | semver.js:1351
  | a | @ | semver.js:1351
  | Promise.then (async) |   |  
  | u | @ | semver.js:1351
  | (anonymous) | @ | semver.js:1351
  | i | @ | semver.js:1351
  | e.create | @ | App.ts:29
  | (anonymous) | @ | apps.ts:222
  | (anonymous) | @ | apps.ts:246
  | (anonymous) | @ | apps.ts:246
  | (anonymous) | @ | apps.ts:246
  | l | @ | apps.ts:246
  | (anonymous) | @ | apps.ts:210
  | (anonymous) | @ | index.js:8
  | deployChart | @ | AppNewContainer.tsx:41
  | (anonymous) | @ | DeploymentForm.tsx:181
  | (anonymous) | @ | index.tsx:3
  | (anonymous) | @ | index.tsx:3
  | (anonymous) | @ | index.tsx:3
  | d | @ | index.tsx:3
  | t.handleDeploy | @ | DeploymentForm.tsx:174
  | (anonymous) | @ | react-dom.production.min.js:14
  | h | @ | react-dom.production.min.js:15
  | (anonymous) | @ | react-dom.production.min.js:15
  | C | @ | react-dom.production.min.js:17
  | S | @ | react-dom.production.min.js:18
  | D | @ | react-dom.production.min.js:18
  | O | @ | react-dom.production.min.js:18
  | j | @ | react-dom.production.min.js:21
  | _r | @ | react-dom.production.min.js:84
  | ma | @ | react-dom.production.min.js:216
  | Ie | @ | react-dom.production.min.js:39
  | kr | @ | react-dom.production.min.js:86
  | va | @ | react-dom.production.min.js:216
  | Or | @ | react-dom.production.min.js:85


```

Looking into possible haproxy annotations, it doesn't seem it has a proxy-timeout like nginx.

**Comment by prydonius** [comment]
Hey @LP0101, which Ingress controller are you using? Voyager seems to support a timeout option: https://github.com/appscode/voyager/blob/master/docs/guides/ingress/configuration/default-timeouts.md

**Comment by LP0101** [comment]
As I'd mentioned, I'm using the haproxy ingress controller. Based on the haproxy documentation, it does have a `ingress.kubernetes.io/timeout-queue` annotation. However, it looks like this only affects 503 errors, not 504. I'll give it a try regardless tomorrow, and report back to see if that works.

**Comment by andresmgot** [comment]
It seems that it may be possible to use a configmap and set `timeout-http-request`? I am reading the docs here:

https://github.com/jcmoraisjr/haproxy-ingress#timeout

If not you may be able to get some help from the maintainers there. We cannot do much in our side if the Ingress Controller closes the connection.

**Comment by prydonius** [comment]
good find @andresmgot, I think either `timeout-http-request` or `timeout-server` is what you're looking for, `timeout-queue` is a timeout for queuing connections when the max number of connections has been reached according to the HAproxy docs: http://cbonte.github.io/haproxy-dconv/1.8/configuration.html#4-timeout%20queue.

**Comment by LP0101** [comment]
Updating the value of `timeout-server` worked, longer charts are working just fine now 👍 

However, this required updating our timeout globally on the ingress controller for all applications. Maybe it would be ideal if Kubeapps had some sort of polling behaviour while waiting for a response from Tiller, as simply waiting for a single HTTP response might be prone to such bugginess?

**Comment by andresmgot** [comment]
Glad it worked!

> Maybe it would be ideal if Kubeapps had some sort of polling behaviour while waiting for a response from Tiller, as simply waiting for a single HTTP response might be prone to such bugginess?

We have discussed that in the past, see this issue for more details: https://github.com/kubeapps/kubeapps/issues/710

**Comment by prydonius** [comment]
Thanks for the feedback @LP0101, I'll close this out for now and we can continue the discussion around that in #710.
