### ISSUE TITLE
kubeapps-dashboard-api crashed many times on Azure AKS

### ISSUE THREAD

**Issue by AceHack** [kubeapps/kubeapps#101]
One of the two has finally started up, but the other one is still crashing, been 10 times now.

https://gist.github.com/AceHack/cd4a79c323b7c44aaa78c3fb78fac629

**Comment by AceHack** [comment]
Both finally started

**Comment by ngtuna** [comment]
Did you find out any issue/error in the pod's log?

**Comment by AceHack** [comment]
No, they just kept getting killed

**Comment by prydonius** [comment]
The way the Monocular API currently indexes charts is not very efficient, in this case we're creating too many goroutines (one for each chart). I've been working on a new sync job that will hopefully fix these issues (https://github.com/kubernetes-helm/monocular/tree/master/src/api/cmd/chart-repo-sync).

Also you should only see a single pod for the API in the latest version of Kubeapps, I reduced the replicas from 2 to 1 for the faster start up time.

**Comment by ngtuna** [comment]
@prydonius Can we have any update on the monocular api performance ?

**Comment by prydonius** [comment]
@ngtuna this will be part of the 0.3.0 release (see https://github.com/kubeapps/manifest/pull/36).

**Comment by ngtuna** [comment]
so I guess we can close this

**Comment by prydonius** [comment]
@ngtuna we should probably keep it open and put it under a 0.3.0 milestone

**Comment by ngtuna** [comment]
yeah fair point

**Comment by prydonius** [comment]
This API service is no longer part of Kubeapps as of 0.3.0, so closing this.
