### ISSUE TITLE
Kubeapps crashes if the chart version is not semver compatible

### ISSUE THREAD

**Issue by LP0101** [kubeapps/kubeapps#1011]
I'm experiencing this when deploying a single custom chart of ours, I can't find the source of it.

It happens when viewing any namespace where the chart is deployed. Here's a screenshot of the error:
![image](https://user-images.githubusercontent.com/16864921/56509595-6f627780-64f5-11e9-8a7b-46a96b526aa4.png)

Looking at the Javascript console, I get this error:

`kube.ts:58 WebSocket connection to 'wss://<DOMAIN>/api/kube/api/v1/namespaces/<NAMESPACE</services?watch=true&fieldSelector=metadata.name%3Djenkins-agent' failed: WebSocket is closed before the connection is established.`

I've tried using different version numbers, no luck. This is the Chart.yml for the chart we're deploying:

```
apiVersion: v1
name: jenkins-dynamic
version: 1.1
appVersion: 2.152
description: The chart deploys a Jenkins Master and an dynamic agent nodes.
icon: https://wiki.jenkins-ci.org/download/attachments/2916393/logo.png
```

**Comment by andresmgot** [comment]
Hi @LP0101,

The problem is that the version should be semver compatible: https://semver.org/

It should work for you if you change the version 1.1 -> 1.1.0. 

In any case, that should not make the application crash so this is also a bug in our side.

**Comment by LP0101** [comment]
That fixed it. Thanks!

**Comment by andresmgot** [comment]
I am glad that worked! Let me reopen this issue for us to fix the crash when a chart doesn't contain a semver compatible version.
