### ISSUE TITLE
Filtering UX improvements

### ISSUE THREAD

**Issue by m1small** [kubeapps/kubeapps#1012]
Following on from https://github.com/kubeapps/kubeapps/issues/580, it would be nice to be able to see a filter list for repositories and possibly other metadata/tags in the sidebar or top bar.

**Comment by lindhe** [comment]
I suggest something like this, to begin with:

![Modified Catalog page](https://user-images.githubusercontent.com/7773090/62620453-a8deb780-b919-11e9-91ea-d0b74e07f136.png)

**Comment by andresmgot** [comment]
The problem with that is that the number of repositories is limited by the width of the view. I would set a vertical menu like in https://hub.kubeapps.com/charts

**Comment by lindhe** [comment]
Oh, that's much better! This gets me a bit confused. Is hub.kubeapps.com not running the code found in this repo??

**Comment by andresmgot** [comment]
yes, they share some backend services but the frontends are different application.

**Comment by absoludity** [comment]
This is done in the new UI.
