### ISSUE TITLE
Please release windows binary

### ISSUE THREAD

**Issue by AceHack** [kubeapps/kubeapps#102]
I have kubeapps running in Ubuntu in WSL on windows but dashboard does not work.  I will need a real windows binary for that to work I'm guessing.

**Comment by ngtuna** [comment]
You can download latest build for windows at https://s3-ap-southeast-1.amazonaws.com/kubeapps/209/kubeapps-windows-amd64.exe

**Comment by ngtuna** [comment]
@AceHack You have the windows binary now in v0.2.0 https://github.com/kubeapps/kubeapps/releases/tag/v0.2.0
