### ISSUE TITLE
Where can I download CI builds?

### ISSUE THREAD

**Issue by AceHack** [kubeapps/kubeapps#103]

**Comment by ngtuna** [comment]
@AceHack The latest build is at:
https://s3-ap-southeast-1.amazonaws.com/kubeapps/209/kubeapps-darwin-amd64
https://s3-ap-southeast-1.amazonaws.com/kubeapps/209/kubeapps-linux-amd64
https://s3-ap-southeast-1.amazonaws.com/kubeapps/209/kubeapps-windows-amd64.exe

**Comment by ngtuna** [comment]
@AceHack PR #104 gives the URLs for downloading the binaries

**Comment by ngtuna** [comment]
I hope the links work for you. Will close this issue now and please reopen it for any further problem with that.
