### ISSUE TITLE
Chart incompatible with Tiller v2.14.0-rc.2

### ISSUE THREAD

**Issue by mickengland** [kubeapps/kubeapps#1031]
Can't install kubeapps running latest tiller version on EKS:

```
$ helm install --name kubeapps --namespace kubeapps bitnami/kubeapps
```
Error: Chart incompatible with Tiller v2.14.0-rc.2

```
$ helm version
```
Client: &version.Version{SemVer:"v2.14.0-rc.2", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.0-rc.2", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}

Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-eks-d69f1b", GitCommit:"d69f1bf3669bf00b7f4a758e978e0e7a1e3a68f7", GitTreeState:"clean", BuildDate:"2019-02-28T20:26:10Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

**Comment by andresmgot** [comment]
hi @mickengland,

This seems to be a bug in the `helm` CLI. Kubeapps requests a `tillerVersion: ">=2.10.0"`. Apparently that doesn't work with pre-releases. I recommend you to use the latest version stable of helm: `v2.13.1`.

**Comment by mickengland** [comment]
That seems to have worked. Thanks.
