### ISSUE TITLE
display update of chart and update of application 

### ISSUE THREAD

**Issue by obeyler** [kubeapps/kubeapps#1039]
New feature proposal:
Add a distinction between helm chart change and application change (and the degree of changement). I propose also that color of update ribbon notification give indication of changment level. According the classic rule 0.0.0:
First digit is major update, Second is minor update, Third is patch update 
the color could relect this level
An option could also propose to user to be only notified for application update

**Comment by andresmgot** [comment]
hi @obeyler,

I agree that distinguishing between app and chart updates will be helpful. The main problem is that applications don't have to follow semver conventions (0.0.0) so we cannot compare versions nor know if a versions is newer than the other. For example:

https://github.com/helm/charts/blob/master/stable/aerospike/Chart.yaml#L2

What we can do is compare chart versions (that should follow the semver versioning) and assume that if a chart version is greater and the app version changes, it means that the new app version is newer.

WDYT @prydonius?

**Comment by obeyler** [comment]
may the scan of the name of image can also be helpfull

**Comment by andresmgot** [comment]
@obeyler @prydonius what do you think about implementing the above and change the color of the banner (and the text) in case there is an update for the application?

![Screenshot from 2019-06-18 13-39-05](https://user-images.githubusercontent.com/4025665/59679637-a68c9680-91cf-11e9-864e-007d371d5bfe.png)

![Screenshot from 2019-06-18 13-46-44](https://user-images.githubusercontent.com/4025665/59679640-ab514a80-91cf-11e9-8684-4dabbdce0749.png)

**Comment by obeyler** [comment]
Great !!! :+1:

**Comment by prydonius** [comment]
I think we might need some UX guidance here (@Angelmmiguel, friendly ping), as we need to ensure that the wording and colours we use here are not confusing. Right now, I'm not sure what is more important (blue vs. green, both generally neutral colours).

Perhaps it might be better to only show the banner for new application versions and a smaller callout for new chart versions.

**Comment by andresmgot** [comment]
Since we have the text in the banner I think it's clear enough but we can wait for Angel's feedback (he is out of the office this week).

**Comment by prydonius** [comment]
I'm not sure that text is that useful if you have no idea what an App Version is. I would hold back for some more guidance here.

**Comment by Angelmmiguel** [comment]
Hi, 

First of all, thanks @obeyler for the suggestion! 

About the changes, I believe we shouldn't associate a color palette to this call to action. All of these notifications are under the same context: "There's an update for your deployment". Changing the color depending on the "type" of update is not trivial to understand. Also, I agree with @prydonius that "Chart update" and "App update" may be confusing for users are not used to those names. 

I'd keep this as simple as we can. I agree the current message doesn't include the app version update. What do you think about updating the current call to action to "Update available"? In the deployment view we can provide more information about the current state and the new versions.

On the other hand, I might miss something but a change in the application version implies an update in the chart version, am I wrong? If this is the case, we can display a single "update section" with all the  information about the new version (app and chart).

What do you think?

I hope it helps :)

**Comment by andresmgot** [comment]
Thanks for the feedback @Angelmmiguel.

One of the goals of this issue is to be able to differ between app updates and chart updates because people may not be interested in upgrading just because there is a new version of the chart (that may include just a minor change in the chart values). If we set the same message "Update available" for both cases, users won't be able to notice the difference.

If we want to leave that with a single message, what we can do in the app list is set the banner only if there is a new app version. Then in the app view we can give more information as you suggest in a update section.

Does that make sense?

**Comment by obeyler** [comment]
Hyp 0 : the deployment of an application XX.v0x with chart XX.v0y don't  works in my current context, if there is a new version of chart with I should want to test the chart (even if the app doesn't change).

Hyp 1 : the deployment of an application XX.v0x with chart XX.v0y  works well in my current context, in case of a new version of chart but no new application version => I can ignore the chart 

hyp 2 : The application version change, (and so on also the chart version) if I want the new functionnality or bug fix , I'll apply the new chart and have to check deeply all value.yml

**Comment by prydonius** [comment]
> If we want to leave that with a single message, what we can do in the app list is set the banner only if there is a new app version. Then in the app view we can give more information as you suggest in a update section.

This sounds reasonable to me, but unfortunately doesn't cover @obeyler's Hyp 0 case. I agree with @Angelmmiguel that this needs to be simple (and also not confusing for less advanced users).

It sounds like this comes down to a question of the importance of the update. We can assume that a new app version + chart version is more important than just a chart version. Though note that this can be a problematic assumption to make, especially if a new chart version contains a critical security vulnerability fix.

**Comment by andresmgot** [comment]
> It sounds like this comes down to a question of the importance of the update. We can assume that a new app version + chart version is more important than just a chart version. Though note that this can be a problematic assumption to make, especially if a new chart version contains a critical security vulnerability fix.

That's a fair point.

My only concern with changing the message to just "Update available" is that use case in which:

 - A user sees that there is a new update available.
 - They click on it and it's a minor chart upgrade, they decide not to upgrade.
 - A new update becomes available but the user ignores it thinking it was the same update they already saw.

To avoid that we could add the possibility of removing the banner for an upgrade (storing that in the browser) but it's probably out of the scope for this issue?

For the moment it seems that having a generic banner plus a detailed update info in the App view satisfies the different uses cases.

**Comment by Angelmmiguel** [comment]
> A new update becomes available but the user ignores it thinking it was the same update they already saw.

You're totally right @andresmgot. I've a question, do we have a way to identify the "priority / importance" of an update? Priorities can be associated to colors + icons (for color accessibility) easily. For example:

* Alert icon + red: critical vulnerability
* Alert icon + yellow: vulnerability
* Arrow up icon + green: new app or chart version. More details in the App view.

> For the moment it seems that having a generic banner plus a detailed update info in the App view satisfies the different uses cases.

I think this solutions is fine for now and we can continue discussing about it :)

**Comment by prydonius** [comment]
We unfortunately don't have a way to determine if an update has a security vulnerability.

**Comment by obeyler** [comment]
In fact the first proposal of andre to change the wording of the banner : chart update or appli update could be an interresting first step.
every body knows that an appli update = chart+appli update
at the user know directly the main useful information, chart or appli update and do what he has to do in regards of his context.

**Comment by andresmgot** [comment]
> every body knows that an appli update = chart+appli update

That's what we don't know for sure if it will be true. Some basic user may not know the different between those two, or maybe the chart maintainers decide not to use the `appVersion` field of the Chart.yaml at all, which would mean that a chart update may include an app version update.

I still think that being explicit in the banner text is harmless though (and may be useful). If we say "A new app version v1.2.3 is available" it implies that there is an "Update available" regardless of the user knowledge of what is an app version or a chart version.

**Comment by Angelmmiguel** [comment]
> > every body knows that an appli update = chart+appli update
>
> That's what we don't know for sure if it will be true. Some basic user may not know the different between those two, or maybe the chart maintainers decide not to use the appVersion field of the Chart.yaml at all, which would mean that a chart update may include an app version update.

Actually, I believe this specific topic is still very confusing for people that start working with Helm. People tend to think the `Chart Version === App Version`.

> I still think that being explicit in the banner text is harmless though (and may be useful). If we say "A new app version v1.2.3 is available" it implies that there is an "Update available" regardless of the user knowledge of what is an app version or a chart version.

I'm fine with this if we add more context in the App View. We need to reinforce this idea. As you mentioned before the `appVersion` may not be used by chart maintainers. So, a `chart` update may include an `app` update. That's the reason I believe we should add more context about what `appVersion` and `chartVersion` means 😄

**Comment by andresmgot** [comment]
Okay, so let's add the message "Update available" in the list view (since we don't have space to give a long explanation) and add more details about the update in the app view.

**Comment by andresmgot** [comment]
so @Angelmmiguel @obeyler what do you think about these screenshots. In this situation `bran-basket` has a new chart update (with the same app version) and `gigantic-fiction` has a new app version available (`crazy-umbrella` is up to date):

App list:

![Screenshot from 2019-07-01 17-33-18](https://user-images.githubusercontent.com/4025665/60448919-d9e71080-9c26-11e9-8808-0cccb54d87b1.png)

App view:

![Screenshot from 2019-07-01 17-32-08](https://user-images.githubusercontent.com/4025665/60448970-f5eab200-9c26-11e9-96f5-70814e353835.png)
![Screenshot from 2019-07-01 17-32-40](https://user-images.githubusercontent.com/4025665/60448969-f5521b80-9c26-11e9-9d86-8da31e6091e9.png)

**Comment by prydonius** [comment]
@andresmgot this looks great! I think for the app list view we can consider having a tooltip/popover that contains the update information displayed in the app view, but for now this is fine.

**Comment by obeyler** [comment]
good job but to my part I just regret that in the app list I can't see if it just a chart or app update in the banner

**Comment by obeyler** [comment]
update available /update app available

**Comment by Angelmmiguel** [comment]
@andresmgot it looks nice! It would be nice to highlight the update information inside the `AppView` but it can be done in a separate task.

> good job but to my part I just regret that in the app list I can't see if it just a chart or app update in the banner

Thanks for your thoughts @obeyler. For now, I believe it's better to keep the UI as simple as it's possible. Some concepts are a bit confusing for new / non-experienced users and they're not even used widely. 

However, we will consider your feedback. This approach may change in the future if we find it's a common requirement :)
