### ISSUE TITLE
Error in setting up local development server for dashboard

### ISSUE THREAD

**Issue by SachinMaharana** [kubeapps/kubeapps#1048]
I am setting up the local development server for contributing and facing issues.
https://github.com/kubeapps/kubeapps/blob/master/docs/developer/dashboard.md

Kubeapps Deployed:

```
apprepo-sync-bitnami-6ljnk-bfp75                                  0/1     Completed   1          5m4s
apprepo-sync-incubator-gzjkq-sv4pf                                0/1     Completed   1          5m4s
apprepo-sync-stable-vdf49-pdggf                                   0/1     Completed   1          5m4s
apprepo-sync-svc-cat-9vkqz-g24xz                                  0/1     Completed   1          5m4s
kubeapps-f6c656b47-9zvmx                                          0/1     Running     0          5m9s
kubeapps-f6c656b47-tmj8w                                          0/1     Running     0          5m8s
kubeapps-internal-0ec2a2e49ec542fb86cce75070e99292-69d44ccppqgw   1/1     Running     0          53m
kubeapps-internal-1ecb76662c13479bbea64a976b398af4-6847d68k5lpk   1/1     Running     0          52m
kubeapps-internal-2e143dca78ce4e0cbc98decf81919d26-6dbc67dmjgwx   1/1     Running     0          2m41s
kubeapps-internal-3cd1c9bdc1cd40de90ac0ba6a4b8cb4b-55594fcx66tp   1/1     Running     0          15m
kubeapps-internal-92e9d1d5b42242bb870e52f7862f359f-7d56db8z7sc8   1/1     Running     0          74m
kubeapps-internal-apprepository-controller-5745b8d868-rgwkd       1/1     Running     0          5m9s
kubeapps-internal-chartsvc-569c887659-m5z48                       1/1     Running     1          5m8s
kubeapps-internal-chartsvc-569c887659-thg8b                       1/1     Running     1          5m9s
kubeapps-internal-tiller-proxy-54f4df678b-vct4j                   1/1     Running     0          5m8s
kubeapps-internal-tiller-proxy-54f4df678b-xfmwv                   1/1     Running     0          5m8s
kubeapps-mongodb-89c57f6f9-crnx2                                  1/1     Running     0          5m9s
```

telepresence --namespace kubeapps --method inject-tcp --swap-deployment kubeapps-internal-dashboard --expose 3000:8080 --run-shell

on yarn run start i am getting the following error:
```
Starting the development server...

ts-loader: Using typescript@3.0.3 and /home/sachin/go/src/github.com/kubeapps/kubeapps/dashboard/tsconfig.json
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with signal "SIGTERM".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "start-js" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
echo $POD_NAME   
kubeapps-f6c656b47-9zvmx

Is there any other setup that i am missing. Any help would be greatly appreciated.

UPDATE:

I tried with vpn-tcp method in telepresense command.

 telepresence --namespace kubeapps --method vpn-tcp --swap-deployment kubeapps-internal-dashboard --expose 3000:8080 --run-shell

Even though the dashboard is being served in localhost:3000, the charts tab provides no data.

xhr.js:172 GET http://localhost:3000/api/kube/api/v1/namespaces 404 (Not Found)
xhr.js:172 GET http://localhost:3000/api/tiller-deploy/v1/namespaces/default/releases 404 (Not Found)
:3000/#/apps/ns/default:1 Error while trying to use the following icon from the Manifest: http://localhost:3000/favicon.ico (Resource size is not correct - typo in the Manifest?)
xhr.js:172 GET http://localhost:3000/api/chartsvc/v1/charts 404 (Not Found)

I assumed it would be connecting to mongodb through telepresence.

**Comment by andresmgot** [comment]
Hi @SachinMaharana,

Have you installed the NPM dependencies before running `yarn run start`? It should be enough running `yarn` prior to start the server.

What I personaly do (in a linux laptop) is to run `telepresence` in one window and then, in a different one, I run `TELEPRESENCE_CONTAINER_NAMESPACE=kubeapps yarn run start`. The environment variable `TELEPRESENCE_CONTAINER_NAMESPACE` is needed to avoid the `404` errors that you are seeing.

**Comment by SachinMaharana** [comment]
Hi @andresmgot ,
Thanks for the reply.

I have followed the revised steps you have mentioned and am still unsuccessful.

```
(⎈ |devops24:default)➜  dashboard git:(master) yarn install
yarn install v1.16.0
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.90s.
```
Then i ran telepresence command.

`telepresence --namespace kubeapps --method inject-tcp --swap-deployment kubeapps-internal-dashboard --expose 3000:8080 --run-shell`

```
(⎈ |devops24:default)➜  dashboard git:(master) telepresence --namespace kubeapps --method inject-tcp --swap-deployment kubeapps-internal-dashboard --expose 3000:8080 --run-shell

T: Starting proxy with method 'inject-tcp', which has the following limitations: Go programs, static binaries, suid programs, and 
T: custom DNS implementations are not supported. For a full list of method limitations see 
T: https://telepresence.io/reference/methods.html
T: Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.
T: Starting network proxy to cluster by swapping out Deployment kubeapps-internal-dashboard with a proxy
T: Forwarding remote port 8080 to local port 3000.

T: Setup complete. Launching your command.
@gke_rugged-feat-237113_us-east1_devops24|bash-5.0$ 
```

I tried two things:
Running in the same telepresence command prompt

`@gke_rugged-feat-237113_us-east1_devops24|bash-5.0$ TELEPRESENCE_CONTAINER_NAMESPACE=kubeapps yarn run start`

Here i have 404 error.

And just like you have mentioned, i opened a diff terminal
(⎈ |devops24:default)➜  dashboard git:(master) TELEPRESENCE_CONTAINER_NAMESPACE=kubeapps yarn run start

Here also i am seeing 404  error with call to api.
In this case i see the env on telepresnce prompt.
```
@ devops24|bash-5.0$ env | grep TELEPRESENCE
TELEPRESENCE_MOUNTS=/app/config.json:/opt/bitnami/nginx/conf/server_blocks:/var/run/secrets/kubernetes.io/serviceaccount
TELEPRESENCE_ROOT=/tmp/tel-q8mx2ewr/fs
TELEPRESENCE_POD=kubeapps-internal-deb523f531b04f629c660f9b6d886a8b-74bc5fbzw7rh
TELEPRESENCE_CONTAINER=dashboard
TELEPRESENCE_CONTAINER_NAMESPACE=kubeapps
```
Is the workflow right?

**Comment by andresmgot** [comment]
@SachinMaharana it's not clear for me if `TELEPRESENCE_CONTAINER_NAMESPACE=kubeapps yarn run start` actually starts the server for you. Does it crash or it keeps running?

When you say you receive a `404`, where are you seeing it, in the web browser console? How are you accessing Kubeapps with an ingress or a service?

**Comment by SachinMaharana** [comment]
@andresmgot it keeps running. Like project is compiled and shows its running on localhost 3000. In browser I open localhost:3000. And I can access the dashboard bit with 404 messages.

**Comment by andresmgot** [comment]
I see, that's the problem. You need to access Kubeapps using the Kubernetes service in order to be properly redirected to the Kubernetes API and other services (you cannot use `localhost:3000`).

I am using an Ingress because it's easier for me but you can access the dashboard with any other mechanism like using a a port-forward (as explained in the getting started guide) or exposing the service as a LoadBalancer. That should fix the `404` errors.

**Comment by prydonius** [comment]
To add some more context, what's running on localhost:3000 is just the development server for the frontend app. By itself, this doesn't have access to the API services it needs to talk to. When you access Kubeapps through the `kubeapps` Service or through an Ingress pointing to the `kubeapps` Service, it acts as a reverse proxy to the API services so the frontend is able to talk to them.

With Telepresence, we can replace the `kubeapps-internal-dashboard` Deployment with the local development server, so that when you access the `kubeapps` Service, it reverse proxies to the local development server instead of the originally deployed dashboard, whilst still providing access to all the API services.

Does that make more sense?

**Comment by SachinMaharana** [comment]
@andresmgot @prydonius Thanks. I could run it now. Definitely, my lack of hands-on with Telepresence prevented me figuring it out. Thanks for the patience. :)

**Comment by prydonius** [comment]
@SachinMaharana no worries, it's definitely a confusing development environment, and we could probably improve the documentation to make it a bit clearer. Telepresence does make developing Kubeapps a lot more rapid, though!
