### ISSUE TITLE
Dev looking to help

### ISSUE THREAD

**Issue by AceHack** [kubeapps/kubeapps#106]
Not sure where to post this, I don't see a slack or anything.  Windows and visual studio/vscode are my primary development envrionments.  I've use a lot of others like xcode, eclipse, and a bunch of others over my 20 years of programming.  I've also have pretty deep knowledge of many orchestrators including K8s, swarm, and Service Fabric, tons of container experience as well.  I triple boot Windows, Mac, and Linux so I can build and test in any enviornment.  I also have access to a lot of Azure resources such as AKS (Managed Kubernetes on Azure), I can pretty much test out anything needed in that environement and cover the costs.  I would really love to help on this project if your interested, this seems like a great project.

Thanks.

**Comment by prydonius** [comment]
@AceHack it would be awesome to have you involved!! Things are a little quiet over the holiday period, but perhaps setting up a developer call and slack channel for Kubeapps in the new year will be a good way to start.

cc @sebgoa @arapulido

**Comment by prydonius** [comment]
@AceHack feel free to reach out on the Kubeapps channel in the Kubernetes slack if you're interested in getting more involved!
