### ISSUE TITLE
A token of a SA with cluster-admin cannot be used to access web UI in openshift 3.11

### ISSUE THREAD

**Issue by BIAOXYZ** [kubeapps/kubeapps#1065]
# Section 1

In my openshift 3.11 cluster in a CentOS virtual machine, I used the following commands to install kubeapps: 
```
wget https://get.helm.sh/helm-v2.14.1-linux-amd64.tar.gz
tar -xvf helm-v2.14.1-linux-amd64.tar.gz
mv linux-amd64/helm /usr/local/bin/

kubectl create serviceaccount tiller --namespace kube-system
kubectl create clusterrolebinding tiller-clusterrolebinding --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
helm init --service-account tiller

helm repo update
helm repo add bitnami https://charts.bitnami.com/bitnami

helm install --name kubeapps --namespace kubeapps bitnami/kubeapps --set frontend.service.type=NodePort

kubectl get secret -n kube-system $(kubectl get serviceaccount tiller -n kube-system -o jsonpath='{.secrets[].name}') -o jsonpath='{.data.token}' | base64 --decode | tee secret
```

Then I can successfully open the web UI of kubeapps in my windows chrome explorer. But use the secret obtained from the last step, I got the following prompt message:

![image](https://user-images.githubusercontent.com/6740021/60166407-b3466580-9833-11e9-948b-5755020e3206.png)

# Section 2

Actually, you can easily reproduce this issue in an online environment: open this [url](https://www.katacoda.com/openshift/courses/playgrounds/openshift311), and use the commands in Section 1. But when I use an online k8s cluster (I do not have local k8s except the openshift 3.11 cluster), this issue will not appear.

**Comment by andresmgot** [comment]
Hi @BIAOXYZ,

Unfortunately Openshift is not a supported platform (yet). We gathered the problems we faced in this issue: https://github.com/kubeapps/kubeapps/issues/676

**Comment by BIAOXYZ** [comment]
@andresmgot OK, then this issue can be closed, thanks.
