### ISSUE TITLE
Support switching between catalogs via changing URL

### ISSUE THREAD

**Issue by wojciechka** [kubeapps/kubeapps#1066]
To reproduce:

- Go to http://127.0.0.1:8080/#/catalog/bitnami
- Go to http://127.0.0.1:8080/#/catalog/stable (i.e. by editing link)

Another way to reproduce it is to edit the HTML (editing the page in the browser or by customizing Kubeapps dashboard image) to replace the top nav menu - such as:

```
<ul class="header__nav__menu" role="menubar">
<li><a class="header__nav__menu__item" href="#/catalog/bitnami">Bitnami Catalog</a></li>
<li><a class="header__nav__menu__item" href="#/catalog/stable" target=>Stable Catalog</a></li>
</ul>
```

Then clicking between the two links will not trigger a refresh.

A workaround is to add something like `onClick="setTimeout(location.reload.bind(location), 100)"` to force a refresh, but it is suboptimal as it reloads the entire application.

**Comment by andresmgot** [comment]
Thanks for filling the issue @wojciechka. I am able to reproduce the issue, it's needed to refresh the page to see the changes.
