### ISSUE TITLE
Document how to use Harbor with Kubeapps

### ISSUE THREAD

**Issue by andresmgot** [kubeapps/kubeapps#1069]
Our docs to set up a private Helm registry with Kubeapps cover Chartmuseum and Artifactory. We can include how to install and use Harbor as Helm registry as well.

The source is here:

https://github.com/kubeapps/kubeapps/blob/master/docs/user/private-app-repository.md

**Comment by SachinMaharana** [comment]
Can this be assigned to me? I would  like to give this a shot.

**Comment by jessehu** [comment]
Thanks @SachinMaharana. I discussed with @andresmgot to open this issue and currently works in progress. Please also help review the patch later.
