### ISSUE TITLE
Consider allowing editing values.yaml i.e. configuration during deployment

### ISSUE THREAD

**Issue by AceHack** [kubeapps/kubeapps#107]
It would be great to allow this during initial deployment and even updating after deployment.  I would also like to be able to define the name too so I don't get the random names.

Thanks.

**Comment by ngtuna** [comment]
@AceHack you can execute `kubeapps up --dry-run -o yaml` to extract the yaml manifest of Kubeapps, `-o json` is accepted as well. Then you can edit the manifest and deploy via `kubectl`.

**Comment by AceHack** [comment]
Sorry I didn't explain fully, it's not the customization of kubeapps, when I deploy say cockroachdb through kubeapps, I want to be able to fully customize the coackroachdb values.

**Comment by ngtuna** [comment]
Not sure if I understand you correctly but It's deployed and configured via Helm, not Kubeapps. For example with cockroachdb, if you want to configure it, seeking to the `configuration` section at https://hub.kubeapps.com/charts/stable/cockroachdb.

cc/ @prydonius

**Comment by prydonius** [comment]
Thanks for the suggestion @AceHack, this is definitely on the roadmap. The first step would be to add a textbox to paste in a raw values.yaml file, in the future we should look towards creating a form from the values.

**Comment by prydonius** [comment]
@AceHack this is now available as of 0.3.0! I'll close this, but feel free to open more issues if you have any problems or questions!
