### ISSUE TITLE
Reduce time between chart repo syncs

### ISSUE THREAD

**Issue by andresmgot** [kubeapps/kubeapps#1070]
The default time to sync chart registries is every hour. This mean that without refreshing the repository manually, a new version/chart can be missing for this hour gap.

We can reduce the frequency of the CronJob to run it every minute but the `chart-repo` job is a bit slow (around 30s for the stable repository). To achieve that we can store the checksum of the repository in the database and only run the heavyweight logic (parse the repository, download the logos, update the database...) if the content of the repository has changed.

**Comment by prydonius** [comment]
It would be good if the last update time could be exposed in the Kubeapps UI too, but the current implementation in https://github.com/helm/monocular/pull/637 would mean we'd need to call the chartsvc API. We should consider how we can extract this and store this info in the status spec of the AppRepository CRD.

**Comment by andresmgot** [comment]
That's a good point, we could use an annotation for that but since the information about the synchronization is already in the database it feels like that's a good place to set this too.

We can reevaluate that in the future, if we refresh it every minute that information may not be that valuable.

**Comment by prydonius** [comment]
Rather than using an annotation, we should make use of the status spec in the CR, as it is for these sorts of usecases.

> if we refresh it every minute that information may not be that valuable.

Are we planning on doing refreshes every minute? That seems way too fast?

**Comment by andresmgot** [comment]
> Are we planning on doing refreshes every minute? That seems way too fast?

That's my goal with https://github.com/helm/monocular/pull/637. Now that it doesn't process everything with each execution, in most of the cases it will do nothing. In case there is an update we will get it in less than a minute. 

Do you see a problem with that approach?

**Comment by prydonius** [comment]
I feel like I'm missing some context, what's the motivation behind changing this to every minute? Have we heard from users that we need this kind of frequency?

This means we'll spin up Pods to run every minute, what happens if a Pod is already running, or is in the middle of a sync?

What about the potential for hitting the rate limits of repository servers if we're hitting index.yaml every minute?

If we're refreshing every minute, the manual refresh button becomes a lot less useful, does it make sense to remove it?

**Comment by andresmgot** [comment]
> I feel like I'm missing some context, what's the motivation behind changing this to every minute? Have we heard from users that we need this kind of frequency?

Yes, this comes from people using private registries. The issue is that when you upload a chart to your registry (either manual or automatically) you may need to wait less than an hour to see the changes in Kubeapps without interaction. In other case you need to know that you need to manually refresh the repository.

> This means we'll spin up Pods to run every minute, what happens if a Pod is already running, or is in the middle of a sync?

We can set the `concurrencyPolicy` to `forbid` to avoid that. In any case it wouldn't cause any harm, both pods would update the database with the same information.

> What about the potential for hitting the rate limits of repository servers if we're hitting index.yaml every minute?

A request a minute doesn't seem a lot and the repository servers can cache the response. Not sure if that may be a problem TBH (or how we can check that).

> If we're refreshing every minute, the manual refresh button becomes a lot less useful, does it make sense to remove it?

It does, yes, we can probably remove it but it doesn't harm to leave it there for a while in case we want to go back and refresh in longer periods.

**Comment by prydonius** [comment]
> Yes, this comes from people using private registries. The issue is that when you upload a chart to your registry (either manual or automatically) you may need to wait less than an hour to see the changes in Kubeapps without interaction. In other case you need to know that you need to manually refresh the repository.

Where have we received this feedback? Is reducing the time the right solution, perhaps we need to make manual refresh more obvious?

> A request a minute doesn't seem a lot and the repository servers can cache the response. Not sure if that may be a problem TBH (or how we can check that).

You are likely right, but let's look into the rate limits for GCS, S3 and GitHub pages at the very least.

**Comment by andresmgot** [comment]
> Where have we received this feedback? Is reducing the time the right solution, perhaps we need to make manual refresh more obvious?

I cannot locate the specific feedback but I've heard several times: "How often does Kubeapps syncs? How can I change that?" I know that manual refreshing is not hard, it's just that I think it's even better not having to interact at all to see changes.

In any case, to avoid concerns about exhausting resources in the servers, what we can do is to make the schedule actually configurable and make it one hour by default so when people add their own registries they can set that to every minute or something else. Would that make sense to you?

**Comment by prydonius** [comment]
> I know that manual refreshing is not hard, it's just that I think it's even better not having to interact at all to see changes.

Fair point, although it can be useful for debugging also.

> In any case, to avoid concerns about exhausting resources in the servers, what we can do is to make the schedule actually configurable and make it one hour by default so when people add their own registries they can set that to every minute or something else. Would that make sense to you?

I think making this configurable is important, but we can start with simply reducing the time and follow up with that later. In order to be a bit conservative though, I would consider a slightly larger refresh interval (e.g. 10m).

**Comment by andresmgot** [comment]
Let's go for the 10 minutes then for the moment and we can make this configurable in a different issue.
