### ISSUE TITLE
Can't Create Service Instances

### ISSUE THREAD

**Issue by vlerenc** [kubeapps/kubeapps#1082]
I have deployed Kubeapps v1.4.1 and registered the AWS and GCP service brokers. The catalog gets populated, but I can't create service instances with Kubeapps:

- When I try to create an AWS s3 service instance, I get: `no schema with key or ref "http://json-schema.org/draft-06/schema#"`
<img width="939" alt="Screenshot 2019-07-10 at 18 36 50" src="https://user-images.githubusercontent.com/4974203/60987390-cb44db80-a341-11e9-8cf6-ce23cfe27fa6.png">

- When I try to create a GCP cloud-storage service instance, I get: `no schema with key or ref "http://json-schema.org/draft-04/schema#"`
<img width="936" alt="Screenshot 2019-07-10 at 18 35 16" src="https://user-images.githubusercontent.com/4974203/60987408-d3048000-a341-11e9-8d0d-13b06f04a569.png">

Am I doing something wrong here or is `kubeapps` having an issue?

I can create service instances via `kubectl` just fine, so the broker is present, the service class/plan as well and when I create an instance (e.g. of class AWS s3), I see the bucket in AWS. So, that's alright. Service catalog is v0.2.1 and the AWS broker chart is v1.0.1.

**Comment by vlerenc** [comment]
It seems this is related to the check `if (!_this.props.noValidate) {` in the in `From.js` and if we set `noValidate` to `true` we get over it and we can create the service instances/bindings just fine. Can this parameter be also set from the outside with the `kubeapps` deployments?

**Comment by andresmgot** [comment]
Hi @vlerenc,

Thanks for the debug info! I have created an image setting `noValidate: true` in the form component. Can you give it a try? You can do it executing:

```
kubectl set image -n kubeapps deployment kubeapps-internal-dashboard dashboard=kubeapps/dashboard-ci:dev-2019-07-11T13-01-30-CEST
```

**Comment by vlerenc** [comment]
Great, works like a charm! Thank you!

That said, the code was in for a purpose, I guess. Am I the first to notice that? Was it added just lately?

In any case, `kubeapps` is awesome. Before that, I used `monocular` for some people/use cases (that are working visually), but `kubeapps` combines Helm chart repos with OSB, i.e. with one tool I get the remote black-box services as well as the local white-box services enabled. Exactly what I was looking for.

If I may, two questions:
- You depend on Tiller, so you do not use the Helm templating directly, I guess (I would have preferred that over Tiller and it's ugly port-forwarding). Will you switch to that or Helm 3 eventually?
- Your wiki page mentions "Connect Helm-based applications to external services with Service Catalog Bindings". What is meant with this? In general, you can do that of course, but is there some built-in support? I wouldn't know how/haven't seen anything.

**Comment by andresmgot** [comment]
Great, thanks for confirming. It seems that you are indeed the first one to notice that. Apparently the default when using `kubectl` is to avoid that validation so I am okay following that approach with Kubeapps.
