### ISSUE TITLE
Cannot update helm install/upgrade timeout when installing charts using kubeapps

### ISSUE THREAD

**Issue by agill17** [kubeapps/kubeapps#1090]
## What am I trying to do?
- Use kubeapps to install charts in a k8s cluster from internal/public helm repositories

## What issue am I running into?
- Not being able to override timeout when installing charts using kubeapps UI.
- This timeout flag: https://helm.sh/docs/using_helm/#helpful-options-for-install-upgrade-rollback

I think its a parameter option that you can pass in here
https://github.com/kubeapps/kubeapps/blob/master/pkg/proxy/proxy.go#L234
and in here
https://github.com/kubeapps/kubeapps/blob/master/pkg/proxy/proxy.go#L257

**Comment by andresmgot** [comment]
Thanks for the issue, can you tell us how to reproduce your issue? What's the timeout you are seeing?

I am asking that because you may be receiving a timeout at the ingress level (depending on the ingress controller you are using) or at the proxy level.

**Comment by agill17** [comment]
@andresmgot I have a chart internally that takes longer than the default 180 seconds to install. Therefore it fails.

**Comment by absoludity** [comment]
Are people imagining the `timeout` option being a config option of the Kubeapps installation (ie. the timeout used for all chart installs), or a per install/upgrade option (ie. a UI change, with extra options after the already-busy values.yml editor).

**Comment by agill17** [comment]
@absoludity I’d prefer a UI option for create/upgrade of helm releases

**Comment by andresmgot** [comment]
For technical reasons, for the moment, I would rather make it generic (for all charts). Right now I would make it configurable with an environment variable so users can change it using a field in the `values.yaml` file.
