### ISSUE TITLE
Login failure causes the UI to get stuck

### ISSUE THREAD

**Issue by migmartri** [kubeapps/kubeapps#1092]
There might be a regression in the login form in where instead of showing that the login was invalid it gets stuck in the loading screen

![Peek 2019-07-24 10-58](https://user-images.githubusercontent.com/24523/61816899-1eb72f00-ae02-11e9-925e-57d1e39ed31e.gif)

**Comment by andresmgot** [comment]
I can reproduce it. Yes, this seems like a regression.
