### ISSUE TITLE
When configmap change, pod not being recreated

### ISSUE THREAD

**Issue by lich1710** [kubeapps/kubeapps#1093]
**Issues:**
- Pod not being recreated when I changed the configmap content

**Setup:**
- I have a helm chart where configmap is mounted as a file to the pod.
- In the deployment manifest, I use auto regenerate new annotation everytime configmap changes. (Added timestamp as well) as below:
```
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configMap-env.yaml") . | sha256sum }}
    timestamp: {{ date "20060102150405" .Release.Time | quote }}
```

**Expectation**: 
- Pod is recreated when configmap change, follow the same behaviour when use helm cli to perform the upgrade.

May I know how to fix this?

**Comment by andresmgot** [comment]
Hi @lich1710,

How do you perform the upgrade of your chart? Do you have it uploaded to a private chart registry?

Are you able to upgrade but the annotations of the pods don't change?

**Comment by lich1710** [comment]
> Hi @lich1710,
> 
> How do you perform the upgrade of your chart? Do you have it uploaded to a private chart registry?
> 
> Are you able to upgrade but the annotations of the pods don't change?

Hi @andresmgot 

- Yes, we use chartmuseum as private chart registry
- I am able to finish the upgrade, the current pod is not recreated thus the annotation is not changed. But if I perform a manual pod deletion, the new pod created will have the updated annotation.

**Comment by andresmgot** [comment]
I see, thanks for the info, I will try to reproduce the issue and will get back to you we should be mimicking the same behavior than the `helm` cli.

**Comment by lich1710** [comment]
Hi @andresmgot,
I return to this topic and performed some tests recently. Turn out, for the pods to be recreated, `annotations` should be inside `spec.template` 
Now Kubeapps performs exactly as the helm cli. We can close this issue then.

**Comment by andresmgot** [comment]
I see, thanks for posting the solution @lich1710!
