### ISSUE TITLE
Usage with helm-secrets

### ISSUE THREAD

**Issue by MartijnZuijd** [kubeapps/kubeapps#1098]
I would like to use the (helm-secrets)[https://github.com/futuresimple/helm-secrets] plugin to encrypt secrets in my helm chart. I also use kubeapps to deploy my applications. 

According to (this)[https://github.com/futuresimple/helm-secrets#helm-wrapper] section you need to call a different call when upgrading/installing a chart 'helm secrets install' from cli.

My question is how do i integrate this with kubeapps? Or is this currently not possible.

**Comment by andresmgot** [comment]
Hi @MartijnZuijd,

Unfortunately it's not possible to use Helm plugins with Kubeapps right now. We contact Tiller directly to do these installations/upgrades so you cannot use this pre-processing. The only thing I can suggest is for you to configure Tiller to store release information as secrets as [recommended in the official docs](https://github.com/helm/helm/blob/master/docs/securing_installation.md#tillers-release-information) but that may not cover your use case.

**Comment by tvvignesh** [comment]
@andresmgot Coming back to this for helm 3. Not that there is no tiller with helm 3 is this doable with kubeapps? I see tools like Skaffold providing an option to do things like this (https://skaffold.dev/docs/references/yaml/#deploy-helm-releases-useHelmSecrets) so I guess the same can be implemented in kubeapps as well.

Just in case you would like a reference - https://github.com/GoogleContainerTools/skaffold/pull/1617

**Comment by andresmgot** [comment]
Hey, true, actually using secrets is now the default for Helm 3 so we can consider this _done_. There is not anything else to do :) (Let me know if you think otherwise)
