### ISSUE TITLE
Repo added from dashboard won't use proxy parameters

### ISSUE THREAD

**Issue by flofourcade** [kubeapps/kubeapps#1104]
Following #696, it appears that when one add a repo from the dashboard, the sync jobs won't use any proxy parameter

**Comment by Sharma-Rajat** [comment]
+1

**Comment by andresmgot** [comment]
It is now possible to set the proxy environment variables using the Dashboard. See:

https://github.com/kubeapps/kubeapps/pull/1085

Let us know if you find any issue doing that.
