### ISSUE TITLE
Can I sync apprepos manually?

### ISSUE THREAD

**Issue by duckzhouya** [kubeapps/kubeapps#1107]
The apprepos sync the job use a cronjob
And if the charts in the repo has changed, we need to wait for the time is up to sync the charts into the mongodb
I wonder if I can do the sync manually to enable the sync of the job in stead of waiting for the time of the cronjob, and this will much more precisely for us to sync with the chart repo.

**Comment by lindhe** [comment]
If I understand you correctly, the answer is yes. Go to Configuration > App Repositories and then click Refresh.

**Comment by duckzhouya** [comment]
Thanks lindhe, I am not very familier with kubeapps, This is a very convinent operation.Thank you for your kindly remind.
