### ISSUE TITLE
Improve Kubeapps frontend proxying of k8s API

### ISSUE THREAD

**Issue by absoludity** [kubeapps/kubeapps#1111]
Certain functionality of the Kubeapps dashboard such as listing namespaces, validating login tokens and checking progress of helm deployments, currently use the Kubernetes API directly. This was done by adding a proxy rule to the frontend nginx config which [proxies requests for `/api/kube` through to `https://kubernetes.default/`](https://github.com/kubeapps/kubeapps/blob/master/chart/kubeapps/templates/kubeapps-frontend-config.yaml#L34), exposing the complete k8s API on the same network used by the frontend (still subject to the configured RBAC rules). 

Though many k8s providers configure public access to the k8s API by default, Kubeapps should document that the k8s API is also exposed through the frontend to avoid possible misunderstandings from users. In the future it may be worth replacing this proxy rule with a small backend API service limited to the Kubeapps context with its focused requirements (checking a deployment progress, obtaining a list of namespaces etc.)

**Comment by absoludity** [comment]
A small backend API service would also allow the frontend client to avoid storing the k8s API token, but rather use an http-only cookie to identify itself with the backend which would include the auth header for the request to the k8s api.

**Comment by absoludity** [comment]
Adding [SSO to Kubeapps, if done together with the proxy impersonation](https://www.youtube.com/watch?v=p5x1btmD2Yw) which @migmartri demonstrated, should be further investigated as a potential fix for this issue also. With that solution, all requests to the K8s API would be routed via the impersonation proxy, with the default RBAC ensuring only accounts with the correct role bindings are able to execute the request.

**Comment by absoludity** [comment]
> A small backend API service would also allow the frontend client to avoid storing the k8s API token, but rather use an http-only cookie to identify itself with the backend which would include the auth header for the request to the k8s api.

The Kubernetes dashboard application solves this quite neatly in a small backend which is encrypting the user-token and returning a JWE (JSON Web Encryption) token as a cookie. This credential is for access to the backend only, and enables the backend to decrypt and access the k8s API with the users token, without requiring storing the token. The only storage required is for the backend's key (which is stored in a k8s secret and is rotatable).

**Comment by absoludity** [comment]
So it turns out that this is also solved by switching to use OpenID Connect for auth (via the auth-proxy) as verified in #1199, as long as we *don't* whitelist the api endpoints.

In this case the `auth-proxy` (oauth-proxy) encrypts the creds (both id_token and access_token) in a cookie, and requires the cookie for all requests so all k8s api requests require authenticating with the provider first, and the auth-proxy inserts the creds into the requests.

**Comment by andresmgot** [comment]
But the thing is that the API is still accessible, isn't it? We still may want to filter requests and only return resources related to applications.

**Comment by absoludity** [comment]
> But the thing is that the API is still accessible, isn't it?

Given that with #1199 you're no longer exposing the nginx frontend with the proxypass - instead only the `auth-proxy` is exposed (and it doesn't white-list the k8s api), so the k8s API is only accessible if you have authenticated - which includes requiring a certain email domain or membership in a specific group, otherwise you cannot even access the endpoint. If you are able to authenticate, the k8s API then can only be used within your own (possibly specific) RBAC policies. So having / finding / stealing a service account token for the cluster does not help you at all - it cannot be used.

Yes, the equivalent of stealing the authz cookie may be possible in some scenarious, but (a) browsers are very careful with http-only cookies (ie. not accessible via script), and it can be time-limited (unlike a service-account).

> We still may want to filter requests and only return resources related to applications.

Yep, the K8s dashboard doesn't do this via proxying, but adds explicit handlers for the endpoints they need in their backend... we could do the same, sending the k8s api routes via a backend which only exposes the resources we're interested in (this is what I meant in another conversation about transitioning tiller-proxy into a small backend as tiller is removed), or we could whitelist (not on the `auth-proxy` but the internal nginx frontend) to only pass requests for the endpoints needed (easier for now, and possible better if it mean we don't need a backend at all.

**Comment by andresmgot** [comment]
> you're no longer exposing the nginx frontend with the proxypass - instead only the auth-proxy is exposed (and it doesn't white-list the k8s api),

Oh yes, right, I forgot that the proxy was in front of the `frontend` (I don't know why I was thinking it was in front of the `dashboard`).

**Comment by absoludity** [comment]
Just verifying that this is now only an issue when *not* using an auth proxy in front of the frontend. The auth proxy ensures a user is authenticated before forwarding the request through to any api server of a cluster:

```
curl -I https://localhost/api/clusters/default
HTTP/2 403 
```

I'm closing this as we already stress now in the docs (both chart README as well as getting started) that k8s service token auth is for demo only.
