### ISSUE TITLE
UI clunkyness

### ISSUE THREAD

**Issue by davidkarlsen** [kubeapps/kubeapps#1114]
1. select a namespace, and an application already deployed in the namespace, click on the app.
2. select another namespace from the drop down, the message "Application xxx not found in the xyz namespace.

A better ux would be to go to applications for the chosen namespace IMO.

**Comment by andresmgot** [comment]
Yes, the namespace selector should not be global. See https://github.com/kubeapps/kubeapps/issues/598

We should fix this sooner than later but it requires some design.

**Comment by andresmgot** [comment]
Let me close this issue in favor of #598 Please, reopen it if you think we should treat them differently.
