### ISSUE TITLE
Regex in path gets included 

### ISSUE THREAD

**Issue by lindhe** [kubeapps/kubeapps#1120]
When using regex in the path, that too gets included.

![Screenshot from 2019-08-09 11-11-29](https://user-images.githubusercontent.com/7773090/62768145-86be7400-ba96-11e9-87aa-f7c95164fde8.png)

Migrated from #673

**Comment by andresmgot** [comment]
Thanks @lindhe, I guess the more user-friendly thing to do here is making the link not a link? What would be your desired user experience @lindhe?

**Comment by lindhe** [comment]
In the best of worlds, it would strip the regex and be a working link. But that's rather hard, I assume. Right now, I click it and manually remove the trailing characters from the address bar. I don't think it would be much more convenient to copy the correct part of a non-link string... I don't have a great suggestion in mind, if stripping the regex is hard. Will get back to you if I come up with something.

**Comment by andresmgot** [comment]
> In the best of worlds, it would strip the regex and be a working link. But that's rather hard, I assume.

I don't think that's something possible. From your example, just removing `(/|$)(.*)` would work but that's not something we can do generally (for example `foo/[a-z]+` would require to be resolved as `foo/a`).

I think the best we can do is at least not make it a link. That way, users would copy/paste as desired. Let us know anyway if you think of something else.

**Comment by lindhe** [comment]
I think that would make for a worse experience in some cases though, so I
would vouch for not changing anything in that case. As it is now, at least
the link works sometimes (and then it's really useful).

**Comment by andresmgot** [comment]
Well yes, I was thinking on disabling the link just when there is a regexp in the path, not disabling it for everything.

**Comment by lindhe** [comment]
Sure... Matching on special characters, or how would you determine that?

**Comment by andresmgot** [comment]
Yes. If the URL contains non valid characters --> disable the link

**Comment by lindhe** [comment]
Sounds fair. Might also catch other edge-cases we have not seen yet. I like it.

**Comment by antgamdia** [comment]
I have been thinking about this issue: we can consider the
[RFC-1738](https://www.ietf.org/rfc/rfc1738.txt) (URLs), updated by [RFC-3986](https://www.ietf.org/rfc/rfc3986.txt), and [RFC-2396](https://www.ietf.org/rfc/rfc2396.txt) (URIs) or also consider the [URL living standard](https://url.spec.whatwg.org/).

A first approach could be detecting the 'special' characters defined in the RFC:

```
delims      = "<" | ">" | "#" | "%" | <">
unwise      = "{" | "}" | "|" | "\" | "^" | "[" | "]" | "`"
reserved    = ";" | "/" | "?" | ":" | "@" | "&" | "=" | "+" | "$" | ","
```

Therefore getting a list of 'valid' characters (no need to % encode them): ```abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._~```

But with this approach, we will dropping valid URLs hosts like:

```
sub.example.إختبار  (translated to sub.example.xn--kgbechtv)
[2001:0db8:85a3:0000:0000:8a2e:0370:7334]
```

On the other hand, we could consider a more exhaustive approach as [this regex](https://rgxdb.com/r/5JXUI5A2) does. Perhaps it's using hammer to crack a nut...
What do you think? cc @andresmgot

**Comment by andresmgot** [comment]
Yes, it's true that with a regexp of that kind we would disable valid URLs. Trickier than expected :). In any case, let's go for the simpler solution, if some URL does not match (like `sub.example.إختبار`) we would be just removing the anchor, which is not big deal.

I think both options, either disabling the link if there is an unexpected character (I found a bigger list here: https://stackoverflow.com/questions/1547899/which-characters-make-a-url-invalid) or a regexp that checks if it's a valid URL (https://stackoverflow.com/questions/5717093/check-if-a-javascript-string-is-a-url). I would go for the second though since it's more complex, it's a pity that there is no an upstream method to do this.

**Comment by antgamdia** [comment]
Validating valid URLs is a thorny topic. Some regexs have plenty of false positives and negatives (see https://mathiasbynens.be/demo/url-regex). I finally came up with this one, which (IMHO) captures a majority of our expected cases. I'll open a PR soon; feel free to improve or correct it! 

`/^(https?:\/\/)?((([a-z\d]([a-z\d-]*[a-z\d])*)\.)+[a-z-]{2,}|((\d{1,3}\.){3}\d{1,3}))(:\d+)?(\/[-a-z\d%_.~+]*)*(\?[;&a-z\d%_.~+=-]*)?(#[-a-z\d_]*)?$/ig`

![image](https://user-images.githubusercontent.com/11535726/97547906-b248b980-19ce-11eb-912a-38f0d073425c.png)

**Comment by andresmgot** [comment]
:+1: go for it @antgamdia
