### ISSUE TITLE
ERRO[0000] error upgrading connection: unable to upgrade connection: pod not found

### ISSUE THREAD

**Issue by yangboz** [kubeapps/kubeapps#113]
After running kubeapps up,
"
NAMESPACE	NAME              	DESIRED	CURRENT
kubeless 	statefulsets/kafka	1      	1      
kubeless 	statefulsets/zoo  	1      	1      

NAMESPACE	NAME                                         	STATUS 
kubeapps 	pod/default-http-backend-786cc69958-47fdj    	Pending
kubeapps 	pod/kubeapps-dashboard-api-56fb98f459-f6dfd  	Pending
kubeapps 	pod/kubeapps-dashboard-ui-7685fdc9cf-pfprl   	Pending
kubeapps 	pod/kubeless-ui-587f9b9cfd-cwfz8             	Pending
kubeapps 	pod/mongodb-f55447769-m6tsn                  	Pending
kubeapps 	pod/nginx-ingress-controller-78db565655-l9qbt	Pending

You can run `kubectl get all --all-namespaces -l created-by=kubeapps` to check the status of the Kubeapps components. 
"
And: 
ERRO[0000] error upgrading connection: unable to upgrade connection: pod not found ("nginx-ingress-controller-78db565655-l9qbt_kubeapps")

**Comment by ngtuna** [comment]
@yangboz Which kubeapps version and kubernetes version/environment are you using ?

**Comment by yangboz** [comment]
OK,I will try to use kubernetes again.Thanks.

**Comment by ngtuna** [comment]
@yangboz feel free to open this issue again if you have more questions come
