### ISSUE TITLE
only connect to 127.0.0.1? how to access from external?

### ISSUE THREAD

**Issue by jinjie2088** [kubeapps/kubeapps#1138]
i used nodeport, get error:

Sorry! Something went wrong.
Troubleshooting:

Check for network issues.
Check your browser's JavaScript console for additional errors.
Check the health of Kubeapps components helm status <kubeapps_release_name>.
Open an issue on GitHub if you think you've encountered a bug.

**Comment by andresmgot** [comment]
Hi,

You should be able to access from outside the cluster if you use an Ingress rule. To do so you can install Kubeapps with the flag `--set ingress.enabled=true`. You can find more details of what you can configure in the `values.yaml` file.

Note that you can also set the front-end service as a `LoadBalancer` or a `NodePort` if you set it. For example `--set frontend.service.type=LoadBalancer` would do the trick.

**Comment by jinjie2088** [comment]
i used nginx for proxy, it works. thank you.
