### ISSUE TITLE
MongoDB is a single point of failure in default deploy

### ISSUE THREAD

**Issue by absoludity** [kubeapps/kubeapps#1142]
The current default deployment for the Kubeapps chart [explicitly avoids using persistence for MongoDB](https://github.com/kubeapps/kubeapps/blob/master/chart/kubeapps/values.yaml#L257) (see #336 for reasoning) and uses the default MongoDB chart setting for [`replicaSet: { enabled: false}`](https://github.com/helm/charts/blob/master/stable/mongodb/values.yaml#L146).

This leaves MongoDB as a single point of failure which requires time to rebuild if the pod is rescheduled (as found in #1141).

The assumption to this point seems to be that this service is a cache which does not require persistence (see #336), which may be true - but it *is* required to be available. We should investigate whether enabling the default Kubeapps deploy to use a replicaSet for this cache (whether or not we stay with MongoDB or switch to something lighter - see #651), so that it is no longer a single pod and single point of failure that quite seriously affects the user experience when rescheduled (which can happen for a variety of reasons, so needs to be handled gracefully for the user experience). We can also re-evaluate #336 to see whether persistence would improve the situation (but imo using replicasets should make persistence less useful for this cache, unless all pods went down).

**Comment by andresmgot** [comment]
I agree in the reasoning. However, there is a price to pay if we follow either of both approaches:

 - If we increase the number of replicas, there is a (high?) cost regarding resources consumption. MongoDB is already the resource that is taking more resources in our application. Making it double is not something we should do lightly.
 - If we attach a persistent volume, people will likely find again the issues that made us work in #336 (PVCs don't work out of the box in some kubernetes environments).

Another possibility can be caching data in the chartsvc. If MongoDB is down, we could work with the latest data received, setting a warning that this info may be out of date. In any case, if both MongoDB and the chartsvc get rescheduled, we will find the same issue. Also, the two replicas of the chartsvc may contain a different state.

I think that probably the easiest to implement with less impact for users is "reverting" #336 and have persistence in our MongoDB.

**Comment by absoludity** [comment]
> I agree in the reasoning. However, there is a price to pay if we follow either of both approaches:
> 
>     * If we increase the number of replicas, there is a (high?) cost regarding resources consumption. MongoDB is already the resource that is taking more resources in our application. Making it double is not something we should do lightly.

Yeah - but it's the same approach we'd take if we were already using Redis or something lighter, so it'd be a move in the right direction and perhaps raise the priority for using something lighter. But yep, needs some thought. 

> 
>     * If we attach a persistent volume, people will likely find again the issues that made us work in #336 (PVCs don't work out of the box in some kubernetes environments).

Plus I'm not sure it'd be necessary if we had a redundant replica by default (ie. one node could go down and the data would still be available, when the pod is rescheduled it should sync etc.
 
> Another possibility can be caching data in the chartsvc.

I feel like I'm falling down a rabbit hole at that point :P. A second-level cache? Personally think we should let the single cache / backend service handle the redundancy.

> If MongoDB is down, we could work with the latest data received, setting a warning that this info may be out of date. In any case, if both MongoDB and the chartsvc get rescheduled, we will find the same issue. Also, the two replicas of the chartsvc may contain a different state.

Right, that's a reason not to go down that path, I think? It's added complexity that should not be necessary.

> I think that probably the easiest to implement with less impact for users is "reverting" #336 and have persistence in our MongoDB.

That doesn't get rid of the single point of failure in the default deployment, but rather just means the downtime would be less (as once the pod was rescheduled, the data could be available), with the cost of the issues outlined there on #336.

**Comment by andresmgot** [comment]
> That doesn't get rid of the single point of failure in the default deployment, but rather just means the downtime would be less (as once the pod was rescheduled, the data could be available), with the cost of the issues outlined there on #336.

Right. Maybe we can just document the different approaches (since I think that is just a matter of enabling/disabling stuff in the chart). About the default I am not sure, the approach we have been following is "production" set up by default. So yes, maybe is better to pay the price of having replication.
