### ISSUE TITLE
bitnami/charts syncer tool should take latest image revisions

### ISSUE THREAD

**Issue by tompizmor** [kubeapps/kubeapps#1156]
Right now the bitnami/charts syncer script takes the latest kubeapps version and append `-r0` to form the bitnami component image tag. 
This image won't be updated again until the next version of kubeapps is released so it is possible that some CVE affects this image.

Instead of using this method to obtain the tag, we can check the latest release of the bitnami-component. For example, check https://github.com/bitnami/bitnami-docker-kubeapps-dashboard/releases to get the latest revision of the image released.

**Comment by andresmgot** [comment]
Thanks @tompizmor, we should be able to include that in the next release (we may need to rethink the approach). cc/ @absoludity
