### ISSUE TITLE
Error executing 'postInstallation': Group '2003' not found

### ISSUE THREAD

**Issue by WangSZ** [kubeapps/kubeapps#116]
Image is `bitnami/mongodb:3.4.9-r1`
After running `kubeapps up`, and mongodb doesn't work. 
The log is
```sh
Welcome to the Bitnami mongodb container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
Send us your feedback at containers@bitnami.com
 nami    INFO  Initializing mongodb
Error executing 'postInstallation': Group '2003' not found
```

**Comment by prydonius** [comment]
@WangSZ this is usually an issue with the volume type, which storage provisioner does your cluster use?

cc @sameersbn

**Comment by sameersbn** [comment]
@WangSZ Not sure what the group `2003` really is !? 
It would be helpful if you could describe your cluster setup.

**Comment by WangSZ** [comment]
@prydonius @sameersbn  StorageClass is glusterfs 3.12.4 with heketi-cli v5.0.1. The cluster is v1.8.3-rancher3 with RBAC on and the other config is default by Rancher V1.6.12. The 'group 2003' confused me too...

**Comment by ngtuna** [comment]
@WangSZ we think this is issue from glusterfs. Would you be able to try with another kind of StorageClass ? Right now we don't have much effort to work on glusterfs so I am afraid it can't be fixed soonly

**Comment by WangSZ** [comment]
@ngtuna  I'll try to update rancher2.0 later and try again .Thanks any way .
