### ISSUE TITLE
[chartsvc] Re-adding a chart registry causes its catalog view to be empty

### ISSUE THREAD

**Issue by andresmgot** [kubeapps/kubeapps#1161]
When deleting a chart registry, we are deleting from one MongoDB document all the entries but we are not deleting the cached hash of the registry so whenever the registry is re-added, the `hash` has not changed in the database so the population of the actual content is skipped.

**Comment by absoludity** [comment]
Just found this same issue today :) The logs of the first sync when re-adding the repo show:
```
$ k logs -n kubeapps apprepo-sync-chartmuseum2-bxk5j-x8ttv
time="2019-09-12T06:40:29Z" level=info msg="Skipping repository since there are no updates" url="https://mnelson-chartmuseum.k.dev.bitnami.net"
time="2019-09-12T06:40:29Z" level=info msg="Successfully added the chart repository chartmuseum2 to database"
```
