### ISSUE TITLE
Kubeapps shows "default" namespace if user cannot list namespaces

### ISSUE THREAD

**Issue by absoludity** [kubeapps/kubeapps#1162]
If a service account is created for a user in a specific namespace (and without permission to list namespaces), and the associated credential is used to login, the namespace switcher shows "default" rather than the specific namespace.

Kubeapps should default to the namespace of the service account rather than the "default" namespace which to which the user may not have access.

Ideally, kubeapps would remember the selected namespace so when returning (without re-authing) it remains selected.

**Comment by prydonius** [comment]
Thanks for creating this! Here is where we select the default namespace: https://github.com/kubeapps/kubeapps/blob/master/dashboard/src/reducers/namespace.ts#L13. We could instead try to read the Service Account token JWT claims to find out what namespace it belongs to and select that.

**Comment by absoludity** [comment]
Thanks @prydonius . Yep, that looks like the best way to go. I setup to reproduce the issue locally. Interestingly, not only do we show "default", but we also include "All namespaces" in the selector - which if you select it, shows you the releases across all namespaces (even though you can't view them individually, as the service account does not have perms).

I assume we should not be showing these. I'll check tiller-proxy - guessing we're not checking the request for releases across all namespaces correctly. Ideally, we'd not include "All namespaces" in the select if the user does not have relevant perms.

**Comment by prydonius** [comment]
Does it make sense to hide the "All namespaces" option? If a user doesn't have permissions, they'll see the permissions error page which will hint at what permissions they need to get from their administrator. IMO that can be useful, and also helps us avoid having to send a request to tiller-proxy to check if they have the permission.

**Comment by absoludity** [comment]
> Does it make sense to hide the "All namespaces" option? If a user doesn't have permissions, they'll see the permissions error page which will hint at what permissions they need to get from their administrator.

It seems odd to me to show something and error when selected for something for which you explicitly haven't been given permission. I agree it would be helpful for the case where your administrator has made a mistake, but following that through we could list all the other namespaces to which you don't have access?

> IMO that can be useful, and also helps us avoid having to send a request to tiller-proxy to check if they have the permission.

Won't we know without checking tiller-proxy? That is, the attempt to list namespaces is a 403 - so we could already only include `_all` if the request to list namespaces succeeded. I only mentioned tiller-proxy above because it appears to be giving access to something it shouldn't (ie. I can use my restricted token, which does not have RBAC to list namespaces, to contact tiller-proxy and get it to return all apps across namespaces).

I've created #1169 since it's not blocking this current change.

**Comment by prydonius** [comment]
> but following that through we could list all the other namespaces to which you don't have access?

This is actually the case if you have the permission to list all namespaces, but don't have permissions to read/deploy inside some namespaces.

It's going to be pretty difficult for us to only show namespaces that you can actually do stuff in. 

> Won't we know without checking tiller-proxy? That is, the attempt to list namespaces is a 403 - so we could already only include _all if the request to list namespaces succeeded. I only mentioned tiller-proxy above because it appears to be giving access to something it shouldn't (ie. I can use my restricted token, which does not have RBAC to list namespaces, to contact tiller-proxy and get it to return all apps across namespaces).

@andresmgot probably knows more, but I think this is because of a limitation in Helm, all releases can be "seen" using `helm list` as long as you have access to read the configmaps in the `kube-system` namespace.

**Comment by absoludity** [comment]
> This is actually the case if you have the permission to list all namespaces, but don't have permissions to read/deploy inside some namespaces.

If my account had been configured with RBAC rules so that I can list all namespaces but not read/deploy, then I guess I'd expect to be able to list namespaces and not read/deploy? But if my account has been configured so that I can't read all namespaces, it's seems odd that we (a) include it as an option, and (b) that it actually works (at least, to me). But ...

> @andresmgot probably knows more, but I think this is because of a limitation in Helm, all releases can be "seen" using helm list as long as you have access to read the configmaps in the kube-system namespace.

Yeah, that makes sense regarding why (b) works. I see I can enter any namespace I like in the switcher and view releases for that (because it's just reading the configmaps, as you say). And possibly it makes sense of (a) too - that we want to do what `helm list` does. So the `_all` option just supports the default behaviour of `helm list`. Thanks @prydonius , and yep, I'll check with Andres next week when he's back.

**Comment by absoludity** [comment]
Note that helm behaviour changes with helm 3, where the release info is stored in the namespace of the release.

**Comment by prydonius** [comment]
Indeed, Helm 3 provides for a much better multi-tenant experience.
