### ISSUE TITLE
Users without RBAC perms can view apps across all namespaces

### ISSUE THREAD

**Issue by absoludity** [kubeapps/kubeapps#1169]
Migrated from https://github.com/kubeapps/kubeapps/issues/1162#issuecomment-532066047 .

Steps to reproduce:

1. Create RBAC service account for user in one namespace only and login
2. Select "All Namespaces" in the namespace switcher

Actual result: helm releases across all namespaces are displayed, even though I am unable to list namespaces, nor see the details of an individual release (as I don't have perms).

Expected result: Either the "You don't have perms", or simply not including the `All Namespaces` option if the user doesn't have permission.

**Comment by andresmgot** [comment]
That's a bit tricky, how do you check if a user has permissions or not to list all releases? That will be fixed by Helm 3 though since the user will need permissions to get secrets in order to retrieve the existing releases.

**Comment by absoludity** [comment]
Closing this as it's a solved issue in Helm 3, and as above, default helm 2 behaviour.
