### ISSUE TITLE
Maintainer links on dashboard are broken

### ISSUE THREAD

**Issue by jetztgradnet** [kubeapps/kubeapps#117]
On the left of a single chart, a list of maintainers is shown with links to their Github account. The maintainers are shown with their name but the link is wrongly formatted to also contain the name instead of the Github username (i.e. https://github.com/Firstname%20Lastname instead of https://github.com/githubusername).

Example from Spark chart:
Maintainer: Lachlan Evenson
Link: https://github.com/Lachlan%20Evenson (which leads to a 404), should be https://github.com/lachie83 instead.

Possibly, this is simply incorrect meta data, searching for Lachlan, I can see some Charts.yaml with his Github user name, some with his firstname/lastname: 
https://github.com/kubernetes/charts/search?utf8=%E2%9C%93&q=Lachlan+Evenson&type=

**Comment by prydonius** [comment]
> Possibly, this is simply incorrect meta data

Indeed, some charts from the stable/incubator repos are still incorrectly using first name/last name in their metadata. Those charts and any other should be fixed, the dashboard for now just assumes all names are github ids.

I'm not sure if it's worth implementing a solution to check if it really is a GitHub ID, given eventually all charts should have switched to GitHub IDs.

**Comment by ngtuna** [comment]
Not sure if we can work on it in dashboard project. From kubeapps cli, it's out of scope

**Comment by jetztgradnet** [comment]
If this is purely driven by provided meta data I suggest closing this issue. 

I only noticed this by chance while clicking on one of the links and not getting to the intended target.

**Comment by prydonius** [comment]
@jetztgradnet agree that we should close this, I don't think it makes sense to work around it here, and should be fixed upstream in kubernetes/charts.

Thanks!
