### ISSUE TITLE
Invalid parameter: redirect_uri 

### ISSUE THREAD

**Issue by nevido** [kubeapps/kubeapps#1174]
helm fetch batnami/kubeapps
vi values.yaml
ingress : enable -> true
host: kubeapps.example.info

helm install -n kubeapps bitnami/kubeapps --namespace kubeapps --set authProxy.enabled=true --set authProxy.clientID=kubeapps --set authProxy.clientSecret=1xxxx-xxx-e11bd0dd2a28 --set authProxy.discoveryURL=http://iam.example.info/auth/realms/demo -f values.yaml

keycloak information

realms - demo
client: kubeapps
secretKEY: 1xxx-xxx-e~
Valid Redirect URIs : http://kubeapps.example.com

the result is Invalid parameter: redirect_uri

i don't know what the problem is..

**Comment by andresmgot** [comment]
Hi @nevido,

You have to configure your allowed redirect_uri in Keycloak. See https://stackoverflow.com/questions/45352880/keycloak-invalid-parameter-redirect-uri/50776053 for more details.
