### ISSUE TITLE
There was an error connecting to the Kubernetes API. Please check that your token is valid.

### ISSUE THREAD

**Issue by nevido** [kubeapps/kubeapps#1179]
kubeapps + keycloak + keycloak-gatekeeper
namespace: default
kubectl create serviceaccount kubeapps-operator
kubectl create clusterrolebinding kubeapps-operator --clusterrole=cluster-admin --serviceaccount=default:kubeapps-operator

kubectl get secret $(kubectl get serviceaccount kubeapps-operator -o jsonpath='{.secrets[].name}') -o jsonpath='{.data.token}' | base64 --decode && echo

 helm install -n kubeapps bitnami/kubeapps -n kubeapps

helm install gabibbo97/keycloak-gatekeeper --name kubeapps-sso --set discoveryURL=http://iam.example.info/auth/realms/test --set upstreamURL=http://kubeapps.default.svc.cluster.local:80 --set ClientID=kubeapps --set ClientSecret=1f86c580-357d-42c0-b6c8-e122bd0dd2a28 --set ingress.enabled=true --set ingress.hosts[0]=kubeapps.example.info

redirecct_url in keycloak : http://kubeapps.example.info/oauth/callback

when i was login via proxy(sso) i can see the this error on the deploy(kubectl logs -f deploy/kubeapps)

.5693269052716062e+09  info    client request  {"latency": 0.001522084, "status": 200, "bytes": 4626, "client_ip": "10.244.0.35:58636", "method": "GET", "path": "/static/media/logo.1ff453c0.svg"}
**1.5693269052942286e+09  error   no session found in request, redirecting for authorization      {"error": "failed to decrypt token"}**
1.5693269052943187e+09  info    client request  {"latency": 0.000097599, "status": 307, "bytes": 95, "client_ip": "10.244.0.35:58636", "method": "GET", "path": "/api/kube/"}
1.5693269053051789e+09  info    client request  {"latency": 0.000043499, "status": 307, "bytes": 293, "client_ip": "10.244.0.35:58636", "method": "GET", "path": "/oauth/author

and then

see the message on the web login site

![image](https://user-images.githubusercontent.com/25813260/65510633-68122080-df10-11e9-877d-f3c22112d2da.png)

i don't know the reason !!

**Comment by andresmgot** [comment]
Hi @nevido,

From your description is not clear to me that when you access Kubeapps, you are redirected to Keycloack, you introduce your credentials and finally, when redirected back to Kubeapps you see that error, right?

If that's the case, you can check the `Network` tab of your web browser. There you should be able to see a request to the path `kube/`. That request should contain the authorization header with your token:

![Screenshot from 2019-09-24 14-54-06](https://user-images.githubusercontent.com/4025665/65513398-7d208c80-dedb-11e9-9aa0-329e2d02a81a.png)

That's the token that you are trying to use to login. Can you check in https://jwt.io/ if that's a valid token?

Note that if you have accessed Kubeapps before, you will have a token stored in your cache. Can you confirm if the issue persists if you access Kubeapps in a incognito window?

**Comment by andresmgot** [comment]
Hi @nevido, were you able to fix the issue? What was the problem?

**Comment by nevido** [comment]
still not yet

i will try other way

나의 iPhone에서 보냄

2019. 9. 25. 오후 4:04, Andres Martinez Gotor <notifications@github.com> 작성:

**Comment by yug0slav** [comment]
Getting the same issue here with kubeapps behind keycloak-gatekeeper / keycloak.

Access to XMLHttpRequest at 'https://keycloak.mydomain.lab/auth/realms/kubeapps/protocol/openid-connect/auth?client_id=kubeapps&redirect_uri=https%3A%2F%2Fkubeapps.mydomain.lab%2Foauth%2Fcallback&response_type=code&scope=openid+email+profile&state=53b8f0c0-e606-47c4-9f4f-0b1748d64905' (redirected from 'https://kubeapps.mydomain.lab/api/kube/') from origin 'https://kubeapps.mydomain.lab' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
