### ISSUE TITLE
mongo container cannot startup

### ISSUE THREAD

**Issue by jinyulin** [kubeapps/kubeapps#118]
The mongo container cannot startup with following error message, which causes kubeapps-api stuck,

```
$ kubectl logs -f mongodb-1543949793-x3gps -n kubeapps

Welcome to the Bitnami mongodb container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
Send us your feedback at containers@bitnami.com

nami    INFO  Initializing mongodb
Error executing 'postInstallation': Group '60001' not found

```

I'm using NFS storage provisoner over here https://github.com/kubernetes-incubator/external-storage/tree/master/nfs, not sure if it's related.

**Comment by prydonius** [comment]
@jinyulin unfortunately this container doesn't work correctly on NFS volumes, we're trying to nail down the issue in the container. In the meantime, is there a different storage type you can use?

**Comment by jinyulin** [comment]
@prydonius, ok I will try with AWS EBS.

**Comment by arapulido** [comment]
I will be closing this issue, as it is not really an issue on Kubeapps, but the container

**Comment by funky81** [comment]
hi @jinyulin , have you success using AWS EBS for this case instead using NFS storage storage provisioner.
I having the same setup with you and still not success using kubeapps over my 1.93 kubernetes.

Thanks
