### ISSUE TITLE
Can't run kubeapps inside Docker Container: bash: /usr/local/bin/kubeapps: No such file or directory

### ISSUE THREAD

**Issue by marcellodesales** [kubeapps/kubeapps#119]
# Required tools

* We are building CLIs using Docker containers.
  * Base image is `alpine:3.6`
* Our CLI installs and sets up Kubectl, including helm being installed...
  * Including a fresh install of tiller
* Kubernetes 1.9.1

Here's the current 

```
[root@3fb706522b3c]:kubeapps # helm init --service-account tiller --upgrade
Creating /root/.helm
Creating /root/.helm/repository
Creating /root/.helm/repository/cache
Creating /root/.helm/repository/local
Creating /root/.helm/plugins
Creating /root/.helm/starters
Creating /root/.helm/cache/archive
Creating /root/.helm/repository/repositories.yaml
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com
Adding local repo with URL: http://127.0.0.1:8879/charts
$HELM_HOME has been configured at /root/.helm.

Tiller (the Helm server-side component) has been installed into your Kubernetes Cluster.
Happy Helming!
```

# Installing Kubeapps

* After that, I'm trying to install the latest version as follows, following the instructions on the README section https://github.com/kubeapps/kubeapps#quickstart.

```
[root@3fb706522b3c]:kubeapps # curl -s https://api.github.com/repos/kubeapps/kubeapps/releases/latest | grep linux | grep browser_download_url | cut -d '"' -f 4
https://github.com/kubeapps/kubeapps/releases/download/v0.2.0/kubeapps-linux-amd64

[root@3fb706522b3c]:kubeapps # curl -L https://github.com/kubeapps/kubeapps/releases/download/v0.2.0/kubeapps-linux-amd64 -o kubeapps-linux-amd64
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   611    0   611    0     0    611      0 --:--:-- --:--:-- --:--:--  1331
100 38.5M  100 38.5M    0     0   564k      0  0:01:10  0:01:10 --:--:--  398k

[root@3fb706522b3c]:kubeapps # chmod +x kubeapps-linux-amd64
[root@3fb706522b3c]:kubeapps # mv kubeapps-linux-amd64 /usr/local/bin/kubeapps
```

# Problem Running

* At this point, I can't run the command because it fails `No such file or directory`

```
[root@3fb706522b3c]:kubeapps # kubeapps --version
bash: /usr/local/bin/kubeapps: No such file or directory
```

* But the file exists

```
[root@3fb706522b3c]:kubeapps # ls -la /usr/local/bin/kubeapps
-rwxr-xr-x 1 root root 40472648 Jan 25 00:39 /usr/local/bin/kubeapps
```

* The app is in the PATH

```
[root@3fb706522b3c]:kubeapps # which kubeapps
/usr/local/bin/kubeapps
```

Where can I go from here?

**Comment by prydonius** [comment]
@marcellodesales the issue is that we compile the `kubeapps` binary as a dynamically linked binary for glibc (which isn't compatible with alpine's minimal muslc lib). I believe the reason we don't statically compile `kubeapps` is because we are using https://github.com/strickyak/jsonnet_cgo, but @ngtuna @anguslees can confirm whether it's possible to statically compile.

In the meantime, are you able to use a glibc compatible base image? At the risk of tooting our own horn, Bitnami maintains a small (though not nearly as small as alpine) base image that uses glibc and also is compatible with debian packages (https://github.com/bitnami/minideb).

**Comment by marcellodesales** [comment]
Thanks for the reply @prydonius... I could pursue that route, but I would only be able to switch to an image based on `rhel7` or `centos:7`... I hope that would be available... 

Meanwhile, I don't think I would be able to re-write the current Dockerfile at the moment... :( I would wait until @ngtuna @anguslees can confirm if it's possible to compile statically... I could compile locally if that's the case while I build the image... 

thank you!

**Comment by prydonius** [comment]
@marcellodesales rhel/centos based images should also work as they would typically use glibc. I'm not sure if there are any slimmer rpm-based images though.

**Comment by marcellodesales** [comment]
@prydonius ok, let me try to see if I can get a base on one of those... problem is I have to convert all the apk install commands :(

**Comment by marcellodesales** [comment]
I just have too many binaries in the same image as I'm building a consolidated CLI... some dependencies in alpine were different than centos... and I'm on a crunch time for a demo tomorrow :(

**Comment by anguslees** [comment]
If building dynamically, the main thing to keep in mind is that the build
env should match the deploy env - so the build image OS/version should
match the final image when using docker multi images. (It should build with
anything that has a go and C++ tool chain available: alpine, Debian,
CentOS, etc)

**Comment by anguslees** [comment]
.. in addition, we need to also fix our release binaries, or remove them.

**Comment by marcellodesales** [comment]
@anguslees @prydonius Have you guys considered using https://goreleaser.com/? That may streamline the binary distribution...

**Comment by ngtuna** [comment]
@marcellodesales https://goreleaser.com/ can't help in this case because the key point here is kubeapps right now can't be built statically. See the below error:

```
$ git diff Makefile
diff --git a/Makefile b/Makefile
index 4fa1b11..b8d7f8a 100644
--- a/Makefile
+++ b/Makefile
@@ -10,7 +10,7 @@ VERSION = dev-$(shell date +%FT%T%z)
 BINARY = kubeapps
 GO_PACKAGES = $(IMPORT_PATH)/cmd $(IMPORT_PATH)/pkg/...
 GO_FILES := $(shell find $(shell $(GOBIN) list -f '{{.Dir}}' $(GO_PACKAGES)) -name \*.go)
-GO_FLAGS = -ldflags='-w -X github.com/kubeapps/kubeapps/cmd.VERSION=${VERSION}'
+GO_FLAGS = -ldflags='-extldflags "-static" -s -w -X github.com/kubeapps/kubeapps/cmd.VERSION=${VERSION}'
 GO_XFLAGS =
 EMBEDDED_STATIC = generated/statik/statik.go

$ make
mkdir -p /home/tuna/kubeapps/src/github.com/kubeapps/kubeapps/.GOPATH/src/github.com/kubeapps/
ln -snf /home/tuna/kubeapps/src/github.com/kubeapps/kubeapps /home/tuna/kubeapps/src/github.com/kubeapps/kubeapps/.GOPATH/src/github.com/kubeapps/kubeapps
/usr/bin/env GOPATH=/home/tuna/kubeapps/src/github.com/kubeapps/kubeapps/.GOPATH go build -o statik ./vendor/github.com/rakyll/statik/statik.go
/usr/bin/env GOPATH=/home/tuna/kubeapps/src/github.com/kubeapps/kubeapps/.GOPATH go generate
CGO_ENABLED=1 /usr/bin/env GOPATH=/home/tuna/kubeapps/src/github.com/kubeapps/kubeapps/.GOPATH go build -i -o kubeapps -ldflags='-extldflags "-static" -s -w -X github.com/kubeapps/kubeapps/cmd.VERSION=dev-2018-02-05T15:57:17+0000' github.com/kubeapps/kubeapps
# github.com/kubeapps/kubeapps
/tmp/go-link-854175608/000003.o: In function `mygetgrouplist':
/tmp/workdir/go/src/os/user/getgrouplist_unix.go:15: warning: Using 'getgrouplist' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/tmp/go-link-854175608/000003.o: In function `mygetgrgid_r':
/tmp/workdir/go/src/os/user/cgo_lookup_unix.go:38: warning: Using 'getgrgid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/tmp/go-link-854175608/000003.o: In function `mygetgrnam_r':
/tmp/workdir/go/src/os/user/cgo_lookup_unix.go:43: warning: Using 'getgrnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/tmp/go-link-854175608/000003.o: In function `mygetpwnam_r':
/tmp/workdir/go/src/os/user/cgo_lookup_unix.go:33: warning: Using 'getpwnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/tmp/go-link-854175608/000003.o: In function `mygetpwuid_r':
/tmp/workdir/go/src/os/user/cgo_lookup_unix.go:28: warning: Using 'getpwuid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/tmp/go-link-854175608/000000.o: In function `_cgo_b0c710f30cfd_C2func_getaddrinfo':
/tmp/go-build/net/_obj/cgo-gcc-prolog:46: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
```

Indeed we want to build it statically. I will try to see around the possible solution. Do you guys have any suggestion ?

**Comment by prydonius** [comment]
I think the best thing to do would be to build kubeapps directly in your Dockerfile. You'll need the Go toolchain and make and will just need to run `make`.

**Comment by marcellodesales** [comment]
@ngtuna @prydonius I have migrated our Baseimage for our CLI and we have all the needed tooling to build local, including golang... So, maybe we can close this ticket and open another one for the statically built version of kubeapps?

**Comment by prydonius** [comment]
@marcellodesales with the latest release (v0.5.0) the linux binary is now statically compiled and works on alpine - check it out!

**Comment by marcellodesales** [comment]
@prydonius Will do once I get some cycle to come back to this
