### ISSUE TITLE
[basic form] Support for parameters that affect different sections

### ISSUE THREAD

**Issue by andresmgot** [kubeapps/kubeapps#1236]
Follow up from #1182 

From: https://github.com/helm/charts/pull/18078#issuecomment-543212398

In the WordPress chart (but this pattern is present in other charts as well), there is a parameter `mariadb.enabled` that is being used for: 

  1. Enabling MariaDB (values under `mariadb.*`)
  2. Disabling/Ignoring the external database details (values under `externalDatabase.*`)

Ideally we want to show information about both sections in the basic form. If MariaDB is enabled, we want to allow people to select the size of the volume used by MariaDB. When disabled, it should show the external database details to fill those parameters.

The current solution has the limitation that a section enabler can be associated with just one section (so we either choose to show details of MariaDB or the external database).

Two possibilities to fix this situation are:
 - Support, somehow, to have a relation 1:2 between a section enabler and the sections it affects. This way, if a schema parameter defines the properties `enables: *` and `disables: *`, both sections would be merged in one and displayed depending on the value of the enabler.
 - Change the chart values and replace the boolean parameter by a choice one. That way, we could have a parameter `databaseSelector: mariadb|external`. And generically add support for `choice` parameters that enables a certain section.

I would rather implement the second, but that'd mean that we don't support the first, requiring changes in the existing chart values.

cc/ @juan131

**Comment by absoludity** [comment]
> I would rather implement the second, but that'd mean that we don't support the first, requiring changes in the existing chart values.

It's not clear to me why you prefer this option if it means we'd need to ask chart authors to change their values.yaml to support this? Or do you mean something else?

Also, keen to know what you don't like about your first option? (if it only requires schema changes, and is generic enough to support all situations?). Also, with the first option, does it need to be binary? Could it instead be:
```
enables:
  - section1
  - section2
disables:
  - section3
```
so that it's more generic? And related to that, why would we need to merge the sections to display them - why not keep the sections separate?

**Comment by andresmgot** [comment]
> It's not clear to me why you prefer this option if it means we'd need to ask chart authors to change their values.yaml to support this? Or do you mean something else?

I mean that I'd rather implement the second option from the implementation point of view in Kubeapps because it's a matter of supporting "choice" options in a generic way. It's true that requiring changes in the chart values is a downside important enough to discard that possibility. In any case, yes, let's go with the option that doesn't require changes in the chart.

> Also, keen to know what you don't like about your first option? (if it only requires schema changes, and is generic enough to support all situations?)

Because it's tricky to implement. Note that we would need to relate sections and parameters that may be at a different depth level. For example, `mariadb.children["enables"]` will have a reference to its parent `mariadb` and a different section at the root level `externalDatabase`. So we need to merge somehow those two sections. While it's something doable, it's not straight-forward and it's entangling the implementation.

> Also, with the first option, does it need to be binary? Could it instead be:

For the moment I would leave it to just one `enables` and one `disables` because supporting an array there would be even more complex. I think that is as generic as supporting:

```
enables: section1
disables: section2
```

> And related to that, why would we need to merge the sections to display them - why not keep the sections separate?

Because the idea is to keep the graphical switch within the section it enables/disables. If not, you will have that switch duplicated. Not sure if that's what you suggest but in that case, it would be something like:

```
Section 1:
 - [on/off] Enable a self hosted MariaDB database?
   - [if on] Mariadb volume size
-----
Section 2:
 - [on/off] Enable a self hosted MariaDB database?
   - [if off] External database details
```

My idea is to have just one section:

```
 - [on/off] Enable a self hosted MariaDB database?
   - [if on] Mariadb volume size
   - [if off] External database details
```

**Comment by andresmgot** [comment]
Thinking about this, I've found a third option. We can remove the implementation for `enables` and `disables` that it's becoming entangled and substitute those for a `hidden` parameter. That way, if a parameter has the `hidden` property, and the parameter that points to is `true`, that parameter will be hidden. For example:

```
    "externalDatabase": {
      "type": "object",
      "properties": {
        "host": {
          "type": "string",
          "hidden": "mariadb.enabled"
        },
```

That way we would hide `externalDatabase.host` if `mariadb.enabled` is `true`.

I like this option because with that we remove the logic related to reordering params hierarchy. The downside is that it would be a breaking change but since this feature is still not being used broadly, it's a good moment.

Let me send a PR with that proposal and let me know what you think.

**Comment by absoludity** [comment]
Excellent - yes, I think that's a much better mapping, and allows multiple objects to be hidden based on one switch etc. Great thinking :)
