### ISSUE TITLE
[oauth2_proxy] Modify the default login page

### ISSUE THREAD

**Issue by andresmgot** [kubeapps/kubeapps#1249]
The current login page is bit simple (and maybe confusing?):

![Screenshot from 2019-10-24 12-00-23](https://user-images.githubusercontent.com/4025665/67475129-e66bfa80-f655-11e9-800a-8f9df09bb800.png)

It doesn't give any info that you are login into Kubeapps. It's possible to modify this default view setting the environment variable: `OAUTH2_PROXY_CUSTOM_TEMPLATES_DIR` pointing to a folder with two templates `sign_in.html` and `error.html`.

Taking the source from https://github.com/bitly/oauth2_proxy/blob/master/templates.go, I made a quick test that it works as expected and I included the Kubeappps logo:

![Screenshot from 2019-10-24 12-03-08](https://user-images.githubusercontent.com/4025665/67475341-48c4fb00-f656-11e9-8907-0a95c6a9cb6b.png)

The issue is how we can provide these two files to the deployment without modifying the source docker image (maybe a public S3 bucket mounted as a volume?)

**Comment by andresmgot** [comment]
I guess that's something doable, we just need to forge the proper template

**Comment by andresmgot** [comment]
@absoludity what do you think is better here: build an image `FROM` oauth2_proxy and add the custom page or use an `initContainer` to download the custom page and place it conveniently?

The first option is offline-friendly but it force us to maintain the "forked" image of oauth2_proxy.

**Comment by absoludity** [comment]
I hadn't looked, but didn't think either of those would be necessary. I assumed that we'd be whitelisting the login page and just updating our template there so that it includes the button when configured. Did you check what harbor are doing for the same effect? I assume it'll be something like that.

**Comment by andresmgot** [comment]
I tried modifying the ingress rule for the login page but no white-listing the URL. I will try that and let you know.
