### ISSUE TITLE
Cannot install charts from a private chart repository

### ISSUE THREAD

**Issue by absoludity** [kubeapps/kubeapps#1256]
Currently Kubeapps allows adding private chart repositories, but AFAICT does not cater for the fact that a private chart repository can contain charts which refer to docker images in a private registry. 

So a private chart repository is only useful if it has private/customized charts which refer to public images only, which is not the main use-case for private chart repositories.

It should be possible to add a private chart repository and install charts from it (EDIT: removed implementation suggestion from issue description).

EDIT: Investigation and initial design at https://docs.google.com/document/d/1YEeKC6nPLoq4oaxs9v8_UsmxrRfWxB6KCyqrh2-Q8x0/edit?usp=sharing

**Comment by andresmgot** [comment]
> It should be possible to specify an image pull secret to be used for charts in a private repository, such that when the AppRepository object is saved, a k8s secret is created for the image pull secret (or if it is the same as the chart repo credential, we can refer to that), so that when a chart from that repository is installed, the image pull secret is added to the deployment pod spec's list of image pull secrets? Or perhaps there's a better way to automate this?

I am not sure if I follow, are you suggesting that we modify the chart deployments/stafefulsets/... on the fly to add a `imagePullSecrets` on the fly before deploying the chart? I don't think that's something doable. I don't think Kubeapps should modify any chart content at all.

From a user point of view, in that situation I would do one of the following:

 - (As you mention) Create custom charts in which the required deployment contains the reference to the `imagePullSecrets`. 
 - Modify the default service account for the target namespace as described [here](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#add-imagepullsecrets-to-a-service-account) to include the required `imagePullSecrets`

**Comment by absoludity** [comment]
> I am not sure if I follow, are you suggesting that we modify the chart deployments/stafefulsets/... on the fly to add a imagePullSecrets on the fly before deploying the chart? I don't think that's something doable. I don't think Kubeapps should modify any chart content at all.

Not necessarily - we could create the `ImagePullSecret` when the `AppRepository` is created, and then when installing a chart from that repo in a certain namespace, Kubeapps can ensure that the image pull secret is included in the default service account for the namespace (which would ensure it gets included with the deployment).

> From a user point of view, in that situation I would do one of the following:
> 
>     * (As you mention) Create custom charts in which the required deployment contains the reference to the `imagePullSecrets`.
> 
>     * Modify the default service account for the target namespace as described [here](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#add-imagepullsecrets-to-a-service-account) to include the required `imagePullSecrets`

The problem, IMO, with this is that it requires *manual* intervention. If I setup Kubeapps for a customer, and give them access to a private chart repository and container registry, then I can't guarantee that they can install the chart. I can manually modify the default service account for all the namespaces to which they have access, but they may be given access to more (or have RBAC to create new namespaces).

I think we need a solution which does not require manual intervention to deploy a chart. As a user, if I can access charts in a repository, that should imply I have access to install those (without requiring manual intervention, IMO).

Do you think there is a reason it should be manual, or is it that you can't see a way for it to be automated?

**Comment by andresmgot** [comment]
> Do you think there is a reason it should be manual, or is it that you can't see a way for it to be automated?

No, I agree that it could be automated (adding the `imagePullSecrets` to the default serviceaccount). What I am not sure is that if Kubeapps is the right place to do so. We don't have the goal of managing Docker images or Docker registries. It would make more sense from my point of view to have that functionality in the Docker registry admin page (i.e. Harbor) because we may miss use cases or cause security issues.

Related to this issue, the Bitnami charts include a `global` section that can be defined in case those charts are copied to a private registry:

https://github.com/helm/charts/blob/master/stable/wordpress/values.yaml#L5

**Comment by prydonius** [comment]
> Kubeapps can ensure that the image pull secret is included in the default service account for the namespace (which would ensure it gets included with the deployment).

I'm not sure this covers all cases. What if a Pod references a different ServiceAccount that is installed by the chart? AFAIK, there isn't a way to apply imagePullSecrets to all Pods/SAs in the cluster.

Some charts have imagePullSecrets as a value (as @andresmgot pointed to for the Bitnami charts). The Secret would still need to be created out of band for this, so we could create that when creating the AppRepo in Kubeapps, but I somewhat agree with Andres that Kubeapps maybe shouldn't solve this problem.

One issue I can see is that a chart repository could contain charts that reference multiple private registries, each with different credentials. Additionally, multiple chart repositories can reference the same private registry (in which case we risk adding it twice). It's not a 1:1 relationship.

Also if Kubeapps creates the Secret, I'm not sure how we'd make it clear to users what to set for the `imagePullSecrets` field. I'm not sure if there's something in the new JSON schema support that would allow us to find that field and set it automatically - that could get error prone, though.

**Comment by absoludity** [comment]
> > Do you think there is a reason it should be manual, or is it that you can't see a way for it to be automated?
> 
> No, I agree that it could be automated (adding the `imagePullSecrets` to the default serviceaccount).

Great.

> What I am not sure is that if Kubeapps is the right place to do so. We don't have the goal of managing Docker images or Docker registries.

Right, but that's not the goal - the goal is for a user to deploy a chart from a private registry to which I have been given access.

> It would make more sense from my point of view to have that functionality in the Docker registry admin page (i.e. Harbor) because we may miss use cases or cause security issues.

But Harbor doesn't know about Kubernetes at all, in this context. I'm guessing you don't mean that that Harbor should tell the app catalog (Kubeapps) about the required docker pull secrets - as that's what I'm proposing, but that seems to be the responsibility, IMO - the docker registry needs to give the app catalog the required credentials to pull the required images.

> 
> Related to this issue, the Bitnami charts include a `global` section that can be defined in case those charts are copied to a private registry:
> 
> https://github.com/helm/charts/blob/master/stable/wordpress/values.yaml#L5

Yep, but what's not clear to me here is whether this is in addition to the default account's pull secrets. I think so, because this chart value defaults to `[]`, but haven't checked the k8s implementation. This would change one reply below...

> > Kubeapps can ensure that the image pull secret is included in the default service account for the namespace (which would ensure it gets included with the deployment).
> 
> I'm not sure this covers all cases. What if a Pod references a different ServiceAccount that is installed by the chart?

Thanks for providing input Adnan. Hmm, hadn't thought of that possibility. I don't see any config option in the values of the bitnami/wordpress chart for `serviceAccountName`, but that doesn't mean charts can't do that generally. If a chart did this - installing its own service account for use by pods - it would also need to enable the `imagePullSecrets` option like the bitnami charts do.


> AFAIK, there isn't a way to apply imagePullSecrets to all Pods/SAs in the cluster/namespace.

We wouldn't want to do this, I don't think? It's slightly different, I want to ensure the imagePullSecrets can be available for any namespace when required (but yeah, not saying it's any better :/ ).

> 
> Some charts have imagePullSecrets as a value (as @andresmgot pointed to for the Bitnami charts). The Secret would still need to be created out of band for this, so we could create that when creating the AppRepo in Kubeapps,

Yes, this is what I'm keen to investigate - but even then, we create the AppRepo in the kubeapps namespace, so the secret would be created there too and *copied* into the namespace for the deployment... so it's looking uglier as I go further :/

> but I somewhat agree with Andres that Kubeapps maybe shouldn't solve this problem.

I also agree from the context of Kubeapps being a helm UI - it's not a responsibility helm does or assumes - I do get that. But helm doesn't allow another user (an admin) to setup your access to a private app repository either - you can only do that step yourself, at which point you would also set pull secrets as required. Whereas Kubeapps allows an admin to set you up with access to a private app repository - but that admin cannot ensure it will work for you. So, from a user perspective, I don't see how we can say Kubeapps allows you to deploy a catalog using a private chart repository - which is something we seem to say (in demos) and something which is wanted.

I'm stuck to know how to proceed here. Interestingly, if an `AppRepository` was created and available only in a specific namespace (something which has come up in a different context), I think this would be more straight forward.


> 
> One issue I can see is that a chart repository could contain charts that reference multiple private registries, each with different credentials.

I don't see this as an issue, as when creating an app repository in Kubeapps you could also allow specifying a list of required pull secrets/credentials.

> Additionally, multiple chart repositories can reference the same private registry (in which case we risk adding it twice).

Not really, if the secret creation is idempotent - when creating the `AppRepository`, Kubeapps would just ensure the required secret exists?

> It's not a 1:1 relationship.

I think that's OK.

> 
> Also if Kubeapps creates the Secret, I'm not sure how we'd make it clear to users what to set for the `imagePullSecrets` field. I'm not sure if there's something in the new JSON schema support that would allow us to find that field and set it automatically - that could get error prone, though.

Right, I wouldn't want to do that. But this depends on whether setting `imagePullSecrets` for a pod is adding additional secrets (ie. the service account secrets are still used also?) or are used instead. I've not yet checked the implementation, but given that the default value in the chart is `[]` I would hope it was consistent, and therefore meaning additional secrets.

So, I think my main question is this: How can Kubeapps allow an admin to add a private `AppRepository` for the installation, so that the general users of the Kubeapps app catalog can install charts from those repositories?

Assumptions:
 - it's fine for charts to be customised to reference a particular `imagePullSecret`, but not to include the actual credential
 - it needs to be done once when the admin is adding the chart repository (not for each user)

**Comment by andresmgot** [comment]
So let's say that we **_need_** to implement this, imaging that there is no other tool to help with this. Also, let's assume that the charts are not modifiable and doesn't include the reference to the `imagePullSecrets`. I think there are two issues that we cannot easily address:

 - Our AppRepositories are currently "global". They are installed in the ns in which kubeapps is running. If we want to add a imagePullSecret(s) to the `default` service account we wouldn't know which namespace to use. I agree that having AppRepositories per namespace would help here but we are not there yet. That would require a big re-architecture.
 - Even if we add the imagePullSecrets to the `default` service account, any deployment/statefulset/other that sets a `serviceAccountName` (like our own [apprepository-controller](https://github.com/kubeapps/kubeapps/blob/master/chart/kubeapps/templates/apprepository-deployment.yaml#L22)) won't have access to that secret and won't be able to pull a private image. One thing that we could do to address this is having a controller watching `serviceaccounts` in all namespaces but again, that's something not trivial (and maybe intrusive?).

**Comment by prydonius** [comment]
> I don't see this as an issue, as when creating an app repository in Kubeapps you could also allow specifying a list of required pull secrets/credentials.

You're right, it's not a huge issue, but it does involve a bit more complexity. When adding a repository, I now have to think about every private registry that charts in my repo might reference and add them here.

> Even if we add the imagePullSecrets to the default service account, any deployment/statefulset/other that sets a serviceAccountName (like our own apprepository-controller) won't have access to that secret and won't be able to pull a private image.

The kind of charts that create their own service accounts are typically Kubernetes extensions that require elevated RBAC privileges. I think this is important, if we automate configuring imagePullSecrets for default SAs, we can't make a promise that it is fully automated as users will need to manually configure it for charts like these.

> One thing that we could do to address this is having a controller watching serviceaccounts in all namespaces but again, that's something not trivial (and maybe intrusive?).

This sounds like it would be out-of-scope for Kubeapps. The problem with trying to do things like this is that it does feel intrusive and cluster operators might have security concerns around automatically propagating imagePullSecrets across namespaces.

> If I setup Kubeapps for a customer, and give them access to a private chart repository and container registry, then I can't guarantee that they can install the chart. I can manually modify the default service account for all the namespaces to which they have access, but they may be given access to more (or have RBAC to create new namespaces).

Just curious, is this hypothetical or a problem we're facing with a customer currently? My concern is that we might be trying to solve for something that doesn't generally apply to how a customer might be managing their Kubernetes infrastructure. For example, at Bitnami we built automation to provision namespaces and give access to users. This same automation could be used to apply relevant imagePullSecrets to these namespaces. Alternatively, I could use a mutating admission controller to add imagePullSecrets to SAs or Pods on creation. I think my point here is that there are different out-of-band solutions here that might make sense in different environments, I'm not sure it would be conducive for Kubeapps to mandate one way for this to be done.

**Comment by absoludity** [comment]
> So let's say that we **_need_** to implement this, imaging that there is no other tool to help with this. Also, let's assume that the charts are not modifiable

FWIW, I *don't* have this constraint... in the (real) scenario, we have the ability to modify the charts, as I outlined above. Please re-check my question and my assumptions at the end of my last comment.

> and doesn't include the reference to the `imagePullSecrets`. I think there are two issues that we cannot easily address:
> 
>     * Our AppRepositories are currently "global". They are installed in the ns in which kubeapps is running. If we want to add a imagePullSecret(s) to the `default` service account we wouldn't know which namespace to use. I agree that having AppRepositories per namespace would help here but we are not there yet. That would require a big re-architecture.

Yes, I think I addressed this above too, when I said:

> Yes, this is what I'm keen to investigate - but even then, we create the AppRepo in the kubeapps namespace, so the secret would be created there too and copied into the namespace for the deployment... so it's looking uglier as I go further :/

So, ugly, yes. That's why I tried to step back and state the main question with the actual (real) constraints that we have.

> 
>     * Even if we add the imagePullSecrets to the `default` service account, any deployment/statefulset/other that sets a `serviceAccountName` (like our own [apprepository-controller](https://github.com/kubeapps/kubeapps/blob/master/chart/kubeapps/templates/apprepository-deployment.yaml#L22)) won't have access to that secret and won't be able to pull a private image.

But we don't have the constraint you assumed above that we can't change the chart. The version of my chart which is in my private repository can ensure the service account (the equivalent of [Kubeapps' app repo service account](https://github.com/kubeapps/kubeapps/blob/master/chart/kubeapps/templates/apprepository-serviceaccount.yaml)) includes the `release-imagePullSecret` secret (which again, appears to require copying - ugly).


> One thing that we could do to address this is having a controller watching `serviceaccounts` in all namespaces but again, that's something not trivial (and maybe intrusive?).

Yeah - specifically, if a service account referencing an image pull secret from an `AppRepository` is created/updated/deleted, to ensure the secret is available in that namespace. I've been thinking along these lines - perhaps an optional flag on the app-repository controller - `ensureImagePullSecrets` - let's keep thinking. Again, just to try to refocus on what I think is the core question and assumptions:

> How can Kubeapps allow an admin to add a private `AppRepository` for the installation, so that the general users of the Kubeapps app catalog can install charts from those repositories?
> 
> Assumptions:
> 
>     * it's fine for charts to be customised to reference a particular `imagePullSecret`, but not to include the actual credential
>     * it needs to be done once when the admin is adding the chart repository (not manually for each user, or each namespace)

On to Adnan's feedback (thanks to you both, again - I realise it's hard to keep context on long comments :/ )

> > I don't see this as an issue, as when creating an app repository in Kubeapps you could also allow specifying a list of required pull secrets/credentials.
> 
> You're right, it's not a huge issue, but it does involve a bit more complexity. When adding a repository, I now have to think about every private registry that charts in my repo might reference and add them here.

There is something I am missing at this point. In my mind, I *have* to think about every private registry that charts in my repo might reference the moment I want people to be able to access the charts in my registry? What is the situation where I would want to provide people with access to my chart repository but *not* to be able to install those charts? Some bit of information is missing at this point for me.

> The kind of charts that create their own service accounts are typically Kubernetes extensions that require elevated RBAC privileges. I think this is important, if we automate configuring imagePullSecrets for default SAs, we can't make a promise that it is fully automated as users will need to manually configure it for charts like these.

Note that we don't need to assume we configure imagePullSecrets for the *default* SA - we could (as discussed above) be watching for service accounts which reference an imagePullSecret for a specific app repository - whether it's a default or specifically named (and/or created) service account, and if the user has access to install apps from that `AppRepository` (which is currently always true), add the secret to that namespace. Not suggesting that that is the solution, but just that I want to avoid assumptions that we don't need, and rather step back and stick to the core question and core assumptions.


> 
> > One thing that we could do to address this is having a controller watching serviceaccounts in all namespaces but again, that's something not trivial (and maybe intrusive?).
> 
> This sounds like it would be out-of-scope for Kubeapps.

Except that Kubeapps enables you to add private `AppRepositories` which make the charts contained within accessible to all users. I'm not saying it should be a default feature, but perhaps an optional flag on the app-repository controller or something similar.

> The problem with trying to do things like this is that it does feel intrusive and cluster operators might have security concerns around automatically propagating imagePullSecrets across namespaces.

Yes, I agree 100% with this. If it was enforced it would be a bad thing, and even as an optional feature (of, for eg. app repo controller) it is not good (making decisions about sharing secrets from the `kubeapps` namespace to regular user namespaces). But why do we then enable access to the charts of an `AppRepository` cluster-wide, if they can't be used? Perhaps we need to re-think assumptions there - I'm not sure.

> 
> > If I setup Kubeapps for a customer, and give them access to a private chart repository and container registry, then I can't guarantee that they can install the chart. I can manually modify the default service account for all the namespaces to which they have access, but they may be given access to more (or have RBAC to create new namespaces).
> 
> Just curious, is this hypothetical or a problem we're facing with a customer currently? My concern is that we might be trying to solve for something that doesn't generally apply to how a customer might be managing their Kubernetes infrastructure.

Yes, a real customer requires an admin Kubeapps user/agent to add a private `AppRepository` to a Kubeapps installation such that users of that installation can then install those charts (and those charts refer to images in a private docker registry).

> For example, at Bitnami we built automation to provision namespaces and give access to users. This same automation could be used to apply relevant imagePullSecrets to these namespaces.

Yes, if we add the constraint that all private `AppRepositories` are known at cluster creation time, then that would be the solution.

> Alternatively, I could use a mutating admission controller to add imagePullSecrets to SAs or Pods on creation. I think my point here is that there are different out-of-band solutions here that might make sense in different environments, I'm not sure it would be conducive for Kubeapps to mandate one way for this to be done.

Yep, I'm open to any solution so we can choose the best - not necessarily as part of Kubeapps, but just so Kubeapps users can *use* the private `AppRepositories` to which they have access. I still do think it's odd that we enable an admin to create a private `AppRepository` so that users can view but not install all the charts in that repository. In this discussion I'm just trying to narrow down to the best solution for the given constraints. Thanks again for taking the time, I really appreciate it.

**Comment by absoludity** [comment]
> > For example, at Bitnami we built automation to provision namespaces and give access to users. This same automation could be used to apply relevant imagePullSecrets to these namespaces.
> 
> Yes, if we add the constraint that all private `AppRepositories` are known at cluster creation time, then that would be the solution.

(actually, doesn't need to be creation time - but just that cluster config is updated out-of-band when `AppRepository` is added).

Thinking more about this, it may just be that this is the constraint we need to work with. I think it would be OK for the current customer need that we have - ie. any new namespace on a specific cluster + Kubeapps is provisioned with the required image pull secrets. The secret can be referenced from the default service account, or included in any private chart which creates a service account.

If a new `AppRepository` is added to the Kubeapps installation at a later date, the cluster configuration will need updating (out-of-band) so that relevant secrets are present in all namespaces where charts can be installed and referenced in default SA's.

It seems to be the only direction that remains sane.

**Comment by absoludity** [comment]
I took a look at Rancher today, after having read a while back in their [docs for registries](https://rancher.com/docs/rancher/v2.x/en/k8s-in-rancher/registries/) that:

- If a workload is created in the Rancher UI, it will automatically pull the required private credentials (but if you create a deployment manually via `kubectl` you need to create the secret manually in the namespace) (though I'm not sure if this is outdated, based on the findings below).

I was keen to come back and find out more. Digging deeper today, I see that in [secret.go](https://github.com/rancher/rancher/blob/v2.3.3/pkg/controllers/user/secret/secret.go) Rancher define two controllers that run in the user cluster:

1. `SecretController` which listens for create/update/delete events in the (project?) management API and propagates the changes to all corresponding namespaces in the cluster API (ie. if I add a new secret for a project containing 5 namespaces, then all 5 namespaces in the cluster API will be updated).
2. `NamespaceController` which listens to events on namespaces in the cluster API and for each, reads the secret from the management namespace of the corresponding project and then creates the k8s secret in that cluster namespace.

So it appears if you create a credential for a Rancher project, that credential will be propagated to all the namespaces for that project (or a specific namespace if scoped as such) so that a workload will have access to the secret when deployed within a project (note, this is slightly different to the docs - I've [asked about this in the rancher slack](https://rancher-users.slack.com/archives/C3ASABBD1/p1575436174237100)).

EDIT: I'll update here once my local Rancher env is up to verify the above.

**Comment by andresmgot** [comment]
I still don't know if we should worry about this. In the case of Rancher, they manage the whole cluster. It's okay in that use case to be able to listen in all namespaces and be able to write secrets in all of them. The case of Kubeapps is different, it seems a bit intrusive to give it admin permissions o that kind. Also, having a secret in the namespace doesn't guarantee that the chart will use that as `imagePullSecret` (unless I am missing something).

**Comment by absoludity** [comment]
> I still don't know if we should worry about this. In the case of Rancher, they manage the whole cluster. It's okay in that use case to be able to listen in all namespaces and be able to write secrets in all of them.

Yes - I wasn't analysing rancher to say we're the same, but rather to see how they provide the functionality to install charts with images from a private registry, which is functionality that we also want - I think? Or is that where I'm going wrong?

> The case of Kubeapps is different, it seems a bit intrusive to give it admin permissions o that kind.
Yep, I didn't imply any solution for Kubeapps in my analysis of Rancher for that reason. But fwiw, we wouldn't need to give "it" (there is no definitive "it" in Kubeapps, once we remove tiller-proxy) special permissions. We would need to ensure that users who should be able to install the chart images have read access to the secrets (ie. they could be stored in a "project" namespace) and write access within the namespace where they deploy.

> Also, having a secret in the namespace doesn't guarantee that the chart will use that as `imagePullSecret` (unless I am missing something).

Rancher explicitly adds the imagePullSecret to the pod spec when creating the workload ([afaict from the source](https://github.com/rancher/rancher/blob/v2.3.3/pkg/api/store/workload/workload_store.go#L213)). This is very intrusive compared with Kubeapps' current functionality, obviously, and not necessarily something we'd consider - but that's what Rancher does.

> 
> Maybe we are trying to fix a problem that doesn't exist yet?

We currently allow adding a private chart repository to Kubeapps' via "Add Repository", which will populate the Kubeapps catalog with the charts from that private repository but installations will fail (unless all images referenced in the private charts are in public registries). I'll rename this issue "Cannot install charts from a private chart repository" - as that avoids implementation details, but let me know if you think that it's not a relevant problem - I really am struggling to see how it is not.

On the positive side, as helm repositories move to OCI distribution spec, the most likely use-case will be a single private registry storing both the charts and images.

**Comment by prydonius** [comment]
> Rancher explicitly adds the imagePullSecret to the pod spec when creating the workload (afaict from the source). This is very intrusive compared with Kubeapps' current functionality, obviously, and not necessarily something we'd consider - but that's what Rancher does.

In the Helm 3 case (or even in Helm 2 with `helm template`), I don't see adding imagePullSecrets to all rendered PodSpecs as that intrusive. Seems like a fairly simple way to ensure we can deploy a chart with private images (so long as we know what registries and credentials they come from). This is tricky with the current Helm 2 + Tiller case, though.

**Comment by absoludity** [comment]
Great, yeah - without tiller it's less intrusive, but it's still requiring patching the yaml resources generated by helm (after ensuring the required secret is available in the namespace etc.). I don't (currently) see another way for this to work.

**Comment by mkmik** [comment]
+1 for addressing this issue, I think it's important.

whether or not this is core feature of kubeapps, or a separate controller that kubeapps (ships with in standalone mode) is a different question. Secret management in general (and image pull secrets in particular) might be handled by other cluster management components, so we want to make sure we can play nicely with them.

**Comment by absoludity** [comment]
I'm working on a design document capturing this, together with investigations of similar relevant functionality in other projects like OpenShift and Rancher. It's not complete, but there's enough of the direction that I'm thinking about to share for initial discussion/objections/corrections . https://docs.google.com/document/d/1YEeKC6nPLoq4oaxs9v8_UsmxrRfWxB6KCyqrh2-Q8x0/edit?usp=sharing
