### ISSUE TITLE
"Sorry! Something went wrong" after deploying chart.

### ISSUE THREAD

**Issue by Yi-jiunTang** [kubeapps/kubeapps#1274]
I installed Kubeapps with Chart and everything goes well.
```
kubectl get all -n=management                                                                                                                                               Tue Nov  5 17:13:34 2019

NAME                                                              READY     STATUS      RESTARTS   AGE
pod/apprepo-sync-chartmuseum-1572944400-s6nl9                     0/1       Completed   0          13m
pod/apprepo-sync-chartmuseum-5gxdl-dgx8m                          0/1       Completed   0          34m
pod/kubeapps-6c8dc84ffb-tljm6                                     1/1       Running     0          35m
pod/kubeapps-internal-apprepository-controller-76d6f565ff-rt4hj   1/1       Running     0          35m
pod/kubeapps-internal-chartsvc-6c5cf8955d-drhpf                   1/1       Running     0          35m
pod/kubeapps-internal-dashboard-78cb98dbf5-fjv2s                  1/1       Running     0          35m
pod/kubeapps-internal-tiller-proxy-67878879c9-ztlt7               1/1       Running     0          35m
pod/kubeapps-mongodb-586db7bf48-pj8kg                             1/1       Running     0          35m

NAME                                     TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)       AGE
service/kubeapps                         NodePort    10.233.0.195    <none>        80:8082/TCP   35m
service/kubeapps-internal-chartsvc       ClusterIP   10.233.17.109   <none>        8080/TCP      35m
service/kubeapps-internal-dashboard      ClusterIP   10.233.3.124    <none>        8080/TCP      35m
service/kubeapps-internal-tiller-proxy   ClusterIP   10.233.60.16    <none>        8080/TCP      35m
service/kubeapps-mongodb                 ClusterIP   10.233.3.235    <none>        27017/TCP     35m

NAME                                                         DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/kubeapps                                     1         1         1            1           35m
deployment.apps/kubeapps-internal-apprepository-controller   1         1         1            1           35m
deployment.apps/kubeapps-internal-chartsvc                   1         1         1            1           35m
deployment.apps/kubeapps-internal-dashboard                  1         1         1            1           35m
deployment.apps/kubeapps-internal-tiller-proxy               1         1         1            1           35m
deployment.apps/kubeapps-mongodb                             1         1         1            1           35m

NAME                                                                    DESIRED   CURRENT   READY     AGE
replicaset.apps/kubeapps-6c8dc84ffb                                     1         1         1         35m
replicaset.apps/kubeapps-internal-apprepository-controller-76d6f565ff   1         1         1         35m
replicaset.apps/kubeapps-internal-chartsvc-6c5cf8955d                   1         1         1         35m
replicaset.apps/kubeapps-internal-dashboard-78cb98dbf5                  1         1         1         35m
replicaset.apps/kubeapps-internal-tiller-proxy-67878879c9               1         1         1         35m
replicaset.apps/kubeapps-mongodb-586db7bf48                             1         1         1         35m

NAME                                            DESIRED   SUCCESSFUL   AGE
job.batch/apprepo-sync-chartmuseum-1572944400   1         1            13m
job.batch/apprepo-sync-chartmuseum-5gxdl        1         1            34m

NAME                                     SCHEDULE    SUSPEND   ACTIVE    LAST SCHEDULE   AGE
cronjob.batch/apprepo-sync-chartmuseum   0 * * * *   False     0         13m             34m
```

I login Kubeapps dashboard and try to deploy  a chart in App Repositories.
It's no problem to deploy a chart. But after deploying successfully, if clicking on other tab (Application or Catalog), it will say "Sorry! Something went wrong." 

![image](https://user-images.githubusercontent.com/6365696/68196025-ea533180-fff2-11e9-8ad2-42baa38d5068.png)

I checked on Chrome's DevTools console, the error message is as below.
![image](https://user-images.githubusercontent.com/6365696/68195221-71070f00-fff1-11e9-8edf-cec92cfeef1e.png)

The error will disappear after refreshing dashboard.
But it still annoying to have this error everytime I deploy chart. 
There are some information of the environment, hope it provides useful clues.
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
```
 helm version
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
```

If there's any suggestion to solve this problem, please let me know. Thanks a lot!

**Comment by andresmgot** [comment]
Hi @Yi-jiunTang,

Indeed that's something it shouldn't be happening. How are you accessing to Kubeapps? Using a `port-forward`, accessing a `NodePort` or with an ingress?

Can you also send a screenshot of the `Network` tab of your chrome console? There may be more information there about what's failing.

Also, what version of Kubeapps are you running?

**Comment by Yi-jiunTang** [comment]
Hi @andresmgot,
 
Thanks for the prompt reply. I appreciate it.

Kubeapps chart version: 2.0.2
We access Kubeapps via NodePort and ingress both.
The same error will show up no matter i access with NodePort or ingress.

It's the screenshot of chrome network console. I'm not sure if there's something useful.
If not, please don't hesitate to tell me to provide more useful information.
Thank you again.
![image](https://user-images.githubusercontent.com/6365696/68262012-e966e200-007c-11ea-840a-637f95bd0575.png)

**Comment by absoludity** [comment]
Thanks @Yi-jiunTang ! The most interesting information from the network console will be the most recent requests when you reproduce the issue. Can you please scroll to the bottom of the network console and include a screenshot of that?

Thanks again for providing the useful info!

**Comment by Yi-jiunTang** [comment]
Hi, @absoludity, Thanks for the reply.

I reproduce the error with the following steps and take screenshot of all network messages.
First of all, deploy one chart in Catalog, take "helm-exporter" for example here.
After deploying successfully, I clicked on Application tab. And error will occur in this moment. 

![image](https://user-images.githubusercontent.com/6365696/68280350-52b41880-00b0-11ea-8939-8b923dcc7b30.png)
![image](https://user-images.githubusercontent.com/6365696/68281481-b0496480-00b2-11ea-870c-3ac70eb390d1.png)

I can't tell if there's abnormal message in network console.
Thanks for yours guy's help.

**Comment by Yi-jiunTang** [comment]
Hi guys,

I found that the latest Kubeaps chart version is 3.0.3.
Is the latest version helpful to this issue?
If yes, i can try to update my Kubeapps and see what will happen.
Thanks!

**Comment by andresmgot** [comment]
Yes, please update to the latest Kubeapps (and helm if possible) and check if that solves the issue. It's true that the are no errors in the network tab so it seems an error in the client side.

**Comment by Yi-jiunTang** [comment]
Thanks @andresmgot, 
I will update to the latest version first and see if there's errors occur again. 
We could close the issue now.

**Comment by andresmgot** [comment]
Okay, please, let us know if that solved your issue.
