### ISSUE TITLE
Token expiration when using oauth2_proxy

### ISSUE THREAD

**Issue by andresmgot** [kubeapps/kubeapps#1281]
When the OIDC token expires, I start receiving 403 and the application becomes unresponsive:

![Screenshot from 2019-11-08 12-29-20](https://user-images.githubusercontent.com/4025665/68473634-caef1b00-0223-11ea-8abd-cc136d3db725.png)

I am not sure if that has changed with oauth2_proxy, but we only try to refresh the token when we receive a 401:

https://github.com/kubeapps/kubeapps/blob/master/dashboard/src/shared/AxiosInstance.ts#L47

Apparently we need to do the same with 403 but differentiating between an expired token and a "real" forbidden action.

**Comment by absoludity** [comment]
Hmm, it could be a difference with oauth2_proxy - I didn't yet check refreshes.

I would think 403 is the correct response (since auth has been provided and the request should be denied with the expired auth), but yeah, we need to detect the 403 for the expired token as you say.
