### ISSUE TITLE
Update CI e2e test to use OIDC local env

### ISSUE THREAD

**Issue by absoludity** [kubeapps/kubeapps#1288]
This will ensure the support for local env with OIDC doesn't rot, but also make it easy to test different roles in CI.

**Comment by absoludity** [comment]
There's one issue currently, in that the local env with OIDC currently requires updating the `/etc/hosts` of the k8s kind API server (to resolve `dex.dex`) which is lost occasionally if the api server is re-started. Need to dig to find out how to avoid this before we can use it reliably.

**Comment by andresmgot** [comment]
This has been already implemented thanks to @antgamdia, including multicluster support :)
