### ISSUE TITLE
Changes tab shows a lot of whitespace differences

### ISSUE THREAD

**Issue by absoludity** [kubeapps/kubeapps#1293]
This is a follow-up to #1235. While testing a local deploy, I noticed the changes tab is showing a lot of white-space. I think this is known (and due to the yaml parsing library's handling of whitespace for comments - though I don't see an [upstream issue](https://github.com/eemeli/yaml/issues)?). Just noting so we can at some point fix it (probably upstream). See:

![kubeapps-whitespace-changes](https://user-images.githubusercontent.com/497518/69102108-98f87700-0ab5-11ea-818f-ef6e32796501.png)

**Comment by andresmgot** [comment]
Yes, that's something I notices too but I am not sure if it's something fixable. I commented that here: https://github.com/eemeli/yaml/issues/125#issuecomment-539068916 but maybe it's worth to create a different issue for that.
