### ISSUE TITLE
tiller proxy probes

### ISSUE THREAD

**Issue by fabianschwarzfritz** [kubeapps/kubeapps#1296]
Hi,

I have seen that the tiller-proxy component has a healthcheck defined for readyness and liveness probe.  See here in th tiller-proxy:
 - https://github.com/kubeapps/kubeapps/blob/33718734ec9d92cc6e58ba4028b81f2751dcb61d/cmd/tiller-proxy/main.go#L31
- and https://github.com/kubeapps/kubeapps/blob/33718734ec9d92cc6e58ba4028b81f2751dcb61d/cmd/tiller-proxy/main.go#L141-L143

However in the deployment, no liveness probe is defined, or at leas I don't see it. 
- https://github.com/kubeapps/kubeapps/blob/master/chart/kubeapps/templates/tiller-proxy-deployment.yaml#L21

Is there any reason why the two endpoints are defined but cannot be configures as kubernetes artifacts? Or did I overlook something? 

Best Regards,
Fabian

**Comment by andresmgot** [comment]
Right, we missed that. Thanks for catching it! The startup time of tiller-proxy is quite fast, that's why we haven't notice any issue with that.
