### ISSUE TITLE
Ingress URL not shown in the AppView

### ISSUE THREAD

**Issue by andresmgot** [kubeapps/kubeapps#1307]
**Description**

URL of the ingress are not shown in the Access URL table

**Steps to reproduce the issue:**

1. Deploy Wordpress
2. Enable the Ingress rule

**Additional information you deem important (e.g. issue happens only occasionally):**

Apparently, the `AccessURLTable` is being mounted before the application manifests is parsed. It's only when mounting it when the component `AccessURLTable` fetches the existing ingress and at that point the list is empty.

**Version of Helm, Kubeapps and Kubernetes**:

- Output of `helm version`:

```
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
```

- Output of `helm list <kubeapps-release-name>`:

```
kubeapps	1       	Wed Nov 20 15:29:47 2019	DEPLOYED	kubeapps-3.0.3v1.6.1     	kubeapps 
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-gke.17", GitCommit:"188432a69210ca32cafded81b4dd1c063720cac0", GitTreeState:"clean", BuildDate:"2019-11-13T20:47:11Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by absoludity** [comment]
I assume that by "enable the ingress rule" you mean setting `ingress.enabled: true`? When I tested a deploy on the same setup I saw the URL in the app view as below:
![ingress-url](https://user-images.githubusercontent.com/497518/69384707-2552a600-0d11-11ea-9a89-2fb636483e0c.png)

Wonder if it's a race condition?

**Comment by andresmgot** [comment]
did you try with the latest version? I think that's also related to the `componentDidUpdate` change (so only present in 1.7.1)
