### ISSUE TITLE
Sorry! Something went wrong. Unable to load Kubeapps configuration: Network Error

### ISSUE THREAD

**Issue by szbjb** [kubeapps/kubeapps#1314]
**Description**

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version of Helm, Kubeapps and Kubernetes**:

- Output of `helm version`:

```
(paste your output here)
```

- Output of `helm list <kubeapps-release-name>`:

```
(paste your output here)
```

- Output of `kubectl version`:

```
(paste your output here)
```
[root@k8s-master-db3 ~]# helm  status  kubeapps
LAST DEPLOYED: Sun Nov 24 16:27:43 2019
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/ConfigMap
NAME                                DATA  AGE
kubeapps-frontend-config            1     5m43s
kubeapps-internal-dashboard-config  2     5m43s

==> v1/Deployment
NAME                                        READY  UP-TO-DATE  AVAILABLE  AGE
kubeapps                                    2/2    2           2          5m43s
kubeapps-internal-apprepository-controller  1/1    1           1          5m43s
kubeapps-internal-chartsvc                  2/2    2           2          5m43s
kubeapps-internal-dashboard                 2/2    2           2          5m43s
kubeapps-internal-tiller-proxy              2/2    2           2          5m43s
kubeapps-mongodb                            1/1    1           1          5m43s

==> v1/Pod(related)
NAME                                                         READY  STATUS   RESTARTS  AGE
kubeapps-76fcb54d54-fw67v                                    1/1    Running  0         5m42s
kubeapps-76fcb54d54-nfdcj                                    1/1    Running  0         5m43s
kubeapps-internal-apprepository-controller-556cc5fff7-tcn64  1/1    Running  0         5m43s
kubeapps-internal-chartsvc-5cc4d5864-dqtvc                   1/1    Running  1         5m43s
kubeapps-internal-chartsvc-5cc4d5864-rnw84                   1/1    Running  1         5m42s
kubeapps-internal-dashboard-6c6c9676d9-dfd6g                 1/1    Running  0         5m42s
kubeapps-internal-dashboard-6c6c9676d9-sjbjt                 1/1    Running  0         5m43s
kubeapps-internal-tiller-proxy-68b6d5566c-4lrsn              1/1    Running  0         5m42s
kubeapps-internal-tiller-proxy-68b6d5566c-f4gfc              1/1    Running  0         5m43s
kubeapps-mongodb-6cbcc9ffd4-skm69                            1/1    Running  0         5m42s

==> v1/Service
NAME                            TYPE       CLUSTER-IP  EXTERNAL-IP  PORT(S)    AGE
kubeapps                        ClusterIP  10.0.0.161  <none>       80/TCP     5m43s
kubeapps-internal-chartsvc      ClusterIP  10.0.0.117  <none>       8080/TCP   5m43s
kubeapps-internal-dashboard     ClusterIP  10.0.0.144  <none>       8080/TCP   5m43s
kubeapps-internal-tiller-proxy  ClusterIP  10.0.0.79   <none>       8080/TCP   5m43s
kubeapps-mongodb                ClusterIP  10.0.0.250  <none>       27017/TCP  5m43s

==> v1/ServiceAccount
NAME                                        SECRETS  AGE
kubeapps-internal-apprepository-controller  1        5m43s
kubeapps-internal-tiller-proxy              1        5m43s

==> v1beta1/Role
NAME                                        AGE
kubeapps-internal-apprepository-controller  5m43s
kubeapps-internal-tiller-proxy              5m43s
kubeapps-repositories-read                  5m43s
kubeapps-repositories-write                 5m43s

==> v1beta1/RoleBinding
NAME                                        AGE
kubeapps-internal-apprepository-controller  5m43s
kubeapps-internal-tiller-proxy              5m43s

NOTES:
** Please be patient while the chart is being deployed **

Tip:

  Watch the deployment status using the command: kubectl get pods -w --namespace default

Kubeapps can be accessed via port 80 on the following DNS name from within your cluster:

   kubeapps.default.svc.cluster.local

To access Kubeapps from outside your K8s cluster, follow the steps below:

1. Get the Kubeapps URL by running these commands:
   echo "Kubeapps URL: http://127.0.0.1:8080"
   export POD_NAME=$(kubectl get pods --namespace default -l "app=kubeapps" -o jsonpath="{.items[0].metadata.name}")
   kubectl port-forward --namespace default $POD_NAME 8080:8080

2. Open a browser and access Kubeapps using the obtained URL.

[root@k8s-master-db3 ~]#

**Comment by absoludity** [comment]
Hi @szbjb . Thanks for the report. This error is displayed when your browser first starts loading the Kubeapps application, it makes a request for `/config.json` and in your case that is failing. Can you please include a screenshot of the browser's javascript debugger's network tab, so we can see more information about the request to `/config.json` ?

Thanks!

**Comment by absoludity** [comment]
Hi again. Let me know if you're able to reproduce this issue and if so, please include the info requested above. I'll close for now until we have further info. Thanks either way!
