### ISSUE TITLE
Allow editing exiting app repositories

### ISSUE THREAD

**Issue by juan131** [kubeapps/kubeapps#1329]
**Description**

Once you add an app repository to Kubeapps, you can't edit its configuration (URL, authorization details, etc.) 

**Steps to reproduce the issue:**

1. Follow [this guide](https://github.com/kubeapps/kubeapps/blob/master/docs/user/private-app-repository.md) to add you private repository to Kubeapps.
2. Introduce some wrong configuration (e.g. a wrong URL).
3. Try to edit the repository you just added.

**Describe the results you received:**

There are no options to edit existing app repositories:

<img width="1048" alt="Screenshot 2019-11-28 at 13 38 42" src="https://user-images.githubusercontent.com/6740773/69807312-4883c680-11e5-11ea-91a9-8b4a7a446877.png">

You can only edit it by deleting/adding it again.

**Describe the results you expected:**

I would like to have a 3rd action (current ones are "Delete" and "Refresh"): "Edit". This new action should allow me editing the exiting app repository.

**Version of Helm, Kubeapps and Kubernetes**:

- Output of `helm list <kubeapps-release-name>`:

```console
$ helm list kubeapps
NAME    	REVISION	UPDATED                 	STATUS  	CHART         	APP VERSION	NAMESPACE
kubeapps	1       	Thu Nov 28 12:23:42 2019	DEPLOYED	kubeapps-3.1.0	v1.7.1     	kubeapps
```

**Comment by andresmgot** [comment]
I got used to this but it's true that it should be possible to edit the current app repositories

**Comment by andresmgot** [comment]
I missed this and created a duplicated: #1666 but this is already done :)
