### ISSUE TITLE
Validate app repositories before adding them

### ISSUE THREAD

**Issue by juan131** [kubeapps/kubeapps#1330]
**Description**

When you add an app repository to Kubeapps, no validations are executed.

**Steps to reproduce the issue:**

1. Follow [this guide](https://github.com/kubeapps/kubeapps/blob/master/docs/user/private-app-repository.md) to add you private repository to Kubeapps.
2. Introduce some wrong configuration (e.g. an invalid URL).

**Describe the results you received:**

Kubeapps accepts the wrong configuration without performing any validation:

<img width="1102" alt="Screenshot 2019-11-28 at 13 38 23" src="https://user-images.githubusercontent.com/6740773/69807699-38b8b200-11e6-11ea-91c4-128c2db6d29b.png">

**Describe the results you expected:**

I would expect Kubeapps to validate the configuration and ensure it can connect and list the chars in the app repository.

**Version of Helm, Kubeapps and Kubernetes**:

- Output of `helm list <kubeapps-release-name>`:

```console
$ helm list kubeapps
NAME    	REVISION	UPDATED                 	STATUS  	CHART         	APP VERSION	NAMESPACE
kubeapps	1       	Thu Nov 28 12:23:42 2019	DEPLOYED	kubeapps-3.1.0	v1.7.1     	kubeapps
```

**Comment by andresmgot** [comment]
Thanks @juan131, apart than validating the URL do you think something else needs to be validated?

**Comment by juan131** [comment]
I guess the basic authentication (or any other provided method) should be validated too

**Comment by andresmgot** [comment]
well, the problem is that the browser may not have access to the URL. For example, if I type `http://chartmuseum.default:8080` the application won't be able to validate the access that URL (apart that it's a valid URL) since that's only valid within the cluster.

In any case, it should be easy to validate that at least the URL is valid.

**Comment by absoludity** [comment]
> In any case, it should be easy to validate in the client side that at least the URL is valid.

I don't see much point in just verifying a valid URL, but could the chart-svc (as I see we post directly to the k8s API when creating/refreshing/deleting app repos) have an endpoint to validate chart repo URL+credentials/certs? This is another point where, if we had a backend receiving the request to create the app repository, we could do other things, like validate the request before adding it as a k8s resource.

**Comment by andresmgot** [comment]
Yes, the problem is that right now we don't have the proper service to do so. We would need to use either the chartsvc or tiller-proxy but it's doable.

**Comment by absoludity** [comment]
We also need to limit the length of the name, since we also generate secrets, jobs, cronjobs based on the name which have fixed limits.
