### ISSUE TITLE
Web Socket connections don't upgrade on GKE

### ISSUE THREAD

**Issue by absoludity** [kubeapps/kubeapps#1352]
### Description:
When running locally with dex/oauth2-proxy, the web socket connections which are used to track changes during an install work perfectly fine, upgrading as expected so the status can be updated:
![websocket-upgraded-locally](https://user-images.githubusercontent.com/497518/70291744-34b51180-1830-11ea-9ec9-db9c3505a3a6.png)

But on a more production-like setup on GKE, the websocket connection request is not being upgraded, and as a result, the status of an install is not updated:

![websocket-screenshot](https://user-images.githubusercontent.com/497518/70291782-557d6700-1830-11ea-8db5-c5eaacb6e494.png)

### Steps to reproduce the issue:

1. Install Kubeapps on a GKE cluster, using the auth-proxy with an accounts.google.com provider
2. After logging in, install an application and wait for the app to be Ready

### Describe the results you received:

App never updates to ready without refreshing the page manually.

### Describe the results you expected:

App updates to show Ready (or more specifically, the websocket connection requests are upgraded as expected).

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
$ helm version
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}

```

- Output of `helm list <kubeapps-release-name>`:

```
$ helm --tiller-namespace tiller list kubeapps
NAME            REVISION        UPDATED                         STATUS          CHART           APP VERSION     NAMESPACE
kubeapps        2               Fri Nov 22 15:17:24 2019        DEPLOYED        kubeapps-3.1.0  v1.7.1          kubeapps 

```

- Output of `kubectl version`:

```
$ k version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-gke.17", GitCommit:"188432a69210ca32cafded81b4dd1c063720cac0", GitTreeState:"clean", BuildDate:"2019-11-13T20:47:11Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by absoludity** [comment]
Checking the nginx-ingress logs on a GKE setup, I see:
```
2019/12/06 02:59:41 [error] 5821#5821: *8788279 upstream timed out (110: Connection timed out) while reading upstream, client: 1.144.111.41, server: <redacted>, request: "GET /api/kube/api/v1/namespaces/default/services?watch=true&fieldSelector=metadata.name%3Dmarvelous-impulse-mariadb HTTP/1.1", upstream: "http://<redacted>:3000/api/kube/api/v1/namespaces/default/services?watch=true&fieldSelector=metadata.name%3Dmarvelous-impulse-mariadb", host: "<redacted>"
```
while the corresponding log on the kubeapps frontend (which is upstream above) is:
```
127.0.0.1 - - [06/Dec/2019:02:59:41 +0000] "GET /api/kube/api/v1/namespaces/default/services?watch=true&fieldSelector=metadata.name%3Dmarvelous-impulse-mariadb HTTP/1.1" 200 720 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0"
```
So it appears the response was generated but nginx-ingress isn't getting the result? Also, note the response is a 200, not 101.

Checking in my local env where websockets work I see the frontend returning 101 responses, both visible in the browser and the frontend logs:
```
127.0.0.1 - - [06/Dec/2019:01:46:23 +0000] "GET /api/kube/api/v1/namespaces/default/services?watch=true&fieldSelector=metadata.name%3Dworthless-line-mariadb HTTP/1.1" 101 705 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0"
```

**Comment by andresmgot** [comment]
:+1: We keep finding issues with these websockets. For example, if the ingress controller is not NGINX, the timeout configuration won't work so you wouldn't receive updates either. I would consider changing the approach here, maybe doing periodic requests instead.
