### ISSUE TITLE
Local development API server requires (and loses) /etc/hosts change

### ISSUE THREAD

**Issue by absoludity** [kubeapps/kubeapps#1356]
### Description:

Currently a local kind cluster with Kubeapps installed using OAuth2/OIDC for auth can be created with:
```
make cluster-kind
make deploy-dev
```

but this depends on a step where the `/etc/hosts` of the k8s api server is updated so that it can resolve the local `dex.dex` hostname [1], so although it works initially, after some time if/when the API server is restarted, the change is lost (and I need to run `make update-apiserver-etc-hosts` to add it back).

We need to find a better way so that this can be stable and usable by devs.

[1] This is because:

- The API server needs to be run with a resolvable tls-enabled `oidc_issuer_url` which is the same issuer URL used by the client and the provider (dex),
- The API server does not have access to internal service host names (such as `dex.dex`), and

**Comment by andresmgot** [comment]
If this is just for a dev environment, maybe it's possible to create a custom image and change `/etc/hosts` in a Dockerfile? (Not sure if that file is modified/mounted by something else)

**Comment by absoludity** [comment]
This is no longer relevant, since the `/etc/hosts` change on the k8s api server is not required, as the bridge network address is used for dex. It's still not perfect, but better and this isn't an issue at least.
