### ISSUE TITLE
Security: Transition Kubeapps to be OAuth2/OIDC by default (with k8s tokens as the exception)

### ISSUE THREAD

**Issue by absoludity** [kubeapps/kubeapps#1357]
### Description:
Using a service account token for user login is easier to setup initially (not requiring any extra auth infrastructure) and so fine for demos and dev, but not so useful for real-life situations when deploying Kubeapps to be used by users in an organisation. There are many security issues distributing permanent tokens like this.

Kubeapps now supports using Oauth2 and OpenIDConnect (via oauth2-proxy) and can support other authentication methods such as LDAP by using dex as the trusted OIDC provider (though other methods may be possible). This depends on using a Kubernetes cluster which is configured with authn/authz (usually OIDC, but hosted solutions can differ, GKE uses an oauth2 token, all of which Kubeapps supports), which is the case in most corporate environments.

Currently all our documentation (both installation and user docs), CI, developer setup and default UI assume authentication using a K8s service account token. I'd like to see us transition to having all of these assume OAuth2/OIDC by default, with a k8s service account token being the exception for a quick test setup.

We have already demonstrated a dev environment using OAuth2 (I use it daily), though we don't promote this yet, due to one remaining issue (#1356). Similarly, I've not switched CI to use this  (#1288) until the same issue is resolved. Once resolved and CI updated, we can trust the OAuth2/OIDC setup to be working on master and begin promoting it in our documentation, installation instructions and more widely, demoting the k8s token setup at the same time.

**Comment by absoludity** [comment]
Also see second last slide in the [2019 Kubecon sig-auth-update](https://github.com/cloudyuga/kubecon19-NA/blob/master/slides/sig-auth-update-and-deep-dive-mo-khan-red-hat-mike-danese-google-tim-allclair-google.pdf):
"Why not tokens? Tokens have amajor downside: [they are] forwardable so may be replayed, [and] don't solve server authentication."

**Comment by andresmgot** [comment]
I am mostly "worried" about the entry level if OIDC is the default. It should be trivial for people to spin up a testing environment (with the default parameters). In other words, `helm install bitnami/kubeapps` should work out of the box with, ideally, no pre-setup. If we cannot achieve that (because #1356) we can just make it very clear (from a documentation perspective) that using a token is not the recommended option.

**Comment by absoludity** [comment]
Yep, agreed. I want to get some more time to investigate whether we can make it possible, but otherwise the best alternative is clarifying the docs throughout.

**Comment by absoludity** [comment]
Closing as we've now stressed in the docs not to use tokens outside of demos, recommending OIDC. I agree that configuring client ids and oauth2 for dev env is not necessary.
