### ISSUE TITLE
Is there any way to get statistic of number of downloads/install of particular chart?

### ISSUE THREAD

**Issue by jainishshah17** [kubeapps/kubeapps#136]

**Comment by prydonius** [comment]
The short answer is that there isn't a way we can really do this, right now. @viglesiasce was working on a way to extract the download stats for the stable and incubator repos, so that's something we may be able to use in the future, but I don't see a good way of doing this for every chart repo.

**Comment by jainishshah17** [comment]
Thank you for information. By any chance can you give me a link to track this feature request.

**Comment by prydonius** [comment]
This is being tracked here https://github.com/kubernetes/charts/issues/5899.
