### ISSUE TITLE
Create screenshot artifact on e2e test failure

### ISSUE THREAD

**Issue by absoludity** [kubeapps/kubeapps#1360]
### Description:

Currently if an e2e test fails, the only output available is something like:
```
 ● Deploys an application with the values by default

    TimeoutError: Text not found "Ready"

      waiting for function failed: timeout 60000ms exceeded
```

It would save a lot of time if a screenshot was created on failure so we could see that the error is something like:
![e2e-failure](https://user-images.githubusercontent.com/497518/70494007-d3f24580-1b5d-11ea-9470-d66ff660401c.png)

**Comment by andresmgot** [comment]
It's already creating those, in the "Artifacts" tab you can find them: https://13229-107555654-gh.circle-artifacts.com/0/home/circleci/project/integration/reports/screenshots/deploys-an-application-with-the-values-by-default.png

**Comment by absoludity** [comment]
Ah great. I missed that. Thanks.
