### ISSUE TITLE
compile error about c.kubeClient.Core undefined

### ISSUE THREAD

**Issue by zkf9971** [kubeapps/kubeapps#1361]
### Description:

Getting the compile error: 
vendor/github.com/kubeapps/kubeapps/pkg/chart/chart.go:356:30: c.kubeClient.Core undefined (type kubernetes.Interface has no field or method Core)

I use the following dependencies:
`
[[projects]]
  branch = "master"
  digest = "1:1d64f79a76a3e50072f3078ad98d52047c26a68056ba8f63f7521ed0d0de8c7e"
  name = "github.com/kubeapps/kubeapps"
  packages = [
    "pkg/chart",
    "pkg/proxy",
    "pkg/yaml",
  ]
  pruneopts = ""
  revision = "746ee386bfa3ebd56ae514c258ce1bab77708549"
`

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.14.0"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.14.0"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.14.0"

**Comment by andresmgot** [comment]
Hi @zkf9971,

Depending on the version of `kubernetes` and `client-go` used you need to specify `c.kubeClient.CoreV1` instead of `c.kubeClient.Core`. We have just updated master to change that so if you pull the latest changes that error should go away.

Let us know if that's the case.

**Comment by zkf9971** [comment]
@andresmgot Great, I noticed it's in master, thank you!
