### ISSUE TITLE
Newly creates namespace gone after namespace switch

### ISSUE THREAD

**Issue by fabianschwarzfritz** [kubeapps/kubeapps#1364]
### Description:

When installing a new chart into a new namespace, the namespace disappears after a namespace switch. 

### Steps to reproduce the issue:

1. Open the kubeapps dashbaord and select the "default" namespace
1. Type in a new non-existing namespace "new-1" via the dropbownbox's text field. 
1. Go to the catalog, select an aribrary chart and deploy it. The new chart gets deployed into the new namespace "new-1". The installation is successful and I can see it on the cluster via `kubectl` and in the Applications tab in kubeapps. The app is deployed into the new namespace "new-1"
1. Select the "default" namespace in the dropdown in the UI. 
1. Try to select the new namespace "new-1" in the dropdown with the mouse (without typing something in). The namespace does not appear there and seems to be gone. 
1.  Workaround 1: It is only possible to get back to the namespace via the ui, by typing in "new-1" in the dropdown box.  Then the namespace can be selected again.
1. Workaround 2: force reloading the page in the browser. Then the namespace appears in the list and can be selected with the mouse. 

### Describe the results you received:
Successfully created namespace via kubeapps UI is not selectable.

### Describe the results you expected:
To see the namespace in the dropbown list box.

### Additional information you deem important (e.g. issue happens only occasionally):
Issue happens independent of which chart is installed. 
Workaround is force-reloading the webbrowser.

### Version of Helm, Kubeapps and Kubernetes:
 - kubeapps 1.7.1
 - 
- Output of `helm version`:

```
/usr/local/Cellar/helm/2.14.3/bin/helm version
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```

*Remark: this helm client 2.14.3 was used for the installation*

- Output of `helm list <kubeapps-release-name>`:

```
/usr/local/Cellar/helm/2.14.3/bin/helm list
NAME       	REVISION	UPDATED                 	STATUS  	CHART        	APP VERSION	NAMESPACE
naughty-fly	1       	Wed Dec 11 10:13:43 2019	DEPLOYED	mongodb-7.6.0	4.0.13     	new-1
```

- Output of `kubectl version`:

```
k version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:42:50Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by andresmgot** [comment]
Right, I am able to reproduce the bug. This is because we are not re-fetching the namespaces. We are only fetching those when mounting the `Header` component (which happens just once).

Another thing is that we are not creating the namespace, we expect Helm to create it for us when deploying the application. This won't happen with Helm 3 so we better change that.

I would suggest to create the namespace when "submitting" in the namespace selector and re-fetch the namespaces at that point.

**Comment by fabianschwarzfritz** [comment]
Thanks for the fix 😊
