### ISSUE TITLE
Chart Icon Rendering incorrect

### ISSUE THREAD

**Issue by fabianschwarzfritz** [kubeapps/kubeapps#1365]
### Description:

The rendering of the chart icons seems to be broken for some chart.

I have found this (similar/same) issue with two chart: *stable/anchor-engine* and *stable/apm-server*.

### Steps to reproduce the issue:

1. Select chart stable/anchore-engine in the catalog. See the anchor icon overlapping with the heading. 
1. Select chart stable/apm-server in the catalog. See the chart icon not displayed, even if it exists in the html and is downloaded (but probably not resized properly). 

### Describe the results you received:
See steps to reproduce.

### Describe the results you expected:
I want to see the icons properly put into the space that is designated. The images should not overlap with text or other elements,  even if this means scaling down non-squared images.

### Additional information you deem important (e.g. issue happens only occasionally):
Issue happens with some of the charts stable/anchor-engine and stalbe/apm-server are the ones I found so far.

### Version of Helm, Kubeapps and Kubernetes:
I think helm/kubectl version should be irelevant. 
Kubeapps Version is `1.7.1`

### Screenshots 
I have attached the following screenshots to show the what I see. 

<img width="1373" alt="Screenshot 2019-12-11 at 10 33 31" src="https://user-images.githubusercontent.com/1759672/70609856-d490e780-1c02-11ea-8640-87bd1ba0ab2d.png">

<img width="1831" alt="Screenshot 2019-12-11 at 10 36 42" src="https://user-images.githubusercontent.com/1759672/70609864-d65aab00-1c02-11ea-97cf-55c2a6d25743.png">

**Comment by andresmgot** [comment]
Thanks for reporting! This should be easy to fix with a CSS change (I am not sure why the `apm-server` logo is 0x0 px)
