### ISSUE TITLE
 container "kubeops" in pod "kubeapps-internal-kubeops-68bf77974-92zhj" is waiting to start: trying and failing to pull image

### ISSUE THREAD

**Issue by OPSTime** [kubeapps/kubeapps#1375]
**cat kubeapps.custom.values**

> useHelm3: true

**install kubeapps**

> $ helm install  kubeapps bitnami/kubeapps  -n kubeapps -f kubeapps.custom.values 

 **List all pods** 

> NAME                                                          READY   STATUS             RESTARTS   AGE
> apprepo-sync-bitnami-1576206000-hm5xb                         0/1     Completed          0          27m
> apprepo-sync-bitnami-1576206600-m9449                         0/1     Completed          0          17m
> apprepo-sync-bitnami-1576207200-zwc4d                         0/1     Completed          0          7m35s
> apprepo-sync-bitnami-78sxr-v2w2h                              0/1     Completed          0          86m
> apprepo-sync-incubator-1576206000-dk77s                       0/1     Completed          0          27m
> apprepo-sync-incubator-1576206600-925jr                       0/1     Completed          0          17m
> apprepo-sync-incubator-1576207200-25zds                       0/1     Completed          0          7m35s
> apprepo-sync-incubator-wsqhm-29l7x                            0/1     Completed          2          86m
> apprepo-sync-stable-1576205400-wztqs                          0/1     Completed          2          37m
> apprepo-sync-stable-1576206600-qcr94                          0/1     Completed          4          17m
> apprepo-sync-stable-1576207200-rhmjp                          0/1     Completed          1          7m35s
> apprepo-sync-svc-cat-1576206000-hp2zp                         0/1     Completed          0          27m
> apprepo-sync-svc-cat-1576206600-qf4fs                         0/1     Completed          0          17m
> apprepo-sync-svc-cat-1576207200-ctk2s                         0/1     Completed          0          7m35s
> apprepo-sync-svc-cat-nndvz-cd5zg                              0/1     Completed          0          86m
> kubeapps-664c5849d4-cp64n                                     0/1     CrashLoopBackOff   21         86m
> kubeapps-664c5849d4-ncnh7                                     0/1     CrashLoopBackOff   21         86m
> kubeapps-internal-apprepository-controller-67696766b6-khv2g   1/1     Running            0          86m
> kubeapps-internal-chartsvc-677b745bb9-prhlz                   1/1     Running            0          86m
> kubeapps-internal-chartsvc-677b745bb9-xsbmf                   1/1     Running            0          86m
> kubeapps-internal-dashboard-54cf8d5c87-kb75l                  1/1     Running            0          86m
> kubeapps-internal-dashboard-54cf8d5c87-r92fc                  1/1     Running            0          86m
> kubeapps-internal-kubeops-68bf77974-92zhj                     0/1     ErrImagePull       0          86m
> kubeapps-internal-kubeops-68bf77974-qww68                     0/1     ImagePullBackOff   0          86m
> kubeapps-mongodb-788ff89fd9-g6m9g                             1/1     Running            0          86m

**Return snapshot logs from pod kubeapps-internal-kubeops-68bf77974-92zhj** 

> $ kubectl logs kubeapps-internal-kubeops-68bf77974-92zhj   -n kubeapps
> Error from server (BadRequest): container "kubeops" in pod "kubeapps-internal-kubeops-68bf77974-92zhj" is waiting to start: trying and failing to pull image

**pull docker.io/kubeapps/kubeops:latest**

> $ docker pull docker.io/kubeapps/kubeops:latest
> Error response from daemon: pull access denied for kubeapps/kubeops, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**docker pull docker.io/kubeapps/dashboard:latest**

> latest: Pulling from kubeapps/dashboard
> Digest: sha256:e0f8d6c2fe36b54e5057474b7e58d3dec2622d56ffa5511683ec8e6502261e19
> Status: Image is up to date for kubeapps/dashboard:latest
> docker.io/kubeapps/dashboard:latest
>

**Comment by OPSTime** [comment]
bitnami/kubeops、bitnami/kubeapps-apprepository-controller
There are no results for this search in Docker Hub。

**Comment by absoludity** [comment]
Thanks @OPSTime . We don't currently support helm3, but are actively working to do so, using locally built images for `kubeops`. Once it is tested and working, we'll ensure the image can be pulled from dockerhub.

By chance, I also just created https://github.com/kubeapps/kubeapps/pull/1376 so the option is less visible in both the `values.yaml` and the Kubeapps UI.
