### ISSUE TITLE
Application not found in the namespace

### ISSUE THREAD

**Issue by andresmgot** [kubeapps/kubeapps#1377]
### Description:

When changing the namespace using the namespace selector in the appliaction view, it tries to fetch the same application name but in the new namespace causing a 404

### Steps to reproduce the issue:

1. Select an application
2. Change namespace

### Describe the results you received:

> Application tasteful-ladybug not found in the default namespace

### Describe the results you expected:

When changing the namespace, it's safer to go back to the AppList view.

**Comment by absoludity** [comment]
Currently solved (changing contents re-routes to the applications index).
