### ISSUE TITLE
Chart API needs to be upgraded from "extensions/v1beta1" to "apps/v1"

### ISSUE THREAD

**Issue by nishk5** [kubeapps/kubeapps#1378]
### Steps to reproduce the issue:

- `helm install stable/zeppelin`

### Describe the results you received:

rpc error: code = Unknown desc = unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
```

- Output of `helm list <kubeapps-release-name>`:

```
NAME            REVISION        UPDATED                         STATUS          CHART           APP VERSION     NAMESPACE
guiding-dragon  1               Fri Dec 13 15:45:03 2019        DEPLOYED        kubeapps-3.2.0  v1.7.1          default
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by andresmgot** [comment]
Hello @nishk5!

We are not the maintainers of the chart `stable/zeppelin`. You will need to create a similar issue in the chart repository: https://github.com/helm/charts

Hope that helps, let me close this issue but let us know if you find any issue related to Kubeapps.

**Comment by nishk5** [comment]
Realized it, sorry my bad. Thanks @andresmgot
