### ISSUE TITLE
Markup is not rendered correctly issues with comments and links

### ISSUE THREAD

**Issue by Siegfriedk** [kubeapps/kubeapps#1390]
### Description:

We have two render issues with the README.md Markdown in kubeapps:
- ```<!-- -->``` will be rendered as plain text in kubeapps
- Relative Links break inside kubeapps
  -  There was already a issue open for the links but its not solved: https://github.com/kubeapps/kubeapps/pull/709 (not sure though what this solved in detail, just wanted to mention it)

### Steps to reproduce the issue:

Create README.md which contains:

```

<!--ts-->
   * [Chart Details](#chart-details)
<!--te-->


# Chart Details
```

### Describe the results you received:

Rendered output:
```
<!--ts-->
   * [Chart Details](#chart-details)
<!--te-->


# Chart Details
```
and link #chart-details is broken.

### Describe the results you expected:

Rendered output:
```
   * [Chart Details](#chart-details)

# Chart Details
```
and link #chart-details works.

### Version of Helm, Kubeapps and Kubernetes:
v1.7.2

**Comment by andresmgot** [comment]
Hi @Siegfriedk,

Thanks for reporting the issue! The library we are using to parse the READMEs is probably ignoring the comments, we would need to check what's happening.

Regarding the relative links, it's true that it should be fixed, does it work for you if the relative link is outside the "block" `<!--- .... -->`?

**Comment by Siegfriedk** [comment]
The toc is not inside the comment block but i tested it nonetheless. It doesn't make a difference.

**Comment by andresmgot** [comment]
Hi @Siegfriedk sorry for the late response! Just letting you know that we are addressing your issue at #1476 and that the fix will be available in the next release. Thanks for reporting!
