### ISSUE TITLE
Creating dashboard with additional repos

### ISSUE THREAD

**Issue by pavel-butkevich-98** [kubeapps/kubeapps#1391]
# Description:

I'am creating new dashboard with additional github private repo using command:
helm install --name kubeapps --namespace kubeapps bitnami/kubeapps
 --set apprepository.initialRepos[0].name=qqq 
--set apprepository.initialRepos[0].url=https://raw.githubusercontent.com/pavel-butkevich-98/helm-test/master/ 
--set apprepository.initialRepos[0].authorizationHeader='Bearer ***'

**So, I have the next error:**
Error: YAML parse error on kubeapps/templates/apprepositories-secret.yaml: error converting YAML to JSON: yaml: line 13: did not find expected comment or line break

The problem is on the authorizationHeader,  without it everything works well. But I need it because my repo is private.

Can anybody help me?

**Comment by andresmgot** [comment]
Thanks for reporting the issue @pavel-butkevich-98! I am able to reproduce the issue. A fix is available at https://github.com/kubeapps/kubeapps/pull/1393/ and will be available in the next release.

**Comment by pavel-butkevich-98** [comment]
Thanks, I hope you PR will fix this issue.

**Comment by pavel-butkevich-98** [comment]
Thanks @andresmgot , I hope your PR will fix this issue.

**Comment by pavel-butkevich-98** [comment]
@andresmgot when will the next release be?

**Comment by andresmgot** [comment]
I have just merged the PR so the new version will be available today (once the related CI processes finish)

**Comment by pavel-butkevich-98** [comment]
@andresmgot could you please notify me when kubeapps 3.2.3 will be available?

**Comment by andresmgot** [comment]
@pavel-butkevich-98 it's now available
