### ISSUE TITLE
Please rollback the feature "Select the latest version when upgrading"

### ISSUE THREAD

**Issue by lich1710** [kubeapps/kubeapps#1407]
I just upgraded my Kubeapps and find this feature [Select the latest version when upgrading](https://github.com/kubeapps/kubeapps/pull/1284) highly dangerous.

- First of all, it auto selected latest version, and since there's no highlight or warning given, so whoever not paying attention can unintentionally upgrade the release to the latest chart version (which might break the whole app).
- Secondly, any reason why we must have this setting? I don't think it is a good idea, since if you want to update an app, you probably want to do it in a more controlled way, or manually done (instead of kubeapps auto set it for you) with proper testing on dev/stg before use in production.

Thus, I would really appreciate if the team can consider the points above and do a rollback of this feature.

**Comment by absoludity** [comment]
Hi there @lich1710 

I think it's important to remember that Kubeapps is enabling users to install helmcharts from a catalog. Admins may choose to use it for some use-cases, but normally admin controlled applications would be using gitops or their own staging/prod CI infrastructure - Kubeapps to this point has not attempted to address this use-case currently. Which is your use-case?

>     * First of all, it auto selected latest version, and since there's no highlight or warning given, so whoever not paying attention can unintentionally upgrade the release to the latest chart version (which might break the whole app).

If a user explicitly clicks "Upgrade" to upgrade an installed release I'd expect they either want to upgrade to a specific version of their choice, or simply the latest chart. What do you think is a good default for that upgrade? Or perhaps you mean it should have no value selected and force the user to select one from the available newer versions?

>     * Secondly, any reason why we must have this setting? I don't think it is a good idea, since if you want to update an app, you probably want to do it in a more controlled way, or manually done (instead of kubeapps auto set it for you) with proper testing on dev/stg before use in production.

Do you mean that you think upgrades should be done without helm at all (ie. manually using `kubectl` with known committed configs etc.), or using helm, just not the Kubeapps UI?

I'm not sure that Kubeapps is addressing the gitops use-case (a more controlled, upgrade from a known, tested version with a committed config). Kubeapps currently is a web UI in front of the helm CLI so we try to support the similar set of features, just via a web UI. We could enable the customization of which features are displayed in the UI (install only, install + upgrade), but the helm CLI could still be used (with the same inputs / changes), as long as the cluster RBAC policies allow those operations for the user. Ideally, (IMO), which features are presented / enabled should be decided directly from the configured k8s RBAC.

I'll wait to hear @andresmgot ' thoughts too.

**Comment by lich1710** [comment]
Hi @absoludity 

> If a user explicitly clicks "Upgrade" to upgrade an installed release I'd expect they either want to upgrade to a specific version of their choice, or simply the latest chart. 

Most of the time, when I click Upgrade, I just want to update values instead of chart version. For example: update number of replicas, update container image tag, update configmap or secrets. In case it's just me doing this kind of Upgrade, then probably I am using Kubeapps the wrong way.

> What do you think is a good default for that upgrade? Or perhaps you mean it should have no value selected and force the user to select one from the available newer versions?

In previous Kubeapps release, when I click Upgrade, the **chart version** is current version, and **values** is set to current values. Then, I choose what I want to upgrade, either value or chart version. In my opinion, this is the best way, since user is totally aware of what's the change is going to be.

> Do you mean that you think upgrades should be done without helm at all (ie. manually using kubectl with known committed configs etc.), or using helm, just not the Kubeapps UI?

Not what I meant, sorry for not to be clear. I was just trying to understand the rational behind this setting. Personally, I think chart version upgrade is a major event and could be a breaking change.
Since Kubeapps always select the latest Chart version, whoever update the values of a production release can accidentally update the chart version as well. And worst case can happen when the upgrade failed, application is down because the latest chart has no compatibility with previous chart values.

**Comment by absoludity** [comment]
> Most of the time, when I click Upgrade, I just want to update values instead of chart version.

Oh - interesting. Yes, when we discussed updating the default value for upgrade, I was assuming that the intent to upgrade a chart is always updating the chart version, but that's not necessarily the case, as you've shown. I'd not considered `helm upgrade` itself being the only way to update the values without changing the chart version.

If the normal use-case is indeed "update values" I agree, reverting to leaving chart version at the current version would be the simplest solution. I'll create a PR tomorrow.

Thanks for the feedback.

**Comment by lich1710** [comment]
Great! Thanks @absoludity ...looking forward for the new release :)

**Comment by andresmgot** [comment]
Thanks for the feedback @lich1710! Indeed we were thinking on the use case of upgrading when the  user wants the latest version, not in the case in which they just want to change some values.

It's true that doing that change without noticing the user may be risky (even though we show now changes in a specific tab) and that the step to select the latest version is trivial from a user point of view.

I am okay removing that feature and making the version selection explicit :+1:
