### ISSUE TITLE
Decide on a logging library (glog, klog or logrus)

### ISSUE THREAD

**Issue by SimonAlling** [kubeapps/kubeapps#1410]
I've noticed that both `github.com/golang/glog`, `github.com/sirupsen/logrus` and `k8s.io/klog` (my fault) are used for logging in Kubeapps. Should we perhaps decide on one of them and use it consistently throughout the code base?

**Comment by absoludity** [comment]
Yep, though I'll wait for Andres (he's been on the project much longer than me) to comment on the historical choices there.

**Comment by andresmgot** [comment]
We've been using `logrus` since I joined the project and I think it's more widely used here so I would standardize on that one unless someone has a better reason. The references to `glog` are older ones (that has been maintained only in the `apprerepository-controller` service).
