### ISSUE TITLE
big bug

### ISSUE THREAD

**Issue by zaourzag** [kubeapps/kubeapps#1427]
error: error executing jsonpath "{.items[0].metadata.name}": Error executing template: array index out of bounds: index 0, length 0. Printing more information for debugging the template:
        template was:
                {.items[0].metadata.name}
        object given to jsonpath engine was:
                map[string]interface {}{"apiVersion":"v1", "items":[]interface {}{}, "kind":"List", "metadata":map[string]interface {}{"resourceVersion":"", "selfLink":""}}

Visit http://127.0.0.1:8080 in your browser to access the Kubeapps Dashboard
error: TYPE/NAME and list of ports are required for port-forward
See 'kubectl port-forward -h' for help and examples

**Comment by absoludity** [comment]
Thanks @zkp12 . Can you please let us know:
*  what operating system you're using?
* exact details of the command you are running
* output of `helm version`

I assume this is happening when you are installing Kubeapps itself?

**Comment by zkp12** [comment]
I use  windows 10 home with minekube

**Comment by andresmgot** [comment]
hi @zkp12,

Unfortunately we don't have all the necessary steps for running Kubeapps in Windows documented. Note that when running a `export` command you need to use the analogue for Windows. In any case, if you send us a screenshot (or the list of commands you are using) we can help you debugging the issue and document it later on.
