### ISSUE TITLE
After I submit a provision request, kubeapps blank-screens

### ISSUE THREAD

**Issue by arschles** [kubeapps/kubeapps#143]
I'm running kubeapps v0.4.0:

```console
$ kubeapps version
Kubeapps Installer version: v0.4.0
```

And ran `kubeapps up` against an [AKS](https://docs.microsoft.com/en-us/azure/aks/intro-kubernetes) cluster (which has no RBAC). I installed service-catalog with RBAC turned off and then the open service broker for azure (from the https://svc-catalog-charts.storage.googleapis.com and https://kubernetescharts.blob.core.windows.net/azure chart repos, respectively)

Then, when I went to provision an [azure-cosmos-document-db](https://github.com/Azure/open-service-broker-azure/blob/master/docs/modules/cosmosdb.md#service-azure-cosmos-document-db) instance (with the default plan), I clicked on "provision" (from [this page](http://localhost:53576/services/brokers/osba/classes/azure-cosmos-document-db)), named my instance, chose a namespace, pressed "submit", I get redirected back to http://localhost:53576/services/instances and get a blank screen.

The below is what I see in the developer console when the blank screen loads

![screen shot 2018-03-01 at 10 04 18 am](https://user-images.githubusercontent.com/70865/36861161-f966316c-1d37-11e8-94e7-70b65626a32a.png)

... If I reload http://localhost:53576/services/instances, I see all my existing instances plus the one I just provisioned.

**Comment by prydonius** [comment]
fixed in https://github.com/kubeapps/dashboard/issues/94, will be part of the next release!

**Comment by arschles** [comment]
awesome!! fwiw, the title of that issue says "your first service instance", but this seems to happen on all provisions...

**Comment by prydonius** [comment]
@arschles good point, and you're right that this affects all provisions. The PR that fixed it is https://github.com/kubeapps/dashboard/pull/102 and essentially the fix was to just refresh the catalog after provisioning.

**Comment by spacecat** [comment]
In the docs it says:

Kubeapps assumes a working Kubernetes (v1.8+) **with RBAC enabled** and kubectl installed and configured to talk to your Kubernetes cluster. Kubeapps binaries are available for both Linux and OS X, and Kubeapps has been **tested with** both minikube, Google Kubernetes Engine (GKE) and **Azure Container Service (AKS)**.


AFAIK AKS does not have support for RBAC.

Does kubeapps still work without it or how should I interpret the docs?

**Comment by arapulido** [comment]
We can close this issue, as this was already fixed

**Comment by spacecat** [comment]
Thanks! Will try it out then.
