### ISSUE TITLE
The latest version of kubernetes has make api of apps/v1beta1 to be release

### ISSUE THREAD

**Issue by AlpherJang** [kubeapps/kubeapps#1431]
### Description:

when i try to install bitcoind version 0.2.2 into latest version of minikube it's reported 
"rpc error: code = Unknown desc = unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta2"

### Steps to reproduce the issue:

1.go to catalog page
2.choose catalog named bitcoind
3.click deploy and submit the form without edit 

### Describe the results you received:

Sorry! Something went wrong.
rpc error: code = Unknown desc = unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta2"

### Describe the results you expected:

deploy success

### Additional information you deem important (e.g. issue happens only occasionally):

maybe it's because of apps/v1beta2 api is release , so we can update template set apps/v1beta2 
to apps/v1

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}

```

- Output of `helm list <kubeapps-release-name>`:

```
NAME    	REVISION	UPDATED                 	STATUS  	CHART         	APP VERSION	NAMESPACE
kubeapps	1       	Fri Jan 10 19:29:16 2020	DEPLOYED	kubeapps-3.2.3	v1.7.2     	kubeapps 
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by andresmgot** [comment]
Hi @AlpherJang,

We are actually not maintaining the charts that are listed in Kubeapps. In this case you should reach the bitcoind maintainers: 

https://github.com/helm/charts/blob/master/stable/bitcoind/Chart.yaml#L16

That error is present in Kubernetes versions newer than 1.16. If you need to use that chart and it doesn't get updated you should be able to deploy it in a Kubernetes cluster 1.15.

**Comment by AlpherJang** [comment]
ok,thanks for your help

**Comment by fabianschwarzfritz** [comment]
Hi @andresmgot ,

this is indeed a very interesting issue we are facing as well. There is nothing kubeapps can do, it's a matter of the chart. Still for the user it is very confusing to have a kind of marketplace to select charts from and after a selection the installation just fails. The first thing people naturally do is blame kubeapps or hosting team...

It's good on one hand to see what went wrong during the installation. But on the other hand it would be very best to see a nicer error message for the users, explaining that this is an issue of the chart itself and the author is the one to be contacted. Do you think this would help to clarify the matter for the user?

Cheers, Fabian

**Comment by AlpherJang** [comment]
Hi @fabianschwarzfritz 
actually i think there is very clear message of error ,but there's no striking mark to tell user where the package from and not enough infomation of chart's content. it's not good for us to find reason or fix problem
i hope my rude description will help

**Comment by andresmgot** [comment]
That's a good point. We can improve the user experience here. Let me create a separate issue for tracking this. To take it into account, what would be the best error message in this case?
