### ISSUE TITLE
Provide a way to provision multiple copies of kubeapps into the same cluster?

### ISSUE THREAD

**Issue by nomisbeme** [kubeapps/kubeapps#144]
Kubeapps provisions some components into shared namespaces e.g sealedsecrets controller with no way to override the namespace used or disable installation of these shared components. 

This is less than ideal on the Kubernetes cluster I use for development which has multiple users, each with their own namespace. I managed to accidentally break other users on this cluster with a naive "kubeapps up" and "kubeapps down" when trying out the 0.3.0 based on the quickstart instructions.

A --disable-shared-components or --sealed-secrets-namespace option would be helpful for me.

**Comment by prydonius** [comment]
FYI, sealed-secrets has now been removed from the Kubeapps distribution. Kubeless is the only remaining thing that would be an issue with multiple copies, I believe. The rest of the Kubeapps controllers/services should work in their own namespaces.

cc @andresmgot wdyt?

**Comment by andresmgot** [comment]
yes, only one copy of Kubeless per cluster is supported right now. It should work as well if the RBAC permissions of the Kubeless controller are limited to a namespace but that is not been tested. In any case I think that our approach is to provide a single Kubeapps application that can be used in a multi-tenancy cluster without having to install it per cluster.

**Comment by prydonius** [comment]
@andresmgot presumably the Kubeless controller is listening to the cluster-scoped Functions endpoint, which would need to be changed if it were to be limited by a namespace. I don't think it makes sense to do that for Kubeless, though.

For Kubeapps controllers like the apprepository-controller, it's fine because we only expect to create AppRepository resources within the `kubeapps` namespace.

**Comment by andresmgot** [comment]
Yes, it's something doable without kubeless.

**Comment by arapulido** [comment]
Closing this one now, as Kubeless is no longer bundled with Kubeapps
