### ISSUE TITLE
[Helm3] Incorrect error message when installing to namespace without access

### ISSUE THREAD

**Issue by absoludity** [kubeapps/kubeapps#1464]
### Description:

If I attempt to install into a namespace to which I don't have access to install (particularly, I can't even read secrets), kubeapps displays the error: "<release-name> already exists, try a different name", which is incorrect (and a bad experience if you keep trying :P).

The actual issue is shown below:
![409-incorrect-error](https://user-images.githubusercontent.com/497518/72575195-b9ab4480-391f-11ea-8d04-fd8179ff2376.png)

### Steps to reproduce the issue:

1. Login as a normal user and choose a namespace to which you don't have access (ie. easiest to use a user who doesn't have access to read secrets in default)
2. Deploy a chart

ER: An error along the lines of "You do not have access to install in the namespace 'foo'".
Actual result: see above image.

Putting this as low priority because, realistically, we should not be presenting people with namespaces to which they don't have access, the underlying issue there is that we add `default` without knowing if the user has access. Once that is fixed this issue won't be so obvious, though still worth fixing.

**Comment by lindhe** [comment]
We also get this issue for other errors too. I had a bug recently that made me try to install a chart from a repo that was not added to the App Repositories.

![Screenshot from 2020-01-21 14-32-14](https://user-images.githubusercontent.com/7773090/72894351-6409da00-3d1b-11ea-8c1c-729b68e53f4a.png)
![Screenshot from 2020-01-21 14-39-13](https://user-images.githubusercontent.com/7773090/72894350-6409da00-3d1b-11ea-86a8-8e709886ca83.png)

**Comment by absoludity** [comment]
> I had a bug recently that made me try to install a chart from a repo that was not added to the App Repositories.

Let us know if you have steps to reproduce this Andreas. It looks like a different issue, but keen to be able to reproduce it (I'm not sure if you mean that you didn't actually have the bitnami repository installed when kubeapps somehow prompted you to install apache 7.3.3).

**Comment by lindhe** [comment]
I can reproduce it:
1. Go to Catalog and navigate to the `bitnami/apache` Chart, click Deploy
2. Open App Repositories in another tab
3. Delete the bitnami repo
4. Head back to the first tab, and click Submit

![Screenshot from 2020-01-23 22-18-41](https://user-images.githubusercontent.com/7773090/73024852-b7208180-3e2e-11ea-8740-b96245682240.png)
![Screenshot from 2020-01-23 22-18-03](https://user-images.githubusercontent.com/7773090/73024853-b7208180-3e2e-11ea-8332-1de4461402a7.png)

**Comment by absoludity** [comment]
Yeah it's a different cause, but related in that an incorrect error message is presented. In your case, I'd expect something like "Chart bitnami/apache not found in configured repositories".

Not sure it's worth raising the priority when it requires deleting the repository in a separate tab (or via the CLI)?

**Comment by lindhe** [comment]
I would expect it to print the message that the HTTP request returns (see Response of my 404)
