### ISSUE TITLE
Prepare AppRepository for being a per-namespace resource

### ISSUE THREAD

**Issue by absoludity** [kubeapps/kubeapps#1495]
Initial work to enable creating per-namespace AppRepositories, which is a pre-requisite for private registry support. See [design doc](https://docs.google.com/document/d/1YEeKC6nPLoq4oaxs9v8_UsmxrRfWxB6KCyqrh2-Q8x0/edit?ts=5e2adf87#) for more info and discussion.

Parent task: #1256 

Tasks:
- [x] Add ClusterRole for reading AppRepositories only
- [x] API: Update the Kubeapps API endpoint to save the AppRepository in the specific namespace (initially always kubeapps' namespace)
- [x] UI: Update URI for AppRepositories to include namespace
- [x] Chart: Add feature-flag / charm switch for perNamespaceAppRepositories, defaulting to false, so work can continue without affecting users.
- [x] UI: When feature-flag enabled, Display AppRepositories for current namespace or all namespaces

**Comment by andresmgot** [comment]
Asking some questions here to avoid polluting the design doc:

>  API: Update the Kubeapps API endpoint to save the AppRepository in the specific namespace (initially always kubeapps' namespace)

The API currently creates the secrets related to the AppRepository. What do you plan to do with those? If the backend does that we'd need to extend the ClusterRole to read and write secrets in all namespaces (which can be too much). The other option is to move that functionality to the dashboard.

> UI: When feature-flag enabled, Display AppRepositories for current namespace (but to avoid initial confusion, include "Looking for site-wide app repositories? Select 'All Namespaces' in the namespace switcher above" or similar (and vice-versa)

Weren't we going to treat AppRepositories in the `kubeapps` namespace as global? If those keep being global, even if the flag is enabled, people will see the usual catalog.

**Comment by absoludity** [comment]
> Asking some questions here to avoid polluting the design doc:

Comments on the design doc are probably easier to manage (as we can resolve them and keep things clear), but whatever you prefer.

> 
> > API: Update the Kubeapps API endpoint to save the AppRepository in the specific namespace (initially always kubeapps' namespace)
> 
> You are planning to use the user serviceaccount to create the AppRepositories?

Not in the above case. By "initially always kubeapps' namespace", I simply meant although the backend API would be updated here to save in a specific namespace passed by the frontend, it would initially be Kubeapps' own namespace to avoid a breaking change. As per the section "[AppRepository and Secrets per namespace](https://docs.google.com/document/d/1YEeKC6nPLoq4oaxs9v8_UsmxrRfWxB6KCyqrh2-Q8x0/edit?ts=5e2adf87#heading=h.396p9pyw1xwi)", I'm planning that the AppRepository will be saved with the *users* credentials.

> Maybe it's better to give the backend to write apprepositories in all namespaces as well. This is because, the typical roles (e.g. `edit`, `view`) won't have permissions to do so and the user will find a forbidden error. Maybe it's better to use the backend serviceaccount to create the AppRepository and the user sa to create the related secrets.

Users will have access to their own namespaces (it's needed to install in the namespace), and as above, having the frontend initially send `kubeapps` as the namespace just maintains the current behaviour until the feature flag is added. Check the above section of the design doc - let's discuss there.

> 
> > UI: When feature-flag enabled, Display AppRepositories for current namespace (but to avoid initial confusion, include "Looking for site-wide app repositories? Select 'All Namespaces' in the namespace switcher above" or similar (and vice-versa)
> 
> Weren't we going to treat AppRepositories in the `kubeapps` namespace as global?
Yes, I'm assuming "All namespaces" in the UI for creating an app repository (with the feature flag on) will mean saving in the `kubeapps` namespace.

> If those keep being global, even if the flag is enabled, people will see the usual catalog.

Yes, they will still be able to see the usual catalog, but they'll be able to create AppRepositories in their own namespace. Not sure if I'm missing something in the question here. Let's discuss on a call in a few mins.

**Comment by migmartri** [comment]
> UI: When feature-flag enabled, Display AppRepositories for current namespace (but to avoid initial confusion, include "Looking for site-wide app repositories? Select 'All Namespaces' in the namespace switcher above" or similar (and vice-versa)

Wouldn't make sense to show both the repositories available in your namespace as well as the ones that have been `inherited` maybe in read only?

**Comment by absoludity** [comment]
> Wouldn't make sense to show both the repositories available in your namespace as well as the ones that have been `inherited` maybe in read only?

The purpose of this view is to be able to create, edit, update app repositories. App repositories exist in specific namespaces, even if they are available for use in other namespaces they can't be edited/updated as if they are part of a different namespace.

So I'm torn. Yes, we could clearly demarcate with "AppRepositories defined in other namespaces" or similar, but the complexity of this UX, which is specifically for creating, editing, updating AppRepos in a specific namespace, goes up quite a bit.

> Actually this can be confusing in my mind, if I am a Kubeapps operator I might think that by selecting `all namespaces` I might get the list of all the repos in all namespaces.

Yep, Andres had the same reaction. I'm re-thinking, but I think we need to be clear about the purpose of this view. I'll move this discussion back to a section of the design doc.

**Comment by migmartri** [comment]
Maybe it is because we are seeing from different angles. From the technical POV you are right, the current UI just CRUDs on app repositories CRDs that are physically present in the selected NS.

From the UX POV I would challenge that. 

As a regular user: it might be strange to me to see a list of apps but when I click on app-repositories there is none. Sure I could select "All namespaces" but I am not even convinced that's the logical path, why do I care about all namespaces? I care about this namespace (or the ones I have access to). By following this model we do not have an answer either to disable repositories that I inherited, if we were showing them in the same UI, we could in the future allow them to remove them.

As an operator: "All namespaces" means in my head repositories from all namespaces, and I'd say that this persona should be able to remove/tweak/fix unwanted repositories.

Thanks for working on this :)

**Comment by absoludity** [comment]
> As a regular user: it might be strange to me to see a list of apps but when I click on app-repositories there is none.

As a regular user in a namespace, you probably wouldn't (and shouldn't) even have RBAC required to see the app-repositories defined for all namespaces (ie. in the separate `kubeapps` repository), let alone manipulate them. We may in the future want to query the `assetsvc` so we can indicate to the user on this page the other repositories active for this namespace, but I don't think that can be replaced with a query of the AppRepository resources themselves?


> As an operator: "All namespaces" means in my head repositories from all namespaces, and I'd say that this persona should be able to remove/tweak/fix unwanted repositories.

Yes, this is Andres' point too on the PR. I'm working to update to this in that PR.

> 
> Thanks for working on this :)

Thanks for the input!

**Comment by andresmgot** [comment]
> As a regular user: it might be strange to me to see a list of apps but when I click on app-repositories there is none. Sure I could select "All namespaces" but I am not even convinced that's the logical path, why do I care about all namespaces? I care about this namespace (or the ones I have access to). By following this model we do not have an answer either to disable repositories that I inherited, if we were showing them in the same UI, we could in the future allow them to remove them.

That's a good point. We can see the app repositories view as the list of AppRepositories in this namespace or as the list of helm registries I can use as a user (current behavior) right now. I think the second is more useful because it allows me to filter the chart catalog by repository (not only edit/delete repositories).

I think that if we add the namespace column in all the cases (and we always list the apprepositories of the `kubeapps` namespace) we can have that UX. Then, if a user tries to refresh/delete the apprepository in the `kubeapps` namespace without permissions to do so it will receive the proper error: permission denied.

**Comment by absoludity** [comment]
I certainly think we should do both (that's exactly what I meant when I confused you with [here](https://github.com/kubeapps/kubeapps/pull/1503#discussion_r376297553) and [here](https://github.com/kubeapps/kubeapps/pull/1503#discussion_r376295504))

I want to show both: AppRepositories which are defined in this namespace, as well as AppRepositories which are defined elsewhere (by other people) but available in this namespace (currently just the global ones, but later others). The thing is, unless you assume cluster-admin, we can only query the k8s server for the former - the AppRepositories which are defined in this namespace, since the user can access the namespace, but not necessarily others (such as kubeapps own namespace). I've updated the doc with these constraints in a UX section, but didn't get a chance today to write the proposal, but it's basically presenting both (eventually). The ones from the current namespace we can do now, but for the app repos defined elsewhere which have been made available in this namespace, we will be able to query the `assetsvc`. Let me write it up on Monday and we can chat through it then.

**Comment by andresmgot** [comment]
ah, I see, that should be "simple" enough if we move the list call to the backend service and we use the backend serviceaccount to retrieve those "global" apprepositories (more or less what I've done in #1507).
