### ISSUE TITLE
Sync per-namespace AppRepositories

### ISSUE THREAD

**Issue by absoludity** [kubeapps/kubeapps#1496]
Support for sync'ing per-namespace AppRepositories, which is a pre-requisite for private registry support. See [design doc](https://docs.google.com/document/d/1YEeKC6nPLoq4oaxs9v8_UsmxrRfWxB6KCyqrh2-Q8x0/edit?ts=5e2adf87#) for more info and discussion.

Parent task: #1256 . Follows (but can be done in parallel with) #1495 

- [x] API: Ensure the app repository credentials (not docker registry secrets) are saved in the specific namespace (using the users' auth)
- [x] API: Ensure the app repository credentials (not docker registry secrets) are copied to Kubeapps' own namespace (with the service account auth) using a canonical name (namespace.repo for eg.)
- [x] API: Ensure both are deleted when an AppRepository is deleted
- [x] chart-sync: With FF enabled, chart-sync should sync AppRepositories across all namespaces

**Comment by andresmgot** [comment]
>  API: Ensure the app repository credentials (not docker registry secrets) are copied to Kubeapps' own namespace (with the service account auth) using a canonical name (namespace.repo for eg.)

This could be a RBAC issue. A user with permissions to access the `kubeapps` namespace will have access to the credentials of all the registries. Maybe it's better to give the apprepository-controller RBAC permissions to create jobs and cronjobs cluster-wide?

**Comment by absoludity** [comment]
> This could be a RBAC issue. A user with permissions to access the `kubeapps` namespace will have access to the credentials of all the registries.

User's don't require permission to access the `kubeapps` namespace for this point - that's what I meant by `copied to Kubeapps' own namespace (with the service account auth)`. More details in "[AppRepository and Secrets per namespace](https://docs.google.com/document/d/1YEeKC6nPLoq4oaxs9v8_UsmxrRfWxB6KCyqrh2-Q8x0/edit?ts=5e2adf87#heading=h.396p9pyw1xwi)" , but with this, a user only requires the normal perms in their own namespace, and Kubeapps only requires the ability to read its own API resource (AppRepositories) in other namespaces.

> Maybe it's better to give the apprepository-controller RBAC permissions to create jobs and cronjobs cluster-wide?

I had thought you were completely against more cluster-wide perms for Kubeapps, which is why I was really happy to find the above solution where the users' RBAC is just for their own namespace, and Kubeapps only needs to read AppRepositories (not secrets, nor cronjobs or other resources which could increase the barrier of installation). But happy to reconsider. Let's chat about this on the call too.
