### ISSUE TITLE
Add generated statik pkg to gitignore

### ISSUE THREAD

**Issue by prydonius** [kubeapps/kubeapps#150]
We currently version the `generated/` and `static/` folders to support installing the CLI using `go get`, but this is causing more issues than it's worth. Since the manifests are generated in a random order each time, this will change even when there are no actual changes. Now that we have binaries for all platforms, we should gitignore those folders and remove the `go get` support.

**Comment by arapulido** [comment]
@prydonius wasn't this done?

**Comment by prydonius** [comment]
@arapulido nope, it's still an issue (e.g. https://github.com/kubeapps/kubeapps/commit/e2cd94cb7ce3dae7996c89ef455eb647eadd5590 in the most recent release).
