### ISSUE TITLE
Authentication with Openshift 4.2 and Helm 3

### ISSUE THREAD

**Issue by cybrwshl** [kubeapps/kubeapps#1500]
### Description:

Is it possible to use OpenShifts oauth2 to authenticate user for Kubeapps?
And if not, what can ldap authentication for kubeapps look like?

Our OpenShift Cluster uses an internal LDAP Server for user authentication.
So we tried to use Dex to provide an OpenID interface for kubeapps authentication against ldap.

This looks something like that:
```
Kubeapps --> Dex --> LDAP --> Dex --> oauth2_proxy --> Kubeapps --> Kubernetes
```

### Describe the results you received:

The basic workflow seems to work, but when returning to kubeapps one gets an unauthorized return code from `/api/kube`.

```log
10.11.12.13 - - [2020/02/04 09:35:53] kubeapps.apps.example.com GET - "/oauth2/start" HTTP/1.1 "Firefox/72.0" 302 327 0.000
10.11.12.13 - user@example.com [2020/02/04 09:35:58] [AuthSuccess] Authenticated via OAuth2: Session{email:user@example.com user:CnVzZXJAbGRhcCUK token:true id_token:true created:2020-02-04 09:35:58.888497372 +0000 UTC m=+50.233218241 expires:2020-02-05 09:35:58 +0000 UTC}
10.11.12.13 - - [2020/02/04 09:35:58] kubeapps.apps.example.com GET - "/oauth2/callback?code=SECRET&state=SECRET%3A%2F" HTTP/1.1 "Firefox/72.0" 302 24 0.031
10.11.12.13 - - [2020/02/04 09:35:58] kubeapps.apps.example.com GET localhost:8080 "/" HTTP/1.1 "Firefox/72.0" 200 409 0.001     
*** SNIP ***
10.11.12.13 - user@example.com [2020/02/04 09:35:59] kubeapps.apps.example.com GET localhost:8080 "/api/kube/" HTTP/1.1 "Firefox/72.0" 401 165 0.011
10.11.12.13 - - [2020/02/04 09:35:59] kubeapps.apps.example.com GET localhost:8080 "/static/css/main.c9d8cde1.css.map" HTTP/1.1 "Firefox/72.0" 304 0 0.001
```
### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
```

- Output of `helm list <kubeapps-release-name>`:

```
kubeapps-3.3.1    v1.8.1
```

- Output of `kubectl version`:

```
Client Version: openshift-clients-4.3.0-201910250623-88-g6a937dfe
Server Version: 4.2.16
Kubernetes Version: v1.14.6+8bbaf43
```

**Comment by absoludity** [comment]
Hi there @cybrwshl .



> Is it possible to use OpenShifts oauth2 to authenticate user for Kubeapps?

I've not tried with OpenShift's own oauth2 yet (it's something I've wanted to get a chance to try).

> And if not, what can ldap authentication for kubeapps look like?

Yes, I use a local dev env for Kubeapps with this setup (ie. dex + ldap). You can take a look at the setup by ensuring you have [kind](https://kind.sigs.k8s.io/) installed, then with this repo checked out, run `make cluster-kind`, export the KUBECONFIG, then `make deploy-dev` (the main parts you're probably interested in are in the [script/deploy-dev.mk](https://github.com/kubeapps/kubeapps/blob/master/script/deploy-dev.mk)

You didn't mention, but I assume you've got your API server running with the required oidc args? If so, to debug why you're getting a 401 I'd check your k8s api server logs.

**Comment by absoludity** [comment]
Closing as we're not currently supporting OpenShift, but reopen if you've a patch or more info as above.

**Comment by davidkarlsen** [comment]
Openshift does it's own thing with auth, so I think this is the way to go in these cases: https://docs.openshift.com/container-platform/4.6/authentication/configuring-oauth-clients.html#oauth-register-additional-client_configuring-oauth-clients
