### ISSUE TITLE
CreateContainerConfigError 

### ISSUE THREAD

**Issue by Atul56789** [kubeapps/kubeapps#1505]
Hi I am trying to deploy Kubeapps in my private cluster where i have hosted my private helm repo and docker registry. After deploying the kubeapps with the help of helm chart facing below error and not able to add my local helm repo.
<img width="701" alt="kubeapps error" src="https://user-images.githubusercontent.com/49866859/73967701-66387f00-493e-11ea-9159-b4a20d5811b1.PNG">
 moreover if i check the status of the pod it giving below error
<img width="434" alt="pod state" src="https://user-images.githubusercontent.com/49866859/73967917-d6df9b80-493e-11ea-870e-5e22a2bfd922.PNG">

and i am not able to add my local helm repo.
<img width="198" alt="local helm repo" src="https://user-images.githubusercontent.com/49866859/73968144-3342bb00-493f-11ea-906e-898612da0769.PNG">
<img width="882" alt="local repo" src="https://user-images.githubusercontent.com/49866859/73968150-3473e800-493f-11ea-850c-8ae3f682123c.PNG">

**Comment by absoludity** [comment]
Hi there. The error you're seeing adding the repo is just a result of the initial issue that you've pointed out yourself: some of the pods are not running.

According to the message you've shown, the issue is that a pod security policy with the setting `runAsNonRoot: true` is in effect and Kubernetes thinks the image wants to run as root. I'm not sure why at that point, as our images run with the UID 1001. I even updated my own deployment of `kubeapps-internal-apprepository-controller` with `runAsNonRoot: true` and confirmed it works fine. So I'm not sure why this might be overridden in your cluster?

Do you have any pod-security-policies in effect? If so, can you paste them? Also if you can paste any values you set when deploying Kubeapps, as well as the version etc. Thanks!

**Comment by Atul56789** [comment]
<img width="182" alt="pod context security" src="https://user-images.githubusercontent.com/49866859/74001650-6bbfb480-4992-11ea-89a0-3e18b7e84864.PNG">
hi the pod security context in Values.yaml file is false

**Comment by Atul56789** [comment]
chart version is 
<img width="918" alt="version kubeapps" src="https://user-images.githubusercontent.com/49866859/74002642-c3abea80-4995-11ea-8f7b-2c5dca59c107.PNG">

**Comment by andresmgot** [comment]
By default, as Michael points out, those images should run with the user ID 1001 so I am not sure why you are getting that error. To try to debug the issue, can you send the YAML of one of the pods failing? For example:

```
kubectl get po -o yaml -n kubeapps kubeapps-internal-assetsvc... (complete here with the name of the pod)
```

In any case, if you set the securityContext, that will be enforced so you the error should go away. You can do that setting this flag when installing the chart: `--set securityContext.enabled=true`.

**Comment by Atul56789** [comment]
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/psp: restricted
    seccomp.security.alpha.kubernetes.io/pod: docker/default
  creationTimestamp: "2020-02-07T08:13:03Z"
  generateName: kubeapps-internal-apprepository-controller-5796f99f98-
  labels:
    app: kubeapps-internal-apprepository-controller
    pod-template-hash: 5796f99f98
    release: kubeapps
  name: kubeapps-internal-apprepository-controller-5796f99f98-n2zp6
  namespace: kubeapps
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: kubeapps-internal-apprepository-controller-5796f99f98
    uid: 0a6d6ae6-6c7e-4aca-8ea6-d759e97b146a
  resourceVersion: "1074295"
  selfLink: /api/v1/namespaces/kubeapps/pods/kubeapps-internal-apprepository-controller-5796f99f98-n2zp6
  uid: 93abdbd4-25d8-455c-a2f3-41cea7b539a6
spec:
  containers:
  - args:
    - --user-agent-comment=kubeapps/v1.8.1
    - --repo-sync-image=docker.io/kubeapps/asset-syncer:latest
    - --repo-sync-cmd=/asset-syncer
    - --namespace=kubeapps
    - --database-secret-name=kubeapps-mongodb
    - --database-secret-key=mongodb-root-password
    - --database-type=mongodb
    - --database-url=kubeapps-mongodb
    - --database-user=root
    - --database-name=charts
    command:
    - /apprepository-controller
    image: docker.io/kubeapps/apprepository-controller:latest
    imagePullPolicy: Always
    name: controller
    resources:
      limits:
        cpu: 250m
        memory: 128Mi
      requests:
        cpu: 25m
        memory: 32Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kubeapps-internal-apprepository-controller-token-7dbdx
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: cnetest-k8s-node-2
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1
    supplementalGroups:
    - 1
  serviceAccount: kubeapps-internal-apprepository-controller
  serviceAccountName: kubeapps-internal-apprepository-controller
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kubeapps-internal-apprepository-controller-token-7dbdx
    secret:
      defaultMode: 420
      secretName: kubeapps-internal-apprepository-controller-token-7dbdx
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-02-07T08:12:02Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-02-07T08:12:02Z"
    message: 'containers with unready status: [controller]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-02-07T08:12:02Z"
    message: 'containers with unready status: [controller]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-02-07T08:13:03Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: docker.io/kubeapps/apprepository-controller:latest
    imageID: ""
    lastState: {}
    name: controller
    ready: false
    restartCount: 0
    state:
      waiting:
        message: container has runAsNonRoot and image will run as root
        reason: CreateContainerConfigError
  hostIP: 192.168.200.16
  phase: Pending
  podIP: 10.233.65.54
  qosClass: Burstable
  startTime: "2020-02-07T08:12:02Z"

**Comment by Atul56789** [comment]
above is the yaml attached please let me know what is the error

**Comment by andresmgot** [comment]
The problem seems to be that you are using the development chart:

```
    image: docker.io/kubeapps/apprepository-controller:latest
```

This is our dev image, the ones published for production are in the bitnami registry: `bitnami/kubeapps-apprepository-controller`.

You should install the chart using the bitnami registry (I assume you installed the chart from the directory available in this repository):

```
helm repo add bitnami https://charts.bitnami.com/bitnami             
helm repo update
helm install -n kubeapps kubeapps bitnami/kubeapps
```

**Comment by Atul56789** [comment]
Hi Andres,

I have used below repo and the images which i have used are below

![image](https://user-images.githubusercontent.com/49866859/74024597-3d5ccc00-49c8-11ea-8668-9a9a04a09987.png)
![image](https://user-images.githubusercontent.com/49866859/74025829-d391f180-49ca-11ea-9536-6f72a41ce328.png)

**Comment by andresmgot** [comment]
Can you clarify how did you install the kubeapps chart? Executing the commands I showed you before should fix your issue.

**Comment by Atul56789** [comment]
Hi Andres,
I agree by executing the commands which you have mentioned it will work the problem is i am deploying this in an air gaped cluster where there is no internet access so i first have to download the images and push them to my private docker registry and same with the helm charts.

**Comment by Atul56789** [comment]
Thanks Andres issue is resolved,hence closing this issue.
