### ISSUE TITLE
Wrong error returned when the installation fails

### ISSUE THREAD

**Issue by andresmgot** [kubeapps/kubeapps#1508]
### Description:

When the application fails to be created, it fails to delete that release (because there is no release). When this happens the error contains "not found" which is considered a 404 causing a wrong response:

![Screenshot from 2020-02-10 17-27-37](https://user-images.githubusercontent.com/4025665/74168870-aa6f9c00-4c2a-11ea-9bf5-bde831fd5ad5.png)

This is the real message:

```
{"code":404,"message":"Release \"mellow-level\" failed: unable to build kubernetes objects from release manifest: error validating \"\": error validating data: ValidationError(Deployment.metadata): unknown field \"selector\" in io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta. Unable to delete failed release: uninstall: Release not loaded: mellow-level: release: not found"}
```

A similar issue happens when the user doesn't have permissions to get a resource (e.g. ClusterRole). The request fails but the error returned is not relevant:

![Screenshot from 2020-02-10 17-32-21](https://user-images.githubusercontent.com/4025665/74169263-544f2880-4c2b-11ea-9c8c-49dfeada228b.png)

The real error:

```
{"code":409,"message":"Release \"dynamic-weight\" failed: rendered manifests contain a resource that already exists. Unable to continue with install: could not get information about the resource: clusterroles.rbac.authorization.k8s.io \"dynamic-weight-prometheus-alertmanager\" is forbidden: User \"system:serviceaccount:kubeapps:kubeapps-edit\" cannot get resource \"clusterroles\" in API group \"rbac.authorization.k8s.io\" at the cluster scope. Unable to delete failed release: uninstall: Release not loaded: dynamic-weight: release: not found"}
```

### Steps to reproduce the issue:

1. Deploy the couchdb-operator chart (404)

or

1. Deploy the prometheus chart (409)

**Comment by absoludity** [comment]
The two errors here seem to be the same two errors listed on #1464 .

**Comment by andresmgot** [comment]
I forgot about that one. Yes, error messages there assume too much...
