### ISSUE TITLE
kubeless pods don't have the `created-by=kubeapps` label

### ISSUE THREAD

**Issue by sebgoa** [kubeapps/kubeapps#151]
Seems that the kubeless resources (at least pods) don't get labeled with `created-by=kubeapps` if kubeless is bootstrapped with `kubeapps up` 

we should check the manifests

**Comment by prydonius** [comment]
@sebgoa are you referring to pods created from the UI not having that label? Or are you talking about the `kubeless-controller` itself?

**Comment by sebgoa** [comment]
what I recall was the controller, since the output of `kubeapps up` never showed the kubeless controller,zk etc pods.

**Comment by prydonius** [comment]
@sebgoa okay thanks - I think this has been fixed, but I'll double check to be sure.
