### ISSUE TITLE
Error reporting in UI assumes user credentials are the problem

### ISSUE THREAD

**Issue by absoludity** [kubeapps/kubeapps#1546]
While debugging an issue (halfway through [this thread](https://kubernetes.slack.com/archives/C9D3TSUG4/p1582738318007300)) we were thrown off by the error message shown in the UI:

![Screen Shot 2020-02-27 at 5 50 00 PM](https://user-images.githubusercontent.com/497518/75498859-75ca5580-5a1c-11ea-8a24-114d00f60c97.png)

which implies that the users credentials need the RBAC, when in fact, the issue was that something had deleted the RoleBinding for the kubeapps-internal-kubeops service account. We should differentiate between an issue with the users RBAC and with the RBAC required by kubeapps (though this could be an unlikely situation - kubeapps own rbac would not normally be deleted).

**Comment by andresmgot** [comment]
yes, there are a few hard-coded RBAC errors that we should try to fix. This is the "same" issue: https://github.com/kubeapps/kubeapps/issues/680

**Comment by andresmgot** [comment]
Closing as duplicated
