### ISSUE TITLE
certificate is invalid for charts.bitnami.com

### ISSUE THREAD

**Issue by plsof** [kubeapps/kubeapps#1549]
[root@master helm]# kubectl get pods -n kubeapps
NAME                                                          READY   STATUS      RESTARTS   AGE
apprepo-kubeapps-cleanup-local-jnptf-nrdkg                    0/1     Completed   0          143m
apprepo-kubeapps-cleanup-local-nhh5q-slc5p                    0/1     Completed   0          149m
apprepo-kubeapps-sync-bitnami-p9pdk-2544w                     0/1     Error       3          58s
apprepo-kubeapps-sync-incubator-f65jn-kgpss                   0/1     Error       3          58s
apprepo-kubeapps-sync-stable-q58rc-jmrnd                      0/1     Error       3          59s
apprepo-kubeapps-sync-svc-cat-pjdz5-h5482                     0/1     Error       3          59s
kubeapps-68d7c9d785-dzrfd                                     1/1     Running     0          60s
kubeapps-68d7c9d785-zcmz9                                     1/1     Running     0          60s
kubeapps-internal-apprepository-controller-798479c99c-sjvf7   1/1     Running     0          60s
kubeapps-internal-assetsvc-746fcbfc6c-ngnt6                   1/1     Running     0          60s
kubeapps-internal-assetsvc-746fcbfc6c-qcj89                   1/1     Running     0          60s
kubeapps-internal-dashboard-566dbc686d-bl47c                  1/1     Running     0          60s
kubeapps-internal-dashboard-566dbc686d-qkxd2                  1/1     Running     0          60s
kubeapps-internal-tiller-proxy-74f7dc7fcc-2zwft               1/1     Running     0          60s
kubeapps-internal-tiller-proxy-74f7dc7fcc-ptrz8               1/1     Running     0          60s
kubeapps-mongodb-85cc7b969d-tsvv7                             1/1     Running     0          60s
[root@master helm]# kubectl logs -f apprepo-kubeapps-sync-bitnami-p9pdk-2544w -n kubeapps
time="2020-03-01T11:09:44Z" level=error msg="error requesting repo index" error="Get https://charts.bitnami.com/bitnami/index.yaml: x509: certificate is valid for chinabookinternational.cn, m.chinabookinternational.cn, www.chinabookinternational.cn, not charts.bitnami.com" url="https://charts.bitnami.com/bitnami/index.yaml"
time="2020-03-01T11:09:44Z" level=fatal msg="Get https://charts.bitnami.com/bitnami/index.yaml: x509: certificate is valid for chinabookinternational.cn, m.chinabookinternational.cn, www.chinabookinternational.cn, not charts.bitnami.com"

**Comment by plsof** [comment]
[root@master helm]# kubectl describe pod apprepo-kubeapps-sync-bitnami-p9pdk-2544w -n kubeapps
Name:           apprepo-kubeapps-sync-bitnami-p9pdk-2544w
Namespace:      kubeapps
Priority:       0
Node:           node2/172.188.2.87
Start Time:     Sun, 01 Mar 2020 19:08:51 +0800
Labels:         apprepositories.kubeapps.com/repo-name=bitnami
                apprepositories.kubeapps.com/repo-namespace=kubeapps
                controller-uid=469c331a-e281-4296-87d1-6a21ca5baf0a
                job-name=apprepo-kubeapps-sync-bitnami-p9pdk
Annotations:    <none>
Status:         Running
IP:             10.244.2.198
Controlled By:  Job/apprepo-kubeapps-sync-bitnami-p9pdk
Containers:
  sync:
    Container ID:  docker://0370292088f63eaa25d3f44421d410ec5d033676ffa324100cb0b32aede39493
    Image:         docker.io/bitnami/kubeapps-asset-syncer:1.8.2-scratch-r0
    Image ID:      docker-pullable://bitnami/kubeapps-asset-syncer@sha256:d104c7602426caec95ce598e174ab8159a9fd357d5cbb0d650cd300646d279f5
    Port:          <none>
    Host Port:     <none>
    Command:
      /asset-syncer
    Args:
      sync
      --database-type=mongodb
      --database-url=kubeapps-mongodb
      --database-user=root
      --database-name=charts
      --user-agent-comment=kubeapps/v1.8.2
      bitnami
      https://charts.bitnami.com/bitnami
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Sun, 01 Mar 2020 19:11:46 +0800
      Finished:     Sun, 01 Mar 2020 19:11:48 +0800
    Ready:          False
    Restart Count:  5
    Environment:
      DB_PASSWORD:  <set to the key 'mongodb-root-password' in secret 'kubeapps-mongodb'>  Optional: false
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-tmdds (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  default-token-tmdds:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-tmdds
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                     From               Message
  ----     ------     ----                    ----               -------
  Normal   Scheduled  4m35s                   default-scheduler  Successfully assigned kubeapps/apprepo-kubeapps-sync-bitnami-p9pdk-2544w to node2
  Normal   Pulled     3m1s (x5 over 4m35s)    kubelet, node2     Container image "docker.io/bitnami/kubeapps-asset-syncer:1.8.2-scratch-r0" already present on machine
  Normal   Created    3m1s (x5 over 4m35s)    kubelet, node2     Created container sync
  Normal   Started    3m1s (x5 over 4m35s)    kubelet, node2     Started container sync
  Warning  BackOff    2m20s (x10 over 4m20s)  kubelet, node2     Back-off restarting failed container

**Comment by absoludity** [comment]
Hi there @plsof . Thanks for taking the time to provide logs. It seems that your Kubeapps installation is running behind some sort of proxy which is inserting its own certificate instead of the correct charts.bitnami.com one.

You can check this by running the following command, which I have verified from two different locations, which shows the certificate subject as charts.bitnami.com and the issuer as amazon:

```
$ openssl s_client -showcerts -connect charts.bitnami.com:443
CONNECTED(00000005)                                                          
depth=2 C = US, O = Amazon, CN = Amazon Root CA 1                            
verify return:1                                                              
depth=1 C = US, O = Amazon, OU = Server CA 1B, CN = Amazon           
verify return:1                                                 
depth=0 CN = charts.bitnami.com                                 
verify return:1                                                 
---                                                             
Certificate chain                                               
 0 s:CN = charts.bitnami.com                                    
   i:C = US, O = Amazon, OU = Server CA 1B, CN = Amazon         
-----BEGIN CERTIFICATE-----
MIIFbzCCBFegAwIBAgIQB7sNwDElf5LWHZBD9fyovjANBgkqhkiG9w0BAQsFADBG
... [snip]
---
Server certificate
subject=CN = charts.bitnami.com

issuer=C = US, O = Amazon, OU = Server CA 1B, CN = Amazon
```

My guess is that you will see something different as the subject/issuer because you are accessing charts.bitnami.com behind some type of proxy.

Hope that helps you debug further. Please re-open this issue if you think there is still an issue with Kubeapps itself.

**Comment by plsof** [comment]
> Hi there @plsof . Thanks for taking the time to provide logs. It seems that your Kubeapps installation is running behind some sort of proxy which is inserting its own certificate instead of the correct charts.bitnami.com one.
> 
> You can check this by running the following command, which I have verified from two different locations, which shows the certificate subject as charts.bitnami.com and the issuer as amazon:
> 
> ```
> $ openssl s_client -showcerts -connect charts.bitnami.com:443
> CONNECTED(00000005)                                                          
> depth=2 C = US, O = Amazon, CN = Amazon Root CA 1                            
> verify return:1                                                              
> depth=1 C = US, O = Amazon, OU = Server CA 1B, CN = Amazon           
> verify return:1                                                 
> depth=0 CN = charts.bitnami.com                                 
> verify return:1                                                 
> ---                                                             
> Certificate chain                                               
>  0 s:CN = charts.bitnami.com                                    
>    i:C = US, O = Amazon, OU = Server CA 1B, CN = Amazon         
> -----BEGIN CERTIFICATE-----
> MIIFbzCCBFegAwIBAgIQB7sNwDElf5LWHZBD9fyovjANBgkqhkiG9w0BAQsFADBG
> ... [snip]
> ---
> Server certificate
> subject=CN = charts.bitnami.com
> 
> issuer=C = US, O = Amazon, OU = Server CA 1B, CN = Amazon
> ```
> 
> My guess is that you will see something different as the subject/issuer because you are accessing charts.bitnami.com behind some type of proxy.
> 
> Hope that helps you debug further. Please re-open this issue if you think there is still an issue with Kubeapps itself.



> Hi there @plsof . Thanks for taking the time to provide logs. It seems that your Kubeapps installation is running behind some sort of proxy which is inserting its own certificate instead of the correct charts.bitnami.com one.
> 
> You can check this by running the following command, which I have verified from two different locations, which shows the certificate subject as charts.bitnami.com and the issuer as amazon:
> 
> ```
> $ openssl s_client -showcerts -connect charts.bitnami.com:443
> CONNECTED(00000005)                                                          
> depth=2 C = US, O = Amazon, CN = Amazon Root CA 1                            
> verify return:1                                                              
> depth=1 C = US, O = Amazon, OU = Server CA 1B, CN = Amazon           
> verify return:1                                                 
> depth=0 CN = charts.bitnami.com                                 
> verify return:1                                                 
> ---                                                             
> Certificate chain                                               
>  0 s:CN = charts.bitnami.com                                    
>    i:C = US, O = Amazon, OU = Server CA 1B, CN = Amazon         
> -----BEGIN CERTIFICATE-----
> MIIFbzCCBFegAwIBAgIQB7sNwDElf5LWHZBD9fyovjANBgkqhkiG9w0BAQsFADBG
> ... [snip]
> ---
> Server certificate
> subject=CN = charts.bitnami.com
> 
> issuer=C = US, O = Amazon, OU = Server CA 1B, CN = Amazon
> ```
> 
> My guess is that you will see something different as the subject/issuer because you are accessing charts.bitnami.com behind some type of proxy.
> 
> Hope that helps you debug further. Please re-open this issue if you think there is still an issue with Kubeapps itself.

Thank you for the wonderful answer above. Later i found something confusing

In host it is ok
[root@master ~]# curl -s 'https://charts.bitnami.com/bitnami/index.yaml' | less
apiVersion: v1
entries:
  airflow:
  - apiVersion: v1
    appVersion: 1.10.9
    created: "2020-02-26T11:15:42.102167838Z"
    description: Apache Airflow is a platform to programmatically author, schedule
      and monitor workflows.
    digest: e4f3cc71201fb6a01a0e909e19d6670ca9b5994b60b4477efb604c480242812a
    home: https://airflow.apache.org/
    icon: https://bitnami.com/assets/stacks/airflow/img/airflow-stack-110x117.png
    keywords:
    - apache
    - airflow
    - workflow
    - dag
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    name: airflow
    sources:
    - https://github.com/bitnami/bitnami-docker-airflow

Then i curl in a pod
[root@master ~]# kubectl exec -it kubeapps-68d7c9d785-78x9s /bin/bash -n kubeapps
I have no name!@kubeapps-68d7c9d785-78x9s:/app$ curl 'https://charts.bitnami.com/bitnami/index.yaml'
curl: (60) SSL: no alternative certificate subject name matches target host name 'charts.bitnami.com'
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
I have no name!@kubeapps-68d7c9d785-78x9s:/app$

so is there a possibility the four error pod is same as kubeapps-68d7c9d785-78x9s

**Comment by absoludity** [comment]
> so is there a possibility the four error pod is same as kubeapps-68d7c9d785-78x9s

Yes, my guess is that any pod running within your cluster will have similar issues. Not sure if the DNS used within your cluster is the issue, but that's where I would start (ie. checking what IP charts.bitnami.com resolves to, both locally and from a pod in your cluster).
