### ISSUE TITLE
Selecting the right application version is very difficult with the current design

### ISSUE THREAD

**Issue by prydonius** [kubeapps/kubeapps#155]
Imported from https://github.com/kubeapps/dashboard/issues/40

@arapulido:
> In the Dashboard you can select a specific Chart version, but it is difficult to see what App version that matches.
>
> It would be good to see what chart versions correspond to what application versions, so the users can select better.
> 
> We can use this issue to discuss the UX options

@prydonius
> One idea I had for this was to group versions by app version. A single app version can be represented in multiple chart versions, but not vice versa. e.g.
>
> 2.0.0
> 0.5.1, 0.5.0
>
> 1.9.0
> 0.4.9, 0.4.8
>
> Though this is likely confusing to users who don't fully understand the relation between app version and chart versions in Helm.

**Comment by andresmgot** [comment]
Already implemented
