### ISSUE TITLE
Does apprepository-controller support http_proxy and https_proxy?

### ISSUE THREAD

**Issue by sayaoailun** [kubeapps/kubeapps#1556]
## Chart

The Chart `bitnami/kubeapps` support `initialReposProxy` by Setting ENV `http_proxy` and `https_proxy`

## apprepository-controller

When I add a new App Repository, the cronjob doesn't have the ENV `http_proxy` and `https_proxy`. I found the code below:

https://github.com/kubeapps/kubeapps/blob/b772c3b5d31ce06d93546b724095c8f009d42d65/cmd/apprepository-controller/controller.go#L573-L594

So is there a way to set the ENV for the cronjob?

**Comment by andresmgot** [comment]
@sayaoailun yes, you just need to edit the `syncJobPodTemplate` and add the required env vars. You have an example here:

https://github.com/kubeapps/kubeapps/blob/master/docs/user/private-app-repository.md#modifying-the-synchronization-job

**Comment by andresmgot** [comment]
Let me close this issue, please reopen it if you still find any problem

**Comment by sayaoailun** [comment]
> @sayaoailun yes, you just need to edit the `syncJobPodTemplate` and add the required env vars. You have an example here:
> 
> https://github.com/kubeapps/kubeapps/blob/master/docs/user/private-app-repository.md#modifying-the-synchronization-job

@andresmgot Thank you very much! That's what I need. And I found the env can be set through the dashboard too.
