### ISSUE TITLE
Doesn't create namespace if it doesn't exist

### ISSUE THREAD

**Issue by prydonius** [kubeapps/kubeapps#156]
_From @sozercan on January 30, 2018 23:20_

If the namespace does not exist, dashboard gives error `Error: namespaces "name" not found`. I believe Helm CLI creates the namespace, if not found.

Not sure if this is related to helm-crd or dashboard?

_Copied from original issue: kubeapps/dashboard#43_

**Comment by prydonius** [comment]
The issue is that helm-crd will install the chart in the namespace that the HelmRelease resource is created in. So whilst Tiller can create namespaces if they don't exist, when using the Kubernetes API to create the HelmRelease we need the namespace to already exist.

The Dashboard could create the namespace for you, but then we need to give RBAC permissions to the Dashboard to do that. The long-term goal for auth is to use a users credentials, so maybe it's okay to try to create the namespace if we have permissions, but fallback to erroring if not?

**Comment by prydonius** [comment]
_From @arapulido on February 5, 2018 9:50_

When do this happen? When you tell the dashboard to install a chart in a specific namespace that doesn't exist? or when the chart itself is overwriting the namespace?

**Comment by prydonius** [comment]
_From @sozercan on February 5, 2018 17:58_

@arapulido happens when you are installing to a namespace that doesn't exist

**Comment by prydonius** [comment]
@andresmgot how does this work with tiller-proxy? Is this relevant anymore?

**Comment by prydonius** [comment]
The Dashboard allows you to treat the namespace selector as a text box to type in any namespace. It's not very obvious, and we probably want to change the design to something like:

![screen shot 2018-06-22 at 11 06 57](https://user-images.githubusercontent.com/1544861/42236043-867daba2-7eae-11e8-9dae-b97de894d087.png)

> if the chart doesn't specify a new namespace

You mean if the chart doesn't have a Namespace kind in its templates? We may want to extend tiller-proxy to verify the namespace exists or that the user can create it?

**Comment by andresmgot** [comment]
> You mean if the chart doesn't have a Namespace kind in its templates? We may want to extend tiller-proxy to verify the namespace exists or that the user can create it?

I mean that, yes. Just checked and Tiller creates the namespace if it doesn't exists so yes we should handle that case.

**Comment by arapulido** [comment]
It works now. Closing
