### ISSUE TITLE
Invalidate storage cache only when necessary

### ISSUE THREAD

**Issue by absoludity** [kubeapps/kubeapps#1560]
Up until recently, mongodb was the only storage option for the assets (charts, files etc.) which Kubeapps indexes. Postgresql was added as a supported backend, but we don't currently support migrations, or even just the ability to know if there's been a schema change.

As a result, and since the storage is just a cache, currently we invalidate the cache and re-create the schema on each upgrade to be sure that the code is working with the correct schema. A less destructive approach would be to only invalidate the cache when a schema change is detected, and the ideal would be to migrate data so that other users don't temporarily see a change in charts etc.

It may be simpler to do this when we only have postgresql as a backend (as even though mongodb doesn't necessarily require resetting the schema, the indexes may also change).

**Comment by absoludity** [comment]
I see the artifacthub folk are using https://github.com/jackc/tern which looks interesting: postgres specific, can be used both as a stand-alone CLI or a go library in your code.

**Comment by andresmgot** [comment]
IMO, running migrations is an ideal solution but maybe is an overkill for our use case. Maintaining the migration seems not trivial. (At the very least we would need to maintain the migration file and configuration and learn how to run these migrations).

If we are able to at least detect schema changes and only delete the database in that case we will be in a better place than right now (and doing that seems more simple).

**Comment by absoludity** [comment]
Maintaining migrations is pretty normal - plenty of tools for this. Running the migrations could simply be running them when the pod starts (one pod will have a transaction and do the migration, others see the migration already done). But I agree - could be more effort than value for this case, as I mentioned in the description.

> If we are able to at least detect schema changes and only delete the database in that case we will be in a better place than right now (and doing that seems more simple).

Yep, as above, it's an improvement happy for us to do that for now, but I do think there are ways of doing that which are a step towards standard migrations. I'll put more context on the PR.

**Comment by absoludity** [comment]
> Yep, as above, it's an improvement happy for us to do that for now, but I do think there are ways of doing that which are a step towards standard migrations. I'll put more context on the PR.

After commenting on the PR, I even wonder if it'd be less effort just to use `tern` either way.

**Comment by andresmgot** [comment]
We are not invalidating the cache after the chart 6.0.0 so we can close this one for the moment (to be re-evaluated if we need to enable the invalidation again).

**Comment by absoludity** [comment]
> We are not invalidating the cache after the chart 6.0.0 

It's more that we are not supporting schema changes to the cache/storage.

> so we can close this one for the moment (to be re-evaluated if we need to enable the invalidation again).

Unfortunately I don't think it's that simple as enabling it again if there is a schema change. We can re-enable it, but without migrations, it needs to remain enabled for a significant time as we have an unbounded upgrade possibilities.

I don't see how the situation has changed, we still need to invalidate the storage cache if the schema changes, and it'd be great if we only did that when necessary (but i think that'd require migrations). Anyway, I'll leave closed, we can re-evaluate when we have cycles to look at it (and perhaps have decided about the future of the cached data too).
