### ISSUE TITLE
Sync job fails to get external icon with selfsigned certificate

### ISSUE THREAD

**Issue by skidpa** [kubeapps/kubeapps#1568]
### Description:

Have the icon on a selfhosted server/repository behind tls with self signed certificate.
so in the charts Chart.yaml the icon path is set to https://myserver/img:443 which is using a self signed certificate.

If the chart is installed using helm from a terminal the icon path works (Applications tab), I'm guessing this is because kubeapps gets the icon location from the Chart.yaml file.
However if i package the chart and upload it to my local chartmuseum the sync will fail with
because of the certificate and the icon will be a broken link in the catalogs tab.

I have to use a self signed certificate. letsencrypt is not an option at the moment.
### Steps to reproduce the issue:

1. [First Step]
have a location behind tls with self signed certificate that contains a img to be used as an icon for a Chart.
2. [Second Step]
package the chart, upload it to a chart repository and sync it
3. [Third Step]
check the logs for the sync job there will be a certificate error

### Describe the results you received:

sync fails to get icon because of untrusted tls certificate
```
time="2020-03-09T08:32:54Z" level=error msg="failed to import icon" error="Get https://witty-name-artifactory-artifactory-nginx.default.svc.cluster.local:443/artifactory/example-repo-local/kubeapps.png: x509: certificate signed by unknown authority" name=kubeapp
```
samething if i try to access it on the nodeport

### Describe the results you expected:

sync fail because of untrusted certificate
was hoping to find a flag or something to get around this.

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.0", GitCommit:"6b6547b6346d9d23af878ed915d67bca9b0fb2bd", GitTreeState:"dirty", GoVersion:"go1.13.3"}
```

- Output of `helm list <kubeapps-release-name>`:

```
NAME             	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART            	APP VERSION
my-kubeapps   	default  	1       	2020-03-06 16:23:59.159390147 +0100 CET	deployed	kubeapps-3.4.3   	v1.8.2 
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by andresmgot** [comment]
Right, I see. Yes a `--skip-tls-verification` would be helpful for your use case. Marking this as `help-wanted` in case someone wants to give a try. The code you are looking for is here:

https://github.com/kubeapps/kubeapps/blob/ca61d9537030c01f269055d8093feb06023d0fa7/cmd/asset-syncer/utils.go#L333

But I guess it's also useful to skip the TLS verification for the whole chart. In that case is a bit more difficult because not only the sync should skip the TLS cert but also the backend (tiller-proxy or kubeops) when installing the chart.

**Comment by antgamdia** [comment]
Closing as it seems to be already implemented at 

https://github.com/kubeapps/kubeapps/blob/0e9ee36bee7eec9e23a02367d7c6ea43bd444f09/cmd/asset-syncer/main.go#L61
