### ISSUE TITLE
filter packages

### ISSUE THREAD

**Issue by kfox1111** [kubeapps/kubeapps#1583]
It would be good if there was a way to specify patterns of package names to exclude from display. For example, you may not want to expose to your users the bitcoind package from the stable repository.

**Comment by andresmgot** [comment]
Hi @kfox1111,

That's a good point but the thing is that the stable and incubator repositories are deprecated and will be going away in May:

https://github.com/helm/charts#deprecation-timeline

My recommendation for you is to remove the `stable` repository and instead cherry pick the repositories you are interested in. You can browse the different repositories and the charts they contain here:

https://hub.kubeapps.com/charts

**Comment by andresmgot** [comment]
This issue was defined for things to exclude from a repository. It's also a possibility to include only certain things from a repository. Collecting @antgamdia comment:

> Add chart filtering -during- fetching in asset-syncer. For instance, just fetch "category=cms" or "version=latest"

**Comment by andresmgot** [comment]
I am going to start with a quick design for this

**Comment by andresmgot** [comment]
@absoludity @antgamdia @danoo Please take a look whenever you have the chance:

https://docs.google.com/document/d/1dNv7Id0l_3sac2SAtswtn3vj2eq6naFPGf9-YmN-3JE/edit?usp=sharing
