### ISSUE TITLE
Chart indicies missing data cause UI "Something went wrong"

### ISSUE THREAD

**Issue by absoludity** [kubeapps/kubeapps#1620]
### Description:

Certain chart indicies don't include some fields, such as sources or maintainers, which causes the dashboard to error without a useful message:

![empty-maintainers](https://user-images.githubusercontent.com/497518/78097270-97f23180-7427-11ea-8717-ddb6f531dfc7.png)

### Steps to reproduce the issue:

1. Add the https://charts.gitlab.io repository to Kubeapps
2. After import, view the repository
3. Click on the chart auto-deploy-app

Expected result: chart displays simply missing some information.
Actual result: error as above.

### Additional information you deem important (e.g. issue happens only occasionally):

The issue does not happen for other charts in the same repo which have maintainers and sources set.

- Output of `helm list <kubeapps-release-name>`:

Running from master.

**Comment by andresmgot** [comment]
I  have fixed the case in which the chart doesn't have sources here: https://github.com/kubeapps/kubeapps/pull/1661
But we still need to cover other cases like you say with the maintainers.

**Comment by wwyhy** [comment]
hello,

I got same error after deploy by helm2. Can you let me know how did you fix this? thanks!

[root@master kubeapps]# helm   --tiller-namespace kubeapps list
NAME    	REVISION	UPDATED                 	STATUS  	CHART         	APP VERSION	NAMESPACE
kubeapps	1       	Fri Jun 12 14:45:30 2020	DEPLOYED	kubeapps-3.7.1	v1.10.1    	kubeapps 

Br, wwyhy

**Comment by absoludity** [comment]
Hi @wwyhy . As above, not all the cases of handling missing info in charts has been handled yet. We'll be working to ensure the remaining cases are done soon. Can you let us know which chart you deployed when you saw the error so we can reproduce and ensure the missing info in the chart you are deploying is covered by our changes? Thanks.

**Comment by wwyhy** [comment]
Hi,

No, just open the home page. got below error, and get above error when click other page.
![image](https://user-images.githubusercontent.com/83105/84633936-b1355500-af23-11ea-93e3-483804f8b11c.png)

**Comment by andresmgot** [comment]
hi @wwyhy, there are different places where that error may be thrown, can you send a screenshot of the browser console with the error?

**Comment by andresmgot** [comment]
I got a similar error, this time in the catalog with an Operator that has a missing property `displayName`:
https://github.com/kubeapps/kubeapps/blob/master/dashboard/src/components/Catalog/Catalog.tsx#L195

It seems that we need to be extra careful in the views we are rendering external info: Catalog, ChartView, OperatorView.

**Comment by absoludity** [comment]
Closing as we think these have been handled as part of the new UI.
