### ISSUE TITLE
Create a loader component

### ISSUE THREAD

**Issue by prydonius** [kubeapps/kubeapps#165]
_From @Angelmmiguel on February 20, 2018 16:3_

Currently, we don't show a loader when we're fetching data from the server. This makes the current experience odd because the elements as appearing without any feedback to the user

_Copied from original issue: kubeapps/dashboard#96_

**Comment by arapulido** [comment]
@Angelmmiguel ping (see above comment)

**Comment by Angelmmiguel** [comment]
Yes! @arapulido, please could you open a task in bitnami/hex and reference it from this one?

Thanks

**Comment by migmartri** [comment]
These are the places where we have loading state which will need to be replaced by the new component.

- [ ] main container app load
- [ ] loading wrapper (maybe the one above?)
- [ ] applications listing
- [ ] application show
- [ ] application deployment
- [ ] application upgrade
- [ ] charts listing
- [ ] charts show
- [ ] chart readme
- [ ] select repo form

**Comment by migmartri** [comment]
I believe that all the loaders have been put in place and whenever the native hex loader is upstream we just need to replace `<LoadingSpinner>` for that one in a single place.
