### ISSUE TITLE
Secret "apprepo-<Repo Name>" is invalid: metadata.ownerReferences.uid: Invalid value: "": uid must not be empty

### ISSUE THREAD

**Issue by locus-akhilkrishna** [kubeapps/kubeapps#1655]
Description:
Getting this error while creating App Repository with Basic Auth.

> Secret "apprepo-test-repo" is invalid: metadata.ownerReferences.uid: Invalid value: "": uid must not be empty

Steps to reproduce the issue:
Create a private App Repository with Basic Auth
Kubeapps Version: v1.9.1
Helm Version version: v3.1.2

![image](https://user-images.githubusercontent.com/51187253/78864239-db1c5800-7a58-11ea-8d5b-9dada3b17b3c.png)

**Comment by absoludity** [comment]
Thanks @locus-akhilkrishna.

Details: When adding the new functionality to validate the app repository before creation (in d5b277cdd) , the order of the objects being instantiated (app repo, secret) was changed. Prior to that commit, the app repo was created first (and so had a UID defined), before being passed to the function instantiating the secret - so the secret could be created with the owner reference uid of the app repo. After that commit, the uncreated app repo and secret are instantiated first, so the secret has a blank UID. The fix should be simple (as should adding a CI path to test this).

Thanks for the report.
