### ISSUE TITLE
cassandra deployment failing with poddisruptionbudgets.policy error

### ISSUE THREAD

**Issue by govindkailas** [kubeapps/kubeapps#1656]
### Description:
Cassandra(5.2.0) deployment from Kubeapp is failing due to poddisruptionbudgets 

I am trying to install Bitnami Cassandra chart versions 5.2.0 from Kubeapp dashboard(v1.8.2). Deployment fails with the following error,

`Release "kong-cassandra" failed and has been uninstalled: rendered manifests contain a resource that already exists. Unable to continue with install: could not get information about the resource: poddisruptionbudgets.policy "kong-cassandra-headless" is forbidden: User "system:serviceaccount:tkgdev-es-dev:tkgdev-es-dev-user" cannot get resource "poddisruptionbudgets" in API group "policy" in the namespace "tkgdev-es-dev"
`
The use have most of the permissions to play on the provisioned namespace, but the below can be noted 

```
kubectl auth can-i get poddisruptionbudgets.policy --as=system:serviceaccount:tkgdev-es-dev:tkgdev-es-dev-user
no
```
**Why would the user need access to `poddisruptionbudgets` ? There should be a way to control it from the values.yaml** 

### Steps to reproduce the issue:

1. Create a namespace tkgdev-es-dev
2. Have the attached role and user created
3. Login to kubeapp and deploy Bitnami Cassandra chart v  5.2.0.
4. Deployment would fail with the below error,
`Release "kong-cassandra" failed and has been uninstalled: rendered manifests contain a resource that already exists. Unable to continue with install: could not get information about the resource: poddisruptionbudgets.policy "kong-cassandra-headless" is forbidden: User "system:serviceaccount:tkgdev-es-dev:tkgdev-es-dev-user" cannot get resource "poddisruptionbudgets" in API group "policy" in the namespace "tkgdev-es-dev"
`
### Describe the results you received:

Deployment failed with 
`forbidden: User "system:serviceaccount:tkgdev-es-dev:tkgdev-es-dev-user" cannot get resource "poddisruptionbudgets" in API group "policy" in the namespace "tkgdev-es-dev"
`
### Describe the results you expected:

The deployment should result in Cassandra running.
### Additional information you deem important (e.g. issue happens only occasionally):
NO

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`: 

```
v3.1.2
```

- Output of `helm list <kubeapps-release-name>`:

```
helm list  -n tkgdev-es-dev
NAME	NAMESPACE	REVISION	UPDATED	STATUS	CHART	APP VERSION
```

- Output of `kubectl version`:

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T12:36:28Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4+vmware.1", GitCommit:"0f866081ec4345725d7a74fdd5d353b5637d387a", GitTreeState:"clean", BuildDate:"2019-12-11T22:11:30Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
[tkgdev-es-dev-role.txt](https://github.com/kubeapps/kubeapps/files/4456829/tkgdev-es-dev-role.txt)

**Comment by andresmgot** [comment]
hello @govindkailas, thank you for filling the issue! Unfortunately we are not the maintainers of the Cassandra chart. Can you create a similar issue in their repository? Here: https://github.com/bitnami/charts/issues/new/choose

You don't need to fill all the details again, you can just point to this issue for more info.

**Comment by govindkailas** [comment]
Sure @andresmgot, I will do that.

**Comment by andresmgot** [comment]
Let me close this issue @govindkailas since I see you are being answered in the other issue. Please reopen it if you think there is something we can help you with.
