### ISSUE TITLE
New card design looks weird in Firefox

### ISSUE THREAD

**Issue by prydonius** [kubeapps/kubeapps#166]
_From @arapulido on February 20, 2018 17:13_

As attached:

<img width="1330" alt="screen shot 2018-02-20 at 6 12 33 pm" src="https://user-images.githubusercontent.com/925437/36438287-bf16da7c-1669-11e8-9afc-845206010b4b.png">

_Copied from original issue: kubeapps/dashboard#98_

**Comment by prydonius** [comment]
_From @arapulido on February 20, 2018 17:14_

Not super critical, but something @Angelmmiguel may want to have a look to, as this is one of the design system componets

**Comment by prydonius** [comment]
_From @Angelmmiguel on February 20, 2018 17:16_

Sure! Thank for creating the issue. It's related with percentual units in margins. I'll fix it :)

**Comment by prydonius** [comment]
_From @sameersbn on February 27, 2018 7:6_

Adding to the FF issues, I noticed that the Configuration drop down menu shifts a little towards the left each time its opened.

![peek 2018-02-27 12-34](https://user-images.githubusercontent.com/410147/36715057-9be4075e-1bba-11e8-94d9-06066ab089a8.gif)

**Comment by arapulido** [comment]
This was fixed
