### ISSUE TITLE
User gets logged out after failing to add app repository

### ISSUE THREAD

**Issue by kristinnardal2** [kubeapps/kubeapps#1675]
### Description:

User gets logged out when trying to add an app repository but doesn't have permissions to do so.

### Steps to reproduce the issue:

1. Have an RBAC enabled cluster, and make sure you have the role that allows listing app repos but not to create them
2. Install Kubeapps
3. Log into Kubeapps
4. Go to app repos page
5. Click create app repo
6. Fill in some info and click "Install Repo"
A relevant error message is displayed since we're not allowed to create app repos, but it's only displayed for a split second before we are logged out.

### Describe the results you received:

A relevant error message is displayed since we're not allowed to create app repos, but it's only displayed for a split second before we are logged out.

### Describe the results you expected:

I expect to get an error message telling me that I am not able to create an app repository and what rights I need to do so as well as staying logged in.

### Additional information you deem important (e.g. issue happens only occasionally):

I don't believe this is exclusive to creating an app repository as I believe we also ran into this when trying to delete an app repository while not having the rights to do so.

@absoludity said on slack that they had also run into this problem while testing locally.

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.0-rc.1", GitCommit:"7bffac813db894e06d17bac91d14ea819b5c2310", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

- Output of `helm list <kubeapps-release-name>`:

```
NAME        NAMESPACE    REVISION    UPDATED                                     STATUS      CHART             APP VERSION
kubeapps    kubeapps     1           2020-04-15 12:43:32.762055057 +0200 CEST    deployed    kubeapps-3.5.2    v1.9.2
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"d94a81c724ea8e1ccc9002d89b7fe81d58f89ede", GitTreeState:"clean", BuildDate:"2020-03-16T20:10:55Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"c83d931fb9bece427bc63a02349755e0f8696d3e", GitTreeState:"clean", BuildDate:"2020-01-31T20:09:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by andresmgot** [comment]
Thanks for the bug report. To identify which is the request that is misbehaving, can you (or @absoludity) post here the request that is failing from the Network tab in the browser console? That will help for the fix.

**Comment by absoludity** [comment]
![logout-on-403](https://user-images.githubusercontent.com/497518/80335417-920d3600-8897-11ea-90bc-e822f09c9deb.png)

The problem is that we currently check whether an error response is a k8s api error by verifying the json content (as all responses from the k8s api from the dashboard are json), but our backend API is returning plain text errors. I have a branch in progress, and will finish it tomorrow.
