### ISSUE TITLE
Manage user account on hub.kubeapps.com

### ISSUE THREAD

**Issue by idkw** [kubeapps/kubeapps#1682]
Hello,

I don't see any way to manage my account at https://hub.kubeapps.com/
When I logout/login with google, I'm not presented with any screen to edit the following properties.

I need to : 
- Edit my email
- Edit my public name
- Edit my notification preferences

![image](https://user-images.githubusercontent.com/7012331/79863710-7eb22480-83d8-11ea-8eeb-525a9f5bc250.png)

Thanks

**Comment by idkw** [comment]
Ok after diggign a bit I've found that the account management settings can be found at : https://bitnami.com/account/

Can you add a link to this page in the top menu bar because it was actually mentionned nowhere ^^

**Comment by andresmgot** [comment]
Hi, thanks for the info, indeed it's not stated anywhere that we are using the account from bitnami.com. We could add a link there.
