### ISSUE TITLE
Don't need Yaml to automatically convert to json

### ISSUE THREAD

**Issue by ygqygq2** [kubeapps/kubeapps#1683]
![image](https://user-images.githubusercontent.com/17672440/79866527-7fb27880-840f-11ea-8daf-f0c625dfb254.png)

![image](https://user-images.githubusercontent.com/17672440/79866671-b9837f00-840f-11ea-809a-b268235acbde.png)

kubeapps version: 1.8.2  and  1.9.2

I don't need Yaml to automatically convert to json.

**Comment by absoludity** [comment]
This isn't related to Kubeapps, but rather is coming from the kubernetes API server: the value of the label "node-role" needs to be a string. If you want to use something that looks like yaml, you'll need to quote it:

```
~/tmp$ grep node-role pod.yaml
    node-role: { kubernetes: { io~1worker: worker } }

~/tmp$ kubectl create --dry-run --validate -f pod.yaml
error: error validating "pod.yaml": error validating data: ValidationError(Pod.spec.nodeSelector.node-role): invalid type for io.k8s.api.core.v1.PodSpec.nodeSelector: got "map", expected "string"; if you choose to ignore these errors, turn validation off with --validate=false

~/tmp$ grep node-role pod.yaml
    node-role: "{ kubernetes: { io~1worker: worker } }"

~/tmp$ kubectl create --dry-run --validate -f pod.yaml
pod/static-web created (dry run)
```

Hope that helps.

**Comment by ygqygq2** [comment]
@absoludity 
I don't agree with you. I hope you can test it in kubeapps. I just want to update apps in kubeapps, and if kubeapps stays the way I wrote it also can upgrade apps.



```
nodeSelector:
  "node-role.kubernetes.io/worker": worker
```

**Comment by absoludity** [comment]
Hmmm, I must be misunderstanding something then, as my example was trying to show that the resource with your node selector label is rejected by the k8s api server, but you must mean something else?  Kubeapps isn't modifying the value that you've entered at all currently, or trying to interpreter it. Rather it is passing it as is.

**Comment by absoludity** [comment]
Ah, you mean that you're entering the value in the comment and it's being updated by Kubeapps as shown in your original?  I'll re open and we'll look more closely.  Thanks!

**Comment by absoludity** [comment]
Yes, I see what you mean now.  The editor itself is  interpreting the node selector. Sorry for the mis- understanding :)

**Comment by ygqygq2** [comment]
:) Hope to fix it soon.

**Comment by andresmgot** [comment]
I can reproduce the issue. For example, I am deploying a version with this values:

```
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
```

When upgrading the app, the annotation gets transformed in the deployment form:

```
ingress:
  annotations: { kubernetes: { io~1ingress: { class: nginx } } }
```

I believe the library we are using for interpreting the YAML values is misbehaving, I am currently investigating this.

**Comment by andresmgot** [comment]
Thanks for reporting the issue @ygqygq2! The fix will be available in the next release

**Comment by davidkarlsen** [comment]
Seems this is still an issue.
