### ISSUE TITLE
Avoid requesting secrets in a namespace

### ISSUE THREAD

**Issue by andresmgot** [kubeapps/kubeapps#1686]
### Description:

In order to be able to update the existing AppRepositories and to be able to select Docker credentials, we are listing all the secrets in a namespace in the Dashboard. We should be able to limit the info requested in order to avoid potential security issues.

**Comment by absoludity** [comment]
In particular, there is no need to fetch secrets while listing app repositories (looks like it's currently done just as a short-cut). We should only be fetching secrets which are required for editing the app repository currently.
