### ISSUE TITLE
Cover Operators and Private Registries with end-to-end tests

### ISSUE THREAD

**Issue by andresmgot** [kubeapps/kubeapps#1708]

**Comment by absoludity** [comment]
Still seeing 
  ● Deploys an Operator

    TimeoutError: Navigation Timeout Exceeded: 20000ms exceeded

       8 |       } catch (e) {
       9 |         // Refresh since the chart will get a bit of time to populate
    > 10 |         await page.reload({
         |                    ^

I'd bee keen to close this ticket only when it's not requiring more work? (Sorry, I perhaps shouldn't have moved it to Done yesterday prematurely).

**Comment by andresmgot** [comment]
No problem, that issue you point is fixed here: https://github.com/kubeapps/kubeapps/pull/1729
