### ISSUE TITLE
Instructions not working for k3s

### ISSUE THREAD

**Issue by Yajo** [kubeapps/kubeapps#1712]
### Description:

Cannot run kubeapps in k3s.

### Steps to reproduce the issue:

1. Install k3s: https://k3s.io/
2. Follow instructions from https://github.com/kubeapps/kubeapps/blob/master/docs/user/getting-started.md

### Describe the results you received:

When I open the kubeapps web UI and paste the token generated with `kubectl get secret $(kubectl get serviceaccount kubeapps-operator -o jsonpath='{range .secrets[*]}{.name}{"\n"}{end}' | grep kubeapps-operator-token) -o jsonpath='{.data.token}' -o go-template='{{.data.token | base64decode}}' && echo`, it fails with: "There was an error connecting to the Kubernetes API. Please check that your token is valid.":

### Describe the results you expected:

I should have been able to login.

### Additional information you deem important (e.g. issue happens only occasionally):

My k3s cluster was completely virgin, running in a brand new k3os VM, so not a lot of chances to have some sort of misconfiguration there.

```
$ k3os --version
k3os version v0.10.0
$ k3s --version
k3s version v1.17.4+k3s1 (3eee8ac3)
```

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

- Output of `helm list <kubeapps-release-name>`:

```
➤ helm list -aA
NAME    	NAMESPACE  	REVISION	UPDATED                                 	STATUS  	CHART         	APP VERSION
kubeapps	kubeapps   	1       	2020-05-03 11:28:29.923537774 +0100 WEST	deployed	kubeapps-3.6.0	v1.10.0    
traefik 	kube-system	1       	2020-04-22 16:34:02.323609242 +0000 UTC 	deployed	traefik-1.81.0	1.7.19     
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.8-beta.0", GitCommit:"6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4", GitTreeState:"archive", BuildDate:"2020-01-29T00:00:00Z", GoVersion:"go1.14beta1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4+k3s1", GitCommit:"3eee8ac3a1cf0a216c8a660571329d4bda3bdf77", GitTreeState:"clean", BuildDate:"2020-03-25T16:13:25Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by andresmgot** [comment]
Hi @Yajo,

Can you check that the token is properly copied? (Just to double check that the command is not returning an error)

Also, can you open the browser console and check the error in the `Network` tab? That should show more info about what the dashboard is trying.

**Comment by Yajo** [comment]
Not sure what I did last time, but today I retried and it all worked like a charm. Sorry, I hope I'm not crazy! Thanks for your help.
