### ISSUE TITLE
Switch to use postgresql by default

### ISSUE THREAD

**Issue by absoludity** [kubeapps/kubeapps#1713]
Currently, while we support Helm < 3.1, we cannot (AFAICT) support upgrading to a chart where Postgresql is used by default for the backend, without requiring manual intervention by the user to ensure (at least) that the database secret exists (normally done pre-install).

With Helm 3.1, we can use the lookup template tag to create the secret if it does not already exist during an upgrade.

So while we could gradually:
 * Move to helm3 by default (make 3.1)
 * Remove helm 2 support
 * Then support upgrading to postgres via the above lookout,
it is going to drawn out over quite a long time.

We need to be able to drop mongodb support so we can begin other larger tasks without being hindered by supporting two backends (with minimal functional testing for mongodb in the go code base).

Another option would be for us to decide when we can drop helm 2 support. According to the [helm2 support contract](https://github.com/helm/helm/blob/master/CONTRIBUTING.md#support-contract-for-helm-2), helm 2 will stop accepting bug fixes this month (May 2020), while November 2020 is the end (no more security patches accepted etc.). Depending on our strategy for that, we may be able to switch to postgres-only at the same time (ie. remove support for mongodb).

**Comment by andresmgot** [comment]
something that would work today is adding a second container to the `apprepository-jobs-preupgrade` job that creates the secret (using `kubectl`) if it doesn't exist. WDYT? Any downside of doing that?

**Comment by absoludity** [comment]
> something that would work today is adding a second container to the `apprepository-jobs-preupgrade` job that creates the secret (using `kubectl`) if it doesn't exist. WDYT? Any downside of doing that?

That's a neat idea - I'd thought of updating the pre-upgrade job (which is the asset-sync binary) to do that, but decided it'd be pretty ugly, but using an init-container or similar would be much neater, using kubectl from a bash script. We just need to pass in the `postgresql.exstingSecret` value for the secret name. Thanks!
