### ISSUE TITLE
Upgrade to Helm 3.2.0+

### ISSUE THREAD

**Issue by batiati** [kubeapps/kubeapps#1726]
Cannot install a chart that uses the function "fromJsonArray" released on [Helm 3.2.0](https://github.com/helm/helm/releases/tag/v3.2.0)

```
Release "XYZ" failed and has been uninstalled: parse error at (/templates/_helpers.tpl:74): function "fromJsonArray" not defined
```

It works from helm install command

**Comment by batiati** [comment]
Workarround: refactory the json file, adding a root element and use the "fromJson" function instead of "fromJsonArray".

This:
```
[ ... ]
```

Became this:
```
{
    Items: [ ... ]
}
```

**Comment by absoludity** [comment]
Thanks. Yes, I only just updated Kubeapps services to 3.1, but we can update again easily enough :)
