### ISSUE TITLE
Configurable cronjob interval for rep sync

### ISSUE THREAD

**Issue by batiati** [kubeapps/kubeapps#1738]
### Description:

In some case it's desirable to configure a custom interval for the `kubeapps-asset-syncer`'s cronjob;
It can be done directly by `kubectl patch`, but eventually the kubeapps restaures the original cronjob interval back to `*/10 * * * *`

Is there a way to configure it on values.yaml or by some configmap key?

**Comment by andresmgot** [comment]
yes, there is a value for that: `--set apprepository.crontab='*/20 * * * *'`

See: https://github.com/kubeapps/kubeapps/blob/master/chart/kubeapps/values.yaml#L183

BTW, just curious, what's your use case, why do you need to modify that value?

**Comment by batiati** [comment]
Thank you @andresmgot!

I'd like to set my private development repository to refresh every minute, so we don't need to manually refresh it after every build.

If it had an API to trigger a refresh just after the build, it would be even better!

**Comment by andresmgot** [comment]
I see, you can also use the K8s API to trigger the refresh in a script if you want to. What the "Refresh" button does under the hoods is to increment the `resyncRequest` property in the AppRepository object to trigger the update, you can also do so for example with:

```
kubectl patch apprepositories.kubeapps.com -n <repo-namespace> <repo-name> -p='[{"op": "replace", "path": "/spec/resyncRequests", "value": <random-number>}]' --type=json
```

Let me close this issue, please re-open it if you find any issue.
