### ISSUE TITLE
Add option to create functions

### ISSUE THREAD

**Issue by sameersbn** [kubeapps/kubeapps#174]
As a user I want to create new functions or reuse existing functions from a functions catalog.

Functions catalog: helm chart repo of functions

**Comment by arapulido** [comment]
@sameersbn I am a bit confused by this issue and not 💯 % clear on what you mean.

Can you describe here what you mean here? The title says to add an option to create functions, which in a way, already had the old UI, but you also talk about the function catalog.

Please, let's design/discuss here before start implementing anything. Thanks

**Comment by prydonius** [comment]
@arapulido I think this comes from when @sameersbn and I were discussing how this integration will look, but we didn't note down what we discussed, sorry. The flow we were thinking of was:

- Click on "New Function" button
- See a choice to either create a function from scratch or to pick one from a catalog
- Clicking on the option from scratch would deploy a sample function in a runtime of choice
- Clicking on the link to pick one from a catalog would point you to the list of charts from the functions repo

**Comment by prydonius** [comment]
Dropping the Function Catalog idea for now, the 0.5.0 release will just contain a simple form.
