### ISSUE TITLE
Bring your own postgresql

### ISSUE THREAD

**Issue by bcollard** [kubeapps/kubeapps#1741]
Hello,

Discovering Kubeapps today, I wish I could use it without having to install a new instance of Mongo or Postgresql.
I read a bit through your architecture doc, and my understanding is that [Postgresql would replace Mongo in a mid/long term](https://github.com/kubeapps/kubeapps/blob/master/docs/architecture/design-proposals/replacing-mongodb.md). 
Using the Helm chart, I have no other choice than installing a new postgres instance. So, I'm tweaking the chart so that Kubeapps components connect to a "third-party" postgres instance.
Would that make sense for anyone else?

Best regards,
Baptiste

EDIT: fix typo

**Comment by andresmgot** [comment]
Hi @bcollard,

Indeed, if you already have a postgres instance it would be nice to be able to connect to it. Please send a PR if you manage to do so! We can discuss further there.

**Comment by absoludity** [comment]
Once we remove mongodb support this will be trivial (ie. just ensuring the extra args such as `--database-user`, `--database-name`, `--database-url` can be configured via helm). Still worth looking at now though if you're interested (shouldn't be too much more complicated).
