### ISSUE TITLE
MariaDB parameters table is not rendered properly in the hub UI

### ISSUE THREAD

**Issue by carrodher** [kubeapps/kubeapps#1742]
### Description:

In the [kubeapps hub UI](https://hub.kubeapps.com/charts/bitnami/mariadb), the “Parameters” table is not rendered properly while in the [bitnami/charts GitHub](https://github.com/bitnami/charts/tree/master/bitnami/mariadb#parameters) it is shown without any issues.

The same issue is happening in other hubs so it seems the library in charge of render those READMEs is not working as expected in this case.

### Steps to reproduce the issue:

1. Go to https://hub.kubeapps.com/charts/bitnami/mariadb

### Describe the results you received:

Ugly markdown table

### Describe the results you expected:

Pretty markdown table

**Comment by andresmgot** [comment]
hi @carrodher, 

The issue seems to be a missing blank line. While GitHub renderer seems to not care about it, it's necessary to add an empty line between the paragraph and the table:

```patch
The following table lists the configurable parameters of the MariaDB chart and their default values.
+
| Parameter                                    | Description                                                                                                                                                                                                                                                              | Default                                                           |
```

You can see that with this change, other tables are properly rendered:

https://hub.kubeapps.com/charts/bitnami/apache
