### ISSUE TITLE
Feature request: Add step to slider params

### ISSUE THREAD

**Issue by acim** [kubeapps/kubeapps#1743]
Slider is really nice feature, but it would be nice to have a step parameter as well so that we can decide, for example, do we want 1, 3 or 5 instances of some service which has leader election. Something like this:

```json
"sliderMin": 1,
"sliderMax": 5,
"sliderStep": 2
```

Of course, there may some other user cases as well.

**Comment by andresmgot** [comment]
This is easy to implement so adding the "good first issue" if anyone wants to grab it. The Slider code is here, we only need to add the step as a property:

https://github.com/kubeapps/kubeapps/blob/master/dashboard/src/components/Slider/Slider.tsx#L38

And it's used here:

https://github.com/kubeapps/kubeapps/blob/master/dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/SliderParam.tsx#L74

The "step" property can be read as the minimum or the maximum.
