### ISSUE TITLE
issue in kubeapps

### ISSUE THREAD

**Issue by pravicloud** [kubeapps/kubeapps#1744]
### Steps to reproduce the issue:

1. [First Step]
2. [Second Step]
3. [and so on...]

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
(paste your output here)
```

- Output of `helm list <kubeapps-release-name>`:

```
(paste your output here)
```

- Output of `kubectl version`:

```
(paste your output here)
```

**Comment by andresmgot** [comment]
Hi @pravicloud, it seems that you left the issue empty. Let me close this one and please re-open a new one with the information about the issue you are facing (or fill this one).
