### ISSUE TITLE
Manage functions deployed by application charts

### ISSUE THREAD

**Issue by sameersbn** [kubeapps/kubeapps#175]
As a user I want to be able to view and edit functions created by charts.

Description:
---

A application helm chart could have one or more functions as a dependency. The user should be able to list and edit these functions.

Implementation:
---

In the AppView page we can display links to the function page

**Comment by arapulido** [comment]
@sameersbn I would like to discuss/understand the design before implementing

**Comment by prydonius** [comment]
fyi this is just supposed to be a way to link functions deployed in a chart from the app deployment page to the function page.

**Comment by arapulido** [comment]
Closing this as we are not planning to work on this
