### ISSUE TITLE
Is there a way to get logs of release-install?

### ISSUE THREAD

**Issue by shenyiling** [kubeapps/kubeapps#1750]
As the tilte, i used kubeapp to deploy a chart, but not completed.I have defined some hooks in values.yaml to create some resource, but only some of them have installed.I don't know the reason.Could i find any logs in kubeapps or my machine? o _ o

**Comment by andresmgot** [comment]
Hi, the logs of the installation will be either in the `kubeops` or `tiller-proxy` deployments (depending if you used helm v2 or helm v3).

In any case, I don't know if you will find anything interesting there, only the error of the installation if there were one. Did the application get created? If so, even if it failed, you can check more info about it either using the `helm` cli or checking the release page in Kubeapps.
