### ISSUE TITLE
Keep changes in a failed installation

### ISSUE THREAD

**Issue by andresmgot** [kubeapps/kubeapps#1774]
### Description:

When deploying (or upgrading) an application, if the operation fails, the whole page renders only the error. The only way of removing the error is reloading the page and doing so causes that all the changes that has been done to the default values are lost.

### Steps to reproduce the issue:

1. Open a deployment form
2. Do any modification
3. Set a name longer than 53 characters

### Describe the results you received:

The installation fails and you are not allowed to do anything but refreshing.

### Describe the results you expected:

Being able to edit the deployment form to change the conflicting parameter.

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm list <kubeapps-release-name>`:

```
NAME    	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART         	APP VERSION
kubeapps	kubeapps 	3       	2020-06-04 15:20:40.202571364 +0000 UTC	deployed	kubeapps-3.7.0	v1.10.1    
```

**Comment by absoludity** [comment]
+1 for the described result, but I'd also add simple input validation (ie. no js required, just max length for the input) for cases like the one described?

**Comment by andresmgot** [comment]
well, yes, that was only an easy way of making the release fail but yes we can validate the lenght of the name.

**Comment by absoludity** [comment]
You're now bumped back to the application deploy page (at least, I was today when the chart repo was down). Re-open if that's not the case.
