### ISSUE TITLE
Error earlier when trying to deploy an application when "All Namespaces" is selected

### ISSUE THREAD

**Issue by andresmgot** [kubeapps/kubeapps#1775]
### Description:

Right now, the dashboard allows you change values in the deployment form even if "All Namespaces" is selected. Submitting the form without changing the namespace causes an error and because of https://github.com/kubeapps/kubeapps/issues/1774 all the changes introduced are lost.

### Describe the results you expected:

It would be better if the deployment form is not rendered until a namespace is selected.

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm list <kubeapps-release-name>`:

```
NAME    	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART         	APP VERSION
kubeapps	kubeapps 	3       	2020-06-04 15:20:40.202571364 +0000 UTC	deployed	kubeapps-3.7.0	v1.10.1    
```

**Comment by absoludity** [comment]
When a user selects a chart/app to deploy can we just:

1. Keep the existing namespace selected if a namespace is selected, or
1. force a namespace to be selected by ensuring that on this page, the namespace selector does not have the "All namespaces" option. That is, the form still renders, but you can't submit until a namespace is selected?

**Comment by andresmgot** [comment]
> That is, the form still renders, but you can't submit until a namespace is selected?

We would still need a message saying why the submit button is disabled. Also, I would need to verify if changing the namespace cause the form to be reset, right now it just hangs (https://github.com/kubeapps/kubeapps/issues/1776.

**Comment by absoludity** [comment]
Currently forces namespace selection when viewing the catalog.
