### ISSUE TITLE
Changing the namespace in the deployment form causes the application to hang

### ISSUE THREAD

**Issue by andresmgot** [kubeapps/kubeapps#1776]
### Description:

In the deployment form, changing the namespace causes the application to hang:

![Screenshot from 2020-06-05 11-43-43](https://user-images.githubusercontent.com/4025665/83862148-d656e600-a721-11ea-9deb-b948b019e430.png)

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm list <kubeapps-release-name>`:

```
NAME    	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART         	APP VERSION
kubeapps	kubeapps 	3       	2020-06-04 15:20:40.202571364 +0000 UTC	deployed	kubeapps-3.7.0	v1.10.1    
```

**Comment by absoludity** [comment]
No longer applies with the new UI (applying a new context resets the route, currently, though see #2018 ).
