### ISSUE TITLE
Allow negative hidden condition

### ISSUE THREAD

**Issue by batiati** [kubeapps/kubeapps#1781]
#### Description

Allow negative hidden condition
Sometimes is needed to define the "shown" condition instead of "hidden".
Introducing a new parameter "negate" in the "hidden" clause will allow this behavior:

#### Benefits
The hidden condition works well for boolean parameters, but it is not always suitable on string comparisons.

For example, the aim is to **show** the "mariadb" section only when the choosen database matches the condition "mariadb". But instead of it, we have to **hide** the section when the other alternative "postgresql" is selected. It would be impossible to achive if we had three possible databases options to choose.

```
    "mariadb": {
      "type": "object",
      "title": "MariaDB Details",
      "form": true,
      "hidden": {
        "condition": "postgresql",
        "value": "databaseType"
      }
```
Introducing the "negate" condition can expand the possible use cases in a simple way, without having to evaluate complex boolean expressions.

#### Example

The control will be hidden when `databaseType` is **not** equals to "mariadb"
```
    "mariadb": {
      "type": "object",
      "title": "MariaDB Details",
      "form": true,
      "hidden": {
        "condition": "mariadb",
        "value": "databaseType"
        "negate": "true"
      }
```

**Comment by andresmgot** [comment]
Look at the solution that @juan131 is developing here: https://github.com/kubeapps/kubeapps/pull/1720

With that, it's possible to have what you want to achieve, you could hide the `mariadb` section if `databaseType` is equal to `postgresql` OR is equal to `external` or something like that.

**Comment by batiati** [comment]
It works great! Thanks
