### ISSUE TITLE
Changing a version in the Deployment form causes a 404

### ISSUE THREAD

**Issue by andresmgot** [kubeapps/kubeapps#1787]
### Description:

In the deployment form, for a namespace different that `kubeapps`, changing the version causes a 404. This is because it's being redirected to `/ns/default/apps/new/bitnami/apache/versions/<version>` rather than `/ns/default/apps/new-from-global/bitnami/apache/versions/<version>`.

### Steps to reproduce the issue:

1. Selects a namespace other than the Kubeapps one
2. Select an application from the catalog
3. Change the version

### Describe the results you received:

> Chart "bitnami/apache" (7.3.15) not found

### Describe the results you expected:

For the new chart version to load.

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm list <kubeapps-release-name>`:

```
NAME      	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART         	APP VERSION
kubeapps  	kubeapps 	3       	2020-06-05 09:01:23.182877348 +0000 UTC	deployed	kubeapps-3.7.0	v1.10.1    
```

**Comment by absoludity** [comment]
Looks like a simple fix that should be prioritized (since it's fallout from the move to multi-namespace).
