### ISSUE TITLE
Basic Forms: Install-only values

### ISSUE THREAD

**Issue by batiati** [kubeapps/kubeapps#1798]
### Feature

Allow to render some values as read-only for upgrades, allowing the user's input only during the chart installation.

### Benefits

Depending on the chart's implementation, changing some values after the installation can leave to unexpected results or inconsistent deployment.

For example, changing the `database` from `mariadb` to `postgresql` after the installation, may leave to data loss if the chart cannot handle such data migration.

### Drawbacks

This validation may be more suitable to be implemented on Helm itself.

**Comment by andresmgot** [comment]
Agree that this can be something that can be implemented at Helm level but it something easy to implement for Kubeapps.

In any case, we cannot prevent the user to switch to the Advanced tab and modify the value manually in the YAML but that's fine if the user really knows what they are doing.

**Comment by andresmgot** [comment]
BTW @batiati, we are hosting a bi-weekly meeting in which we discuss the progress of Kubeapps, feel free to join! Link to the calendar: https://github.com/kubeapps/kubeapps/releases/download/v1.10.2/kubeapps-iteration-planning.ics
