### ISSUE TITLE
Deleting a namespaced app repo does not delete cronjob nor assets

### ISSUE THREAD

**Issue by absoludity** [kubeapps/kubeapps#1832]
### Description:

Deleting a namespaced app repo leaves the sync cronjob in place and so assets are still returned (but unable to be deployed) after deletion.

### Steps to reproduce the issue:

1. Install `my-repo` in the default namespace using `https://charts.bitnami.com/bitnami`
2. Verify the cronjob is installed, sync performed, and results appear in the catalog
3. Delete the `my-repo` repo in the default namespace

### Describe the results you received:

Results are still shown for the my-repo repository in the catalog, but cannot be deployed.
The cronjob is still present in the kubeapps namespace for syncing the data.

### Describe the results you expected:

Results should no longer appear, nor should the sync cronjob still be present.

### Version of Helm, Kubeapps and Kubernetes:
- Output of `helm version`:

```
helm version
version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}```
```
- Output of `helm list <kubeapps-release-name>`:

```
helm list -n kubeapps
NAME            NAMESPACE       REVISION        UPDATED                                         STATUS          CHART                 APP VERSION
chartmuseum     kubeapps        1               2020-06-24 16:18:45.924973082 +1000 AEST        deployed        chartmuseum-2.13.0    0.12.0     
kubeapps        kubeapps        1               2020-06-24 15:57:01.541583472 +1000 AEST        deployed        kubeapps-3.7.2        v1.10.2    
```

BUT note running a development dashboard image.

- Output of `kubectl version`:

```
k version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-30T20:19:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by andresmgot** [comment]
Hitting this issue, maybe we should prioritize it. Mostly because I cannot add the repo again using a different name, it gets 0 results when visiting the catalog.

**Comment by absoludity** [comment]
The issue here will be that the previous code, where both the app repository and cron jobs etc. are all in the `kubeapps` namespace works because of the owner references (the cronjob being owned by the app repository). Where as for a namespaced app repo they are in different namespaces and so cannot be owned (owner refs are per namespace). Until we enable cron jobs to run in the users namespace (which means updating the asset-sync job to *not* use the DB as a communication layer, see #1647), we'll need to update the backend to delete the cronjob explicitly (so it'll be fine if you delete via Kubeapps UI, but not if you delete the app repo via kubectl).
