### ISSUE TITLE
ErrorSelector gives misleading conflict error message

### ISSUE THREAD

**Issue by lingsamuel** [kubeapps/kubeapps#1834]
### Description:

If a newer charts contains existed resources in cluster, `upgrade` will failed and raise misleading error message.

Code location: https://github.com/kubeapps/kubeapps/blob/9c148707810c8de25768a8727b9ad02d8bf33a2c/dashboard/src/components/ErrorAlert/ErrorSelector.tsx#L36

In this case, it always prints messages: `{ReleaseName}  already exists, try a different name.` which is wrong.

The actual reason is already present in the request response, such as

```json
{"code":409,"message":"Unable to upgrade the release: rendered manifests contain a new resource that already exists. Unable to continue with update: existing resource conflict: namespace: ns-name, name: configmap-name, existing_kind: /v1, Kind=ConfigMap, new_kind: /v1, Kind=ConfigMap"}
```

The backend error location:
https://github.com/kubeapps/kubeapps/blob/9c148707810c8de25768a8727b9ad02d8bf33a2c/pkg/agent/agent.go#L119

This calls the `helm.v3` lib, code location:
https://github.com/helm/helm/blob/release-3.1/pkg/action/upgrade.go#L93

And it can't pass this check:
https://github.com/helm/helm/blob/release-3.1/pkg/action/upgrade.go#L221

### Steps to reproduce the issue:

1. Create a release
2. Add a named config map to chart
3. Create a config map in the same name to cluster
4. Open inspector, select `Network` panel to see the response
5. Try to upgrade the releas

### Describe the results you received:

Upgrade will fail because the config map already exist, but the dashboard displays a misleading error message, inspector shows the response which contains real reason.

### Describe the results you expected:

Dashboard should display the real reason.

### Additional information you deem important:

Just change the title to something like: 
```
title={`${resource} conflict error: ${error.message}`}`
```
will fix this problem.

**Comment by absoludity** [comment]
Wow - thanks for the detailed report. Yep, that error should be more specific.

**Comment by andresmgot** [comment]
The behavior described (showing errors in the error message) is present in the new UI (Kubeapps 2.0). Thanks for reporting!
