### ISSUE TITLE
ServiceCatalog: planUpdatable has no UI

### ISSUE THREAD

**Issue by kvaps** [kubeapps/kubeapps#1847]
### Description:

Services with `spec.planUpdatable=true` supports upgrade/downgrade plans, but it is not working in kubeapps interface

### Steps to reproduce the issue:

1. Install servicecatalog
2. Create clusterserviceclass orr serviceclass with `spec.planUpdatable=true` and plans available.
3. Create an instance from it
4. Try to change the plan for deployed service

### Describe the results you received:

UI has no option to update the plan

### Describe the results you expected:

Some button or another element to change the plan.

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.14.4"}
```

- Output of `helm list <kubeapps-release-name>`:

```
NAME    	NAMESPACE	REVISION	UPDATED                                 	STATUS  	CHART         	APP VERSION
kubeapps	kubeapps 	1       	2020-06-30 09:52:27.701112733 +0200 CEST	deployed	kubeapps-3.7.2	v1.10.2    
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:39:24Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by andresmgot** [comment]
Hi, the development of the integration with services brokers is frozen and it's likely to be deprecated. We are still open to contributions though. If you think you can work on this we will be happy to help with any possible issue.

**Comment by absoludity** [comment]
We've deprecated the service catalog integration.
