### ISSUE TITLE
Upgrade action should be exclusive

### ISSUE THREAD

**Issue by lingsamuel** [kubeapps/kubeapps#1850]
### Description:

Trigger a new `upgrade` action before the previous one finishes, the newer one will probably fail because some hook jobs name conflict, which makes the release status become `failed`. And some jobs remain in the namespace.

### Steps to reproduce the issue:

1. Create a chart contains a lot hooks
2. Upgrade it multiple times
3. The newer one will failed because name conflict, but the previous one is executing normally
4. Release status changes to `failed`

### Describe the results you expected:

The second `upgrade` action should be rejected if there is another upgrade action is running.

### Version of Helm, Kubeapps and Kubernetes:

Kubeapps version 3.7.2 with Helm 3.

**Comment by andresmgot** [comment]
Hi @lingsamuel, we could indeed check the release status and disable the upgrade button if the status is `PENDING_UPGRADE`. Would that solve your issue?

**Comment by lingsamuel** [comment]
I think that's okay.

**Comment by ppbaena** [comment]
Close as it is merged in #3041
