### ISSUE TITLE
Ipv6 support for nginx configration

### ISSUE THREAD

**Issue by supu2** [kubeapps/kubeapps#1853]
kubeapps-fronted-config.yaml and  dashboard-config.yaml  has only ipv4 listen address. Can add "listen [::]:8080;" after listen 8080;
Old conf
`    server {
      listen 8080;
      server_name _;`
New conf
`    server {
      listen 8080;
      listen  [::]:8080;
      server_name _;`

**Comment by andresmgot** [comment]
Hi @supu2,

Thanks for reporting the issue! Do you mind sending a PR fixing it?

**Comment by supu2** [comment]
https://github.com/kubeapps/kubeapps/pull/1856

**Comment by absoludity** [comment]
We should switch so that IPv6 isn't enabled by default, since TKG and k8s upstream don't yet have it as GA.
