### ISSUE TITLE
Kind value is being dropped from binding creation

### ISSUE THREAD

**Issue by ralphsmith80** [kubeapps/kubeapps#1855]
### Description:

Unable to create a Service Binding via the Kubeapps dashboard. This maybe related to #990 .

I have a video link you can download [here](https://1drv.ms/u/s!Au-fZXWZl4eHkHNbaKzvCUCgQ8JR).

### Steps to reproduce the issue:

1. Follow steps on the [service catalog walkthrough](https://svc-cat.io/docs/walkthrough/) up to [step 4](https://svc-cat.io/docs/walkthrough/#step-4---creating-a-new-serviceinstance)
2. Create a service instance via kubeapps
3. Create a service binding via kubeapps 

### Describe the results you received:

Dashboard is returning an error when creating a Service Binding.

### Describe the results you expected:

Service Binding should be created.

### Additional information you deem important (e.g. issue happens only occasionally):

Error response:
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "ServiceBinding in version \"v1beta1\" cannot be handled as a ServiceBinding: unmarshalerDecoder: Object 'Kind' is missing in '{\"metadata\":{\"name\":\"mini-binding\"},\"spec\":{\"instanceRef\":{\"name\":\"mini-instance\"},\"parameters\":{}}}', error found in #10 byte of ...|ters\":{}}}|..., bigger context ...|nceRef\":{\"name\":\"mini-instance\"},\"parameters\":{}}}|...",
  "reason": "BadRequest",
  "code": 400
}
```

The error message seems to imply that the `kind` property is missing. I attempted to issue the same request via Postman with the added `"kind": "ServiceBinding"` metadata key:value but that failed with the same error response. 

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`: 

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"dirty", GoVersion:"go1.14.3"}
```

- Output of `helm list <kubeapps-release-name>`:

Installed via [Quick Start in README](https://github.com/kubeapps/kubeapps#quick-start). Version in UI is noted as [v1.10.2](https://github.com/kubeapps/kubeapps/releases/tag/v1.10.2)

```
Error: "helm list" accepts no arguments
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:18:29Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by andresmgot** [comment]
Hi @ralphsmith80,

Indeed it seems that we are not setting the `Kind` while submitting ServiceBindings:

https://github.com/kubeapps/kubeapps/blob/master/dashboard/src/shared/ServiceBinding.ts#L58

We would need to add the `Kind` there, maybe you can give it a try?

Also, as far as I know, Minibroker is not compatible with Helm 3 so I'd be wary of that: https://github.com/kubeapps/kubeapps/issues/1623

**Comment by ralphsmith80** [comment]
Thanks @andresmgot! 

I had plans to dig into the code to see if adding that would fix the issue. Thanks for pointing out the area in the code. That'll save me some time digging. Since my test with Postman failed I'm not sure if that change alone will address the issue.

> I attempted to issue the same request via Postman with the added "kind": "ServiceBinding" metadata key:value but that failed with the same error response.

Thanks for the heads up on helm 3 and minibroker. I didn't note any issues other than documented syntax for helm when getting minibroker running via helm 3 but I'll keep that in mind.

**Comment by ralphsmith80** [comment]
I started looking at this yesterday afternoon. Adding the following to the `post` does get past the `kind` issue.

```
apiVersion: "servicecatalog.k8s.io/v1beta1",
kind: "ServiceBinding",
```

After that there's a 404 error fetching the secret I'm looking out now. At first glance I'm thinking this might be caused by the `apiVersion: "v1"` post param. 

As another note, I ran into issues getting telepresence to work due to the [Mac SIP issue](https://www.telepresence.io/reference/methods). As a work around because the project uses create-react-app (good choice) I did the following:

1. Run kubeapps per the docs `kubectl port-forward -n kubeapps svc/kubeapps 8080:80`
2. proxy local app XHRs via the `proxy` key in package.json - `"proxy": "http://127.0.0.1:8080"`

Updating the developer docs for that as an alternative to telepresence would be a good idea. If I wasn't already familiar with CRA I would have been stuck.

**Comment by andresmgot** [comment]
Thanks for the details @ralphsmith80. I was not aware of that option for running the dashboard, cool :) Do you mind sending a PR for the dev docs explaining it?

**Comment by ralphsmith80** [comment]
@andresmgot I included the binding fix and the doc update in the above PR. ☝️

**Comment by andresmgot** [comment]
Thanks! Let me close this issue then. The fix will be included in the next release :)
