### ISSUE TITLE
Kubeapps OIDC Authentication returns to login screen after successful authentication

### ISSUE THREAD

**Issue by vrabbi** [kubeapps/kubeapps#1874]
### Description:
I have deployed Kubeapps on a TKG Workload cluster which uses Dex on the Management Cluster as its OIDC provider. Dex is configured with AD as its backend.
authentication to the cluster with AD users via Dex works as expected.
I have deployed kubeapps and added the kubeapps IP (i used service type load balancer for the frontend) and redirect URL in the staticClient section in Dex to allow redirect back to the relevant URL.
When i log into Kubeapps, It redirects to Dex for authentication. when i sign it it just redirects back to the login page and never opens the dashboard.
to deploy kubeapps i used the following command:
helm install kubeapps bitnami/kubeapps   --namespace kubeapps --set authProxy.enabled=true   --set authProxy.provider=oidc   --set authProxy.clientID=<CLUSTER_NAME>   --set authProxy.clientSecret=<SECRET>   --set authProxy.cookieSecret=$(echo "not-good-secret" | base64)   --set authProxy.additionalFlags="{-cookie-secure=false,-oidc-issuer-url=https://<DEX_IP>, -ssl-insecure-skip-verify}" --set useHelm3=true --set frontend.service.type=LoadBalancer

### Steps to reproduce the issue:

1. Deploy a TKG Management Cluster
2. Enable Dex with AD backend on the management cluster
3. Deploy an OIDC enabled Workload cluster
4. deploy kubeapps with the relevant parameters as describe above
5. try to login

### Describe the results you received:

When i log into Kubeapps, It redirects to Dex for authentication. when i sign it it just redirects back to the login page and never opens the dashboard.

### Describe the results you expected:

login should work

### Additional information you deem important (e.g. issue happens only occasionally):

Log from the auth-proxy container:
<WORKER_NODE_IP> - - [2020/07/20 15:30:19] <FRONTEND_LB_IP> GET - "/oauth2/start" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36" 302 280 0.000
<WORKER_NODE_IP> - scott@terasky.local [2020/07/20 15:30:28] [AuthSuccess] Authenticated via OAuth2: Session{email:scott@terasky.local user:Cj1DTj1TY290dCBSb3NlbmJlcmcsT1U9UGVyc29uYWwsT1U9VFNVc2VycyxEQz10ZXJhc2t5LERDPWxvY2FsEgRsZGFw PreferredUsername: token:true id_token:true created:2020-07-20 15:30:28.982529091 +0000 UTC m=+2084.801338998 expires:2020-07-20 15:35:27.982199577 +0000 UTC m=+2383.801009485}
<WORKER_NODE_IP> - - [2020/07/20 15:30:28] <FRONTEND_LB_IP> GET - "/oauth2/callback?code=oqlffsse5qhemzqfdux55zznb&state=eb1d99be74144809ea117e92470ff75c%3A%2F" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36" 302 24 0.024
<WORKER_NODE_IP> - - [2020/07/20 15:30:28] <FRONTEND_LB_IP> GET localhost:8080 "/" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36" 304 0 0.001
<WORKER_NODE_IP> - scott@terasky.local [2020/07/20 15:30:29] <FRONTEND_LB_IP> GET localhost:8080 "/api/clusters/default/" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36" 401 165 0.004

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

- Output of `helm list <kubeapps-release-name>`:

```
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
kubeapps        kubeapps        1               2020-07-20 17:55:40.342639984 +0300 IDT deployed        kubeapps-3.7.4  v1.10.3

```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3+vmware.1", GitCommit:"9c3cd5473f5bd8199eb7444ba5c04e5eca2f83f7", GitTreeState:"clean", BuildDate:"2020-05-22T05:14:06Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by vrabbi** [comment]
bad configuration on my end. it works now

**Comment by batiati** [comment]
Hi @vrabbi 
I'm facing this very same issue, do you mind to detail which configurations were wrong at your end? It seems that the oidc is correctly authenticated, but the k8s api is denying acccess thowing the "found 1 parts of token" error.

I'm using Rancher k8s v1.19.2 + Keycloak

Logs from auth-proxy container:
```
10.42.0.0:41256 - batiati@triadesolucoes.com.br [2020/10/12 19:11:58] [AuthSuccess] Authenticated via OAuth2: Session{email:batiati@triadesolucoes.com.br user:24785368-d4d5-4b70-980f-730d3727576c PreferredUsername:batiati token:true id_token:true created:2020-10-12 19:11:58.148116984 +0000 UTC m=+2239.540143351 expires:2020-10-12 19:12:58.147599382 +0000 UTC m=+2299.539625849 refresh_token:true}
10.42.0.0:41256 - - [2020/10/12 19:11:58] kubeapps.multiclubes.com.br GET - "/oauth2/callback?state=328c1a68f6d58924c4fb80a299cbcc80%3A%2F&session_state=19e9b0ee-09da-4487-83af-618a8ab65ee4&code=0340b0dd-8525-41ea-982b-f53f0de07753.19e9b0ee-09da-4487-83af-618a8ab65ee4.fdf564b3-5594-4570-b0f0-c40dec9902bb" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36" 302 24 0.051
10.42.0.0:41256 - batiati@triadesolucoes.com.br [2020/10/12 19:11:58] kubeapps.multiclubes.com.br GET / "/api/clusters/default/" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36" 401 165 0.006
```

Logs from kube-api-auth:
`´`
time="2020-10-12T19:11:58Z" level=info msg="Processing v1Authenticate request..."
time="2020-10-12T19:11:58Z" level=error msg="found 1 parts of token"
```

Thank you in advance

**Comment by kvaps** [comment]
auth-proxy log:
```
10.112.1.245:36708 - - [2020/10/14 08:43:25] kubeapps-stage.example.org GET - "/oauth2/start" HTTP/1.1 "Mozilla/5.0 (X11; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0" 302 318 0.000
10.112.1.245:36708 - - [2020/10/14 08:43:27] kubeapps-stage.example.org GET - "/api/clusters/default/" HTTP/1.1 "Mozilla/5.0 (X11; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0" 403 2642 0.000
```

keycloak log:
```
{
  "@timestamp": "2020-10-14T08:43:26.163Z",
  "sequence": 2577,
  "loggerClassName": "org.jboss.logging.Logger",
  "loggerName": "org.keycloak.events",
  "level": "INFO",
  "message": "type=CODE_TO_TOKEN, realmId=nextcloud, clientId=kubeapps, userId=1cdd3e59-a195-4f61-957f-8e737179b3eb, ipAddress=10.28.36.177, token_id=8841e94a-d49c-4490-835d-445e62d7007b, grant_type=authorization_code, refresh_token_type=Refresh, scope='openid email profile', refresh_token_id=d3e2bb31-79be-4cdb-b8f1-2e88d3675780, code_id=b931940d-2bed-408d-ab08-a35cce7c3524, client_auth_method=client-secret",
  "threadName": "default task-13",
  "threadId": 10659,
  "mdc": {},
  "ndc": "",
  "hostName": "keycloak-1",
  "processName": "jboss-modules.jar",
  "processId": 508,
  "@version": "1"
}
```

apisrver logs are clean

I use kubeapps behind the nginx-ingress-controller, not sure if it is connected.

**Comment by andresmgot** [comment]
Thanks @batiati let's keep the conversation in #2111 since both seems similar issues.
