### ISSUE TITLE
Proposal: Execution log

### ISSUE THREAD

**Issue by lingsamuel** [kubeapps/kubeapps#1919]
If the helm package contains a lot of hooks, it takes a long time to execute. Can we logs the hooks execution process?

I take a look at helm's source code, found that helm didn't provide such feature. I made a proposal here https://github.com/helm/helm/issues/8530

Is kubeapps team interesting in it? I can implement it in helm SDK (v3).

**Comment by absoludity** [comment]
Yeah - that'd definitely be useful, to provide more information about which hooks were being processed or why an install failed etc.
