### ISSUE TITLE
lost connection to pod with portforward.go

### ISSUE THREAD

**Issue by bayudwiyansatria** [kubeapps/kubeapps#1925]
Hi, i'm trying install `kubeapps` but seem found error while installing.
Tiller are deployed using `service account`. And `ClusterRoleBinding` has been set.

I'm also tried to install other packages with `helm` and successfully.

### Error :
```
E0806 07:11:53.201572   25732 portforward.go:233] lost connection to pod
E0806 07:12:23.175693   25732 portforward.go:340] error creating error stream for port 35038 -> 44134: Timeout occured
```
### Command :
```
helm install --name kubeapps --namespace kubeapps --wait --set featureFlags.operators=true bitnami/kubeapps
```

### Helm Version :

```
Client: &version.Version{SemVer:"v2.16.9", GitCommit:"8ad7037828e5a0fca1009dabe290130da6368e39", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.8", GitCommit:"145206680c1d5c28e3fcf30d6f596f0ba84fcb47", GitTreeState:"clean"}
```

### Kubectl Version :

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

### Cloud Provider/Platform : 

Self-Hosted on premises at Vultr

**Comment by absoludity** [comment]
Hi there. Can you provide more info, for example, when exactly do you see this message? (if during install, can you paste your `helm install` command and all its output, if it's after install, can you paste the output of `kubectl get pods --namespace <your namespace>` as well as relevant logs for any failing pod). Thanks!

**Comment by bayudwiyansatria** [comment]
> Hi there. Can you provide more info, for example, when exactly do you see this message? (if during install, can you paste your `helm install` command and all its output, if it's after install, can you paste the output of `kubectl get pods --namespace <your namespace>` as well as relevant logs for any failing pod). Thanks!

Hello @absoludity 
Thank you for replying.
I think the problem are in `kubectl` found the thread the corellated https://github.com/kubernetes/kubernetes/issues/74551.

And i have successfully running `kubeapps` to my environment.
The problem appears only when running HA kubernetes multi master with 1 or more master are low resources. Some times the etcd leader changed.

Best regards,
Bayu Dwiyan Satria

**Comment by absoludity** [comment]
Glad it's sorted. I'll close this then. Thanks.
