### ISSUE TITLE
Documentation for users access management

### ISSUE THREAD

**Issue by jgato** [kubeapps/kubeapps#1927]
this is just a suggestion to improve documentation about configuring user's access management.

[The section for read/write app repositories](https://github.com/kubeapps/kubeapps/blob/master/docs/user/access-control.md#app-repositories), talks about binding the role "apprepositories-read". But you dont provide the yaml for that. It is the same than role "kubeapps-apps-read", but it would be confusing for people just following the tutorial and not enough K8s knowledge (like me). By the way, the role name is "apprepositories-read" or" kubeapps-apprepositories-read"?.

It happens the same in the section for write app repositories.

The way of executing the kubectl command changes from what it has been done in previous steps (wold be confusing). An environment variable instead of using --namespace. I suggest using the same way. 

In any case the command seems also confusing about the rolebinding:

```
kubectl create -n $KUBEAPPS_NAMESPACE rolebinding example-kubeapps-repositories-read \
  --clusterrole=kubeapps:$KUBEAPPS_NAMESPACE:apprepositories-read \
  --serviceaccount default:example
```

--clusterole==kubeapps:$KUBEAPPS_NAMESPACE:apprepositories-read

shouldnt be just..?

--clusterole==apprepositories-read

Again, the role name is apprepositories-read, but the one for reading apps is kubeaps-apprepositories-read.

For the apprepositories write section. Shouldnt we use an existing kubernetes role write, like we did with role edit in the apps write?

I am just trying to clarify that, because it is taking me a lot of time to reproduce the whole process (maybe because I am pretty new to Kubernetes)

many thanks

EDIT: As per a [comment from Curtis below](https://github.com/kubeapps/kubeapps/issues/1927#issuecomment-674467601), the confusion may be that the docs indicate `kubeapps:$KUBEAPPS_NAMESPACE:apprepositories-read` where as it may now be a const: `kubeapps:kubeapps:apprepositories-read` (we should double-check why it was changed - I think i did it as part of the per-namespace app repos work, but need to check the details).

**Comment by absoludity** [comment]
Hi there. Thanks for the feedback, I'll take a closer look tomorrow, but when you try:
```
kubectl get clusterrole | grep apprepositories
```

you should see the clusterroles which Kubeapps installs, like:

```
kubeapps:kubeapps:apprepositories-read                                 2020-08-06T05:18:41Z
kubeapps:kubeapps:apprepositories-write                                2020-08-06T05:18:41Z
```

(note the names depend on your choice of helm release name).

Is that not the case?

**Comment by jgato** [comment]
Hi :) 

I have different names:

```
 $  kubectl get clusterrole | grep apprepositories
apprepositories-read                                                   2020-08-06T07:46:30Z
apprepositories-write                                                  2020-08-06T08:08:33Z
kubeapps:kubeapps:apprepositories-read                                 2020-08-05T12:17:51Z
kubeapps:kubeapps:apprepositories-write                                2020-08-05T12:17:51Z

```

Pretty strange, I dont remember creating kubeapps:kubeapps:apprepositories-read and write. What could have happened?

With this roles if I try to create a repo from the dashboard:

![image](https://user-images.githubusercontent.com/3435696/89508451-3b849180-d7ce-11ea-989c-074a63df9d58.png)

**Comment by jgato** [comment]
Ok I have fixed last part, I created wrongly the role apprepositories-write  ;)  Now it is in the way:

```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: apprepositories-write
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - create
  - delete
  - patch
  - update

```
But it is better if you provide that in the documentation to avoid errors, like the one I just did jajaja

**Comment by absoludity** [comment]
> Hi :)
> 
> I have different names:
> 
> ```
>  $  kubectl get clusterrole | grep apprepositories
> apprepositories-read                                                   2020-08-06T07:46:30Z
> apprepositories-write                                                  2020-08-06T08:08:33Z
> kubeapps:kubeapps:apprepositories-read                                 2020-08-05T12:17:51Z
> kubeapps:kubeapps:apprepositories-write                                2020-08-05T12:17:51Z
> ```
> 
> Pretty strange, I dont remember creating kubeapps:kubeapps:apprepositories-read and write. What could have happened?

They are created by the kubeapps chart when you install Kubeapps. They're the ones the documentation are referring to, so that when you asked:

> --clusterole==kubeapps:$KUBEAPPS_NAMESPACE:apprepositories-read
> 
> shouldnt be just..?
> 
> --clusterole==apprepositories-read

it is actually the first one (`kubeapps:$KUBEAPPS_NAMESPACE:apprepositories-read`).

**Comment by jgato** [comment]
So, should I create the roles in that way? kubeapps:$KUBEAPPS_NAMESPACE:apprepositories-read, instead of my apprepositories-read?
in this moment it is working for me.

**Comment by absoludity** [comment]
There's no need to change your setup if it's working, it's just that the documentation tries to get you to use these existing cluster roles which it creates when you install the chart, to avoid errors. But yes, we can make that clearer.

**Comment by jgato** [comment]
cool. Tell me if I can help you and I will re-produce the documentation :)

**Comment by ccollicutt** [comment]
Right now, you follow the docs but use a namespace other than kubeapps then you won't have the right permissions.

**Comment by absoludity** [comment]
Thanks for the detail @ccollicutt . If either of you are keen for a quick PR to fix that, we'll land it, otherwise I'll fix it soon. Thanks either way!

**Comment by andresmgot** [comment]
> Right now, if you follow the docs but use a namespace other than kubeapps then you won't have the right permissions. The docs show setting a variable for kubeapps:$KUBEAPPS_NAMESPACE:apprepositories-read, but the kubeapps installed clusterole is always called "kubeapps:kubeapps:apprepositories-read".

This may caused by a badly rendered command, I have updated the docs to use `kubeapps:${KUBEAPPS_NAMESPACE}:apprepositories-read` but I can confirm that the cluster-role is properly created with the namespace in which Kubeapps is installed to avoid collision with other kubeapps instances.

I have detected several errors/confusing things in the docs, take a look if you have a chance!
