### ISSUE TITLE
Automatically delete and start sync cronjob after a long cluster down time

### ISSUE THREAD

**Issue by lingsamuel** [kubeapps/kubeapps#1941]
### Description:

The Kubernetes has a bug https://github.com/kubernetes/kubernetes/issues/42649 that makes cronjob never trigger after cluster recovers, which breaks AppRepo sync.

### Steps to reproduce the issue:

1. Add an App Repository, set a small sync schedule (`* * * * *` for example)
2. Stop the cluster for a long time (bigger than 100x schedule time)
3. Resume the cluster
4. The cronjob won't be triggered because the issue mentioned above

### Describe the results you received:

The cronjob won't be triggered anymore

### Describe the results you expected:

Can kubeapps detects the cronjob event `FailedNeedsStart` and then delete it and re-start it again to recover?

**Comment by andresmgot** [comment]
mmh, this seems like something that needs to be fixed for Kubernetes (and something that happens only in development environments)

**Comment by lingsamuel** [comment]
It's in development env indeed, I set a small schedule to sync CI generated charts.
It's a staled upstream bug, seems that the K8s team doesn't interest in it. We could handle such occasion so the non-fixed version K8s can work, or at least, we can add it as a FAQ?

**Comment by andresmgot** [comment]
> we can add it as a FAQ?

Yes, that can be helpful for others. Do you mind sending a PR? A good place for that is here: https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps#troubleshooting

**Comment by absoludity** [comment]
Closing as it's affecting local dev env only, is related to an upstream k8s bug. Happy to re-open and accept patches.
