### ISSUE TITLE
how to Secondary development KubeApps ?

### ISSUE THREAD

**Issue by lypee** [kubeapps/kubeapps#1952]
Sorry for my bad English 
We want us to input ***.yaml content and these content can into Database ,We can search it and deploy it by ***.yaml files that we input .
I dont know How to store the contents of the warehouse in the database in which form
Looking forward to your answer ;

**Comment by lypee** [comment]
Which function is stored in the database

**Comment by absoludity** [comment]
Currently Kubeapps only supports importing Helm charts for deployment (though there is also operator support behind a feature flag, it does not use the database at all).

We don't currently support importing plain yaml content for deployment, though we do have plans to generalise the current chart support so in the future plugins can be written for different formats.

Currently, your only option would be to convert your yaml content to a basic Helm chart and include it in a helm 2 repository.

Please re-open if that doesn't answer your question :)

**Comment by andresmgot** [comment]
I believe you may want to have something like what's requested in this issue: https://github.com/kubeapps/kubeapps/issues/859 (being able to use different values yaml like `production-values.yaml`). If that's your case, you can subscribe to that issue to get updates.

**Comment by lypee** [comment]
> Currently Kubeapps only supports importing Helm charts for deployment (though there is also operator support behind a feature flag, it does not use the database at all).
> 
> We don't currently support importing plain yaml content for deployment, though we do have plans to generalise the current chart support so in the future plugins can be written for different formats.
> 
> Currently, your only option would be to convert your yaml content to a basic Helm chart and include it in a helm 2 repository.
> 
> Please re-open if that doesn't answer your question :)

Can I  Secondary development  Kubeapps to achieve my goal

**Comment by lypee** [comment]
t

> Currently Kubeapps only supports importing Helm charts for deployment (though there is also operator support behind a feature flag, it does not use the database at all).
> 
> We don't currently support importing plain yaml content for deployment, though we do have plans to generalise the current chart support so in the future plugins can be written for different formats.
> 
> Currently, your only option would be to convert your yaml content to a basic Helm chart and include it in a helm 2 repository.
> 
> Please re-open if that doesn't answer your question :)

We usr Harbor as private repository
We want to be able to enter (yaml file) on the page  and  ability to store the contents of files in the database
Then we can go to the Catalog column and deploy it .
