### ISSUE TITLE
I can't enter the pod of assetsvc

### ISSUE THREAD

**Issue by lypee** [kubeapps/kubeapps#1963]
I enter the command : kubectl exec -it ASSETSVC_POD_NAME /bin/bash or /bin/sh ，
It prompted me ： 
OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"/bash\": stat /bash: no such file or directory": unknown
command terminated with exit code 126

**Comment by andresmgot** [comment]
That's because the container is made `FROM: scratch` to be as minimal as possible, which means that it only has the golang binary. Closing this as this is not an issue. If you want to reach us to ask any question, you can also find us in the #kubeapps channel in the Kubernetes slack org.
