### ISSUE TITLE
Cannot upgrade if current installed version chart is missing

### ISSUE THREAD

**Issue by lingsamuel** [kubeapps/kubeapps#1984]
### Description:

If the installed version chart is missing from the repository source (such as Chartmuseum), it can't be upgraded.

### Steps to reproduce the issue:

1. Create a chart v1.0.0, push it to Chartmuseum
2. Install it
3. Upgrade the chart to a newer version, the "Update Available" sign appears
4. Delete the current version chart from Chartmuseum
5. The "Update Available" sign is gone. Manually click the `upgrade` button, kubeapps will ask me which repo should it use, after selection, it says `xxx(v1.0.0) not found`

### Describe the results you received:

This happens in an accident data loss in my private Chartmuseum.
I can't upgrade my chart unless I manage to recover the current version chart (I am not sure whether a *fake* chart with same version will work).

### Describe the results you expected:

I think the current version chart shouldn't affect the upgrade function because the newer version chart is already presented. I am not sure if it's a Helm limit.

### Version of Helm, Kubeapps and Kubernetes:

Kubeapps version 3.7.3 with Helm 3, K8s version 1.13.2.

**Comment by andresmgot** [comment]
hi @lingsamuel, I understand your issue. The current logic to check if an app belongs to a repository is checking if the combination of chart ID + chart version + app version is available in a registry, if it's the case, we are confident enough that the app comes from that registry (since we don't have a way to know it for sure, check [this issue](https://github.com/helm/helm/issues/6464) for more info).

We could relax that check and allow people to force-select a repository only if the chart ID is present. Maybe you are able to give it a try?

> (I am not sure whether a fake chart with same version will work).

Yes, that will work as a workaround as far as the combination of ID + version is the same.

**Comment by lingsamuel** [comment]
What do you mean "give *it* a try"?

**Comment by andresmgot** [comment]
No, I mean having the possibility to force the selection of a repository, even if the check that verifies that the chart exists fail.

The fake chart workaround will work for sure (if that's good enough for you).

**Comment by lingsamuel** [comment]
It sounds like I need to wait for some patches?

**Comment by andresmgot** [comment]
Do you mean because of https://github.com/kubeapps/kubeapps/issues/1980? That shouldn't affect you if you are seeing the `SelectRepoForm`. Or do you mean for some other patch?

**Comment by lingsamuel** [comment]
In fact, I don't know how to "force-select a repository" (`SelectRepoForm` you mentioned). I just thought it was a incoming feature, is it already exist? How can I find it?

**Comment by andresmgot** [comment]
No, I meant that it's a feature that you could try to implement :) Sorry our plates are a bit full with the work of the UI revamp and the multicluster support so we won't be able to work on this anytime soon.

If you are interested let me know, I can guide you a bit around the code.

**Comment by lingsamuel** [comment]
I know very little about Frontend and React, I am afraid I can't help...

**Comment by antgamdia** [comment]
Hi! We have recently revamped our backend (v2.4.0 onwards) and we also improved a little bit the manual repository selection (below). From now on we will support more packaging formats besides Helm, so the backend has moved to a plugin-based arch. 
Let me close the issue for now, but please, feel free to reopen it if the issue still persists.

![image](https://user-images.githubusercontent.com/11535726/133118714-7ed824db-0158-4a92-884c-6b413762038e.png)
