### ISSUE TITLE
[Upgrade Flow] Allow to select global or namespaced repositories

### ISSUE THREAD

**Issue by andresmgot** [kubeapps/kubeapps#1987]
### Description:

Follow up of https://github.com/kubeapps/kubeapps/issues/1980. If the repository cannot be automatically detected, show repositories from both namespaces: the current one and the global one.

**Comment by absoludity** [comment]
Can you add the steps to reproduce this? Txs.

**Comment by andresmgot** [comment]
Yes.

 - Deploy a chart in the namespace `default` from the `bitnami` repo.
 - Delete the `bitnami` repo.
 - Try to upgrade the chart.

That will show the error when the repository selector should be shown instead (if you don't have repositories in the `default` namespace).
