### ISSUE TITLE
Cannot use external auth proxy without patching frontend service

### ISSUE THREAD

**Issue by zahid0** [kubeapps/kubeapps#1996]
### Description:

When using external auth proxy, the Kubeapps service is not accessible. In the frontend service the value of `targetPort` should be `http` instead of `proxy`.

https://github.com/kubeapps/kubeapps/blob/ea44804980d7238e94096d9c3ba499438a64d169/chart/kubeapps/templates/kubeapps-frontend-service.yaml#L16

The above line should be changed to
```
{{- if and .Values.authProxy.enabled (not .Values.authProxy.external) }}
```

**Comment by zahid0** [comment]
@absoludity

**Comment by andresmgot** [comment]
Right, good catch @zahid0. Do you mind sending a PR?

**Comment by absoludity** [comment]
Thanks @zahid0 . Let us know if you want / have time to update it (one-liner). In the longer-term, I'd like to have CI testing the proxy setups.
