### ISSUE TITLE
goget doesn't build correctly

### ISSUE THREAD

**Issue by arapulido** [kubeapps/kubeapps#20]
If you get the project with goget, you get the following error:

```
package github.com/kubeapps/installer/generated/statik: cannot find package "github.com/kubeapps/installer/generated/statik" in any of:
	/usr/local/Cellar/go/1.9.2/libexec/src/github.com/kubeapps/installer/generated/statik (from $GOROOT)
	/Users/ara/go/src/github.com/kubeapps/installer/generated/statik (from $GOPATH)
```

**Comment by ngtuna** [comment]
Right. As we rejected to put `generated/statik` into git push. It's better generated at the build time. Let me find a way how to support `go get`

**Comment by jjo** [comment]
> Right. As we rejected to put generated/statik into git push. It's better generated at the build time. Let me find a way how to support go get

imo we should review this policy, and re-commit it in-tree, to enable
`go get ...` - it wouldn't be the 1st in-tree blob~ish we include,
fwiw  just peek at `vendor/` for .ico, .jpg and alike
