### ISSUE TITLE
Refactor namespace management UX

### ISSUE THREAD

**Issue by andresmgot** [kubeapps/kubeapps#2018]
### Description:

Follow up of https://github.com/kubeapps/kubeapps/pull/2016#issuecomment-689438445

For the moment, we are everyone to list app in all namespaces and to create namespaces. If they don't have RBAC permissions, they will eventually get an error which may not be the best UX.

We need to implement the backend logic to enable/disable these features. Potentially hiding or disabling the related buttons in the UI.

**Comment by andresmgot** [comment]
## Current status

After successfully logging in the system, the user is presented with the context selector in which they will be able to select the namespace and cluster to work on. By default, the namespace associated to the service account is selected. If the account is not associated to a namespace, "All Namespaces" is selected.

If the user has permissions to list namespaces, the list of all namespaces available is shown. In other case, the `kubeops` serviceaccount is used to filter out the namespaces in which the user doesn't have permissions.

When changing the context, the user is redirected to the AppList view since it's the safest thing to do.

## Proposed changes

 1. Even if a user has permissions to list namespaces, remove from the list the namespaces in which the user doesn't have permissions. This prevents from errors selecting a wrong namespace.
 2. If the user doesn't have an associated namespace, use the first one available (in alphabetical order). This will autoselect the available namespace in case a user is only allowed to work in a single namespace.
 3. Apart from filtering out the namespaces in which the user doesn't have permissions, remove the ones in "terminating" state (#543).
 4. Remove the "All Namespaces"  option from the context selector. This option only makes sense in certain views: ApplicationList and OperatorList. Using "All Namespaces" in other views like the Catalog or the Deployment Form is troublesome. Rather than showing this option in the Context Selector, we can add a checkbox in the views interested: "[ ] Show applications from all namespaces".
 5. Store the last namespace used in the browser console. That way, when reloading or logging in again, the work from the previous session can be resumed. Remove this parameter when intentionally logging out from the system (so other users will use their preferred namespace). If the stored namespace is not in the list of allowed namespace, fallback to the default behavior.
 6. Disable the "Create Namespace" button when the user doesn't have permissions to create a namespace. When hovering the disabled button, information text about the missing permissions should be shown.
 7. Disable the dropdown menus and the "Change Context" button for views in which changing the context may throw an error. Changing the cluster / namespace is only safe in certain views (AppList, Catalog, OperatorList, AppRepoList). Doing that in other views (e.g. in the ApplicationView) may throw errors (e.g. a Not Found error). When the "Change Context" is disabled, hovering over the button should show information about why it's been disabled. Note that the default should be to disable the context change, only allowing it in specific views in which that behavior is properly tested.

**Comment by absoludity** [comment]
So we already do (1) for people who don't have perms to list namespaces and we use the service account if available? +1 to use the same code.

With 4., will this mean we no longer have a specific route for all namespaces in those list views, or we'll update the route when the checkbox is selected. Also, what behaviour does the namespace selector have when the checkbox is selected? (Probably clearest to just use current behaviour and change the namespace and implicitly unchecking the checkbox). We should also be careful here to design a UX solution for these list views which will also allow "All clusters" in the future too.

I'm not sure about 7 and 7.1. Rather than disabling the change context button, could 7.1 be used for those views where it makes sense while others (where changing context doesn't make sense) go back to the app list? This would continue to avoid the errors while still enabling 7.1 for those views where it makes sense.

**Comment by andresmgot** [comment]
> So we already do (1) for people who don't have perms to list namespaces and we use the service account if available? +1 to use the same code.

Yes, 1. is for people that has permissions to list namespaces but don't have permissions to use all those namespaces. Right now, all of those are listed but they are not usable.

> With 4., will this mean we no longer have a specific route for all namespaces in those list views, or we'll update the route when the checkbox is selected. 

Yes, well we can have that as a query parameter: `/c/default/namespace/default/apps?all_ns=true`.

> Also, what behaviour does the namespace selector have when the checkbox is selected? (Probably clearest to just use current behaviour and change the namespace and implicitly unchecking the checkbox). We should also be careful here to design a UX solution for these list views which will also allow "All clusters" in the future too.

My idea is to leave it with the original namespace (I don't think that's confusing?). We can have similar checkboxes for all clusters (if that makes sense).

> I'm not sure about 7 and 7.1. Rather than disabling the change context button, could 7.1 be used for those views where it makes sense while others (where changing context doesn't make sense) go back to the app list? This would continue to avoid the errors while still enabling 7.1 for those views where it makes sense.

Having the same button that behaves differently depending on the view is IMO more confusing. For me it would seem buggy that if I change the namespace in the catalog it still shows the catalog but if I do so in the chart view it redirects me to the app list. IMO it's more clear if the button is disabled and if I hover it says "Changing context is not allowed in the current page".
