### ISSUE TITLE
Move helm/operator support to plugin interface

### ISSUE THREAD

**Issue by absoludity** [kubeapps/kubeapps#2023]
### Description:

As different Kubernetes packaging formats emerge and gain in popularity, it would be great to ensure that Kubeapps itself remains relevant rather than being coupled to one particular packaging format such as Helm (or operators).

To do this, we first need to define an interface/contract that can be fulfilled by different backend plugins while keeping the support for the current Helm (and operator? though this is quite different as its more than a packaging framework given the OLM requirements etc.) functionality unbroken.

Once we have defined the interface and plugin system, and migrated the existing Helm support, adding support for `kapp` from [Carvel](https://k14s.io/) would be a great first candidate.

Regarding the plugin system, I assume we could learn and benefit quite a bit from Octant's plugin system.

**Comment by andresmgot** [comment]
> (and operator? though this is quite different as its more than a packaging framework given the OLM requirements etc.)

Yes, IMO it should cover the operator use case as well. In fact it can be easily compared to Helm:

 - Requirement: Helm => OLM
 - Source: App Repository => Operator catalog (e.g. OperatorHub)
 - Application Definition: Chart => Operator
 - Instance: Release => Operator Instance

**Comment by andresmgot** [comment]
I have deleted a note that were in the dashboard related to this issue:

> Decouple Kubeapps dependence on helm by focusing on support for tools that render yaml (such as helm, or ytt) and then deploying those yaml configs with https://get-kapp.io/, for example, though this would break cli compatibility unless kapp can support the same release format (check).

**Comment by absoludity** [comment]
Rather than creating/implementing a pluggable API, we should investigate using the K8s aggregation API https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/apiserver-aggregation/ , which would allow registering different backends as they're supported etc.

**Comment by antgamdia** [comment]
Closing as this change was released in v2.4.0 and other subtasks are already tracked in other issues.
