### ISSUE TITLE
Hide "All Namespaces" if user is restricted

### ISSUE THREAD

**Issue by kfirfer** [kubeapps/kubeapps#2041]
Hello

**Feature suggestion**

If the user hasn't rule to view namespaces, would be nice to hide the "All Namespaces" in the namespaces drop-down list

![Selection_002](https://user-images.githubusercontent.com/7741545/93356624-1876e400-f848-11ea-8b4a-6559234796ce.png)

Same goes to "Create New" (namespace)

**Comment by kfirfer** [comment]
i sew that you already created a issue:
#2018 
closing issue

**Comment by andresmgot** [comment]
Indeed, thanks for the feedback @kfirfer
