### ISSUE TITLE
Set success/fail history limit of the apprepo's sync jobs

### ISSUE THREAD

**Issue by kfirfer** [kubeapps/kubeapps#2047]
Hello

Would be nice to see ability to set cronjob history success/failures of the jobs generated by apprepo sync controller
For example:

- --successful-jobs-history-limit=1
- --failed-jobs-history-limit=2

**Comment by andresmgot** [comment]
Thanks for the suggestion @kfirfer, I guess that the thing that bothers you is the amount of jobs that gets generated, right? We have a related opened issue for that: https://github.com/kubeapps/kubeapps/issues/668

**Comment by kfirfer** [comment]
yes right
it's could be nice to also support parameter value of 0 on success

**Comment by fbalicchia** [comment]
Hi, instead of using limit WDYT about using `ttlSecondsAfterFinished `  in JobSpec definition ? https://kubernetes.io/docs/concepts/workloads/controllers/job/#clean-up-finished-jobs-automatically

**Comment by andresmgot** [comment]
That would be nice yes, would you be up to send a quick PR? :) You can find the code for the jobs definition at `cmd/apprepository-controller/controller.go`

**Comment by fbalicchia** [comment]
Ok I'll do it today thanks

**Comment by andresmgot** [comment]
This was closed by #2297

**Comment by lingsamuel** [comment]
The release page doesn't note that this feature requires TTLAfterFinished feature gate enabled in old cluster which the PR already mentioned it?

**Comment by absoludity** [comment]
I've updated the release note for that commit to include the requirement (the changelog for a release only shows the commit messages normally).

Also created #2718 to include this info in the code (and adjust the arg name in the doc string).

**Comment by lingsamuel** [comment]
I mean we need mention this obviously in the list of "major changes" in the release note, rather than hiding it in the changelog among many bump changes.

**Comment by lingsamuel** [comment]
Seriously, do users care about dependencies version changes? Those thousands of trivial bump changes hide the important changes.

**Comment by absoludity** [comment]
> Seriously, do users care about dependencies version changes (from dependabot)? Those thousands of trivial bump changes hide the important changes.

We've just been automating the generation based on the commit logs. Certainly would be better to separate out the security/version bumps from the actual changes.

> I mean we need mention this obviously in the list of "major changes" in the release note, rather than hiding it in the [changelog](https://github.com/kubeapps/kubeapps/releases/tag/v2.2.0) among many bump changes.

Happy to do so. Done.

**Comment by lingsamuel** [comment]
Thanks. I also think the fallback option should be mentioned: `--ttl-lifetime-afterfinished-job=""` for `apprepository-controller`.
