### ISSUE TITLE
[NEED HELP] Clarity UI - Websocket errors

### ISSUE THREAD

**Issue by rayanebel** [kubeapps/kubeapps#2049]
### Description:

Hi, 

I've installed kubeapps on an AKS cluster and I linked it with Azure AD to let our user to authenticate through Azure. On the **hex** UI everything seems to works but when I tried to enable the new UI _(clarity)_ with the feature flag provided, I have several websocket errors and after couple of minute the application disconnect me and I'm not able to connect again when I click again on `login with OIDC provider` I have a blank page and I need to wait some time to be able to login again.

Here you can see the message that I have on the Google Chrome console:

![kubeapps-wss-bug](https://user-images.githubusercontent.com/15887095/93750360-a44b9000-fbfb-11ea-9e56-3587fbcbd648.png)

Just for information, the user that I'm using to login is a cluster admin. I'm using NGINX as ingress controller and I have setup the following annotations:

```
nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
```

### Flags used

```
featureFlags:
  invalidateCache: true
  operators: false
  # ui is a WIP feature for the migration to Clarity design system.
  ui: clarity
```

Can someone help me on this issue ?

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.3", GitCommit:"8f832046e258e2cb800894579b1b3b50c2d83492", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

- Output of `helm list <kubeapps-release-name>`:

```
NAME                    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
kubeapps                blue-dev        1               2020-09-21 10:41:07.1137078 +0200 CEST  deployed        kubeapps-3.9.2          v1.11.3
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"b93345fce4b93610948e30f12c767f5dabd3d570", GitTreeState:"clean", BuildDate:"2020-08-24T20:09:56Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by andresmgot** [comment]
hi @rayanebel, thanks for reporting the issue.

The websocket errors you are seeing are harmless, in case Kubeapps is not able to reach the service using websockets, it falls back to do periodic sync calls to get updates.

The other issue you are reporting seems related to Azure AD. Does the problem persist? If you get constantly logged out, you may need to increase the time that your session is allowed (you should be able to configure that in Azure). In any case, this should not be affected by the UI used since the authentication process is handled by the `oauth2_proxy` container running along with the Kubeapps dashboard.

**Comment by absoludity** [comment]
To debug the authn only lasting a short time, if you can you temporarily deploy Kubeapps with `--set-authorization-header=true` added to the `authProxy.additionalFlags`, this will ensure that you can actually see the `id_token` being used as a client header (normally it's not sent to the browser as its not needed and better security for it not to be exposed). With that setting, if you look at a request in the browser inspector, you'll see the `Authorization` header will be set with a Bearer token. This is the `id_token` being used for authentication. If you copy the value of this token and base64 decode it (easiest way is to use MS's site at https://jwt.ms , depending on your security concerns), and look for the `exp` field: this is the number of seconds until that `id_token` expires. Knowing this value will narrow down where we debug :)

**Comment by rayanebel** [comment]
Hi @absoludity @andresmgot,

When I try to login it's working then after couple of minute, the ui disconnect by itself and return me to the login page.
I retrieved the bearer token return by Azure AD and used by kubeapps _(from my browser)_. When I decoded it, I found this property `"exp": 1600765916`. 

Now, when I am authenticated and that I stay on the home page _(context: default, namespace: all)_ everything seems to work and I'm not disconnected and I have this errors on my console.

```
manifest.json:1 GET https://kubeappstest.xxxxxxxxxxxxxxxxx.com/manifest.json 403 (Forbidden)
manifest.json:2 Manifest: Line: 2, column: 1, Syntax error.
xhr.js:178 GET https://kubeappstest.xxxxxxxxxxx.com/api/clusters/default/apis/operators.coreos.com/v1alpha1/namespaces/operators/clusterserviceversions 404 (Not Found)
```

Next, on one of my namespace I've a helm chart deployed (just the release present) but no workload is running (I've scale down all the deployment to 0). I saw that application on the UI and when I click on it I have the following errors and after that I'm automatically disconnected.

![kubeapps-bug-1](https://user-images.githubusercontent.com/15887095/93862017-be4fa600-fcc1-11ea-92c0-763424fcb085.png)

Next, I've also the `Kubernetes Service catalog` deployed _(not on the same namespace than kubeapps)_. When I click on it on the UI, I've also a couple of errors about some resources not found (like the previous one) then I'm automatically disconnected.

![kubeapps-bug-2](https://user-images.githubusercontent.com/15887095/93863922-6ebea980-fcc4-11ea-8ba3-c352b27d55db.png)

When I tried with a simple application (only one pod) it's working I don't have the 404 errors and I'm not diconnected and I can't login back I'm redirect to a blank page when the UI try to reach `/oauth/start` endpoint.

![kubeapps-bug-3](https://user-images.githubusercontent.com/15887095/93864188-cc52f600-fcc4-11ea-8804-09c5c554806c.png)

It seems that If I have only two-three 404 errors it's ok but if I have 10 errors the UI don't like it.

**Comment by andresmgot** [comment]
> When I tried with a simple application (only one pod) it's working I don't have the 404 errors and I'm not diconnected and I can't login back I'm redirect to a blank page when the UI try to reach /oauth/start endpoint.

If you are not "disconnected" how is it that you need to login back? Can you elaborate?

> It seems that If I have only two-three 404 errors it's ok but if I have 10 errors the UI don't like it.

I am still confused by this, Kubeappos won't logout unless it receive a 403 (Forbidden) error, can you check if you have any 403 response in the Network tab? 404s should not affect that.

> Just one question why do you use websockets ?

We use websockets to get updates in the resources of the application (for example, to know when the application is ready). The problem is that the svc-catalog chart has resources that contains an apiVersion that is not known (that is what causes the `undefined` in the URL of the websocket). We should fix that to avoid all those 404 anyway (regardless of the auth issue),

**Comment by andresmgot** [comment]
Reopening this as a bug
