### ISSUE TITLE
Remove sealed-secrets from Kubeapps

### ISSUE THREAD

**Issue by prydonius** [kubeapps/kubeapps#206]
Currently, Kubeapps includes sealed-secrets as part of the components it installs. However, it is not being surfaced in the Dashboard. We should decide whether it makes sense to include sealed-secrets in the UI or remove it from the Kubeapps distribution.

## Including it in the UI

- Include a page to view and create SealedSecret resources. We could have a form that allows you to build a SealedSecret resource by inputting key-value pairs (similar to setting Travis secret env vars), and after creating the UI could spit out the encrypted SealedSecret resource that you can then copy and paste into your git repo, etc.
- It feels a bit out of place from what Kubeapps currently offers, I'm not sure it makes sense to put SealedSecrets in the top-level navigation, we could put it under the "Configuration" submenu though

## Removing it

- We would simply remove it from the Kubeapps manifests and it would no longer be managed by the CLI
- This would prevent interfering with a cluster operator's installation of SealedSecrets (something we have run into with Bitnami clusters)

cc @arapulido @anguslees

**Comment by arapulido** [comment]
@prydonius Let's remove it :)
