### ISSUE TITLE
[FEATURE REQUEST] refresh repository by webhook 

### ISSUE THREAD

**Issue by kfirfer** [kubeapps/kubeapps#2062]
Hello

Per the conversion here: #2057  and the comment https://github.com/kubeapps/kubeapps/issues/1738#issuecomment-629087081
Would be nice to see webhook refresh mechanism of the repositories

When triggering the webhook, the related repository get refreshed

**Comment by antgamdia** [comment]
We are currently addressing this issue. Just for the sake of completeness, I'm adding here some info from the [Harbor documentation](https://goharbor.io/docs/2.0.0/working-with-projects/project-configuration/configure-webhooks/ ):

Harbor sends a POST request with the structure below to a given endpoint with a fixed authentication header. 

The idea for Kubeapps is that it will trigger a refresh once a successfully authenticated request hits the endpoint, regardless of the content of the hook payload.


Example of webhook configuration in Harbor:

![image](https://user-images.githubusercontent.com/11535726/98010957-980c4280-1df7-11eb-8052-32396431566e.png)

Example of webhook payload sent by Harbor:

```
{
	"type": "PUSH_ARTIFACT",
	"occur_at": 1586922308,
	"operator": "admin",
	"event_data": {
		"resources": [{
			"digest": "sha256:8a9e9863dbb6e10edb5adfe917c00da84e1700fa76e7ed02476aa6e6fb8ee0d8",
			"tag": "latest",
			"resource_url": "hub.harbor.com/test-webhook/debian:latest"
		}],
		"repository": {
			"date_created": 1586922308,
			"name": "debian",
			"namespace": "test-webhook",
			"repo_full_name": "test-webhook/debian",
			"repo_type": "private"
		}
	}
}
```
