### ISSUE TITLE
Cache application logo(s)

### ISSUE THREAD

**Issue by kfirfer** [kubeapps/kubeapps#2065]
Hello

I think the logo(s) of the application does not get cached in the browser
Im using kubeapps helm chart version 4.0.0
Image for reference:
![Selection_004](https://user-images.githubusercontent.com/7741545/94210724-342d5a80-fed8-11ea-9e36-a9eef6fc1ea8.png)

And this is my ingress configuration:
```
ingress:
  enabled: true
  hostname: kubeapps.tatzan.com
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "5"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/connection-proxy-header: "keep-alive"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
    nginx.ingress.kubernetes.io/limit-connections: "1000"
    nginx.ingress.kubernetes.io/limit-rps: "1000"
    nginx.ingress.kubernetes.io/limit-rate: "1000"
    nginx.ingress.kubernetes.io/enable-access-log: "true"
    nginx.ingress.kubernetes.io/enable-rewrite-log: "true"
    nginx.ingress.kubernetes.io/enable-opentracing: "false"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "server: saffer";
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "X-Frame-Options: DENY";
      more_set_headers "X-Xss-Protection: 1";
      proxy_set_header Connection "Upgrade";
  extraTls:
    - hosts:
        - "*.domain.co.il"
        - "*.domain.com"
```

Would like to know if it is related to configuration

Thanks !

**Comment by absoludity** [comment]
Note, your screenshot is of the catalog page, not the installed apps, but confirmed on the existing 3.9.2 chart with the new UI. If I switch from the Catalog tab to the App and back to Catalog, the images aren't re-fetched at all (good), but if I refresh the page (not a hard refresh), all the logo requests are 200s rather than 304 not modified.

I had thought with the old UI these would be 304s, but haven't re-checked.

**Comment by absoludity** [comment]
BTW, are you using the 4.0.0 chart from master? AFAICT, the 4.0.0-beta1 isn't yet published (but should be in the next day or so).

**Comment by kfirfer** [comment]
@absoludity 
Yes, im using the 4.0.0 chart from master

**Comment by kfirfer** [comment]
Couldnt wait for the release.. =D
