### ISSUE TITLE
2.0 release notes - out of date instructions

### ISSUE THREAD

**Issue by vrabbi** [kubeapps/kubeapps#2068]
### Description:

In the release notes for the 2.0 rc1 version of kubeapps the installation instructions are incorrect. They mention installation via helm 2 and helm 3 while the useHelm3 parameter is removed from the chart. This could cause issues for end users.

### Describe the results you expected:

The instructions should be updated and helm 3 should be the only option

**Comment by absoludity** [comment]
Thanks @vrabbi . Updated the template for the next beta and manually edited the current beta 1 release.

**Comment by andresmgot** [comment]
Thanks for catching this! The instructions are now updated.
