### ISSUE TITLE
Deployment - Default values in form

### ISSUE THREAD

**Issue by kfirfer** [kubeapps/kubeapps#2069]
Hello

The default values in the form(taken before in version 1.X from the values.yaml file) is missing in 2.0, it is intended ?

Image for reference:

![Selection_006](https://user-images.githubusercontent.com/7741545/94294144-0e4f9680-ff68-11ea-80bd-f871a5f0dbe6.png)

**Comment by kfirfer** [comment]
It is not that important at all, since I realized it is using the default values if it empty
closing

**Comment by absoludity** [comment]
No no, it is important, and is something @andresmgot noticed and fixed in #2061 :) Thanks.

**Comment by kfirfer** [comment]
@absoludity 
Ah alright

I thought it was designed to change
Thanks!
