### ISSUE TITLE
[Helm] Include repo URL in a Helm release

### ISSUE THREAD

**Issue by andresmgot** [kubeapps/kubeapps#2074]
Should we take the time now to design and implement the helm feature to include repo URL with a helm release? (mentioned recently by combitech folk as a pain point). See https://github.com/helm/helm/issues/6464#issuecomment-628746817

**Comment by absoludity** [comment]
Yeah, when I created that issue upstream it was to simply include the chart repo URI with the release info, but it's now quite a bit bigger (generic metadata associated with a release, of which the repo URI will be the first item). It'd be great to do and would simplify things for Kubeapps (and other UIs), I'm just not sure if it's worth investing here or in the opposite direction of moving the helm support in Kubeapps to a plugin to enable other formats. I think the latter will be a better use of time.
