### ISSUE TITLE
Chart new version indicator when select all namespaces

### ISSUE THREAD

**Issue by kfirfer** [kubeapps/kubeapps#2075]
Hello

Would be nice to see the indicator icon when new chart version will appear when clicking on "All namespaces"
Currently the indicator is been shown if you select specific namespace

![Selection_008](https://user-images.githubusercontent.com/7741545/94493214-afeb1800-01f4-11eb-82d0-9474cd8fd2ad.png)

**Comment by andresmgot** [comment]
Thanks for reporting, this seems like a bug
