### ISSUE TITLE
GetOperatorLogo is not cluster aware

### ISSUE THREAD

**Issue by absoludity** [kubeapps/kubeapps#2076]
### Description:

After installing the OLM on a k8s cluster which is not the cluster on which Kubeapps is installed, and then browsing to the list of operators to make available, none of the logos are rendered. All requests return a 500 as shown:

![operators-logo-500](https://user-images.githubusercontent.com/497518/94499163-50662a00-023f-11eb-936e-359ee645ce60.png)

It appears that the request is going through to the cluster on which Kubeapps is installed (which in this case, does not have the OLM installed, hence the api server is unable to provide the resource).

Note that if you deploy an operator, then the instance does show the icon so must be routed to the correct cluster. It's just on the available operators page.

### Steps to reproduce the issue:

1. Install Kubeapps in a multi-cluster setup
2. Install the OLM on the cluster on which Kubeapps is not installed
3. Browse the available operators

### Describe the results you received:

No logos appear

### Describe the results you expected:

Logos appear

**Comment by absoludity** [comment]
Confirmed that retrospectively installing the OLM also on the cluster on which Kubeapps is installed results in the logos displaying.

**Comment by andresmgot** [comment]
Adding the bug label

**Comment by andresmgot** [comment]
I've been checking this, the operator logo includes the cluster since https://github.com/kubeapps/kubeapps/pull/2025 (15 days ago). Maybe you are using an old image? I run this locally and it's using the namespace properly:

![Screenshot from 2020-09-29 16-44-23](https://user-images.githubusercontent.com/4025665/94574941-fcc20380-0273-11eb-8b04-0743af67a52f.png)

In any case, I found a couple of unrelated small issues so sending a PR for those.

**Comment by absoludity** [comment]
Sorry, I should have been clearer: the issues isn't the URL being fetched - it correctly has the cluster and namespace etc. as you found, but rather that the backend function `[GetOperatorLogo](https://github.com/kubeapps/kubeapps/blob/master/pkg/kube/kube_handler.go#L650)` is not cluster aware (nor any of the other items on that interface, but most are related to AppRepositories and so don't require cluster awareness right now).

**Comment by andresmgot** [comment]
ah, got it
