### ISSUE TITLE
Release "substantial-eyes" failed and has been uninstalled: YAML parse error on event-perception-front/templates/Deployment.yaml: error converting YAML to JSON: yaml: line 120: mapping values are not allowed in this context

### ISSUE THREAD

**Issue by gys1006** [kubeapps/kubeapps#2105]
### Steps to reproduce the issue:

1. [First Step]
2. [Second Step]
3. [and so on...]

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
(paste your output here)
```

- Output of `helm list -n <kubeapps-namespace> <kubeapps-release-name>`:

```
(paste your output here)
```

- Output of `kubectl version`:

```
(paste your output here)
```

**Comment by andresmgot** [comment]
Hi @gys1006,

It seems there is an issue in the YAML files of the chart you are trying to install. Can you post the piece of YAML around the line `120` of the conflicting file? That way we could verify if it's a chart or a parsing issue.
