### ISSUE TITLE
Annoying error message in the UI when adding per namespace app repository

### ISSUE THREAD

**Issue by bsctl** [kubeapps/kubeapps#2106]
# Description:
We configured the per namespace app repositories feature as per [docs](https://github.com/kubeapps/kubeapps/blob/master/docs/user/private-app-repository.md#per-namespace-app-repositories). When logging as regular user, with no cluster admin permissions, the UI reports an annoying message: `An error occurred while fetching repositories: apprepositories.kubeapps.com is forbidden: User "alice" cannot list resource "apprepositories" in API group "kubeapps.com" in the namespace "kubeapp-system"`. The `kubeapp-system` is the namespace where the cluster admin installed the `kubeapp` application and where the global repositories are installed. Please note the namespace selector in the up-right corner of the UI is set on one of the namespaces the user owns.

### Steps to reproduce the issue:

1. install `kubeapp` as cluster admin using the related Helm Chart with `allowNamespaceDiscovery: true`.
2. give the user `alice` the permissions to read/write `apprepositories` in her owned namespaces.

As alice user do the following:

```
$ kubectl -n oil-development auth can-i get apprepositories
yes
$ kubectl -n oil-development auth can-i create apprepositories
yes
```

3. login as `alice` user in the UI (via OIDC)
4. the namespace selector reports only namespaces owned by alice, i.e.: `gas-development, gas-marketing, oil-development, oil-kubeapp, oil-production`
5. select one of the above namespace and switch to the same context.
6. add an new app repository

### Describe the results you received:
The UI reports an annoying message: `An error occurred while fetching repositories: apprepositories.kubeapps.com is forbidden: User "alice" cannot list resource "apprepositories" in API group "kubeapps.com" in the namespace "kubeapp-system"`.  However, `alice` user can create a new app repository in the current namespace.

### Describe the results you expected:
The UI should not warn about the permissions related to the namespace where the kubeapp is installed when the namespace selector is set on another namespace.

### Additional information you deem important (e.g. issue happens only occasionally):
Always in our setup

### Version of Helm, Kubeapps and Kubernetes:

```
helm list
NAME                    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION        
kubeapp                kubeapp-system      1               2020-10-12 16:26:41.668571 +0200 CEST   deployed        kubeapps-4.0.3  v2.0.0-beta.2

helm version
version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.7"}

kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

```

**Comment by andresmgot** [comment]
Hi @bsctl,

Thank you for reporting the issue and all the details. We are aware of the issue, the problem is that the application is trying to retrieve global repositories when visiting that page.

We have already fixed it in https://github.com/kubeapps/kubeapps/pull/2099 and the fix will be available in the next release (which will be available in the next few days).

**Comment by absoludity** [comment]
This should no longer be relevant with the fix mentioned. Please re-open if you find otherwise.
