### ISSUE TITLE
The UI welcomes regular users with an annoying message: "unable to list apps .. in all namespaces"

### ISSUE THREAD

**Issue by bsctl** [kubeapps/kubeapps#2107]
### Description:
Logging to the UI as a regular user with no cluster admin permissions, the namespace selector on the up-right corner is positioned to `all-namespaces`. So the UI welcomes the new user with an annoying message : `Unable to list apps: Forbidden error, missing permissions: apiGroup: "", resource: "secrets", action: "list", in all namespaces`.

### Steps to reproduce the issue:

We installed with `allowNamespaceDiscovery: true` so regular users can only see their owned namespaces. 

### Describe the results you received:
The UI welcomes the new user with an annoying message : `Unable to list apps: Forbidden error, missing permissions: apiGroup: "", resource: "secrets", action: "list", in all namespaces`.

### Describe the results you expected:
It would be better to position the namespace selector on the first namespace of the owned namespace list so the UI does not report the error above. Another option would be to filter the secrets only on owned namespaces, ref. #1471 
In case there are no namespaces owned by the user, the selector can be positioned on a `_none_` value.

### Additional information you deem important (e.g. issue happens only occasionally):
always on our setup

### Version of Helm, Kubeapps and Kubernetes:

```
helm list
NAME NAMESPACE REVISION UPDATED STATUS CHART APP VERSION
kubeapp kubeapp-system 1 2020-10-12 16:26:41.668571 +0200 CEST deployed kubeapps-4.0.3 v2.0.0-beta.2

helm version
version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.7"}

kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by andresmgot** [comment]
Yes, this is one of the items listed in the refactor of the UX for the namespace selector:

https://github.com/kubeapps/kubeapps/issues/2018

We can probably include the fix to select the first namespace available (rather than all namespaces) by default for 2.0 since it's an easy fix.
