### ISSUE TITLE
App repos installed in a namespace are not visible in other namespaces owned by the same user

### ISSUE THREAD

**Issue by bsctl** [kubeapps/kubeapps#2108]
### Description:
App repos installed in a namespace are not visible in other namespaces owned by the same user. 

### Steps to reproduce the issue:
We configured the per namespace app repositories feature as per documentation. Kubeapp is installed with `allowNamespaceDiscovery: true` , so regular users with no cluster admin permissions can only list their owned namespaces. Give a user, eg. `alice` the permissions to read/write `apprepositories` in her owned namespaces.

As `alice` user do the following:

```
$ kubectl -n oil-development auth can-i get apprepositories
yes
$ kubectl -n oil-development auth can-i create apprepositories
yes
$ kubectl -n oil-production auth can-i get apprepositories
yes
$ kubectl -n oil-production auth can-i create apprepositories
yes
```

### Describe the results you received:

Login as alice user in the UI (via OIDC)

As `alice` add an `apprepository` into namespace `oil-production`: the repo is visible when the namespace selector is on the `oil-production` but it is not visible when the the namespace selector is on the `oil-development`. However the repos installed by the cluster admin in the `kubeapp-system` namespaces are always visible in all namespaces.

### Describe the results you expected:
Alice user has the permission to read/write `apprepositories` in both the namespaces `oil-production` and `oil-development`. The expected is that alice can see `apprepositories` deployed in all her namespaces.

### Version of Helm, Kubeapps and Kubernetes:

```
helm list
NAME NAMESPACE REVISION UPDATED STATUS CHART APP VERSION
kubeapp kubeapp-system 1 2020-10-12 16:26:41.668571 +0200 CEST deployed kubeapps-4.0.3 v2.0.0-beta.2

helm version
version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.7"}

kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by andresmgot** [comment]
Hi @bsctl,

That's expected for namespaced resources. Namespaced app repositories are only available in the namespace they are installed in. This works the same way if `alice` creates a Kubernetes `service` in the namespace `oil-development`, it won't be available in `oil-production` even if the user has permissions to access both. You will need to either copy the app repository to the other namespace or make it global if you want to have it available for all namespaces. 

We have an open issue for helping copying app repositories to other namespaces (which I believe will help your use case) https://github.com/kubeapps/kubeapps/issues/1701 but we have not included it in the roadmap yet.

Let me close this issue, if you have further comments please add them in #1701 so we can have the conversation in just one place. Thank you!
