### ISSUE TITLE
An error occurred: Object(...)(...).split is not a function 

### ISSUE THREAD

**Issue by sfxworks** [kubeapps/kubeapps#2114]
### Description:
Just installed OLM. Initially, kubeapps was working with it just fine. I went to browse an operator. Then hit back in the browser. I end up with this in the console logs and on the screen.

### Steps to reproduce the issue:

1. Install kubeapps
2. Install OLM as described https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/install/install.md
3. Go to the operators tab
4. Browse something?
5. Attempt to go back 

### Describe the results you received:

```
An error occurred: Object(...)(...).split is not a function
```
Appears in yellow. 

### Describe the results you expected:
Lists operators available to install.

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

- Output of `helm list -n <kubeapps-namespace> <kubeapps-release-name>`:

```
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
kubeapps        kubeapps        1               2020-10-14 02:10:25.7026936 -0400 EDT   deployed        kubeapps-4.0.3  v2.0.0-beta.2
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by andresmgot** [comment]
Hi @sfxworks,

Indeed that's a bug, thanks for reporting it and all the details! I noticed it as well a few days ago and fixed it as part of https://github.com/kubeapps/kubeapps/pull/2091

We are preparing a new release that will be available in the next few days, the next version will contain the fix. Let me close this issue, let us know if you notice anything else.
