### ISSUE TITLE
An error occurred: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by sfxworks** [kubeapps/kubeapps#2120]
### Description:

`An error occurred: Cannot read property 'name' of undefined` during operator object install

### Steps to reproduce the issue:

1. Install kubeapps
2. Choose an operator, like etcd
3. change the name (or possibly use the default name but I changed the name)
4. deploy it
5. See `An error occurred: Cannot read property 'name' of undefined`

### Describe the results you received:

`An error occurred: Cannot read property 'name' of undefined`
### Describe the results you expected:
Show information of deployment described in the documentation 

### Version of Helm, Kubeapps and Kubernetes:

```
helm version
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}

helm list -n kubeapps
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
kubeapps        kubeapps        1               2020-10-21 12:30:32.2962579 -0400 EDT   deployed        kubeapps-4.0.4  v2.0.0

kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by absoludity** [comment]
I tried to reproduce this in a demo environment and got a different (less descriptive) error. I was able to deploy etcd, but when the dashboard tries to display the resources of the deployment, I'm seeing 

![a-t-undefined](https://user-images.githubusercontent.com/497518/96807399-28df3780-1462-11eb-9628-0b18a041f4bd.png)

From the trace, it looks like it could be https://github.com/kubeapps/kubeapps/blob/master/dashboard/src/components/AppView/ResourceTable/ResourceTable.tsx#L91

Need to reproduce locally to investigate further.

**Comment by andresmgot** [comment]
Right, I am able to reproduce it as well @sfxworks. Let me send a PR for fixing it.

**Comment by sfxworks** [comment]
Thanks everyone

> I was able to deploy etcd, but when the dashboard tries to display the resources of the deployment, I'm seeing

Sorry I did forget to clarify that I received this error when attempting to display resources produced by the operator. This looks about right.
