### ISSUE TITLE
Offline Install: AppRepo sync jobs do not receive required imagePullSecrets

### ISSUE THREAD

**Issue by absoludity** [kubeapps/kubeapps#2144]
## Description:

In #1751 support was added to allow offline installation of Kubeapps. If that offline installation is from an internal mirror, the `global.imageRegistry=REPO_URL` option can be set [as per the docs](https://github.com/kubeapps/kubeapps/blob/master/docs/user/offline-installation.md#4-install-kubeapps), which works. If the internal mirror also requires pull secrets, the additional `global.imagePullSecrets=SECRET_NAME` option needs to be set, which also works for the initial installation, but this value is *not* passed through to the app repository controller and so is not used for the cronjobs/syncjobs that try to pull the related kubeapps image.

So the kubeapps installation works, but sync jobs go into image pull backoff:

![kubeapps](https://user-images.githubusercontent.com/497518/98175825-72904d80-1f4b-11eb-91b9-da216c3c7881.png)

This was originally reported on [#kubeapps in kubernetes slack](https://kubernetes.slack.com/archives/C9D3TSUG4/p1604511793033400).

### Steps to reproduce the issue:

1. Setup an internal docker registry with kubeapps images mirrored, [as per the docs](https://github.com/kubeapps/kubeapps/blob/master/docs/user/offline-installation.md#4-install-kubeapps).
2. Ensure the internal docker registry is private, requiring docker credentials
3. Create a secret in your `kubeapps` namespace with the docker credentials
4. Install kubeapps setting both the `global.imageRegistry` and `global.imagePullSecrets` options

### Describe the results you received:

Kubeapps installs fine but sync jobs fail with ImagePullBackoff

### Describe the results you expected:

Kubeapps installs fine and sync jobs run without issue.

**Comment by absoludity** [comment]
Until this is fixed, you should be able to work around this with `kubectl -n kubeapps edit cronjob CRONJOB_NAME`  (list the cronjobs to get the actual name), and add the imagePullSecrets to the pod spec manually. Once saved, that should ensure subsequent jobs are run with the given image pull secret (which you can verify). That workaround should only be required once per kubeapps app repository.

**Comment by antgamdia** [comment]
I'm able to reproduce the issue. Here are the detailed steps for setting up the environment for future reference:
> For the sake of simplicity, I'll use the demo instance of Habor; it becomes reset periodically, but it's up enough time to test this out. As per a k8s cluster, I'll use Kind.

1.  Go to demo.goharbor.io, create an account, create a project and set it as private. We will get a URL:
```
https://demo.goharbor.io/my-project/
```
2. To simulate an air-gapped network scenario, we first need to download each artifact and upload them to our 'local private registry'

2.1 Download Kubeapps and update deps:
```
helm pull --untar https://charts.bitnami.com/bitnami/kubeapps-4.0.4.tgz
helm dep update ./kubeapps
```
  2.2 Pull the images that Kubeapps will need:
```
docker pull bitnami/kubeapps-apprepository-controller:2.0.0-scratch-r2
docker pull bitnami/kubeapps-asset-syncer:2.0.0-scratch-r2
docker pull bitnami/kubeapps-assetsvc:2.0.0-scratch-r2
docker pull bitnami/kubeapps-dashboard:2.0.0-debian-10-r5 
docker pull bitnami/kubeapps-kubeops:2.0.0-scratch-r2
docker pull bitnami/kubectl:1.18.9-debian-10-r5
docker pull bitnami/nginx:1.19.2-debian-10-r32 
docker pull bitnami/oauth2-proxy:6.1.1-debian-10-r12
docker pull bitnami/postgresql:11.9.0-debian-10-r73
```
  2.3 Re-tag and push to our 'local private registry'. This should be the last point where we need internet access.
```
docker tag bitnami/kubeapps-apprepository-controller:2.0.0-scratch-r2 demo.goharbor.io/my-project/bitnami/kubeapps-apprepository-controller:2.0.0-scratch-r2
docker tag bitnami/kubeapps-asset-syncer:2.0.0-scratch-r2 demo.goharbor.io/my-project/bitnami/kubeapps-asset-syncer:2.0.0-scratch-r2
docker tag bitnami/kubeapps-assetsvc:2.0.0-scratch-r2 demo.goharbor.io/my-project/bitnami/kubeapps-assetsvc:2.0.0-scratch-r2
docker tag bitnami/kubeapps-dashboard:2.0.0-debian-10-r5 demo.goharbor.io/my-project/bitnami/kubeapps-dashboard:2.0.0-debian-10-r5
docker tag bitnami/kubeapps-kubeops:2.0.0-scratch-r2 demo.goharbor.io/my-project/bitnami/kubeapps-kubeops:2.0.0-scratch-r2
docker tag bitnami/kubectl:1.18.9-debian-10-r5 demo.goharbor.io/my-project/bitnami/kubectl:1.18.9-debian-10-r5
docker tag bitnami/nginx:1.19.2-debian-10-r32 demo.goharbor.io/my-project/bitnami/nginx:1.19.2-debian-10-r32
docker tag bitnami/oauth2-proxy:6.1.1-debian-10-r12 demo.goharbor.io/my-project/bitnami/oauth2-proxy:6.1.1-debian-10-r12
docker tag bitnami/postgresql:11.9.0-debian-10-r73 demo.goharbor.io/my-project/bitnami/postgresql:11.9.0-debian-10-r73

docker push demo.goharbor.io/my-project/bitnami/kubeapps-apprepository-controller:2.0.0-scratch-r2
docker push demo.goharbor.io/my-project/bitnami/kubeapps-asset-syncer:2.0.0-scratch-r2
docker push demo.goharbor.io/my-project/bitnami/kubeapps-assetsvc:2.0.0-scratch-r2
docker push demo.goharbor.io/my-project/bitnami/kubeapps-dashboard:2.0.0-debian-10-r5
docker push demo.goharbor.io/my-project/bitnami/kubeapps-kubeops:2.0.0-scratch-r2
docker push demo.goharbor.io/my-project/bitnami/kubectl:1.18.9-debian-10-r5
docker push demo.goharbor.io/my-project/bitnami/nginx:1.19.2-debian-10-r32
docker push demo.goharbor.io/my-project/bitnami/oauth2-proxy:6.1.1-debian-10-r12
docker push demo.goharbor.io/my-project/bitnami/postgresql:11.9.0-debian-10-r73
``` 
3. Create an ImagePullSecret (refer to the k8s docs for more info):
``` 
kubectl create secret docker-registry harbor --docker-server=demo.goharbor.io --docker-username=test --docker-password=Test12345 --docker-email=test@test.test
``` 
4. Install Kubeapps from the downloaded artifact in 1. and let it use the registry (`global.imageRegistry`) and the imagePullSecret (`global.imagePullSecrets[0]`)
```
helm install kubeapps ./kubeapps --set global.imageRegistry=demo.goharbor.io/docker --set global.imagePullSecrets[0]=harbor
``` 

Currently, the controller of the jobs is not passing any ImagePullSecret through its 
 jobs (https://github.com/kubeapps/kubeapps/blob/master/cmd/apprepository-controller/controller.go#L478)
The fix should be straightforward: make it to accept ImagePullSecrets and pass them to its jobs.

I'm addressing this issue and will send a PR.

**Comment by absoludity** [comment]
Thanks for recording the detailed setup!
