### ISSUE TITLE
Bump CRD from v1beta1 to v1 (k8s 1.16+)

### ISSUE THREAD

**Issue by antgamdia** [kubeapps/kubeapps#2169]
### Description:

In k8s 1.16+ a deprecation warning of `apiextensions.k8s.io/v1beta1` in favor of `apiextensions.k8s.io/v1` appeared. In 1.22+ it will be fully deprecated.

Note that this change will drop support for <=1.15 versions.

### Steps to reproduce the issue:

Performing `helm install kubeapps` in a 1.16+ cluster

### Describe the results you received:

A deprecation warning is being thrown.

### Describe the results you expected:

No deprecation warning.

### Additional information you deem important (e.g. issue happens only occasionally):

If we bump up the version, k8s clusters prior to 1.15 won't be able to install Kubeapps.
Besides, 1.22+ users aren't able to install it.

### Version of Helm, Kubeapps and Kubernetes:

The warning is being thrown in k8s versions 1.16, 1.17, 1.18, 1.19 (and future 1.20, 1.21).

**Comment by antgamdia** [comment]
Just for the record, this issue is a follow up of the PRs #2164 and #2168.

Also, note that simply change `v1beta1` -> `v1` won't work, as it will throw the following error: (thanks @andresmgot for pointing this out!)

```
Error: failed to install CRD crds/apprepository-crd.yaml: CustomResourceDefinition.apiextensions.k8s.io "apprepositories.kubeapps.com" is invalid: 
[spec.versions: Invalid value: []apiextensions.CustomResourceDefinitionVersion(nil): must have exactly one version marked as storage version, status.storedVersions: Invalid value: []string(nil): must have at least one stored version]
```

https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/

**Comment by antgamdia** [comment]
![image](https://user-images.githubusercontent.com/11535726/99956029-9d6d0500-2d85-11eb-95c4-b336f0679227.png)

Regardless of this lifecycle, we currently plan to support the same versions as GKE: https://cloud.google.com/kubernetes-engine/docs/release-notes#stable-channel

**Comment by antgamdia** [comment]
Just for the record, Ingress objects should also be bumped up from: `extensions/v1beta1` to `networking.k8s.io/v1`. This change is available from 1.14, so there should not be any problem in migrating.
More info at https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

Note that there is a change in how ports are defined:

```
serviceName: kubeapps 
servicePort: 80
```

```
 port:
  name: kubeapps
  number: 80
```

**Comment by antgamdia** [comment]
See #2445

**Comment by antgamdia** [comment]
Requesting this change as part of the https://github.com/bitnami/charts/pull/6301#pullrequestreview-656429423

**Comment by absoludity** [comment]
1.22 is now one month away: https://www.kubernetes.dev/resources/release/ . Re-prioritising accordingly.

**Comment by dlaloue-vmware** [comment]
i installed kubeapps today after updtaing the bitnami repo on my machine, and the change is already available.
should this issue be closed then?
