### ISSUE TITLE
Helm stable repo problem

### ISSUE THREAD

**Issue by zmmdv** [kubeapps/kubeapps#2170]
Hello everyone. When i'm putting additional repos inside values file. And syncing pod starts he fails with this errors.
Can someone help? How to avoid errors of deprecated charts?
Using helm 3.4.0
Latest version of kubeapps chart.
Kubernetes 1.17.13
Docker 19.03.13
Values file changes :
  ## Initial chart repositories to configure
  ##
  initialRepos:
    - name: bitnami
      url: https://charts.bitnami.com/bitnami                                                        WORKING
    - name: stable
      url: https://charts.helm.sh/stable                                                                 NOT WORKING
    - name: prometheus-community
      url: https://prometheus-community.github.io/helm-charts                           WORKING
    - name: helm-stable
      url: https://kubernetes-charts.storage.googleapis.com                               NOT WORKING

time="2020-11-18T07:25:24Z" level=info msg="skipping deprecated chart" name=kube-state-metrics                                                                                             │
│ time="2020-11-18T07:25:24Z" level=info msg="skipping deprecated chart" name=mysqldump                                                                                                      │
│ time="2020-11-18T07:25:24Z" level=info msg="skipping deprecated chart" name=node-problem-detector                                                                                          │
│ time="2020-11-18T07:25:24Z" level=info msg="skipping deprecated chart" name=postgresql                                                                                                     │
│ time="2020-11-18T07:25:24Z" level=info msg="skipping deprecated chart" name=bookstack                                                                                                      │
│ time="2020-11-18T07:25:24Z" level=info msg="skipping deprecated chart" name=drupal                                                                                                         │
│ time="2020-11-18T07:25:24Z" level=info msg="skipping deprecated chart" name=searchlight                                                                                                    │
│ time="2020-11-18T07:25:24Z" level=info msg="skipping deprecated chart" name=verdaccio                                                                                                      │
│ time="2020-11-18T07:25:24Z" level=info msg="skipping deprecated chart" name=elastic-stack                                                                                                  │
│ time="2020-11-18T07:25:24Z" level=info msg="skipping deprecated chart" name=nats                                                                                                           │
│ time="2020-11-18T07:25:24Z" level=info msg="skipping deprecated chart" name=sealed-secrets                                                                                                 │
│ time="2020-11-18T07:25:24Z" level=info msg="skipping deprecated chart" name=cert-manager                                                                                                   │
│ time="2020-11-18T07:25:24Z" level=info msg="skipping deprecated chart" name=eventrouter                                                                                                    │
│ time="2020-11-18T07:25:24Z" level=info msg="skipping deprecated chart" name=gangway                                                                                                        │
│ time="2020-11-18T07:25:24Z" level=info msg="skipping deprecated chart" name=gcloud-endpoints                                                                                               │
│ time="2020-11-18T07:25:24Z" level=info msg="skipping deprecated chart" name=kibana                                                                                                         │
│ time="2020-11-18T07:25:24Z" level=info msg="skipping deprecated chart" name=nginx-lego                                                                                                     │
│ time="2020-11-18T07:25:24Z" level=info msg="skipping deprecated chart" name=bitcoind                                                                                                       │
│ time="2020-11-18T07:25:24Z" level=info msg="skipping deprecated chart" name=cockroachdb                                                                                                    │
│ time="2020-11-18T07:25:24Z" level=info msg="skipping deprecated chart" name=g2                                                                                                             │
│ time="2020-11-18T07:25:24Z" level=info msg="skipping deprecated chart" name=kapacitor                                                                                                      │
│ time="2020-11-18T07:25:24Z" level=info msg="skipping deprecated chart" name=kiam                                                                                                           │
│ time="2020-11-18T07:25:24Z" level=info msg="skipping deprecated chart" name=prometheus-cloudwatch-exporter                                                                                 │
│ time="2020-11-18T07:25:24Z" level=info msg="skipping deprecated chart" name=datadog                                                                                                        │
│ time="2020-11-18T07:25:24Z" level=info msg="skipping deprecated chart" name=kube-ops-view                                                                                                  │
│ time="2020-11-18T07:25:24Z" level=info msg="skipping deprecated chart" name=sonatype-nexus                                                                                                 │
│ time="2020-11-18T07:25:24Z" level=info msg="skipping deprecated chart" name=gce-ingress                                                                                                    │
│ time="2020-11-18T07:25:24Z" level=info msg="skipping deprecated chart" name=k8s-spot-rescheduler                                                                                           │
│ time="2020-11-18T07:25:24Z" level=info msg="skipping deprecated chart" name=logstash                                                                                                       │
│ time="2020-11-18T07:25:24Z" level=info msg="skipping deprecated chart" name=prometheus-couchdb-exporter

**Comment by antgamdia** [comment]
The [Helm Stable](https://charts.helm.sh/stable ) repo from Nov 13th 2020 is considered as [deprecated](https://github.com/helm/charts/blob/master/README.md#deprecation-timeline):

`At 1 year, support for this project will formally end, at which point the stable and incubator chart repos will be marked obsolete. At that time these chart repos will likely be garbage collected and no longer available. This git repository will remain as an archive.`

Perhaps some charts from https://kubernetes-charts.storage.googleapis.com have also been marked as deprecated.

The default behavior is to skip the deprecated charts when syncing a new repository.

**Comment by andresmgot** [comment]
Indeed, the `stable` repository has been completely deprecated and their artifacts are now obsolete (which means that those artifacts are potentially insecure).

Any chart marked as deprecated won't be shown in Kubeapps. If there is a chart that you need to use (and it's not part of a different repository) you can ask to the chart maintainer to provide an alternative. Note that you can search for the current repositories either in the https://artifacthub.io/ or in https://hub.kubeapps.com/.

Let me close this issue since it's not related to Kubeapps, please let us know if you still find any issue.
