### ISSUE TITLE
icons not available in an air-gap deployment

### ISSUE THREAD

**Issue by dealboy** [kubeapps/kubeapps#2196]
Hi, 

I have deployed kubeapps (using helm chart v5.0.0 ) on my internal (air-gapped) k8s cluster.
I configure the bitnami-charts via an internal repository mirror.  All charts are available and can be deployed! 
 
The only missing part are the chart icons.
The apprepo-kubeapps-sync process cannot get the chart icons because it tries to access https://bitnami.com/assets/xyz

is there a way to configure that? 

( I found https://github.com/kubeapps/kubeapps/blob/master/docs/user/private-app-repository.md but is for custom internal repo)

thanks
yannis

**Comment by andresmgot** [comment]
Hi,

Unfortunately, there is not. Note that Kubeapps just retrieves the repository `index.yaml` and get the links to the logos from there. The only thing that you could do is to mirror the logos as well and modify the links to point to your air-gapped environment:

```yaml
    home: https://github.com/bitnami/charts/tree/master/bitnami/airflow
    icon: https://bitnami.com/assets/stacks/airflow/img/airflow-stack-110x117.png
```

**Comment by dealboy** [comment]
> Hi,
> 
> Unfortunately, there is not. Note that Kubeapps just retrieves the repository `index.yaml` and get the links to the logos from there. The only thing that you could do is to mirror the logos as well and modify the links to point to your air-gapped environment:
> 
> ```yaml
>     home: https://github.com/bitnami/charts/tree/master/bitnami/airflow
>     icon: https://bitnami.com/assets/stacks/airflow/img/airflow-stack-110x117.png
> ```

thanks, I will give it a try
