### ISSUE TITLE
Make prepending namespace to release name optional

### ISSUE THREAD

**Issue by bruce2409** [kubeapps/kubeapps#220]
At the moment, I'm trying to keep deployments spread out per-namespace. For example, wordpress deploys go into the wordpress namespace. 

However because release names have the chart name prepended you end up with a long and a bit redundant deployment name/service DNS name (ie wordpress-example-wordpress.wordpress.svc.cluster.local)

If there were some sort of way to have it be optional that would be great. Perhaps via some sort of option you can set in the spec in the API calls?

**Comment by andresmgot** [comment]
waiting for review at #330
