### ISSUE TITLE
Java like annotations in values.yaml to generate values.schema.json

### ISSUE THREAD

**Issue by stephanDesj** [kubeapps/kubeapps#2203]
It will be very helpful to have a annotation like functionality to use inside values.yaml.

i.e in values.yaml
#@title: "an application title"
#@description: "a descriptions"
#@form: true
app:
  somevalues: "asdasd"

in values.schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "properties": {
        "app": {
            "title" : "an application title",
            "description" : "a descriptions",
            "form": true,
            "type": "object"
...
}

**Comment by antgamdia** [comment]
That's interesting. What would be your use case? How having these annotations will be useful for you?
Do you mean generating a json schema by means of an annotated yaml?

**Comment by andresmgot** [comment]
> What would be your use case? How having these annotations will be useful for you?
> Do you mean generating a json schema by means of an annotated yaml?

I'd assume so. The thing is that having a explicit json schema allows to run a validation before the chart gets installed (helm does that).
