### ISSUE TITLE
The update of the charts warehouse failed

### ISSUE THREAD

**Issue by NadamHL** [kubeapps/kubeapps#2204]
Environment.：
kubeapps：
NAME    	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART         	APP VERSION
kubeapps	kubeapps 	1       	2020-08-28 09:03:57.911802931 +0800 CST	deployed	kubeapps-3.9.1	v1.11.2  

kubernetes：
1.15.12

kernel：
4.4.198

现象：
View through kubeapps' web interface
![image](https://user-images.githubusercontent.com/39847290/101112562-8e554500-3618-11eb-9747-91fd7b818770.png)

View from the helm command line
![image](https://user-images.githubusercontent.com/39847290/101112578-98774380-3618-11eb-9c62-dd922eef0992.png)

result
The update of the charts warehouse failed

**Comment by antgamdia** [comment]
Perhaps there is a sort of problem when fetching the latest version of the chart. Have you tried refreshing the repository in Kubeapps manually?
In the lastest versions, you have a manual refresh button:
![image](https://user-images.githubusercontent.com/11535726/101196152-a94ba780-3660-11eb-816a-0ddad0751237.png)

You can also inspect the logs of the cronjob in charge of syncing the repo information. To list all the jobs executed by Kubeapps exec: `kubectl get jobs -n kubeapps`

**Comment by andresmgot** [comment]
This seems like an issue with the chart itself. I'd recommend to contact the chart developers. If you still think this is an issue related to Kubeapps, please let us know.
