### ISSUE TITLE
kubeapps returns 401 using oidc, after a [AuthSuccess] 

### ISSUE THREAD

**Issue by dealboy** [kubeapps/kubeapps#2207]
### Description:

kubeapps using OIDC and gitlab ( https://docs.gitlab.com/ee/integration/oauth_provider.html ). 

authProxy  supports that setup https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/oauth_provider#gitlab-auth-provider 

Although I get authenticated by gitlab, and authProxy  reports [AuthSuccess]  when redirected to /api/clusters/default/, kubeapps gives me a **401** 

```
192.168.1.5:47316 - - [2020/12/07 16:43:26] kubeapps.rancher.development.int GET / "/" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0" 304 0 0.001
192.168.1.5:47138 - - [2020/12/07 16:43:26] kubeapps.rancher.development.int GET / "/static/js/main.6a34618e.chunk.js" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0" 304 0 0.002
192.168.1.5:47316 - - [2020/12/07 16:43:26] kubeapps.rancher.development.int GET / "/static/css/main.f333eac1.chunk.css" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0" 200 161557 0.052
192.168.1.5:47138 - - [2020/12/07 16:43:26] kubeapps.rancher.development.int GET / "/static/media/logo.1ff453c0.svg" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0" 304 0 0.001
192.168.1.5:47138 - - [2020/12/07 16:43:28] kubeapps.rancher.development.int GET - "/oauth2/start" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0" 302 353 0.000
192.168.1.5:47138 - user01@development.int [2020/12/07 16:43:29] kubeapps.rancher.development.int GET / "/api/clusters/default/" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0" 401 165 0.010
192.168.1.5:47138 - user01@development.int [2020/12/07 16:43:46] [AuthSuccess] Authenticated via OAuth2: Session{email:user01@development.int user:user01_ad PreferredUsername: token:true id_token:true created:2020-12-07 16:43:46.423236723 +0000 UTC m=+71.754491786 expires:2020-12-07 16:45:46 +0000 UTC refresh_token:true}
192.168.1.5:47138 - - [2020/12/07 16:43:46] kubeapps.rancher.development.int GET - "/oauth2/callback?code=XXXXXXXXb6cd85f144f0bbd960a194500ba13de4cd8cd756cc788583d4795db&state=AAAAAAAAAAf9946a6484db46a2a51770%3A%2F" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0" 302 24 0.230
192.168.1.5:47138 - user01@development.int [2020/12/07 16:43:46] kubeapps.rancher.development.int GET / "/api/clusters/default/" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0" 401 165 0.007
```

### Steps to reproduce the issue:

1. Enable authProxy and configure it to use gitlab 
2. Deploy and try to login
3. Get redirected to default kubeapps auth page

### Describe the results you received:

authProxy proxy returns in the logs [AuthSuccess]

### Describe the results you expected:

the user to be authenticated and have access to  /api/clusters/default/

### Additional information you deem important (e.g. issue happens only occasionally):

The issue happens always

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

- Output of `helm list -n <kubeapps-namespace> <kubeapps-release-name>`:

```
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION

kubeapps        kubeapps        8               2020-12-07 17:42:29.883088126 +0100 CET deployed        kubeapps-5.0.0  2.0.1      
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by absoludity** [comment]
Hi @dealboy . Kubeapps simply tries to access the k8s API server with the `id_token` it is passed, but there are a few common misconfigurations which people sometimes find. I've just created an issue for us (kubeapps team) to document steps to debug this situation. I've included most of the details there at https://github.com/kubeapps/kubeapps/issues/2208 . Can you please paste here the output of the command showing the `oidc` args for your k8s api server? You may also want to try getting the token and decoding it, as described there. Let me know what you find and I'll then be able to dig deeper. Thanks!

**Comment by absoludity** [comment]
(also whether your RBAC for the above user is for `user01@development.int` or `oidc:user01@development.int` ).

**Comment by davidkarlsen** [comment]
I see the same with openshift. Openshift is, well, openshift, so k8s trainwrecked by RH. I can't see that it declares any OIDC parms for the api-server, yet they do use OIDC and integrate very well with IDPs. Do you have any openshift users?

**Comment by absoludity** [comment]
> I see the same with openshift. Openshift is, well, openshift, so k8s trainwrecked by RH. I can't see that it declares any OIDC parms for the api-server, yet they do use OIDC and integrate very well with IDPs.

Yep, so if the api-server is running without the oidc params, it'll be using a webhook auth or similar to verify any credential that comes with the request. From the issues people have raised, I'm assuming it doesn't accept the `id_token` which we pass by default (as this works with the oidc setup). *BUT* it could be as simple as configuring Kubeapps to send the access token instead (which we already do for the GKE environment). You can read more at Example 3 in our [oidc docs](https://github.com/kubeapps/kubeapps/blob/master/docs/user/using-an-OIDC-provider.md#deploying-a-proxy-to-access-kubeapps) but just involves setting the `frontend.proxypassAccessTokenAsBearer=true` chart option.

But ideally you'd want to be able to debug the requests to the API server without Kubeapps being involved, so getting a hold of the access token which has been granted, then checking with curl. If that works, then it should be as simple as the above option. If not, then I'd be checking RBAC associated with the token's user (which I'm sure you've already done).

> Do you have any openshift users?

Not officially, but people certainly are trying. I'd be keen to add documentation once it's sorted, but as above, my guess is it's requiring the access token as the authorization bearer. If I get some time I'd love to take a look, but hard atm.

**Comment by davidkarlsen** [comment]
Tried the example 3 approach, still get:
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}
```
on url: https://kubeapps..../api/clusters/default/

config:
```
values:
        useHelm3: true
        frontend:
            proxypassAccessTokenAsBearer: true
        authProxy:
            provider: oidc
            enabled: true
            clientID: XXX
            clientSecret: XXXX
            cookieSecret: XXX
            additionalFlags:
            - --oidc-issuer-url=https://sts.windows.net/XXX
        ingress:
            enabled: true
            hostname: kubeapps.XXXX
            extraTls:
            -   hosts:
                - kubeapps.XXXX
                secretName: kubeapps-tls
        securityContext:
            enabled: true
```

**Comment by absoludity** [comment]
```
>             additionalFlags:
>             - --oidc-issuer-url=https://sts.windows.net/XXX
```
Sorry, weren't you asking about OpenShift David? I'm confused by the above which looks like this is Windows AD. There's an existing issue for the new managed Active Directory which was resolved by MS upstream by adapting oauth2-proxy, but we haven't yet got that in Kubeapps as it hasn't landed upsteram . Details towards the end of #2118 . Don't know if that's relevant to your situation, or whether you are somehow using OpenShift but with MS AD?

**Comment by davidkarlsen** [comment]
Hi, yes, I use AAD as IDP via OIDC: https://docs.openshift.com/container-platform/4.6/authentication/identity_providers/configuring-oidc-identity-provider.html
Internally OS runs an oauth server: https://docs.openshift.com/container-platform/4.6/authentication/configuring-internal-oauth.html - which again can use several sources of auth (oidc, ldap, etc)

I found this project which is a fork of oauth2proxy https://github.com/openshift/oauth-proxy, so that will redirect me into OS common login, where I can select login options, and then get redirected back, so I think this is maybe a good option. I just need to figure out how kubeapps can use it. It seems to get back with an Authorization header.

**Comment by dealboy** [comment]
regarding my initial issue, the replies by @absoludity and the details in #2208 allowed me to configure OIDC and it works fine.
Thanks a lot.

**Comment by absoludity** [comment]
Excellent, thanks for letting us know @dealboy
