### ISSUE TITLE
FAQ entry or otherwise document steps for debugging oidc logins

### ISSUE THREAD

**Issue by absoludity** [kubeapps/kubeapps#2208]
### Description:

We often get questions about how to debug oidc logins where the user logs in to the SSO successfully but Kubeapps says it's a 401.

These are actually easy once you know how, but we really need to document the know-how :) (probably at https://github.com/kubeapps/kubeapps/blob/master/docs/user/using-an-OIDC-provider.md ).

First, if you temporarily set the `--set-authorization-header=true` option for oauth2 proxy, the actual `id_token` will be included in the Authorization header of the response back to the client, so you can then:

1) base64 decode the token (or paste into https://jwt.io if it's a local throw-away credential for testing) to verify the token has the correct user/groups etc. that you expect, and
2) use the token with `curl -H "Authorization: Bearer $TOKEN" ...` to reproduce the issue without depending on Kubeapps etc.

Once you can reproduce, there are a couple of possibilities for the cause which commonly trip people up:

1. Sometimes people don't have a k8s cluster api server even configured for oidc (not realising that was necessary). Easy to check the api server oidc args with something like:
```
k -n kube-system get po -l component=kube-apiserver -o yaml | grep oidc
      - --oidc-ca-file=/etc/kubernetes/pki/apiserver.crt
      - --oidc-client-id=default
      - --oidc-groups-claim=groups
      - '--oidc-groups-prefix=oidc:'
      - --oidc-issuer-url=https://172.18.0.2:32000
      - --oidc-username-claim=email
      - '--oidc-username-prefix=oidc:'
```

2. The most common problem is that the api server is using an `oidc-username-prefix` (whether explicitly specified or the default - the [docs specify that the default for both the username and group prefix is `oidc:`](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#configuring-the-api-server) but I've always explicitly defined it). So for a token identifying a user of `myname@example.com`, the RBAC would need to be for the user `oidc:myname@example.com` .

**Comment by andresmgot** [comment]
so... you just need to copy this description to the FAQ, isn't it? :+1:

**Comment by absoludity** [comment]
> so... you just need to copy this description to the FAQ, isn't it? +1

Yep, I tried to dump what I had just told someone here. I'll paste it into a PR.
