### ISSUE TITLE
Emptying values box when deploying crashes page

### ISSUE THREAD

**Issue by bruce2409** [kubeapps/kubeapps#221]
When you're on the deployment page, if you empty by selecting all and deleting the content of the Values box or just select all and paste, the page crashes and just shows loading at the top.

Here's a recording: https://streamable.com/ioa3f

This happens in both chrome 65.0.3325.181 and firefox 59.0.2 in OS X 10.13 as well as Chrome in Windows, so don't think it's anything browser side?

**Comment by bruce2409** [comment]
As show in video, leaving even a single character in the editor doesn't crash it, just if you completely empty it.

**Comment by prydonius** [comment]
@sameersbn I remember you coming across this, was it fixed in master?
