### ISSUE TITLE
Update all google docs links after the workspace migration

### ISSUE THREAD

**Issue by antgamdia** [kubeapps/kubeapps#2215]
9 links in 7 files:

docs/architecture/design-proposals/README.md
 - https://docs.google.com/document/d/1YZzLtIbS2copQJgspFiMd0eAhpyt8u19MUSDEvH2X4g
 - https://docs.google.com/document/d/1oG9nerd5CurWSIwH33kKCsOCtkSFMgcm8SuTJyuSnxs/

docs/architecture/design-proposals/OCI-registries.md
 - https://docs.google.com/document/d/1-9mAdNhu_Hue8ZmCywXQbNEOLhC1-IABQ36zk_Ua1SM/edit
 

docs/architecture/design-proposals/clarity-ui.md
 - https://docs.google.com/document/d/1rnrU2T3YB-mk68XpCW9GXnkcg2v2xLz7tijSLMR3GEc/
 

docs/architecture/design-proposals/multi-cluster-support.md
- https://docs.google.com/document/d/1-6cKxOsW6K5u3lK7Om2zQeVYVPxzHT6dVwej5wy3_9A/edit
- https://docs.google.com/document/d/1-6cKxOsW6K5u3lK7Om2zQeVYVPxzHT6dVwej5wy3_9A/edit
 

docs/developer/pinniped-proxy.md
 - https://docs.google.com/document/d/1Sqhq_JIfb7M3K5RloV4T2itznu56EDJm_PEz2yrPk1E/edit#

docs/architecture/design-proposals/sso-without-oidc-api-server.md
 - https://docs.google.com/document/d/1Sqhq_JIfb7M3K5RloV4T2itznu56EDJm_PEz2yrPk1E/edit#
 

docs/user/private-app-repository.md
 - https://docs.google.com/document/d/1YEeKC6nPLoq4oaxs9v8_UsmxrRfWxB6KCyqrh2-Q8x0/edit?ts=5e2adf87

**Comment by andresmgot** [comment]
note that some of them are linked to `bitnami.com` accounts and are still valid
