### ISSUE TITLE
Do we have the swagger API doc of Dashboard or KubeOPS?

### ISSUE THREAD

**Issue by DesistDaydream** [kubeapps/kubeapps#2222]
Do we have the swagger API doc of Dashboard or KubeOPS?

When I want to use kubeapps through API, I did not find API documentation

Or, do we plan to create a Swagger API?

**Comment by antgamdia** [comment]
Thank you for your interest in having proper API documentation. It is something we have been thinking of, but the main development effort prevents us from having enough time for addressing this.

Currently, the main assetsvc and kubeops APIs are being defined at: https://github.com/kubeapps/kubeapps/blob/master/cmd/kubeops/main.go#L109 and
https://github.com/kubeapps/kubeapps/blob/master/cmd/assetsvc/main.go#L47

But, of course, having a good OpenAPI model of these API is something really interesting. We will discuss it in the upcoming iteration planning.

Thanks for popping up this!

**Comment by DesistDaydream** [comment]
I am very happy to see that this issue has been moved to the Next iteration discussion.
Wish kubeapps better and better
