### ISSUE TITLE
All k8s resources for a release polled continuously even after navigating away on Firefox

### ISSUE THREAD

**Issue by absoludity** [kubeapps/kubeapps#2258]
### Description:

Watching the network requests while viewing a release shows that:
1. a bunch of connection upgrade requests go through to watch the resources,
2. the dashboard additionally begins polling all resources on a timeout
3. all resources continue to be polled after switching to another page.

These continue to accumulate as you visit other app releases so that you end up flooding the backend.

Questions:
1. Why are we both upgrading to a websocket successfully and then also polling? Was this from the work to resolve the issues with websockets? I would have thought we should only be polling if the websocket connections failed.
2. Why are we watching/polling resources on completed releases? Yes, they could go into a different state which the websocket will handle, but if we're polling we should not be polling with the same frequency as when initially running an app?
3. Why are we watching/polling *all* resources (ie. not just those that change state, but also those that don't, such as roles, clusterroles etc etc.)
4. Why are we continuing to watch/poll the resources after navigating away from the release page (guessing this is just a bug)

### Steps to reproduce the issue:

1. Open your Kubeapps URL and notice in the Network tab
2. Navigate to view the Kubeapps release and watch the network tab for a minute. You'll see ~30 101 upgrades to websocket, followed by ~30-40 requests every 5s
3. Navigate back to the Apps and watch the polling continue
4. navigate back to the Kubeapps release and watch more items being added to the polling.

Repeate 3-4 and you'll be flooding the backend in no time :)

### Describe the results you received:

The (unnecessary?) polling accumulates until the backend is flooded with requests

### Describe the results you expected:

1. Polling wouldn't be required when the websocket upgrade is successful
2. Polling wouldn't poll all resources, just those that change
3. Even for resources that can change after a release, polling would not be as frequent
4. Polling wouldn't continue after navigating away from a release

**Comment by andresmgot** [comment]
It seems that the bug only appears in your current setup. I am not able to reproduce it in my local environment, neither in the GKE demo setup. In the first setup (local) the websocket is successfully upgraded and no periodic request is made. In the second (GKE) the websocket connection fails and the periodic requests are made but once the AppView component is closed, the requests stop.

> * Why are we both upgrading to a websocket successfully and then also polling? Was this from the work to resolve the issues with websockets? I would have thought we should only be polling if the websocket connections failed.

We are not. The polling is only triggered if the websocket connection throws an error. The code is here:

https://github.com/kubeapps/kubeapps/blob/master/dashboard/src/actions/kube.tsx#L129
https://github.com/kubeapps/kubeapps/blob/master/dashboard/src/reducers/kube.ts#L191

So my guess is that in your env, the socket receives an "error" event but it's still able to perform the connection?

> * Why are we watching/polling resources on completed releases? Yes, they could go into a different state which the websocket will handle, but if we're polling we should not be polling with the same frequency as when initially running an app?

There is not a exponential back off mechanism for neither success nor failure scenarios but that can be a potential point of improvement, yes.

> * Why are we watching/polling _all_ resources (ie. not just those that change state, but also those that don't, such as roles, clusterroles etc etc.)

We don't have that distinction atm, we could have a hardcoded list of elements we are interested on (workloads, services, ingresses).

> 4\. Why are we continuing to watch/poll the resources after navigating away from the release page (guessing this is just a bug)

Again we are not, we are calling `closeTimer()` when the component is unmounted:

https://github.com/kubeapps/kubeapps/blob/master/dashboard/src/components/AppView/ResourceTable/ResourceTable.tsx#L78https://github.com/kubeapps/kubeapps/blob/master/dashboard/src/reducers/kube.ts#L209

Can you telepresence into the cluster and get more info? (for example, what error the websocket is throwing or if the cleanup action is being called).

**Comment by absoludity** [comment]
> It seems that the bug only appears in your current setup.

I can reproduce the requests never stopping on the GKE demo setup (with Firefox, which Chrome it doesn't happen).

> I am not able to reproduce it in my local environment, neither in the GKE demo setup.

Did you try with a different browser? I can confirm the requests stop on Chromium when navigating away from the app view, but not on FF.

> In the first setup (local) the websocket is successfully upgraded and no periodic request is made.

Confirmed that with Chromium, it does both websocket and two lots of non-websocket requests, but does not poll as the websocket request succeeds. For example, here are all the requests filtered for 'postgresql' from the Kubeapps deployment:

![kubeapps-postgresql-requests](https://user-images.githubusercontent.com/497518/105247697-4f2f8300-5bc9-11eb-87ea-114809dac363.png)

But with Firefox in the same environment, it seems the websocket upgrade returns 101 but then the connection "was interrupted while the page was loading" so it starts polling:

![kubeapps-postgresql-requests-ff](https://user-images.githubusercontent.com/497518/105248701-f4972680-5bca-11eb-94b0-cb24614f3a59.png)

Furthermore, as per the report, if I navigate back to the Applications, the polling continues (both locally and on GKE).

> In the second (GKE) the websocket connection fails and the periodic requests are made but once the AppView component is closed, the requests stop.

Confirmed they stop with Chrom(ium), but continue with Firefox here. Can you re-check please?

> 
> > * Why are we both upgrading to a websocket successfully and then also polling? Was this from the work to resolve the issues with websockets? I would have thought we should only be polling if the websocket connections failed.
> 
> We are not.

Sorry, that was my mistake. I read the 101s in FireFox as a successful upgrade and missed that the websocket connection was subsequently interrupted in the console. 

> 
> So my guess is that in your env, the socket receives an "error" event but it's still able to perform the connection?

Correct, though not my env, rather with the FF browser afaict. 

> > * Why are we watching/polling resources on completed releases? Yes, they could go into a different state which the websocket will handle, but if we're polling we should not be polling with the same frequency as when initially running an app?
> 
> There is not a exponential back off mechanism for neither success nor failure scenarios but that can be a potential point of improvement, yes.

Especially for apps with lots of resources.


> 
> > * Why are we watching/polling _all_ resources (ie. not just those that change state, but also those that don't, such as roles, clusterroles etc etc.)
> 
> We don't have that distinction atm, we could have a hardcoded list of elements we are interested on (workloads, services, ingresses).

Ditto - important for apps with lots of resources.

> 
> > 4. Why are we continuing to watch/poll the resources after navigating away from the release page (guessing this is just a bug)
> 
> Again we are not, we are calling `closeTimer()` when the component is unmounted:
> 
> https://github.com/kubeapps/kubeapps/blob/master/dashboard/src/components/AppView/ResourceTable/ResourceTable.tsx#L78https://github.com/kubeapps/kubeapps/blob/master/dashboard/src/reducers/kube.ts#L209
> 
> Can you telepresence into the cluster and get more info? (for example, what error the websocket is throwing or if the cleanup action is being called).

Happy to dig deeper if you are unable to reproduce that with Firefox neither locally or on GKE. Let me know please.

**Comment by andresmgot** [comment]
Indeed, I can reproduce it with Firefox, weird. I will try to get more info.
