### ISSUE TITLE
Unable to install Kubeapps in TKG cluster

### ISSUE THREAD

**Issue by AkhilCh308** [kubeapps/kubeapps#2271]
### Describe the results you received:
When we give, helm install kubeapps --namespace kubeapps-test-2 --set assetsvc.service.port=9090 bitnami/kubeapps
Error: secrets "kubeapps-db" already exists
also, when i give helm list, status showing failed
root@tkg [ ~ ] tkg12workloadcluster-01-admin@tkg12workloadcluster-01:default) # helm list -n kubeapps-test-2
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS  CHART           APP VERSION
kubeapps        kubeapps-test-2 1               2021-01-22 11:05:28.406449774 +0000 UTC failed  kubeapps-5.0.1  2.0.1

Now proceeding further steps in doc, we're able to access ui, but soon after pasted the secret, goes on loading, no further results.

FYI, on of my colleague installed kubeapps in his minikube, but when we try the same in our tkg cluster we're facing the issues mentioned above, tkg-version: 1.2.0

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
(paste your output here)
```

- Output of `helm list -n <kubeapps-namespace> <kubeapps-release-name>`:

```
(paste your output here)
```

- Output of `kubectl version`:

```
(paste your output here)
```

**Comment by andresmgot** [comment]
hi @AkhilCh308,

The error you mention `Error: secrets "kubeapps-db" already exists` seems to be related to a previous installation of Kubeapps that was not properly cleaned-up. Can you, uninstall the release, delete the namespace `kubeapps-test-2` and try again in a clean environment?

**Comment by absoludity** [comment]
As Andres mentioned, this just appears to be resources from a previous (failed) installation which haven't been deleted. After ensuring it's deleted and retrying, you may get the original error.

FWIW, I documented exactly what I did to run Kubeapps on TKG (though 1.1, so there will be some differences) with SSO authentication at: https://liveandletlearn.net/post/kubeapps-on-tkg-management-cluster/

**Comment by AkhilCh308** [comment]
Hi @andresmgot,

I've cleaned everything in namespace "kubeapps-test-2", and started fresh in a new namespace, I've followed the steps given in the document - https://tanzu.vmware.com/developer/guides/kubernetes/kubeapps-gs/
Here are the steps and their output

`root@tkg [ ~ ] tkg12workloadcluster-01-admin@tkg12workloadcluster-01:default) # k get all -n kubeapps-test-2
No resources found in kubeapps-test-2 namespace.
root@tkg [ ~ ] tkg12workloadcluster-01-admin@tkg12workloadcluster-01:default) # k get secret -n kubeapps-test-2
NAME                  TYPE                                  DATA   AGE
default-token-52jzq   kubernetes.io/service-account-token   3      2d18h
root@tkg [ ~ ] tkg12workloadcluster-01-admin@tkg12workloadcluster-01:default) # k get sa -n kubeapps-test-2
NAME      SECRETS   AGE
default   1         2d18h
root@tkg [ ~ ] tkg12workloadcluster-01-admin@tkg12workloadcluster-01:default) # k create ns kubeapps-test-3
namespace/kubeapps-test-3 created
root@tkg [ ~ ] tkg12workloadcluster-01-admin@tkg12workloadcluster-01:default) # helm repo add bitnami https://charts.bitnami.com/bitnami -n kubeapps-test-3
"bitnami" has been added to your repositories
root@tkg [ ~ ] tkg12workloadcluster-01-admin@tkg12workloadcluster-01:default) # helm install kubeapps --namespace kubeapps-test-3 bitnami/kubeapps --set useHelm3=true
Error: secrets "kubeapps-db" already exists
root@tkg [ ~ ] tkg12workloadcluster-01-admin@tkg12workloadcluster-01:default) # k get secret -n kubeapps-test-3
NAME                                                          TYPE                                  DATA   AGE
default-token-qp258                                           kubernetes.io/service-account-token   3      3m6s
kubeapps-db                                                   Opaque                                2      68s
kubeapps-internal-apprepository-controller-token-9mp6x        kubernetes.io/service-account-token   3      68s
kubeapps-internal-apprepository-job-postupgrade-token-rbjbb   kubernetes.io/service-account-token   3      68s
kubeapps-internal-apprepository-jobs-cleanup-token-bdv7s      kubernetes.io/service-account-token   3      68s
kubeapps-internal-db-secret-jobs-cleanup-token-44dgs          kubernetes.io/service-account-token   3      68s
kubeapps-internal-kubeops-token-v947n                         kubernetes.io/service-account-token   3      68s
sh.helm.release.v1.kubeapps.v1                                helm.sh/release.v1                    1      68s
root@tkg [ ~ ] tkg12workloadcluster-01-admin@tkg12workloadcluster-01:default) # helm list
NAME            NAMESPACE       REVISION        UPDATED                                         STATUS          CHART                   APP VERSION
app             default         1               2020-11-25 04:46:09.332926373 +0000 UTC         deployed        mcds-nodejs-app-0.1.0   0.0.0
mcds-gradle     default         1               2020-12-07 11:34:28.447346111 -0500 -0500       deployed        mcds-gradle-0.1.0       0.0.0
tomcat          default         1               2020-12-02 11:58:13.870485842 +0000 UTC         deployed        tomcat-7.0.0            9.0.39
root@tkg [ ~ ] tkg12workloadcluster-01-admin@tkg12workloadcluster-01:default) # helm list -n kubeapps-test-3
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS  CHART           APP VERSION
kubeapps        kubeapps-test-3 1               2021-01-25 05:14:22.702508707 +0000 UTC failed  kubeapps-5.0.1  2.0.1
root@tkg [ ~ ] tkg12workloadcluster-01-admin@tkg12workloadcluster-01:default) #


Thing is, when I try to deploy kubeapps for the first time, I've got the same error : Error: secrets "kubeapps-db" already exists
But if we see, even though it threw error, secret "kubeapps" is created in that namespace.
and also soon after we perfom helm install command, then if we see helm status, it's showing failed.
But when I proceed with further steps according to document, finally am able to access kubeapps dashboard, and pasted the secret key to login, from then it started loading and continues, no further result.


Also while I delete namespace, it's status is showing "terminating" for a long time

root@tkg [ ~ ] tkg12workloadcluster-01-admin@tkg12workloadcluster-01:default) # k get ns
NAME                        STATUS        AGE
build-service               Active        46d
cert-manager                Active        55d
default                     Active        75d
elastic                     Active        54d
fromvra8                    Active        59d
jenkins                     Active        68d
k-t                         Active        6d
kpack                       Active        46d
kube-node-lease             Active        75d
kube-public                 Active        75d
kube-system                 Active        75d
kubeapps-tanzu              Terminating   11d
kubeapps-test               Terminating   2d18h

**Comment by andresmgot** [comment]
mmh, that's weird, it should not happen in a clean environment. What version of Helm are you using? Maybe it's a bug in the current version that you are using that is not properly handling the `pre-install` hook.

> But when I proceed with further steps according to document, finally am able to access kubeapps dashboard, and pasted the secret key to login, from then it started loading and continues, no further result.

The installation is not successful, so it may be the case that there some missing resources in your setup. In any case, can you let us know how have you accessed the dashboard (the command you are using to open the `port-forward` tunnel, for example) and if there is any error in the `Console` or `Network` tabs of your web browser?

**Comment by AkhilCh308** [comment]
root@tkg [ ~ ] tkg12workloadcluster-01-admin@tkg12workloadcluster-01:default) # helm version
version.BuildInfo{Version:"v3.3.0-rc.1", GitCommit:"5c2dfaad847df2ac8f289d278186d048f446c70c", GitTreeState:"dirty", GoVersion:"go1.14.4"}
root@tkg [ ~ ] tkg12workloadcluster-01-admin@tkg12workloadcluster-01:default) #

this is the helm version

command used to access dashboard: kubectl port-forward -n kubeapps-test-3 svc/kubeapps 8080:80

Then I've accessed dashboard, it asked to paste the secret key, after that it stuck with loading, and no error with my web browser, it working fine

**Comment by andresmgot** [comment]
you are using a non-stable version of Helm, can you try the latest one: https://github.com/helm/helm/releases/tag/v3.5.0 and verify if the problem persists?

**Comment by AkhilCh308** [comment]
Thanks @andresmgot by following your steps, I resolved the issue, thanks for your time

Regards,
Akhil Surepally

**Comment by andresmgot** [comment]
Thanks for letting us know!
