### ISSUE TITLE
auth-proxy should use secrets for OIDC clientId, clientSecret and cookieSecret

### ISSUE THREAD

**Issue by floek** [kubeapps/kubeapps#2275]
### Description:

The current deployment of oauth2-proxy adds sensitive information to the parameter list of oauth2-proxy.
From `chart/kubeapps/templates/kubeapps-frontend-deployment.yaml´: 
```
- --client-id={{ required "You must fill \".Values.authProxy.clientID\" with the Client ID of the provider" .Values.authProxy.clientID }}
- --client-secret={{ required "You must fill \".Values.authProxy.clientSecret\" with the Client Secret of the provider" .Values.authProxy.clientSecret }}
- --cookie-secret={{ required "You must fill \".Values.authProxy.cookieSecret\" with a 16, 24 or 32 byte base64 encoded seed string for secure cookies" .Values.authProxy.cookieSecret }}       
```

This exposes the data in the process list. It maybe better to put those data in a secret or environment variable as shown nginx-ingress external OAUTH authentication example or kubeprod:
- https://kubernetes.github.io/ingress-nginx/examples/auth/oauth-external-auth/
- https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/docs/examples/auth/oauth-external-auth/oauth2-proxy.yaml
- https://github.com/bitnami/kube-prod-runtime/blob/master/manifests/components/oauth2-proxy.jsonnet

### Steps to reproduce the issue:

1. Define in helm chart values:
```
authProxy:
  enabled: true
  skipKubeappsLoginPage: true
  provider: "oidc"
  clientID: "myId"
  clientSecret: "myClientSecret"
  cookieSecret: "myCookieSecret"
```

### Describe the results you received:

Sensitive data in the process list.

### Describe the results you expected:

No sensitive data in the process list.

### Additional information you deem important (e.g. issue happens only occasionally):

Permanent.

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
```

- Output of `helm list -n <kubeapps-namespace> <kubeapps-release-name>`:

```
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
kubeapps        kubeapps        6               2021-01-22 12:27:29.627126572 +0100 CET deployed        kubeapps-5.0.1  2.0.1
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by absoludity** [comment]
Indeed, thanks @floek
