### ISSUE TITLE
Avoid to close the websocket connection when loading the component

### ISSUE THREAD

**Issue by andresmgot** [kubeapps/kubeapps#2276]
### Description:

Follow up of #2267

After https://github.com/kubeapps/kubeapps/pull/2267#issuecomment-765252896, I noticed that the websocket connection to get application resources is opened and close several times during the loading of the component. Causing an error (warning) if the socket is closed before the connection is finished. We should avoid closing the socket if the component is still loading.

**Comment by absoludity** [comment]
Importantly, if we do this we may be able to remove the work-around currently starting to poll then stopping the poll if we get data on the websocket.
