### ISSUE TITLE
[Feature enhance]Use git to save helm values

### ISSUE THREAD

**Issue by SaigyoujiYuyuko233** [kubeapps/kubeapps#2277]
### Description:
I think kubeapps can add a feature that support save helm values using git repo.
For example, we can bind git repo that in gitlab/github/local that use to save the values.yaml
The process is like:
- 1. bind git repo (gitlab/github/local)
- 2. user go to deploy/upgrade a application
- 3. below the config editor, there is a section that allow user to make comment for git
- 4. when application deploy/upgrade successfully, commit to git and push if nessary

Thanks for hard working! :)

**Comment by andresmgot** [comment]
We have an issue opened to evaluate GitOps in Kubeapps: https://github.com/kubeapps/kubeapps/issues/979

**Comment by SaigyoujiYuyuko233** [comment]
> We have an issue opened to evaluate GitOps in Kubeapps: #979

Sorry for late reply, thanks! I'll check that!
