### ISSUE TITLE
Common customisations to Kubeapps components after installation

### ISSUE THREAD

**Issue by prydonius** [kubeapps/kubeapps#228]
In order to better understand how we can improve the upgrade path for Kubeapps components, we need to understand how people might want to change or customise the installation after an initial `kubeapps up`. Today, any user customisations would be overwritten by subsequent `kubeapps up` runs.

Comment in this issue if there are customisations you're making to Kubeapps after the initial installation.

Common ones I've seen:

- Ingress: changing the class/annotations/tls to work with another Ingress controller
- kube-api pod: adding `--disable-filter` flag to make Kubeapps work on external domain names. This one won't be an issue when we finish the work on AuthN/Z as we will include that flag by default.

**Comment by prydonius** [comment]
- Configuring a storageClass or emptyDir for MongoDB

**Comment by prydonius** [comment]
- Configuring a different image registry to pull from (from @cristian04)

**Comment by arapulido** [comment]
We can now close this issue, as we have a helm chart.
