### ISSUE TITLE
Integrate Artifactory Charts repo 

### ISSUE THREAD

**Issue by sebgoa** [kubeapps/kubeapps#229]
If charts are stored in artifactory we should be able to add the repo in kubeapps and pull down the charts.

It might just work out of the box

https://www.jfrog.com/confluence/display/RTF/Helm+Chart+Repositories

**Comment by prydonius** [comment]
Cool, I think it might work although I'm not sure about the username and password. If it's basic auth, it should work if it's encoded in the string (e.g. https://<user>:<password>@my-chart-repo.com/charts). Either way, we should definitely check it out.

**Comment by sebgoa** [comment]
@prydonius can you put a link to the code line that does chart repo sync ? or the service actually.

**Comment by sameersbn** [comment]
@sebgoa https://github.com/kubeapps/kubeapps/tree/master/cmd/apprepository-controller is the CRD that handles the repo sync. We would need to add authentication support for the sync here. 

The dashboard needs to be updated to allow users to specify the credentials to authenticate with the chart repo.

**Comment by sameersbn** [comment]
Update: I have been playing around with Artifactory and found that Artifactory allows unauthenticated anonymous access to the helm repository, therefore we can use the URL as-is to build the chart cache in kubeapps. I am checking if it's possible to disable the anonymous access in the configuration. @sebgoa Do you think it's worth working on adding support for authenticated chart downloads?

@adnan Thanks for your insight. 

> Is basic auth the only auth mechanism used in Artifactory?

Yes, thats correct. HTTP Basic authentication is used and I don't seen any other authentication methods supports.

Talking about the authentication, we'd also need to add support for authentication in the helm-crd resource

**Comment by sameersbn** [comment]
Update 2: 

The anonymous access can be disabled by configuring the file permissions.

**Comment by sameersbn** [comment]
> I think the best way to do this securely would be to have the AppRepository CRD reference a secret containing the basic auth user/pass,

@prydonius So when a user adds a repo with auth, kubeapps would need to create the secret which would then be referred my the CRD, right?

**Comment by sameersbn** [comment]
> I guess we need to support authenticated chart downloads, then

correct!

**Comment by prydonius** [comment]
> Talking about the authentication, we'd also need to add support for authentication in the helm-crd resource

Ah, you're right.

> @prydonius So when a user adds a repo with auth, kubeapps would need to create the secret which would then be referred by the CRD, right?

yeah, that's what I was thinking

**Comment by ankushchadha** [comment]
API Keys can be used - Following needs to be added to the header - "X-JFrog-Art-Api:..."

Access Tokens can also be used - Following needs to be added to the header - "Authorization: Bearer <Token>"

More details [here]([https://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API#ArtifactoryRESTAPI-Authentication])

**Comment by sameersbn** [comment]
thanks for the info @ankushchadha . thats really helpful. I think we're going to go ahead with the use of access tokens.

**Comment by prydonius** [comment]
@ankushchadha do access tokens expire after some time? It would be nice to use the `Authorization: Bearer` header as it is more standard and we can reuse it for other protocols. If the API key is the only way to do this though, we can either use the `type` field in the AppRepository CRD to indicate Artifactory, or we could simply support custom headers (more flexible, but more work for the user).

**Comment by sameersbn** [comment]
@prydonius Access tokens have an expiry period so you can control the period of time for which you grant access. You can all set a token to be non-expirable by setting the expiry to zero, in which case it will remain valid indefinitely until actively revoked.

**Comment by prydonius** [comment]
@sameersbn thanks for looking into that, sounds like that's a good way to go then (non-expiring access token) and we can add documentation on how to do that with Artifactory.

**Comment by sameersbn** [comment]
Implemented in https://github.com/kubeapps/kubeapps/pull/247 and https://github.com/bitnami-labs/helm-crd/pull/23

Demo:

![sneekpeek](https://user-images.githubusercontent.com/410147/39048683-f77e780e-44bb-11e8-9aca-1d548ce3e248.gif)

**Comment by prydonius** [comment]
@sameersbn awesome work!!

**Comment by arapulido** [comment]
🙌  Great work! and very cool demo!

**Comment by sameersbn** [comment]
Kubeapps 0.7.0 is out with this feature!
