### ISSUE TITLE
Catalog UI shaking while retrieving filtered charts 

### ISSUE THREAD

**Issue by antgamdia** [kubeapps/kubeapps#2290]
### Description:

UI keeps shaking while loading more items:

![shakingUI2](https://user-images.githubusercontent.com/11535726/106136002-ec119380-6168-11eb-9099-0e24d2c308eb.gif)

### Steps to reproduce the issue:

1. Go to the catalog and do -not- scroll down
2. Select a category (it will trigger a whole fetching page by page)
3. UI will shake until everything is fetched

### Describe the results you received:

UI shakes because of a div appearing and disappearing

### Describe the results you expected:

UI not shaking

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}
```

- Output of `helm list -n <kubeapps-namespace> <kubeapps-release-name>`:

```
kubeapps        kubeapps        1               2021-01-28 12:10:10.852090143 +0100 CET deployed        kubeapps-5.0.1  DEVEL      
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by absoludity** [comment]
Related to https://github.com/kubeapps/kubeapps/pull/1474 (Antonio, meet Simon :) )
