### ISSUE TITLE
Documentation note for install using namespace other than default

### ISSUE THREAD

**Issue by thejonpearson** [kubeapps/kubeapps#2292]
### Description:

Within the [getting started guide ](https://github.com/kubeapps/kubeapps/blob/master/docs/user/getting-started.md), step 2 suggests creating a cluster role binding using the flag 

`--serviceaccount=default:kubeapps-operator`

I'm not certain if the issue is specifically in the creation of the service account or the app itself, but when installing and creating a service account using a namespace other than default the resulting token will be accepted for moving past the initial auth but the dashboard will load a mostly blank page, and api returns a 403. 

Suggest a minor update to the getting started guide that mentions specifying the correct namespace for the service account if KubeApps or the service account was created in a namespace other than `default`. 

### Steps to reproduce the issue:

1. Create new namespace and switch to it: `kubectl create ns kubeapps && kubens kubeapps`
2. Install via helm (almost certainly applies to any install method)
3. Create serviceaccount: `kubectl create serviceaccount kubeapps-operator`
4. Create clusterrolebinding: `kubectl create clusterrolebinding kubeapps-operator --clusterrole=cluster-admin --serviceaccount=default:kubeapps-operator`
5. Retrieve kubeapps-operator auth token: `kubectl get secret $(kubectl get serviceaccount kubeapps-operator -o jsonpath='{range .secrets[*]}{.name}{"\n"}{end}' | grep kubeapps-operator-token) -o jsonpath='{.data.token}' -o go-template='{{.data.token | base64decode}}' && echo`
6. ((port forward if not using ingress or public IP via loadbalancer))
7. Open dashboard in web browser and authenticate using token

### Describe the results you received:

Dashboard header partially loads (blue banner and KubeApps logo only, no Apps/Catalogs tabs, context menu or waffle menu) loads, loading spinner spins forever. 

Console reports 403 attempting to load `/api/clusters/default`.

### Describe the results you expected:

Dashboard populates correctly. 

Alternatively, it would be great to see some sort of pre-validation of the token at the auth page and returning a user-friendly error if the token is valid but not usable for the app itself would be fantastic! Updating the documentation is far easier though :)

**Comment by absoludity** [comment]
Thanks @thejonpearson . Would another simpler solution for the getting started guide be to simply be explicit about the namespace when creating the service account? Like #2293 ?
