### ISSUE TITLE
"Login via OIDC Provider" text not configurable

### ISSUE THREAD

**Issue by absoludity** [kubeapps/kubeapps#2325]
### Description:

Currently if you configure your Kubeapps installation to use, say VMware Cloud Services for authentication, you don't want users to have to click on the label "Login via OIDC Provider" to log in. Instead, you should be able to configure this text during installation so it can say "Login via VMware Cloud Services" for example.

**Comment by andresmgot** [comment]
I think this is somethingi @antgamdia is evaluating, to make these strings configurable
