### ISSUE TITLE
Unexpected style changes

### ISSUE THREAD

**Issue by andresmgot** [kubeapps/kubeapps#2348]
### Description:

There are some style changes currently in master. This is the current status:

![Screenshot from 2021-02-08 16-14-21](https://user-images.githubusercontent.com/4025665/107240011-bc487280-6a29-11eb-968d-165fdf504b3d.png)

And this is how is supposed to look like:

![Screenshot from 2021-02-08 16-14-37](https://user-images.githubusercontent.com/4025665/107240052-c8343480-6a29-11eb-93c6-7f22c201f6ec.png)

Note the misplaced titles and text.

I can confirm this is because the clarity upgrade at #2327.

I am going to revert that commit for the moment until we allocate the proper time to bump the major version of Clarity.

**Comment by antgamdia** [comment]
Great, let's revert until we have some time to check it closely. Thanks for letting us know!

**Comment by antgamdia** [comment]
Should we close this issue but take it into consideration when https://github.com/kubeapps/kubeapps/issues/2372?

**Comment by andresmgot** [comment]
okay, following up in the new issue
