### ISSUE TITLE
Feature: Custom Form Components

### ISSUE THREAD

**Issue by aanthonyrizzo** [kubeapps/kubeapps#2352]
Kubeapps is an awesome UI solution for launching applications on Kubernetes. However I think that it lacks a lot of customization. One area that I think has a lot of customization potential is the deployment form. I think allowing developers to import custom components would be a great feature and would allow devs to take control of the form components. The component devs can add live validation, custom UI elements, etc and really bring the form building to the next level. 

After looking through the codebase these seem to be the places that would need to change to make this happen:
1. An additional field in `IBasicFormParam`. This would be called something like `customFormComponent` which would exist in the json schema to tell the dashboard that we want to render a custom component instead of one of the provided form components.
2. Some logical condition that checks for `param.customFormComponent` so that we can render the component.
3. A way to programmatically import the component package into the conditional stated above (im not quite sure the best way to do this).

Im very interested in this and am willing to start working on it if you think this is something that would be possible @andresmgot. Im also open to other implementations I just outlined what seemed like the easiest/best way.

**Comment by andresmgot** [comment]
Hi @aanthonyrizzo, thanks for bringing this up.

In my opinion, I'd love to see those customizations in the upstream project so everyone can benefit from them. From the description you have, only the person writing the `customFormComponent` would be able to use the modification while it's something that other people may find useful.

I'd go for the direction of making the current code as easy as possible to extend (I know now is a bit convoluted) so people looking for new formats (e.g. arrays :)) can contribute.

If there is a very opinionated style someone wants to apply (e.g. having form boxes in red), we could support that making it optional.

WDYT?
