### ISSUE TITLE
Review and clean old, no longer used remote branches?

### ISSUE THREAD

**Issue by danoo** [kubeapps/kubeapps#2370]

**Comment by antgamdia** [comment]
When a user jumps in the Kubeapps repo, it's a bit weird viewing all these branches. It has no effect, but, I (personally) like to have a clean policy of active branches:

![branches](https://user-images.githubusercontent.com/11535726/107496749-ffbdf080-6b91-11eb-9d55-1309fd4116b9.gif)

**Comment by andresmgot** [comment]
_cleaned mine_

**Comment by antgamdia** [comment]
_cleaned mine_

**Comment by absoludity** [comment]
Done and [updated the settings so they're deleted automatically on merge](https://docs.github.com/en/github/administering-a-repository/managing-the-automatic-deletion-of-branches).
