### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by danoo** [kubeapps/kubeapps#2371]

**Comment by antgamdia** [comment]
See Clarity theming options: https://clarity.design/foundation/themes/usage/#custom-theme

**Comment by antgamdia** [comment]
Some updates here :) 

![image](https://user-images.githubusercontent.com/11535726/108560521-22bc7300-72fd-11eb-8cb0-0daee16f7871.png)

![image](https://user-images.githubusercontent.com/11535726/108560616-50092100-72fd-11eb-9998-4faa49573439.png)

![image](https://user-images.githubusercontent.com/11535726/108560761-88a8fa80-72fd-11eb-84d7-238ce4043b8f.png)

![image](https://user-images.githubusercontent.com/11535726/108561017-d6256780-72fd-11eb-842a-21a6aa944968.png)

**Comment by absoludity** [comment]
Woah - looks great!

**Comment by andresmgot** [comment]
:rocket: cool!

Minor thing regarding icons: we should use a white-version of the icons we currently have for getting the right contrast, for example, the helm icon here:

![Screenshot from 2021-02-22 10-48-54](https://user-images.githubusercontent.com/4025665/108691316-a8a60d00-74fb-11eb-8e76-c20502bc57c2.png)

**Comment by antgamdia** [comment]
>  cool!
> 
> Minor thing regarding icons: we should use a white-version of the icons we currently have for getting the right contrast, for example, the helm icon here:
> 
> ![Screenshot from 2021-02-22 10-48-54](https://user-images.githubusercontent.com/4025665/108691316-a8a60d00-74fb-11eb-8e76-c20502bc57c2.png)

I did some trick in the 404 image (since it was not that important), a css filter inverting colors.
Here we should change, indeed, the image. I have to look into how the images are being loaded: just css? or do we control them in react?
I'll investigate it and will send a PR soon :)
Thanks!

**Comment by antgamdia** [comment]
Currently, this is the implemented way to decide which dark/light theme should be loaded based on the user browser's preferences.

![darkmode](https://user-images.githubusercontent.com/11535726/108755526-ac5f8100-7547-11eb-9048-3120e6c2f2d5.gif)

**Comment by antgamdia** [comment]
After several PRs, Kubeapps finally has a dark mode in master and it's ready to be released in the upcoming version! 

:sun_with_face: -->  :new_moon_with_face:

![darkMode](https://user-images.githubusercontent.com/11535726/109964603-2a611c00-7cee-11eb-9997-f3f3d0936e5c.gif)

**Comment by andresmgot** [comment]
Thanks @antgamdia! I have been giving this a try, it looks great :) I have a few notices a few small issues, some of them I am not sure if they are related to the dark mode, the clarity update or they were there from before (sorry if some of them are too picky :P):

1. I would set the background color of the header to the same of the rest of the body to avoid that gap:
![Screenshot from 2021-03-04 13-52-15](https://user-images.githubusercontent.com/4025665/109968759-66e34680-7cf3-11eb-96f4-cf03983feb23.png)

2. The color of the icons and the text in buttons is not consistent. I believe the Clarity guidelines state that the icons should be black in this case.
![Screenshot from 2021-03-04 13-52-30](https://user-images.githubusercontent.com/4025665/109968860-85494200-7cf3-11eb-87e2-451e6d57b368.png)

3. The AceEditor should be set to the dark-mode too.
![Screenshot from 2021-03-04 13-52-47](https://user-images.githubusercontent.com/4025665/109969149-d9ecbd00-7cf3-11eb-9ae8-087641274ab0.png)

(Same for the installation values)
![Screenshot from 2021-03-04 13-54-31](https://user-images.githubusercontent.com/4025665/109969581-5e3f4000-7cf4-11eb-8a98-3ce156282885.png)
 
4. (unrelated to this update) I would remove the "V" from this deployment button, it looks weird
![Screenshot from 2021-03-04 13-52-58](https://user-images.githubusercontent.com/4025665/109969208-ebce6000-7cf3-11eb-9cc4-36fe9ccf5d11.png)

5. The Changes tab needs to be adapted as well
![Screenshot from 2021-03-04 13-53-14](https://user-images.githubusercontent.com/4025665/109969315-0d2f4c00-7cf4-11eb-8728-037b8efdf0c9.png)

6. The Secret table on the top overlaps a bit with the section separator (the example is for bitnami/airflow)
![Screenshot from 2021-03-04 13-54-06](https://user-images.githubusercontent.com/4025665/109969447-34861900-7cf4-11eb-8593-5903e223a59f.png)

7. The tooltip button component should be white now:
![Screenshot from 2021-03-04 13-56-00](https://user-images.githubusercontent.com/4025665/109969689-7911b480-7cf4-11eb-9b2a-bbdbc97f7b78.png)

8. In the deployment form, the slider can overflow a bit its container:
![Screenshot from 2021-03-04 13-57-45](https://user-images.githubusercontent.com/4025665/109969713-7fa02c00-7cf4-11eb-813e-24d322ec061e.png)

9. Not sure why the text here is black (delete modal):
![Screenshot from 2021-03-04 13-58-28](https://user-images.githubusercontent.com/4025665/109969817-9f375480-7cf4-11eb-8e4b-853133ea8763.png)

10. Before, the textareas occupied the whole width. Now they are quite small (apprepo form):
![Screenshot from 2021-03-04 14-05-55](https://user-images.githubusercontent.com/4025665/109969890-b8d89c00-7cf4-11eb-8bcf-e58b8d1829df.png)

11. These two buttons are not aligned:
![Screenshot from 2021-03-04 14-06-54](https://user-images.githubusercontent.com/4025665/109970048-e6254a00-7cf4-11eb-861a-4902e1573d4f.png)

Let me reopen this issue so we can track those ^ I can help adapting some

**Comment by andresmgot** [comment]
another one:

12. In light mode, the search-box text is also white making it unreadable:

![Screenshot from 2021-03-09 13-05-24](https://user-images.githubusercontent.com/4025665/110468209-468eff80-80d8-11eb-99d8-d4b9ef437e23.png)
