### ISSUE TITLE
CI doesn't test deployment to other clusters so it breaks.

### ISSUE THREAD

**Issue by absoludity** [kubeapps/kubeapps#2376]
### Description:

The current CI for Kubeapps does not test deploying to a cluster other than the one on which Kubeapps is installed, so we occasionally get breakage and only find out when trying to create a demo :P.

**Comment by andresmgot** [comment]
I agree but I would much rather cover it with unit tests. Deploying a second cluster and doing a browser test there would be much more slower and prone to flaky environments.

**Comment by absoludity** [comment]
I don't think anyone would argue the related code shouldn't be unit-tested, but this still does not address the situation of "can we deploy to another cluster", in the same way that unit tests for non-multi-cluster code don't obviate the need for CI testing an app release on a single cluster.

We can't test everything during integration, sure, but core functionality like "can I deploy an app to a different cluster from the one on which Kubeapps is installed" is something I think we should consider.
