### ISSUE TITLE
Use optional provision/bind JSON scehma from Service Catalog

### ISSUE THREAD

**Issue by jeremyrickard** [kubeapps/kubeapps#239]
The [Open Service Broker API](https://github.com/openservicebrokerapi/servicebroker/) allows brokers to provide a JSON schema that defines provisioning/update/bind parameters. It would be very nice if Kubeapps could leverage that to provide a nicer screen for creating services instead of simply providing a JSON blob. OpenShift does this and I believe that the Cloud Foundry Apps Manager does as well. This is _optional_ however, so there should be a good fallback. 

Here is an example of the UI in OpenShift: 
![](https://files.slack.com/files-pri/T0Q7631L4-F9ZTM00MU/osba-firewall-x.jpg)

**Comment by prydonius** [comment]
thanks @jeremyrickard for filing, I agree this would be pretty sweet to have!

FYI, for some reason I'm not seeing the OpenShift image you uploaded.

**Comment by jeremyrickard** [comment]
Ahhhh I messed up my original comment with the image! I’ll update it :)

**Comment by mhrivnak** [comment]
+1. I think this is a required feature for service catalog integration to be useful in most cases. I'm not aware of anything else that provides this functionality to Kubernetes users except the OpenShift UI, so it would be very exciting to see it in kubeapps.

I tested the 1.0.0-alpha3 release on minikube with the [Automation Broker](http://automationbroker.io). It was great to see the full list of services provided by our broker rendered in kubeapps, but the form to enter Plan details lacks the ability to provide instance parameters. Most, if not all, of the services available from that broker require parameters to be specified. You can browse the available services here if you're curious: https://hub.docker.com/r/ansibleplaybookbundle/

As an example, the "Development" plan for our [PostgreSQL APB](https://hub.docker.com/r/ansibleplaybookbundle/postgresql-apb/) service class includes this parameter section:

```
$ kubectl get clusterserviceplan 7f4a5e35e4af2beb70076e72fab0b7ff -o yaml

<snip>

  instanceCreateParameterSchema:
    $schema: http://json-schema.org/draft-04/schema
    additionalProperties: false
    properties:
      postgresql_database:
        default: admin
        pattern: ^[a-zA-Z_][a-zA-Z0-9_]*$
        title: PostgreSQL Database Name
        type: string
      postgresql_password:
        pattern: ^[a-zA-Z0-9_~!@#$%^&*()-=<>,.?;:|]+$
        title: PostgreSQL Password
        type: string
      postgresql_user:
        default: admin
        maxLength: 63
        pattern: ^[a-zA-Z_][a-zA-Z0-9_]*$
        title: PostgreSQL User
        type: string
      postgresql_version:
        default: "9.6"
        enum:
        - "9.6"
        - "9.5"
        - "9.4"
        title: PostgreSQL Version
        type: string
    required:
    - postgresql_database
    - postgresql_user
    - postgresql_password
    - postgresql_version
    type: object

<snip>
```

At whatever point this feature becomes available, I'll be eager to test it with the Automation Broker.

**Comment by arapulido** [comment]
@mhrivnak we have a new release of Kubeapps with this new feature. Were you able to test again the AutomationBroker with it?
