### ISSUE TITLE
Enable building customised solutions powered by Kubeapps

### ISSUE THREAD

**Issue by danoo** [kubeapps/kubeapps#2390]

**Comment by antgamdia** [comment]
- [x] Custom translations: 
  - Next: do we want to extend to every string in Kubeapps? or just selected parts (login. etc)?  
- [x] Custom styles:
  - Next: better theming in accordance with Clarity
- [ ] Custom repository filtering when fetching
  - Still to be discussed

**Comment by andresmgot** [comment]
Closing this, we will evaluate a dark mode style in #2371 and custom filtering at https://github.com/kubeapps/kubeapps/issues/1583
