### ISSUE TITLE
Kubeapps on vSphere

### ISSUE THREAD

**Issue by danoo** [kubeapps/kubeapps#2391]

**Comment by absoludity** [comment]
This should just work once we have the pinniped-proxy work released and documented (we're waiting on the image being part of bitnami community catalog).

**Comment by danoo** [comment]
Can we give it a try?

**Comment by absoludity** [comment]
Yep, I'm finding out about access to a vsphere7 k8s cluster.

**Comment by absoludity** [comment]
> This should just work once we have the pinniped-proxy work released and documented (we're waiting on the image being part of bitnami community catalog).

Just confirming this was the case. I tested with the pinniped-proxy that is currently part of the tmc auth extension added to the cluster (currently 0.4) and was able to login and deploy.
