### ISSUE TITLE
Update the interface used for syncing chart data from the DB to an assetsvc API that can be used from other namespaces and clusters

### ISSUE THREAD

**Issue by danoo** [kubeapps/kubeapps#2394]
Update the interface used for syncing chart data from the DB to an assetsvc API that can be used from other namespaces and clusters
Currently the asset sync job requires access to the Kubeapps DB, meaning it can only be securely run in the Kubeapps namespace, see #1647
This same issue stops us from being able to set app repositories on other clusters (#1982)
While there we should update the DB actions to use transactions (or a framework where this comes for free) since many jobs can be posting data to the asset svc.

**Comment by absoludity** [comment]
Thanks - I thought we already had this as an issue, but I see it's only implied from those linked (and described in the multi-cluster doc).

**Comment by absoludity** [comment]
Bringing this into the discussion for next iteration again as it's going to soon be a blocker: If Kubeapps is installed on a specific cluster (such as a shared-services cluster in TKG), then users will only be able to use the app repositories configured with Kubeapps on install. They will be unable to add app repositories and hence unable to use private app repositories etc.

**Comment by ppbaena** [comment]
To be closed as the new approach for package repositories API is in progress in #3496
