### ISSUE TITLE
Unable to see available helm charts from harbor repo in kubeapps

### ISSUE THREAD

**Issue by gkulkarni32** [kubeapps/kubeapps#2410]
### Steps to reproduce the issue:

1. Set up kubeapps on the cluster using kubeapps helm chart
2. Go to 'Configuration -> App Repository', try to add a new repository. I used the VMware corporate harbor repo link and provided user/credentials. 
3. I can now see the corporate harbor as a repo in kubeapps'
4. When i try to search for the catalog for the corporate harbor repo, it does not show any charts i have uploaded. 

### Describe the results you received:

Able to add the corporate harbor repository, but the uploaded helm charts are not seen in kubeapps catalog.

### Describe the results you expected:

Expected to see the helm chart i have uploaded in corporate harbor in kubeapps after the repository was added. 

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"dirty", GoVersion:"go1.15.5"}
```

- Output of `helm list -n <kubeapps-namespace> <kubeapps-release-name>`:

```
NAME    	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART         	APP VERSION
kubeapps	kubeapps 	1       	2021-02-10 16:37:43.436933 +0530 IST	deployed	kubeapps-5.1.0	2.1.0    
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.14+vmware.1", GitCommit:"bbf52cd6cf83a50507e943b717ed321d383a37b5", GitTreeState:"clean", BuildDate:"2020-08-19T23:48:38Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by andresmgot** [comment]
hi @gkulkarni32, you should be able to see the `sync` job in the `kubeapps` namespace. You can retrieve the logs from there to get more information if the sync is failing:

```
kubectl logs -n kubeapps apprepo-<namespace>-sync-<repo_name>-...
```

Are you able to see any error in that job?

**Comment by gkulkarni32** [comment]
Yes, i see an error: 
```time="2021-02-17T02:52:49Z" level=error msg="lastChecksum: "
time="2021-02-17T02:52:49Z" level=fatal msg="error unmarshaling JSON: json: cannot unmarshal string into Go value of type repo.IndexFile"```

**Comment by gkulkarni32** [comment]
Thanks for the pointer to the job that syncs the repository. There was an issue with the url to the chartrepo. This is resolved now.
