### ISSUE TITLE
kubeapps installation error.

### ISSUE THREAD

**Issue by robertbovens** [kubeapps/kubeapps#2452]
### Description:

I am unable to install kubeapps,

### Steps to reproduce the issue:

helm3 repo add bitnami https://charts.bitnami.com/bitnami
helm3 repo update
helm3 install kubeapps --namespace kubeapps bitnami/kubeapps

### Describe the results you received:

I received the following error and am not able to install kubeapps:

Error: parse error at (kubeapps/charts/postgresql/charts/common/templates/_secrets.tpl:84): function "lookup" not defined

### Describe the results you expected:

Installation of kubeapps

### Additional information you deem important (e.g. issue happens only occasionally):

 Ubuntu 18.04.5 LTS

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}

```

- Output of `helm list -n <kubeapps-namespace> <kubeapps-release-name>`:

```
helm3 list -n kubeapps
NAME    NAMESPACE       REVISION        UPDATED STATUS  CHART   APP VERSION

```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.2-34+350770ed07a558", GitCommit:"350770ed07a558ba1ce8202a6f9ea849f9a75f06", GitTreeState:"clean", BuildDate:"2021-02-11T20:09:31Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.2-34+350770ed07a558", GitCommit:"350770ed07a558ba1ce8202a6f9ea849f9a75f06", GitTreeState:"clean", BuildDate:"2021-02-11T20:10:29Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by absoludity** [comment]
Hi Robert. The postgres chart which Kubeapps depends on has been updated and uses a newer helm feature: the lookup function (as much as I personally dislike it :P).

Anyway, this should work fine if you update your helm 3 client (it's quite old: v3.0.2 is from Dec 2019).

Though I think that will fix your problem, we should update the minimum Helm version of our chart if we're depending lookup. Thanks.

**Comment by robertbovens** [comment]
I use ubuntu 18.04.05 so its bundled with it, and i don't see i can just upgrade helm for it.  Already did a update of all the packages i can update. Not sure if it will give the same problem with the newer version of ubuntu 20. I run it in vm`s and already have the 20 installed just didnt try it yet or i did but i dont remember. But it should work even with the lts release of ubuntu 18.04.5

**Comment by andresmgot** [comment]
Hi @robertbovens, I am not sure how often the package is updated in Ubuntu repositories. I recommend you to use their GitHub release to get the latest bug and security fixes: https://github.com/helm/helm/releases

**Comment by robertbovens** [comment]
I tried it on ubunto 20.04 but i get the same version of helm3. Just to verify i run the same commands on ubuntu 20.04.2 LTS and get the same result, so a bit dissapointing. I run in this problem earlier with other charts, and thought there were errors with the charts. So to satisfy my mind i will do the same thing with a newer version of helm3 with other install of kubernetes, just in case.\

Best regards,

Robert

**Comment by andresmgot** [comment]
Unfortunately, there is not much we can do here ([we require Helm > 3.1](https://github.com/kubeapps/kubeapps/blob/master/docs/user/getting-started.md#prerequisites)). My recommendation is to contact the package mantainers to update its version or directly downloading the `helm` binary from its release page.

Let us know if we can help with something else,
