### ISSUE TITLE
Service Catalog Chart needs an icon

### ISSUE THREAD

**Issue by sebgoa** [kubeapps/kubeapps#246]
that would be nice

**Comment by prydonius** [comment]
Thanks @sebgoa, I agree it would be nice! However this is really more an issue for upstream (https://github.com/kubernetes-incubator/service-catalog/). Can you file the issue there?

**Comment by prydonius** [comment]
Closing since this doesn't require any changes on Kubeapps' side. Once the upstream chart gets an icon, it will automatically be imported and shown in Kubeapps.
