### ISSUE TITLE
fix security vulnerability in extracting chart tarballs

### ISSUE THREAD

**Issue by prydonius** [kubeapps/kubeapps#248]
See kubernetes/kubernetes#61297, the solution is to use https://github.com/cyphar/filepath-securejoin to ensure the path is within context.

See fix in Helm: kubernetes/helm#3898

Since the chart-repo cmd doesn't actually store tarballs in the filesystem, we may not actually be vulnerable to this.

**Comment by prydonius** [comment]
I believe we're not vulnerable as we process the tarball in-memory and look for matches in paths (so we wouldn't pick up any files with `..` paths in them. https://github.com/kubeapps/kubeapps/blob/master/cmd/chart-repo/utils.go#L371

**Comment by sameersbn** [comment]
yea.. kubeapps seems to be safe from this vulnerability.
