### ISSUE TITLE
Swagger/OpenAPI documentation

### ISSUE THREAD

**Issue by mcwienczek** [kubeapps/kubeapps#2495]
Is there a possibility to generate OpenAPI documentation from the services? I would like to develop a custom frontend that integrates with kubeapps over REST API.

**Comment by antgamdia** [comment]
We already have an initial version of the API docs here: https://github.com/kubeapps/kubeapps/blob/master/dashboard/public/openapi.yaml

Once Kubeapps is installed, you can find the interactive documentation on the right panel:

![image](https://user-images.githubusercontent.com/11535726/109808136-0ab2f080-7c27-11eb-8c94-8efb0f556ac6.png)

**Comment by mcwienczek** [comment]
Thank you very much for help!

**Comment by antgamdia** [comment]
Great, if you need further assistance, drop another issue or reach us on the [Slack community channel](https://kubernetes.slack.com/messages/kubeapps). Looking forward to seeing what you build :)
