### ISSUE TITLE
OLM : Catalog available in Kubeapps GUI

### ISSUE THREAD

**Issue by yeplaa** [kubeapps/kubeapps#2513]
### Description:

I would like know if the specific OLM Catalog (loaded by Catalogsource ressource) are loaded into Kubeapps GUI or if it's possible to load only Operatorhub.io catalog? 

Thanks for your help

**Comment by andresmgot** [comment]
Hi,

At this moment, the only supported catalog that is supported is the one that OLM installs by default (tihs is the catalog behind operatorhub.io).

**Comment by yeplaa** [comment]
Thanks @andresmgot   Is the new feature is planned in short time or isn't it planned yet?

**Comment by yeplaa** [comment]
Thanks for your reply @andresmgot
