### ISSUE TITLE
Giltab OCI Registry configuration

### ISSUE THREAD

**Issue by muthurajr** [kubeapps/kubeapps#2548]
### Description:

I'm trying to configure Gitlab OCR registry for the charts. Gitlab registry listing is accessible using below.
```
curl --header "PRIVATE-TOKEN: **********" "https://gitlab.com/api/v4/projects/*********/registry/repositories"
```
How should we configure the APP Repository, and the Gitlab docker registry configuration?

This is not clear in the documentation:
```
curl -X GET "https://harbor.domain/api/v2.0/projects/my-oci-registry/repositories" -H "accept: application/json" | jq 'map(.name) | join(", ")'
Note: Substitute the domain harbor.domain and the project name my-oci-registry with your own. Also, if the repository is not public, you can use -u username:password to retrieve the same list.
```

### Steps to reproduce the issue:

1. Refer https://gitlab.com/msvechla/alertmanager-bot-helm as an example for Helm chart registry in Gitlab

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}
```

- Output of `helm list  --namespace kubeapps `:

```
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
kubeapps        kubeapps        1               2021-03-12 17:57:13.341106035 +0000 UTC deployed        kubeapps-5.3.0  2.2.1
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1
.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.15-gke.800", GitCommit:"fa6f8f9671a3ba4b1790bac677bb72b04204e8fc", GitTreeState:"clean", BuildDate:"2020-12-21T09:19:13Z", GoVe
rsion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by absoludity** [comment]
Hi there. 

Note that the [specific part of the documentation to which you are referring](https://github.com/kubeapps/kubeapps/blob/master/docs/user/private-app-repository.md#oci-registry) is just a `curl` command to obtain a list of repositories in the registry that works with Harbor (part of the harbor API). You don't need to (and can't) use that with gitlab (and I'm not sure that gitlab has a similar endpoint).

All you should need to do is to (manually) list the repository names that you want to make available in kubeapps in the "List of repositories" text box. I assume, based on your Curl, that you're also specifying "Bearer token" for authorization too.
