### ISSUE TITLE
some chart templates don't implement securityContext

### ISSUE THREAD

**Issue by Morriz** [kubeapps/kubeapps#2552]
### Description:

We are using chart with `appVersion: 2.2.1` and see errors when deploying the chart as is. 

```
templates/tests/test-assetsvc.yaml - Policy: psp-allowed-users - Container kubeapps-assetsvc-test is attempting to run without a required securityContext/runAsUser. Allowed runAsUser: {"rule": "MustRunAsNonRoot"}
templates/tests/test-dashboard.yaml - Policy: psp-allowed-users - Container kubeapps-dashboard-test is attempting to run without a required securityContext/runAsUser. Allowed runAsUser: {"rule": "MustRunAsNonRoot"}
```

These templates don't seem to implement `securityContext`.

**Comment by andresmgot** [comment]
Those are the chart tests @Morriz, they are not meant to be run in production. They don't really get installed in your cluster unless you execute `helm test <kubeapps_release>`.

**Comment by Morriz** [comment]
What do you mean these tests should not be run in production? I thought they are used to provide feedback to helm wether a service is up or not, otherwise fail the deployment.

**Comment by Morriz** [comment]
Anyway, it would be beneficial to also patch these two tests with this snippet:
```yaml
      {{- if .Values.securityContext.enabled }}
      securityContext: {{- omit .Values.securityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
```

**Comment by andresmgot** [comment]
> What do you mean these tests should not be run in production? I thought they are used to provide feedback to helm wether a service is up or not, otherwise fail the deployment.

Not really, you don't need to run those. It's just for us to give early feedback (or fail early) if we introduce a breaking change in a PR or something.

> Anyway, it would be beneficial to also patch these two tests with this snippet:
> 
> ```yaml
>       {{- if .Values.securityContext.enabled }}
>       securityContext: {{- omit .Values.securityContext "enabled" | toYaml | nindent 8 }}
>       {{- end }}
> ```
> 
> It works fine and makes it conform.

I agree, we can add that. Would you mind sending a PR with that?

**Comment by Morriz** [comment]
Sure. Coming up

**Comment by Morriz** [comment]
See https://github.com/kubeapps/kubeapps/pull/2560
