### ISSUE TITLE
Enforce / customize helm release name

### ISSUE THREAD

**Issue by Siegfriedk** [kubeapps/kubeapps#2570]
### Description:

Currently we use kubeapps to provide a simple way for creating jenkins instances. This currently leads to the issue, that in one namespace there are like 15 kubeapp apps where 50% have a meaningful release name (team name, product, usecase) and the rest are not (added screenshot which doesn't reflect this ratio but it fluctuates)

We also use the values.yaml in a way that all critical options and values are at the top and we leverage yaml templating to group settings in 'profiles'.

We already have values in your values.yaml you need to configure and it would make sense for us to:
Either enforce entering a release name and not having the option to autogenerate it at all
OR
to build/configure the release name by ourselfs through the helm chart / values.yaml

I just checked out the new forms feature (totally looking forward to this! :D ) and it would be great if that would work with those forms as well.

One thing which makes it also hard is that in the overview of installed apps, you can't see who created which instance but we do use custom tokens for everyone.

### Steps to reproduce the issue:

Create many instances of one application

### Describe the results you received:

A mess as one namespace contains only one application type (jenkins), and the only differentiater besides the helm release name, is the chart version.

### Describe the results you expected:

An easy overview page which is customer focused and allows a customer to see their applications.

### Version of Helm, Kubeapps and Kubernetes:

Kubeapps 2 ( 2.0.1 )

![Screen Shot 2021-03-18 at 11 38 30](https://user-images.githubusercontent.com/47592287/111614693-2817bb00-87e0-11eb-808b-3a85144b196b.png)

**Comment by andresmgot** [comment]
Thanks @Siegfriedk,

I see, it may makes sense to allow to disable the auto-generated name (in fact, that's the default for Helm 3). We can add a configuration option for that.

> I just checked out the new forms feature (totally looking forward to this! :D ) and it would be great if that would work with those forms as well.

You mean the recently-merged custom form components? I am curious, can you elaborate how you would use them?

> One thing which makes it also hard is that in the overview of installed apps, you can't see who created which instance

Yes. That's tracked as part of https://github.com/kubeapps/kubeapps/issues/2393 and we plan to start working on that soon.

> but we do use custom tokens for everyone.

We don't recommend using tokens for running Kubeapps in production. The recommended setup is using OIDC: https://github.com/kubeapps/kubeapps/blob/master/docs/user/using-an-OIDC-provider.md

**Comment by Siegfriedk** [comment]
Hi @andresmgot,


> You mean the recently-merged custom form components? I am curious, can you elaborate how you would use them?

I saw it more in the context of basic form components. I was not aware that there is also a custom form components.

What we do right now, which is probably a similar pattern on what the form components do, is to sort values in values.yaml to the top and use profiles. It looks like this:

![Screen Shot 2021-03-18 at 14 32 16](https://user-images.githubusercontent.com/47592287/111634748-1988ce00-87f7-11eb-8732-6e9f1930df62.png)


With more control over the release name OR over what is shown on the Applications page, it would make it much easier to understand who created a jenkins/app for what and how.

My mentioning of forms was meant like a side note on forms as i assume forms have the same issue.


> > but we do use custom tokens for everyone.
> 
> We don't recommend using tokens for running Kubeapps in production. The recommended setup is using OIDC: https://github.com/kubeapps/kubeapps/blob/master/docs/user/using-an-OIDC-provider.md

We use gke and don't want to give our customers access to our GCP environment; Therefore we need to create tokens manually for that specific namespace; 

We tried to do it differently but failed and i have to recheck again what the outcome was:
https://github.com/kubeapps/kubeapps/issues/2154
https://github.com/kubeapps/kubeapps/issues/2119

**Comment by absoludity** [comment]
> > > but we do use custom tokens for everyone.
> > 
> > 
> > We don't recommend using tokens for running Kubeapps in production. The recommended setup is using OIDC: https://github.com/kubeapps/kubeapps/blob/master/docs/user/using-an-OIDC-provider.md
> 
> We use gke and don't want to give our customers access to our GCP environment;

Right, I was going to say that you can use access tokens with gke, but yes, it'll mean users will need to be able to auth via accounts.google.com and have access to the GCP account.

> Therefore we need to create tokens manually for that specific namespace;
> 
> We tried to do it differently but failed and i have to recheck again what the outcome was:
> #2154
> #2119

pinniped won't yet help you, but they are working towards supporting gke and other hosted services with their 0.7.0 release which we'll aim to support shortly thereafter.
