### ISSUE TITLE
Deployment template spec with 'imagePullSecrets' fails to deploy

### ISSUE THREAD

**Issue by daviesian** [kubeapps/kubeapps#2634]
### Description:

When deploying a custom chart that includes `imagePullSecrets` in a Deployment template spec, I get a long stack trace from Kubeapps:

```
An error occurred: PANIC: interface conversion: interface {} is []interface {}, not []map[string]interface {} goroutine 18808 [running]: 
github.com/urfave/negroni.(*Recovery).ServeHTTP.func1(0x7efde834b300, 0xc00087e978, 0xc00062e500, 0xc000924900) 
/bitnami/blacksmith-sandox/kubeapps-kubeops-2.3.0/pkg/mod/github.com/urfave/negroni@v1.0.0/recovery.go:159 +0xcb panic(0x1aa2bc0, 0xc000a36b10) 
/usr/local/go-1.13.5/src/runtime/panic.go:679 +0x1b2 
github.com/kubeapps/kubeapps/pkg/agent.(*DockerSecretsPostRenderer).updatePodSpecWithPullSecrets(0xc00087f2e0, 0xc000a365d0) 
/bitnami/blacksmith-sandox/kubeapps-kubeops-2.3.0/src/github.com/kubeapps/kubeapps/pkg/agent/docker_secrets_postrenderer.go:155
...
```

If I remove the `imagePullSecrets` from the template spec, the error goes away (although of course then I can't pull my images!), so that is definitely the source of the problem. The spec looks like this:

```yaml
...
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
...
```

The error appears to be [this line in docker_secrets_postrenderer.go](https://github.com/kubeapps/kubeapps/blob/master/pkg/agent/docker_secrets_postrenderer.go#L155), which tries to type cast the list of objects (`[]interface {}`) to a `[]map[string]interface{}`, and fails. I'm afraid Go is nowhere near the top of the list of languages I'm comfortable with, so I can't offer much more insight than that. I apologise if I'm misunderstanding something fundamental.

It's important to note that this Helm chart installs perfectly from the command line using `helm install ...`, so I believe my Deployment template spec is correct. The spec is also not templated, so this has nothing to do with parameters specified in `values.yaml` or elsewhere.

### Steps to reproduce the issue:

1. Create a helm chart, specifying `imagePullSecrets` for a Deployment template spec.
2. Push that chart to a helm registry
3. Add the registry to KubeApps
4. Attempt to deploy the chart.
5. Receive error

### Describe the results you received:

Stacktrace above

### Describe the results you expected:

Deployment to proceed

### Additional information you deem important (e.g. issue happens only occasionally):

* If `imagePullSecrets` is not specified in Deployment template spec, KubeApps deployment proceeds normally.
* It makes no difference whether `imagePullSecrets` is templated and loaded from `values.yaml` or not.
* The chart can be deployed via `helm install` on the command line just fine.

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}
```

- Output of `helm list -n <kubeapps-namespace> <kubeapps-release-name>`:

```
$ helm list -n kubeapps
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
kubeapps        kubeapps        1               2021-03-27 21:34:45.846049072 +0000 UTC deployed        kubeapps-5.5.0  2.3.0
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:10:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:02:01Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by andresmgot** [comment]
Hi @daviesian,

I can see the error, I will patch it soon. In the meantime, do you know that you can associate an imagePullSecret to a repository and Kubeapps will automatically inject it (without having to modify the chart just for that)? See: https://github.com/kubeapps/kubeapps/blob/master/docs/user/private-app-repository.md#associating-docker-image-pull-secrets-to-an-apprepository

**Comment by daviesian** [comment]
Hi @andresmgot,

Thanks for confirming the problem. I'm aware of the (great) Kubeapps feature to inject an `imagePullSecret`, and that's what I'm using as a workaround, but sadly I need to develop the Helm chart to work for people who don't use Kubeapps as well as for those who do.

Please let me know if there's anything I can do to help develop or test the fix - I would be happy to contribute in any way I can if you point me in the right direction. But I appreciate that it might be more effort to do that than to fix it yourself!

**Comment by andresmgot** [comment]
Hi @daviesian, this should be fixed by #2641, can you verify it that works for you? The CI has built a dev image that you can try:

```
kubectl set image -n kubeapps deployment/kubeapps-internal-kubeops kubeops=kubeapps/kubeops-ci:build-5e262f23379550f544431dcb386b609f29e457cc
```

**Comment by daviesian** [comment]
Hi @andresmgot,

Yes, that works perfectly, thank you! And thank you for including the `kubectl` command, that would have taken me hours to get right on my own.

It looks like you have releases every week or two, so I assume this fix will be rolled into the next one?

**Comment by andresmgot** [comment]
:+1: thanks for confirming, yes, this will be included in the next release.
