### ISSUE TITLE
Inappropriate random names

### ISSUE THREAD

**Issue by alex-vukov** [kubeapps/kubeapps#2649]
Your random name generator sometimes creates inappropriate names. I really appreciate the fun but I was showing a demo to a VP in my company and the generated name was "racial-disgust" which was a bit awkward to say the least...
You can see what I am talking about in your video https://www.youtube.com/watch?v=MHylHSDJqvc&t=150s where you have "poor-wash"

**Comment by andresmgot** [comment]
Hi @alex-vukov,

I am really sorry to hear that. That kind of names are unacceptable. We rely in the library `moniker-native` to generate random names but taking a deeper look to the default dictionary there, there are several names and adjectives that are inappropriate (and go against our [code of conduct](https://github.com/kubeapps/kubeapps/blob/master/CODE_OF_CONDUCT.md)).

We will remove that library from the project (and evaluate if the random generation is even necessary or useful). Thank you for reporting the issue!

**Comment by antgamdia** [comment]
Totally agree; thank you for reporting it. We are going to work on getting rid of it.
However. let me close this issue in favor of https://github.com/kubeapps/kubeapps/issues/2570, to avoid duplicates.
