### ISSUE TITLE
CI Error: Execution context was destroyed, most likely because of navigation

### ISSUE THREAD

**Issue by andresmgot** [kubeapps/kubeapps#2653]
### Description:

This error is quite frequent in CI builds:

![Screenshot from 2021-04-07 09-57-37](https://user-images.githubusercontent.com/4025665/113831353-cc5da380-9787-11eb-9839-0ee066b50bae.png)

We should address it. Apparently is related to the login workflow with Dex.

### Steps to reproduce the issue:

Examples: 

https://app.circleci.com/pipelines/github/kubeapps/kubeapps/2683/workflows/c4f589b3-8299-49ae-ab03-16c058d85505/jobs/43208
https://app.circleci.com/pipelines/github/kubeapps/kubeapps/2683/workflows/8a160663-ef5f-4822-a069-0f58ea2852c5/jobs/43207

**Comment by antgamdia** [comment]
Should be solved by #2651 , but let's hold it under the "review" column until some more builds get executed.

**Comment by antgamdia** [comment]
Nope, it still fails... https://app.circleci.com/pipelines/github/kubeapps/kubeapps/2675/workflows/e5dbeed8-e5a0-4c92-93ce-bff5af3d2524/jobs/43241/artifacts   :sob:

**Comment by andresmgot** [comment]
the build that you point didn't include your fix yet, so maybe this is already fixed

**Comment by andresmgot** [comment]
I haven't seen the error again so we can assume this has been fixed :)
