### ISSUE TITLE
Issue with Kubeapps and Chartmuseum

### ISSUE THREAD

**Issue by prydonius** [kubeapps/kubeapps#269]
ChartMuseum uses relative URLs in the repo index and this doesn't seem to be working properly in Kubeapps. The charts from the repo show up fine within Kubeapps, but Helm CRD controller doesn't seem to handle relative URLs in the index correctly:

```
2018/04/24 15:22:07 Downloading https://kubernetes-charts.storage.googleapis.com/chartmuseum-1.3.1.tgz ...
2018/04/24 15:22:07 Downloaded https://kubernetes-charts.storage.googleapis.com/chartmuseum-1.3.1.tgz to /helm/cache/archive/chartmuseum-1.3.1.tgz
2018/04/24 15:22:07 Installing release default-chartmuseum into namespace default
2018/04/24 15:22:08 Installed/updated release default-chartmuseum (status DEPLOYED)
2018/04/24 15:29:06 Downloading charts/seanmeme-0.1.1.tgz ...
2018/04/24 15:29:06 Error updating default/seanmeme, will retry: repo charts not found
```

For my custom chart from chartmuseum, it tries to download `charts/seanmeme...` instead of the absolute URL.

cc @sameersbn this might be fix by your upcoming changes.

**Comment by sameersbn** [comment]
@prydonius Yes, I the PR was fixed today to support this case.

**Comment by kumarinfo90** [comment]
Can someone please explain what ChartMuseum is?

If i have written any custom helm chart , i can able to push it to kubeapps from their i can able to access when/where i want right.
Then what is the need for ChartMuseum ?
Please correct me if i am wrong.

Thanks,

**Comment by andresmgot** [comment]
Hi @kumarinfo90,

ChartMuseum is a Helm registry, you can store Helm charts there.

Kubeapps is a web interface for deploying and maintaining charts. It's functionality is similar to the `helm` CLI. In other words, you can use Kubeapps to deploy charts that you have stored in ChartMuseum.

Hope that clarifies it to you,
