### ISSUE TITLE
Standardize chart workflow

### ISSUE THREAD

**Issue by antgamdia** [kubeapps/kubeapps#2704]
Since we are explicitly making the [Kubeapps bitnami chart](https://github.com/bitnami/charts/tree/master/bitnami/kubeapps) the official one so that they can add the proper standardization features and perform improvements on their own, we need first to accomplish:

### Kubeapps end
- [x] Release the upcoming version with the current approach
- [x] Revisit our user docs to explicitly state that we are using the Bitnami chart, so the internal one is just for development purposes, with no support.
- [x] Remove any automagic step with regards to the Bitnami chart 
  - [x] CI steps?
  - [x] ./scripts folder?
- [x] Update our dev docs to match the current release process
- [x] Chart automatic syncing (merged - https://github.com/kubeapps/kubeapps/pull/2754)
- [x] Merge the bitnami changes in our dev chart (merged - https://github.com/kubeapps/kubeapps/pull/2795)

### Bitnami end
- [x] Review the Bitnami chart PR (ongoing - https://github.com/bitnami/charts/pull/6301)
- [x] Check whether the tests in the bitnami pipeline can or should be updated or are fine as they are ( https://github.com/kubeapps/kubeapps/issues/2704#issuecomment-833394288)

**Comment by antgamdia** [comment]
For these early stages, we can perform the PR process manually, but, what if we change the current `sync_chart` CI job to make use of the GitHub CLI to send an automatic PR to the bitnami/chart repo?

https://cli.github.com/manual/gh_pr_create

**Comment by absoludity** [comment]
> For these early stages, we can perform the PR process manually, but, what if we change the current `sync_chart` CI job to make use of the GitHub CLI to send an automatic PR to the bitnami/chart repo?
> 
> https://cli.github.com/manual/gh_pr_create

Possibly. Will we want to create a PR for each change to the chart? IMO there will be some changes that we do want a PR for immediately (together with a chart point release), such as a bug fix in the chart, and others that we don't (such as feature work going on in devel). Up until now, we've always just done a chart release with whatever is in our main branch when we bump the chart version, and perhaps that's OK to continue for now, but I do wonder whether we'll eventually need to use a release branch to better manage changes. Let's see.

**Comment by antgamdia** [comment]
>  but I do wonder whether we'll eventually need to use a release branch to better manage changes

Yep, absolutely! I just mentioned the continuous-PR approach so that we preserve the same behavior as we just had. 
However, as part of the branch renaming we should do at some point, perhaps we can leave master/main as a release branch and operate with a develop branch, even following a gitflow approach (or similar ones).

**Comment by antgamdia** [comment]
As per the offline discussion:

Chart syncing:

- **Bitnami-->Kubeapps**: add a CI job that analyzes the differences between their chart and ours (ignoring images). Create a PR on our side or just fail the job would be OK (likely we won't that kind of changes so often, so no need of performing a thorough reconciliation).
- **Kubeapps-->Bitnami**: add a CI job (on release, not on master) that creates a PR in their side with the changes (ignoring images)

**Comment by antgamdia** [comment]
>  Check whether the tests in the bitnami pipeline can or should be updated or are fine as they are.

AFAIK, their testing approach is threefold:

- Testing e2e functionality:
  - Login page is working
    - Has login title and token input
  - Login/logout
    - Has login title and token input
    - Enter token
    - Has menu
    - Click on logout
    - Has login title and token input
   - Add repo
     - Login
     - Has menu
     - Click on Application Repositories
     - Add repo name and repo url
     - Click on add repo
     - Check the repo is added (just in the app repo view, not checking if there is actual content in there)
     - Logout
   - Check added repo
     - Login
     - Go to the catalog
     - Check if the app is present
     - Logout
  - Deploy chart
    - Login
    - Go to the catalog
    - Click on the app
    - Click on versions
    - Add a deployment name
    - Click on deploy
    - Has deploy name and has "ready"
    - Logout
  - Check deployed chart
    - Login
    - Go to applications
    - Type the deployment name in searchbox
    - Page has this deployment name
    - Logout
  - Upgrade chart
    - Login
    - Go to the deployment app page
    - Has "ready"
    - Click on upgrade
    - Increase replicas
    - Click on upgrade
    - Has deploy name and "ready"
    - Logout
- Testing other dashboard aspects:
  - Nginx is serving the static files in `static`, for instance, the `manifest.json'`.
  - Nginx is serving the app (200 OK) and it contains "You need to enable JavaScript to run this app"
  - Nginx binary is OK and HTTP_PROXY is disabled
 - Testing the rest of the services:
   - Has an executable binary `apprepository-controller`
   - Has an executable binary `asset-syncer`
   - **There is NO test for `kubeops`**
   - Has an executable binary `kubeapps-pinniped-proxy` and `--help` works.


So, as far as I can tell, the test suite is enough (combined with ours) to test the basic core functionality, nonetheless, it could be improved by:

1. Adding a "rollback application" e2e test case (as per #2762 ).
2. Adding a simple test for the Kubeops binary
3. Testing at least a simple command in the rest of the binaries, for instance, the  `--help`.

See what you think @absoludity , cc @juan131

**Comment by absoludity** [comment]
So it looks like e2e tests were added in the pipeline at a certain point-in-time based on what we had in our repo. If that's the case, I'm not sure why the pipeline is not instead using our e2e tests (so they're updated as we add more, like rollback that you've mentioned, or testing with multicluster+OIDC as we have today). I don't remember if I brought this up at the time they were added to the pipeline.

Anyway, +1 to not block on this at the moment, looks like there is decent coverage. Longer term, it seems like our integration tests in our repo belong with the chart and should be updated in the pipeline when we update the chart.

**Comment by antgamdia** [comment]
Closing as it is finally done :tada:  after merging https://github.com/kubeapps/kubeapps/pull/2795 and performing a few changes in the CI.
