### ISSUE TITLE
dashboard doesnt display charts 

### ISSUE THREAD

**Issue by itsecforu** [kubeapps/kubeapps#2710]
Loading takes forever - the wheel spins forever on the tabs of the catalog and applications 

pods looks ok:

```
kubectl -n kubeapps get pods
NAME                                                          READY   STATUS      RESTARTS   AGE
apprepo-kubeapps-sync-bitnami-1619165400-8b8xn                0/1     Completed   0          23m
apprepo-kubeapps-sync-bitnami-1619166000-rqs79                0/1     Completed   0          7m59s
apprepo-kubeapps-sync-bitnami-1619166600-9pqtf                0/1     Completed   0          3m43s
apprepo-kubeapps-sync-bitnami-f72qx-2tpfj                     0/1     Completed   1          30m
kubeapps-7ffc9c78bf-22868                                     1/1     Running     0          30m
kubeapps-7ffc9c78bf-4xxd2                                     1/1     Running     0          30m
kubeapps-internal-apprepository-controller-6cd9b9b9cb-fv4xw   1/1     Running     0          30m
kubeapps-internal-assetsvc-5dd4d86d9-62m6b                    1/1     Running     0          30m
kubeapps-internal-assetsvc-5dd4d86d9-v45rf                    1/1     Running     0          30m
kubeapps-internal-dashboard-9787f4448-kvw7v                   1/1     Running     0          30m
kubeapps-internal-dashboard-9787f4448-ldk8d                   1/1     Running     0          30m
kubeapps-internal-kubeops-8446b55554-4d8s2                    1/1     Running     0          30m
kubeapps-internal-kubeops-8446b55554-mt42k                    1/1     Running     0          30m
kubeapps-postgresql-primary-0                                 1/1     Running     0          30m
```

curl works:
```
kubectl -n kubeapps exec kubeapps-7ffc9c78bf-22868 -- curl -Is https://charts.bitnami.com
HTTP/2 200
content-type: text/html
content-length: 409
last-modified: Fri, 17 Jul 2020 12:00:51 GMT
x-amz-server-side-encryption: AES256
x-amz-version-id: VPAmiLE04jn.n5.RD9finskK0DqJIvgI
accept-ranges: bytes
server: AmazonS3
date: Thu, 22 Apr 2021 09:40:21 GMT
etag: "d44f63b2f18863fb99f08ec3403d5c8a"
x-cache: Hit from cloudfront
via: 1.1 b5b008573eab794a3818bb6b76b0a164.cloudfront.net (CloudFront)
x-amz-cf-pop: HEL50-C1
x-amz-cf-id: VYqdOPgpnfihvLO8WGe-zX5f4mzKsZ9xDNReyGs29mm6QFyQQwsCzQ==
age: 82430
```

**Comment by antgamdia** [comment]
Hi, sorry to hear that. Let's try to find out what's wrong:
first of all, could you share the versions you're using:


- Output of `helm version`:

- Output of `helm list -n <kubeapps-namespace> <kubeapps-release-name>`:

- Output of `kubectl version`:

Next, could you please share a screenshot of your preferred browser developer console (e.g, [chrome](https://developer.chrome.com/docs/devtools/network/reference/)), so that we can see which HTTP requests are going wrong?

You should see something like: `https://<your_url>/api/assetsvc/v1/clusters/default/namespaces/default/charts?page=1&size=20`, no?

**Comment by absoludity** [comment]
> curl works:
> 
> ```
> kubectl -n kubeapps exec kubeapps-7ffc9c78bf-22868 -- curl -Is https://charts.bitnami.com
...
> ```

Note that this curl isn't so relevant, in that the dashboard isn't getting that URL. Rather, it's the URL used by the sync jobs that you've included in your first paste to populate Kubeapps' cache (in postgresql), which is what is queried by the frontend (the URL that Antonio suggested you should see).

**Comment by itsecforu** [comment]
Thx for feedback!

helm:
```
 helm version
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547c                                                                                      f05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}

```
kubeapps:

```
helm list -n kubeapps
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
kubeapps        kubeapps        1               2021-04-23 11:03:10.045945364 +0300 MSK deployed        kubeapps-6.0.1  2.3.1
```


kubectl:

```
 kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```
screenshoot:  

![alt text](https://itsecforu.ru/wp-content/uploads/2021/04/kubeapps-err.png)

**Comment by antgamdia** [comment]
Thanks for the logs! Could you please share another screenshot with the `Network` tab open? 
This 404 you see is totally normal as you probably don't have any OLM installed.

Edit: I've just seen the new image, please take another one with the catalog, not the application view, so that we can see which requests are going wrong.

**Comment by itsecforu** [comment]
Is it?

![alt text](https://itsecforu.ru/wp-content/uploads/2021/04/kubeaapp.png)

**Comment by antgamdia** [comment]
Yes, thank you.

> Loading takes forever - the wheel spins forever on the tabs of the catalog and applications

So, it seems now works, isn't it? The catalog is being properly loaded without the endless spinner as far as a can see in the picture.

If you still are facing this issue, could you please elaborate a little bit more? Thanks!

**Comment by itsecforu** [comment]
part is loaded, and under them the spinner continues to work

**Comment by antgamdia** [comment]
Well, the "good" news is that the UI is working properly, as it tries to load the next page (the catalog is paginated, so, once you scroll down, it will try to fetch new charts).

Have a look at the logs and let us know if you see some error there:

It seems nginx is crashing somehow and, therefore, the requests will end up in a 502 since they cannot be properly routed. Let's find what's causing this crash.

```
kubectl logs -n kubeapps deployment/kubeapps nginx
kubectl logs -n kubeapps deployment/kubeapps auth-proxy
kubectl logs -n kubeapps deployment/kubeapps pinniped-proxy

kubectl logs -n kubeapps deployment/kubeapps-internal-assetsvc 
kubectl logs -n kubeapps deployment/kubeapps-internal-kubeops
```

**Comment by itsecforu** [comment]
nginx - these two errors are duplicated 


```
2021/04/28 11:05:58 [error] 25#25: *133763 recv() failed (110: Connection timed out) while reading response header from upstream, client: 127.0.0.1, server: _, request: "GET /api/assetsvc/v1/clusters/default/namespaces/default/charts/categories HTTP/1.1", upstream: "http://10.233.31.241:8080/assetsvc/v1/clusters/default/namespaces/default/charts/categories", host: "10.2.27.11:8085", referrer: "http://10.2.27.11:8085/"
2021/04/28 11:05:58 [error] 25#25: *133717 recv() failed (110: Connection timed out) while reading response header from upstream, client: 127.0.0.1, server: _, request: "POST /api/v1/clusters/default/can-i HTTP/1.1", upstream: "http://10.233.31.241:8080/backend/v1/clusters/default/can-i", host: "10.2.27.11:8085", referrer: "http://10.2.27.11:8085/"
```
auth-proxy:

```
Found 2 pods, using pod/kubeapps-7ffc9c78bf-4xxd2
error: container auth-proxy is not valid for pod kubeapps-7ffc9c78bf-4xxd2

```

pinniped-proxy:

```
kubectl logs -n kubeapps deployment/kubeapps pinniped-proxy
Found 2 pods, using pod/kubeapps-7ffc9c78bf-4xxd2
error: container pinniped-proxy is not valid for pod kubeapps-7ffc9c78bf-4xxd2
```
kubeapps-internal-assetsvc  -no errors


internal-kubeops:

```
2021/04/23 08:23:09 http: proxy error: context canceled
2021/04/23 08:23:09 http: proxy error: context canceled
2021/04/23 08:45:06 http: proxy error: read tcp 10.233.70.136:51596->10.233.29.78:8080: read: connection timed out
2021/04/23 08:45:06 http: proxy error: context canceled
2021/04/23 08:56:07 http: proxy error: context canceled
2021/04/23 09:11:39 http: proxy error: read tcp 10.233.70.136:35432->10.233.29.78:8080: read: connection timed out
2021/04/23 10:14:07 http: proxy error: read tcp 10.233.70.136:34800->10.233.29.78:8080: read: connection timed out
2021/04/23 10:34:39 http: proxy error: read tcp 10.233.70.136:43816->10.233.29.78:8080: read: connection timed out
2021/04/23 10:56:25 http: proxy error: context canceled
2021/04/23 11:45:41 http: proxy error: read tcp 10.233.70.136:47110->10.233.29.78:8080: read: connection timed out
2021/04/23 13:38:14 http: proxy error: read tcp 10.233.70.136:40724->10.233.29.78:8080: read: connection timed out
2021/04/28 05:37:26 http: proxy error: read tcp 10.233.70.136:39190->10.233.29.78:8080: read: connection timed out
2021/04/28 10:26:07 http: proxy error: context canceled
2021/04/28 10:50:28 http: proxy error: context canceled
2021/04/28 11:46:57 http: proxy error: context canceled

```
just in case, I did the forwarding this way :

`kubectl port-forward --namespace kubeapps service/kubeapps 8085:80 
`

**Comment by antgamdia** [comment]
Mmm, definitely it seems a connectivity issue between the pods. The `port-forward` command must be run taking into account the values.yaml configuration. 

Have a look at the chart:

https://github.com/kubeapps/kubeapps/blob/4ec1d4665a32b96a0fdd9ee2cc81f2f8aea84752/chart/kubeapps/templates/NOTES.txt#L55

I guess if you change it to 8080, it will work. Otherwise, perhaps you'll need to tweak the values.yaml a little bit.

**Comment by itsecforu** [comment]
OK! I freed this port and restarted forwarding with port 8080 

Now my message about 20 minutes:

`Fetching Cluster Info...`

**Comment by antgamdia** [comment]
Are you authenticating using a token or have you configured the OIDC approach? Are you configuring multiple clusters or just a single one? (ie, have you modified the `clusters: ` section in the values.yaml?)
Could you share the logs again? 

I'm also running Kubeapps 2.3.1 and I'm unable to reproduce the error, unfortunately.

**Comment by itsecforu** [comment]
I didnt use value file:

`helm install kubeapps  bitnami/kubeapps -n kubeapps
`
There is only one cluster.

Auth via token: 

` kubectl get secret $(kubectl get serviceaccount kubeapps-operator -o jsonpath='{range .secrets[*]}{.name}{"\n"}{end}' | grep kubeapps-operator-token) -o jsonpath='{.data.token}' -o go-template='{{.data.token | base64decode}}' && echo
`

**Comment by itsecforu** [comment]
Seems the same with 8080 port :-(

![alt text](https://itsecforu.ru/wp-content/uploads/2021/04/kubeapps-err4.png)

**Comment by itsecforu** [comment]
Mb its course performance .

How many recommended resources does a deployment need?

**Comment by antgamdia** [comment]
At the moment, I don't have any recommendations for running Kubeapps itself. As a developer, I use Kind for setting up my local environment and they recommend:

> If you are building Kubernetes (for example - kind build node-image) on MacOS or Windows then you need a minimum of 6GB of RAM dedicated to the virtual machine (VM) running the Docker engine. 8GB is recommended.
Source: https://kind.sigs.k8s.io/docs/user/quick-start/

You could try to set the `replicas: 1` (as in https://github.com/kubeapps/kubeapps/blob/master/docs/user/manifests/kubeapps-local-dev-values.yaml).

Regarding the deployment resources, it will depend on the application you're trying to deploy.

**Comment by absoludity** [comment]
@itsecforu From the errors and screenshots, it looks like the environment itself isn't stable, though I am confused as to why you're seeing 502s while your output of `kubectl get po` shows zero restarts for the kubeapps pods. Can you confirm:

1. After you experience the 502s and other issues, whether `kubectl get po` for your kubeapps namespace still shows healthy pods or something else. If you see something else, grab the logs of that pod(s)
2. What environment you're checking this on, and whether there are any resource limits enforced?

**Comment by itsecforu** [comment]
solve it via restarting deploymernts with more cpu ! thx all for feedback

**Comment by antgamdia** [comment]
Great, happy to hear you finally solved it. Sometimes is not that easy to debug issues related to resource allocation.
