### ISSUE TITLE
Custom labels to kubeapps deployments

### ISSUE THREAD

**Issue by ShahrozeMalik** [kubeapps/kubeapps#2711]
### Description:

We have different EKS clusters as part of our infrastructure and every cluster has kubeapps dashboard deployed in it. We recently updated a policy of our clusters that every deployment must have **"AppID: 123"** label otherwise it cannot be deployed, now we cannot find a way to add it in values.yaml. There are different deployments and we are unable to find a way to add custom labels to every deployment.

### Describe the results you received:
labels.AppID not found. You must add AppID label to deploy it.

### Describe the results you expected:

Labels are added to deployments and cluster policy allowed it to be deployed

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`: 

```
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
```

- Output of `helm list -n <kubeapps-namespace> <kubeapps-release-name>`:

```
helm list -n helm-kubeapps-ns
NAME            NAMESPACE               REVISION        UPDATED                                 STATUS          CHART           APP VERSION
kubeapps        helm-kubeapps-ns        1               2020-12-02 15:26:49.151958345 +0000 UTC deployed        kubeapps-5.0.0  2.0.1
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.12-eks-7684af", GitCommit:"7684af4ac41370dd109ac13817023cb8063e3d45", GitTreeState:"clean", BuildDate:"2020-10-20T22:57:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by antgamdia** [comment]
Hi @ShahrozeMalik,
unfortunately, you're right, the labels used in the Kubeapps chart are fixed and cannot be changed at this very moment.

As a temporary workaround, you can download locally the chart and modify the file https://github.com/kubeapps/kubeapps/blob/master/chart/kubeapps/templates/_helpers.tpl#L14 adding your labels there. They will be applied to each deployment.

Nevertheless, there's good news here. We are planning to perform some changes in how the official Bitnami/VMware Kubeapps chart is built (https://github.com/kubeapps/kubeapps/issues/2704) and soon we will also a similar `values.yaml` structure as the rest of the chart does. Therefore, adding labels will be just modifying the `commonLabels: {}` object in there.

**Comment by antgamdia** [comment]
Hi @ShahrozeMalik !

Recently, we have finished the migration process I told you about. That means that now you can add `commonLabels` to you values.yaml file ([more information here](https://github.com/bitnami/charts/tree/master/bitnami/kubeapps#common-parameters)).
(You must use a chart version >= 7.0.0, though)

```
helm search repo kubeapps
NAME                    CHART VERSION   APP VERSION     DESCRIPTION                                       
bitnami/kubeapps        7.0.0           2.3.2           Kubeapps is a dashboard for your Kubernetes clu...
```

Let me close the issue, but feel free to add more comments if you face any other problem.
