### ISSUE TITLE
Organize project labels, milestones, etc.

### ISSUE THREAD

**Issue by ppbaena** [kubeapps/kubeapps#2714]
Update GitHub board: labels, milestones, tags, etc.
Document a triage workflow to perform on any tasks to standardize and simplify the process. to help the team to keep the board updated with relevant information about the progress and next steps.

**Comment by antgamdia** [comment]
Should we close it? If so, next time you can write at the PR  `fixes #2714`  and it will get closed once merged.

**Comment by ppbaena** [comment]
Done! PR that will close this issue sent for revision.
