### ISSUE TITLE
External access to Kubeapps

### ISSUE THREAD

**Issue by pkrishn6** [kubeapps/kubeapps#273]
More of a question than an issue.

I have deployed kubeapps (kubeapps up) on a AWS EC2 instance. I edited the kubeapps-kube-api and set disable-filter=true and edited svc/nginx-ingress to change it to type: NodePort.
I am able to access kubeapps using nodeIp:nodePort of nginx and when I click on repos, I see the stable, svc-cat  and incubator repos but the charts page is empty.

I am seeing this on Chrome dev-tools:
Request URL: http://xxxxxxx:32248/api/chartsvc/v1/charts
Request Method: GET
Status Code: 404 Not Found

What is correct way to gain external access. Should svc/dashboard--ui be a nodePort instead? I tried that too and that does not work too. Charts page is still empty. Any suggestions on what I am doing wrong?

**Comment by pkrishn6** [comment]
MongoDB was the issue. I created a pv based on a hostPath. PVC was bound but chartsvc couldn't connect to mongoDB. Setting emptyDir worked.

Thanks....

**Comment by prydonius** [comment]
Perfect thanks @pkrishn6! I added the issue about PVC/StorageClass/emptyDir configuration to https://github.com/kubeapps/kubeapps/issues/228
