### ISSUE TITLE
Development environment broken with duplicate tls certs

### ISSUE THREAD

**Issue by absoludity** [kubeapps/kubeapps#2730]
### Description:

A change to the chart (#2445) a couple of months ago broke the kind-cluster dev setup (I'd thought it was a local issue so had just worked around it) so that kubeapps doesn't deploy, but rather helm errors because there is a conflict with tls certs.

### Steps to reproduce the issue:

1. `make cluster-kind`
2. `make deploy-dev`]

### Describe the results you received:

```
helm --kubeconfig=/home/michael/.kube/kind-config-kubeapps install kubeapps ./chart/kubeapps --namespace kubeapps --create-namespace \
        --values ./docs/user/manifests/kubeapps-local-dev-values.yaml \
        --values ./docs/user/manifests/kubeapps-local-dev-auth-proxy-values.yaml \
        --values ./docs/user/manifests/kubeapps-local-dev-additional-kind-cluster.yaml
Error: rendered manifests contain a resource that already exists. Unable to continue with install: Secret "localhost-tls" in namespace "kubeapps" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "kubeapps"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "kubeapps"
```

### Describe the results you expected:

Kubeapps should be deployed in the local cluster using tls with the pre-generated `localhost-tls` cert.

### Additional information you deem important (e.g. issue happens only occasionally):

The problem is that with the change in #2445, our chart template now assumes that if you have tls enabled and don't have cert manager enabled, that it should generate an (untrusted) tls cert for you: https://github.com/kubeapps/kubeapps/blob/master/chart/kubeapps/templates/tls-secrets.yaml#L17

It seems like a valid use case to want to enable tls without cert manager and specify your own (trusted) cert.

**Comment by absoludity** [comment]
I'd propose we remove the auto-tls cert generation from our chart, unless there is a good use-case for having an *untrusted* cert generated for tls?

**Comment by absoludity** [comment]
The related change will be included in the upstream change to the bitnami kubeapps chart.

**Comment by antgamdia** [comment]
Closing issue since https://github.com/bitnami/charts/pull/6301 was already merged with your change.
