### ISSUE TITLE
Chart broken for Kubeapps with pinniped if release name not kubeapps

### ISSUE THREAD

**Issue by absoludity** [kubeapps/kubeapps#2767]
### Description:

Following the instructions for deploying Kubeapps with pinniped support with the latest chart does not work.

### Steps to reproduce the issue:

1. Follow the documented steps

### Describe the results you received:

nginx fails to start with:

```
nginx 20:33:18.19 INFO  ==> ** Starting NGINX **
2021/05/06 20:33:18 [emerg] 1#1: host not found in upstream "kubeapps-internal-pinniped-proxy.apps" in /opt/bitnami/nginx/conf/server_blocks/vhost.conf:36
nginx: [emerg] host not found in upstream "kubeapps-internal-pinniped-proxy.apps" in /opt/bitnami/nginx/conf/server_blocks/vhost.conf:36
```

Turns out the host has an extra `<namespace>-` prefix, with a service created `<namespace>-kubeapps-internal-pinniped-proxy`.

Even if that's manually updated in the nginx config, then the backend errors similarly with:

```
lookup kubeapps-internal-pinniped-proxy.apps on 172.22.64.10:53: no such host
```

### Describe the results you expected:

Traffic routed to the correct service name.

### Additional information you deem important (e.g. issue happens only occasionally):

AFAICT, looking at the chart, the service name is calculated as

```
{{ include "common.names.fullname" . }}-internal-pinniped-proxy
```

and `common.names.fullname` effectively evaluates to just your helm release name, *iff* your helm release name includes the ame of the chart `kubeapps` (see the [common chart code for details](https://github.com/bitnami/charts/blob/master/bitnami/common/templates/_names.tpl#L16)). But if your release name does *not* include the chart name 'kubeapps`, then the fullname is created as `<release-name>-<chart-name>`, as is the case here `apps-kubeapps`, resulting in the service name of `apps-kubeapps-internel-pinniped-proxy`.

So the rest of the chart needs to use the same helper to result in the same name.

### Version of Helm, Kubeapps and Kubernetes:

Using v2.3.2 (and I assume the latest chart for templating, but not using Helm). More details on the [public slack thread](https://kubernetes.slack.com/archives/C9D3TSUG4/p1620331053044800).

**Comment by absoludity** [comment]
Easier way to reproduce. First, if the release name is kubeapps, there's no problem and all the references match the service URL:

```
helm template kubeapps ./chart/kubeapps --values docs/user/manifests/kubeapps-local-dev-additional-kind-cluster-for-pinniped.yaml --set pinnipedProxy.enabled=true --values docs/user/manifests/kubeapps-local-dev-auth-proxy-values.yaml | grep internal-pinniped-proxy
        proxy_pass http://kubeapps-internal-pinniped-proxy.default:3333;
        proxy_pass http://kubeapps-internal-pinniped-proxy.default:3333;
  name: kubeapps-internal-pinniped-proxy
            - --pinniped-proxy-url=http://kubeapps-internal-pinniped-proxy.default:3333
```

But if I set the release name to `apps`, then the service name is prefixed, but all the references are not:

```
helm template apps ./chart/kubeapps --values docs/user/manifests/kubeapps-local-dev-additional-kind-cluster-for-pinniped.yaml --set pinnipedProxy.enabled=true --values docs/user/manifests/kubeapps-local-dev-auth-proxy-values.yaml | grep internal-pinniped-proxy 

        proxy_pass http://kubeapps-internal-pinniped-proxy.default:3333;
        proxy_pass http://kubeapps-internal-pinniped-proxy.default:3333;
  name: apps-kubeapps-internal-pinniped-proxy
            - --pinniped-proxy-url=http://kubeapps-internal-pinniped-proxy.default:3333
```

**Comment by absoludity** [comment]
As per the related PR, I've pushed this change up for Juan on the related change for the bitnami kubeapps chart at https://github.com/juan131/charts/pull/4

**Comment by antgamdia** [comment]
Closing issue since https://github.com/bitnami/charts/pull/6301 was already merged with your change.
