### ISSUE TITLE
Create a robot account for CI purposes

### ISSUE THREAD

**Issue by antgamdia** [kubeapps/kubeapps#2776]
Required by https://github.com/kubeapps/kubeapps/issues/2704 and taken apart for tracking the progress individually:

We used to have a @kubernetes-bitnami  bot account. However, since we are diverging from the bitnami repos coupling, we ought to create a new CI account that is properly set up. This issue includes:

- [x] Define a mechanism to store our secrets
- [x] Create a @kubeapps-bot account
- [x] Generate the personal access token
  - [x] Grant permissions for releasing as well, check signature?
- [x] Generate a deployment key in the Kubeapps repo
- [x] Add pgp keys to the bot account
- [x] Adapt scripts used in https://github.com/kubeapps/kubeapps/pull/2754 to sign commits
- [x] Adapt CI config to pass the proper env vars:
  - [x] Acces token
  - [x] Deployment keys
  - [x] Tokens
  - [x] pgp key 
- [x] Verify it works

**Comment by antgamdia** [comment]
Please join me in welcoming our fresh new @kubeapps-bot in GitHub and [kubeappsbot](https://hub.docker.com/u/kubeappsbot) in Dockerhub :) 

Closing the issue as it is done

**Comment by absoludity** [comment]
Woohoo! Thanks @antgamdia
