### ISSUE TITLE
Unable to load function in function editor

### ISSUE THREAD

**Issue by sameersbn** [kubeapps/kubeapps#282]
WebSocket connection errors are observed in the error console. I am able to make the same request using curl with the auth token.

```console
$ curl -sSL -H "Authorization: Bearer $TOKEN" "http://localhost:8080/api/kube/apis/apps/v1beta1/namespaces/default/deployments?watch=false&labelSelector=function=hello"
curl -sSL -H "Authorization: Bearer $TOKEN" "http://localhost:8080/api/kube/apis/apps/v1beta1/namespaces/default/deployments?watch=false&labelSelector=function=hello"
{
  "kind": "DeploymentList",
  "apiVersion": "apps/v1beta1",
  "metadata": {
    "selfLink": "/apis/apps/v1beta1/namespaces/default/deployments",
    "resourceVersion": "379948"
  },
  ...
  ...
}
```

See screenshot below.

![functions](https://user-images.githubusercontent.com/410147/39420414-1f3a71e0-4c82-11e8-81db-e82a4d1c33b6.png)

**Comment by prydonius** [comment]
@sameersbn I wasn't able to reproduce this, but I suspect this is happening because of #285 the `1.0.0-alpha.1` binaries are pointing to the wrong image tag for kubeless. Can you confirm which kubeless-controller-manager tag is running?

**Comment by arapulido** [comment]
@sameersbn @prydonius is this still an issue? Shall we close this one?

**Comment by sameersbn** [comment]
Sorry.. this can be closed. 
This issue here was because my build was using the wrong image tags.
