### ISSUE TITLE
chart install fails when pinnipedProxy is enabled

### ISSUE THREAD

**Issue by dlaloue-vmware** [kubeapps/kubeapps#2826]
### Description:

helm install fails when pinnipedProxy is enabled, failing on missing pinnipedProxy.service.port value

### Steps to reproduce the issue:

configure the values file to enable pinnipedProxy.
do helm install 

### Describe the results you received:

helm install fails because of missing pinnipedProxy.service.port value

### Describe the results you expected:

successful installation

### Additional information you deem important (e.g. issue happens only occasionally):

3 files are using pinnipedPRoxy.service.port, maybe instead of pinnipedProxy.containerPort:
  frontend configmap.yaml
  frontend service.yaml
  kubeops deployment.yaml

**Comment by absoludity** [comment]
Thanks @dlaloue-vmware . Yes, as per our slack chat, we recently had a major upgrade of the upstream bitnami/kubeapps chart which has broken the pinniped integration (we test oidc on CI but not yet with pinniped). As this is a bug in the upstream chart, we'll need to do the fix there.

For context: the upstream chart standardization was done in this PR: https://github.com/bitnami/charts/pull/6301

**Comment by dlaloue-vmware** [comment]
this issue is dependent on the following bitnami/charts issue: https://github.com/bitnami/charts/issues/6398

**Comment by antgamdia** [comment]
Closing as the changes are already in the production chart
