### ISSUE TITLE
logout does not work in oidc/sso setup

### ISSUE THREAD

**Issue by dlaloue-vmware** [kubeapps/kubeapps#2827]
### Description:

I have a setup with SSO/oidc using the default auth proxy and pinniped proxy/
the logout from the dashboard does not log the user out.

the logout does redirect to the login screen, but clicking the login with oidc provider buttons logs you back in automatically.
this could be reproduces even after closing the browser and opening a new one.

### Steps to reproduce the issue:

setup kubeapps in SSO/oidc configuration, using default auth proxy and pinniped proxy.
open browser and navigate to login screen.
click login with oidc provider, enter username/password. (user is no wlogged in)
click the logout button (users is redirected to login screen)
click on login with oidc provider button again
     ->   users is automatically logged in from previous session.

click logout
close browser
open new browser
click login with oidc provider
     ->   users is automatically logged in from previous session.

(note: i am using firefox)

### Describe the results you received:

users was logged in automatically

### Describe the results you expected:

login screen from oidc provider should have been presented to let the user enter username/password again

**Comment by absoludity** [comment]
I just tried this in the dev env (standard OIDC with pinniped setup) and it is apparently working there:
![login-out](https://user-images.githubusercontent.com/497518/118600076-d1d0f380-b7f3-11eb-878e-4c0f2c86153a.gif)

I'm keen to see your oauth2-proxy configuration... you can copy-n-paste it (sanitized) from the actual frontend deployment yaml. I suspect something is awry, but keen to find out more.

As mentioned on slack, it is actually oauth2-proxy which handles the logout URL (and oauth2-proxy simply deletes the cookie with the request - the cookie isn't even visible to the Kubeapps code since it's http-only). Let's find out :)

**Comment by dlaloue-vmware** [comment]
![logout](https://user-images.githubusercontent.com/74025858/118698409-36288e80-b7c5-11eb-9698-0cffe8570bce.gif)

**Comment by dlaloue-vmware** [comment]
Here is the values.yaml i used (i have removed the pinniped configuration)

frontend:
  service:
    type: LoadBalancer

authProxy:
  enabled: true
  skipKubeappsLoginPage: false
  provider: oidc
  clientID: kubeapps
  clientSecret:   <redacted>
  cookieSecret: Y29va2llLXNlY3JldC0xNg==
  emailDomain: "*"
  additionalFlags:
   - --ssl-insecure-skip-verify
   - --cookie-secure=false
   - --scope=openid email groups
   - --oidc-issuer-url=  <redacted>

**Comment by antgamdia** [comment]
Mmm, I'm not 100% sure, but, if you are authenticated in your IdP (AWS), I don't see why Kubeapps should log out from that provider (we are not using SSO, which, would allow you to close sessions in other apps rather than Kubeapps).

The issue, as I see it, would be if after a page reloads, you will get authenticated in kubeapps (that's the oauth2 cookie). But it is not happening.

**Comment by absoludity** [comment]
> Here is the values.yaml i used (i have removed the pinniped configuration)

Thanks. It was actually the issuer URL, or more specifically, what IdP you were using that I was keen to see. From the gif you're using aws. So yes, I suspect, as Antonio mentioned, that you are being logged out of Kubeapps just fine. Then:

* when you click on the "Login with your OIDC provider", oauth2-proxy is redirecting to your IdP to auth,
* your IdP (aws) says that you're still authenticated with it, and so redirects back to oauth2-proxy saying as much (completing the oauth2 login),
* oauth2-proxy adds the cookie again.

You can check the logs of the auth-proxy container of the frontend to confirm. What I see when I click Logout is (I've added comments to each line):

```
kubectl -n kubeapps logs deployment/kubeapps auth-proxy
...
# This is the last request *before* I click logout, just so you can see the log format for an authenticated user
# (in my case it has the actual email, but with AWS it may just be a hash identifier)
10.244.0.8:46046 - 5640ea1e0b35f0a47a298887d8475fc7 - kubeapps-operator@example.com [2021/05/18 20:24:48] localhost GET / "/api/clusters/default/apis/dex.coreos.com/v1" HTTP/1.1 "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0" 200 2906 2.923

# This is the actual URI to logout which is configured in the default values (/oauth2/signout) and is handled by oauth2-proxy.
# Note that it no longer has the auth info.
10.244.0.8:46046 - 6a6ba241a79ce323abe3367d876f6e01 - - [2021/05/18 20:25:00] localhost GET - "/oauth2/sign_out" HTTP/1.1 "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0" 302 24 0.001

# From this point, oauth2-proxy complains that the expected cookie (_oauth2_proxy)
# is no longer present with requests.
[2021/05/18 20:25:02] [stored_session.go:76] Error loading cookied session: cookie "_oauth2_proxy" not present, removing session
10.244.0.8:46046 - 83bd0a7ccbb5d15c6d47ebb313e1e801 - - [2021/05/18 20:25:02] localhost GET - "/api/clusters/default/" HTTP/1.1 "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0" 401 0 0.000
[2021/05/18 20:25:04] [stored_session.go:76] Error loading cookied session: cookie "_oauth2_proxy" not present, removing session
``` 

Another way to check is to use your browsers debugger (Storage->Cookies on FF), to verify that the `_oauth2_proxy` cookie is present when you're logged in:
![cookie-set](https://user-images.githubusercontent.com/497518/118720110-8ad31480-b86c-11eb-9cc4-85bd8626d5ce.png)

**Note**: The storage view does not update automatically - you need to click on the small refresh icon (just to the right of Filter Items +).

When you then click on Kubeapps' Logout and get back to the login screen, if you refresh the storage data, you should see that the cookie is indeed gone:
![no-cookie-set](https://user-images.githubusercontent.com/497518/118720325-cf5eb000-b86c-11eb-94fa-1cb0882e4a0d.png)

If not, let us know!

**Comment by absoludity** [comment]
I'm not 100% (haven't used AWS's OIDC functionality before), but it supports a logout URL that you can configure (via url params) to logout the AWS session and then redirect to oauth2-proxy's logout URI? That would ensure that both cookies are removed:

https://docs.aws.amazon.com/cognito/latest/developerguide/logout-endpoint.html

To try this, you can set the `authProxy.oauthLogoutURI` value from its default value of `/oauth2/sign_out`, to something like: `https://mydomain.auth.us-east-1.amazoncognito.com/logout?
client_id=ad398u21ijw3s9w3939&
logout_uri=https://your-kubeapps-dns/oauth2/sign_out` ? (again, haven't checked, but think that should do what you intend, logging out of both your identity provider and Kubeapps)

**Comment by dlaloue-vmware** [comment]
my IDP / OIDC provider is Keycloak, AWS is just the name of my realm :-)

thinking about it a bit more, i can see why Kubeapps will relogin automatically as i have logged in into my sso account. For example, when i am signed in to my Google account, i can login to another connected app. If i logout and relogin, i will be automatically logged in because i did not log out from google, just from my app.

but the issue then is that the login screen is incorrect. if i logged out, the login screen should at least ask as what user i should log in again. Here, once you have logged in once with a user, you cannot login as another user anymore.

**Comment by dlaloue-vmware** [comment]
i am closing this issue as this is behaving as designed.
There are 2 levels of authentication - with kubeapps and with the IDP. logging out from Kubeapps UI does not log you out from the IDP by default.
note that there is a way to configure Kubeapps to trigger a IDP logout as well.
