### ISSUE TITLE
[kubeapps-apis] Demo core.v1alpha1.GetPackageRepositories

### ISSUE THREAD

**Issue by absoludity** [kubeapps/kubeapps#2848]
### Description:

The current demo functionality, such as `GetPackageRepositories` and `GetAvailablePackages`, are exposed per plugin, for example:

```
$ curl -s http://localhost:8080/plugins/helm_fluxv2/packages/v1alpha1/packagerepositories | jq .
{
  "repositories": [
    {
      "name": "bitnami",
      "namespace": "flux-system",
      "url": "https://charts.bitnami.com/bitnami"
    }
  ]
}

$ curl -s http://localhost:8080/plugins/kapp_controller/packages/v1alpha1/packagerepositories | jq .
{
  "repositories": [
    {
      "name": "repo-name.example.com",
      "namespace": "",
      "url": "foo.registry.example.com/repo-name/main@sha256:cecd9b51b1f29a773a5228fe04faec121c9fbd2969de55b0c3804269a1d57aa5"
    }
  ]
}
```

This allows clients to interact with specific plugins when needed, as we cannot assume that this will not be necessary in some circumstances, such as a plugin-specific UX using extra features of that format.

That said, we also want to ensure it's possible to provide a generic implementation of the packages API implemented in our core, that returns results from all plugins, such as:

```
$ curl -s http://localhost:8080/core/packages/v1alpha1/packagerepositories | jq .
{
  "repositories": [
    {
      "name": "bitnami",
      "namespace": "flux-system",
      "url": "https://charts.bitnami.com/bitnami",
      "plugin": "fluxv2"
    },
    {
      "name": "repo-name.example.com",
      "namespace": "",
      "url": "foo.registry.example.com/repo-name/main@sha256:cecd9b51b1f29a773a5228fe04faec121c9fbd2969de55b0c3804269a1d57aa5",
      "plugin": "kapp-controller"
    }
  ]
}
```

**Comment by absoludity** [comment]
Marked size/M only because there's some uncertainty around calling the grpc endpoints of the plugins from core, but assuming that's straight-forward, I expect this to be 1-2 days.

**Comment by antgamdia** [comment]
So, the idea here is: create a new `core` endpoint and, for each `GetConfiguredPlugins` invoke `GetPackageRepositories` and marshall the response back to the user, no?
I agree, when developing clients for this API, having this endpoint will simplify the UI logic. 
Thanks for filing the issue!

**Comment by dlaloue-vmware** [comment]
i understand that the plugin specific call can return the plugin specific payload, with whatever details that make sense for that plugin.

but for the core service, will the response payload be polymorphic or only expose a common schema?

**Comment by absoludity** [comment]
> i understand that the plugin specific call can return the plugin specific payload, with whatever details that make sense for that plugin.

It can, in that we're not (yet) stopping a plugin author from doing so, but we're not planning to do so. Currently the two plugins we're experimenting with use the core.packages messages.

> 
> but for the core service, will the response payload be polymorphic or only expose a common schema?

It'll only expose a common schema. Part of this task is to figure out whether it's possible to only include plugins in such an aggregate call iff they implement the same interface (that will be the safest and easiest option). So plugins can diverge if there is a specific need, but clients would only be able to access those via the plugin-specific requests (until a new version of the core.packages which potentially adapts if whatever specific fields/functionality as required makes sense for all plugins).

**Comment by dlaloue-vmware** [comment]
Carvel is moving fast and i do not remember the full details, but regarding Flux, there are different types of repository:  helm repositories (with index.yaml), git repositories and s3 buckets - they may even support chart hubs at some point.

Are we limiting the support to the "helm repository" or are we supporting all types of source?
If we were to support more than the helm repository, then the schema for flux would immediately diverge from the carvel schema and using the core schema will not fit anymore.

**Comment by absoludity** [comment]
The immediate need is certainly for the fluxv2 + helm repository, but we don't need to limit it to that, necessarily.

As an example, if the proto for a PackageRepository identifies the plugin and has an optional `repositoryType` field, then plugins could support multiple repository types (ie. knowing how to fetch repos of whatever type they support as well as packages for them). Yes, it'd not be possible to use a generic API for *creating* the repository via a UX/Kubeapps, but that's less of a priority [1] - it would however be possible to fetch those repos as well as packages for those repos via a generic API.

I'm wanting to work on this current issue this week to demo for an example endpoint and verify what's possible so we can design for all interactions.

[1] The creation of different resources is exactly where I expect UX/clients may require plugin-specific code, unless we're able to neatly depend on the openapi schema of CRs to generate useful forms. But that's quite a way down the track.

**Comment by dlaloue-vmware** [comment]
so, is it a design decision or a technical decision to not suupport just one "list" api with polymorphism?

**Comment by absoludity** [comment]
protobuf3 does not support inheritance at all (the `extend` keyword was removed when going from protobuf v2->v3), so technically there's no polymorphism, but something similar can be achieved via composition (you may have noticed the preference for composition in the golang ecosystem in general, not sure if that's the case in the java world also these days? [Aside: I loved the [head-first series on OO](https://www.amazon.com.au/Head-First-Objects-Oriented-Analysis-Design/dp/0596008678) 15 years ago, which used java and certainly preferred composition over inheritance, but don't know if that was normal).

Regarding a decision about whether we provide something similar to polymorphism via composition or not, in the core API endpoints, I still say:

> I'm wanting to work on this current issue this week to demo for an example endpoint and verify what's possible so we can design for all interactions.

I'm explicitly putting off making a decision there until I see what's possible with this small demo of one endpoint (ie. in the next day or two), and will base my own vote on that data :)
