### ISSUE TITLE
Test Kubeapps with Pinniped 0.9

### ISSUE THREAD

**Issue by antgamdia** [kubeapps/kubeapps#2947]
Since Pinniped 0.9.0+, it has built-in support for LDAP (apart from the existing OIDC providers).
We should investigate if Kubeapps can be configured to use it or whether we have to implement further changes.

Thanks for pointing this out, @vrabbi

**Comment by absoludity** [comment]
The LDAP support relies on supervisor being the IdP, I think, but currently you [can't configure custom clients for supervisor](https://github.com/vmware-tanzu/pinniped/issues/577) currently, so it may not be possible to use the LDAP support yet (summarising what Scott said in our meeting, haven't checked).

**Comment by antgamdia** [comment]
Yep, you're right, there's no LDAP support in the concierge, so this new functionality cannot be tested right now.
Anyway, re-sizing the scope of this issue just to test if Pinniped 0.9.x works as expected:

I can confirm that Pinniped 0.9.2 is nicely working as usual (as we expected). Initially, I ran into this [transient issue ](https://github.com/vmware-tanzu/pinniped/issues/425)(likely due to a Kind problem or docker pull rate limit), but after deleting and creating pinniped again, it worked.

Closing issue then :)

```
❯ k get deploy -n pinniped-concierge
NAME                                 READY   UP-TO-DATE   AVAILABLE   AGE
pinniped-concierge                   2/2     2            2           9m50s
pinniped-concierge-kube-cert-agent   1/1     1            1           9m38s
```
You should have two deployments: `pinniped-concierge` and `pinniped-concierge-kube-cert-agent`
