### ISSUE TITLE
unable to login to kubeapps with cluster-admin tokoen

### ISSUE THREAD

**Issue by roie9876** [kubeapps/kubeapps#297]
hello
Kubeapps Installer version: v1.0.0-alpha.3
i created new serviceaccount kubeapps-operator
this token works on the k8s dashboard but not on the kubeapps api login
when try to login i get this message:
####################################
Sorry! Something went wrong.
Troubleshooting:
Check for network issues.
Check your browser's JavaScript console for errors.
Check the health of Kubeapps components kubectl get po --all-namespaces -l created-by=kubeapps.
Open an issue on GitHub if you think you've encountered a bug.
####################################

here is the output of the 
localadmin@ubuntu:~/kubepps$  kubectl get po --all-namespaces -l created-by=kubeapps
NAMESPACE   NAME                                        READY     STATUS    RESTARTS   AGE
kubeapps    apprepository-controller-584b4b54d5-fxfkd   1/1       Running   0          59m
kubeapps    chartsvc-d5f86ddf5-hlr2f                    1/1       Running   0          59m
kubeapps    kubeapps-5bdd68c5cc-sgpkh                   1/1       Running   0          59m
kubeapps    kubeapps-dashboard-ui-567b67844-txw9g       1/1       Running   0          59m
kubeapps    mongodb-76bd56459f-w4tm9                    1/1       Running   0          59m

kubectl get deployment -n kubeapps
NAME                       DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
apprepository-controller   1         1         1            1           1h
chartsvc                   1         1         1            1           1h
kubeapps                   1         1         1            1           1h
kubeapps-dashboard-ui      1         1         1            1           1h
mongodb                    1         1         1            1           1h
tiller-deploy              1         1         1            1           1h

BTW where is the kubeapps-kube-api deployment ?

**Comment by prydonius** [comment]
Thanks for filing the issue! Are you seeing any HTTP status errors in the Network tab of your browser?

> BTW where is the kubeapps-kube-api deployment ?

We now use the `kubernetes.default` Service directly instead of a `kubectl proxy` pod.

**Comment by roie9876** [comment]
hello prydonius
can we work on this together ? i can provide you remote access.
my email is roie9876@gmail.com

**Comment by prydonius** [comment]
@roie9876 absolutely, just pinged you!

**Comment by roie9876** [comment]
hello prydonius
thank you very much for your remote support. 
the first problem was access the wrong pod
i tried to access 
kubeapps kubeapps-dashboard-ui
but we need to access
kubeapps kubeapp

after that we didn't saw any helm chart, this issue was because the environment need internet connectivity from the PODs to WWW.
after fix this two issue kubeapps work s.
thank you very much for your support.

**Comment by prydonius** [comment]
Awesome @roie9876, I'm glad you were able to get around the network issue!

Going to go ahead and close out this issue, feel free to open a new one if you run into further issues!
