### ISSUE TITLE
Define a testing strategy for Kubeapps React app

### ISSUE THREAD

**Issue by arapulido** [kubeapps/kubeapps#299]
All of our testing is in the go parts of Kubeapps, but a lot of logic and interaction with the K8s APIs happen at the React app level.

We need to define the testing strategy and a minimum coverage, before we grow this technical debt

**Comment by prydonius** [comment]
After chatting with @sameersbn our plan is to:

1. start writing tests for two or three smaller components whilst getting familiar with the test framework
1. once we're more familiar, start tackling the bigger components like AppView, FunctionView, ServiceInstancesView, ChartsView and their subcomponents
1. look into integration testing after unit testing

As far as coverage, I don't think we want to set a hard minimum coverage goal but we should use a coverage tool to get an idea of what parts of the app are untested and where the bulk of the logic is. I'll look into coverage tools for React.
