### ISSUE TITLE
Unable to Install Kubeapps on TKG Cluster

### ISSUE THREAD

**Issue by poorfellow-org** [kubeapps/kubeapps#2994]
### Description:

When running the default installation via the official helm chart, the pods are created and images are pulled.  However, the kubeapps and Postgres pods never become ready.

### Steps to reproduce the issue:

1. helm install kubeapps --namespace kubeapps bitnami/kubeapps --set frontend.service.type=LoadBalancer
2. kubectl get pods -w --namespace kubeapps
3. kubectl logs <frontend and postgres pods> -n kubeapps

### Describe the results you received:

The frontend pods' logs indicate the following:

$ kubectl logs -n kubeapps kubeapps-5f85f9d999-wp6cz
nginx 15:56:18.69
nginx 15:56:18.69 Welcome to the Bitnami nginx container
nginx 15:56:18.69 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-nginx
nginx 15:56:18.70 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-nginx/issues
nginx 15:56:18.70
nginx 15:56:18.70 INFO  ==> ** Starting NGINX setup **
nginx 15:56:18.71 INFO  ==> Validating settings in NGINX_* env vars
nginx 15:56:18.79 INFO  ==> Initializing NGINX
nginx 15:56:18.80 INFO  ==> ** NGINX setup finished! **

nginx 15:56:18.81 INFO  ==> ** Starting NGINX **
2021/06/16 15:56:18 [emerg] 1#1: host not found in upstream "kubernetes.default" in /opt/bitnami/nginx/conf/server_blocks/vhost.conf:32
nginx: [emerg] host not found in upstream "kubernetes.default" in /opt/bitnami/nginx/conf/server_blocks/vhost.conf:32

On the postgres pods:

$ kubectl logs kubeapps-postgresql-primary-0 -n kubeapps
postgresql 13:59:21.67
postgresql 13:59:21.67 Welcome to the Bitnami postgresql container
postgresql 13:59:21.67 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
postgresql 13:59:21.67 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
postgresql 13:59:21.67
postgresql 13:59:21.69 INFO  ==> ** Starting PostgreSQL setup **
postgresql 13:59:21.71 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 13:59:21.72 INFO  ==> Loading custom pre-init scripts...
postgresql 13:59:21.72 INFO  ==> Initializing PostgreSQL database...
postgresql 13:59:21.75 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 13:59:21.75 INFO  ==> Generating local authentication configuration
postgresql 13:59:22.88 INFO  ==> Starting PostgreSQL in background...
postgresql 13:59:23.26 INFO  ==> Changing password of postgres
postgresql 13:59:23.28 INFO  ==> Creating replication user repl_user
postgresql 13:59:23.31 INFO  ==> Configuring replication parameters
postgresql 13:59:23.34 INFO  ==> Configuring fsync
postgresql 13:59:23.40 INFO  ==> Loading custom scripts...
postgresql 13:59:23.41 INFO  ==> Enabling remote connections
postgresql 13:59:23.43 INFO  ==> Stopping PostgreSQL...
waiting for server to shut down.... done
server stopped
postgresql 13:59:23.54 INFO  ==> ** PostgreSQL setup finished! **

postgresql 13:59:23.57 INFO  ==> ** Starting PostgreSQL **
2021-06-16 13:59:23.596 GMT [1] LOG:  pgaudit extension initialized
2021-06-16 13:59:23.597 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2021-06-16 13:59:23.597 GMT [1] LOG:  listening on IPv6 address "::", port 5432
2021-06-16 13:59:23.599 GMT [1] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2021-06-16 13:59:23.612 GMT [142] LOG:  database system was shut down at 2021-06-16 13:59:23 GMT
2021-06-16 13:59:23.615 GMT [1] LOG:  database system is ready to accept connections
[pfsadmin@mprosmgt01 ~]$ kubectl logs kubeapps-postgresql-primary-0 -n kubeapps
postgresql 13:59:21.67
postgresql 13:59:21.67 Welcome to the Bitnami postgresql container
postgresql 13:59:21.67 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
postgresql 13:59:21.67 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
postgresql 13:59:21.67
postgresql 13:59:21.69 INFO  ==> ** Starting PostgreSQL setup **
postgresql 13:59:21.71 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 13:59:21.72 INFO  ==> Loading custom pre-init scripts...
postgresql 13:59:21.72 INFO  ==> Initializing PostgreSQL database...
postgresql 13:59:21.75 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 13:59:21.75 INFO  ==> Generating local authentication configuration
postgresql 13:59:22.88 INFO  ==> Starting PostgreSQL in background...
postgresql 13:59:23.26 INFO  ==> Changing password of postgres
postgresql 13:59:23.28 INFO  ==> Creating replication user repl_user
postgresql 13:59:23.31 INFO  ==> Configuring replication parameters
postgresql 13:59:23.34 INFO  ==> Configuring fsync
postgresql 13:59:23.40 INFO  ==> Loading custom scripts...
postgresql 13:59:23.41 INFO  ==> Enabling remote connections
postgresql 13:59:23.43 INFO  ==> Stopping PostgreSQL...
waiting for server to shut down.... done
server stopped
postgresql 13:59:23.54 INFO  ==> ** PostgreSQL setup finished! **

postgresql 13:59:23.57 INFO  ==> ** Starting PostgreSQL **
2021-06-16 13:59:23.596 GMT [1] LOG:  pgaudit extension initialized
2021-06-16 13:59:23.597 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2021-06-16 13:59:23.597 GMT [1] LOG:  listening on IPv6 address "::", port 5432
2021-06-16 13:59:23.599 GMT [1] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2021-06-16 13:59:23.612 GMT [142] LOG:  database system was shut down at 2021-06-16 13:59:23 GMT
2021-06-16 13:59:23.615 GMT [1] LOG:  database system is ready to accept connections

$ kubectl logs kubeapps-postgresql-read-0 -n kubeapps
postgresql 14:01:16.66
postgresql 14:01:16.66 Welcome to the Bitnami postgresql container
postgresql 14:01:16.67 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
postgresql 14:01:16.67 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
postgresql 14:01:16.67
postgresql 14:01:16.68 INFO  ==> ** Starting PostgreSQL setup **
postgresql 14:01:16.70 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 14:01:16.71 INFO  ==> Loading custom pre-init scripts...
postgresql 14:01:16.72 INFO  ==> Initializing PostgreSQL database...
postgresql 14:01:16.74 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 14:01:16.75 INFO  ==> Generating local authentication configuration
postgresql 14:01:16.75 INFO  ==> Waiting for replication master to accept connections (60 timeout)...
kubeapps-postgresql:5432 - no response
kubeapps-postgresql:5432 - no response
kubeapps-postgresql:5432 - no response
kubeapps-postgresql:5432 - no response
kubeapps-postgresql:5432 - no response
kubeapps-postgresql:5432 - no response
kubeapps-postgresql:5432 - no response
kubeapps-postgresql:5432 - no response
kubeapps-postgresql:5432 - no response
kubeapps-postgresql:5432 - no response
kubeapps-postgresql:5432 - no response
kubeapps-postgresql:5432 - no response
kubeapps-postgresql:5432 - no response
kubeapps-postgresql:5432 - no response
kubeapps-postgresql:5432 - no response
kubeapps-postgresql:5432 - no response

### Describe the results you expected:

The pods to come up normally.

### Additional information you deem important (e.g. issue happens only occasionally):

The issue occurs on every deployment attempt.

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"clean", GoVersion:"go1.16.3"}
```

- Output of `helm list -n <kubeapps-namespace> <kubeapps-release-name>`:

```
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART               APP VERSION
kubeapps        kubeapps        1               2021-06-16 15:31:38.277609608 -0400 EDT deployed        kubeapps-7.1.0      2.3.2

```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1+wcp.3", GitCommit:"fb53e772aa2828c695b1f6b9fe83c63f87c27cf6", GitTreeState:"clean", BuildDate:"2021-02-05T05:07:45Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2+vmware.1", GitCommit:"81b46131915aab7ee009967d15ac9c63534554dc", GitTreeState:"clean", BuildDate:"2021-01-19T23:03:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by absoludity** [comment]
Hi @poorfellow-org . Thanks for the report. It looks like both logs that you've shown indicate that DNS is not running correctly on your cluster? That is...

> $ kubectl logs -n kubeapps kubeapps-5f85f9d999-wp6cz
...
> 2021/06/16 15:56:18 [emerg] 1#1: host not found in upstream "kubernetes.default" in /opt/bitnami/nginx/conf/server_blocks/vhost.conf:32
> nginx: [emerg] host not found in upstream "kubernetes.default" in /opt/bitnami/nginx/conf/server_blocks/vhost.conf:32

"kubernetes.default" is the internal host on a cluster for the kubernetes api server, yet appears not to be resolving by the above error. Can you verify this by following the [kubernetes docs for troubleshooting dns](https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/#create-a-simple-pod-to-use-as-a-test-environment)? (or more simply, you might be able to just exec similar commands on the `kubeapps-5f85f9d999-wp6cz` pod itself).

> 
> On the postgres pods:
> 
> $ kubectl logs kubeapps-postgresql-primary-0 -n kubeapps
...
> postgresql 14:01:16.75 INFO ==> Waiting for replication master to accept connections (60 timeout)...
> kubeapps-postgresql:5432 - no response
> kubeapps-postgresql:5432 - no response

This is the same problem: `kubeapps-postgresql` is the name of the service which should be resolved by the kube dns.

Let me know if what I said is not the case, thanks.

**Comment by poorfellow-org** [comment]
Thank you for the help!

So, I deployed a dns test pod into the kubeapps namespace (after testing in the default namespace), and DNS resolution is working to core-dns.  However, when looking at the log from the core-dns pod, I see the following:

$ kubectl logs --namespace=kube-system -l k8s-app=kube-dns
.:53
[INFO] plugin/reload: Running configuration MD5 = db32ca3650231d74073ff4cf814959a7
CoreDNS-1.7.0
linux/amd64, go1.15.5,
.:53
[INFO] plugin/reload: Running configuration MD5 = db32ca3650231d74073ff4cf814959a7
CoreDNS-1.7.0
linux/amd64, go1.15.5,
[ERROR] plugin/errors: 2 kubeapps-postgresql. A: read udp 192.168.0.6:60103->10.1.3.22:53: i/o timeout
[ERROR] plugin/errors: 2 kubeapps-postgresql. A: read udp 192.168.0.6:57098->10.1.3.22:53: i/o timeout

I can't run any troubleshooting commands in the postgres pods, since I cannot elevate to root to install the requisite programs.  What's odd is that only the bitnami deployments seem to be having this issue.  Could it be the core-dns implementation on TKG that's changed, and requires a tweak to the chart?

**Comment by antgamdia** [comment]
> I can't run any troubleshooting commands in the postgres pods, since I cannot elevate to root to install the requisite programs. What's odd is that only the bitnami deployments seem to be having this issue. Could it be the core-dns implementation on TKG that's changed, and requires a tweak to the chart?

Mmm, that's weird. We tested Kubeapps on TKGm 1.3 (in aws) and TKGs 1.2 (as far as I can remember) and it worked nicely.
Which TKG version are you using? where are you running the workload clusters? perhaps are you installing kubeapps in the management cluster?

**Comment by poorfellow-org** [comment]
Thank you for your reply.

The implementation is actually TKGI.  The network stack is NSX-T.  I've enabled workload management.  I created a namespace for the TKG cluster, then deployed the cluster using the following template:

apiVersion: run.tanzu.vmware.com/v1alpha1      #TKGS API endpoint
kind: TanzuKubernetesCluster                   #required parameter
metadata:
  name: k8s-tkg-prod-01                      #cluster name, user defined
  namespace: mpc-tkg-prod-01                   #vsphere namespace
spec:
  distribution:
    version: v1.20.2                             #Resolves to latest TKR 1.20
  topology:
    controlPlane:
      count: 3                                 #number of control plane nodes
      class: best-effort-large                #vmclass for control plane nodes
      storageClass: tanzu-storage-policy         #storageclass for control plane
    workers:
      count: 3                                 #number of worker nodes
      class: best-effort-2xlarge                #vmclass for worker nodes
      storageClass: tanzu-storage-policy         #storageclass for worker nodesapiVersion: run.tanzu.vmware.com/v1alpha1

**Comment by antgamdia** [comment]
Ahh, TKGI... unfortunately I personally don't have much experience with TKGI, so perhaps I'm missing something.
In the [#kubeapps on Kubernetes Slack](https://kubernetes.slack.com/messages/kubeapps) perhaps  you can get more assistance from other community people that also tried to deploy Kubeapps in TKGi.

If even the postgresql from bitnami/charts is failing (I mean, standalone, not as part of kubeapps), I suggest you create [a new issue in their repo](https://github.com/bitnami/charts/issues/new/choose) so that they can evaluate what's happening. But, yep, I agree, it seems to be a networking issue.

Nonetheless, I'm gonna create a task to evaluate Kubeapps in TKGi environments in the future.

**Comment by poorfellow-org** [comment]
Thank you both so much.

I'm going to try to deploy kubeapps directly to a TKGI pod/vsphere pod, and see if it functions well there.  Will report back.

**Comment by poorfellow-org** [comment]
Kubeapps installs and runs perfectly on a native vsphere namespace.  One caveat for deploying charts requiring a PV: the storage class will need to be explicitly defined, since there is no "default" within a native namespace.

Thanks again for all your help.
