### ISSUE TITLE
Frequent CI failures in GKE

### ISSUE THREAD

**Issue by antgamdia** [kubeapps/kubeapps#3019]
ERROR: (gcloud.container.clusters.create) ResponseError: code=403, message=Your project already has the maximum number of clusters: (50) in location **********.

**Comment by antgamdia** [comment]
A workaround (disabling the test in GKE with the _on master_ trigger) was added in https://github.com/kubeapps/kubeapps/pull/3058. Since the root cause is an internal problem with our G account, perhaps we can close this issue for now.

**Comment by ppbaena** [comment]
Issue has been closed due CI failures in GKE ended by migrating to a new account with dedicated resources.
