### ISSUE TITLE
Saving chart/ app configuration for backup

### ISSUE THREAD

**Issue by raphael-09** [kubeapps/kubeapps#3031]
Dear KubeApps Community,

We have a cluster running for a customer and we want to implement an In-cluster app management UI for them. The goal is that the customer can self deploy apps.
The problem we see with KubeApps at the moment is that we cannot save a charts configuration file for backup or later use. 
So if the customer self deploys an app using KubeApps and e.g. the cluster crashes for whatever reasons, we cannot restore the exact same configuration.
Is there any way we could implement this?

**Comment by absoludity** [comment]
I think this is already possible with helm, regardless of Kubeapps. That is, if your customer installs a chart via Kubeapps or via helm (same either way), then helm will have created a "release" for that deployment. The release (usually a configmap or secret in the namespace to which you deploy) encodes a bunch of information which you can access with the `helm get` command.

For example, to get the values that were used by the customer when they deployed the app (via Kubeapps or Helm), you can use: `helm get values RELEASE_NAME` as [documented on the helm website](https://helm.sh/docs/helm/helm_get_values/) (try it out!).

Now that doesn't mean that you'll have access to that data if your cluster crashes, but it does mean you have the saved chart configuration file for backup - it should be trivial from there for your backup to keep that data elsewhere to be able to redeploy with the identical configuration.

Please close this if that answers your question :)
