### ISSUE TITLE
combine pkg/kube/http_utils.go and pkg/http-client/httpclient.go into one

### ISSUE THREAD

**Issue by gfichtenholt** [kubeapps/kubeapps#3045]
Just noticed we have two libraries *roughtly* responsible for doing the same thing: http client utilities used by other parts of code. Methinks, this shouldn't be the case. There should just be one Http Client utility. I was responsible for part of this problem: introduction of  pkg/http-client/httpclient.go, because I didn't know/notice at the time the other one existed.

**Comment by absoludity** [comment]
Might be worth just doing this? (ie. combining them now before any other changes get added depending on the new one?). Sorry I missed that in the review.

**Comment by gfichtenholt** [comment]
go ahead if you want/looking for easy things to do :-)
I am neck-deep in caching stuff and can't do it at the moment. Will get to it at some point

**Comment by dlaloue-vmware** [comment]
I have been comparing the 2 files, and after doing one refactor where i merged httpclient.go into http_utils.go, i think there is actual value in keeping the 2 files separate.
what i think should happen is that some of the code in http_utils.go that is http client specific should be moved to httpclient.go (for the most part, it is already there) and have http_utils.go leverage httpclient.go.

**Comment by gfichtenholt** [comment]
that sounds ok to me. Michael?

**Comment by absoludity** [comment]
Yep, I'd chatted separately about this:
