### ISSUE TITLE
Add userAgent to requests from kubeops service 

### ISSUE THREAD

**Issue by absoludity** [kubeapps/kubeapps#3076]
### Description:

The `kubeops` service is currently setting an empty user agent. The old `tiller-proxy` service used to include a `version.go` which set a userAgent string to be used in the chart client:

https://github.com/kubeapps/kubeapps/blob/v1.11.3/cmd/tiller-proxy/version.go

but it seems this was never moved across to the kubeops service. As a result, the [`UserAgent` field of the `Options`](https://github.com/kubeapps/kubeapps/blob/master/cmd/kubeops/internal/handler/handler.go#L43) is not being set during [kubeops startup](https://github.com/kubeapps/kubeapps/blob/master/cmd/kubeops/main.go#L80), and the existing `userAgentComment` which is in the code is left unused. We should add a version.go similar to the old tiller-proxy one or the [current asset-syncer one](https://github.com/kubeapps/kubeapps/blob/master/cmd/asset-syncer/version.go).

### Steps to reproduce the issue:

Check the charts.bitnami.com logs and see only `tiller-proxy/v...` from old installations of Kubeapps. I suspect there will also be ones with empty userAgent strings.

**Comment by ppbaena** [comment]
userAgent checked and working.
