### ISSUE TITLE
Implement further direct helm plugin features

### ISSUE THREAD

**Issue by absoludity** [kubeapps/kubeapps#3146]
### Description:

In #2993 we implemented GetAvailablePackageSummaries, GetAvailablePackageDetail, and GetAvailablePackageVersions. The remaining tasks are:

- [x] GetInstalledPackageSummaries
- [x] Update GetAvailablePackageDetail to include readme and values etc.
- [x] GetInstalledPackageDetail
- [x] CreateInstalledPackage
- [x] UpdateInstalledPackage
- [x] DeleteInstalledPackage

which we'll add to the direct helm backend plugin while agreeing on the messages in the doc (#2944).

**Comment by antgamdia** [comment]
Let me reopen this issue as I think it was accidentally closed via PR (if only we already implemented every operation... :P)

**Comment by antgamdia** [comment]
Closed in favor of https://github.com/kubeapps/kubeapps/issues/3340

**Comment by absoludity** [comment]
> Closed in favor of #3340

Not sure I want to close this in favour of #3340. This one here is a unit of work that we can effectively complete in the next iteration (I would think). Whereas #3340 is a summary of a whole bunch of work that we are in no place to complete in the next iteration. I think it's important to be able to break things down and assign smaller parts to get done?

**Comment by antgamdia** [comment]
> Whereas #3340 is a summary of a whole bunch of work that we are in no place to complete in the next iteration. I think it's important to be able to break things down and assign smaller parts to get done?

I do agree here. I just thought we might want to create two issues for tracking each operation during this iteration and left the #3340 as the only high-level issue. But, yep, if we want this issue to be the unit of work for this iteration, I'm totally ok with it!
