### ISSUE TITLE
Handle empty chart from index

### ISSUE THREAD

**Issue by ram-pi** [kubeapps/kubeapps#3150]
### Description:
In some cases the index returns empty charts (i.e. https://chart.testarchitect.com/index.yaml) and the asset-syncer is unable to get the "deprecated" property so the execution goes in error.

### Steps to reproduce the issue:
1. Add https://chart.testarchitect.com as repo in kubeapps
2. Click on refresh for getting the latest charts
3. Check the log on the asset-syncer microservice

### Additional info
I've solved in my local enviroment adding a check for the empty entry in kubeapps/pkg/helm/index.go.

**Comment by antgamdia** [comment]
Hi @ram-pi , thanks for reporting it; I can reproduce this issue (below). I'm adding the proper labels and moving the issue to our backlog.
It would be great if you can send a PR with the fix you already implemented. Kubeapps always welcomes community contributions :) 

```console
❯ k logs -n kubeapps apprepo-default-sync-empty-ndt88-ncp2r
time="2021-07-14T09:48:29Z" level=info msg="Last checksum: "
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/kubeapps/kubeapps/pkg/helm.ChartsFromIndex(0xc0005a6000, 0x27a, 0x400, 0xc0003c61c0, 0xc00026e001, 0x11, 0xc000221880, 0x1, 0x1, 0xc00026e000)
        /go/src/github.com/kubeapps/kubeapps/pkg/helm/index.go:74 +0x516
main.(*HelmRepo).Charts(0xc0003c6040, 0x1, 0x1696483, 0x11, 0xc000221880, 0x1, 0x1)
        /go/src/github.com/kubeapps/kubeapps/cmd/asset-syncer/utils.go:226 +0xeb
main.glob..func4(0x22051e0, 0xc00042a600, 0x3, 0x8)
        /go/src/github.com/kubeapps/kubeapps/cmd/asset-syncer/sync.go:114 +0x8fb
github.com/spf13/cobra.(*Command).execute(0x22051e0, 0xc00042a580, 0x8, 0x8, 0x22051e0, 0xc00042a580)
        /go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x2204f60, 0x0, 0x211bd98, 0xc000114058)
        /go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
        /go/src/github.com/kubeapps/kubeapps/cmd/asset-syncer/main.go:48 +0x2d
```

**Comment by ram-pi** [comment]
@antgamdia sure! I'll send you a PR asap ;)
