### ISSUE TITLE
Implement further fluxv2 plugin features

### ISSUE THREAD

**Issue by gfichtenholt** [kubeapps/kubeapps#3173]
the goal is to have parity with helm plug-in features (see https://github.com/kubeapps/kubeapps/issues/3146)

**Comment by antgamdia** [comment]
Hi! Should we close this issue in favor of https://github.com/kubeapps/kubeapps/issues/2946 ?  (or vice-versa)

**Comment by gfichtenholt** [comment]
I am fine with that.

**Comment by ppbaena** [comment]
This issue can be closed as it is directly related to #2946
