### ISSUE TITLE
Generic error message displayed when providing invalid chart name for app deployment

### ISSUE THREAD

**Issue by wojciechka** [kubeapps/kubeapps#318]
When trying to deploy an application and providing an invalid name - such as starting with upper case - kubeapps shows a very generic and not informative error:

![image](https://user-images.githubusercontent.com/683972/40227558-2086a508-5a8f-11e8-9574-5f3d08811f19.png)

It would be beneficial if there is validation for some of the fields and/or the output from deployment error is parsed and some errors are shown with their message.

**Comment by prydonius** [comment]
From @allen-servedio (https://github.com/kubeapps/kubeapps/issues/323#issue-324932129)

---
When adding a new app repo, if there is a space in the name of the repo, it will fail with your general error message (something went wrong, check for network issues, check the Javascript console, etc...). When I look at the Javascript console here is what I see as the response:

```
Request URL: http://localhost:64560/api/kube/apis/kubeapps.com/v1alpha1/namespaces/kubeapps/apprepositories
Request Method: POST
Status Code: 422 Unprocessable Entity
Remote Address: 127.0.0.1:64560
Referrer Policy: no-referrer-when-downgrade
Connection: keep-alive
Content-Length: 1016
Content-Type: application/json
Date: Mon, 21 May 2018 14:11:23 GMT
Server: nginx/1.12.2
```

I think if you just do some basic validation and require that the name not have spaces in it, it would be a better use experience.

**Comment by prydonius** [comment]
From @nomisbeme (#412)

---
I'm running on AKS:
```
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.9", GitCommit:"57729ea3d9a1b75f3fc7bbbadc597ba707d47c8a", GitTreeState:"clean", BuildDate:"2018-06-29T01:07:01Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
The alpha4 release installed using the defaults:
```
$ kubectl get po kubeapps-dashboard-ui-8465dc9887-7ssxm -n kubeapps -o jsonpath='{..image}'
kubeapps/dashboard:v1.0.0-alpha.4
```

**Steps to reproduce**
1. Launch kubeapps dashboard in the browser
2. Charts tab > MySQL 5.7.14 > Deploy using Helm
3. Enter a string with a capital letter in the name "Mysql"

**Expected result**
Helm chart is used to create a new release in the cluster

**Actual result**
Sorry! Something went wrong message

**Additional details**
Chrome network tab shows that a post request failed with 422:
```
Request URL: http://localhost:54631/api/kube/apis/helm.bitnami.com/v1/namespaces/default/helmreleases
Request Method: POST
Status Code: 422 Unprocessable Entity
Remote Address: 127.0.0.1:54631
Referrer Policy: no-referrer-when-downgrade
```

If capital letters are prohibited this should be handled more gracefully. Better, upper and lower case deployment names should be permitted.
