### ISSUE TITLE
Links in Getting Started page are broken

### ISSUE THREAD

**Issue by josemaia** [kubeapps/kubeapps#3180]
### Description:

Internal links in Getting Started page are redirecting wrongly, to a 404 page.

### Steps to reproduce the issue:

1. https://kubeapps.com/docs/getting-started/
2. click "configure an OAuth2/OIDC provider" in Step 2
3. hit nginx 404 page

### Additional information you deem important (e.g. issue happens only occasionally):

Link appears to be rewriting partially, e.g. https://kubeapps.com/docs/getting-started/using-an-OIDC-provider instead of the correct https://kubeapps.com/docs/using-an-OIDC-provider

**Comment by absoludity** [comment]
Thanks @josemaia , yes the docs were recently restructured and we'd missed that we need to be careful with the relative links due to the docs site using clean URLs (the link to the dashboard is also similarly broken at the end of the page).

We need to either:

- add a check to ensure we can't land markdown docs with links that will break the docs site, or
- update the docs site so it doesn't require a different URL format for relative links.

Thoughts @antgamdia , @ppbaena ?

**Comment by antgamdia** [comment]
I'd rather avoid extra patches or checks, and directly go with what other projects are doing: either serving the docs via Github pages or set up a Netlify static site. But the key point is that we really should maintain a single repo, not a website and the main kubeapps repo separately (when they're using the same info).

Perhaps after these intense iterations, we could set some time for this in sept ?

**Comment by absoludity** [comment]
+1 - that's what I meant with the second point.

**Comment by ppbaena** [comment]
+1 to the second approach too, but in the meanwhile I'm checking broken links and fixing at kubeapps.com so we can keep our documentation available to users until we have some extra capacity to update the docs site.

**Comment by ppbaena** [comment]
I've been checking kubeapps.com and there are broken links at:

- https://kubeapps.com/docs/getting-started/
- https://kubeapps.com/docs/dashboard/
- https://kubeapps.com/docs/using-an-OIDC-provider/
- https://kubeapps.com/docs/access-control/
- https://kubeapps.com/docs/deploying-to-multiple-clusters/
- https://kubeapps.com/docs/offline-installation/

**Comment by ppbaena** [comment]
Current https://kubeapps.com website will be deprecated and replaced by a new website fully integrated in the kubeapps repo as described in #3953
