### ISSUE TITLE
Add deployment order

### ISSUE THREAD

**Issue by andresmgot** [kubeapps/kubeapps#32]
There is a dependency between some of the elements of kubeapps (for example the `ratesvc` will fail until the MongoDB database is ready). This causes exponentials backoff times. It will speed up the deployment if we implement a basic dependency system in which the deployments that depends on other doesn't start until the previous one finishes.

It will be nice as well to have some kind of progression info.

Right now this is just a wrapper around deployment manifests, I would expect from an installer certain intelligence to know which components should be installed in which order and also give information about the installation progress.

**Comment by ngtuna** [comment]
this can be solved by default kubecfg's behavior. Link to #21

**Comment by ngtuna** [comment]
we solve this with kubecfg's deployment order
