### ISSUE TITLE
Helm CRD: Ability to adopt existing Helm deployments

### ISSUE THREAD

**Issue by arapulido** [kubeapps/kubeapps#320]
In Monocular, the dashboard is able to show the Helm deployments that were deployed within Monocular, but also the ones that were deployed directly with Helm CLI.

In Kubeapps, only the ones that were created through the dashboard are shown and can be managed through the dashboard.

We need to improve Helm CRD and the Kubeapps Dashboard to allow for this.

**Comment by prydonius** [comment]
@andresmgot let's setup a call to discuss this

**Comment by andresmgot** [comment]
waiting for review at #330

**Comment by andresmgot** [comment]
Moved to done since it was implemented in helm-crd in https://github.com/bitnami-labs/helm-crd/pull/29 and the feature is available in v0.4.0. The UI changes continues under review at #330.
