### ISSUE TITLE
The global chart repository cannot be used to upgrade charts on another cluster

### ISSUE THREAD

**Issue by shoon2430** [kubeapps/kubeapps#3213]
### Description:

In a multi-cluster environment, it seems that the Global Repositories registered in the default cluster cannot be loaded when the application is upgraded in another cluster.

### Steps to reproduce the issue:

First, our kubeapps set up keycloak OIDC and set up 4 clusters.

kubeapps Chart version is '7.1.2' and repository is 'https://charts.bitnami.com/bitnami'

Here is the values.yaml file I used:

~~~
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "64k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "8"
  hostname: {hostname}
  path: /

authProxy:
  enabled: true
  provider: "oidc"
  clientID: {clientID}
  clientSecret: {clientSecret}
  cookieSecret: {cookieSecret}
  scope: "openid email"
  additionalFlags:
    - --cookie-secure=true
    - --set-authorization-header=true
    - --oidc-issuer-url={keycloak-domain}/auth/realms/{realms}
    - --login-url={keycloak-domain}/auth/realms/{realms}/protocol/openid-connect/auth
    - --redeem-url={keycloak-domain}/auth/realms/{realms}/protocol/openid-connect/token
    - --validate-url={keycloak-domain}/auth/realms/{realms}/protocol/openid-connect/userinfo
    - --pass-access-token=true
    - --skip-jwt-bearer-tokens=true

clusters:
  - name: dkc
    apiServiceURL: {cluster-endpoint}
    certificateAuthorityData: {certificateAuthority}
  - name: okc0
    apiServiceURL: {cluster-endpoint}
    certificateAuthorityData: {eks-certificateAuthority}
    isKubeappsCluster: true
  - name: prod
    apiServiceURL: {cluster-endpoint}
    certificateAuthorityData: {eks-certificateAuthority}
  - name: dev
    apiServiceURL: {cluster-endpoint}
    certificateAuthorityData: {eks-certificateAuthority}
~~~

1. kubeapps global repository check

![grobal_repo](https://user-images.githubusercontent.com/44529784/127317838-29a4f214-4182-414c-931c-be5cb084db40.png)

2. bitnami/nginx deploy

![deploy](https://user-images.githubusercontent.com/44529784/127318005-ccb27a26-519f-4182-9e3e-e2b3881d462a.png)

3. bitnami/nginx deploy success

![deploy_success](https://user-images.githubusercontent.com/44529784/127322065-cf60a788-de59-4625-9aa3-b7390f84e584.png)

4. bitnami/nginx upgrade (replica -> 2)

![upgrade_0](https://user-images.githubusercontent.com/44529784/127318024-a94f3942-4f4f-4721-9828-de837a76e2e5.png)

5. bitnami/nginx upgrade

![upgrade_404_console](https://user-images.githubusercontent.com/44529784/127318034-f5b83fbf-474b-48ed-9dd3-b9adf11cdc25.png)
![upgrade_404_network](https://user-images.githubusercontent.com/44529784/127318040-d6d8a675-7134-47ab-a8c4-23d9dab96384.png)

### Describe the results you received:

It seems that the chart repository registered in the default cluster cannot be loaded.

### Describe the results you expected:

If the global repository is registered on the primary cluster, I think it should be possible to deploy, upgrade, delete from other clusters (including other namespaces in other clusters).

### Additional information you deem important (e.g. issue happens only occasionally):

If you search the chart through the api with the name and namespace of another cluster, it seems to be inquired.

![api-get-chart](https://user-images.githubusercontent.com/44529784/127319408-ec12dc96-8529-4a52-b355-abb7364a9cf3.png)

After CRD is created in each cluster (except for the default cluster), upgrade is possible if app repositories are registered in the corresponding namespace.
* CRD : https://github.com/kubeapps/kubeapps/blob/master/chart/kubeapps/crds/apprepository-crd.yaml

apprepository-crd.yaml

~~~
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: apprepositories.kubeapps.com
spec:
  group: kubeapps.com
  scope: Namespaced
  names:
    kind: AppRepository
    plural: apprepositories
    shortNames:
      - apprepos
  version: v1alpha1
~~~

apprepositories.yaml

~~~
apiVersion: kubeapps.com/v1alpha1
kind: AppRepository
metadata:
  name: bitnami
  namespace: devops
spec:
  type: helm
  url: 'https://charts.bitnami.com/bitnami'
---
apiVersion: kubeapps.com/v1alpha1
kind: AppRepository
metadata:
  name: chartmuseum
  namespace: devops
spec:
  type: helm
  url: "{my-chartmuseum}"
~~~

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

- Output of `helm list -n <kubeapps-namespace> <kubeapps-release-name>`:

```
We are deploying kubeapps using argoCD.
Chart version : 7.1.2

docker.io/bitnami/kubeapps-apprepository-controller:2.3.2-scratch-r0
docker.io/bitnami/kubeapps-asset-syncer:2.3.2-scratch-r0
docker.io/bitnami/kubeapps-assetsvc:2.3.2-scratch-r0
docker.io/bitnami/kubeapps-dashboard:2.3.2-debian-10-r46
docker.io/bitnami/kubeapps-kubeops:2.3.2-scratch-r0
docker.io/bitnami/nginx:1.19.10-debian-10-r60
docker.io/bitnami/oauth2-proxy:7.1.3-debian-10-r46
docker.io/bitnami/postgresql:11.12.0-debian-10-r23
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.16-eks-7737de", GitCommit:"7737de131e58a68dda49cdd0ad821b4cb3665ae8", GitTreeState:"clean", BuildDate:"2021-03-10T21:33:25Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by antgamdia** [comment]
Thanks a lot for the detailed report! As we discussed in Slack, it seems to be a bug. Let's label it so that we can plan it for upcoming iterations.

**Comment by shoon2430** [comment]
Thank you!

**Comment by absoludity** [comment]
Hrmm, so we ensured that the repo is fetched from the kubeapps cluster when installing, but failed to do the same with the other actions. I'll leave this for Dmitri, hopefully we can do exactly what we've done for the install action.

We could (and should) also update the existing CI multicluster test to ensure upgrade and delete work.
