### ISSUE TITLE
Space in repo name fails...

### ISSUE THREAD

**Issue by allen-servedio** [kubeapps/kubeapps#323]
When adding a new app repo, if there is a space in the name of the repo, it will fail with your general error message (something went wrong, check for network issues, check the Javascript console, etc...). When I look at the Javascript console here is what I see as the response:

```
Request URL: http://localhost:64560/api/kube/apis/kubeapps.com/v1alpha1/namespaces/kubeapps/apprepositories
Request Method: POST
Status Code: 422 Unprocessable Entity
Remote Address: 127.0.0.1:64560
Referrer Policy: no-referrer-when-downgrade
Connection: keep-alive
Content-Length: 1016
Content-Type: application/json
Date: Mon, 21 May 2018 14:11:23 GMT
Server: nginx/1.12.2
```

I think if you just do some basic validation and require that the name not have spaces in it, it would be a better use experience.

**Comment by prydonius** [comment]
Thanks @allen-servedio, agreed! I believe #318 covers a similar issue so I will move your comment to that issue.
