### ISSUE TITLE
Add switch to enable/disable operators support

### ISSUE THREAD

**Issue by ppbaena** [kubeapps/kubeapps#3252]
The Operator support which was added to Kubeapps was done so rather urgently and has the Dashboard communicating directly with the K8s API server.

We're currently removing all call-sites in the dashboard which talk directly to the K8s API server and instead replacing them with package-specific plugins.

We need to ensure that Kubeapps can be run without operator support (which will be the default) so that the frontend is not proxying requests to the k8s API server.  As we will want CI to be running our normal tests without any proxying to the K8s API server, the normal CI tests will run with operator support disabled (the default). We need to evaluate whether we should also run a separate CI job with the operator support to ensure it stays working.

We should also evaluate how much effort would be involved to replace the Operator functionality in the dashboard with a packaging plugin, together with the community use of the operator support.

**Comment by absoludity** [comment]
I've updated the description and moved this to the discussion column, since it's required (and a natural part of) the current work that I'm doing to remove the calls to the K8s API server.
