### ISSUE TITLE
Kubeapps multi cluster is not working

### ISSUE THREAD

**Issue by banicr** [kubeapps/kubeapps#3255]
### Description:

 While installing Kubeapps it is not always gets successful, Sometimes it gives “failed to exchange credentials”.

### Steps to reproduce the issue:

1. Configured the OIDC provider (CSP)
2. Installed the nginx-ingress controller
3. Installed the cert-manger and ClusterIssuer
4. Created the custom values.yaml file and added the contents related to my environment. (for multi cluster added apiServiceURL, CertificateAuthorityData and ServiceToken).
5. Installed the kubeapps using the custom values.yaml file
6. Configured Rbac

### Describe the results you received:

Kubeapps can not be accessed and it will be stuck in the login page

### Describe the results you expected:

Should be able to login into the kubeapps and deploy an application

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

- Output of `helm list -n <kubeapps-namespace> <kubeapps-release-name>`:

```
NAME    	NAMESPACE	REVISION	UPDATED                               	STATUS  	CHART         	APP VERSION
kubeapps	kubeapps 	1       	2021-08-11 15:38:38.46883253 +0000 UTC	deployed	kubeapps-7.2.1	2.3.3
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1+wcp.3", GitCommit:"fb53e772aa2828c695b1f6b9fe83c63f87c27cf6", GitTreeState:"clean", BuildDate:"2021-02-05T05:07:45Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7+vmware.1", GitCommit:"c1a2f0ee316b35eca4ef6a7cb15ec9cc31a13f8f", GitTreeState:"clean", BuildDate:"2021-05-24T18:38:12Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by absoludity** [comment]
Thanks for creating a separate issue. Copying my reply to the email where we discussed this:

> This is an error you're seeing after installing Kubeapps while trying to login right? (Rather than while installing? At least in the code I can only see this error when authenticating, not while installing Kubeapps). From looking at the code, this error means that the configuration for the running Kubeapps (at that time, could be dependent on installation state of other non-kubeapps components) resulted in Kubeapps being unable to talk to the Pinniped service to exchange the user's OIDC token for a credential provided by Pinniped. If you see this happen, please check the logs of the pinniped-proxy service and create an issue on our Github issue tracker (ensuring there is no private info in the logs that you include). The logs should show us why Kubeapps was unable to talk with Pinniped as expected.

Can you please attach the logs from the pinniped-proxy pod from the time when you trigger this issue? I cannot reproduce it right now, so the extra information would be very helpful to a timely resolution :)
