### ISSUE TITLE
Can’t select namespaces for other clusters in kubeapps for multicluster configuration

### ISSUE THREAD

**Issue by banicr** [kubeapps/kubeapps#3257]
### Description:

can’t select namespaces for other clusters in kubeapps for multicluster configuration.

### Steps to reproduce the issue:

1. Configured the OIDC provider (CSP)
2. Installed the nginx-ingress controller
3. Installed the cert-manger and ClusterIssuer
4. Created the custom values.yaml file and added the contents related to my environment. (for multi cluster added apiServiceURL, CertificateAuthorityData and ServiceToken).
5. Installed the kubeapps using the custom values.yaml file
6. Configured Rbac

### Describe the results you received:

Namspaces will be disabled and can not enable it

### Describe the results you expected:

Should be able to select namespaces for other clusters to switch between clusters.

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

- Output of `helm list -n <kubeapps-namespace> <kubeapps-release-name>`:

```
NAME    	NAMESPACE	REVISION	UPDATED                               	STATUS  	CHART         	APP VERSION
kubeapps	kubeapps 	1       	2021-08-11 15:38:38.46883253 +0000 UTC	deployed	kubeapps-7.2.1	2.3.3
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1+wcp.3", GitCommit:"fb53e772aa2828c695b1f6b9fe83c63f87c27cf6", GitTreeState:"clean", BuildDate:"2021-02-05T05:07:45Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7+vmware.1", GitCommit:"c1a2f0ee316b35eca4ef6a7cb15ec9cc31a13f8f", GitTreeState:"clean", BuildDate:"2021-05-24T18:38:12Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by absoludity** [comment]
With a slight edit to point to the separate issue you've created, here was my response:

> So at this point you are somehow authenticated and have successfully switched to the other cluster? (Interested to know what was different from [#3256] above that you are now able to authenticate with the other cluster). The reason you can't select namespaces is because Kubeapps does not have access to list namespaces on the other cluster. You either need to ensure that the user has the related RBAC to do so on the other cluster, or ensure that your [clusters config includes a service account token for the other cluster linked to RBAC that allows listing namespaces](https://github.com/kubeapps/kubeapps/blob/master/docs/user/deploying-to-multiple-clusters.md#a-kubeapps-configuration-example), so that Kubeapps can use that to fetch the namespaces.

Can you please show the Javascript debugger request from Kubeapps when it tries to get the namespaces. You'll see it appear in the Network tab of your browser debugger as soon as you select the cluster. It'll look like this:

![kubeapps-get-namespaces-request](https://user-images.githubusercontent.com/497518/129512458-988c3e81-db18-41a4-b8c2-ab389cf12293.png)

Assuming that request is not returning a 200 for you, I'm keen to see what the response tab shows (see the tab on the bottom right of the above screenshot).
