### ISSUE TITLE
when I try to deploy application in kubeapps default cluster, it immeadiately signs out

### ISSUE THREAD

**Issue by banicr** [kubeapps/kubeapps#3258]
### Description:

 If I try to deploy any application on default cluster, it immediately signs out.

### Steps to reproduce the issue:

1. Configured the OIDC provider (CSP)
2. Installed the nginx-ingress controller
3. Installed the cert-manger and ClusterIssuer
4. Created the custom values.yaml file and added the contents related to my environment. (for multi cluster added apiServiceURL, CertificateAuthorityData and ServiceToken).
5. Installed the kubeapps using the custom values.yaml file
6. Configured Rbac

### Describe the results you received:

 If I try to deploy any application on default cluster, it immediately signs out.

### Describe the results you expected:

Should be able to deploy application.

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

- Output of `helm list -n <kubeapps-namespace> <kubeapps-release-name>`:

```
NAME    	NAMESPACE	REVISION	UPDATED                               	STATUS  	CHART         	APP VERSION
kubeapps	kubeapps 	1       	2021-08-11 15:38:38.46883253 +0000 UTC	deployed	kubeapps-7.2.1	2.3.3
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1+wcp.3", GitCommit:"fb53e772aa2828c695b1f6b9fe83c63f87c27cf6", GitTreeState:"clean", BuildDate:"2021-02-05T05:07:45Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7+vmware.1", GitCommit:"c1a2f0ee316b35eca4ef6a7cb15ec9cc31a13f8f", GitTreeState:"clean", BuildDate:"2021-05-24T18:38:12Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by absoludity** [comment]
My reply via email:

> So this one is unrelated to any multi-cluster setup right? Given that you can reproduce this one also, can you please create an issue on our Github project. What would be very helpful is a screenshot of the requests tab of the browser debugger when this happens, showing the response of the request that is returning the 401. This will help us identify which request and why.

Can you please attach the above screenshot so we can find out why Kubeapps thinks you don't have permission to deploy the app? It could be a bug in our authentication proxy, or it could be missing RBAC for the user. Hard to say without more info.

**Comment by banicr** [comment]
Hi @absoludity ,

kubeapps page is getting stuck in login. and I see the below errors in kubeapps pinniped-proxy container

logs:
INFO  pinniped_proxy > Listening on http://0.0.0.0:3333
 ERROR pinniped_proxy::service > Unauthorized by pinniped: authentication failed

Caused by:
    authentication failed
 INFO  pinniped_proxy::service > GET https://kubernetes.default/ 401 Unauthorized
 ERROR pinniped_proxy::service > Unauthorized by pinniped: authentication failed
 
 Please help me resolve this.
