### ISSUE TITLE
[kubeapps-apis] Add `repoURL`, `home` and `sources` to `AvailablePackageDetail`

### ISSUE THREAD

**Issue by absoludity** [kubeapps/kubeapps#3279]
### Description:

While Antonio was adapting the UX to use the new client and API, he noted that three fields used in the current `AppView` are not yet exposed via the `AvailablePackageDetail` message. These are:

* `repoURL`
* `home`
* `sources`

which are used to display 
![image](https://user-images.githubusercontent.com/11535726/127780417-33acbc5c-a439-4390-968e-7fdd14dbe91f.png)

(need to verify with the current AppView exactly where the info is used).

We need to add these fields to be able to reproduce the current Helm view.

Splitting off from #3165 to focus the iteration.

**Comment by gfichtenholt** [comment]
@absoludity Michael I assume that I just need to update the design doc, core .proto file and fluxv2 plug-in with this. In other words, direct-helm plug-in implementation is outside the scope for this. Please confirm. Thanks

**Comment by absoludity** [comment]
We need to populate those fields with the direct helm plugin. If you don't want to do that, that's fine - I can.

**Comment by gfichtenholt** [comment]
ah, ok, misunderstanding then. I will try and take care of it
