### ISSUE TITLE
Dockerfile for dashboard does not include yarn install

### ISSUE THREAD

**Issue by wojciechka** [kubeapps/kubeapps#332]
This makes a fresh clone of kubeapps not build successfully due to missing `react-scripts-ts` binary.

The following should be enough to run `yarn install` and only run it whenever included packages change - such as:

```
--- a/dashboard/Dockerfile
+++ b/dashboard/Dockerfile
@@ -1,5 +1,8 @@
 FROM node:8.9 AS build
 WORKDIR /app
+COPY package.json /app/package.json
+COPY yarn.lock /app/yarn.lock
+RUN yarn install
 COPY . /app
 RUN yarn run build
```

At this point `node_modules` could also be added to `dashboard/.dockerignore` so any local modules are not injected into the first stage of the build.

**Comment by sameersbn** [comment]
The following should suffice I think. 

```diff
-RUN yarn run build
+RUN yarn install && yarn run build
```

However I am not sure why this was not being done in the dockerfile by default. @prydonius should have a better idea.

**Comment by prydonius** [comment]
I guess there is no particular reason for this, in the CI `yarn install` happens outside of the Docker build, so `COPY . /app` already includes all the dependencies.
