### ISSUE TITLE
Draft version of new API and pluggable architecture documentation

### ISSUE THREAD

**Issue by ppbaena** [kubeapps/kubeapps#3328]
Provide some information about structural changes in Kubeapps 2.4.0, though it is not intended to be a technical and exhaustive documentation, but a first approach to the new pluggable architecture and API (that is still in progress) to facilitate the adoption by Kubeapps users.

**Comment by antgamdia** [comment]
As a first step towards, the upcoming 2.4.0 version will include the new API docs as part of the deployed API documentation portal (accessible via _right menu -> API documentation) 

![image](https://user-images.githubusercontent.com/11535726/131653222-a12a1e21-548d-4b26-a539-f0958c110dac.png)

Also, a quick outline will appear as part of the release docs.

**Comment by absoludity** [comment]
Given I've just written a blog post about this, it'd be easy to add the docs now. I'll plan to do this next week.
