### ISSUE TITLE
[kubeapps-apis] the implementation of core packaging and plugin packages should also be versioned, like plugin implementations.

### ISSUE THREAD

**Issue by ppbaena** [kubeapps/kubeapps#3329]

**Comment by antgamdia** [comment]
### Tracking questions/decisions while implementing Core Operations

**Question**: should every operation have a `Plugin` as part of the request? 
**Motivation**: from the UI perspective, a user might want to filter their installed/available applications based on the packaging system. Right now, for instance `GetInstalledPackageSummaries`  just have `Context` and `PaginationOptions`.
**Decision**:  TBD


cc @absoludity

**Comment by absoludity** [comment]
If it is to filter the results, we'll need something other than just the singular plugin (given that you may want to filter for results from multiple plugins). I'd say longer term we do want to filter by plugin on the core API, but not necessary right now?
