### ISSUE TITLE
Invalid Version: latest

### ISSUE THREAD

**Issue by kfirfer** [kubeapps/kubeapps#3347]
Hello

Im using kubeapps 2.4.0 and im getting this error if the docker image tag is "latest":
```
Invalid Version: latest
```

Screenshot :

![ksnip_20210905-040944](https://user-images.githubusercontent.com/7741545/132111702-d7023843-7aa4-4b7c-ba06-f3617ea16680.png)

**Comment by absoludity** [comment]
Thanks @kfirfer . Yes, we incorrectly assumed with the new Dashboard code that the appVersion must be semver2 compatible. Fixed in the attached PR.
