### ISSUE TITLE
Use non-persistent emptyDir volume for MongoDB deployment

### ISSUE THREAD

**Issue by prydonius** [kubeapps/kubeapps#336]
Switching to a non-persistent MongoDB deployment by default will reduce the permission issues we often see with the Bitnami MongoDB container in certain environments.

We use MongoDB as a cache, and if the data is lost it can be easily repopulated either automatically (at next sync cycle), or manually by clicking on "Refresh" in the App Repositories page.

cc @sameersbn

**Comment by sameersbn** [comment]
Yes, since kubeapps uses mongodb primarily for caching only we could remove the default persistence configuration. But have you come across any reports of failing kubeapps deployments as a result of permission issues in mongodb volumes?

**Comment by andresmgot** [comment]
I think this is the comment we received:

> is there an option to change the volume size for the mongodb-data PVC in kubeapps that's used by mongodb to store kubeapps' data? (Oracle refuses to create a volume that's less than 50Gi)

BTW, if it is used just to store cache, why not using a more lightweight service?

**Comment by prydonius** [comment]
@andresmgot that's actually not where this feedback comes from, but it would also help for that case too.

> BTW, if it is used just to store cache, why not using a more lightweight service?

The initial assumption was that we were going to need a fully-fledged database to store lots of different types and data. However, we've gone back on that a little bit and now use CRDs when we can (e.g. AppRepositories). What ended up happening is we only store chart metadata cache in MongoDB now. We may want to rethink and switch back to something more lightweight like Redis, but I don't think we have the capacity to do that right now.

**Comment by arapulido** [comment]
@prydonius @sameersbn We should investigate the issues people are having with permissions, and file them against our mongodb chart (this is orthogonal to remove the PV from kubeapps or not)

**Comment by prydonius** [comment]
@arapulido agreed, and this is what we've been doing so far.
