### ISSUE TITLE
Unable to use Kubeapps under a subpath

### ISSUE THREAD

**Issue by antgamdia** [kubeapps/kubeapps#3368]
### Description:

Eventually, we get this odd error in the `GetInstalledPackagesSummaries` operation:

![image](https://user-images.githubusercontent.com/11535726/132399757-60e87dfc-bb6c-4882-ac1f-42d676e21057.png)

### Steps to reproduce the issue:

1. Install Kubeapps under a sub-path, for example, using the local dev environment, with:

```diff
--- a/docs/user/manifests/kubeapps-local-dev-values.yaml
+++ b/docs/user/manifests/kubeapps-local-dev-values.yaml
@@ -18,6 +18,8 @@ kubeappsapis:
 ingress:
   enabled: true
   hostname: localhost
+  path: "/kubeapps(/|$)(.*)"
+  pathType: Prefix
   tls: true
   extraTls:
   - hosts:
@@ -27,3 +29,5 @@ ingress:
     nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
     # Required for ingress-nginx 1.0.0 for a valid ingress.
     kubernetes.io/ingress.class: nginx
+    nginx.ingress.kubernetes.io/configuration-snippet: "rewrite ^(/kubeapps)$ $1/ redirect;"
+    nginx.ingress.kubernetes.io/rewrite-target: "/$2"
```

2. Login and try to view applications

### Describe the results you received:

`Response closed without grpc-status (Headers only) in GetInstaledPackageSummaries`.

Specifically, the grpc request to the APIs server does not include the prefix:
![GetInstalledPackageSummaries-no-prefix](https://user-images.githubusercontent.com/497518/132426382-e2aefe4a-aca9-4938-bb2d-8b795eaa0d3c.png)

### Describe the results you expected:

The grpc request should be prefixed just like all other requests.

### Additional information you deem important (e.g. issue happens only occasionally):

Slack thread discussing this issue: https://kubernetes.slack.com/archives/C9D3TSUG4/p1631011129013300

### Version of Helm, Kubeapps and Kubernetes:

Kubeapps  2.4.0

**Comment by absoludity** [comment]
Actually, this one is reproducible, but isn't the same cause as the one we saw during release. The cause here is that there's a subpath is being used for the Kubeapps appliication, while the new client in the dashboard uses an absolute url `/apis`. You can verify that with a local kind cluster that it doesn't work.

So the request is never even getting to the apis server at all. I'm fixing that (one-liner).
