### ISSUE TITLE
GCP broker testing and documentation

### ISSUE THREAD

**Issue by arapulido** [kubeapps/kubeapps#339]
We want to test Kubeapps Service Catalog integration with as many brokers as possible.

We should test it with the GCP broker, file any issues if it doesn't work, and document it and blog about it if it does.

**Comment by prydonius** [comment]
sub task of #686

**Comment by arapulido** [comment]
This is fix with https://github.com/kubeapps/kubeapps/blob/master/docs/user/service-catalog.md
