### ISSUE TITLE
Unable to view InstalledPackageSummaries during release

### ISSUE THREAD

**Issue by absoludity** [kubeapps/kubeapps#3394]
During the release of Kubeapps 2.4, the release tests hit an issue where it failed to view InstalledPackageSummaries , but could view AvailablePackageSummaries and individual packages.

The error is reported as: `Response closed without grpc-status (Headers only)` in GetInstaledPackageSummaries

We were unable to reproduce this as it was displayed in the release env (but were able to force the similar error for different reasons by dropping traffic in various scenarios, such as #3340).

We need to investigate what is causing this error in the particular situation on the release instance and re-enable those tests.

**Comment by absoludity** [comment]
I've tried to reproduce this locally with nginx directives, but afaict I can only remove headers from the proxied response, not trailers. I've also verified that for a successful request, grpc-web *always* sends the `grpc-status` as a trailer (it is only sent as a header on error or if for some other reason the response has not had headers or body yet sent).

When we had the original environment up, we noticed that the `GetAvailablePackageSummaries` request (and `GetAvailablePackageDetail`) were working without issue, so it was specific to the `GetInstalledPackageSummaries` response. This seems to rule out any networking issues on the one side that would result in the trailers not being present, and on the other side appears to rule out it being a browser/client issue.

We also noted that the data was actually present in the response (as in, it had been served correctly).

**Comment by absoludity** [comment]
I can manually reproduce this by setting a deadline on the context which is smaller than the time taken to serve `GetAvailablePackageSummaries`. The patch is:

```diff
--- a/cmd/kubeapps-apis/server/server.go
+++ b/cmd/kubeapps-apis/server/server.go
@@ -21,6 +21,7 @@ import (
        "fmt"
        "net"
        "net/http"
+       "time"
 
        "github.com/improbable-eng/grpc-web/go/grpcweb"
        "github.com/soheilhy/cmux"
@@ -104,6 +105,11 @@ func Serve(serveOpts ServeOptions) {
 
        httpSrv := &http.Server{
                Handler: http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
+                       // Update the request and with a deadline of 500ms.
+                       clientDeadline := time.Now().Add(time.Duration(500) * time.Millisecond)
+                       ctx, cancel := context.WithDeadline(r.Context(), clientDeadline)
+                       defer cancel()
+                       r = r.WithContext(ctx)
                        if webrpcProxy.IsGrpcWebRequest(r) || webrpcProxy.IsAcceptableGrpcCorsRequest(r) || webrpcProxy.IsGrpcWebSocketRequest(r) {
                                webrpcProxy.ServeHTTP(w, r)
                        } else {
```

If I build that image, the `Apps` tab, which calls `GetAvailablePackageSummaries` returns the expected error, but with a 0 byte response, since it is terminating the connection before the data/body is set. In the release env where we originally saw this, the data was present on the body, just not the grpc-status in the trailers.

**Comment by absoludity** [comment]
Furthermore, we're no longer seeing this issue in our release environment. What's clear is that it's a network issue... something that is truncating the longer response, as shown by the manual triggering of the result by the above patch.

I'll move this issue to waiting for review for now. If we get more info from others seeing the same error message (we had one person yesterday reporting internally), we need to find out more details about the ingress controller and configuration, or anything else that could be cancelling/truncating longer requests.

**Comment by ppbaena** [comment]
No more info related to this issue, so I move to close. In case we get more info from others seeing the same error message we can re-open it.
