### ISSUE TITLE
{IPv6} Issue to Sync Charts repo

### ISSUE THREAD

**Issue by valentin2105** [kubeapps/kubeapps#340]
Hi,

I'm currently trying KubeApps in IPv6-only Kubernetes cluster, 

After making few small change (Nginx's bind, DNS Name) on the kubeapps.yaml file (from kube-apps up), I'm able to reach the UI, list repo, create serverless stuffs ... 

I'm facing  only one issue, It's about syncing repo to Mongo DB. 

My Jobs `apprepo-sync-stable` for example stuck from 30mn, without any chart in the UI and any logs in the Pod.  

While inspecting the pod, the args point on the right Mongo DNS name & the process seem running, but nothing happend.

Any idea how to debug that ? 

Really looking forward got the charts on the UI :smile:  

Thanks !

**Comment by prydonius** [comment]
hey @valentin2105, that's an interesting issue. Are you able to connect to MongoDB using a MongoDB client pod? 

1. Get your MongoDB password: `kubectl get secrets -n kubeapps mongodb -o jsonpath='{.data.mongodb-root-password}' | base64 --decode`
2. Run `kubectl run -n kubeapps mongodb-client --image bitnami/mongodb --rm --tty -i --command -- bash`
3. Inside the bash prompt run `mongo --host mongodb -u root -p --authenticationDatabase admin` and paste the MongoDB password when prompted.

This will help verify that it's not a networking issue in your cluster.

**Comment by valentin2105** [comment]
Hi @prydonius , 

It seem Mongo doesn't bind in IPv6, its, I think it's the problem.

I currently trying to fix that, I will confirm here if it solve the problem. 

Any idea how to change the Bitnami config created on the MongoDB container ? a configMap maybe will be the simpliest solution ?

**Comment by valentin2105** [comment]
I confirm the issue was the MongoDB binding. 

Any Idea how to solve this, with a clean way ? 

'Cause now, I launched a Socat binding in the pod, but it's not really clean stuffs.

**Comment by sameersbn** [comment]
@valentin2105 as a workaround can you try the following and let us know the results?

```
kubeapps up --dry-run | \
  sed -e 's|bitnami/mongodb:3.4.*|mongo:3.6-jessie\n        args: ["--ipv6"]|' \
      -e 's|name: MONGODB_ROOT_PASSWORD|name: MONGO_INITDB_ROOT_USERNAME\n          value: "root"\n        - name: MONGO_INITDB_ROOT_PASSWORD|' \
      -e 's|/bitnami/mongodb|/data/db|' \
  | kubectl apply -f -
```

**Comment by valentin2105** [comment]
@sameersbn  It work at glance, thanks. 

You think that `--ipv6` could become an "Kubeapps up" arguments that make theses change ?

**Comment by sameersbn** [comment]
@valentin2105 i think we should make a request to add an option to enable ipv6 by default or have a env configuration to enable it. Alternatively we could also mount a custom configuration in kubeapps with ipv6 enabled.

**Comment by prydonius** [comment]
@sameersbn AFAIK MongoDB 3+ should have it enabled by default, right?

**Comment by sameersbn** [comment]
@prydonius it's the `mongo` client that has ipv6 support enabled by default (https://docs.mongodb.com/manual/reference/program/mongo/#cmdoption-mongo-ipv6). For the `mongod` server, the `--ipv6` flag needs to be specified for it listen to connections on ipv6 addresses (https://docs.mongodb.com/manual/reference/program/mongod/#cmdoption-mongod-ipv6)

**Comment by sameersbn** [comment]
@here I've opened a issue at bitnami/bitnami-docker-mongodb#97 requesting them to enable ipv6 by default.

**Comment by prydonius** [comment]
> For the mongod server, the --ipv6 flag needs to be specified for it listen to connections on ipv6 addresses (https://docs.mongodb.com/manual/reference/program/mongod/#cmdoption-mongod-ipv6)

Thanks for that clarification! We can keep this issue open to update to the new version of MongoDB with this support when that lands. @sameersbn in the meantime, can we configure the startup options for the Bitnami MongoDB container?

**Comment by valentin2105** [comment]
@sameersbn If IPv6 is enabled by default on bitnami/mongodb, it would be awesome and 100% legit I think. (not noticeable for IPv4 users).

Thanks ! I close this one ?

**Comment by prydonius** [comment]
@valentin2105 let's keep it open for now, so we can remember to update MongoDB in Kubeapps when support for ipv6 lands upstream :).

**Comment by valentin2105** [comment]
Cool, Thanks @prydonius

**Comment by sameersbn** [comment]
> can we configure the startup options for the Bitnami MongoDB container?

unfortunately the bitnami/mongodb container does not allow users to specify command line arguments for `mongod`. The interim fix for this is to define a configmap for the mongod configuration in the manifests.

**Comment by sameersbn** [comment]
> unfortunately the bitnami/mongodb container does not allow users to specify command line arguments for mongod.

Oh! it seems we can supply `MONGODB_EXTRA_FLAGS` env param for this

**Comment by sameersbn** [comment]
@valentin2105 could you please try the following command to deploy kubeapps and let me know if it works.

```bash
kubeapps up --dry-run | \
  sed -e 's|bitnami/mongodb:3.4.*|bitnami/mongodb:3.6|' \
      -e 's|name: MONGODB_ROOT_PASSWORD|name: MONGODB_EXTRA_FLAGS\n          value: "--ipv6 --bind_ip 0.0.0.0,::"\n        - name: MONGODB_ROOT_PASSWORD|' \
  | kubectl apply -f -
```

**Comment by valentin2105** [comment]
@sameersbn 
Sorry for the delay. Yeah it work at glance ! 

Thanks ! I close this one, if would be great to drop that somewhere on kubeapps Docs ;)

**Comment by prydonius** [comment]
@sameersbn didn't the MongoDB image get updated to support ipv6?

**Comment by sameersbn** [comment]
@prydonius PR #377 upgrades the mongo image with ipv6 enabled by default. /cc @valentin2105
