### ISSUE TITLE
front: edition of an apprepository filter clears it

### ISSUE THREAD

**Issue by dud225** [kubeapps/kubeapps#3447]
### Description:

When creating a new Application Repository, all works as expected. But when editing it to filter out some charts, there is no error on the UI but the resulting `apprepositories` filter is reset:
```
  filterRule:
    jq: ""
```

### Steps to reproduce the issue:

1. Create an App Repository, e.g. [Bitnami](https://charts.bitnami.com/bitnami)
2. Once the App Repository is creted, edit it to modify the filter, eg `nginx, jenkins`
3. Check the resulting `apprepositories`, the filter will be blank even if one was set up at the time of creation

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}
```

- Output of `helm list -n <kubeapps-namespace> <kubeapps-release-name>`:

```
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
kubeapps        kubeapps        5               2021-09-08 10:10:27.536393583 +0000 UTC deployed        kubeapps-7.4.0  2.4.0
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.4-3+e5758f73ed2a04", GitCommit:"e5758f73ed2a04898a6bba130459e17b95402dcd", GitTreeState:"clean", BuildDate:"2021-08-12T15:05:00Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.4-3+e5758f73ed2a04", GitCommit:"e5758f73ed2a04898a6bba130459e17b95402dcd", GitTreeState:"clean", BuildDate:"2021-08-12T15:00:31Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by absoludity** [comment]
Thanks @dud225 . Easy to repro. Haven't dug, but from the network request, it looks like the dashboard is simply not setting the filters when updating the app repo. For example, I see the following when setting the filters to "apache,jenkins"
![edit-repo-no-filters](https://user-images.githubusercontent.com/497518/134123285-93ee8d05-4715-47a5-a59e-b9d4a9bb5e3a.png)

Appreciate the help you're giving us lately so reluctant to say patches welcome. We'll prioritise it in our next planning meeting if someone hasn't grabbed it already :)
