### ISSUE TITLE
Tiller release gets updated twice when migrating to Kubeapps

### ISSUE THREAD

**Issue by prydonius** [kubeapps/kubeapps#345]
In #330, I discovered that migrating a release results in the Tiller release getting updated twice. It should only be updated once.

Steps to reproduce:

1. Checkout code from #330 
2. Create a Helm release using the CLI `helm --tiller-namespace=kubeapps install stable/redis`
3. Migrate it in Kubeapps
4. Notice that the Helm release is now at revision 3 `helm --tiller-namespace=kubeapps list`

This might actually be an issue during upgrade also, I haven't verified this.

**Comment by andresmgot** [comment]
I am not sure if this is an issue. It is true that the revision gets bumped but if there are no changes the deployment won't be updated. This is the same behavior than when you execute `helm upgrade ...` several times.

**Comment by andresmgot** [comment]
Ah, sorry I misunderstood it. That's an issue yes. It's caused because the controller modifies the HelmRelease metadata to add a `finalizer` and that gets interpreted as an upgrade. This PR: https://github.com/bitnami-labs/helm-crd/pull/31 should fix that.
