### ISSUE TITLE
Add `BUF_TOKEN` to the circleci environment vars

### ISSUE THREAD

**Issue by ppbaena** [kubeapps/kubeapps#3510]
Edit (@antgamdia)

I once got an error when downloading the `buf` binary from their website as part of our dockerfile. It was a sort of rate limit and, in the error message, they recommended using a token if running it a CI system (https://docs.buf.build/bsr/authentication/)

However. I'm wondering: `buf` is more that the tool, it is a whole repository  (BSR) for pushing the proto files, so that others can use it as a dependency. Should we start pushing our proto files there?? See an example here: https://buf.build/envoyproxy/protoc-gen-validate/file/main/validate/validate.proto

Benefits? Near future, I don't see any. Long term, other projects using grpc and buf will be able to import our definitions really easily. 
Cons? An additional thing to maintain with no immediate outcome.

So, some possibilities I foresee:

1. Close this issue straight away as it is no longer reproducible.
2. Create an account there and add the token to our CI, just in case
3. Same as in 2. but also push the proto files to BSR
4. Same as in 3. but also add a CI action to always sent the latest proto files to BSR.

See what you think

**Comment by antgamdia** [comment]
As per the (offline) discussion, let's go with (2) and let's plan, in the future, to add our API spec to BSR.

**Comment by antgamdia** [comment]
Token created and added to circleci. Credentials are stored and shared according to our protocols.

BTW, I've pushed the current proto files to a private BSR registry, see how it looks like:

![image](https://user-images.githubusercontent.com/11535726/135422454-ef2fc78c-62a6-43da-8957-033de26b4229.png)
