### ISSUE TITLE
Kubeapps forms no longer compatible with "OpenAPI Schema Object" schemas

### ISSUE THREAD

**Issue by antgamdia** [kubeapps/kubeapps#3526]
Since a few hours ago, our upgrade/rollback tests started failing for no specific reason. It is probably an upstream issue related to the latest Apache chart used in our test.

**Comment by antgamdia** [comment]
Well...  it seems the schema used in the Apache chart changed... https://github.com/bitnami/charts/commit/e3a8529be0fb7b3269e0105f2571d3b850891aa5#diff-ca31c7e60e6b0504ec10491ce8d590588c00763730b6ee3e18382f14f9cf688b

We ought to double-check it internally to really know if this change is going to be expanded to the rest of charts. If so... the form won't get rendered anymore unless we find out what's happening.

**Comment by absoludity** [comment]
Thanks for the investigation. I think we can close this for now since the schema change in the catalog was reverted?
