### ISSUE TITLE
Flux plugin requires an additional config getter

### ISSUE THREAD

**Issue by absoludity** [kubeapps/kubeapps#3560]
### Description:

For Helm (and Carvel, fwiw), all requests to the kubeapps-apis service are synchronous requests where we avoid privilege escalation by carrying out the underlying request to the k8s API server with the users credentials.

This is done by providing each plugin (upon initialization) with a kubernetes config getter function which takes the request context and returns a k8s config to use.

This isn't suffecient for the flux plugin which additionally runs out-of-request interactions with the Kubernetes API server. Although we've already ensured that if the flux plugin is selected, that the service account will be granted additional read privileges, we also need to ensure that the plugin can get a config based on the service account rather than the request context.

As [outlined by Greg in a comment](https://github.com/kubeapps/kubeapps/blob/master/cmd/kubeapps-apis/server/plugins.go#L325-L342), the only way to ensure the flux plugin can interact with the required privileges is by patching the code to use the in cluster config (ie. configured service account).

FWIW, I think the solution here is just to update the flux plugin so that for those out-of-band requests to the API server, the plugin simply uses the in cluster config rather than the provided configGetter function. The plugin can already grab this directly with `rest.InClusterConfig()` since it doesn't support clusters other than the one one which Kubeapps (and the apisserver/plugin) is running. We may later want to make this available as a helper to plugins with a cluster-aware function (ie. `getServiceAccountConfig(cluster string)`, but until that is certain, it's simpler for the flux plugin to use `rest.InClusterConfig()`.

cc @gfichtenholt Documenting here as an issue so we can discuss and fix :)

**Comment by gfichtenholt** [comment]
don't forget it also has to work in unit tests with the fake k8s  client

**Comment by gfichtenholt** [comment]
ok, so it looks like the current state after #3559 got merged is that flux plug in is broken and prevents kubeappsapis server from starting (obviously if enabled) due to stuff like this at startup

Error: failed to initialize plugins server: failed to register plugins: plug-in "name:\"fluxv2.packages\" version:\"v1alpha1\"" failed to register due to: customresourcedefinitions.apiextensions.k8s.io "helmrepositories.source.toolkit.fluxcd.io" is forbidden: User "system:anonymous" cannot get resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope

So this needs to be fixed ASAP. Is this PR something you wanted me to implement or were you intending to make these changes yourself?

**Comment by gfichtenholt** [comment]
No problem, I will take of it

**Comment by absoludity** [comment]
Actually I thought this was already broken as per your [comment in the code](https://github.com/kubeapps/kubeapps/blob/master/cmd/kubeapps-apis/server/plugins.go#L325-L342) to which I had linked to in the description above, which says, in particular that you were (only) able to run your integration tests successfully with the manual code change that you outlined there? Or maybe I'm missing something? At least, that was the trigger for this issue. I would think they will still pass with that manual patch in your comment, but haven't checked. Or maybe you meant that it was passing if you ran with the `unsafeUseDemoSA` was true?

> So this needs to be fixed ASAP. Is this PR something you wanted me to implement or were you intending to make these changes yourself?

That'd be great if you can update the flux plugin to directly use the InClusterConfig for the async interactions with the api server, only. Let me know if you think there's a better way (or don't want to do it or whatever).
 
> As a side note, this is where my integration tests running on CI would have come in handy. Your changes wouldn't have passed :-) Oh well

I would have thought your earlier branch with the comment outlining the manual patch required for your integration tests to pass would have also failed? But yep, either way, integration tests or a simple e2e test would also have caught it. We need to ensure the plugin can be tried *without* any unsafe RBAC, +1 to do it ASAP.

> No problem, I will take of it

Great, thanks.

**Comment by absoludity** [comment]
+1, probably returning an unauthorized or similar? Thanks.
