### ISSUE TITLE
UI: InternalError too much recursion when the ns exceeds some length

### ISSUE THREAD

**Issue by dud225** [kubeapps/kubeapps#3587]
Hello

when deploying a chart on a namespace that exceeds some length, e.g. `test1test2test3test4`, Kubeapps' UI fails and the user looses complete control:
![Capture d’écran de 2021-10-13 15-05-02](https://user-images.githubusercontent.com/17550475/137138849-089d26ad-ccf4-4d66-ae8c-eb1c821dca5b.png)
![Capture d’écran de 2021-10-13 16-27-26](https://user-images.githubusercontent.com/17550475/137153450-f9e0bb7e-192e-42b1-abd7-4836801c3e81.png)

There is no error outputted in the dashboard pods.

**Comment by absoludity** [comment]
That depends whether you can reproduce it reliably in some context? Are you able to reproduce it with your chart in the `test1test2test3test4` namespace?

Assuming your chart is private and can't be shared, the next best thing would be to create a public example of a minimal chart that exhibits the issue.

So it could just be that the combination of long namespace name and long chart or release name is causing the issue. Or something your chart in particular is doing with names that it creates for k8s resources? If you can find that, then create and attach a public chart tarball that we can use to trigger the issue, we can then work on improving the handling there.
