### ISSUE TITLE
Some Chart versions hidden from dropdown when deploying an application

### ISSUE THREAD

**Issue by cristian-aldea** [kubeapps/kubeapps#3588]
### Description:

We’re running into a very strange bug and need help since it’s affecting customers of our infrastructure product.

We use Kubeapps for customers to deploy applications, and we use Chartmuseum to store charts for them to use. However, when we want to select a version of an application to deploy, some versions are hidden.

I’ve done some testing, and all the versions we offer are indeed available in chartmuseum, they show up when we GET on /api/charts/chart-name, and they can be pulled using “helm pull” to get the tar bundle. However it seems that Kubeapps is failing to show all these versions in the dropdown. For example, we start off by seeing the versions 1.19.4, 1.19.5, and 1.19.6:

![Screen Shot 2021-10-13 at 11 08 31 AM](https://user-images.githubusercontent.com/23544999/137169738-02710eae-7221-4d17-b8e3-f2a3bbcfe198.png)

but when a test chart like 1.19.7-CCT-XXXX (a test chart created for testing changes introduced by a ticket) is uploaded, some versions start disappearing.

![Screen Shot 2021-10-13 at 11 13 14 AM](https://user-images.githubusercontent.com/23544999/137169821-12ecda4d-34cf-4a01-ac0b-f888b4ee4e16.png)

However, I know for sure that Kubeapps knows about these hidden versions, since older applications deployed using these versions can still be accessed:

![Screen Shot 2021-10-13 at 11 13 34 AM](https://user-images.githubusercontent.com/23544999/137169865-1562c328-35c2-4340-8fab-e66e4edaef87.png)

as opposed to showing us an error about the chart version not existing:

![Screen Shot 2021-10-13 at 11 31 07 AM](https://user-images.githubusercontent.com/23544999/137169941-d08b967c-51d8-4162-ad29-fd60baa0d3c2.png)

This leads me to believe that the dropdown is bugged in some way. We just started running into this issue, and it seems (not 100% sure on this) to start occurring when test charts (X.X.X-ABC-XXXX) are uploaded. Please tell us if you know anything about why this is happening. thank you for the help

Slack message: https://kubernetes.slack.com/archives/C9D3TSUG4/p1634139332089700

Our version history:
oct 6: we updated kubeapps chart to 7.5.4, app version 2.4.0
sept 9: we updated kubeapps chart to 7.4.0, app version 2..4.0
july 7, we updated kubeapps chart to 7.1.2, app version 2.3.2

### Steps to reproduce the issue:

1. Deploy chartmuseum and kubeapps
2. configure chartmuseum as an app repository for kubeapps
3. upload charts to chartmuseum
4. refresh the app repository on kubeapps ui, or by running the sync cronjob

### Describe the results you received:

Some chart versions don't show in the dropdown

### Describe the results you expected:

All chart versions show up in the dropdown

### Additional information you deem important (e.g. issue happens only occasionally):

We use particular version names when deploying test charts (chart which include changes related to a ticket). These charts have the format X.X.X-TICKET. This might be unexpected and might be partially causing the issue. but we've been doing this for years without running into this issue before.

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"dirty", GoVersion:"go1.16.6"}
```

- Output of `helm list -n <kubeapps-namespace> <kubeapps-release-name>`:

```
NAME    NAMESPACE       REVISION        UPDATED STATUS  CHART   APP VERSION
# nothing, we don't deploy kubeapps through helm install, but through argocd
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.8", GitCommit:"5575935422cc1cf5169dfc8847cb587aa47bac5a", GitTreeState:"clean", BuildDate:"2021-06-16T13:00:45Z", GoVersion:"go1.15.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.10-gke.301", GitCommit:"17ad7bd6afa01033d7bd3f02ce5de56f940a915d", GitTreeState:"clean", BuildDate:"2021-08-24T05:18:54Z", GoVersion:"go1.15.15b5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by cristian-aldea** [comment]
I see, thank you so much for the quick response explaining the issue. Yes (1) would allow us to quickly address the issue for now and (2) would be nice, since indeed some older versions aren't relevant, but might still be useful to deploy for testing and such.

**Comment by cristian-aldea** [comment]
Just quickly, for my own information, when was this change in the api made?

**Comment by absoludity** [comment]
> Just quickly, for my own information, when was this change in the api made?

We switched the create and update UX functions over to the new API with https://github.com/kubeapps/kubeapps/releases/tag/v2.4.1 so I assume it was that release (so 10 days ago).



> Also, let us know when these features will be implemented so we can organize the upgrade on our side. Now that we know what the behavior actually is we'll be able to manage it for now.

Will do, we'll discuss it in our next planning meeting (one week from now) and update it then (perhaps doing the first part in the next iteration). Let us know if it's not tenable to manage the issue and we'll give it a higher priority.

**Comment by cristian-aldea** [comment]
Thank you so much for implementing a fix for our issue!

Looking forward to the new release :)

**Comment by linhvuntu** [comment]
Hi there I'm using kubeapps helm version 12.2.4/ App version 2.6.2 and the issue still happens. 
I have updated the pluginConfig as below (increase all version display to 5), but the Package Versions dropdownlist still only show 3 major/minor/patch releases. Is there any param that I need to config?

  pluginConfig:
    core:
      packages:
        v1alpha1:
          versionsInSummary:
            major: 5
            minor: 5
            patch: 5

**Comment by absoludity** [comment]
Hi @linhvuntu . Just to double-check, the `pluginConfig` is an option of `kubeappsapis`, not a root option, as per the values.yaml:

https://github.com/vmware-tanzu/kubeapps/blob/a82349ee18211d7b781c74cd3974599e87b8a77b/chart/kubeapps/values.yaml#L1494-L1514

It looks as though you're seeing the default (of 3) because your specified values are having no effect (which makes sense if the `pluginConfig` isn't specified as an option of `kubeappsapis`). Let us know if that's the problem or we need to dig further. Thanks.

**Comment by linhvuntu** [comment]
Hi @absoludity , how to specify the  `pluginConfig` as an option of `kubeappsapis` ?

I have tried to to set the `enabledPlugins: [helm-packages, resources, core]` but there is no directory `/plugins/core` in the pod. What should  be the correct way then? Thanks

**Comment by absoludity** [comment]
Hi @linhvuntu . You shouldn't need to set `enabledPlugins` at all, just leave that one blank. To specify the `pluginConfig`, it's just a matter of setting that value when deploying the chart, so for example, your values file should contain:

```
kubeappsapis:
  pluginConfig:
    core:
      packages:
        v1alpha1:
          versionsInSummary:
            major: 5
            minor: 5
            patch: 5
```

From your previous example above, it looked like you thought `pluginConfig` was a root or global field in the values.yaml, as you'd not specified the `kubeappsapis` before it, which would mean that Helm just happily ignored your `pluginConfig`. Hope that's clearer.

**Comment by linhvuntu** [comment]
Hi @absoludity , ok now I get what it means by `root option`.. Actually I skipped the `kubeappsapis` in my example, the actual values that I set is exactly as you mentioned above. Because I just use default values.yaml and update the numbers.

`
kubeappsapis:
  enabledPlugins: []
  pluginConfig:
    core:
      packages:
        v1alpha1:
          versionsInSummary:
            major: 5
            minor: 5
            patch: 5
          timeoutSeconds: 300
`

And it's still not working. When checking the startup log, it show like this 
`+helm using custom config: [{{5 5 5} 300 false }]`

Does it mean the custom config is "false" to setup?

**Comment by linhvuntu** [comment]
> Hi @absoludity , ok now I get what it means by `root option`.. Actually I skipped the `kubeappsapis` in my example, the actual values that I set is exactly as you mentioned above. Because I just use default values.yaml and update the numbers.
> 
> kubeappsapis: enabledPlugins: [] pluginConfig: core: packages: v1alpha1: versionsInSummary: major: 5 minor: 5 patch: 5 timeoutSeconds: 300
> 
> And it's still not working. When checking the startup log, it show like this `+helm using custom config: [{{5 5 5} 300 false }]`
> 
> Does it mean the custom config is "false" to setup?

asdf

**Comment by absoludity** [comment]
So that config looks fine then. If I run Kubeapps without that config and check the logs of the kubeapps-apis server pod, I see that the helm custom config is `[{{3 3 3} 300 }]` as expected:

```
I0223 03:10:34.820621       1 root.go:36] "kubeapps-apis has been configured with serverOptions" serverOptions={Port:50051 PluginDirs:[/plugins/helm-packages /plugins/resources] ClustersConfigPath:/config/clusters.conf PluginConfigPath:/config/kubeapps-apis/plugins.conf PinnipedProxyURL:http://kubeapps-internal-pinniped-proxy.kubeapps:3333 PinnipedProxyCACert: GlobalHelmReposNamespace:kubeapps UnsafeLocalDevKubeconfig:false QPS:50 Burst:100}
I0223 03:10:35.125202       1 server.go:101] +helm NewServer(globalPackagingCluster: [default], globalPackagingNamespace: [kubeapps], pluginConfigPath: [/config/kubeapps-apis/plugins.conf]
I0223 03:10:35.125331       1 server.go:112] +helm using custom config: [{{3 3 3} 300 }]
I0223 03:10:35.125346       1 server.go:124] +helm NewServer effective globalPackagingNamespace: [kubeapps]
```

If I update to use your above config, I see `[{{5 5 5} 300 }]` as expected:

```
I0223 03:12:44.517948       1 root.go:36] "kubeapps-apis has been configured with serverOptions" serverOptions={Port:50051 PluginDirs:[/plugins/helm-packages /plugins/resources] ClustersConfigPath:/config/clusters.conf PluginConfigPath:/config/kubeapps-apis/plugins.conf PinnipedProxyURL:http://kubeapps-internal-pinniped-proxy.kubeapps:3333 PinnipedProxyCACert: GlobalHelmReposNamespace:kubeapps UnsafeLocalDevKubeconfig:false QPS:50 Burst:100}
I0223 03:12:44.818952       1 server.go:101] +helm NewServer(globalPackagingCluster: [default], globalPackagingNamespace: [kubeapps], pluginConfigPath: [/config/kubeapps-apis/plugins.conf]
I0223 03:12:44.819086       1 server.go:112] +helm using custom config: [{{5 5 5} 300 }]
I0223 03:12:44.819101       1 server.go:124] +helm NewServer effective globalPackagingNamespace: [kubeapps]
I0223 03:12:44.819407       1 plugins.go:152] "Successfully registered plugin" pluginPath="/plugins/helm-packages/helm-packages-v1alpha1-plugin.so"
```
Can you please check the logs of your kubeapps-apis server to see whether it's reading the config in and getting `{5 5 5}` as expected? That will help us to know where to look next.

**Comment by linhvuntu** [comment]
So I tried to create a brand new kubeapps with Helm `Package version 12.2.4 / App Version 2.6.3`, and with the config of `{10 10 10}` and the logs are as below

```
I0223 04:40:53.660198       1 root.go:36] "kubeapps-apis has been configured with serverOptions" serverOptions={Port:50051 PluginDirs:[/plugins/helm-packages /plugins/resources] ClustersConfigPath:/config/clusters.conf PluginConfigPath:/config/kubeapps-apis/plugi │ns.conf PinnipedProxyURL:http://kubeapps-internal-pinniped-proxy.kubeapps:3333 PinnipedProxyCACert: GlobalHelmReposNamespace:kubeapps-v3 UnsafeLocalDevKubeconfig:false QPS:50 Burst:100}                                                                               │
I0223 04:40:53.941472       1 server.go:101] +helm NewServer(globalPackagingCluster: [default], globalPackagingNamespace: [kubeapps-v3], pluginConfigPath: [/config/kubeapps-apis/plugins.conf]                                                                         
I0223 04:40:53.941671       1 server.go:112] +helm using custom config: [{{10 10 10} 300 }]                                                                                                                                                                             
I0223 04:40:54.029400       1 server.go:124] +helm NewServer effective globalPackagingNamespace: [kubeapps-v3]                                                                                                                                                          
I0223 04:40:54.030557       1 plugins.go:152] "Successfully registered plugin" pluginPath="/plugins/helm-packages/helm-packages-v1alpha1-plugin.so"                                                                                                                     │
I0223 04:40:54.332092       1 server.go:119] +resources using custom config: [{{ }}]
```

So it seems updated successfully, but when checking the Package Version dropdown list, it still display in with the setting of `{3 3 3}`

The Helm package I'm checking is the public ingress-nginx chart from Kubernetes here: https://github.com/kubernetes/ingress-nginx/tree/main/charts/ingress-nginx

When I check the this chart versions from terminal, it shows full list of versions as below
```
helm search repo ingress-nginx/ingress-nginx -l

NAME                       	CHART VERSION	APP VERSION	DESCRIPTION
ingress-nginx/ingress-nginx	4.5.2        	1.6.4      	Ingress controller for Kubernetes using NGINX a...
ingress-nginx/ingress-nginx	4.5.0        	1.6.3      	Ingress controller for Kubernetes using NGINX a...
ingress-nginx/ingress-nginx	4.4.2        	1.5.1      	Ingress controller for Kubernetes using NGINX a...
ingress-nginx/ingress-nginx	4.4.1         	1.5.2      	Ingress controller for Kubernetes using NGINX a...
ingress-nginx/ingress-nginx	4.4.0        	1.5.1      	Ingress controller for Kubernetes using NGINX a...
ingress-nginx/ingress-nginx	4.3.0        	1.4.0      	Ingress controller for Kubernetes using NGINX a...
ingress-nginx/ingress-nginx	4.2.5        	1.3.1      	Ingress controller for Kubernetes using NGINX a...
ingress-nginx/ingress-nginx	4.2.4        	1.3.1      	Ingress controller for Kubernetes using NGINX a...
ingress-nginx/ingress-nginx	4.2.3        	1.3.0      	Ingress controller for Kubernetes using NGINX a...
ingress-nginx/ingress-nginx	4.2.2        	1.3.0      	Ingress controller for Kubernetes using NGINX a...
ingress-nginx/ingress-nginx	4.2.1         	1.3.0      	Ingress controller for Kubernetes using NGINX a...
ingress-nginx/ingress-nginx	4.2.0        	1.3.0      	Ingress controller for Kubernetes using NGINX a...
ingress-nginx/ingress-nginx	4.1.4         	1.2.1      	Ingress controller for Kubernetes using NGINX a...
ingress-nginx/ingress-nginx	4.1.3         	1.2.1      	Ingress controller for Kubernetes using NGINX a...

... and more ..
```

But from the Package Version dropdown list in the Kubeapps Dashboards, it show only
```
4.5.2 
4.5.0
4.4.2
4.4.1
4.4.0
4.3.0
3.41.0
3.40.0
3.39.0
.. and more ..
```

For some specific reason, we need to use the Chart version 4.2.5 but it is not displayed.

Do I need to config anything else at the kubeappsController or elsewhere? I have cleared cache, use another laptop to check but it's still the same

**Comment by absoludity** [comment]
Thanks for the detail, I'm turning that into a separate bug report to investigate the regression - see #6020. Let's discuss it there.
