### ISSUE TITLE
OCI charts pushed with helm >= 3.7 fail to be synced with "manifest does not contain a layer with mediatype application/tar+gzip"

### ISSUE THREAD

**Issue by satya-dillikar** [kubeapps/kubeapps#3606]
### Description:

failed to pull chart. Got manifest does not contain a layer with mediatype application/tar+gzip

### Steps to reproduce the issue:

Added OCI Registry with below details
"repoURL": "https://demo.goharbor.io/"
repoNames: test10/podinfo/podinfo, test10/wordpress/wordpress

see screenshots
![Screen Shot 2021-10-15 at 4 48 02 PM](https://user-images.githubusercontent.com/37601587/137817534-9321b6ac-e6fa-41f2-8660-1eab7386c234.png)
![Screen Shot 2021-10-15 at 4 51 01 PM](https://user-images.githubusercontent.com/37601587/137817562-c4217100-b6e0-410f-bc0c-9d9b32299293.png)
![Screen Shot 2021-10-15 at 4 50 26 PM](https://user-images.githubusercontent.com/37601587/137817607-8edcc163-5635-4050-9a46-626ff9e5e5f2.png)

### Describe the results you received:

There was no error in the UX, but it turns out on the back-end sync job fails with an error.
```
$kubectl get pods -n kubeapps
NAME                                                         READY   STATUS             RESTARTS   AGE
apprepo-default-cleanup-demo.goharbor.io-lvmpl-96m2s         0/1     Completed          0          5m1s
apprepo-default-sync-demo.goharbor.io-ccdlr-rvz6r            0/1     CrashLoopBackOff   1          14s
apprepo-kubeapps-sync-bitnami-27238970-m7kfb                 0/1     Completed          0          23m
apprepo-kubeapps-sync-bitnami-27238980-7z8qg                 0/1     Completed          0          13m
apprepo-kubeapps-sync-bitnami-27238990-q4lcv                 0/1     Completed          0          3m39s
apprepo-kubeapps-sync-bitnami-zgg8b-d6dw6                    0/1     Completed          0          77s
kubeapps-65b8c847b9-kmntc                                    1/1     Running            5          3d
kubeapps-65b8c847b9-qv84j                                    1/1     Running            4          3d
kubeapps-internal-apprepository-controller-66c66f666-gkkhz   1/1     Running            2          3d
kubeapps-internal-assetsvc-6748c44b7b-47ps2                  1/1     Running            2          3d
kubeapps-internal-assetsvc-6748c44b7b-sxpj9                  1/1     Running            2          3d
kubeapps-internal-dashboard-67d6f6cb87-92zjt                 1/1     Running            2          3d
kubeapps-internal-dashboard-67d6f6cb87-kth7p                 1/1     Running            2          3d
kubeapps-internal-kubeappsapis-fd66dbb7f-f48xb               1/1     Running            2          3d
kubeapps-internal-kubeops-84d5b7b646-h8jzv                   1/1     Running            0          5m42s
kubeapps-internal-kubeops-84d5b7b646-zk7ss                   1/1     Running            0          5m42s
kubeapps-postgresql-primary-0                                1/1     Running            2          3d
kubeapps-postgresql-read-0                                   1/1     Running            2          3d

$ kubectl logs pod/apprepo-default-sync-demo.goharbor.io-ccdlr-rvz6r -n kubeapps
time="2021-10-15T23:14:12Z" level=info msg="Last checksum: "
time="2021-10-15T23:14:12Z" level=error msg="failed to pull chart. Got manifest does not contain a layer with mediatype application/tar+gzip"
time="2021-10-15T23:14:12Z" level=fatal msg="Can't add chart repository to database: pq: syntax error at or near \")\""
```

### Describe the results you expected:

back-end sync job should be able to pull OCI registry with helm-charts
### Additional information you deem important (e.g. issue happens only occasionally):

Only seen with OCI Registry which working on PR #2962 

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.17"}
```

- Output of `helm list -n <kubeapps-namespace> <kubeapps-release-name>`:

```
NAME    	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART         	APP VERSION
kubeapps	kubeapps 	1       	2021-10-12 15:40:58.320257 -0700 PDT	deployed	kubeapps-7.4.0	2.4.0
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:38:26Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by absoludity** [comment]
Thanks @satya-dillikar for the report.

If we check the [release notes of helm v3.7.0](https://github.com/helm/helm/releases/tag/v3.7.0) (the version we've used here to test), you'll see they say "In addition, a change to the experimental OCI manifest format was introduced, preventing Helm 3.7 from fetching charts built with older versions of the experimental OCI feature. Users will need to re-package and upload their OCI charts when upgrading to Helm 3.7. This change does not affect standard Helm charts.".

In the latest Kubeapps release, we're [using helm 3.5.4](https://github.com/kubeapps/kubeapps/blob/v2.4.1/go.mod#L82) . This means that Kubeapps' OCI support only currently works with a chart pushed with a helm 3.6.x client. This is great to know, so thanks for the report.

Can you please check that if you upload charts to harbor with [helm 3.6.3](https://github.com/helm/helm/releases/tag/v3.6.3), that it works as expected?

Regarding the fix, we'd need to investigate whether we can support both or need to make a hard switch. If it's the latter, we'll want to do so when the Bitnami content team also update to the new format (they may have updated already, haven't checked).

I've not verified, but assume that one issue is going to be that [Kubeapps currently expects the mediaType](https://github.com/kubeapps/kubeapps/blob/v2.4.1/pkg/helm/helm.go#L36-L50) to be `application/tar+gzip`, whereas our examples with the 3.7 client show that it is `application/vnd.cncf.helm.chart.content.v1.tar+gzip`. It'd be great if that was the only difference (easy fix to add to the known types), but I doubt that's the case. We could try adding to the known type and seeing if that enables the syncer to do its thing. Let me know if you try.
