### ISSUE TITLE
nginx: [warn] conflicting server name "" on 0.0.0.0:8080, ignored

### ISSUE THREAD

**Issue by aminebizid** [kubeapps/kubeapps#361]
amineacs ➜  wx k -n kubeapps logs pod/kubeapps-6d49586cfb-9z7h4 -f

Welcome to the Bitnami nginx container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-nginx
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-nginx/issues
Send us your feedback at containers@bitnami.com

nami    INFO  Initializing nginx
nginx   INFO  ==> nginx.conf not found. Applying bitnami configuration...
nami    INFO  nginx successfully initialized
INFO  ==> Starting nginx...
**nginx: [warn] conflicting server name "" on 0.0.0.0:8080, ignored
2018/06/14 07:30:13 [warn] 31#0: conflicting server name "" on 0.0.0.0:8080, ignored**
10.22.217.41 - - [14/Jun/2018:07:30:22 +0000] "GET / HTTP/1.1" 499 0 "-" "kube-probe/1.11+"
10.22.217.41 - - [14/Jun/2018:07:30:27 +0000] "GET / HTTP/1.1" 499 0 "-" "kube-probe/1.11+"
10.22.217.41 - - [14/Jun/2018:07:30:31 +0000] "GET / HTTP/1.1" 499 0 "-" "kube-probe/1.11+"
10.22.217.41 - - [14/Jun/2018:07:30:32 +0000] "GET / HTTP/1.1" 499 0 "-" "kube-probe/1.11+"
10.22.217.41 - - [14/Jun/2018:07:30:37 +0000] "GET / HTTP/1.1" 499 0 "-" "kube-probe/1.11+"

**Comment by prydonius** [comment]
Hey @aminebizid, could you describe the issue a bit more? That warning does not seem too important.

**Comment by sameersbn** [comment]
@prydonius I think the user is pointing out the `conflicting server name` warning message in the nginx logs. @aminebizid this message is harmless and IMO should not cause any issues, if you do notice any problem please do let us know.

@prydonius this warning message can be removed by adding the `server_name` directive to the `vhost.conf`. But maybe it makes more sense to have `server_name localhost` in the `nginx.conf` by default. thoughts?

**Comment by prydonius** [comment]
Yeah I also through the warning was not too important, just curious if @aminebizid was running into any weird side-effects that caused @aminebizid to look through the logs?

**Comment by sameersbn** [comment]
I tested it out by adding `server_name localhost` to the the vhost and exposed the dashboard using in ingress and had no issues. We can also use `server_name _` in our vhost configure to specify a catch-all hostname (also tested to be working).

**Comment by prydonius** [comment]
@sameersbn mind sending a PR for one of those?
