### ISSUE TITLE
UI: Helm values not correctly reported

### ISSUE THREAD

**Issue by dud225** [kubeapps/kubeapps#3621]
Hello

I've initially deployed Kubeapps with a long Helm command that happened to add some Nginx annotations:
```
--set ingress.annotations."nginx\.ingress\.kubernetes\.io/auth-response-headers"=Authorization \
--set ingress.annotations."nginx\.ingress\.kubernetes\.io/auth-signin"='https://$host/oauth2/start?rd=$escaped_request_uri' \
--set ingress.annotations."nginx\.ingress\.kubernetes\.io/auth-url"=http://oauth2-proxy.kube-system.svc.cluster.local/oauth2/auth \
--set ingress.annotations."nginx\.ingress\.kubernetes\.io/configuration-snippet"='rewrite ^(/kubeapps)$ $1/ redirect;' \
--set ingress.annotations."nginx\.ingress\.kubernetes\.io/rewrite-target"='/$upstream_path' \
```

However those settings are not correctly reported within Kubeapps:
![Capture d’écran de 2021-10-20 09-50-16](https://user-images.githubusercontent.com/17550475/138051043-75917e35-6f55-4939-a2aa-817ce86364f8.png)

which makes it unhappy when deploying:
![Capture d’écran de 2021-10-20 09-50-40](https://user-images.githubusercontent.com/17550475/138051152-5430c7bf-39c1-442a-bb0b-93fb0c6ad98a.png)

Manually adjusting the values in the UI allows the deployment to succeed.

**Comment by antgamdia** [comment]
Hi Hervé, thanks for reporting it. I'll have a look using the current version in the main branch (as we performed some changes in the AppUpgrade view). However, it could be an actual issue derived from the parsing from yaml <-> json, so it is worth checking.

**Comment by castelblanque** [comment]
Reopening issue as [stated here](https://kubernetes.slack.com/archives/C9D3TSUG4/p1646652896997059) by a user.
Installation values appear unquoted in the Upgrade screen Yaml edition.
