### ISSUE TITLE
Charts themselves may need caching in fluxv2 plugin

### ISSUE THREAD

**Issue by absoludity** [kubeapps/kubeapps#3636]
Just moving from the [PR discussion](https://github.com/kubeapps/kubeapps/pull/3628#issuecomment-948340352) to an actual issue, as requested by @gfichtenholt , where Greg said:

> I know why that is. I'm not caching any specific charts (only parsed repo index). (Some of the) chart details have to come from a tarball, so if one isn't already there I create a HelmChart on-the-fly, wait while until it reconciles, get the tarball, and then clean up by deleting the HelmChart. I'm a little surprised that it takes that long, I have seen much shorter times, bit I digress. So 2nd call wouldn't be any faster than the 1st. If I didn't do the clean up, it obviously would be, but I didn't want potentially unbound number of HelmCharts laying around after a while.
> 
> One obvious solution would be to cache package details (i.e. introduce another resource-based watcher cache)...
> 
> Another solution might be to make the cleanup process a bit more sophisticated, to make it kind of a garbage collector, that keeps around a around , say, 5 of LRU HelmCharts. That way the number of HelmCharts left around is still bounded. Back in school they taught me if a user clicks on one package, they're likely to click there again, so this would solve it too.
> 
> Neither of these approaches would not speed up the 1st call, but either one would make the cost of 2nd and subsequent calls to `GetAvailablePackageDetail` insignificant.

This was in response to my comment that:
> Just noted that fetching the available package detail appears to be taking around 2.5s (see below). Not a big deal, but just checking in case @gfichtenholt can make it quicker (he's good at that :P )
>
> ![flux-apache](https://user-images.githubusercontent.com/497518/138218705-c3629e7a-2936-4ad6-ab18-90236dae4974.png)

**Comment by absoludity** [comment]
> Neither of these approaches would not speed up the 1st call, but either one would make the cost of 2nd and subsequent calls to `GetAvailablePackageDetail` insignificant.

Yep. Another possibility is to do something similar to helm where a job is started and caches the files for the latest few versions of each chart. That way clicking on an available app summary would show the details very quickly, where as if the user then switches to an older version they get a 2s delay which is OK.

**Comment by gfichtenholt** [comment]
Guys, fyi an update: I have implemented one tentative approach where when you add a new repo source, it caches the parsed index (as it before) but now also the details of only THE LATEST version of each chart (hopefully that's the one that would be displayed in the catalog by default, so it looks instantaneous (a cache hit)). Just FYI, the chart details are README, values and schema files. Not zipped or anything, just in plain text. So, after bitnami is added to flux, I end up with about 100 keys in Redis (one for helmrepository and the rest are details for each chart):
```
$ rdcli -h localhost --port 6379 --auth $REDIS_PWD "keys" "*" 
1) helmcharts:default:bitnami/grafana:7.2.4
2) helmcharts:default:bitnami/jupyterhub:0.3.1
3) helmcharts:default:bitnami/grafana-operator:1.5.1
4) helmcharts:default:bitnami/spark:5.7.10
5) helmcharts:default:bitnami/kong:4.1.9
6) helmcharts:default:bitnami/spring-cloud-dataflow:4.2.0
7) helmcharts:default:bitnami/mariadb:10.0.2
8) helmcharts:default:bitnami/nats:7.0.1
9) helmcharts:default:bitnami/jenkins:8.0.18
10) helmcharts:default:bitnami/rabbitmq:8.24.7
11) helmcharts:default:bitnami/mongodb-sharded:3.9.15
12) helmcharts:default:bitnami/kubernetes-event-exporter:1.2.3
13) helmcharts:default:bitnami/kubeapps:7.5.10
14) helmcharts:default:bitnami/prestashop:13.3.0
15) helmcharts:default:bitnami/redis:15.6.1
16) helmcharts:default:bitnami/wavefront-prometheus-storage-adapter:1.0.12
17) helmcharts:default:bitnami/concourse:0.1.13
18) helmcharts:default:bitnami/dataplatform-bp2:10.0.0
19) helmcharts:default:bitnami/tensorflow-resnet:3.2.20
20) helmcharts:default:bitnami/redmine:17.1.0
21) helmcharts:default:bitnami/oauth2-proxy:1.1.1
22) helmcharts:default:bitnami/wavefront:3.1.17
23) helmcharts:default:bitnami/node:16.1.0
24) helmcharts:default:bitnami/owncloud:10.3.0
25) helmcharts:default:bitnami/osclass:12.0.0
26) helmcharts:default:bitnami/kibana:9.1.2
27) helmcharts:default:bitnami/cert-manager:0.1.25
28) helmcharts:default:bitnami/phpmyadmin:8.3.0
29) helmcharts:default:bitnami/wavefront-adapter-for-istio:1.0.12
30) helmcharts:default:bitnami/rabbitmq-cluster-operator:2.0.0
31) helmcharts:default:bitnami/ejbca:3.1.0
32) helmcharts:default:bitnami/orangehrm:10.2.0
33) helmcharts:default:bitnami/dokuwiki:11.2.13
34) helmcharts:default:bitnami/pytorch:2.3.19
35) helmcharts:default:bitnami/minio:9.2.1
36) helmcharts:default:bitnami/dataplatform-bp1:9.0.0
37) helmcharts:default:bitnami/common:1.10.1
38) helmcharts:default:bitnami/postgresql:10.13.8
39) helmcharts:default:bitnami/kafka:14.4.1
40) helmcharts:default:bitnami/kubewatch:3.2.20
41) helmcharts:default:bitnami/apache:8.9.6
42) helmcharts:default:bitnami/airflow:11.1.8
43) helmcharts:default:bitnami/parse:15.0.14
44) helmcharts:default:bitnami/testlink:9.3.0
45) helmcharts:default:bitnami/argo-workflows:0.1.8
46) helmcharts:default:bitnami/joomla:10.2.1
47) helmcharts:default:bitnami/tomcat:9.6.0
48) helmcharts:default:bitnami/memcached:5.15.8
49) helmcharts:default:bitnami/aspnet-core:2.0.0
50) helmcharts:default:bitnami/consul:10.1.3
51) helmcharts:default:bitnami/sonarqube:0.1.0
52) helmcharts:default:bitnami/opencart:10.1.0
53) helmcharts:default:bitnami/nginx-ingress-controller:9.0.8
54) helmcharts:default:bitnami/postgresql-ha:8.0.1
55) helmcharts:default:bitnami/node-exporter:2.3.15
56) helmcharts:default:bitnami/phpbb:10.2.0
57) helmcharts:default:bitnami/contour:7.0.3
58) helmcharts:default:bitnami/ghost:15.1.2
59) helmcharts:default:bitnami/mongodb:10.29.4
60) helmcharts:default:bitnami/grafana-tempo:0.2.14
61) helmcharts:default:bitnami/suitecrm:9.4.1
62) helmcharts:default:bitnami/elasticsearch:17.3.3
63) helmcharts:default:bitnami/nginx:9.5.14
64) helmcharts:default:bitnami/harbor:11.1.0
65) helmcharts:default:bitnami/zookeeper:7.4.12
66) helmrepositories:default:bitnami
67) helmcharts:default:bitnami/mariadb-galera:6.0.5
68) helmcharts:default:bitnami/mxnet:2.3.22
69) helmcharts:default:bitnami/wildfly:12.0.0
70) helmcharts:default:bitnami/keycloak:5.2.0
71) helmcharts:default:bitnami/magento:19.0.9
72) helmcharts:default:bitnami/fluentd:4.4.1
73) helmcharts:default:bitnami/jasperreports:11.1.0
74) helmcharts:default:bitnami/kiam:0.3.20
75) helmcharts:default:bitnami/drupal:10.4.7
76) helmcharts:default:bitnami/argo-cd:2.0.12
77) helmcharts:default:bitnami/geode:0.3.4
78) helmcharts:default:bitnami/mysql:8.8.12
79) helmcharts:default:bitnami/cassandra:9.0.5
80) helmcharts:default:bitnami/kube-state-metrics:2.1.17
81) helmcharts:default:bitnami/wavefront-hpa-adapter:1.0.3
82) helmcharts:default:bitnami/external-dns:5.5.0
83) helmcharts:default:bitnami/wordpress:12.2.1
84) helmcharts:default:bitnami/haproxy:0.2.18
85) helmcharts:default:bitnami/influxdb:2.4.1
86) helmcharts:default:bitnami/mediawiki:12.4.2
87) helmcharts:default:bitnami/kube-prometheus:6.4.1
88) helmcharts:default:bitnami/etcd:6.10.3
89) helmcharts:default:bitnami/solr:2.1.3
90) helmcharts:default:bitnami/redis-cluster:7.0.11
91) helmcharts:default:bitnami/metrics-server:5.10.10
92) helmcharts:default:bitnami/logstash:3.6.17
93) helmcharts:default:bitnami/discourse:5.1.0
94) helmcharts:default:bitnami/contour-operator:0.2.0
95) helmcharts:default:bitnami/odoo:20.1.2
96) helmcharts:default:bitnami/metallb:2.5.11
97) helmcharts:default:bitnami/thanos:8.1.0
98) helmcharts:default:bitnami/moodle:11.2.1
```
The whole thing ends up taking about 25MB of Redis memory. 
Obviously any chart version not in the cache requested by user (a cache miss scenario), would take longer (about 2-3 seconds based on what I've seen so far) to load the first time, and then as above.

Just checking if this sounds like a reasonable approach and I should continue, or try something else

**Comment by antgamdia** [comment]
Wow just 25MB, that's great. This approach will speed up the user-perceived app performance, as they will see something as soon as they select something. 
From a UX point of view, I think it's ok letting a user wait for some seconds if they explicitly select a version, so, as for me, it's a nice cache approach.

That said, I just wonder (not meaning we should/shouldn't do it), whether we should make this "number of cached versions" configurable. Like in "latest version + latest-N previous ones" or "latest + latest-N and then LRU based on user-selection".
Also, perhaps we can also add to the cache (in runtime) the currently installed version, so when the user tries to fetch the package details, the response time gets improved for subsequent calls.

**Comment by gfichtenholt** [comment]
OK, thanks, Antonio that's encouraging. Sounds like I'm on the right track. If I can cache 1, I can cache N, that's not too big a leap

**Comment by absoludity** [comment]
Nice work Greg! I agree, the main think we want to solve is the initial load time, so much less of an issue that a user needs to wait when selecting a different version (a cache-miss, which I assume is then added to the cache).

Out of interest, how long does it take to cache just the first versions? (I assume it does this after the plugin is registered?).

**Comment by gfichtenholt** [comment]
Thank you, Michael. I have the numbers now from my latest experiment. bitnami+100 latest chart versions in the original format (.tgz) is 18MB. Vs 25 if uncompressed. I thought there'd be a bigger gain, but maybe the fact that the cache entry for bitnami repo (parsed model that includes metadata for all 14K versions) is the big elephant in the room, so everything else is small in comparison. Oh well, I still like that approach. 
To answer your last question, I have one background worker right now syncing charts one-by-one sequentially
so the first chart starts at 
```
I1129 01:58:26.622102       1 chart_cache.go:193] +syncHandler(helmcharts:default:bitnami/airflow:11.1.8)
and the last one ends at
I1129 01:59:27.937374       1 chart_cache.go:243] -syncHandler(helmcharts:default:bitnami/zookeeper:7.4.12) 
```

So that's a minute. Obviously this work can and will benefit from parallelization. I will have several (5 or 10) doing this concurrently. So that number is going to change

**Comment by gfichtenholt** [comment]
Here are a few more numbers from my MacBook I just collected:
Helm plugin GetAvailablePackageDetail:
```
$ time grpcurl -plaintext -d '{"available_package_ref": {"context": {"cluster": "default", "namespace": "kubeapps"}, "plugin": {"name": "helm.packages", "version": "v1alpha1"}, "identifier": "bitnami/apache"}}' -H "Authorization: Bearer $TOKEN" localhost:8080 kubeappsapis.core.packages.v1alpha1.PackagesService.GetAvailablePackageDetail
{
  "availablePackageDetail": {
    "availablePackageRef": {
      "context": {
        "namespace": "kubeapps"
      },
      "identifier": "bitnami/apache",
      "plugin": {
        "name": "helm.packages",
        "version": "v1alpha1"
      }
    },
   ... skipped ...
real	0m0.168s
user	0m0.024s
sys	0m0.017s  
```
