### ISSUE TITLE
UI: app repository Install Repo button fires twice (sometimes)

### ISSUE THREAD

**Issue by dlaloue-vmware** [kubeapps/kubeapps#3678]
### Description:

I ran several times into the use case where clicking the "Install Repo" button to add a new app repository is being executed twice, resulting in an error message being displayed.
The first execution seems to properly create the app repository, and does not seem to be affected by the second execution.

### Describe the results you expected:

Any submit button should be guarded from firing multiple times.

**Comment by castelblanque** [comment]
Not an easy one :)

There are redundant calls int [AppRepoForm.tsx](https://github.com/kubeapps/kubeapps/blob/master/dashboard/src/components/Config/AppRepoList/AppRepoForm.tsx):
- `onClick` of the button in the form, triggers the install logic -> `<CdsButton disabled={validating} onClick={install}>`
- `handleInstallClick`function calls install logic as well upon submission of form -> `<form onSubmit={handleInstallClick}>`

However, the problem I'm facing with Jest is that simulating the 'click' on the button (having it changed to `type=submit`) is not submitting the form in the tests. 
After some research, I found [this issue](https://github.com/enzymejs/enzyme/issues/308), which is mentioned in an [old Kubeapps issue](https://github.com/kubeapps/kubeapps/pull/1723#discussion_r421885145).
Instead, if simulate('submit') is used with the button instance, `disable` status is not honored and can be invoked multiple times.

Will continue investigating tomorrow 👀
