### ISSUE TITLE
Kubeapps installs components into different namespaces

### ISSUE THREAD

**Issue by vtuson** [kubeapps/kubeapps#37]
I was expecting for kubeapps to install everything into a single name space but:
Kubeless goes into kubeless
Monokular into kubeapps 
SealedSecrest into kube-system

I found that a bit messy , specially kube-system as I already had a lot install there and I had to do spot the difference to see what was added after I run kubeapps up

**Comment by ngtuna** [comment]
I don't see problem to install kubeapps components in several namespaces but you're right on the output of the installation progress. The installer should print out the result of what are deployed and where they are deployed.

**Comment by vtuson** [comment]
at least we should avoid installing in kube-system from kubeapps so it is more clear in the system after installation of what got provisioned

**Comment by prydonius** [comment]
We should print out a status at the end showing what is installed. Something like `kubectl get all --all-namespaces -l installer=kubeapps`. https://github.com/kubeapps/manifest/issues/7 is relevant to this, allowing us to define a selector for this

**Comment by arapulido** [comment]
The reason why it installs into different namespaces is to avoid breaking other CLI tools (like `kubeless` or `kubeseal`) that expects some components installed in particular namespaces. Something we can fix/workaround in the future.

In the mean time, the way we are going to address this is by labelling everything that is installed by kubeapps correctly, so people can check it easily and will improve the output of the command so when it finishes it shows everything that it installed.

**Comment by ngtuna** [comment]
I opened an issue for labeling in manifest here https://github.com/kubeapps/manifest/issues/7

**Comment by vtuson** [comment]
OK that works for me
