### ISSUE TITLE
can't install kubeapps components: Error updating roles kubeapps.apprepository-controller: roles.rbac.authorization.k8s.io "apprepository-controller" is forbidden: unable to create new content in namespace kubeapps because it is being terminated

### ISSUE THREAD

**Issue by fhchina** [kubeapps/kubeapps#371]
when I install kubeapps, I type: kubeapps up
then I got the following error:

can't install kubeapps components: Error updating roles kubeapps.apprepository-controller: roles.rbac.authorization.k8s.io "apprepository-controller" is forbidden: unable to create new content in namespace kubeapps because it is being terminated

My Environment:
OS: Ubuntu Server 16.04.01 LTS
Kubernetes:  1.8.13
Helm: 2.9.1

**Comment by fhchina** [comment]
@prydonius Now I retype: kubeapps up, I got:
INFO[0008]  Creating non-existent deployments kubeless.kubeless-controller-manager 
ERRO[0011] can't install kubeapps components: (-500)Internal Server Error. Please Contact Your Administrator

**Comment by prydonius** [comment]
@fhchina are you able to use `kubectl` correctly? Sounds like your Kubernetes API server is acting up

**Comment by prydonius** [comment]
@fhchina did you solve your issue?

**Comment by arapulido** [comment]
@fhchina The Kubeapps CLI is now deprecated. Please, deploy Kubeapps using Helm (following the guide at https://github.com/kubeapps/kubeapps/blob/master/docs/user/getting-started.md). I will close this issue now. Please, open a new one if you have issues deploying Kubeapps with the Helm chart. Thanks!
