### ISSUE TITLE
Cannot add ChartMuseum repository that uses basic auth, 422 error

### ISSUE THREAD

**Issue by thedevelopnik** [kubeapps/kubeapps#375]
I have installed Kubeapps using installer v1.0.0-alpha.3. I've made a private repo using the most recent version of [ChartMuseum](https://github.com/kubernetes-helm/chartmuseum). ChartMuseum supports basic auth. I cannot get Kubeapps to add this repository using either `https://<username>:<password>@<url-of-repo>` in the url part of the form, nor by putting in a `Basic <token>` in the Authorization Header field and leaving out the `user:pass` part of the url. I can add the repo just fine using the `https://<username>:<password>@<url-of-repo>` format in the Helm CLI.

When I click `Install Repo` I get `POST http://localhost:60212/api/kube/apis/kubeapps.com/v1alpha1/namespaces/kubeapps/apprepositories 422 (Unprocessable Entity)` in the browser console.

**Comment by prydonius** [comment]
@thedevelopnik thanks for filing the issue, can you see the response from that API call in the network tab of your browser?

**Comment by prydonius** [comment]
I just tested this and was able to successfully add a chartmuseum repo with basic auth using the authorization header input in Kubeapps.

**Comment by thedevelopnik** [comment]
@prydonius I figured out the issue was what I was trying to name the repo. I was trying to name it "GSC ChartMuseum" and that's what was causing the 422. Calling it "gsc-chartmuseum" worked fine. Closing the ticket.

**Comment by prydonius** [comment]
Thanks @thedevelopnik, looks like this is a little bit related to https://github.com/kubeapps/kubeapps/issues/318 in that we could probably validate the name before sending it to the API.
