### ISSUE TITLE
kubeapp should not assume current context is set

### ISSUE THREAD

**Issue by DazWilkin** [kubeapps/kubeapps#381]
To error-proof my experience, I unset current-context when I'm working with multiple clusters but this breaks `kubeapps`:
```
kubeapps up
ERRO[0000] can't get Kubernetes client: invalid configuration: no configuration has been provided 
```
If I set `current-context`, it works:
```
kubectl config set current-context fabric-180626
Property "current-context" set.

kubeapps up
INFO[0002] Fetching schemas for 1 resources             
INFO[0002] Updating clusterrolebindings kubeapps-cluster-admin 
INFO[0003]  Creating non-existent clusterrolebindings kubeapps-cluster-admin 
...
Kubeapps has been deployed successfully. 
```
There's no evident flag that would permit me pushing context through:
```
kubeapps up --help
Install Kubeapps components.

List of components that kubeapps up installs:

- Kubeless (https://github.com/kubeless/kubeless)
- Sealed-Secrets (https://github.com/bitnami/sealed-secrets)
- Helm/Tiller (https://github.com/kubernetes/helm)
- Kubeapps Dashboard (https://github.com/kubeapps/dashboard)

Usage:
  kubeapps up FLAG [flags]

Flags:
      --dry-run      Show manifest to be submitted to the k8s cluster without deploying.
  -h, --help         help for up
  -o, --out string   Specify manifest format: yaml | json. Note: used only with --dry-run (default "yaml")

Global Flags:
  -v, --verbose string   Set log level: debug, info, warning, error.
debug: Usually only enabled when debugging. Very verbose logging.
info: General operational entries about what's going on.
error: Used for errors that should definitely be noted.
warning: Non-critical entries that deserve eyes. (default "info")
```

**Comment by prydonius** [comment]
Thanks for the issue @DazWilkin. We could certainly add a `--kube-context` flag to `kubeapps` that enables selecting a context. Is that what you're looking for?

**Comment by DazWilkin** [comment]
Thanks for the prompt response!

Yes, but... ;-)

Helm uses `--kube-context` as the flag so this would be consistent with it.

But `kubectl` uses `--context` and it seems that Helm and Kubeapps would be more consistent if they adopted this name too. Thoughts?

Additionally, Helm uses `namespace` as the flag for Kubernetes namespaces not `kube-namespace`

**Comment by prydonius** [comment]
Since we're moving to a Helm chart based install in #325, we may not need to actually do anything here.

**Comment by arapulido** [comment]
@DazWilkin The Kubeapps CLI is now deprecated. Please, deploy Kubeapps using Helm (following the guide at https://github.com/kubeapps/kubeapps/blob/master/docs/user/getting-started.md). I will close this issue now. Please, open a new one if you have issues deploying Kubeapps with the Helm chart. Thanks!
