### ISSUE TITLE
405/403 when  access kubeapps dashboard

### ISSUE THREAD

**Issue by Suozz** [kubeapps/kubeapps#3810]
### Description:

fail to run kubeapps when I run kubeapps first.
![image](https://user-images.githubusercontent.com/29419237/143169239-31855903-406b-4e56-ab6b-0889c40da3a3.png)

when I access dashboard by serviceaccount token, caused 403 errors below
```
root@n23-061-197:~# kubectl get --namespace default secret $(kubectl get --namespace default serviceaccount kubeapps-operator -o jsonpath='{range .secrets[*]}{.name}{"\n"}{end}' | grep kubeapps-operator-token) -o jsonpath='{.data.token}' -o go-template='{{.data.token | base64decode}}' && echo
eyJhbGciOiJSUzI1NiIsImtpZCI6ImlFZHItSUNxOUpHYi1NVTBnbXhIUmIwT2tMWWVYQWpWc3NvbU5aWlpZMEEifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6Imt1YmVhcHBzLW9wZXJhdG9yLXRva2VuLThoOGttIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6Imt1YmVhcHBzLW9wZXJhdG9yIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiYTVkZmRhYTQtZWMyOS00YjE4LThjYjEtY2ZlZWZmZDI3NmZkIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmRlZmF1bHQ6a3ViZWFwcHMtb3BlcmF0b3IifQ.IvVoFax6nB-UFO6zAwGqXPn-k7C5eW0islffg3GAoswtm_NeXzE0sdcD3J619nqQGbHl6wM2QYedmMUbGycpr2FfMcvUHMxM8QO90UlA4lvnWDces36xSt-iIHFfZJvZqWn3_DgdAKoryw6HO2vhl_cGgDucGMxdOxfL6Uq_E379NnT7QhfHnVnC8GLI3CEzQMCv1fECRZlGdD2QF33G6JHXZLtrIPgHR0P_RQshFMSZu89TzDqhjLjaRinASSAolIFnfs1i_Uz9FggR0pbVaKTwVGlXicdK6gvmlhgxi2qg3CJ4ipP6XcEsDCFUmRxOYMse-2Xc3H_Zcvpbc4_myQ

root@n23-061-197:~# kubectl auth can-i --as system:serviceaccount:default:kubeapps-operator get ns
yes
```

![image](https://user-images.githubusercontent.com/29419237/143172976-782127d2-aef6-436f-a755-dcc1cba4a3ab.png)

### Steps to reproduce the issue:

1. install kubeapps 
2. input token
3. cause this problem

### Describe the results you expected:

normal use

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
install by kubesphere v3.2.0
```

- Output of `helm list -n <kubeapps-namespace> <kubeapps-release-name>`:

```
NAME          	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART          	APP VERSION
kubeapp-ufhlgg	test     	2       	2021-11-24 02:15:08.918766902 +0000 UTC	deployed	kubeapps-7.5.10	2.4.1
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-339+b4128595cc9586-dirty", GitCommit:"b4128595cc95869b63e984258bf0e7213ace7770", GitTreeState:"dirty", BuildDate:"2021-06-21T13:02:40Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:35:25Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by absoludity** [comment]
Hi there @Suozz . Something is odd with the way the request is being routed/proxied there. That request should be for a URL that looks like:
```
https://your-frontend-ip-addr/apis/kubeappsapis.core.packages.v1alpha1.PackagesService/GetInstalledPackageSummaries
```
which seems to match what you had as the original issue title, but in the screenshot, it appears to be:

```
http://your-frontend-ip-addr/api/v1/namespaces/test/services/http:kubeapp-ufhlgg-kubeapps-internal-dashboard:http/proxy/apis/kubeappsapis.core.packages.v1alpha1.PackagesService/GetInstalledPackageSummaries
```
and yes, a 405 may be the correct response for a POST to that endpoint. Is it possible that you're running some custom proxy rules? If so, can you share the details?

**Comment by Suozz** [comment]
> 

- I access the kubeapp‘s service by apiserver, just like [k8s docs](https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-services/#manually-constructing-apiserver-proxy-urls), so the path is correct and I can get the html from service.
-  I use `kubectl proxy --port=8080 --address='0.0.0.0' --accept-hosts='^.*' &` command and proxy the server:8080 to minikube apiserver 
- I insert the token of my service account token, but the server still think user is system:anonymous
![image](https://user-images.githubusercontent.com/29419237/143183166-01905849-9c6b-4f87-b8c0-911703573154.png)

**Comment by absoludity** [comment]
Oh - I see. You're using `kubectl proxy` to proxy the entire k8s API server and then accessing the Kubeapps dashboard service directly via the k8s apiservers ability to proxy services.

One reason this won't work is that the Kubeapps dashboard service is itself just an nginx server with a single-page app - it doesn't handle any requests other than service the single-page app. All the additional requests are usually proxied by the kubeapps frontend service, which is the one that you should be accessing. So you could instead try accessing the "kubeapps" frontend service with something like:

```
http://your-k8s-api-ip-address/api/v1/namespaces/kubeapps/services/kubeapps:80/proxy
```

and see if that works, but I don't know that we've ever tried it that way. We recommend instead port-forwarding directly to the kubeapps frontend service (rather than via the proxied URL of the k8s api server). See https://github.com/kubeapps/kubeapps/blob/master/docs/user/getting-started.md#step-3-start-the-kubeapps-dashboard for more info.

Let me know if that solves your problem.
