### ISSUE TITLE
Tarballs from Harbor Helm charts fail to download. URL is malformed.

### ISSUE THREAD

**Issue by castelblanque** [kubeapps/kubeapps#3821]
### Description:

Error occurs when trying to install a chart from a Harbor Helm repository. Dashboard shows error with "_chart download request failed_".

### Steps to reproduce the issue:

1. Create a Helm repository in Harbor, e.g. in [demo](https://demo.goharbor.io) site
2. Upload a chart `.tgz` file
3. Add repository to Kubeapps
4. Install chart from Kubeapps

### Describe the results you received:

Nothing is installed.

- Kubeapps dashboard shows:
![image](https://user-images.githubusercontent.com/67455978/143458810-d11ae059-0fa6-4b7b-b99e-7a78f7ad5060.png)

- `kubeapps-apis` pod logs shows:
`2021/11/25 14:24:55 Downloading https://demo.goharbor.io/chartrepo/charts/hook-with-timeout-0.1.0.tgz ...`

### Describe the results you expected:

Chart tarball properly downloaded and installed by Kubeapps.

### Additional information you deem important (e.g. issue happens only occasionally):

It seems that URL of the chart tarball is incorrectly formed [here](https://github.com/kubeapps/kubeapps/blob/master/cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go#L1089).
The chart index.yaml from Harbor shows a path for the tarball that is relative to the repo and not absolute.
```
...
    type: application
    urls:
    - charts/my-chart-name-0.1.0.tgz
    version: 0.1.0
...
```

This probably can be fixed by using [this function](https://github.com/kubeapps/kubeapps/blob/master/cmd/asset-syncer/server/utils.go#L723).

### Version of Helm, Kubeapps and Kubernetes:

Current development version of Kubeapps

**Comment by antgamdia** [comment]
Yes, I can confirm the same issue... I think I did introduce that issue when we moved from retrieving the TarballURL "in real time" to using the one saved in the DB. I forgot to concat it if the URL happens to be relative instead of absolute, I guess. :sweat_smile: 
Thanks for pointing this issue out!

**Comment by absoludity** [comment]
Thanks for going the extra step to investigate and document the solution Rafa!
