### ISSUE TITLE
Document how to use the tiller proxy, secure setup, connecting to existing Tiller, etc.

### ISSUE THREAD

**Issue by prydonius** [kubeapps/kubeapps#384]

**Comment by arapulido** [comment]
Some ideas for this documentation (these are just suggestions)

 * In the Developer documentation, we need to add in the main README.md the proxy component (it is not in that list)
 * In the Architecture folder, I would add some documentation (maybe a diagram) on how the proxy works, and how it prevents users from unauthorized usage. I would explain the differences in security of using an existing Tiller v.s. the one coming with kubeapps (if any) and TLS v.s. none (in both cases). I would link to some documentation about general Tiller security.
* In the User docs I would add some high level docs on how to secure TIller, what are the differences and how to use an existing Tiller.

**Comment by arapulido** [comment]
👍
