### ISSUE TITLE
Deprecate or maintain kubeapps/common

### ISSUE THREAD

**Issue by antgamdia** [kubeapps/kubeapps#3847]
### Description:

We have some cross-package logic shared under the `pkg` folder. Notwithstanding, we still have a repository called https://github.com/kubeapps/common. 
In fact, we are using this repo in different parts of our code (see below)

I wonder whether we should just go monorepo and incorporate this logic under the `pkg` folder so that we can continue updating the associated dependencies and removing dead code (if any).
If not, what I'd suggest is updating that repo to gomodules and performing, at least, some cleanup.

- https://github.com/kubeapps/kubeapps/blob/master/cmd/asset-syncer/server/delete.go
- https://github.com/kubeapps/kubeapps/blob/master/cmd/asset-syncer/server/invalidate-cache.go
- https://github.com/kubeapps/kubeapps/blob/master/cmd/asset-syncer/server/postgresql_utils.go
- https://github.com/kubeapps/kubeapps/blob/master/cmd/asset-syncer/server/sync.go
- https://github.com/kubeapps/kubeapps/blob/master/cmd/asset-syncer/server/utils_test.go
- https://github.com/kubeapps/kubeapps/blob/master/cmd/asset-syncer/server/utils.go
- https://github.com/kubeapps/kubeapps/blob/master/cmd/assetsvc/pkg/utils/postgresql_utils.go
- https://github.com/kubeapps/kubeapps/blob/master/cmd/assetsvc/pkg/utils/utils.go
- https://github.com/kubeapps/kubeapps/blob/master/cmd/assetsvc/server/handler.go
- https://github.com/kubeapps/kubeapps/blob/master/cmd/assetsvc/server/server.go
- https://github.com/kubeapps/kubeapps/blob/master/cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server_test.go
- https://github.com/kubeapps/kubeapps/blob/master/cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go
- https://github.com/kubeapps/kubeapps/blob/master/cmd/kubeops/internal/handler/handler.go
- https://github.com/kubeapps/kubeapps/blob/master/pkg/auth/authgate.go
- https://github.com/kubeapps/kubeapps/blob/master/pkg/dbutils/postgresql_utils_test.go
- https://github.com/kubeapps/kubeapps/blob/master/pkg/dbutils/postgresql_utils.go
- https://github.com/kubeapps/kubeapps/blob/master/pkg/dbutils/dbutilstest/pgtest/pgtest.go
-

**Comment by castelblanque** [comment]
I would say that Kubeapps is almost already monorepo, isn't it?
Since stuff like Dashboard and backend is included in the same one, for example.

Code in https://github.com/kubeapps/common is formed by 4 go files, and most likely used by Kubeapps only?
I would vote for moving those files into `pkg` and discontinue the `common` repo. And, as you recommend, doing some cleanup in the process 😄

**Comment by absoludity** [comment]
+1 . I don't even remember the history here... I'd guess it was because there was common code shared between Kubeapps and monocular, but I see no reason for us to keep it now.
