### ISSUE TITLE
Reduce same-purpose Go dependencies 

### ISSUE THREAD

**Issue by antgamdia** [kubeapps/kubeapps#3848]
### Description:

While upgrading our deps in the past, I noticed we are using a bunch of dependencies for the same purpose. Unless there is an actual reason for doing so, I think we should keep our dependencies as tight as possible.

#### Duplicated YAML deps:

- github.com/ghodss/yaml v1.0.0
- gopkg.in/yaml.v2 v2.4.0
- sigs.k8s.io/yaml v1.3.0
- k8s.io/apimachinery/pkg/util/yaml

#### Duplicated logging deps:

- k8s.io/klog/v2 v2.30.0
- github.com/pkg/errors v0.9.1
- github.com/sirupsen/logrus v1.8.1

#### Dupplicated deps

- github.com/Masterminds/semver v1.5.0
- github.com/Masterminds/semver/v3 v3.1.1

**Comment by absoludity** [comment]
+1 for the more obvious ones (semver v3, yaml). With the logging ones, +1 to use klog/v2, but how is the errors package related to logging? (It should be superseded by the standard errors pkg now, I tihnk?)

**Comment by antgamdia** [comment]
WRT Duplicated logging deps, citing this [Michael's comment](https://github.com/kubeapps/kubeapps/discussions/4087#discussioncomment-2029801) for the record:

> We can (and should) update in the kubeapps apisserver to using klog.InfoS and klog.ErrorS which are drop-in replacements, then users can choose to add the --logging-format option to the deployment (or better, we enable from the chart). At least that would have us enabling structured logging in the main service into the future.

**Comment by antgamdia** [comment]
Solved via:

- [ ] https://github.com/kubeapps/kubeapps/pull/4177
- [ ] https://github.com/kubeapps/kubeapps/pull/4178
- [ ] https://github.com/kubeapps/kubeapps/pull/4179
- [ ] https://github.com/kubeapps/kubeapps/pull/4180

Using named import is something still under discussion at https://github.com/kubeapps/kubeapps/pull/4176 (although it doesn't affect to this issue, directly)
