### ISSUE TITLE
Support OIDC tokens from a third party provider

### ISSUE THREAD

**Issue by dlohin** [kubeapps/kubeapps#385]
Allow for the support of OpenID tokens to be given to authenticate users to Kubeapps in a manner similiar to Kubernetes Dashboard.  

The administrator should be able to place a reverse proxy in front of Kubeapps which will redirect users to an Identity Provider (IdP).  User then authenticates and a bearer token is given to the proxy.  This bearer token is then injected transparently into subsequent requests by the user.

The OIDC process is documented here for Kubernetes: https://kubernetes.io/docs/reference/access-authn-authz/authentication/

It should be possible to tie a group provided in the Json Web Token (JWT) to a ClusterRoleBinding within Kubernetes.  

`kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: keycloak-admin-group
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: Group
  name: /admin`

**Comment by prydonius** [comment]
FYI this was made possible in the Kubernetes Dashboard with https://github.com/kubernetes/dashboard/pull/1539

**Comment by andresmgot** [comment]
This is now fully available in the version v1.3.0. Check the documentation [here](https://github.com/kubeapps/kubeapps/blob/master/docs/user/using-an-OIDC-provider.md) and please reopen the issue if you find any problem.
