### ISSUE TITLE
Add a mechanism to select a ServiceAccount with which the Carvel bundle will get installed

### ISSUE THREAD

**Issue by antgamdia** [kubeapps/kubeapps#3850]
Parent issue: https://github.com/kubeapps/kubeapps/issues/3849

Some alternatives:

1.  Kubeapps creating SAs (therefore needing a privileged user to install carvel stuff)
    1. Before installing, autogenerate a SA with the proper RBA, or
    2. Letting users select which SA and RBAC they want to grant
2.  Kubeapps not creating SA:
    1. Before installing, a user would select a SA from a list of available SA within a given namespace. Throw any RBAC errors back, or
    2. Letting users write the name of the SA (not listing perms required). Throw any RBAC errors back.

Personally, I don't think Kubeapps should be that privilege piece creating SAs and RBACs... so I'd rather discard option 1). 
Instead, I'd go with 2.1 and 2.2, I mean:

In the deployment form, we could query if the user can list SAs; if so, I'd render a dropdown with all the available SAs in the current namespace. Otherwise, if the listing fails, I'd fall back to rendering a text input so that the user can write which SA they want.

![image](https://user-images.githubusercontent.com/11535726/143925165-4a2e2b7c-7ef5-4a95-ad01-92a896646e49.png)

![image](https://user-images.githubusercontent.com/11535726/143925592-a75da9a6-250d-49b2-8f1b-c34c45167880.png)

**Comment by castelblanque** [comment]
Agree with your approach @antgamdia , Kubeapps could not always have enough privileges to create service accounts.
Seems that approach "2" is the most reasonable one.
Question: for listing eligible services accounts for the dropdown would we need some filtering? There might be existing accounts not meant for being used by Kubeapps? In that case some annotations in the service account would suffice?

**Comment by absoludity** [comment]
Yes - agreed. Let's steer very clear of Kubeapps having special RBAC (especially as this would need to be unlimited to be able to create the service account and RBAC).

I'd (personally) do your 2.1 and 2.2 as separate phases: support the case where users require RBAC to list service accounts in the NS. This is going to be the 80-90% usage (imo). Then decide if we want to additionally support the case where a user cannot list SA's, but can read them (your 2.2)... I'd do this if we find people needing it, personally.

> Question: for listing eligible services accounts for the dropdown would we need some filtering? There might be existing accounts not meant for being used by Kubeapps? In that case some annotations in the service account would suffice?

The user is listing those service-accounts, not Kubeapps (I mean, the request is done with the users' credential). I think it's OK to list all service accounts in the ns (that's what I'd expect to see, just like I would on the CLI if I was choosing which SA to use). Yes, we could using annotations/labels to limit this, but I worry it'd be more work and more confusing for users in the end?
