### ISSUE TITLE
Installed app not found right after installing a Carvel package

### ISSUE THREAD

**Issue by antgamdia** [kubeapps/kubeapps#3852]
Parent issue: https://github.com/kubeapps/kubeapps/issues/3849

When a package is installed, we got redirected to the InstalledPackage view, which is great. The problem is that Kapp hasn't created the `App` resource yet. Alternatives (I'd go with 2)

1. Auto-retry from the UI in N attempts
    -  follow-up idea: should we add exp. backoff retries to every get-alike request to avoid transient API connectivity issues?
2. Check the `App` resource exists in the backend before sending the OK response back.

**Comment by castelblanque** [comment]
What do you think about having the InstalledPackage view to listen to events from the backend until the App resource is communicated to be existing? In a similar fashion to what Michael has done in the resources plugin.
It could be independent from any previous step that the user was doing: whenever entering the InstalledPackage view -> listen to backend events until "App" resource is received...or timed out.

It is just an idea 😃

**Comment by absoludity** [comment]
> What do you think about having the InstalledPackage view to listen to events from the backend until the App resource is communicated to be existing? In a similar fashion to what Michael has done in the resources plugin.

Unfortunately for technical reasons (related to matching the packaging core interface) we can't use streaming in the packaging API :/ (more [info here](https://github.com/grpc/grpc-go/issues/4500)).

Now, the actual Carvel CR is created syncronously (PackageInstall), so yes, there should be no need to return a not found error. I think this is what you mean by your 2nd option Antonio? (As in, if the request finds the PackageInstall, then the server can set a deadline in the context and wait for the kapp app to be created before returning OK). If so, +1 for that option. Obviously a not found error is perfect when the `PackageInstall` itself is not found (since it should be created synchronously).

**Comment by castelblanque** [comment]
Thanks for the explanation about that technical limitation Michael!

For my understanding, sorry 😅 : after having the `PackageInstall` synchronously created, user will be shown the InstalledPackage view. In case the `App` is not existing, what is being shown in the view until the kapp controller has finished its job? and how does the view update for reflecting new status? (e.g. server sets a deadline of 30s and Kapp controller finishes in 10s)

**Comment by absoludity** [comment]
> For my understanding, sorry sweat_smile : after having the `PackageInstall` synchronously created, user will be shown the InstalledPackage view.

They'll be redirected to the InstalledPackage view and see a spinner (as the `GetInstalledPackageDetails` request won't have yet returned...

> In case the `App` is not existing, what is being shown in the view until the kapp controller has finished its job?

They'll see the spinner for a few more milli-seconds until the controller creates the `App` and the `GetInstalledPackageDetails` request completes and returns the data.

> and how does the view update for reflecting new status? (e.g. server sets a deadline of 30s and Kapp controller finishes in 10s)

Hopefully the times involved are in the order of milli-seconds, but yes, the view would still be showing the spinner until the `GetInstalledPackageDetail` request returns at which point the redux state is updated and the view updates based on the state. The key point being that the view does not even render (stays with the spinner) until the `GetInstalledPackageDetails` returns, and it only returns after the `App` has been created. That's the thought anyway, afaiui.
