### ISSUE TITLE
Provide initial values when installing a Carvel package

### ISSUE THREAD

**Issue by antgamdia** [kubeapps/kubeapps#3853]
Parent issue: https://github.com/kubeapps/kubeapps/issues/3849

Carvel packages do not have any "default values.yaml" file, or, at least, there is no standard/recommended Carvel-way to do that. As a result, users will see an empty textarea waiting for them to add all the values. Ideas (I'd go with 1)

1. Auto-infer a values.yaml file using the OpenAPI Schema (follow-up idea: we are gonna need to parse this schema at some point... should we just implement this "advanced form" now -two birds one stone - ? 
2. Do nothing until Carvel folks recommend something.

**Comment by antgamdia** [comment]
As per @vrabbi's suggestion (thanks for the pointer!) , le also consider the work done in https://github.com/vmware-tanzu/tanzu-framework/pull/1422/

**Comment by antgamdia** [comment]
Confirming this approach is doable :)

![image](https://user-images.githubusercontent.com/11535726/147957546-33386615-2323-4b67-92ab-a40bd5db7a77.png)

Still have to check a couple of things (marshaling issues, checking why Tanzu Framework folks decided to adapt the k8s code, add tests, etc.).

**Comment by antgamdia** [comment]
#### Quick update (Jan 4th):

After a few tweaks in the code, the values can be auto-inferred (using the `default` in the Schema and fallback to `""`, `0`, `false`, `[]` and `{}`).

![image](https://user-images.githubusercontent.com/11535726/148054463-81e158d3-a64f-45fd-966c-94f23d7fc390.png)

Just out of curiosity, I've pulled the changes in https://github.com/kubeapps/kubeapps/pull/3527. It works pretty decently (though some performance issues appear when the schema is large). Perhaps we may want to add these changes in a follow-up PR or even work on the "advanced form" tab,

![image](https://user-images.githubusercontent.com/11535726/148055055-15c0e0e6-a0a6-4460-b603-5e7cfea4092f.png)

**Comment by vrabbi** [comment]
this looks awesome! the form would also be great to have!
