### ISSUE TITLE
Improve UI handling while backend is still starting up or upgrading

### ISSUE THREAD

**Issue by castelblanque** [kubeapps/kubeapps#3912]
### Description:

Whenever Kubeapps backend is still starting up or upgrading, UI shows an unrelated message `Unable to list apps: Invalid GetInstalledPackagedSummaries...`.

One of the cases is Postgres pods not yet ready and UI trying to access backend DB logic.
But this might happen in other situations, like other pods not ready for whatever reason.

### Steps to reproduce the issue:

1. Upgrade Kubeapps installation with low resources (e.g. little CPU and memory + PV for a single PostgreSQL pod?)
2. While pod is not yet "Ready", try listing installed packages from UI.

### Describe the results you received:

Following message is thrown:
![image](https://user-images.githubusercontent.com/67455978/144989694-fc05bfb3-dfc3-4018-9aa9-894e2b15c79a.png)

### Describe the results you expected:

Some specific message informing the user to wait while system gets ready.

**Comment by antgamdia** [comment]
Similarly, I'd also improve the message when the connection to the API server has been lost (likely because a pod is being restarted or OOMKilled).

Perhaps this issue is practically the same as https://github.com/kubeapps/kubeapps/issues/3723, feel free to leave as is or even close one of them if you consider it's a duplicate.

**Comment by castelblanque** [comment]
Yeah, just landed #4084 which is not the solution for this issue, but might help towards a better handling of errors in UI.

Errors like the one mentioned in this issue can not be differentiated (e.g. `pq relation "charts" does not exist` comes from the Helm plugin) in order to express them in a more meaningful way (following the example before, this would be something like `Database is not up and running. Please wait.` or similar).

Closing in favor of #3723 and #4084.
