### ISSUE TITLE
Question about authentication

### ISSUE THREAD

**Issue by jboesh** [kubeapps/kubeapps#3961]
Hi

is it possible to disable the authentication (ie not ask for a token when going to the kubeapps application)?
I have my own authentication in the cluster (oauth2-proxy) that I want to use for this.

I find it very annoying to have to log in with a token every time.

so 2 specific questions:
1. can I disable authentication somehow? so that no token is requested?
2. if authentication cannot be turned off, can I use my own password instead?

thanks in advance!

**Comment by antgamdia** [comment]
Hi @jboesh ,

please note the token authentication is only intended for demo purposes; any production deployment should use the OIDC approach, which I think also fits your needs.
I guess you need to let Kubeapps know which OIDC config you are using. In fact, we also use oauth2proxy.

Once you've done that, it is possible for Kubeapps to skip the login page: you only need to set to true the `.authProxy.skipKubeappsLoginPage` in the values.yaml file ([source](https://github.com/kubeapps/kubeapps/blob/v2.4.2/chart/kubeapps/templates/dashboard/configmap.yaml#L76))

Hope this answers your question!
