### ISSUE TITLE
Question: application repository

### ISSUE THREAD

**Issue by jboesh** [kubeapps/kubeapps#3963]
Hi

Ive got one application respository (https://charts.bitnami.com/bitnami)
I was wondering if there are more that I can add and use in Kubeapps.

Thanks in advance

**Comment by antgamdia** [comment]
Hi @jboesh ,

thanks for your interest in discovering new repositories. Every provider could offer their own Helm repository for distributing their content, nonetheless, I would personally recommend https://artifacthub.io, an aggregator of different sources.
In addition, the [VMware Marketplace](https://marketplace.cloud.vmware.com/) is also offering plenty of content, including Helm charts and other artifacts for Kubernetes clusters.

In [this guide](https://github.com/kubeapps/kubeapps/blob/master/docs/step-by-step/kubeapps-on-tkg/step-3.md) we explain how to add the VMware Marketplace and other production-ready and commercial repositories such as the [VMware Application Catalog](https://tanzu.vmware.com/application-catalog).
