### ISSUE TITLE
Error installing any app with AVI LB

### ISSUE THREAD

**Issue by castelblanque** [kubeapps/kubeapps#3980]
### Description:

When trying to install any app from i.e. bitnami repo, a message `Error:` is written in the frontend and this message appears on the `kubeapps` pod (added line breaks for clarity):

```
2021/12/09 14:10:01 [error] 25#25: *35280 upstream prematurely closed connection while reading response header from upstream, 
client: X.X.X.X, 
server: _, 
request: "POST /apis/kubeappsapis.core.packages.v1alpha1.PackagesService/CreateInstalledPackage HTTP/1.1", 
upstream: "http://Y.Y.Y.Y:8080/kubeappsapis.core.packages.v1alpha1.PackagesService/CreateInstalledPackage", 
host: "Z.Z.Z.Z", 
referrer: "http://Z.Z.Z.Z/"
```

The service type is Load Balancer, backed by AVI LB.

### Describe the results you received:

`Error: ` in the frontend, and a more descriptive error in the Kubeapps-apis pod.

### Describe the results you expected:

Packages to be installed without any error.

### Additional information you deem important (e.g. issue happens only occasionally):

Issue happens consistently.
Same error trying to deploy an app with kubeapps when using `kubectl port-forward -n kubeapps svc/kubeapps 8080:80` instead of load balancer IP.

### Version Kubeapps:

2.4.1

**Comment by castelblanque** [comment]
As stated by the reporter person:
`Same error trying to deploy an app with kubeapps when using kubectl port-forward -n kubeapps svc/kubeapps 8080:80 instead of load balancer IP.`

This suggest that the load balancer is out of the picture.
Requested more information.

**Comment by ppbaena** [comment]
To be closed as no additional information related to the issue was provided.
If you find anything new, please consider to reopen the issue.
Thanks.
