### ISSUE TITLE
Update client-go to 4.0.0 or greater

### ISSUE THREAD

**Issue by prydonius** [kubeapps/kubeapps#40]
In order to use client-go to create a portforward connection, we need the remotecommand or spdy package. remotecommand moved to client-go in https://github.com/kubernetes/client-go/commit/20e59c60f899e4e2b16161938abe0f33b60ff570#diff-8656ac6cd2859b6ba2961d35c31735b4 and previously this was in kubernetes/kubernetes. This is how kubectl implements portforward today 
with the spdy package (https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/portforward.go#L102) and previously with remotecommand (https://github.com/kubernetes/kubernetes/blob/2612e0c78ad18ac87bbd200d547100cf99f36089/pkg/kubectl/cmd/portforward.go#L104).

So, in order to avoid adding kubernetes/kubernetes as a dependency here, we could upgrade client-go. The problem is that this pulls in a newer version of apimachinery which doesn't seem to be compatible with kubecfg. As usual, we're in Kubernetes dependency hell...

There might be another way to implement this, but I couldn't find any other documentation than what `kubectl` is doing.

For now, we can have the `dashboard` command execute `kubectl port-forward`, but ideally we're able to use the client-go library to create this portforward.

**Comment by ngtuna** [comment]
I might be missing things today (too busy trying to understand gcloud cli :-( ), but what do you intend to do with `portforward` connection in installer ?

**Comment by prydonius** [comment]
@ngtuna sorry, it's for the dashboard command which will setup a port-forward with the nginx controller pod. See #41

**Comment by ngtuna** [comment]
Ref #65

**Comment by ngtuna** [comment]
closed via #65
