### ISSUE TITLE
Deleting a repository with deployed charts creates an error

### ISSUE THREAD

**Issue by dlohin** [kubeapps/kubeapps#400]
When a user deploys a chart and then later decides to remove the repository without first deleting all the charts created by that repository the applications screen will no longer load giving the user an error message:

![image](https://user-images.githubusercontent.com/20578548/42585554-f1a62fd4-8503-11e8-9097-0971a14e91f9.png)

If I look at developer tools I can see the problem, as it is referencing objects from the old repostiory (in this case I deleted stable)
![image](https://user-images.githubusercontent.com/20578548/42585611-1de02bcc-8504-11e8-89e5-5e5ea9623f44.png)

To recover from this error, I have been able to add the repository back with the same name, then it will load and I can delete the charts.

I would either recommend not letting a user delete a repository until all charts are first deleted or give users another way to delete orphaned charts.

**Comment by prydonius** [comment]
Thanks! I believe this might actually be fixed with the tiller-proxy stuff since we don't need the chartsvc anymore, I can try to see if it's still an issue in master.

**Comment by prydonius** [comment]
@dlohin this indeed will be fixed in the next release (v1.0.0-alpha.5) as part of the changes to use the Tiller Proxy service. Now, if a chart repository is deleted, any charts deployed from that repository are still viewable in the Apps sections and can be deleted and also upgraded by selecting the repo from a list.

What do you think of that experience?

**Comment by dlohin** [comment]
That sounds great!  As long as the user can recover from the state I think that is fine.  Thanks for your response!  Looking forward to trying out alpha 5.
