### ISSUE TITLE
Error messages when rendering templates improperly

### ISSUE THREAD

**Issue by dlohin** [kubeapps/kubeapps#401]
In order to provide a better user experience it would be nice to print messages from the Helm render process.  For example, helm lets you specify a "required" value and when a user doesn't input this you can print error messages.

```
{{ required "Please enter a valid host name!" .Values.ingress.host }}
```

When a user doesn't input these, sometimes they are currently presented with a generic error message and sometimes I have seen it hang on loading.  I haven't figured out why there is different outcomes.

![screen shot 2018-07-11 at 12 10 40 pm](https://user-images.githubusercontent.com/20578548/42586192-90366d98-8505-11e8-9e90-3f74473bf571.png)

![screen shot 2018-07-11 at 8 47 20 am](https://user-images.githubusercontent.com/20578548/42586310-cbffdd78-8505-11e8-8489-b4e2bf863b3d.png)

Tiller does properly display the message in the error logs.

```
[tiller] 2018/07/11 12:33:02 failed install prepare step: render error in "kibana/templates/kibana-ingress.yaml": template: kibana/templates/kibana-ingress.yaml:12:13: executing "kibana/templates/kibana-ingress.yaml" at <required "Please ent...>: error calling required: Please enter a valid host name!
```

It would be nice if somehow tiller messages could make it back to the user.

**Comment by andresmgot** [comment]
just to be able to quickly reproduce the issue, can you put an example of chart that has a required field?

**Comment by dlohin** [comment]
Sure, here you go!  http://repos.sealingtech.org/dev/kibana-required.tgz

The part the doesn't work is in the ingress.
http://repos.sealingtech.org/dev/kibana/templates/kibana-ingress.yaml

What I was hoping to be able to do is leave the ingress.host value blank so that if a user just clicked through it would error and give them a useful descriptive message "Please enter a valid host name!".

**Comment by andresmgot** [comment]
#466 has been landed so we can close this issue. In future releases (or when using `latest` for the dashboard and tiller-proxy) it will show the error returned by Tiller if the installation goes wrong.
