### ISSUE TITLE
Support Kubernetes API Service proxy endpoint like Kubernetes Dashboard

### ISSUE THREAD

**Issue by prydonius** [kubeapps/kubeapps#402]
As we move away from the `kubeapps` CLI, we should rethink the recommended way to access the Kubeapps Dashboard. Today, the `kubeapps dashboard` does a port-forward to the `kubeapps` pod. Without the CLI the same can be accomplished using the `kubectl port-forward ...` command. However this is a bit more complex to use as it requires figuring out the pod name.

The Kubernetes Dashboard [recommends users use `kubectl proxy`](https://github.com/kubernetes/dashboard#getting-started) to setup a secure proxy to the Kubernetes API and points users to access the known URL, `http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/`.

We could support the same method in Kubeapps and point users to `http://localhost:8001/api/v1/namespaces/kubeapps/services/http:kubeapps:/proxy/`. This currently doesn't work correctly as the Dashboard and potentially the NGINX proxy expects to be under the root and not under a subpath[1]. We would need to make some changes to ensure Kubeapps works correctly under a subpath.

Supporting this method has the following advantages:
- familiar to Kubernetes Dashboard users
- proxies to the Service rather than the Pod, which is the correct way of accessing services within Kubernetes
- Easier than a complex `kubectl port-forward` command
- Potentially more reliable the `kubectl port-forward` (some people have reported issues of flaky connections with port forward, but it's not clear if this also affects proxy)

cc @migmartri

[1] ![screen shot 2018-07-11 at 14 35 42](https://user-images.githubusercontent.com/1544861/42600580-b82e2310-8517-11e8-91d1-239a12b9414b.png)

**Comment by prydonius** [comment]
We'll need to enable hash-based routing in order to make this work

**Comment by prydonius** [comment]
Note that enabling hash-based routing will also allow Kubeapps to be mounted under a subpath (e.g. internal.domain.com/kubeapps), which has been requested by some folks.

**Comment by malejpavouk** [comment]
It would be really cool, as we have multiple apps running on our server and we want the users to use standard ports (80 or 443). 
And we can't simply deploy kubeapps on rootpath "/", as it would cause path collisions. Deploying it under some context (such as "/kubeapps") would really be helpful.

**Comment by prydonius** [comment]
thanks for the feedback @malejpavouk

**Comment by prydonius** [comment]
Had some time to look into this, it won't be possible to support `kubectl proxy` because the proxy will strip the Kubeapps Authorization header, by design: https://github.com/kubernetes/kubernetes/issues/38775.

We could still switch to hash-based routing to support mounting Kubeapps on a subpath (e.g. mydomain.com/kubeapps), however it's not straightforward to make asset URLs (like the Kubeapps logo) relative with the way we import them:

https://github.com/kubeapps/kubeapps/blob/1bf5a257e787bee2b6702da9649629adae45c6ed/dashboard/src/components/Header/Header.tsx#L3

create-react-app does support relative URLs for this https://github.com/facebook/create-react-app/pull/1489, but this change doesn't seem to be present in the react-scripts-ts fork we use, so we might need to eject to get that support.

An easier way to support a subpath would be to set the basename in React router (https://reacttraining.com/react-router/web/api/BrowserRouter/basename-string), which we can get from a configuration option (via config.json).

**Comment by migmartri** [comment]
Thanks for the research. How important do you think it is to support paths? To me it is important since it is an exposed value in the ingress but want to know your take.

> An easier way to support a subpath would be to set the basename in React router (https://reacttraining.com/react-router/web/api/BrowserRouter/basename-string), which we can get from a configuration option (via config.json).

This sounds good.

**Comment by prydonius** [comment]
@migmartri a couple people seem to have run into this (based on slack conversations), and it's a fairly bad experience right now as it's not clear that it doesn't work. I think if the solution is simple enough with the basename, it's worth implementing it. I don't think it's an ideal solution, because it requires setting the path you want to use in the values.yaml, but we can make that a setting in the ingress configuration so it's tied together.

**Comment by stormmore** [comment]
checkout the `PUBLIC_URL` environment variable. I came across it in a react admin app and pretty sure it applies to create-react-apps too.

**Comment by migmartri** [comment]
I've doing some testing and managed to make the app work in a subpath by doing:

1 - changing only the basename in react router is not enough since underneath API calls for kube/api and tiller-proxy will be using `/`

![selection_793](https://user-images.githubusercontent.com/24523/50121435-664b5c00-021e-11e9-9ac6-93241d0d6cf5.png)
 
2 - Changing the ingress path (to a value including backslash) gets us close but the static files are redirected  to index.html due to our Nginx config `try_files $uri /index.html;` Updating our Nginx config map configuration does the trick.

i.e 
```
      location / {
        rewrite  ^/[MY_INGRESS_PATH]/(.*) /$1 break;

        try_files $uri $uri/ /index.html;
      }
``` 

3 - Then there are some changes that need to happen in the app, like for example making /config.json to relative or every single /api/kube reference.

We would need to make 1 and 2 take effect part of the chart configuration so they map the ingress path. Alternatively we could replace 1 for using hash URLs instead.

**Comment by migmartri** [comment]
Actually I am wrong. It seems that changing the router basename messes with the relative paths in index.html.

**Comment by Keithsc** [comment]
I am trying to get Kubeapps to work on https://mysite.com/kubeapps. The kubeapps page appears but there's a blue throbbing circle in the middle of the page.

I am using the Kubernetes 14.1 with the nginx ingress controller and am changing the following values in my helm-values.yaml

ingress:
  enabled: true
    kubernetes.io/ingress.class: public
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
  hosts:
  - name: mysite.com
    path: /kubeapps/

In my browser I can see that all the request get a 200 except one that gets a 404 for "/" 

helm ls  show the following...
kubeapps  kubeapps-1.6.2 	v1.3.2 kubeapps

Any helm would be appreciated.

**Comment by andresmgot** [comment]
hi @Keithsc, I can reproduce the issue, there is a very similar issue already active: https://github.com/kubeapps/kubeapps/issues/1005 Let me reply to you there
