### ISSUE TITLE
readme for dex chart always loading

### ISSUE THREAD

**Issue by prydonius** [kubeapps/kubeapps#408]
The dex chart doesn't have a README.md (https://github.com/helm/charts/tree/master/stable/dex) but it is shown as constantly Loading in the UI:

![screen shot 2018-07-23 at 5 55 01 pm](https://user-images.githubusercontent.com/1544861/43112879-dd78999a-8eac-11e8-9bff-5bb5c53ce972.png)

The README.md should have a 404 response

**Comment by arapulido** [comment]
@prydonius might this be a regression? You fixed that in the past with https://github.com/kubeapps/kubeapps/pull/223/files

**Comment by prydonius** [comment]
@arapulido yes I think it is, I was thinking this issue was familiar :P
