### ISSUE TITLE
Add ingressClassName option to the Help ingress section

### ISSUE THREAD

**Issue by foal** [kubeapps/kubeapps#4086]
### Description:

Try to specify `ingressClassName` for kubeapps ingress, but the current Helm chart doesn't support it

### Describe the results you received:

No way to specify the `ingressClassName` during deployment 

### Describe the results you expected:

Specify the `ingressClassName` during deployment if it is necessary.

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
helm version
version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.16.10"}
```

- Output of `helm list -n <kubeapps-namespace> <kubeapps-release-name>`:

```
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
kubeapps        kubeapps        9               2022-01-08 14:34:58.748372215 +0000 UTC deployed        kubeapps-7.7.0  2.4.2
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:42:41Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by antgamdia** [comment]
Hi @foal ,

I thought it was added, but we only include this annotation for the cert-manager (`Values.ingress.certManager.httpIngressClass`) but not for the Kubeapps chart itself.

However, the Kubeapps official chart is the one being managed by Bitnami (https://github.com/bitnami/charts/blob/master/bitnami/kubeapps); a specific team is in charge of performing all the changes in the chart and we just periodically sync our chart with theirs.
So, any chart-related issue or PR should be filed in the [bitnami/charts](https://github.com/bitnami/charts/) repository instead.

As far as I am concerned, they are in an ongoing process of standardizing their charts, but it is a tedious task requiring some effort. So, eventually, the Kubeapps chart will get this `ingressClassName` field.

If you want to speed up the process, I suggest you have a look at one of the latest changes they did (for example, this [ingress template in the bitnami/apache chart](https://github.com/bitnami/charts/blob/master/bitnami/apache/templates/ingress.yaml)) and try to adapt the [kubeapps nginx template](https://github.com/kubeapps/kubeapps/blob/master/chart/kubeapps/templates/ingress.yaml) to the "new" format.

Once you have it, please [open a PR in the bitnami/charts](https://github.com/bitnami/charts/pulls) repo and they will kindly review and accept it. It is at that moment that the chart gets immediately updated and published (meaning you don't have to wait until a new Kubeapps release to get the fix).

**Comment by antgamdia** [comment]
As an initial idea, perhaps something like this could work (but I haven't personally tested it). Again, the best option is to send a PR to the bitnami/charts folks and get their feedback.

```yaml
{{- if .Values.ingress.enabled -}}
apiVersion: {{ include "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" . ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.ingress.certManager }}
    {{- if .Values.ingress.certManager.clusterIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.certManager.clusterIssuer }}
    {{- end }}
    {{- if .Values.ingress.certManager.httpIngressClass }}
    acme.cert-manager.io/http01-ingress-class: {{ .Values.ingress.certManager.httpIngressClass }}
    {{- end }}
    {{- if .Values.ingress.certManager.commonName }}
    cert-manager.io/common-name: {{ .Values.ingress.certManager.commonName }}
    {{- end }}
    {{- end }}
    {{- if .Values.ingress.annotations }}
    {{- include "common.tplvalues.render" (dict "value" .Values.ingress.annotations "context" . ) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" . ) | nindent 4 }}
    {{- end }}
spec:
  {{- if and .Values.ingress.ingressClassName (eq "true" (include "common.ingress.supportsIngressClassname" .)) }}
  ingressClassName: {{ .Values.ingress.ingressClassName | quote }}
  {{- end }}
  rules:
    {{- if .Values.ingress.hostname }}
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          {{- if .Values.ingress.extraPaths }}
          {{- toYaml .Values.ingress.extraPaths | nindent 10 }}
          {{- end }}
          - path: {{ .Values.ingress.path }}
            {{- if eq "true" (include "common.ingress.supportsPathType" $) }}
            pathType: {{ $.Values.ingress.pathType }}
            {{- end }}
            backend: {{- include "common.ingress.backend" (dict "serviceName" (include "common.names.fullname" $) "servicePort" "http" "context" $)  | nindent 14 }}
    {{- end }}
    {{- range .Values.ingress.extraHosts }}
    - host: {{ .name | quote }}
      http:
        paths:
          - path: {{ default "/" .path }}
            {{- if eq "true" (include "common.ingress.supportsPathType" $) }}
            pathType: {{ $.Values.ingress.pathType }}
            {{- end }}
            backend: {{- include "common.ingress.backend" (dict "serviceName" (include "common.names.fullname" $) "servicePort" "http" "context" $)  | nindent 14 }}
    {{- end }}
  {{- if or (and .Values.ingress.tls (or .Values.ingress.certManager .Values.ingress.selfSigned)) .Values.ingress.extraTls }}
  tls:
    {{- if and .Values.ingress.tls (or .Values.ingress.certManager .Values.ingress.selfSigned) }}
    - hosts:
        - {{ .Values.ingress.hostname | quote }}
      secretName: {{ printf "%s-tls" .Values.ingress.hostname }}
    {{- end }}
    {{- if .Values.ingress.extraTls }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.ingress.extraTls "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
```

**Comment by ppbaena** [comment]
Thanks for your reply @antgamdia.
I'm closing this issue as everything is on the side of bitnami charts.

**Comment by absoludity** [comment]
JFTR, support for `ingressClassName` is added in https://github.com/bitnami/charts/pull/9441.
