### ISSUE TITLE
Validate Service Catalog form inputs against JSON Schema before submitting

### ISSUE THREAD

**Issue by arapulido** [kubeapps/kubeapps#410]
The Google PubSub Beta plan has two required fields for bindings: roles and serviceaccountid, but only service account id is checked before submitting that it has been filled:

![screen shot 2018-07-24 at 11 48 02 am](https://user-images.githubusercontent.com/925437/43130715-8de9d7e6-8f37-11e8-8ad2-ea8c8834b998.png)

You can submit the form without selecting a role and you would get the following error from the broker:

```
Bind call failed: operation "projects/774136762833/operations/7cbf0cf3-8e8f-11e8-a033-0242ac110019/1532360757420933595" failed: generic::internal: operation projects/774136762833/operations/7cbf0cf3-8e8f-11e8-a033-0242ac110019/1532360757420933595 create binding deployment failed: generic::invalid_argument: Operation "operation-1532360758209-571ac8aa929e9-30d7af30-5aeed865" failed with : [{"code":"MANIFEST_EXPANSION_USER_ERROR","location":"/deployments/b45e0e9c4-d410-44f7-afed-644c97abec74/manifests/manifest-1532360758337","message":"Manifest expansion encountered the following errors: Invalid properties for 'gcp-services/composite:cloud-pubsub-binding-f3622e2':\n'roles' is a required property at ['parameters']\n Resource: b45e0e9c4-d410-44f7-afed-644c97abec74 Resource: config"}]
```

**Comment by prydonius** [comment]
We're relying on the browser validation, we probably want to validate the input with the JSON Schema before submitting to improve this.
