### ISSUE TITLE
flux plugin: switch to using flux native data types instead of unstructured 

### ISSUE THREAD

**Issue by gfichtenholt** [kubeapps/kubeapps#4112]
Documenting leftover items for flux plugin per Pepe's request so we can prioritize it against other work

This is a leftover item from #3899

@antgamdia  said:
Not now, but perhaps we can use the typed struct instead of dealing with the unstructured data directly (as I'm doing in the kapp plugin).

This has been on my TODO list for a while. To be clear. The benefit to end user is none. But the benefit to developers/maintainers of this code is huge. Code based on unstructured types is difficult to work with/maintain and is error prone. Not to mention very verbose. 
Ideally, I'd want to switch to use APIs like https://github.com/fluxcd/source-controller/tree/main/api/v1beta1 which should make the code much more concise and easier to read.

**Comment by antgamdia** [comment]
Totally agree, there is no direct user-faced benefit, but from a developer pov, the difference is huge. For the record, find below a screenshot comparing the two approaches:

![image](https://user-images.githubusercontent.com/11535726/150106058-f8becc07-191b-4eff-bfeb-9c03034d7451.png)

**Comment by gfichtenholt** [comment]
Just FYI, I did see what Antonio did with kapp_controller and I am hoping to take things a bit further and least in flux plugin. In kapp_controller there are constant conversions from unstructured to typed (`runtime.DefaultUnstructuredConverter.FromUnstructured`) and back (`runtime.DefaultUnstructuredConverter.ToUnstructured`)  due to having to work with `dynamic.Interface` behind the scenes to access server resources. dynamic.Interface forces one to use unstructured, therefore constant back and forth. Yes, what is there now a reasonable first step. But, for flux, I am hoping to eventually get rid of dependency on `dynamic.Interface` in production code and tests and replace it with something like https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.11.0/pkg/client#Client which will let me work with typed objects all the way from server to caller and back. This is a bit of work though. A lot of existing code (production and tests) will need to be refactored, but I feel it's worth the effort.

**Comment by absoludity** [comment]
Excellent, that'd be great to be able to use a typed client without having to use the same client-go version as the upstream go lib (carvel/flux - that was what stopped us initially using the typed client for carvel, from memory, needing to update our own go.mod deps to match their version).

**Comment by gfichtenholt** [comment]
still work to do...
