### ISSUE TITLE
Click any application error: "An error occurred: btoa(...).replaceAll is not a function."

### ISSUE THREAD

**Issue by ygqygq2** [kubeapps/kubeapps#4142]
kubeapps version: v2.4.2
Like that
![image](https://user-images.githubusercontent.com/17672440/150472493-c9aa6a92-d12f-421e-a908-b8d1a0f31ab4.png)

![image](https://user-images.githubusercontent.com/17672440/150472412-e04dfa45-0a77-434c-8d04-e01ae99212e4.png)

**Comment by antgamdia** [comment]
Thanks for reporting the issue, however, I'm unable to reproduce it locally as I don't really know which are the steps to repro it.
However, it's true the `atob` and `btoa` functions have been deprecated in favor of `Buffer.from`, so, perhaps it's can be related to.

I'm sending a PR addressing this deprecation.

**Comment by ygqygq2** [comment]
Thanks. It’s not just google chrome

![image](https://user-images.githubusercontent.com/17672440/150630093-825f9f69-58a2-4996-940a-be09ca860787.png)
