### ISSUE TITLE
Remove Functions link from top menu

### ISSUE THREAD

**Issue by prydonius** [kubeapps/kubeapps#416]
We will be removing the Functions link in the top menu. The experimental Functions UI will still be visible by manually navigating to /functions.

Now that Kubeapps will also no longer bundle Kubeless, we also need to display a link to the Kubeless chart if the API doesn't exist (similar to the Service Instances page if the Service Catalog is not installed).

**Comment by andresmgot** [comment]
I am wondering what's the point of maintaining that code if there is no easy way to know that the `/functions` view exists (and it is not reachable through the UI). IMO we should either remove the all the views/components or make it reachable somehow.

**Comment by arapulido** [comment]
@prydonius I think it should be there. Can we make it show if the functions API is there?

**Comment by prydonius** [comment]
In the interesting of moving forward with the release, I think we should hide the Functions link for now and then add support for discovering the Functions API and showing the link if it's there later/in a future release. What do you think?

**Comment by arapulido** [comment]
Sounds good to me! 👍
