### ISSUE TITLE
end2end test for Kubeapps chart deployment

### ISSUE THREAD

**Issue by arapulido** [kubeapps/kubeapps#417]
We should have an e2e test in Kubeapps that does the following:

 * Spins up a new K8s cluster (i.e. in AKS or GKE). We should do this at least for 2 versions of K8s
 * Deploys Tiller
 * Installs the Helm Chart in the cluster
 * Checks that the pods for all deployments are up and running

**Comment by prydonius** [comment]
We may also be able to write a small [Helm test](https://docs.helm.sh/developing_charts/#chart-tests) for basic service checks (or at least we should use this when we develop e2e selenium tests). We should look into using https://github.com/helm/chart-testing which is the tooling used in github.com/helm/charts for testing charts.
