### ISSUE TITLE
Provision to configure or install to remote host

### ISSUE THREAD

**Issue by AkshayDubey29** [kubeapps/kubeapps#419]
Do we have any sort of provision through which we can install using helm on remote K8s cluster?

**Comment by prydonius** [comment]
Currently this isn't possible, is there any reason you can't run Kubeapps on the cluster you want to deploy in?

In the next release, this could be possible if you had Tiller in your remote k8s cluster accessible externally and configured Kubeapps to connect to that Tiller host. I really don't recommend making Tiller externally accessible though.

**Comment by arapulido** [comment]
Closing this one, as the question was replied. @AkshayDubey29 let us know if it doesn't work for you
