### ISSUE TITLE
Fluxv2: GetInstalledPackageResourceRefs() returns not-found initially before flux creates helm release

### ISSUE THREAD

**Issue by absoludity** [kubeapps/kubeapps#4213]
### Description:

When creating an installed package via flux, flux creates the `HelmRelease` and returns, so that the Kubeapps UI redirects to display the installed package details.

The UI requests `GetInstalledPackageResourceRefs()`, but the plugin initially returns a not-found error, because it tries to find the actual helm release which the flux controller hasn't yet created (it's quick, but obviously not synchronous).

I plan to work around this in the UI simply by having the request re-issued a few times in this specific situation, but I think ideally, given that the plugin can easily determine that the `HelmRelease` exists and that the actual helm release will be created (probably in under a second from local testing), that it should in this situation delay returning until the actual helm release has been created and it can continue to return the resource references. This means that clients of the API don't need to handle this. Of course it would still have a context deadline or similar to fail if the actual helm release wasn't created in some reasonable time.

Anyway, that's just my thoughts - let me know what you think.

### Steps to reproduce the issue:

1. Install Kubeapps with fluxv2 enabled
2. Install apache

### Describe the results you received:

UX displays the not-found error, complaining that the actual helm release was not found (because flux is about to create it). Clicking Try again then succeeds and displays the installed package details, including the resources.

### Describe the results you expected:

The UI displays the installed package details without error. (I'll add a work-around to the UX as mentioned above so this is achieved for now).

**Comment by gfichtenholt** [comment]
No problem. I will take a look tomorrow. Thanks

**Comment by gfichtenholt** [comment]
Sorry, just to clarify, are you suggesting I make `CreateInstalledPackage()` into a blocking call? Or introduce some kind of delay mechanism into `GetInstalledPackageResourceRefs()` such that it'll block until the newly created  release appears in helm? Either way, that doesn't feel right. Any artificial blocking I introduce will basically be polling for some condition. So, why poll on the server side? That _feels_ off. Our UX is just one kind of client for kubeapps. We also have (or could have) an REST/gRPC API clients. If I add the polling on the server-side, every client will be affected. Some clients might not care. To me it seems client side should be the one polling. 
Also, we have an API that returns the installed package detail, including status. So, to me it seems logical for UX to poll on status until it shows SUCCESS or FAILURE, and only after that ask for `GetInstalledPackageResourceRefs()`
Having said that, I may have missed something and I am listening and willing to be convinced otherwise.

**Comment by gfichtenholt** [comment]
Okay, from what Antonio said, to draw a parallel to flux plugin, the options are:
1) introduce a wait in `CreateInstallPackage() `so that it waits only until corresponding helm release is created by flux (which is a smaller time window than what it takes to fully reconcile the CR), then return OR
2) introduce a wait in `GetInstalledPackageResourceRefs() `to wait for same condition as (1) OR
3) do nothing on the server side and return error and have the client retry. This is how things work today

DId I get this right?

**Comment by absoludity** [comment]
> Okay, from what Antonio said, to draw a parallel to flux plugin, the options are:
> 
>     1. introduce a wait in `CreateInstallPackage() `so that it waits only until corresponding helm release is created by flux (which is a smaller time window than what it takes to fully reconcile the CR), then return OR

I wasn't suggesting this... since with Flux, we create the `HelmeRelease` object during the `CreateInstallPackage` call - which is (I believe?) the "installed package", and all that endpoint should be responsible for (we have all the data we need to return then).

> 
>     2. introduce a wait in `GetInstalledPackageResourceRefs() `to wait for same condition as (1) OR

This is what I was proposing, only because that endpoint currently just fails with a 404 for an installed package that does exist, as though it was an incorrect call. At that point, the plugin has the data to know that it will be available (and from my quick testing, it's available in less than a second). I don't mind if you disagree and don't want to do this in the backend, since I will work around it in the dashboard anyway, I just wanted to enable clients to make a correct call (what are the resource references for this installed package) and avoid getting a 404 or having to poll. But I don't feel strongly about it - so if you do, no problem.

> 
>     3. do nothing on the server side and return error and have the client retry. This is how things work today

Will work, once I add the workaround in the frontend :)

> 
> 
> DId I get this right?

Yep.

**Comment by gfichtenholt** [comment]
let me just say, I haven't heard a convincing argument yet. (3) is still my preference, but let me sleep on it over the weekend 😄

**Comment by gfichtenholt** [comment]
So spent a couple of hours contemplating it I was about to change my mind on this and go ahead implement (2) when the following occurred to me.
The thing that I feel strongly about is against having a full-blown loop on the server-side that waits
 for a CR to reconcile. I feel it in my gut (Can't really back that up with evidence right now) 
 that kind of code belongs on the client side: a CLI (like flux CLI) would be a perfect example. 
 Now, flux does not give me any kind of special notification when the helm release object is created, 
 so if I were to code it, the logic would look like this (pseudo-code):

```
 timedOut = false
 // this checks flux HelmRelease CR status
 isPending = isHelmReleasePending(key) 
 while (isPending && !timedOut) {
    helmRelease = getHelmReleaseViaActionGetter(key)
    if helmRelease != nil {
       break
    }
    time.Sleep(someSmallDuration)
    // this checks flux HelmRelease CR status
    isPending = isHelmReleasePending(key)
    timedOut = ...
}
if helmRelease != nil {
   getResoureRefs(helmRelease)
} else {
   return error
}

```
Unlike kapp_controller plugin, I am not waiting for a k8s resource to show up, but rather a helm artifact.
Checking the resource status just lets me exit the loop as soon as the resource has been reconciled 
(suucessfully or failed)
You will notice this is very similar (or in the worst case scenario, exactly the same) loop that
 I was trying to avoid having on the server-side, basically wait for the object to reconcile and 
 only then proceed. Can you guys tell me something against that argument that might ease my mind a bit?

**Comment by absoludity** [comment]
> So spent a couple of hours contemplating it I was about to change my mind on this and go ahead implement (2) when the following occurred to me. The thing that I feel strongly about is against having a full-blown loop on the server-side that waits for a CR to reconcile. I feel it in my gut (Can't really back that up with evidence right now) that kind of code belongs on the client side: a CLI (like flux CLI) would be a perfect example.

FWIW, I agree - I think the ideal situation would be that we could do something so that grpc would build all clients to handle the situation and re-request. I just don't yet know how to do that, or whether it's worthwhile even. Anyway, I've already work around it explicitly in the dashboard code (first abstraction above the actual grpc-generated client), so it's not important right now to keep thinking about it IMO.

> Now, flux does not give me any kind of special notification when the helm release object is created, so if I were to code it, the logic would look like this (pseudo-code):
> 
> ```
>  timedOut = false
>  // this checks flux HelmRelease CR status
>  isPending = isHelmReleasePending(key) 
>  while (isPending && !timedOut) {
>     helmRelease = getHelmReleaseViaActionGetter(key)
>     if helmRelease != nil {
>        break
>     }
>     time.Sleep(someSmallDuration)
>     // this checks flux HelmRelease CR status
>     isPending = isHelmReleasePending(key)
>     timedOut = ...
> }
> if helmRelease != nil {
>    getResoureRefs(helmRelease)
> } else {
>    return error
> }
> ```
> 
> Unlike kapp_controller plugin, I am not waiting for a k8s resource, like a ConfigMap, to show up, but rather a helm artifact. 

It is usually a config map, but can be configured to be a secret, so yes, it would be best to get it via the action getter as you suggested (if we ever did this).

> Checking the CR resource status just lets me exit the loop early, as soon as the resource has been reconciled (suucessfully or failed). Obviously, IRL I would implement the loop using `wait.PollImmediateWithContext` but that's besides the point. You will notice this is very similar (or in the worst case scenario, exactly the same) loop that I was trying to avoid having on the server-side, basically wait for the object to reconcile and only then proceed. Can you guys tell me something against that argument that might ease my mind a bit?

Nope. I think your reasons are sound, and you've convinced me :) Happy to close this.

**Comment by gfichtenholt** [comment]
👍

**Comment by absoludity** [comment]
FWIW: good thing we didn't do this as there was another case I'd not counted on: if a flux package is installed with a service account that does not have sufficient RBAC. In this case, the `HelmRelease` is created and sits in a Pending state permanently until the RBAC is updated to allow the service account to be used in the reconciliation. As a result, the resource refs remain not-found for an indeterminate (but long) period of time.
