### ISSUE TITLE
Cannot install Kubeapps

### ISSUE THREAD

**Issue by tjanitsc** [kubeapps/kubeapps#4214]
### Description:

Cannot install Kubeapps

### Steps to reproduce the issue:

1. helm repo add bitnami https://charts.bitnami.com/bitnami
"bitnami" already exists with the same configuration, skipping
2. helm install kubeapps --namespace kubeapps bitnami/kubeapps
Error: INSTALLATION FAILED: failed to download "bitnami/kubeapps"

### Describe the results you received:

helm install kubeapps --namespace kubeapps bitnami/kubeapps
Error: INSTALLATION FAILED: failed to download "bitnami/kubeapps"

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
helm version
version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.5"}
```

- Output of `helm list -n <kubeapps-namespace> <kubeapps-release-name>`:

```
kubectl create namespace kubeapps
namespace/kubeapps created
```

- Output of `kubectl version`:

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:16:20Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.16", GitCommit:"e37e4ab4cc8dcda84f1344dda47a97bb1927d074", GitTreeState:"clean", BuildDate:"2021-10-27T16:20:18Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by antgamdia** [comment]
HI @tjanitsc ,

> Error: INSTALLATION FAILED: failed to download "bitnami/kubeapps"

it seems like a problem when fetching the chart from Helm, I mean, I don't think it is a Kubeapps-related problem.

I would suggest the following:
1. Re-trying the same action (perhaps it was just a transient issue)
2. Try installing another chart from the same bitnami repository
3. Download the chart locally and install it from there, like: `helm upgrade --install kubeapps ./chart/kubeapps -n kubeapps`

Hope it helps!

**Comment by absoludity** [comment]
The `--debug` flag for your `helm install` command may help identify what the issue is downloading Kubeapps too (not sure, but it will give more output, some of which may be relevant).
