### ISSUE TITLE
Discover Kubeless API and show Functions link in navigation if enabled

### ISSUE THREAD

**Issue by prydonius** [kubeapps/kubeapps#422]
With the removal of the Functions link in #416 by default, we should be able to discover if the Kubeless API is available and display the Functions link if it is.

**Comment by andresmgot** [comment]
Any suggestion for the implementation? Probably checking the k8s API every time the component is loaded is not the best approach.

**Comment by prydonius** [comment]
@andresmgot I think that should actually be fine, right? The Navbar is only loaded once so the check would only happen once/on-reload.

**Comment by andresmgot** [comment]
Yeah, I guess it won't be a problem. Probably is worse handle cache issues if we store that somewhere.

**Comment by prydonius** [comment]
won't fix
