### ISSUE TITLE
install error on a fresh k3d k3s cluster. 

### ISSUE THREAD

**Issue by bayeslearner** [kubeapps/kubeapps#4237]
(base) ~ kubectl create namespace kubeapps
helm install kubeapps --namespace kubeapps bitnami/kubeapps
namespace/kubeapps created
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "AppRepository" in version "kubeapps.com/v1alpha1"

[fedora@fedora35 config_kube]$ k3d --version
k3d version v5.2.2
k3s version v1.21.7-k3s1 (default)

**Comment by absoludity** [comment]
Hi @bayeslearner . Can you paste the verbose output when doing the helm install? Also, the output of `helm version`?

Recent helm install command adds CRDs first, before trying to install the k8s resources, as [outlined in their docs](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#install-a-crd-declaration-before-using-the-resource). For Kubeapps, we include an `AppRepository` CR definition, which should be installed by helm in your above command, before it tries to validate the generated release manifest. But for some reason, on your k3s cluster it appears that the `AppRepository` CRD isn't present (or ready?) on the cluster by the time helm moves to install the resources.

The reasons I can think this could be possible would be:
1. An old (2.x) `helm` binary which isn't installing the CRDs,
2. something causing `helm` to move ahead after installing the CRDs, but before they're ready?

You can check the second one with:
```
kubectl get crd apprepositories.kubeapps.com        
NAME                           CREATED AT
apprepositories.kubeapps.com   2022-02-01T03:58:39Z
```
which shows, in my cluster, that it is present (naturally, as I've already installed Kubeapps).
