### ISSUE TITLE
Dashboard shows the Nginx welcome page

### ISSUE THREAD

**Issue by prydonius** [kubeapps/kubeapps#424]
According to https://github.com/bitnami/bitnami-docker-nginx#debian-9-1140-r25-and-ol-7-1140-r46 the path for mounting the nginx vhost has changed from /bitnami/nginx to /opt/bitnami/nginx. We should ensure we update our manifests to mount the vhosts in the right paths.

**Comment by arapulido** [comment]
@prydonius Increased the priority to critical, as the dashboard in master is not currently working due to this issue (you get the nginx welcome page)

**Comment by andresmgot** [comment]
I'll handle it

**Comment by prydonius** [comment]
@arapulido @andresmgot thank you! I think this was due to us using the rolling tag
