### ISSUE TITLE
Olm version in Command is v20 not 20 - typo

### ISSUE THREAD

**Issue by urbanswelt** [kubeapps/kubeapps#4269]
Thank you very much for kubeapps !

https://github.com/kubeapps/kubeapps/blob/78a5f53d2ff85d8c373c48acc4d5f12d7ca29e10/docs/user/operators.md?plain=1#L22

`
curl -L https://github.com/operator-framework/operator-lifecycle-manager/releases/download/v0.20.0/install.sh -o install.sh
chmod +x install.sh
./install.sh v0.20.0

`

**Comment by absoludity** [comment]
Thanks @urbanswelt . Might be a one-liner that @ppbaena can include in the documentation changes he's currently working on?
