### ISSUE TITLE
Reduce size of binary

### ISSUE THREAD

**Issue by sebgoa** [kubeapps/kubeapps#43]
spend a bit of time reducing the size of the binary.

not only basic compression , but maybe Go compilation options ? or reducing some of the deps ?

**Comment by ngtuna** [comment]
I just did a small search around and saw `strip` and `gccgo` will help. Will test it

**Comment by ngtuna** [comment]
`strip` helps, `-ldflags "-s -w"` also helps to reduce the size a bit. One more tool called `upx` reduces the binary dramatically to around 4MB. Need to test the output binary...

**Comment by prydonius** [comment]
I have heard `upx` can cause issues with Go binaries, but haven't actually seen any issues myself. It may be safer to just tar gzip when uploading

**Comment by sebgoa** [comment]
Let's not use extreme tooling. My main point was about the deps and whether we are pulling way too much stuff which may cause the binary to be inflated.

So I was more looking at a review of our deps and strimming those down rather than tricks to shrink the binary.

**Comment by prydonius** [comment]
Closing as not too relevant/important. We'll soon be moving to a Helm chart based install.
