### ISSUE TITLE
Job pods in failed state after deploying helm chart

### ISSUE THREAD

**Issue by migmartri** [kubeapps/kubeapps#434]
After deploying the kubeapps helm chart, you can see a set of pods triggered by the sync jobs that are in `error` state.

```
apprepo-sync-incubator-6l2f6-b7rq9                          0/1       Error       0          3h        apprepositories.kubeapps.com/repo-name=incubator,controller-uid=18b03ceb-9998-11e8-9ad3-06254f8710a6,job-name=apprepo-sync-incubator-6l2f6
```

Although this does not have any consequence from the functional standpoint so k8s will create another pod and wait to fulfill the job's completion, it does not offer a good user experience.

To me, once of the first things that a user will do after installing the chart is to check that everything is running, and seeing some pods in error state can be confusing.

The error specifically is about not being able to connect to mongoDB due to a deployment race condition. We might be able to solve this by using an init container in the job.pod.spec that waits for mongodb to be accessible. We should set a job deadline to avoid long infinite loops. 

```
time="2018-08-06T16:45:23Z" level=fatal msg="Can't connect to mongoDB: unable to connect to MongoDB"
```

**Comment by prydonius** [comment]
@andresmgot IMO the current behaviour of failing is correct for the `chart-repo` CLI, the orchestration around it should ensure it is restarted until it works. Another way to do this would be to use an initContainer to wait for MongoDB, but IMO the restartPolicy is a neater solution.

**Comment by andresmgot** [comment]
Yes, the restartPolicy is the "k8s way" of doing that. I was just pointing out an alternative in case that gives any trouble.
