### ISSUE TITLE
Deleted applications distinction

### ISSUE THREAD

**Issue by migmartri** [kubeapps/kubeapps#436]
Currently, the Helm proxy returns all the Helm releases including the deleted ones, but from the UI POV there is not a way to distinguish which one is in status `deployed`, `deleted` or `failed`.

We should expose this status information in the API so we can in the UI:

* Show the status in the apps list
* In the future, add a toggle to show `all apps` which includes deleted or failed
* Hide `upgrade` button for non deployed apps
* Hide `delete` button for deleted apps.

**Comment by migmartri** [comment]
The current `deployed` status in the app view is misleading since it marks it as deployed even though the app does not exist and there are not k8s deployments available

```ts
  private isReady() {
    const { deployments } = this.props;
    if (deployments.length > 0) {
      return deployments.every(d => {
        const status: IDeploymentStatus = d.status;
        return status.availableReplicas === status.replicas;
      });
    } else {
      // if there are no deployments, then the app is considered "ready"
      // TODO: this currently does not distinguish between deployments not
      // loaded yet and no deployments
      return true;
    }
  
```

**Comment by prydonius** [comment]
@migmartri R.E. the logic for determining the deployment status, that needs to be improved in general (for example, does not support StatefulSets). What we have today was just a quick solution we developed at a hackathon.

**Comment by arapulido** [comment]
@prydonius I think Migue's issue is related, but different. If you install a chart using the helm CLI, the app appears correctly in the apps view, but if you then delete it using the CLI again, it doesn't disappear from the Apps view.

**Comment by arapulido** [comment]
Only if you --purge your release, if will disappear from the apps view

**Comment by prydonius** [comment]
@arapulido yep I understood the issue, I was just pointing out that that logic needs to be updated in general

**Comment by migmartri** [comment]
I have created an issue to tackle the differences between both approaches https://github.com/kubeapps/kubeapps/issues/481
