### ISSUE TITLE
Developer doc issues

### ISSUE THREAD

**Issue by migmartri** [kubeapps/kubeapps#438]
The running dashboard in development section is outdated by indicating that the deployment to swap is `kubeapps-dashboard-ui` when now it is called `[release-name]-kubeapps-dashboard`

https://github.com/kubeapps/kubeapps/blob/master/docs/developer/dashboard.md#running-the-dashboard-in-development

**Comment by prydonius** [comment]
Right now the developer docs still mention the `kubeapps` CLI for deploying Kubeapps, once we change to the Helm chart all of the documentation will need to be updated to the new references. We'll tackle this as part of #406.
