### ISSUE TITLE
Improve App deployment status

### ISSUE THREAD

**Issue by prydonius** [kubeapps/kubeapps#439]
The current Deployed status in the App View only supports Kubernetes Deployments. We should support all workloads (DaemonSet, StatefulSet, ReplicaSets, ReplicationControllers) and ensure all pods associated with the Helm release are running.

**Comment by arapulido** [comment]
👍 this would be great to have

**Comment by andresmgot** [comment]
Another improvement here: If the application fails to be installed it displays the `failed` tag when listing the apps but it says `Deploying` when clicking in the App details:

<img width="334" alt="screen shot 2018-08-27 at 10 44 48" src="https://user-images.githubusercontent.com/4025665/44650204-3fa2b480-a9e6-11e8-90a2-2e7ce3386075.png">

<img width="1235" alt="screen shot 2018-08-27 at 10 41 45" src="https://user-images.githubusercontent.com/4025665/44650178-2c8fe480-a9e6-11e8-946e-6193d6a7bb26.png">

I'd raise the priority of this issue or maybe tackle this specific bug in a different issue.

**Comment by andresmgot** [comment]
I have created a new document to discuss possible improvements: https://docs.google.com/document/d/1eWvabsnY5tfhGVyV3cDbh_YPrAsnmrn06nWUXjXzke4/
