### ISSUE TITLE
Offline Install: Dashboard not showing running apps and Installed Catalogs

### ISSUE THREAD

**Issue by tomhouweling1987** [kubeapps/kubeapps#4417]
### Description:

When KubeApps is deployed in an Offline environment the dashboard is not showing any running apps in the cluster.

### Steps to reproduce the issue:

1. Setup an internal docker registry with kubeapps images mirrored, [as per the docs](https://github.com/kubeapps/kubeapps/blob/master/docs/user/offline-installation.md#4-install-kubeapps).
2. Download Latest source code (https://github.com/kubeapps/kubeapps/releases/tag/v2.4.3)
3. Deploy KubeApps with helm install

### Describe the results you received:

KubeApps install is fine but it is not showing running apps in the running cluster when show apps in all namespaces is enabled

### Describe the results you expected:

KubeApps showing running apps in all namespaces of the cluster

### Additional information you deem important (e.g. issue happens only occasionally):

Deployed KubeApps in an Online environment with no issues.
In both environments, online and offline, Rancher v2.5.11 is used to manage k8s.

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

- Output of `helm list -n <kubeapps-namespace> <kubeapps-release-name>`:

```
AME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION

kubeapps        kubeapps        1               2022-03-14 15:14:11.7384797 +0100 CET   deployed        kubeapps-7.8.7  2.4.3
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"windows/amd64"}

Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:03:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by absoludity** [comment]
Thanks @tomhouweling1987 .  We'll probably need to take a look and try to reproduce this.

A couple of things that may help though:

> KubeApps install is fine but it is not showing running apps in the running cluster when show apps in all namespaces is enabled

So you're not even seeing Kubeapps itself as an installed application, correct? Can you open the browser debugger's Network tab and look for a request that says "GetInstalledPackageSummaries", click on it so you can see the request headers and take a screenshot for us?

Also, if you can just confirm (even if you can't paste the output), that the output of `helm ls --all-namespaces` shows other helm installs.

Thanks for the extra info.

**Comment by tomhouweling1987** [comment]
Hey @absoludity,

Indeed, i cant see KubeApps itself. But i can confirm that I can see the namespaces. In the app itself I also switch between the namespaces and I can also create new namespaces from the KubeApp itself.
 
Screenhot of GetInstalledPackages:
![screenshot_request_headers](https://user-images.githubusercontent.com/45419572/158566201-820c83a9-a466-4669-97a9-8d3c9e48fc7e.png)

**Comment by absoludity** [comment]
Thanks. So it appears that Kubeapps thinks there are no installed packages (ie. no error, just empty response), which is a little baffling. I don't suppose you've changed the default value of the `packaging` chart option? (just one explanation for that behaviour). You should be able to run something like the following to check:

```
helm -n kubeapps get values kubeapps | grep -A5 packaging
packaging:
  helm:
    enabled: true
```

Also, can you please show the output of `helm ls --all-namespaces`?

**Comment by tomhouweling1987** [comment]
The problem is solved. Don't know what was the specific problem. But when we installed KubeApps with ChartVersion 7.8.10 everything is working again.

**Comment by absoludity** [comment]
Excellent. Re-open if you experience it again and have more info. Thanks for the update!
