### ISSUE TITLE
Invalid GetAvailablePackageSummaries response from the plugin kapp_controller.packages

### ISSUE THREAD

**Issue by cmoulliard** [kubeapps/kubeapps#4485]
### Description:

The carvel packages cannot be displayed using kubeapps v2.4.3 and the following error is reported within the UI

```
An error occurred while fetching the catalog: Invalid GetAvailablePackageSummaries response from the plugin kapp_controller.packages: rpc error: code = NotFound desc = no available packages: <nil>.
```

**Remark**: If I select the namespace `tap-install` where the packageRepository, packages, ... are installed I got another error `An error occurred while fetching the catalog: upstream request timeout. `

### Steps to reproduce the issue:

Instructions followed to install kubeapps on k8S 1.21 where Carvel packages and repository have been deployed
```
helm repo add bitnami https://charts.bitnami.com/bitnami
helm uninstall kubeapps -n kubeapps

cat <<EOF > kubeapps-values.yml
packaging:
  carvel:
    enabled: true
EOF

helm install kubeapps -n kubeapps bitnami/kubeapps -f kubeapps-values.yml
cat <<EOF | kubectl apply -f - 
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: kubeapps-grpc
  namespace: kubeapps
spec:
  virtualhost:
    fqdn: kubeapps.10.0.76.205.nip.io
  routes:
    - conditions:
      - prefix: /apis/
      pathRewritePolicy:
        replacePrefix:
        - replacement: /
      services:
      - name: kubeapps-internal-kubeappsapis
        port: 8080
        protocol: h2c
    - services:
      - name: kubeapps
        port: 80
EOF
kubectl create --namespace default serviceaccount kubeapps-operator
kubectl create clusterrolebinding kubeapps-operator --clusterrole=cluster-admin --serviceaccount=default:kubeapps-operator
kubectl get --namespace default secret $(kubectl get --namespace default serviceaccount kubeapps-operator -o jsonpath='{range .secrets[*]}{.name}{"\n"}{end}' | grep kubeapps-operator-token) -o jsonpath='{.data.token}' -o go-template='{{.data.token | base64decode}}' && echo
```

PackageRepository and PackageMetada have been installed successfully
```
[centos@n121-test ~]$ kc get PackageRepository/tanzu-tap-repository -n tap-install
NAME                   AGE   DESCRIPTION
tanzu-tap-repository   40h   Reconcile succeeded
[centos@n121-test ~]$ kc -n tap-install get PackageMetadata/cnrs.tanzu.vmware.com
NAME                    DISPLAY NAME            CATEGORIES   SHORT DESCRIPTION                                    AGE
cnrs.tanzu.vmware.com   Cloud Native Runtimes                Cloud Native Runtimes is a serverless runtime b...   40h52m53s
```

### Version of Helm, Kubeapps and Kubernetes:

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:16:05Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:10:22Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by absoludity** [comment]
Thanks Charles. Before I go ahead and reproduce in a local environment, can you pls check the following:

> PackageRepository and PackageMetada have been installed successfully
> 
> ```
> [centos@n121-test ~]$ kc get PackageRepository/tanzu-tap-repository -n tap-install
> NAME                   AGE   DESCRIPTION
> tanzu-tap-repository   40h   Reconcile succeeded

So the above shows that a package repository has been added to the `tap-install` namespace, *not* the `kapp-controller-packaging-global` namespace. Unless there's something different in your setup that I'm not aware of, this would normally mean that the packages from that repository are only available in that one namespace (`tap-install`). If you instead add the repo to the global namespace, they should be available in all namespaces (same as on the CLI).

Ah, I see the description updated with:

> **Remark**: If I select the namespace `tap-install` where the packageRepository, packages, ... are installed I got another error `An error occurred while fetching the catalog: upstream request timeout. `

How many packages are in that repo? (`kubectl -n tap-install get packages | wc -l`) We did have an issue #4099 with the response times for this view being unusable in the most recent release, which I investigated and fixed, but unfortunately that fix isn't yet released.

**Comment by cmoulliard** [comment]
Information from the log of the pod `kubeapps-internal-kubeappsapis-5fc8bdf7fc-sc4c9` -->
```
I0323 08:20:57.797868       1 packages.go:58] +core GetAvailablePackageSummaries (cluster="default", namespace="tap-install")
I0323 08:20:57.797910       1 packages.go:79] Items now: 0/100
I0323 08:20:57.797920       1 packages.go:81] Should enter
I0323 08:20:57.797955       1 server.go:200] +helm GetAvailablePackageSummaries (cluster="default", namespace="tap-install")
I0323 08:20:59.354490       1 packages.go:79] Items now: 98/100
I0323 08:20:59.354552       1 packages.go:81] Should enter
I0323 08:20:59.354618       1 server_ctrl_packages.go:35] +kapp-controller GetAvailablePackageSummaries (cluster="default", namespace="tap-install")
I0323 08:21:03.547004       1 request.go:597] Waited for 92.165715ms due to client-side throttling, not priority and fairness, request: GET:https://10.96.0.1:443/apis/source.toolkit.fluxcd.io/v1beta1?timeout=32s
I0323 08:21:08.061139       1 request.go:597] Waited for 900.8094ms due to client-side throttling, not priority and fairness, request: GET:https://10.96.0.1:443/apis/accelerator.apps.tanzu.vmware.com/v1alpha1?timeout=32s
I0323 08:21:17.147911       1 request.go:597] Waited for 93.163293ms due to client-side throttling, not priority and fairness, request: GET:https://10.96.0.1:443/apis/storage.k8s.io/v1beta1?timeout=32s
I0323 08:21:21.649259       1 request.go:597] Waited for 198.47601ms due to client-side throttling, not priority and fairness, request: GET:https://10.96.0.1:443/apis/replication.apiresources.multicluster.x-tanzu.vmware.com/v1alpha1?timeout=32s
I0323 08:21:21.649832       1 request.go:597] Waited for 197.51973ms due to client-side throttling, not priority and fairness, request: GET:https://10.96.0.1:443/apis/kpack.io/v1alpha2?timeout=32s
I0323 08:21:21.650269       1 request.go:597] Waited for 198.01859ms due to client-side throttling, not priority and fairness, request: GET:https://10.96.0.1:443/apis/internal.bindings.labs.vmware.com/v1alpha1?timeout=32s
I0323 08:21:21.650674       1 request.go:597] Waited for 198.420526ms due to client-side throttling, not priority and fairness, request: GET:https://10.96.0.1:443/apis/internal.packaging.carvel.dev/v1alpha1?timeout=32s
I0323 08:21:21.651605       1 request.go:597] Waited for 199.335724ms due to client-side throttling, not priority and fairness, request: GET:https://10.96.0.1:443/apis/kappctrl.k14s.io/v1alpha1?timeout=32s
I0323 08:21:21.652037       1 request.go:597] Waited for 197.997103ms due to client-side throttling, not priority and fairness, request: GET:https://10.96.0.1:443/apis/buildservice.tanzu.vmware.com/v1alpha1?timeout=32s
I0323 08:21:21.652443       1 request.go:597] Waited for 198.36921ms due to client-side throttling, not priority and fairness, request: GET:https://10.96.0.1:443/apis/caching.internal.knative.dev/v1alpha1?timeout=32s
I0323 08:21:21.652938       1 request.go:597] Waited for 198.781016ms due to client-side throttling, not priority and fairness, request: GET:https://10.96.0.1:443/apis/carto.run/v1alpha1?timeout=32s
I0323 08:21:21.653285       1 request.go:597] Waited for 198.200368ms due to client-side throttling, not priority and fairness, request: GET:https://10.96.0.1:443/apis/authentication.k8s.io/v1?timeout=32s
I0323 08:21:21.747245       1 request.go:597] Waited for 198.514013ms due to client-side throttling, not priority and fairness, request: GET:https://10.96.0.1:443/apis/tekton.dev/v1alpha1?timeout=32s
I0323 08:21:21.946965       1 request.go:597] Waited for 491.97602ms due to client-side throttling, not priority and fairness, request: GET:https://10.96.0.1:443/apis/rabbitmq.com/v1beta1?timeout=32s
I0323 08:21:21.947176       1 request.go:597] Waited for 492.213984ms due to client-side throttling, not priority and fairness, request: GET:https://10.96.0.1:443/apis/source.toolkit.fluxcd.io/v1beta1?timeout=32s
I0323 08:21:21.947278       1 request.go:597] Waited for 492.225562ms due to client-side throttling, not priority and fairness, request: GET:https://10.96.0.1:443/apis/sources.tanzu.vmware.com/v1alpha1?timeout=32s
I0323 08:21:21.947529       1 request.go:597] Waited for 492.44859ms due to client-side throttling, not priority and fairness, request: GET:https://10.96.0.1:443/apis/secretgen.carvel.dev/v1alpha1?timeout=32s
I0323 08:21:21.949837       1 request.go:597] Waited for 292.505959ms due to client-side throttling, not priority and fairness, request: GET:https://10.96.0.1:443/apis/servicebinding.io/v1alpha3?timeout=32s
I0323 08:21:22.050768       1 request.go:597] Waited for 595.624189ms due to client-side throttling, not priority and fairness, request: GET:https://10.96.0.1:443/apis/services.apps.tanzu.vmware.com/v1alpha1?timeout=32s
I0323 08:21:22.147432       1 request.go:597] Waited for 595.753868ms due to client-side throttling, not priority and fairness, request: GET:https://10.96.0.1:443/apis/stacks.stacks-operator.tanzu.vmware.com/v1alpha1?timeout=32s
I0323 08:21:22.152718       1 request.go:597] Waited for 595.614222ms due to client-side throttling, not priority and fairness, request: GET:https://10.96.0.1:443/apis/secretgen.k14s.io/v1alpha1?timeout=32s
I0323 08:21:22.248365       1 request.go:597] Waited for 595.754734ms due to client-side throttling, not priority and fairness, request: GET:https://10.96.0.1:443/apis/kpack.io/v1alpha1?timeout=32s
I0323 08:21:22.252882       1 request.go:597] Waited for 595.749033ms due to client-side throttling, not priority and fairness, request: GET:https://10.96.0.1:443/apis/source.apps.tanzu.vmware.com/v1alpha1?timeout=32s
I0323 08:21:22.252939       1 request.go:597] Waited for 595.747916ms due to client-side throttling, not priority and fairness, request: GET:https://10.96.0.1:443/apis/sources.triggermesh.io/v1alpha1?timeout=32s
I0323 08:21:22.253841       1 request.go:597] Waited for 595.752019ms due to client-side throttling, not priority and fairness, request: GET:https://10.96.0.1:443/apis/kubeapps.com/v1alpha1?timeout=32s
I0323 08:21:25.153095       1 server.go:59] NotFound 27.355274768s /kubeappsapis.core.packages.v1alpha1.PackagesService/GetAvailablePackageSummaries
...
```

**Comment by cmoulliard** [comment]
> How many packages are in that repo? (`kubectl -n tap-install get packages | wc -l`)

```
kubectl -n tap-install get packages | wc -l
49
```

**Comment by cmoulliard** [comment]
> that fix isn't yet released.

When is the next release planned ? Is it possible to test the fix using a snapshot kubeapps image ?

**Comment by absoludity** [comment]
Thanks for the log snippet. What this seems to show is (other than debug logs that didn't get removed):

1. You currently are running with both the helm and carvel/kapp-controller support (might be intentional)
2. The kapp-controller plugin is taking way to long to scan the ~50 pkgs, but this is a know issue which was since fixed but not released as above (as per #4099)
3. The core handler (which aggregates results from all enabled plugins, in your case currently both helm and carvel), is returning a NotFound error. It's not clear to me which of the cases you mention in the description this corresponds to. For example, you were originally seeing this when checking another namespace, but the log is for the `tap-install` namespace, and it's taking 25s or so which implies it's doing the slow processing we expect.

What you could try is:

1. Disabling the helm support so we can reduce the noise (`packaging.helm.enabled=false`).
2. If you're keen (and only if you're keen), try using the latest dev image for the kubeappsapis - `docker.io/kubeapps/kubeapps-apis:latest` - which includes the performance fix. This may show us whether the 404 is fixed or still relevant. But only if you're keen.

> When is the next release planned ? Is it possible to test the fix using a snapshot kubeapps image ? @absoludity

Great! You are keen :) So yes, try the latest dev image mentioned above for the kubeappsapis deployment. As for the release, we're just waiting to hear back about an internal issue with the internal testing/publishing of our official chart before starting a new release. I'd estimate in the next week or two.

**Comment by cmoulliard** [comment]
> What you could try is:

I did what you suggested but catalog screen stays empty

![Screenshot 2022-03-24 at 15 49 51](https://user-images.githubusercontent.com/463790/159943366-fc24f29d-a75f-4872-80f4-0c43b601a3f5.png)

**Comment by castelblanque** [comment]
Many thanks Charles. 
I see the screenshot you pasted is from the Repositories list. It is consistent with the current status of Kubeapps: only Helm repositories are shown in UI. For Carvel and Flux, they still need to be managed through CLI. In #3496 we are working on bringing a common API for all, and then making it available through the UI.

From the logs, it seems that only Carvel is enabled, ok:
```bash
PluginDirs:[]string{"/plugins/kapp-controller", "/plugins/resources"}
```

And `GetAvailablePackageSummaries` calls are taking now a really small load time and being OK:

```bash
I0324 14:48:42.657407       1 packages.go:59] +core GetAvailablePackageSummaries (cluster="default", namespace="tap-install")
I0324 14:48:42.657451       1 server.go:59] OK 56.656µs /kubeappsapis.core.packages.v1alpha1.PackagesService/GetAvailablePackageSummaries
```

Strange that there are no packages shown in Catalog.
Could you please paste the Network call to `GetAvailablePackageSummaries` from your browser? I mean from the developer tools.

**Comment by cmoulliard** [comment]
![Screenshot 2022-03-24 at 16 12 37](https://user-images.githubusercontent.com/463790/159948361-b6ec6f15-1539-42da-8e9b-64851f13f58a.png)

**Comment by absoludity** [comment]
> We need something more verbosity here to figure out if `packageMetadata` have been discovered within the namespace selected: https://github.com/kubeapps/kubeapps/blob/main/cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_ctrl_packages.go#L53

You might find there is more verbosity in the actual error returned for the request (check the call to GetAvailablePackageSummaries in the network tab of your browser in the developer tools, as @castelblanque mentioned above). Also, I don't think we error if we don't find any package metadata, but rather would just return an empty list (which is not the case here).

I haven't had a chance to try with the tanzu-tap-repository, but I'm beginning to suspect that what is happening is that the handler is finding the metadata, but then failing to find the related packages and throwing an error. Looking at the code, the only reason I can see that it might do so is if the group-version-resource was different. But pointless to guess, I'll try to setup with the same repo later to test.

**Comment by cmoulliard** [comment]
Here are the CRDs deployed by TAP on k8s and used to document/describe the packages
```
[centos@k121-centos7-tap ~]$ kc api-resources --api-group=packaging.carvel.dev
NAME                  SHORTNAMES   APIVERSION                      NAMESPACED   KIND
packageinstalls       pkgi         packaging.carvel.dev/v1alpha1   true         PackageInstall
packagerepositories   pkgr         packaging.carvel.dev/v1alpha1   true         PackageRepository
[centos@k121-centos7-tap ~]$ kc api-resources --api-group=data.packaging.carvel.dev
NAME               SHORTNAMES   APIVERSION                           NAMESPACED   KIND
packagemetadatas   pkgm         data.packaging.carvel.dev/v1alpha1   true         PackageMetadata
packages           pkg          data.packaging.carvel.dev/v1alpha1   true         Package
```
**FYI**: I created a bash script to install in a VM running K8S, TAP: https://github.com/halkyonio/tap/blob/main/scripts/install.sh

**Comment by absoludity** [comment]
Thanks Charles. I'll try to setup my local dev env with your TAP repos sometime this week to look more closely. In the mean-time, 

> You might find there is more verbosity in the actual error returned for the request (check the call to GetAvailablePackageSummaries in the network tab of your browser in the developer tools, as @castelblanque mentioned above).

**Comment by cmoulliard** [comment]
I reviewed the steps to install kubeapps on TCE (= tanzu community edition) if that helps

```
mkdir _temp && cd _temp
rm -rf $HOME/.local
rm -rf $HOME/.tanzu
!! Download the latest daily build from github README page: https://storage.googleapis.com/tce-cli-plugins-staging/build-daily/2022-03-28/tce-darwin-amd64-v0.12.0-dev.1.tar.gz
wget https://storage.googleapis.com/tce-cli-plugins-staging/build-daily/2022-03-28/tce-linux-amd64-v0.12.0-dev.1.tar.gz
tar -vxf tce-darwin-amd64-v0.12.0-dev.1.tar.gz
tce-linux-amd64-v0.12.0-dev.1/install.sh

VM_IP=65.108.148.216
cat <<EOF > config.yml
ClusterName: toto
KubeconfigPath: ""
ExistingClusterKubeconfig: ""
NodeImage: ""
Provider: kind
ProviderConfiguration:
  rawKindConfig: |
    kind: Cluster
    apiVersion: kind.x-k8s.io/v1alpha4
    nodes:
    - role: control-plane 
      kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true" 
      extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
Cni: calico
CniConfiguration: {}
PodCidr: 10.244.0.0/16
ServiceCidr: 10.96.0.0/16
TkrLocation: projects.registry.vmware.com/tce/tkr:v1.22.5
PortsToForward: []
SkipPreflight: false
ControlPlaneNodeCount: "1"
WorkerNodeCount: "0"
EOF

tanzu uc delete toto
tanzu uc create toto -f config.yml

#tanzu package repository update projects.registry.vmware.com-tce-main-v0.11.0 --url projects.registry.vmware.com/tce/main:v0.11.0-alpha.3568.3 -n tanzu-package-repo-global
#tanzu package available list -A
tanzu package install cert-manager --package-name cert-manager.community.tanzu.vmware.com --version 1.6.1 -n tanzu-package-repo-global --wait=false

cat <<EOF > values-contour.yaml
envoy:
  service:
    type: ClusterIP
  hostPorts:
    enable: true
EOF
tanzu package install contour --package-name contour.community.tanzu.vmware.com --version 1.18.1 -f values-contour.yaml --wait=false


helm repo add bitnami https://charts.bitnami.com/bitnami

cat <<EOF > kubeapps-values.yml
image:
  tag:
packaging:
  carvel:
    enabled: true 
  helm:
    disabled: false  
featureFlags:
  operators: false
EOF

helm uninstall kubeapps -n kubeapps
kubectl create ns kubeapps
helm install kubeapps -n kubeapps bitnami/kubeapps -f kubeapps-values.yml

cat <<EOF | kubectl apply -f -
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: kubeapps-grpc
  namespace: kubeapps
spec:
  virtualhost:
    fqdn: kubeapps.$VM_IP.nip.io
  routes:
    - conditions:
      - prefix: /apis/
      pathRewritePolicy:
        replacePrefix:
        - replacement: /
      services:
      - name: kubeapps-internal-kubeappsapis
        port: 8080
        protocol: h2c
    - services:
      - name: kubeapps
        port: 80
EOF
kubectl create --namespace default serviceaccount kubeapps-operator
kubectl create clusterrolebinding kubeapps-operator --clusterrole=cluster-admin --serviceaccount=default:kubeapps-operator
kubectl create clusterrolebinding kubeapps-operator-cluster-admin --clusterrole=cluster-admin --serviceaccount kubeapps:kubeapps-operator

kubectl get --namespace default secret $(kubectl get --namespace default serviceaccount kubeapps-operator -o jsonpath='{range .secrets[*]}{.name}{"\n"}{end}' | grep kubeapps-operator-token) -o jsonpath='{.data.token}' -o go-template='{{.data.token | base64decode}}' && echo
```

@absoludity

**Comment by absoludity** [comment]
Thanks for the update @cmoulliard : 

> This is really frustrating as we can consult the carvel packages using TCE

Yes, I've run Kubeapps on TCE without issue too. Just to be sure I'm understanding your results though: You see no issue running Kubeapps on TCE and viewing TCE's repository, but it's not clear to me whether if you do then install your TAP repo there, you see the same error (I assume?).

I plan to try on a vanilla kind cluster.

**Comment by absoludity** [comment]
So I just added the TAP repository (1.0.2) directly to my local dev env with:

```
kubectl -n kapp-controller-packaging-global create secret generic tap-registry-creds --from-literal=username="$INSTALL_REGISTRY_USERNAME" --from-literal=password="$INSTALL_REGISTRY_PASSWORD"

cat <<EOF | kubectl apply -f -
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: tap-test
  namespace: kapp-controller-packaging-global
spec:
  syncPeriod: 10m
  fetch:
    imgpkgBundle:
      image: registry.tanzu.vmware.com/tanzu-application-platform/tap-packages:1.0.2
      secretRef:
        name: "tap-registry-creds"
EOF

```

After reconciliation succeeds, I try in Kubeapps to view the catalog, and see a slightly different error than what you saw, but I think it will be for the same or a similar reason:

> An error occurred while fetching the catalog: Invalid GetAvailablePackageSummaries response from the plugin kapp_controller.packages: rpc error: code = Internal desc = unexpected order for kapp-controller packages, expected "cnrs.tanzu.vmware.com", found "cert-manager.tanzu.vmware.com".

This error is highlighting an assertion that our implementation makes, which is that for every `Package`, the associated `PackageMeta` will exist. I added that assertion, but can remove it and ignore packages where this is not true. It appears to be false for the `tap-packages:1.0.2`:

```
$ kubectl get packages | grep contour                      
contour.tanzu.vmware.com.1.18.2+tap.1                       contour.tanzu.vmware.com                              1.18.2+tap.1    16m16s

$ kubectl get packagemetadata | grep contour
$
```

I'm assuming that's not intended? Wondering how the `tanzu` CLI copes with packages that don't have any associated packagemetadata, or is there a step I've missed that causes this situation?

**Comment by cmoulliard** [comment]
> Yes, I've run Kubeapps on TCE without issue too. Just to be sure I'm understanding your results though: You see no issue running Kubeapps on TCE and viewing TCE's repository, but it's not clear to me whether if you do then install your TAP repo there, you see the same error (I assume?).

What I did:
- I deployed TCE 0.11 (last daily build) on k1.21
- I deployed contour, certmanager and kubeapps

What I observe:
- I can see ALL the packages of the "projects.registry.vmware.com-tce-main-v0.11.0" repository under the namespace `default` BUT not the packages of the repository of "tkg-core-repository". See: `http://kubeapps.65.108.148.216.nip.io/#/c/default/ns/projectcontour/catalog`
- I can see 2 packages installed: contour, certmanager under `tanzu-package-repo-global/` namespace. See: `http://kubeapps.65.108.148.216.nip.io/#/c/default/ns/tanzu-package-repo-global/apps?allns=yes. Surprisingly, a CNI package also appears .... 

FYI:
```
[snowdrop@h01-121 ~]$ kc get pkgr -A
NAMESPACE                   NAME                                            AGE   DESCRIPTION
tanzu-package-repo-global   projects.registry.vmware.com-tce-main-v0.11.0   15h   Reconcile succeeded
tkg-system                  tkg-core-repository                             15h   Reconcile succeeded

and

[snowdrop@h01-121 ~]$ kc get pkgm -n tanzu-package-repo-global
NAME                                                  DISPLAY NAME                  CATEGORIES                 SHORT DESCRIPTION                                    AGE
app-toolkit.community.tanzu.vmware.com                App-Toolkit package for TCE   application lifecycle      Kubernetes-native toolkit to support applicatio...   15h43m40s
cartographer.community.tanzu.vmware.com               Cartographer                                             Kubernetes native Supply Chain Choreographer.        15h43m40s
cert-injection-webhook.community.tanzu.vmware.com     cert-injection-webhook                                   The Cert Injection Webhook injects CA certifica...   15h43m40s
cert-manager.community.tanzu.vmware.com               cert-manager                  certificate management     Certificate management                               15h43m40s
contour.community.tanzu.vmware.com                    contour                       ingress                    An ingress controller                                15h43m40s
external-dns.community.tanzu.vmware.com               external-dns                  dns                        This package provides DNS synchronization funct...   15h43m40s
fluent-bit.community.tanzu.vmware.com                 fluent-bit                    logging,observability      Fluent Bit is a fast Log Processor and Forwarder     15h43m39s
fluxcd-source-controller.community.tanzu.vmware.com   Flux Source Controller        gitops                     The source-controller is a Kubernetes operator,...   15h43m39s
gatekeeper.community.tanzu.vmware.com                 gatekeeper                    policy management          policy management                                    15h43m39s
grafana.community.tanzu.vmware.com                    grafana                       monitoring,observability   Visualization and analytics software                 15h43m39s
harbor.community.tanzu.vmware.com                     harbor                        OCI registry               OCI Registry                                         15h43m39s
knative-serving.community.tanzu.vmware.com            knative-serving               serverless                 Knative Serving builds on Kubernetes to support...   15h43m38s
kpack.community.tanzu.vmware.com                      kpack                         build                      kpack builds application source code into OCI c...   15h43m38s
local-path-storage.community.tanzu.vmware.com         local-path-storage            storage                    This package provides local path node storage a...   15h43m40s
multus-cni.community.tanzu.vmware.com                 multus-cni                    networking                 This package provides the ability for enabling ...   15h43m40s
prometheus.community.tanzu.vmware.com                 prometheus                    monitoring,observability   A time series database for your metrics              15h43m40s
velero.community.tanzu.vmware.com                     velero                        backup                     Disaster recovery capabilities                       15h43m40s
whereabouts.community.tanzu.vmware.com                whereabouts                   networking                 A CNI IPAM plugin that assigns IP addresses clu...   15h43m40s
```

**Remark**: I can pass you the TOKEN to access the console if you want @absoludity

**Comment by cmoulliard** [comment]
> I'm assuming that's not intended?

I think that you are right as it is (from what I know) mandatory that we have a PackageMetadata (see by example : https://github.com/vmware-tanzu/community-edition/tree/main/addons/packages/contour).
With the latest repository they released the number of PackageMetadata matches the number of Packages :-) but of course we can have 1 to many packages / packagemetadata.

**Comment by cmoulliard** [comment]
> Wondering how the `tanzu` CLI copes with packages that don't have any associated packagemetadata

According to their code, they check first the PackageMetadata - see [here](https://github.com/vmware-tanzu/tanzu-framework/blob/main/cmd/cli/plugin/package/package_available_list.go#L53-L83)

**Comment by absoludity** [comment]
> > Wondering how the `tanzu` CLI copes with packages that don't have any associated packagemetadata
> 
> According to their code, they check first the PackageMetadata - see [here](https://github.com/vmware-tanzu/tanzu-framework/blob/main/cmd/cli/plugin/package/package_available_list.go#L53-L83)

Right, so they never even find that contour package to include in the list (since there was no package metadata).

> > I'm assuming that's not intended?
> 
> I think that you are right as it is (from what I know) mandatory that we have a PackageMetadata (see by example : https://github.com/vmware-tanzu/community-edition/tree/main/addons/packages/contour).
> 
> With the latest repository they released daily `v0.11.0-alpha.3568.3`, the number of PackageMetadata matches the number of Packages :-) but of course we can have 1 to many packages / packagemetadata.
> 
> ```
> kubectl get packages | grep contour
> contour.community.tanzu.vmware.com.1.18.1                    contour.community.tanzu.vmware.com                    1.18.1     15h53m45s

I think we might have confused repositories here? I have assumed since the start of this issue that the `Invalid GetAvailablePackageSummaries response` error was when running Kubeapps with the `tanzu-tap-repository`, as in the description. That's what I've reproduced above, and that's where I've found the missing `PackageMetadata`. I've not found that issue with the TCE repo, only the TAP one. Is there a new TAP repo I can try instead with the issue fixed?

> contour.community.tanzu.vmware.com.1.19.1                    contour.community.tanzu.vmware.com                    1.19.1     15h53m45s
> contour.community.tanzu.vmware.com.1.20.1                    contour.community.tanzu.vmware.com                    1.20.1     15h53m45s
> 
> kubectl get packagemetadata | grep contour
> contour.community.tanzu.vmware.com                    contour                       ingress                    An ingress controller                                15h53m50s
> ```
> 
> To get the latest repository released and the version, use `crane ls projects.registry.vmware.com/tce/main | grep v0.11 | tail -1`

Right, this is the TCE repository, not the TAP one. To reproduce your original issue, I'm running a cluster with kapp-controller and just the tap rep from registry.tanzu.vmware.com/tanzu-application-platform/tap-packages:1.0.2

Is there a new version of this repository with that issue fixed? I assume that will fix your original problem (but can't be 100% until we try).

**Comment by absoludity** [comment]
> I've not found that issue with the TCE repo, only the TAP one. Is there a new TAP repo I can try instead with the issue fixed?

Or if that is indeed the issue and it's probable that some people will publish invalid repositories occasionally, I might update Kubeapps to similarly ignore packages without metadata.

**Comment by cmoulliard** [comment]
> Is there a new version of this repository with that issue fixed?

I dont think that a new TAP repository has been published since [1.0.2](https://docs.vmware.com/en/Tanzu-Application-Platform/1.0/tap/GUID-install.html#add-package-repositories) AND 
```
crane auth login registry.tanzu.vmware.com -u xxxx -p yyyy
2022/03/29 10:44:04 logged in via /home/snowdrop/.docker/config.json

crane ls registry.tanzu.vmware.com/tanzu-application-platform/tap-packages
1.0.0
1.0.1
1.0.2
sha256-0048f9c4affb582558448be6f0944958faa00eb9fd7172264136e6959db6e773.imgpkg
sha256-01ff1c931b7cb8a0b55694e51932053188a129f67d9fc6d2b68bd4f0afa1bb7f.image-locations.imgpkg
sha256-01ff1c931b7cb8a0b55694e51932053188a129f67d9fc6d2b68bd4f0afa1bb7f.imgpkg
sha256-0386ac7bcaa043e8d310d82427e278a6feacbb9b55950fe66ca8a609c4220b2e.imgpkg
sha256-03a4c5b9921a8c9fd75ae0629bda83fb7052dff88356e76bedf3c90439de0b7b.imgpkg
...
```

**Comment by cmoulliard** [comment]
> Right, this is the TCE repository isn't it? Rather than the TAP one?

Yes this is the TCE and not the TAP repository

**Comment by cmoulliard** [comment]
As the issue reported here will be fixed in a next release of kubeapps (= upstream request time out to fetch the packages), then I will close it and open a new one covering the issue discovered using TAP 1.0.2 repository
