### ISSUE TITLE
kubeapps up or dashboard should wait for KubeApps UI and nginx ingress to be running

### ISSUE THREAD

**Issue by prydonius** [kubeapps/kubeapps#45]
Currently, running `kubeapps dashboard` directly after `kubeapps up` will likely fail as the services haven't started up yet.

Minimally, the Dashboard UI pods and Nginx Ingress pods should be running for the Dashboard to be accessible. The Dashboard UI handles waiting for the API to be ready.

**Comment by ngtuna** [comment]
I would go with `kubeapps up`. The `dashboard` command should be very strait-forward to open the ui without waiting

**Comment by prydonius** [comment]
Closing as not too relevant/important. We'll soon be moving to a Helm chart based install.
