### ISSUE TITLE
Service instances page flashes with incorrect message

### ISSUE THREAD

**Issue by migmartri** [kubeapps/kubeapps#450]
When you enter in the section you get a series of messages, "service catalog not installed, ""broket not installed" and finally `Provision External Services from the Kubernetes Service Catalog`

The UI should not show this  transient state.

![selection_623](https://user-images.githubusercontent.com/24523/43874707-0ec4f402-9b42-11e8-9c67-2a9fe0b83ef0.png)

**Comment by prydonius** [comment]
+1 we should have a Loader that ensures we figure out the state before displaying the message

**Comment by andresmgot** [comment]
This was fixed with #719
