### ISSUE TITLE
[dashboard] Upgrade react-scripts to latest version due to vulnerable dependencies

### ISSUE THREAD

**Issue by castelblanque** [kubeapps/kubeapps#4502]
### Description:

Currently Dashboard is using `react-scripts` v4.0.3.
When running `yarn audit`, 27 vulnerabilities are found:

```
21 vulnerabilities found - Packages audited: 2476
Severity: 2 Low | 10 Moderate | 8 High | 1 Critical
```

19 out of those 21 are related to `react-scripts`.
Some of those vulnerabilities can be found also in [Dependabot's security report here.](https://github.com/kubeapps/kubeapps/security/dependabot)

Upgrading to v5 should fix most of the vulnerabilities, but it will require some work.
This version introduces breaking changes, so source code adaptations are needed too.

Dependency-wise, after upgrading to v5, only 3 vulnerabilities are left as of today. Two of them are related to `swagger-ui-react`.

```
3 vulnerabilities found - Packages audited: 2028
Severity: 1 Moderate | 2 High
```

**Comment by antgamdia** [comment]
Thanks for pointing it out. 
I did try to perform the upgrade, but I encountered some blockers. There are some unresolved upstream issues we are waiting for, as far as I remember. 

See https://github.com/kubeapps/kubeapps/issues/4018

**Comment by castelblanque** [comment]
Ok, previously I made a search for issues but none came up when searching `react-scripts`.
I see in that issue it is only mentioned once, but with a typo: `The main problem is react-scrips`.
That is why I didn't find it hahaha.
Thanks for pointing to the issue!

We might need to raise the priority of this upgrade, as dependencies of 4.x might fall behind.

**Comment by absoludity** [comment]
So let's close this one and raise the priority on the other (let's discuss it in the planning).
