### ISSUE TITLE
Access to a non existing service instance should return 404

### ISSUE THREAD

**Issue by migmartri** [kubeapps/kubeapps#454]
Currently it returns 200 and an empty page.

![selection_631](https://user-images.githubusercontent.com/24523/43875740-83ded402-9b46-11e8-8802-f52cd39f04aa.png)

It seems that it should be handled the same way Helm releases are handled

![selection_632](https://user-images.githubusercontent.com/24523/43875773-b0dca22c-9b46-11e8-8ca9-52c7960f6d43.png)

**Comment by andresmgot** [comment]
Closing this since it's already fixed.
