### ISSUE TITLE
Non-bindable ClusterServiceClass

### ISSUE THREAD

**Issue by migmartri** [kubeapps/kubeapps#456]
I am not able to bind a Mysql instance class in the basic plan, is it possible that the UI let me choose it but it should have not? Is this something that we can detect?

![selection_629](https://user-images.githubusercontent.com/24523/43876825-8a56ce0c-9b4b-11e8-8420-60461f090c1b.png)

**Comment by prydonius** [comment]
I think there is a bindable true/false parameter in the Service Class that we should respect, and disable the "Add Binding" button in this case
