### ISSUE TITLE
How do you generate the api token when running kubectl on Windows?

### ISSUE THREAD

**Issue by natiki** [kubeapps/kubeapps#459]
Hi,

I have MiniKube and KubeCtrl installed on Windows 10. Following the steps from

https://github.com/kubeapps/kubeapps/blob/master/docs/user/getting-started.md#step-2-create-a-kubernetes-api-token

to get the API token it says to do the following:

> kubectl get secret $(kubectl get serviceaccount kubeapps-operator -o jsonpath='{.secrets[].name}') -o jsonpath='{.data.token}' | base64 --decode

However in DOS and PowerShell there is no base64 command. So how do you accomplish this?

**Comment by arapulido** [comment]
You can get the result of the `kubectl` part of the command to a varialbe, and then decode it using the method explained here: https://adsecurity.org/?p=478

**Comment by arapulido** [comment]
@natiki if the method above works for you, it would be great if you could contribute to the docs with a PR with this Windows instructions. Thanks!

**Comment by prydonius** [comment]
Looks like this is a PowerShell command to decode base64:
```
[System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("YmxhaGJsYWg="))
```

We could update the docs to have that

**Comment by natiki** [comment]
Add PR https://github.com/kubeapps/kubeapps/pull/471
