### ISSUE TITLE
Update default makefile target once CLI is deprecated

### ISSUE THREAD

**Issue by migmartri** [kubeapps/kubeapps#461]
Currently, the default make target is the Kubeapps CLI. This is forcing us to have a `all` target to run `make` or `make test` across the rest of the components.

Once the CLI is gone, we might want to deprecate `make all` and use `make` instead for the same purpose.

Additionally, at that point, there will be some cleanup that can be done in the makefile like removing unnecessary targets (i.e static/kubeapps-objs.yaml) or creating single Makefiles per component so a human operator can use pwd change via make. i.e `make -C cmd/chart-repo` instead of relying on our mapping.'

What do you think?

**Comment by andresmgot** [comment]
For me the question is if that we are going to keep including the `kubeapps` binary in future releases. If we don't want to do that yes, we should remove any reference to that.

**Comment by prydonius** [comment]
Let's discuss that on Monday, I'm leaning on removing it in the next release.
