### ISSUE TITLE
Can't install multiple Kubeapps instances via Helm Chart 

### ISSUE THREAD

**Issue by migmartri** [kubeapps/kubeapps#463]
During installation, the Helm chart allows you to select the namespace you want to deploy Kubeapps to, which works fine for the first installation in the cluster but it fails if there is already an existing kubeapps instance installed.

This is because the chart tries to install again cluster-wide resources resulting in for example

```
Error: release kubeapps failed: customresourcedefinitions.apiextensions.k8s.io "apprepositories.kubeapps.com" already exists
```

The same issue applies to cluster-roles.

We should extend our Helm chart to skip these resources if they already exist.

**Comment by arapulido** [comment]
Bumping the priority of this one. I think we should try to fix this as soon as possible.

**Comment by migmartri** [comment]
Hi,

I am not sure about the proposed solution, mainly because I think that it can corrupt other releases(please correct me if I am wrong), what I mean with that is:

- helm install --name foo > Installs the CRD and clusterRoles in the default namespace
- helm install --name bar --set createClusterResources=false --namespace kubeapps > Reuses CRD and cluster roles and installs the rest in the kubeapps namespace 
- helm delete foo -> Deletes foo release including the shared clusterRoles and CRDs, in theory breaking the bar release.

The way I was thinking of tackling this issue was:

### ClusterRoles

Prefix the release name as we do in other resources. We will need to update the RBAC documentation but please note that by default we say helm install -n kubeapps which means that the RBAC documentation should not change by default.  

### CRDs

Rely on the Helm capabilities (Helm 2.2.0+ ~= 2017)  helper which will allow us to wrap our CRDs within: 

```
{{ if not .Capabilities.APIVersions.Has "kubeapps.com/v1alpha1" -}}
```

This solution will not require an extra flag and still will protect operators from affecting other releases.

What do you think?

cc/ @prydonius @andresmgot

**Comment by prydonius** [comment]
FYI I dropped the priority, I don't think this is a critical issue since the `kubeapps` CLI didn't allow you to install multiple instances of Kubeapps either. Feel free to change to back to critical if you disagree, though @arapulido .

**Comment by prydonius** [comment]
Okay I think the best way we can solve this is:

1. Use the [Helm keep annotation](https://github.com/helm/helm/blob/master/docs/charts_tips_and_tricks.md#tell-tiller-not-to-delete-a-resource) to stop Tiller from ever deleting the CRD
2. Update documentation to include deleting the CRD after deleting the Helm chart (if there are no other instances of Kubeapps)
3. Add a post-delete job in the chart to clean up AppRepository CRDs when deleting the chart

**Comment by andresmgot** [comment]
I think that for the cluster roles we can maybe remove them from the chart. Since those are just for people to create some predefined roles we can just document how to create them. That will be a bit more verbose but it can be clarifying (and less magic). It can be confusing to explain in the docs that depending on the release name the clusterrole name may vary. 

Regarding the CRD, I agree with the solution @prydonius suggests (the app repository objects are namespaced, aren't they?)

**Comment by prydonius** [comment]
> I think that for the cluster roles we can maybe remove them from the chart.

What do you think @arapulido @migmartri? We don't really use the ClusterRoles in the UI, and instead suggest specific RBAC roles when a user doesn't have enough permissions, so maybe it makes sense.

> Regarding the CRD, I agree with the solution @prydonius suggests (the app repository objects are namespaced, aren't they?)

Yes, they are namespaced, but there won't be a way for us to distinguish between different releases of Kubeapps in the same namespace. I think we can just add a caveat that separate releases of Kubeapps should be installed into separate namespaces.

**Comment by andresmgot** [comment]
I will remove the `ClusterRoles` then. Please @migmartri @arapulido if you disagree with that let me know.
