### ISSUE TITLE
Charts List view crashes if there are no charts

### ISSUE THREAD

**Issue by prydonius** [kubeapps/kubeapps#470]
If you delete all the chart repos tracked in Kubeapps and then access the Charts page, you get a blank page and the app crashes.

**Comment by anannaya** [comment]
Any update on this issue ?

**Comment by andresmgot** [comment]
@anannaya in the last version of kubeapps you will see a message "No charts found..." instead of a blank page. That's why this issue is closed.

Are you having a different issue with this?
