### ISSUE TITLE
Using helm to delete kubeapps does not appear to work?

### ISSUE THREAD

**Issue by natiki** [kubeapps/kubeapps#474]
Hi,

Apologies if this is a noob (and potentially a helm) question but the docs say to install do the following:

`helm install --name kubeapps --namespace kubeapps bitnami/kubeapps`

and then I am guessing the removal is:

`helm del --purge kubeapps`

However the removal is not removing all traces of kubeapps. I cannot tell if this is related to a helm chart issue, the wrong command issued or something else.

So can you please confirm how we remove kubeapps in its entirety. (Used to be kubeapps.exe down)

**Comment by andresmgot** [comment]
Hi @natiki, as commented in https://github.com/kubeapps/kubeapps/issues/472#issuecomment-412535448 if the initialization job fails to be executed it will not be deleted even after deleting the chart. We will add a hook in the chart to fix that issue but in the meantime you can delete any remaining object executing `kubectl delete ns kubeapps`.

**Comment by natiki** [comment]
Closing this as it is indirectly dealt with in #472
