### ISSUE TITLE
Tag Service Catalog as Beta

### ISSUE THREAD

**Issue by arapulido** [kubeapps/kubeapps#475]
We should mark the Service Catalog feature in the app as beta or preview in order to indicate the instability issues and that it is not up to par with other features in Kubeapps.

**Comment by andresmgot** [comment]
@arapulido @migmartri @prydonius Should we show a small warning message in the view? Something like:

<img width="982" alt="screen shot 2018-08-20 at 15 17 23" src="https://user-images.githubusercontent.com/4025665/44342808-6b74e600-a48c-11e8-8061-78c4c253e028.png">
