### ISSUE TITLE
Create a plan to refactor Service Catalog integration

### ISSUE THREAD

**Issue by arapulido** [kubeapps/kubeapps#476]
Draw up a list the things that need to be refactored and improved with the Service Catalog integration, so we can plan the work accordingly.

**Comment by prydonius** [comment]
I've put together a draft list of the issues we should tackle here: https://docs.google.com/document/d/1MeTrtaRnMjqMKtjIyxeWILDzUwUo1wPpxmqA4Xx7dWs/edit#heading=h.q1crzxcxrjat

**Comment by migmartri** [comment]
Thanks @prydonius it looks good!

Some comments:

I can see a mix of bug fixes (i.e page flashing), refactoring (files layout) and even new features (watch services). It might be worth tagging those entries that way.

Also, It might be useful to attach to every one of the items a priority in the context of the whole service catalog refactoring/improvement? 

Doing these two things will help later on with the extrapolation of the info to their respective issues. WDYT?

**Comment by prydonius** [comment]
@migmartri I have updated the document to categorise the items and set a priority for each one. Thanks for the feedback, PTAL!

**Comment by migmartri** [comment]
> @migmartri I have updated the document to categorise the items and set a priority for each one. Thanks for the feedback, PTAL!

This is great, thank you very much!

**Comment by andresmgot** [comment]
Thanks @prydonius. I just added a couple of small comments. Apart from that, do you think we should add a task to validate that the current approach work with different cloud providers (not only Azure)?

**Comment by arapulido** [comment]
Thanks @prydonius ! I was wondering if we should add something around re-designing / improving how you use the bindings from the edit values view? Right now it is a bit weird to have to copy and paste

**Comment by prydonius** [comment]
@andresmgot not seeing the comments you added, unless it was just adding the priorities to the titles? About testing with different cloud providers, we have tested it with the GCP broker before, and there is an open issue to test it with the automation broker #338 - I think it will be good to go back and test each broker again as there were issues before with the GCP broker (although I think we determined that they were issues with the broker and not specifically Kubeapps). I'll add something to the list!

@arapulido good point, I will add something about that also!

**Comment by obeyler** [comment]
> Thanks @prydonius. I just added a couple of small comments. Apart from that, do you think we should add a task to validate that the current approach work with different cloud providers (not only Azure)?

I could be great to find an full example of integration with kubeDb (I'm not using azure ;-) )

**Comment by prydonius** [comment]
@obeyler thanks for the feedback, looks like KubeDB doesn't use the Service Catalog API and is instead is using the Operator model: https://kubedb.com/docs/0.8.0/guides/elasticsearch/quickstart/quickstart/. It could be pretty interesting to integrate with KubeDB though, as it serves a similar usecase. Just created #647 to address that!

**Comment by prydonius** [comment]
Added two new items to the list in the improvements section:

- [[P2] Validate/test integration against different Service Brokers](https://docs.google.com/document/d/1MeTrtaRnMjqMKtjIyxeWILDzUwUo1wPpxmqA4Xx7dWs/edit?ts=5ba92cd9#heading=h.x4u7oy6dslue)
- [[P2] Rethink UX around consuming Service Bindings when deploying apps](https://docs.google.com/document/d/1MeTrtaRnMjqMKtjIyxeWILDzUwUo1wPpxmqA4Xx7dWs/edit?ts=5ba92cd9#heading=h.1q21jtrr0gr)

please take another look! What's the next step for this, should we create issues for each of these and add them to the board?

**Comment by andresmgot** [comment]
LGTM. Yes, we will need issues for those items with the proper priority.

**Comment by prydonius** [comment]
Issues have now been created for all of these and added to the roadmap with needs-triage. We can go over these during the triaging fest and assign appropriate priorities based on the priorities in the doc. Closing this for now.
