### ISSUE TITLE
Error while deploying Kubeapps chart in non-rbac clusters

### ISSUE THREAD

**Issue by migmartri** [kubeapps/kubeapps#480]
Error: release kubeapps failed: clusterroles.rbac.authorization.k8s.io "kubeapps-apprepository-controller" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["cronjobs"], APIGroups:["batch"], Verbs:["get"]} PolicyRule{Resources:["cronjobs"], APIGroups:["batch"], Verbs:["list"]} PolicyRule{Resources:["cronjobs"], APIGroups:["batch"], Verbs:["watch"]}] user=&{system:serviceaccount:kube-system:tiller 171064b4-741d-11e8-9944-0a58ac1f0e8f [system:serviceaccounts system:serviceaccounts:kube-system system:authenticated] map[]} ownerrules=[] ruleResolutionErrors=[clusterroles.rbac.authorization.k8s.io "cluster-admin" not found]

**Comment by prydonius** [comment]
Reproduced on an AKS cluster with RBAC disabled:

```
Error: release steely-albatross failed: clusterroles.rbac.authorization.k8s.io "steely-albatross-kubeapps-apprepository-controller" is forbidden: attempt to grant extra privileges: [{[get] [batch] [cronjobs] [] []} {[list] [batch] [cronjobs] [] []} {[watch] [batch] [cronjobs] [] []}] user=&{system:serviceaccount:kube-system:default 63e12d0a-9f47-11e8-bb6c-d6e551b314a5 [system:serviceaccounts system:serviceaccounts:kube-system system:authenticated] map[]} ownerrules=[] ruleResolutionErrors=[]
```

**Comment by prydonius** [comment]
Found the same issue on GKE with legacy authorization enabled:

```
Error: release errant-puffin failed: clusterroles.rbac.authorization.k8s.io "errant-puffin-kubeapps-apprepository-controller" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["cronjobs"], APIGroups:["batch"], Verbs:["get"]} PolicyRule{Resources:["cronjobs"], APIGroups:["batch"], Verbs:["list"]} PolicyRule{Resources:["cronjobs"], APIGroups:["batch"], Verbs:["watch"]}] user=&{system:serviceaccount:kube-system:default 0ee8efce-9f4b-11e8-8423-42010a800088 [system:serviceaccounts system:serviceaccounts:kube-system system:authenticated] map[]} ownerrules=[PolicyRule{Resources:["selfsubjectaccessreviews" "selfsubjectrulesreviews"], APIGroups:["authorization.k8s.io"], Verbs:["create"]} PolicyRule{NonResourceURLs:["/api" "/api/*" "/apis" "/apis/*" "/healthz" "/swagger-2.0.0.pb-v1" "/swagger.json" "/swaggerapi" "/swaggerapi/*" "/version"], Verbs:["get"]}] ruleResolutionErrors=[]
```

It appears that if RBAC is disabled (whatever that means, the APIs are still there but it seems it's read-only by serviceaccounts), Tiller is unable to create/update ClusterRoles.

I checked the stable/nginx-ingress and it has an `rbac.enabled` flag which is `true` by default. When set to `false`, I'm able to install the chart successfully, but get a similar error when using the default `true` value. We should add the same option to the Kubeapps chart to fix this. See https://github.com/helm/helm/blob/master/docs/chart_best_practices/rbac.md for the community charts' best practices on RBAC in charts.

**Comment by migmartri** [comment]
Working on it :100: !
