### ISSUE TITLE
Honor Helm CLI behavior in the UI

### ISSUE THREAD

**Issue by migmartri** [kubeapps/kubeapps#481]
Currently, Kubeapps behaves in a different way compared to the Helm CLI itself in the following

 ### Listing charts

Helm lists by default only FAILED and DEPLOYED releases, Kubeapps list them all.

### Delete releases

Helm soft-deletes by default, Kubeapps purge them

We should probably honor the Helm behavior by 

* List by default the same way the CLI does, adding a "show all" filter in the listing
* Soft delete by default but add a checkbox in the confirm dialog to purge the release.

**Comment by andresmgot** [comment]
Do we really want to do that? When listing applications it's useful to see all the applications even the ones that are deleted. If someone tries to reuse a name (because it has been deleted) and it's not listed anywhere it will be confusing.

The same applies to deleting a release, I think it's more common for people to want to delete+purge a release than just delete them. I am okay if we have a field to avoid purging the release though.

**Comment by migmartri** [comment]
Thanks for the comment @andresmgot. You raise a good question. I do not know if we want to. I would be in favor of doing it but before some clarifications.

* I am not advocating for never showing deleted apps but changing the default view instead.
* Listing the deleted and failed apps should be accessible easily by toggling a filter.
* The purge functionality will be still there.

Knowing that, this is why I think we should change it.

- I would not be surprised that most Helm users don't know what delete actually means (from the implementation standpoint), they just see it disappear from the `helm list` command. And this works fine because Helm relies on autogenerated release names by default, so conflicts are prevented. This also means that potentially there will be many of these deleted releases already there (I leave them behind all the time).

- Helm deletion, by default, does not remove the configmap releases, so even in small installations the list shown in kubeapps can be, in my opinion, overwhelming and confusing.

- When we used Helm CRD we had our own reality of chart releases and our deletion by default purged, so technically this discussion did not apply by then. Now, we should assume that Kubeapps can be connected to their existing Tiller, which potentially will have deleted releases CM stored. I would expect as an user to see what I see in Helm list by default.

- I do not think that we should optimize the dashboard for the cluster operator but for the end user instead. Sure, a cluster operator might want to see by default the deleted releases to clean them up, audit them and so on, but as an end user you might just care about the apps that are deployed.
 
> If someone tries to reuse a name (because it has been deleted) and it's not listed anywhere it will be confusing.

I agree, but that's how Helm work. And to be clear, we will still list the deleted apps, we can even add a link to them or redirect (since we will not change the proxy response). So there will be a escape hatch to purge the release (toggle the filter and purge or use the CLI as expected).

I see an issue though, and is that we force the user to add a release name instead of making it optional and relying on release name generation. This might mean that we are going to have more name conflicts than the CLI.

> I think it's more common for people to want to delete+purge a release than just delete them.

Maybe, I am assuming that there are good reasons for which the Helm team decided not to purge by default, auditing and un-delete (helm rollback), so at first I'd prefer to stick to their behavior for predictability sake.

This is my opinion, but definitely more input is needed.

**Comment by prydonius** [comment]
My 2 cents:

I agree with @migmartri that the default behaviour should be that deleted apps are hidden. I think failed and succeeded apps should be shown, following Helm list's behaviour. We should add a filter/toggle in the AppList page to show deleted apps.

> we can even add a link to them or redirect (since we will not change the proxy response). So there will be a escape hatch to purge the release (toggle the filter and purge or use the CLI as expected).

Regardless of whether the proxy or the dashboard filters the releases (IMO it should be the proxy), we should be able to discover the conflict and show an appropriate message. I agree that linking to the release so it can be deleted is a good measure.

**Comment by arapulido** [comment]
@andresmgot can we close this now?

**Comment by andresmgot** [comment]
yep
