### ISSUE TITLE
Apply changes in upstream chart

### ISSUE THREAD

**Issue by migmartri** [kubeapps/kubeapps#482]
There are some changes in the chart upstream that will need to be down-streamed here 

https://github.com/bitnami/charts/pull/752#pullrequestreview-146159435

**Comment by prydonius** [comment]
Reopening as https://github.com/bitnami/charts/pull/752 requires changes, we should update the chart here again once that is merged.

**Comment by migmartri** [comment]
@prydonius it seems that this was actually finished here https://github.com/kubeapps/kubeapps/commit/047ab654a6842047a4f314c7b0b201d922f7146d

Can we close it?
