### ISSUE TITLE
Auto generate release name

### ISSUE THREAD

**Issue by migmartri** [kubeapps/kubeapps#485]
Currently, during chart deployment, we enforce the user to provide a release name. Release name which is optional in the Helm CLI.

![selection_644](https://user-images.githubusercontent.com/24523/44121166-d4352aaa-9fd3-11e8-9489-fb7a8440ad3e.png)

We might want to look into a way to auto-generate a release name if not provide.

Auto-generating a release name has the benefit of helping to avoid name collisions with existing charts now that we share Tiller, more so if we end up enabling deletion (not purge) by default. https://github.com/kubeapps/kubeapps/issues/481

From top of my head I can see two ways to implement this:

1 - Rely on Tiller release name generation

This will require us to make the field optional and let Tiller handle the name generation. We would need to do some tweaks in the UX to make it friendly enough (i.e field placeholder)

2 - Have our own generator

This has the benefit of being backend agnostic, if we support another backend that it's not tiller, we can still rely on this mechanism.

It also seems to have some benefits from the UX perspective since the user can tweak that value and see it in advance.

In term of effort, option 1 seems easier than option 2.

**Comment by prydonius** [comment]
We actually have the capability currently to generate a name, we use the `moniker-native` module in the Function deployment view to do so: https://github.com/kubeapps/kubeapps/blob/a2f5dd4d1bbefc76e4d113babd8d4a2c6609c341/dashboard/src/components/FunctionList/FunctionDeployButton.tsx#L55

So we should be able to easily implement option 2 using the same module, also I like that this method doesn't rely on Tiller directly (e.g. if we change the way tiller proxy works, or support a different deployment tool in the future). Also, +1 for the UX benefit of being able to see the name and tweak before deploying.

**Comment by andresmgot** [comment]
Agree, my +1 to option 2.
