### ISSUE TITLE
Ensure bitnami charts repo is fixed before releasing Kubeapps with the repo

### ISSUE THREAD

**Issue by prydonius** [kubeapps/kubeapps#486]
We came across a pretty serious issue in the bitnami charts repo (https://github.com/bitnami/charts/issues/753) that currently renders some charts broken. We should ensure this gets fixed before the next release of Kubeapps goes out with the change from #465. This issue serves as a reminder to check that this is fixed before we release.

**Comment by arapulido** [comment]
@prydonius I think we can close this one now?

**Comment by prydonius** [comment]
@arapulido yes, thanks!
