### ISSUE TITLE
Unauthorised requests when navigating the dashboard....

### ISSUE THREAD

**Issue by natiki** [kubeapps/kubeapps#490]
![image](https://user-images.githubusercontent.com/4738140/44146282-46f91aa2-a0d2-11e8-9619-8765319e7ebc.png)

![image](https://user-images.githubusercontent.com/4738140/44146300-5902cb26-a0d2-11e8-8b10-ba57019e32f3.png)

![image](https://user-images.githubusercontent.com/4738140/44146353-7ca02074-a0d2-11e8-88f1-f1611a4c2770.png)

**Comment by prydonius** [comment]
closing in favour of #472, feel free to reopen if this is a different issue!
