### ISSUE TITLE
Update generic error message to describe how to see kubeapps components status

### ISSUE THREAD

**Issue by andresmgot** [kubeapps/kubeapps#494]
When the dashboard receives a 500 error it tells the user to check the pods with that label. When installing Kubeapps with the chart that tag is missing so the command suggested returns an empty list. We should either change that message or add the label to the resources we deploy.

**Comment by andresmgot** [comment]
>  even better link people to the AppView page for the Kubeapps release

That may be a bit difficult: We either hardcode the path (which may be wrong if the user doesn't install it with the default name or namespace) or we need to discover the application which would require async calls and filtering for an error message. Also I prefer executing `helm status ...` because it also shows the app pods (so you can see if some pod is crashing, pending...).

**Comment by prydonius** [comment]
Also, it might be the AppView page that is actually broken ;)
