### ISSUE TITLE
Migrate to circle-ci 2.0

### ISSUE THREAD

**Issue by migmartri** [kubeapps/kubeapps#497]
Circle CI outputs the following message

> This project is currently running on CircleCI 1.0 which will no longer be supported after August 31, 2018. Please start migrating this project to CircleCI 2.0.

https://circleci.com/gh/kubeapps/kubeapps/37?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by migmartri** [comment]
Actually, it seems that the message is misleading and went away.

**Comment by migmartri** [comment]
Well, the behavior is strange.

![selection_652](https://user-images.githubusercontent.com/24523/44223076-6a198580-a13b-11e8-8dcb-485006802257.png)

**Comment by prydonius** [comment]
Seems like there was a previous configuration using 1.0
