### ISSUE TITLE
kubeapps-up is installing a fixed mongodb password (!!)

### ISSUE THREAD

**Issue by anguslees** [kubeapps/kubeapps#50]
kubeapps is installing a fixed mongodb user/root password of "23gyfwefhg928" - which is obviously unacceptable.

The password must be dynamically generated on first install (or some similar approach).

**Comment by arapulido** [comment]
Assigning Tuna to this one

**Comment by vtuson** [comment]
I am not sure how worry we are about entropy but here is a basic function I used before in go:
https://play.golang.org/p/_KTS2frMKy

**Comment by anguslees** [comment]
@vtuson: There are two random number generators in golang, and the one you're using there is the pseudo-random *non-cryptographic* one.

For generating auth tokens (like mongodb passwords), we should use the secure one: `crypto/rand.Reader`

**Comment by vtuson** [comment]
Great, thanks!

**Comment by ngtuna** [comment]
closed via PR #51
