### ISSUE TITLE
Add /healthz endpoints in our services and use them as k8s probes 

### ISSUE THREAD

**Issue by migmartri** [kubeapps/kubeapps#502]
It seems that our chart does not include `probes` for some of our services, i.e tiller-proxy or chart-svc.

We could potentially standardize on the addition of a `/healthz` endpoint in those services than then could be hit by the helm chart tests if needed. 

This issue is about reviewing that all our services have a health/status page and probes are correctly set.

**Comment by arapulido** [comment]
Won't fix
