### ISSUE TITLE
Speed up image builds

### ISSUE THREAD

**Issue by andresmgot** [kubeapps/kubeapps#522]
The current (default) Makefile tasks for building the images that Kubeapps is composed of (based on Go) have a couple of points of improvement regarding performance:

 - It builds the image from the root directory. This causes that Docker copies the whole repository to the docker environment.
 - The Dockerfiles copies the whole root directory to the GOPATH inside the container.
 - The compilation takes place within the container. If Docker is virtualized in the host running the build the CPU will be limited to the CPU of the virtual machine.

As an alternative we can compile the binary in the host machine and just copy the binary to the container (the tiller-proxy image uses this approach). The result is significantly faster in the CI (1min vs 2min) and way faster in a local environment (for a rebuild 8s vs 2min).

**Comment by prydonius** [comment]
Thanks for creating this @andresmgot!

> It builds the image from the root directory. This causes that Docker copies the whole repository to the docker environment.
>The Dockerfiles copies the whole root directory to the GOPATH inside the container.

We should probably build the binary into a rootfs/ directory and then just use that for the context

> As an alternative we can compile the binary in the host machine and just copy the binary to the container (the tiller-proxy image uses this approach). 

+1, cross-compiling is pretty easy so I don't think there's any reason we need to build inside the container. We will also need to run `dep ensure` before the build - I'm not sure if that should be part of the make task?

**Comment by andresmgot** [comment]
> We will also need to run `dep ensure` before the build - I'm not sure if that should be part of the make task?

`dep ensure` is a quite expensive command. I'd take another 2min just to do a no-op if everything is updated. I would avoid that unless there is a major reason.

**Comment by prydonius** [comment]
@andresmgot so we should only run `dep ensure` manually when dependencies change? I guess that makes sense since they'll be vendored in. Developers will just have to make sure to run that when changing deps.

**Comment by andresmgot** [comment]
Yes, that's correct.

**Comment by prydonius** [comment]
@andresmgot okay, makes sense, thanks!
