### ISSUE TITLE
Improve API error handling

### ISSUE THREAD

**Issue by migmartri** [kubeapps/kubeapps#546]
For example, if tiller-proxy is down we get stuck in a "loading" state.

We should show a message and maybe encourage people to open an issue in GH.

![selection_661](https://user-images.githubusercontent.com/24523/44600298-b729d700-a78d-11e8-8629-8e5d4074fd63.png)

**Comment by prydonius** [comment]
Hmm, yeah the "Sorry! Something went wrong" message should be shown here. Seems like a regression?

**Comment by migmartri** [comment]
FWIW. React 16 added the error boundary functionality that we might be able to use for generic not handled errors https://reactjs.org/docs/error-boundaries.html

**Comment by prydonius** [comment]
@migmartri I tested that before and it only worked on uncaught errors in render, and won't catch errors that happen out of band (e.g. thunk, componentDidMount)
