### ISSUE TITLE
Chart documentation should have a table with options and default values

### ISSUE THREAD

**Issue by arapulido** [kubeapps/kubeapps#555]
Following best practices, our chart README.md should have a table with the different options and default values.

**Comment by prydonius** [comment]
I started doing it initially, but it quickly became a bit insane to enumerate every value (especially when a lot of them are the same, e.g. each `image` object). Is there any particular reason you think this is useful?

**Comment by arapulido** [comment]
This needs further discussion

**Comment by arapulido** [comment]
Won't fix
