### ISSUE TITLE
Bitnami repo is not installed by default

### ISSUE THREAD

**Issue by arapulido** [kubeapps/kubeapps#556]
I just deployed Kubeapps using the latest chart and the Bitnami repo is not deployed by default, although it is on the list of initial repos in the values.yaml (https://github.com/bitnami/charts/blob/master/bitnami/kubeapps/values.yaml#L26).

Are we ignoring that value?

Logs for the apprepo controller:

```
I0829 13:16:37.529262       1 controller.go:234] Successfully synced 'kubeapps/incubator'
I0829 13:16:37.532813       1 event.go:218] Event(v1.ObjectReference{Kind:"AppRepository", Namespace:"kubeapps", Name:"incubator", UID:"c25a32e1-ab8d-11e8-92dc-08002778810c", APIVersion:"kubeapps.com", ResourceVersion:"5200", FieldPath:""}): type: 'Normal' reason: 'Synced' AppRepository synced successfully
I0829 13:16:37.574066       1 event.go:218] Event(v1.ObjectReference{Kind:"AppRepository", Namespace:"kubeapps", Name:"stable", UID:"c256901f-ab8d-11e8-92dc-08002778810c", APIVersion:"kubeapps.com", ResourceVersion:"5199", FieldPath:""}): type: 'Normal' reason: 'Synced' AppRepository synced successfully
I0829 13:16:37.574123       1 controller.go:234] Successfully synced 'kubeapps/stable'
I0829 13:16:37.585678       1 controller.go:234] Successfully synced 'kubeapps/svc-cat'
I0829 13:16:37.585704       1 event.go:218] Event(v1.ObjectReference{Kind:"AppRepository", Namespace:"kubeapps", Name:"svc-cat", UID:"c25e574e-ab8d-11e8-92dc-08002778810c", APIVersion:"kubeapps.com", ResourceVersion:"5203", FieldPath:""}): type: 'Normal' reason: 'Synced' AppRepository synced successfully
```

**Comment by arapulido** [comment]
Weirdly, if I deploy using the local chart (instead of the one at charts.bitnami.com/bitnami) it gets the bitnami repo. @prydonius any ideas?

**Comment by andresmgot** [comment]
Is the CR deployed? (`kubectl get apprepositories  -n kubeapps` should return the bitnami one).
Also, is the job there, and in that case, did it success? (`kubectl get jobs -n kubeapps` should show `apprepo-sync-bitnami-*`).

**Comment by prydonius** [comment]
I can't reproduce this @arapulido, are you upgrading from a previous Helm release? The bootstrap job will only run on post-install so it needs to be a fresh install.

**Comment by arapulido** [comment]
Weird, I cannot reproduce this anymore. It is weird because I was convinced it was a new deployment.
