### ISSUE TITLE
Create a high order component wrapping the authenticated components

### ISSUE THREAD

**Issue by migmartri** [kubeapps/kubeapps#560]
As discussed here https://github.com/kubeapps/kubeapps/issues/294#issuecomment-416692088 we should follow up the authentication handling in the frontend by wrapping the routes/containers that needs to be authenticated.

For more information about this component and previous efforts in that front refer to   https://github.com/kubeapps/kubeapps/issues/294#issuecomment-416692088

**Comment by absoludity** [comment]
This was done with the `PrivateRoutesContainer`
