### ISSUE TITLE
Error deploying an app if `all namespaces` is selected

### ISSUE THREAD

**Issue by migmartri** [kubeapps/kubeapps#566]
Once you select all namespaces in the UI and click on deploy an app. An error is raised because the namespace is invalid.

![selection_669](https://user-images.githubusercontent.com/24523/44881379-36268000-ac64-11e8-983a-3ac7e2b25715.png)

We need to figure out a way to get user input about in which namespace she wants to deploy the app.

**Comment by prydonius** [comment]
Perhaps the simplest thing to do for now would be to switch the default namespace when going to a deployment view if namespace === "_all". @migmartri do you want to fix this this iteration, just wondering why you added the important-soon priority?

**Comment by migmartri** [comment]
I think that we should fix it soon but it does not mean to be done this iteration. I am still confused with those priority labels. To me important-soon does not seem to convey this iteration and important-long-term feels like it pretty much never will be done :)

Will update the tag

**Comment by migmartri** [comment]
I personally would like to be able to choose the namespace during deployment, which means that we would 1: Make choosing a namespace required, 2: When in a namespace, this value will be selected, 3: When you are in all-namespaces this value is blank and needs to be set.

That said, I think that the approach has the drawback that it can be confusing that you have one namespace selected at the top and another one in the form. So for now I think that It would be better to just do what @prydonius suggested.
