### ISSUE TITLE
Add a TLS certificate for the Tiller proxy in our e2e scenario

### ISSUE THREAD

**Issue by andresmgot** [kubeapps/kubeapps#573]
We would need a test to ensure that we don't break #569 

We can generate a dummy certificate on the fly in our e2e test and simulate a scenario closer to production. We should probably also scope the tiller-proxy role to be able to read just the needed secrets.

**Comment by andresmgot** [comment]
Yes, the PR fixes both things. Thanks for the clarification.

**Comment by prydonius** [comment]
Actually it was already working, the TLS certificate is mounted into the Pod so an RBAC role is not required for that to work.

**Comment by arapulido** [comment]
Done!
