### ISSUE TITLE
[Feature Request] Ability to filter charts by repository....

### ISSUE THREAD

**Issue by natiki** [kubeapps/kubeapps#580]
Hi,

On the charts page it would be great to be able to filter to only include charts from certain repositories.

![image](https://user-images.githubusercontent.com/4738140/44942650-35275700-adfa-11e8-90e3-3daab363689d.png)

So for instance I would probably have this set up to exclude all incubator charts.

**Comment by andresmgot** [comment]
That's possible if you navigate to navigate to `http://localhost:8080/charts/stable` but I think we should navigate to that URL if the user clicks on the repo tag in the chart card. What do you think?

Also @natiki if you are not interested in `incubator` charts you can delete the repo clicking on `Configuration > App Repositories`.

**Comment by natiki** [comment]
@andresmgot I would think it would be more intuitive if we had at the top of the screen something like:

All | Incubator | Stable | .... 

By default all is depressed. And when you type to search you get everything. Selecting one of the others gets you only in that repo etc. Ctrl+Click would be multiple etc.

Also I would rather not delete the repo but disable it. Means I can reactivate it later when I want it instead of having to look up the url again.

**Comment by prydonius** [comment]
+1, this page should have the ability to filter by repo

**Comment by andresmgot** [comment]
Let's rise the priority of this. This get worse when adding more repositories like the bitnami or the jfrog ones:

![screen shot 2018-09-18 at 13 22 27](https://user-images.githubusercontent.com/4025665/45684887-fdcddf80-bb47-11e8-80ef-35d0788a3d62.png)

**Comment by migmartri** [comment]
The scope for now is allowing the user to go to the repo list by clicking on the repo name label.
