### ISSUE TITLE
Doing initial svc-catalog install seems to throw a heap of 404's under the skin....

### ISSUE THREAD

**Issue by natiki** [kubeapps/kubeapps#581]
![image](https://user-images.githubusercontent.com/4738140/44942818-55a4e080-adfd-11e8-84e4-f00e68346cac.png)

**Comment by prydonius** [comment]
This can certainly be improved, but I believe this is expected and just the way we're checking to see if the service catalog is installed right now. We should tackle this as part of the plan for #476.

**Comment by natiki** [comment]
Happy if you want to close this and track all via #476

**Comment by prydonius** [comment]
Thanks @natiki!
