### ISSUE TITLE
[Feature request] Show on installed chart if a new chart version exist in repo

### ISSUE THREAD

**Issue by obeyler** [kubeapps/kubeapps#588]
As since few days I cannot deploy the last kubeapps I don't know if this feature is present or not :-)

It may be a good idea to show to the operator that some deployed chart can or need to be updated.
either by a cartrige with a different color ( the color can change in function of the number of new release of the chart)
or juste by adding a logo on the cartrige . Need Upgrade in this case if the user click on it the Upgrade will be proposed and done if user agrees

**Comment by prydonius** [comment]
Definitely agree that this would be a great feature to have!

**Comment by andresmgot** [comment]
I've gathered some quick notes about this:

https://docs.google.com/document/d/1oG9nerd5CurWSIwH33kKCsOCtkSFMgcm8SuTJyuSnxs/

@prydonius @migmartri please take a look and add your thoughts if you have a different proposal.

**Comment by prydonius** [comment]
@andresmgot can you open comment access to that doc? I think we can have it public for comments only.
