### ISSUE TITLE
Revisit development environments

### ISSUE THREAD

**Issue by prydonius** [kubeapps/kubeapps#589]
Carrying on from https://github.com/kubeapps/kubeapps/pull/583, we should revisit the developer experience of the different components we have in Kubeapps.

- API servers (chartsvc, tiller-proxy)
  - We should use a live-reload utility (e.g. https://github.com/codegangsta/gin) within a development container and run telepresence using the container method to replace the instance in the cluster. This would provide a similar experience to running the Dashboard today.
- Controllers (apprepository-controller)
  - Currently we recommend scaling the controller in the cluster down to 0, and building and running the controller directly on the local machine pointing to the kubeconfig. Telepresence is not that useful here because we would need to use the `$TELEPRESENCE_ROOT` env var in the code to find the kubeconfig, so we might just want to keep this as-is if we don't find a better solution for controllers.
- Background job tooling (chart-repo)
  - Currently we recommend running a Telepresence shell to get DNS access to MongoDB and running chart-repo on the local machine to test with. We should look into using the container method for Telepresence here. There is also no good way to test how this will be run with apprepository-controller without pushing the image and running an instance of apprepository-controller that uses it.
- Dashboard
  - We currently run this under Telepresence, but should look into using the container method.

**Comment by andresmgot** [comment]
BTW tiller-proxy as the apprepository-controller requires to access the K8s API so telepresence is not the best option today.

**Comment by prydonius** [comment]
@andresmgot ah, good point... we may want to consider building the `$TELEPRESENCE_ROOT` env var in. This actually gives us an advantage over the local kubeconfig since we can use ServiceAccounts and play around with RBAC.
