### ISSUE TITLE
Show deleted apps filter should be shown even if there are no apps

### ISSUE THREAD

**Issue by migmartri** [kubeapps/kubeapps#593]
For example, in my case I do not have any non-deleted app but I do have deleted apps. The problem with the current approach is that I can not see those deleted apps until I have a non-deleted one.

We should always show the filter even if the filter says no apps.

![selection_683](https://user-images.githubusercontent.com/24523/45187970-6e3f3d00-b1e7-11e8-9b1a-ac7ec42b12b3.png)

**Comment by prydonius** [comment]
I think we could fix this next iteration
