### ISSUE TITLE
Re-evaluate namespace global dropbox

### ISSUE THREAD

**Issue by migmartri** [kubeapps/kubeapps#598]
Currently, in the namespace selector we have an 'All namespaces' option. This selection is useful if you want to list the apps deployed across your cluster but has no value AFAICS in other parts of the dashboard. Actually it adds some complexity since now we need to handle this scenario https://github.com/kubeapps/kubeapps/issues/566

We should revisit the usage and existence of this option, @arapulido raised good points here https://github.com/kubeapps/kubeapps/pull/595#issuecomment-419448660

**Comment by lindhe** [comment]
Sorry for not investigating myself before asking now, but what's the behaviour for namespaces that you do not have privileges to access? Because that can be the case, no?

**Comment by andresmgot** [comment]
AFAIK in case you don't have permissions to see a namespace you shouldn't be able to list them so you would only see a namespace in the dropbox.

In case a namespace is manually typed in the URL the user should receive a "You don't have permissions to list resources in the namespace "<ns>""

This is not being tested so I cannot verify that's the actual behavior.

**Comment by davidkarlsen** [comment]
You will always be allowed to list namespaces, but they should maybe be filtered against some rbac to what actions you can apply in them. A check could be to test for list-pods, and only list the namespaces you can list in for instance.

**Comment by lindhe** [comment]
I guess that would leave out ns that have no pods...

**Comment by absoludity** [comment]
Parts of this have been addressed by #1471 and the remaining part (whether we even show an enabled "All namespaces" when the person doesn't have the RBAC) is #2018
