### ISSUE TITLE
Document private repository setup

### ISSUE THREAD

**Issue by migmartri** [kubeapps/kubeapps#600]
Currently, Kubeapps supports Bearer tokens for repository authentication which makes it suitable for example for connecting to a private artifactory repository and potentially any other repository that follows the standard Helm chart repo spec and is exposed via http(s).

@sameersbn wrote a [great blogpost](https://medium.com/bitnami-perspectives/announcing-artifactory-integration-in-kubeapps-0-7-0-14ea911a2328) about using artifactory with kubeapps that we might want to bring here. We can also look into how to connect to a regular private s3 bucket, the use of the helm-s3 plugin as suggested [here](https://kubernetes.slack.com/archives/C9D3TSUG4/p1536260005000100) or even other alternatives like ChartMuseum.

There is already an issue to support s3 repos which in the end could be part of this documentation effort https://github.com/kubeapps/kubeapps/issues/591

WDYT?

**Comment by jdolitsky** [comment]
@prydonius Chartmuseum actually does accept bearer tokens in `latest` docker image, however it does not yet examine scopes (push vs pull etc). It simply verifies using public key that token is valid/non-expired and signed w/ corresponding private key:

```
docker pull chartmuseum/chartmuseum:latest

docker run --rm -it \
  -p 8080:8080 \
  -v $(pwd)/config:/config:ro \
  -e DEBUG=1 \
  -e STORAGE=local \
  -e STORAGE_LOCAL_ROOTDIR=/charts \
  -e BEARER_AUTH=1 \
  -e AUTH_REALM=https://localhost:5001/auth \
  -e AUTH_SERVICE=chartmuseum \
  -e AUTH_ISSUER=auth-server-example \
  -e AUTH_CERT_PATH=/config/server.pem \
  chartmuseum/chartmuseum:latest

curl -v -H "Authorization: Bearer $CM_TOKEN" http://localhost:8080/index.yaml
```

This work is high priority and should come together soon. Please take a look at https://github.com/chartmuseum/auth-server-example

**Comment by prydonius** [comment]
Awesome @jdolitsky, that's good to see! Kubeapps should work with that too then, but we should definitely try it out and verify that.
