### ISSUE TITLE
Rename kubeapps-dashboard Service to avoid confusion over what Service to use

### ISSUE THREAD

**Issue by prydonius** [kubeapps/kubeapps#602]
A lot of users (#382, https://github.com/kubeapps/kubeapps/issues/577#issuecomment-419392268) mistake the `kubeapps-dashboard` Service as the one to set as a LoadBalancer or proxy to using an Ingress resource, when in fact the `kubeapps` Service should be used. It doesn't help that the default Kubernetes Dashboard manifest calls their Service `kubernetes-dashboard`.

We should rename this Service to something that sounds like less of an entrypoint, for example:

- kubeapps-react
- kubeapps-static
- kubeapps-internal

This should help avoid users mistaking the correct Service in the future.

**Comment by andresmgot** [comment]
I would say `kubeapps-dashboard-internal` so we don't lose meaning there. Also, what I think we are missing is some docs to explain how to expose Kubeapps with an Ingress.

**Comment by obeyler** [comment]
Another way should be to provide a Ingress rule in documentation or even in the helm chart
