### ISSUE TITLE
Feature/addon disablement option

### ISSUE THREAD

**Issue by migmartri** [kubeapps/kubeapps#605]
Currently, Kubeapps focused in two main feature sets:

- Deploy and manage applications using Helm.
- Integration with k8s service catalog.

These two features are exposed via menu entries on the top navbar.
![selection_684](https://user-images.githubusercontent.com/24523/45315017-1f93ea80-b4e8-11e8-9be7-5348baf519c3.png)

I'd like to open the discussion of if we should allow users to "enable/disable" addons, being the first one the service catalog.

My take on this is that it makes sense to offer this functionality because:

* While deploying applications is the core of the dashboard, service catalog is an additional, optional capability. 
* It is not supported in all platforms, for example EKS does not support it yet.
* In some cases you might not be interested in any of the existing brokers or on this feature at all.
* Although we are working on improving it, this feature still needs some polishing.

Enabling/Disabling features could be done initially as part of a setting (enabled by default so we do not change the current behavior) in the values.yaml file so it can be tweaked at deployment time. In the future, we might want to evaluate a different way in which an admin enable/disables addons.

What do you think?

**Comment by prydonius** [comment]
My concern with hiding features is that they likely won't be re-enabled and won't be very discoverable. Is there a way we can put less emphasis on the Service Catalog pages without completely hiding it? For example, we could put it under an Add-ons menu that is collapsed by default, if we move to vertical navigation:

![screen shot 2018-09-10 at 15 45 29](https://user-images.githubusercontent.com/1544861/45328419-beccd800-b510-11e8-81cf-46ab0327176d.png)

This could then be used for other non-core add-on type integrations in the future.

I think a parallel could be drawn to something like the GCE Cloud Console, where this is a menu with lots of different services that are all discoverable. When you click on one that you haven't used before you get some information on how to enable to feature (e.g. enabling the API).

**Comment by arapulido** [comment]
I don't think we should enable/disable add-ons at this point. It is not like we have 10 of them and are cluttering the UI. We just have 1 :). I would leave it as it is, for easier discoverability

**Comment by arapulido** [comment]
As for the vertical menu, again, I think it is a bit too much for just 2 items

**Comment by andresmgot** [comment]
I agree on having them somehow discoverable through the UI, if not it's going to be very difficult for users to even know that exists. For me it would be neat having a menu under "Configuration" to see the list of add-ons and enable/disable them.

> We just have 1 :)

I would consider (if we implement this) to include Kubeless functions as well as an add-on since we already have the code :)

**Comment by andresmgot** [comment]
@migmartri was this issue just to ask the question? Should we discuss something else? (I am wondering what "waiting for review" means here)

**Comment by migmartri** [comment]
It as a question. I put it in waiting for review to be sure that everybody had a chance to give their opinion. I'll move it to done now.

Thanks for following up.

**Comment by prydonius** [comment]
Let's keep this open for now and we can update it if we get more feedback that this might be something we want to do.

**Comment by jgato** [comment]
Hi there,
I see this discussion pretty old. In my case, I would like to offer kubeapps to final users. With only the possibility of deploying very concrete apps. But services is not something they will need. Is there any posibility of disabling Services?

**Comment by absoludity** [comment]
I believe it won't be displayed on the new UI (to be released in a few weeks), and I'm currently working on a branch which will remove the option for `Service Instances (alpha)` if the service broker has not been installed, which effectively means it'll be disabled (absent from the main menu). I'll link this issue when the PR is created. Thanks!
