### ISSUE TITLE
Be able to create namespaces/make it easier to deploy to new namespaces

### ISSUE THREAD

**Issue by obeyler** [kubeapps/kubeapps#613]
If the token give the ability to create ns
Either be able to create namespace or declare a namespace when deploy a chart

**Comment by prydonius** [comment]
Actually you can do this today by typing in the name of the namespace you want to create in the Namespaces dropdown box and then deploy a chart into it. It's not immediately clear though, we may want to improve the way you choose the namespace to deploy in.

**Comment by obeyler** [comment]
Ok Sorry I haven't seen this way to do that before.

**Comment by prydonius** [comment]
@obeyler no worries, I think we can make this easier to do!

**Comment by andresmgot** [comment]
That's another point to implement https://github.com/kubeapps/kubeapps/issues/598. If we remove it from the top and make it an input for the deployment form it would be easier to discover.

**Comment by absoludity** [comment]
Namespace creation has been done for some time.
