### ISSUE TITLE
Feature request Store chart value history to be able to reuse it

### ISSUE THREAD

**Issue by obeyler** [kubeapps/kubeapps#614]
When deploy a chart: keep   value.yml + date + comment  into database 
give the opportunity  to set same value for a new deployment into another namespace or even after an undeploy to set same value as before

**Comment by prydonius** [comment]
Hey @obeyler, this is a really interesting idea! So these would be like "templates" of values.yaml files that you could save and reuse to apply the same values to future deployments?

**Comment by obeyler** [comment]
Yes  on a multi tenant cluster if you want to deploy same application for different project with specific value It would be easier to duplicate what you have put on previous deployment.
And as it easy to delete a deployment and create a new one on a small cluster if you want to keep your memory/cpu you can delete and redeploy apps only when you need it again

**Comment by prydonius** [comment]
Makes sense! @arapulido @andresmgot @migmartri what do you think about this feature?

> on a small cluster if you want to keep your memory/cpu you can delete and redeploy apps only when you need it again

This might be a good case for not purge deleting the app. If you just soft-delete it (e.g. `helm delete` or delete without clicking purge in Kubeapps), then you can go back and `helm rollback` it in the future (see https://github.com/helm/helm/blob/master/docs/quickstart.md#uninstall-a-release).

**Comment by andresmgot** [comment]
I agree, makes sense for me too.

**Comment by davidkarlsen** [comment]
Looking for somewhat the same - make the history of values used for deployments available - this eases rollback and also keeps track of changes so it is easier to reason about what was changed when. Ideally alongside a userId of the one initiating the deployment and the date as well.

**Comment by absoludity** [comment]
This is actually done as part of helm 3: `helm get values` https://helm.sh/docs/helm/helm_get_values/
