### ISSUE TITLE
Revisit client timeout settings

### ISSUE THREAD

**Issue by migmartri** [kubeapps/kubeapps#619]
Currently, one of our client `axios` do not have any timeout set which makes connections to depend on upstream reverse proxy settings.

Based on my tests, if for example tiller-proxy is down, this means that we get a 60 seconds timeout enforced by our frontend-nginx. This timeout is the same regardless of exposing the dashboard via port-forward or ingress.

![selection_700](https://user-images.githubusercontent.com/24523/45446044-cad7a780-b680-11e8-8878-4531992109fb.png)
![selection_701](https://user-images.githubusercontent.com/24523/45446057-cdd29800-b680-11e8-87b8-168c1ada613a.png)

Based [on this conversation](https://github.com/kubeapps/kubeapps/pull/615#discussion_r216836644), we mentioned that we might need up to 2 minutes to install a chart in some cases, in which with the current setup will not be possible. 

We should revisit our current timeout situation to 1) Be sure that these long-lasting sync ops can be done (ideally we should move to an async model) and 2) The rest of the API calls have a sensible default that gives a more snappy user experience in case of errors.

**Comment by prydonius** [comment]
See #710 to discuss moving tiller-proxy to asynchronous operations
