### ISSUE TITLE
The e2e test script should enumerate pods/deployments rather than hardcoding

### ISSUE THREAD

**Issue by prydonius** [kubeapps/kubeapps#623]
Currently, our e2e test script hardcodes all the deployments to check to be running: https://github.com/kubeapps/kubeapps/blob/master/script/e2e-test.sh#L49-L55

If we add a new component in the future, it's likely that we may forget to add it to this list. We should be able to simply enumerate all the pods related to the chart (e.g. using release labels) rather than explicitly listing each one.

**Comment by andresmgot** [comment]
Note that we need to differentiate between normal pods and job pods. Also in case there is a new component we'd need to add it to the other lists (`helm install`, and the image check) so it's not that easy to forget.

**Comment by prydonius** [comment]
> Note that we need to differentiate between normal pods and job pods.

I believe the job pods won't have the `release` label, but we can check.

> Also in case there is a new component we'd need to add it to the other lists (helm install, and the image check)

Hmm not sure what you mean by this

**Comment by andresmgot** [comment]
>>Also in case there is a new component we'd need to add it to the other lists (helm install, and the image check)

> Hmm not sure what you mean by this

What I mean is that there is a new component we would need to add it to three places so it's difficult to either not hardcode them but also forget it. This would be an example:

```patch
diff --git a/script/e2e-test.sh b/script/e2e-test.sh
index c9670100..047c78e0 100755
--- a/script/e2e-test.sh
+++ b/script/e2e-test.sh
@@ -39,12 +39,15 @@ helm install --name kubeapps-ci --namespace kubeapps $ROOT_DIR/chart/kubeapps \
   --set dashboard.image.repository=kubeapps/dashboard$IMG_MODIFIER \
   --set tillerProxy.image.tag=$DEV_TAG \
   --set tillerProxy.image.repository=kubeapps/tiller-proxy$IMG_MODIFIER
+  --set newComponent.image.tag=$DEV_TAG \
+  --set newComponent.image.repository=kubeapps/new-component$IMG_MODIFIER

 # Ensure that we are testing the correct image
 k8s_ensure_image kubeapps kubeapps-ci-internal-apprepository-controller $DEV_TAG
 k8s_ensure_image kubeapps kubeapps-ci-internal-chartsvc $DEV_TAG
 k8s_ensure_image kubeapps kubeapps-ci-internal-dashboard $DEV_TAG
 k8s_ensure_image kubeapps kubeapps-ci-internal-tiller-proxy $DEV_TAG
+k8s_ensure_image kubeapps kubeapps-ci-internal-new-component-proxy $DEV_TAG

 # Wait for Kubeapps Pods
 k8s_wait_for_pod_ready kubeapps app=kubeapps-ci
@@ -52,6 +55,9 @@ k8s_wait_for_pod_ready kubeapps app=kubeapps-ci-internal-apprepository-controlle
 k8s_wait_for_pod_ready kubeapps app=kubeapps-ci-internal-chartsvc
 k8s_wait_for_pod_ready kubeapps app=kubeapps-ci-internal-tiller-proxy
 k8s_wait_for_pod_ready kubeapps app=mongodb
+k8s_wait_for_pod_ready kubeapps app=kubeapps-ci-internal-new-component
 k8s_wait_for_pod_completed kubeapps apprepositories.kubeapps.com/repo-name=stable

 # Run helm tests
```
