### ISSUE TITLE
Too many pod tag as "Terminated" not purged

### ISSUE THREAD

**Issue by obeyler** [kubeapps/kubeapps#624]
There is so many pod "Terminated:error" that I can't check all to find the reason another issue (I've got 404 on repository list) #625 

note that there is 55 pods most of them are Terminated pods...
![image](https://user-images.githubusercontent.com/23224162/45455051-17a19980-b6e6-11e8-9510-70111c0db11e.png)
![image](https://user-images.githubusercontent.com/23224162/45455103-3ef86680-b6e6-11e8-8ba4-0eba100cf734.png)

**Comment by prydonius** [comment]
It looks like the cleanup job failed and kept restarting, I'm guessing it's related to #625 because the apprepository API seems to have disappeared.

**Comment by migmartri** [comment]
@obeyler could you paste the logs of one of those failing pods?

**Comment by obeyler** [comment]
each failing pod has :
time="XXXXXXXZ" level=fatal msg="Can't connect to mongoDB: unable to connect to MongoDB"

**Comment by migmartri** [comment]
Thanks @obeyler.

@prydonius @andresmgot, do you think that this could be related to https://github.com/kubeapps/kubeapps/issues/665?

Long story short is that if you miss passing the existing MongoDB password during the chart upgrade the application gets miss-configured. https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps#upgrading-kubeapps

Would it possible that this is what happened to you @obeyler?

JFYI, we have planned to work on improving upgrading Kubeapps during the next release.

**Comment by obeyler** [comment]
@prydonius @migmartri 
I redeploy very offen the chart on my kubernetes cluster It's seems that the mongodb instance is still running but the kubeapps pod is not able to connect to the mongo anymore.
Maybe the password inside kubeapps changes so kubeapps won't be able anymore to connect to the first mongodb (or the new I don't know).
On the chart value file an explicit way to fix the password could be a great idea. It force not changement on each deployment.

**Comment by andresmgot** [comment]
hi @obeyler, we have released a new version of Kubeapps (the latest chart version is 0.6.2). That should fix any issue with the mongodb secret. Have you tried that version?
