### ISSUE TITLE
all repositories have disapeared

### ISSUE THREAD

**Issue by obeyler** [kubeapps/kubeapps#625]
Sorry I forgot to take immediatly the snapshot where I can see "Error"
I lost all repository ( Without any re deployent of the chart)

![image](https://user-images.githubusercontent.com/23224162/45456180-1b371f80-b6ea-11e8-9e9c-a5951a8efd16.png)

![image](https://user-images.githubusercontent.com/23224162/45456118-d9a67480-b6e9-11e8-834d-7090fa39175a.png)

**Comment by prydonius** [comment]
What's the output of `kubectl get crd`?

**Comment by obeyler** [comment]
@prydonius 
 kubectl get crd
NAME                           AGE
apprepositories.kubeapps.com   10h

**Comment by andresmgot** [comment]
mm, this issue seems indeed related to #624 . Something has gone wrong with an uninstallation of Kubeapps and the `apprepositories.kubeapps.com` CRD is probably in `Deleting` state. What does it return `kubectl get -o yaml crd apprepositories.kubeapps.com` ?

If you had `apprepositories` and they disappeared it may be for a different side effect. If the clean up job from a previous installation didn't succeed and the job is being restarted even when a new installation takes place the clean up job may delete the new `apprepositories`. We should probably add a check to avoid that but it's something difficult to get. The clean up job may have failed if the CRD `apprepositories.kubeapps.com` has been deleted before uninstalling kubeapps.

In any case, to fix these issues I would recommend to uninstall the chart, delete the `kubeapps` namespace and ensure that everything is clean before reinstalling the chart.

**Comment by obeyler** [comment]
I worried about 

> "In any case, to fix these issues I would recommend to uninstall the chart, delete the kubeapps namespace and ensure that everything is clean before reinstalling the chart."

I can do that but in our system as we have a full automatized installation for Kubernetes/ other somponents/and  all charts each part is launch automatically on any change 
so adding a manual step for specif chart...

**Comment by obeyler** [comment]
```
kubectl get -o yaml crd apprepositories.kubeapps.com
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/resource-policy: keep
  creationTimestamp: 2018-09-12T21:45:51Z
  generation: 1
  labels:
    app: kubeapps-apprepository-controller
    chart: kubeapps-0.4.1
    heritage: Tiller
    release: kubeapps
  name: apprepositories.kubeapps.com
  resourceVersion: "14418"
  selfLink: /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/apprepositories.kubeapps.com
  uid: 37ee8fb2-b6d5-11e8-af42-fa163e213e2c
spec:
  additionalPrinterColumns:
  - JSONPath: .metadata.creationTimestamp
    description: |-
      CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.

      Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata
    name: Age
    type: date
  group: kubeapps.com
  names:
    kind: AppRepository
    listKind: AppRepositoryList
    plural: apprepositories
    shortNames:
    - apprepos
    singular: apprepository
  scope: Namespaced
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: AppRepository
    listKind: AppRepositoryList
    plural: apprepositories
    shortNames:
    - apprepos
    singular: apprepository
  conditions:
  - lastTransitionTime: 2018-09-12T21:45:51Z
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: null
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1alpha1

```

**Comment by andresmgot** [comment]
> I can do that but in our system as we have a full automatized installation for Kubernetes/ other somponents/and all charts each part is launch automatically on any change so adding a manual step for specif chart...

what's your automatic workflow? In theory kubeapps should behave like any other chart. It seems that your issues are related to a failure in the uninstallation.

Your `apprepositories.kubeapps.com` seems to be healthy (at least now). If you delete the pod `kubeapps-repository-controller-...` it should create a new one. Does that one have the same logs? Does it work for you if you install the repositories again?

**Comment by migmartri** [comment]
@obeyler I'd like to dig a little bit more into the issue.

Did this happen after a chart upgrade our out of the blue?

Thanks for the info about the `CustomResourceDefinition`, is that the current state of the installation? Is it still failing?

Could you list of apprepository resources?

```
 kubectl get apprepositories.kubeapps.com --show-labels
```

What's the response that you get from the appRespositories API call in the UI?

![selection_702](https://user-images.githubusercontent.com/24523/45505945-c70c5980-b742-11e8-9dee-e9be24764620.png)

**Comment by prydonius** [comment]
@obeyler we'd be happy to jump on a call to help you debug this if that's easier!

**Comment by obeyler** [comment]
@migmartri  Sorry I have to redeploy all the cluster so I haven't got the context anymore. I reproduce it again I'll do the 
 kubectl get apprepositories.kubeapps.com --show-labels you've asked

**Comment by obeyler** [comment]
Note that I suspect that the behavior occured when kubernetes drain a node.

**Comment by prydonius** [comment]
@obeyler interesting, for now I will close this, but please reopen an issue referring to this if you see this again.
