### ISSUE TITLE
Windows binary

### ISSUE THREAD

**Issue by arapulido** [kubeapps/kubeapps#63]
Kubeapps CLI should have a working binary for Windows

**Comment by ngtuna** [comment]
To not be missing: the cross compiling also needs to be added so we can get rid of OSX build on travis which takes too much time to be completed.

**Comment by ngtuna** [comment]
Right now cross compiling kubeapps cli is unable because of the jsonnet version being used is in C++. One of the solution is using the pure Go version of it: https://github.com/google/go-jsonnet

**Comment by ngtuna** [comment]
Couple of fails when trying to build windows binary on a linux machine:

```
$ env GOOS=windows GOARCH=amd64 CC_FOR_TARGET=x86_64-w64-mingw32-gcc CGO_ENABLED=1 go build -o kubeapps.exe main.go
# runtime/cgo
gcc: error: unrecognized command line option ‘-mthreads’; did you mean ‘-pthread’?

$ env CC=i686-w64-mingw32-gcc-win32 GOOS=windows GOARCH=386 CGO_ENABLED=1 go build -o kubeapps.exe main.go
# github.com/kubeapps/kubeapps/vendor/github.com/strickyak/jsonnet_cgo
g++: error: unrecognized command line option ‘-mthreads’; did you mean ‘-pthread’?

$ env CC=x86_64-w64-mingw32-g++ GOOS=windows GOARCH=amd64 CGO_ENABLED=1 go build -o kubeapps.exe main.go
# runtime/cgo
gcc_libinit_windows.c: In function ‘void x_cgo_sys_thread_create(void (*)(void*), void*)’:
gcc_libinit_windows.c:57:13: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
  if(thandle == -1) {
     ~~~~~~~~^~~~~
cc1plus: all warnings being treated as errors
```

I am struggling what is the best CC for windows on linux. https://wiki.debian.org/Mingw-W64 seems to be the most recommended.

cc/ @anguslees @sebgoa

**Comment by sebgoa** [comment]
Why do you still have some jsonnet in kubeapps CLI. Since the manifests are loaded as YAML...

**Comment by anguslees** [comment]
I replied to this earlier over chat, without realising there was a github issue as well.  TL;DR: We need to set both CC and CXX:

This works for me (it compiles and produces a windows executable, I haven't tried actually running it):
```console
 % CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ GOOS=windows GOARCH=amd64 go build -o kubeapps.exe .
```

**Comment by ngtuna** [comment]
close #63 via #84
