### ISSUE TITLE
The first time you run kubeapps dashboard the browser opens to a blank 

### ISSUE THREAD

**Issue by arapulido** [kubeapps/kubeapps#64]
Steps to reproduce:

1) `kubeapps up`
2) `kubeapps dahsboard`

Expected results:

Opening the browser waits a couple of seconds for the proxy to be ready and then opens the page successfully

Actual results:

Opening the browser tag is too fast and it opens before the proxy is ready. You get a server error and need to refresh the page to get to the dashboard

**Comment by prydonius** [comment]
note this is a side-effect of #40, but we may be able to work around it by handling the proxy as a child process

**Comment by ngtuna** [comment]
PR for #40 has been submitted. PTAL @prydonius #65 . I will also check dashboard command to leverage client-go v4.0 today
