### ISSUE TITLE
chart e2e test should test both TLS and non-TLS scenarios

### ISSUE THREAD

**Issue by prydonius** [kubeapps/kubeapps#646]
In https://github.com/kubeapps/kubeapps/pull/642 we updated the chart e2e test to enable TLS in Tiller and test tiller-proxy in this scenario. However, this opens up a potential hole where Kubeapps might break for non-TLS scenarios.

We should add an additional test for a non-TLS scenario. I think the best way to implement this would be to:

1. update e2e-test.sh to take a parameter for enabling/disabling TLS and namespace to install Tiller into
2. execute the script twice in the CI, one with TLS enabled and another with TLS disabled in different namespaces in the same cluster

What do you think?

**Comment by andresmgot** [comment]
In my opinion, testing this specific setup e2e would not worth the overhead it adds. I see this like doing a e2e with and without RBAC. If the secure option works, it would be a rare corner case that the insecure option doesn't. Also, we will be using the version without TLS in our development environments (at least I will) so it would be difficult to miss an error there.

A different thing would be if we want to test different combinations of the helm chart installation options to test that they work together. In that case I would suggest something that add less overhead: like comparing the output of executing `helm install --dry-run --debug` to check expected results.

**Comment by prydonius** [comment]
My main concern is testing that tiller-proxy is able to connect properly to a Tiller with both TLS disabled and enabled.

> I see this like doing a e2e with and without RBAC.

The difference is most people will have RBAC enabled, but Helm with TLS disabled. We are now actually testing a less common scenario. Also, if RBAC is disabled (in permissive mode), everything should work the same.

> Also, we will be using the version without TLS in our development environments (at least I will) so it would be difficult to miss an error there.

Well sure, but that's not really a reason to not add automated testing of any sort, right?

> A different thing would be if we want to test different combinations of the helm chart installation options to test that they work together. In that case I would suggest something that add less overhead: like comparing the output of executing helm install --dry-run --debug to check expected results.

We specifically want to test that tiller-proxy is able to start up and connect to Tiller correctly here, so I don't think a template test would really suffice.
