### ISSUE TITLE
[idea] integration with KubeDB operator

### ISSUE THREAD

**Issue by prydonius** [kubeapps/kubeapps#647]
KubeDB is an operator that allows you to run different databases inside your cluster: https://kubedb.com/docs/0.8.0/guides/elasticsearch/quickstart/quickstart/. Kubeapps could integrate with KubeDB to provide a UI to provision and manage instances of KubeDB databases.

**Comment by prydonius** [comment]
cc @obeyler

**Comment by obeyler** [comment]
Thanks !

**Comment by florianrusch** [comment]
For everyone who is also searching for the Service Broker of KubeDB, take a look here: https://github.com/appscode/service-broker/

**Comment by florianrusch** [comment]
@prydonius I think this could be closed or? I've tested it in the last days and it seems to work as expected.

**Comment by prydonius** [comment]
@florianrusch good to hear! Yes, I suppose we can close this out, thanks!

**Comment by tamalsaha** [comment]
AppsCode Service Broker is out now! To use with Kubeapps, you can follow the guide here: https://appscode.com/products/service-broker/0.1.0/guides/kubeapps/
