### ISSUE TITLE
[Design/Proposal] Global runtime error handling

### ISSUE THREAD

**Issue by migmartri** [kubeapps/kubeapps#657]
Currently, when a runtime error happens in the dashboard, the UI stops rendering but "unless specifically handled" the user does not see a message that something went wrong. This was the case https://github.com/kubeapps/kubeapps/issues/635 for example:

React 16 has the concept of errorBoundary that we should explore https://reactjs.org/docs/error-boundaries.html, potentially making it available as a wrapper at the root component.

This component could eventually contain the efforts made here https://github.com/kubeapps/kubeapps/issues/654

The goal being:

* Step 1: If a unexpected runtime error happens, we show a message to the user that `something went wrong` (I believe that we have already some markup for this that suggest to look at the console and so on)
* Step 2: This component might be able to capture some specific custom errors, showing different error types and messages https://github.com/kubeapps/kubeapps/issues/654. This currently is happening at every component level, so making it generic could help.

wdyt @andresmgot @prydonius ?

**Comment by prydonius** [comment]
Yes, I was concerned about losing that information with generic errors, but I think @migmartri mentioned that this could be achieved if we had a reducer that looked at global errors and the actions can dispatch that information.

**Comment by migmartri** [comment]
Work in progress, draft proposal, DO NOT REVIEW YET

Kubeapps error handling

## Error types and scope


The scope of this task is to have an answer to two types of errors, unexpected/unhandled and handled.

### 1 - Unexpected, unhandled errors

These are the errors raised by the application at runtime. And they can go from a application logic exception to network errors connecting to an API.

Today, we are handling errors per-case basis, which is good if we want to react to the thrown error via a side-effect (i.e retry) or by showing actionable information to the user, but we still **need a catch all "Sorry something went wrong"**

Why do we need a catch all?

Currently, if the application experiences a runtime error, the application stops rendering, but does not notify the user that something went wrong. Leaving a page in a potentially corrupted state. [This](https://github.com/kubeapps/kubeapps/issues/632) is an example of such behavior.

This behavior can be confusing, so it would be better to just show the user, "something went wrong, please double check 'foo' and/or create an issue in here..."

This kind of catch all, in theory, should be easily achieved by using React's [Error boundary](https://reactjs.org/docs/error-boundaries.html). In our case we will wrap our `Root` or `Layout` components. If we want to allow the app to render the header and footer but wrap the dynamic content, we could do it inside the LayoutComponent, example:

```tsx
<main>
  <ErrorBoundary>
    <div className="container">{this.props.children}</div>
  </ErrorBoundary>
</main>
```

The way `ErrorBoundary` will work is by catching any error, in which case, it will render the existing `UnexpectedErrorAlert` component.

NOTE: ErrorBoundary does not apply on event handlers as explained [here](https://reactjs.org/docs/error-boundaries.html#how-about-event-handlers), but it is still a good addition in our case since we have quite some client side logic, i.e parsing yaml.

### 2 - Handled errors

Currently, we are doing quite a good job on the way we expose specific errors to the user in a central way. For doing so, we use a multi-purpose component called `ErrorSelector`, which is in charge of showing an error in different ways depending on its nature.

This approach is good, but it has the drawback that every one of the components is rendering this `ErrorSelector` component potentially in a different way/place. 

It would be better if this ErrorSelector component was rendered only once in the layout, and is connected to the redux store. This is a example of [this pattern](https://stackoverflow.com/a/34403521). 

That way, errors will allways be shown in the same place.

**Implementation details**

**TODO**: 
- [ ] Look into portals
- [ ] Look into existing error actions and where/how they are handled

## Action plan

1 - Implement error boundary for runtime rendering errors, reusing `UnexpectedError` component.
2 - Implement an instance of ErrorSelector in the layout connected to the redux store, move a couple of ErrorSelector consumers to this new model.
3 - Finish the migration of all these consumers from rendering the component to dispatch an error and remove those renders.
4 - For the `ErrorBoundary` component

**Comment by andresmgot** [comment]
I created #724 #725 #726 #727 from the stages described in the document. I set the milestone for the first one to 1.0 and the rest for beyond 1.0 as agreed in the doc.

**Comment by migmartri** [comment]
> I created #724 #725 #726 #727 from the stages described in the document. I set the milestone for the first one to 1.0 and the rest for beyond 1.0 as agreed in the doc.

Thanks @andresmgot!
