### ISSUE TITLE
Improve Kubeapps chart upgrade experience

### ISSUE THREAD

**Issue by migmartri** [kubeapps/kubeapps#665]
Upgrading the chart requires that you pass the previous Mongodb password, otherwise the newly upgrade release will not be able to connect to MongoDB.

We [have it documented](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps#upgrading-kubeapps) but it seems [common for users](https://kubernetes.slack.com/archives/C9D3TSUG4/p1537474402000100?thread_ts=1537467768.000100&cid=C9D3TSUG4) to miss this additional step, probably mainly because they were not asked to do anything during install.

We should find away to avoid this pitfall

* Is there any way we could detect that the password was not passed and let the user know during upgrade?
* Maybe asking the user for the password during installation?
* Do not autogenerate a password?

**Comment by migmartri** [comment]
Currently, if an user forgets to pass the previous MongoDB password to `helm upgrade`, chartsvc will crash but it can be recovered by following these steps:

1 - Delete the mongodb pod, something like `kubectl delete $(kubectl get pods -l app=mongodb,release=kubeapps -o name)`
2 - Go to the repositories section in the UI and click on refresh on every one of the repos?

**Comment by andresmgot** [comment]
IMO we should target to be able to upgrade Kubeapps from Kubeapps itself (the UI). For doing so we should assume that the terminal is not available. I wonder if we can set `required` for `.Values.mongodb.existingSecret` if `.Release.IsUpgrade` as you suggest. That way users doesn't need to obtain the current root password but the name of the secret (that by default is `kubeapps-mongodb`). Apart from that we can document how to do the process (with screenshots) and point to that doc in the default release notes. WDYT?

**Comment by arapulido** [comment]
I have raised the priority of this, as I think that  we should improve a lot the experience of upgrading Kubeapps (especially since we are shipping very often)

**Comment by prydonius** [comment]
@andresmgot the problem with what you suggest is that if we skip the secret during upgrade, Helm will delete it, so there is no current way to keep the secret around without changing the password on upgrade.

We could move the creation of the secret to a pre-install hook, that way Helm won't manage it after installation, but that will keep it around after deleting the chart unless we also add a post-delete hook that deletes it (similar to what we do with apprepos).

**Comment by andresmgot** [comment]
> We could move the creation of the secret to a pre-install hook, that way Helm won't manage it after installation, but that will keep it around after deleting the chart unless we also add a post-delete hook that deletes it (similar to what we do with apprepos).

My +1 to that then.

**Comment by andresmgot** [comment]
I am going to try then implementing the secret generation in hooks. Let me know if you think otherwise.

**Comment by prydonius** [comment]
@andresmgot what would be the upgrade experience of that from the existing chart? If we move it to a hook, Helm will likely delete the existing secret and it won't be created unless it's also a pre-upgrade hook?

**Comment by andresmgot** [comment]
Yes, good point. I'll make sure that we cover that use case to avoid breaking changes.
