### ISSUE TITLE
[Design/Proposal] Revisit application access URL

### ISSUE THREAD

**Issue by arapulido** [kubeapps/kubeapps#673]
Right now only kind of works for LoadBalancer services

**Comment by prydonius** [comment]
This sounds great @andresmgot, I have some questions about the Ingress part but the LoadBalancer stuff makes sense to me,

> If the ingress rule doesn’t have a valid IP/hostname we should show the Pending tag.

AFAIK `status.loadBalancer.ingress` will have the IP/hostname of the Ingress controller (e.g. LoadBalancer svc IP of the ingress controller), but what we'd really want to check is if `spec.rules[*].host` is set, right? That will hold the actual hostnames that I want to access the app by.

> If spec.tls.hosts is set, that takes precedence to status.loadBalancer.ingress. Those hosts will be shown instead.

I'm not sure I understand why this takes precedence? What's special about `spec.tls.hosts` over `spec.rules[*].host`?

**Comment by migmartri** [comment]
Thanks @andresmgot, I am also not sure about the Ingress part?

For example, for the default kubeapps ingress (which I have installed) I get:

```yaml
$ k get ingress miguel-kubeapps -o yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/acme-challenge-type: dns01
    certmanager.k8s.io/acme-dns01-provider: default
    certmanager.k8s.io/cluster-issuer: letsencrypt-staging-dns
  creationTimestamp: 2018-09-13T00:31:18Z
  generation: 1
  labels:
    app: kubeapps
    chart: kubeapps-0.5.1
    heritage: Tiller
    release: miguel-kubeapps
  name: miguel-kubeapps
  namespace: miguel
  resourceVersion: "134549220"
  selfLink: /apis/extensions/v1beta1/namespaces/miguel/ingresses/miguel-kubeapps
  uid: 54cbc660-b6ec-11e8-b1b0-06b787dce24e
spec:
  rules:
  - host: miguel-kubeapps-dev.k.dev.bitnami.net
    http:
      paths:
      - backend:
          serviceName: miguel-kubeapps
          servicePort: http
        path: /
  tls:
  - hosts:
    - miguel-kubeapps-dev.k.dev.bitnami.net
    secretName: kubeapps-miguel-devel
status:
  loadBalancer:
    ingress:
    - {}
```
In which case, `status.loadBalancer.ingress` is an empty object but the actual hostname I want is: `https://miguel-kubeapps-dev.k.dev.bitnami.net`

That means that we need to iterate through the spec.rules.hosts[], and then decide if they have SSL termination in the ingress controller by looking for a match in the tls.hosts?

**Comment by andresmgot** [comment]
> AFAIK status.loadBalancer.ingress will have the IP/hostname of the Ingress controller (e.g. LoadBalancer svc IP of the ingress controller), but what we'd really want to check is if spec.rules[*].host is set, right?

You are right. I was thinking in the case that no host is added but that's probably not a useful case.

> That means that we need to iterate through the spec.rules.hosts[], and then decide if they have SSL termination in the ingress controller by looking for a match in the tls.hosts?

What we can do is adding the hosts under `spec.rules.hosts` as HTTP URLs and the ones in `tls.hosts` as HTTPS. Taking your Ingress example that would mean that we show `http://miguel-kubeapps-dev.k.dev.bitnami.net` and `https://miguel-kubeapps-dev.k.dev.bitnami.net` in the UI. That way we don't need to do smart matching since the application is actually accessible using both URLs.

**Comment by andresmgot** [comment]
@migmartri @prydonius I have updated the comment. Note that I have also added a note to the case in which the host contains a wildcard.

**Comment by migmartri** [comment]
> You are right. I was thinking in the case that no host is added but that's probably not a useful case.

We need to also take into account the `path`, for example:

```yaml
$ k get ingress [REDACTED]-swagger -o yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
   ...
  labels:
   ...
spec:
  rules:
  - host: [REDACTED].k.dev.bitnami.net
    http:
      paths:
      - backend:
          serviceName: [REDACTED]
          servicePort: 8080
        path: /docs
status:
  loadBalancer:
    ingress:
    - {}
```

In which case the correct way to access to it is via:

```
http://[REDACTED].k.dev.bitnami.net/docs
```
> What we can do is adding the hosts under spec.rules.hosts as HTTP URLs and the ones in tls.hosts as HTTPS. Taking your Ingress example that would mean that we show http://miguel-kubeapps-dev.k.dev.bitnami.net and https://miguel-kubeapps-dev.k.dev.bitnami.net in the UI. That way we don't need to do smart matching since the application is actually accessible using both URLs.

Is it accessible by both URLs? By default for example Nginx Ingress controller [redirects](https://kubernetes.github.io/ingress-nginx/user-guide/tls/#server-side-https-enforcement-through-redirect), so to me showing the non-https URL is unnecessary clutter that I'd prefer to avoid.

Just for the record, things can get trickier with TLS when you have multiple ingress resources under the same hostname. 

Ingress name | hostname | tls hostname | path | expected result |
------------ | ------------- | --| ---|--|
A| foobar.com|foobar.com|/|https://foobar.com|
B| foobar.com||/docs|https://foobar.com/docs|

Note how B, even though does not defined the hostname under `tls.hosts`, still inherits the TLS behavior from the other ingress resource. This means that if we want to do this properly, we will need to process all the ingresses together, group by hostname and so on. That said, I do not think that we should do it for now since this will just mean that we will show an http:// url that will get redirected to https://

**Comment by prydonius** [comment]
> We need to also take into account the path, for example:

+1, I was thinking we could ignore it for now, but I think it makes sense to include it.

> Is it accessible by both URLs? By default for example Nginx Ingress controller redirects, so to me showing the non-https URL is unnecessary clutter that I'd prefer to avoid.

+1 I also think we should just do a simple string match of the hosts to determine if it's HTTPS or not.

> Note how B, even though does not defined the hostname under tls.hosts, still inherits the TLS behavior from the other ingress resource. 

Hmm, that actually seems like a bug or limitation in the way the ingress controller handles that to me. If it correctly dealt with each Ingress configuration separately, it should have created the `/docs` path under a virtual host over HTTP, and the `/` path under a virtual host over HTTPS.

**Comment by andresmgot** [comment]
>> We need to also take into account the path, for example:

> +1, I was thinking we could ignore it for now, but I think it makes sense to include it.

I though about omitting paths to avoid long lists but okay. We can show each one of the paths if they exist.

>>  Is it accessible by both URLs? By default for example Nginx Ingress controller redirects, so to me showing the non-https URL is unnecessary clutter that I'd prefer to avoid.

> +1 I also think we should just do a simple string match of the hosts to determine if it's HTTPS or not.

It's not that easy to do the matching. For example if the `rules[].host = foo.bar.net` and the TLS host is `*.bar.net` a simple string match won't work. Anyway, in that case we would show `http://foo.bar.net` and `https://*.bar.net`.

Also, about the Nginx redirection: that can be avoided with an annotation. In any case, I am fine if we omit the HTTP URL in that case.

**Comment by andresmgot** [comment]
Updated the description with your suggestions.

**Comment by prydonius** [comment]
I'm not 100% based on https://github.com/kubernetes/ingress-nginx/issues/2667 that something like "*.bar.net" works in Ingress, according to https://github.com/kubernetes/ingress-nginx/issues/2667#issuecomment-398997936 "bar.net" would work for "foo.bar.net". Anyway, I think there is probably some regex we can do to match these.

**Comment by migmartri** [comment]
> It's not that easy to do the matching. For example if the rules[].host = foo.bar.net and the TLS host is *.bar.net a simple string match won't work. 

`*.bar.net` is this a valid tls host? According to https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.12/#ingresstls-v1beta1-extensions 

> The values in this list must match the name/s used in the tlsSecret. Defaults to the wildcard host setting for the loadbalancer controller fulfilling this Ingress, if left unspecified.

Which sounds like either is domain specific or it will be *, but not necessarily says that wildcards are supported. I am not sure about this though.

> foo.bar.net and the TLS host is *.bar.net a simple string match won't work. Anyway, in that case we would show http://foo.bar.net and https://*.bar.net.

Why? we should show `https://foo.bar.net`. I'd just show the ones in the spec.hosts, tls.hosts will only be used to know if we should put https in front or not. I do not understand why we would like to show `https://*.bar.net.`. 

I might be missing something. Could we do an exercise with a table similar to the one here https://github.com/kubeapps/kubeapps/issues/673#issuecomment-425184567 where we put a different set of valid (per the spec) examples and its UI outcome?

**Comment by migmartri** [comment]
Something that it might be confusing is that I do not think that we should show the union of both sets spec.hosts + spec.tls.hosts

What we need to do is to shot `spec.hosts` and the intersection of both (or regexp match) should the the https:// domains ?

**Comment by andresmgot** [comment]
> Which sounds like either is domain specific or it will be *, but not necessarily says that wildcards are supported. I am not sure about this though.

It's supported: https://github.com/kubernetes/ingress-nginx/issues/2667

I am okay if we want to do some smart matching (`*.bar.net` -> `foo.bar.net`) but that means that there might be cases we are not taking into account.

> The actual hosts setup for the Ingress are configured in spec.rules[*].host, spec.tls.hosts just tells the Ingress controller which hosts in spec.rules[*].host should TLS be enabled for.

True, I didn't thought it like that.

**Comment by andresmgot** [comment]
Moving this to "done"! I will start sending PRs, we can discuss implementation details there.

**Comment by prydonius** [comment]
@andresmgot I forgot to check your updated proposal, but it looks good to me. Just FYI, we should probably lgtm proposals before going ahead and implementing it, in case more discussion is needed.

**Comment by andresmgot** [comment]
yes @prydonius, don't worry, I had the LGTM from @migmartri and I only started implementing the SVC part. Thanks for checking!

**Comment by lindhe** [comment]
When using regex in the path, that too gets included. :/

Might be hard to fix though...

![Screenshot from 2019-08-09 11-11-29](https://user-images.githubusercontent.com/7773090/62768145-86be7400-ba96-11e9-87aa-f7c95164fde8.png)

**Comment by prydonius** [comment]
@lindhe would you be able to open a separate issue for that?
