### ISSUE TITLE
Check and document OpenShift support 

### ISSUE THREAD

**Issue by migmartri** [kubeapps/kubeapps#676]
We should check if Kubeapps is compatible with OpenShift as well as documenting any setup differences.

**Comment by migmartri** [comment]
Something that I noticed is that `helm status` reports that the mongodb deployment has a different API version

```
==> v1beta1/Deployment
NAME              DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
kubeapps-mongodb  1        0        0           0          51m

==> v1beta2/Deployment
kubeapps-internal-apprepository-controller  1  1  1  1  51m
kubeapps-internal-chartsvc                  2  2  2  0  51m
kubeapps-internal-dashboard                 2  2  2  2  51m
kubeapps                                    2  2  2  2  51m
kubeapps-internal-tiller-proxy              2  2  2  0  51m
```

and actually this deployment can not schedule any pod.

This is the last entry in the deployment status timeline.

```
  Normal  ScalingReplicaSet  53m   deployment-controller  Scaled up replica set kubeapps-mongodb-5898f98f66 to 1
```

and this is the error in the replica set

```
  Warning  FailedCreate  5s (x14 over 46s)  replicaset-controller  Error creating: pods "kubeapps-mongodb-5898f98f66-" is forbidden: unable to validate against any security context constraint: [fsGroup: Invalid value: []int64{1001}: 1001 is not an allowed group spec.containers[0].securityContext.securityContext.runAsUser: Invalid value: 1001: must be in the ranges: [1000140000, 1000149999]]
```

**Comment by migmartri** [comment]
Another issue I've found is that this command does not work

```
kubectl get secret $(kubectl get serviceaccount kubeapps-operator -o jsonpath='{.secrets[].name}') -o jsonpath='{.data.token}' | base64 --decode
```

 because there is actually two secrets listed inside the service account secrets array and we pick the first one
```
apiVersion: v1
imagePullSecrets:
- name: kubeapps-operator-dockercfg-qflks
kind: ServiceAccount
metadata:
  creationTimestamp: 2018-10-19T18:03:10Z
  name: kubeapps-operator
  namespace: kubeapps
  resourceVersion: "34638"
  selfLink: /api/v1/namespaces/kubeapps/serviceaccounts/kubeapps-operator
  uid: 3d7c5b51-d3c9-11e8-8ef5-080027c965a6
secrets:
- name: kubeapps-operator-dockercfg-qflks
- name: kubeapps-operator-token-tt564
```

this shows how brittle our command is so we might need to look into an alternative.

**Comment by andresmgot** [comment]
> securityContext.runAsUser: Invalid value: 1001: must be in the ranges

Yes, that's a common problem with some charts. Openshift doesn't allow to use that user. We can set `.Values.mongodb.securityContext.enabled` to `false` to avoid it. The image is already using the user 1001 (link here: https://github.com/bitnami/bitnami-docker-mongodb/blob/master/3.6/debian-9/Dockerfile#L33) so the result will be the same and Openshift will use one of their allowed UIDs.

**Comment by migmartri** [comment]
Thanks @andresmgot 

Another issue that I am running into is that when I try to log in, the API server panics.

```json
{
  "code": 401,
  "message": "an error on the server (\"This request caused apiserver to panic. Look in the logs for details.\") has prevented the request from succeeding (post selfsubjectrulesreviews.authorization.k8s.io)"
}
```

**Comment by andresmgot** [comment]
that's what I was afraid of. See https://github.com/kubeapps/kubeapps/issues/698#issuecomment-426483216

**Comment by migmartri** [comment]
See https://github.com/kubeapps/kubeapps/issues/698#issuecomment-431872229 for more info about the error

**Comment by migmartri** [comment]
I have done some testing in a dedicated OpenShift cluster

#### Install Helm and Kubeapps

```bash
# Logging in with a cluster-admin user
$ oc login https://cluster-URL:8443 --username admin --password REDACTED
$ oc project miguel

$ oc version
# Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", # BuildDate:"2018-10-05T16:46:06Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
# Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1+a0ce1bc657", GitCommit:"a0ce1bc", GitTreeState:"clean", BuildDate:"2018-07-09T13:09:48Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"linux/amd64"}

$ export TILLER_NAMESPACE=miguel
# Install Helm
$ kubectl -n ${TILLER_NAMESPACE} create sa tiller
$ kubectl create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount=${TILLER_NAMESPACE}:tiller
$ helm init --service-account tiller

# Install Kubeapps
$ helm repo update
$ helm install --name kubeapps --set tillerProxy.host=tiller-deploy.${TILLER_NAMESPACE}:44134 --namespace miguel bitnami/kubeapps

# Create credentials
$ kubectl create serviceaccount kubeapps-operator -n miguel
$ kubectl create clusterrolebinding kubeapps-operator --clusterrole=cluster-admin --serviceaccount=miguel:kubeapps-operator

# Access dashboard
$ export POD_NAME=$(kubectl get pods -n miguel -l "app=kubeapps,release=kubeapps" -o jsonpath="{.items[0].metadata.name}")
$ kubectl port-forward -n miguel $POD_NAME 8080:8080
```

### Post Installation

#### Issue 1: MongoDB does not start 

The replicaSet contains the following error.
> Warning  FailedCreate  <invalid> (x12 over <invalid>)  replicaset-controller  Error creating: pods "kubeapps-mongodb-67c5cf5fc5-" is forbidden: unable to validate against any security context constraint: [fsGroup: Invalid value: []int64{1001}: 1001 is not an allowed group]

It seems that the issue is with the fact that we set a security context in our MongoDB chart
  
https://github.com/bitnami/charts/blob/master/upstreamed/mongodb/values.yaml#L65-L68
  
Workaround: Removing that setting in the Values.yaml allowed MongoDB pods to be scheduled. We could override this setting in our kubeapps values.yaml file.
  
#### Issue 2: Get service account login token does not return anything

```bash
$ kubectl get secret $(kubectl get serviceaccount kubeapps-operator -o jsonpath='{.secrets[].name}') -o jsonpath='{.data.token}' | base64 --decode
$ kubectl get secret $(kubectl get serviceaccount kubeapps-operator -o jsonpath='{.secrets[].name}') -o jsonpath='{.data.token}' | base64 --decode
```
  
The Issue is because the service account by default contains two secret keys and we are accessing to the first one
```  
$ kubectl get serviceaccount kubeapps-operator -o jsonpath='{.secrets[*].name}'
=> kubeapps-operator-dockercfg-rr6hm kubeapps-operator-token-hvnfh
```
Workaround/Fix: Try to use regexp although it is only supported in jsonpath 1.12+. We could also try to get the last one instead of the first one (could not make it work either)

#### Issue 3: Initial import jobs are not created
  
In the repository controllers you can find:

```go
E1102 23:42:29.698459       1 controller.go:239] error syncing 'miguel/bitnami': cronjobs.batch "apprepo-sync-bitnami" is forbidden: cannot set an ownerRef on a resource you can't delete: User "system:serviceaccount:miguel:kubeapps-internal-apprepository-controller" cannot delete cronjobs.batch in project "miguel", <nil>
E1102 23:42:29.698811       1 controller.go:239] error syncing 'miguel/incubator': cronjobs.batch "apprepo-sync-incubator" is forbidden: cannot set an ownerRef on a resource you can't delete: User "system:serviceaccount:miguel:kubeapps-internal-apprepository-controller" cannot delete cronjobs.batch in project "miguel", <nil>
E1102 23:42:29.699992       1 controller.go:239] error syncing 'miguel/stable': cronjobs.batch "apprepo-sync-stable" is forbidden: cannot set an ownerRef on a resource you can't delete: User "system:serviceaccount:miguel:kubeapps-internal-apprepository-controller" cannot delete cronjobs.batch in project "miguel", <nil>
E1102 23:42:29.701056       1 controller.go:239] error syncing 'miguel/svc-cat': cronjobs.batch "apprepo-sync-svc-cat" is forbidden: cannot set an ownerRef on a resource you can't delete: User "system:serviceaccount:miguel:kubeapps-internal-apprepository-controller" cannot delete cronjobs.batch in project "miguel", <nil>
E1102 23:49:33.098667       1 controller.go:239] error syncing 'miguel/bitnami': cronjobs.batch "apprepo-sync-bitnami" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: User "system:serviceaccount:miguel:kubeapps-internal-apprepository-controller" cannot update apprepositories/finalizers.kubeapps.com in project "miguel", <nil>
```

It seems that the app-repository-controller role does not have enough permissions specifically missing:
  
* `delete` verb to `cronjob` and `job`
* `update` verb to `apprepository/finalizers` 


The workaround could be to edit the role `k edit role kubeapps-internal-apprepository-controller` being a working role something like:


```yaml
kubectl get role kubeapps-internal-apprepository-controller  -o yaml
apiVersion: authorization.openshift.io/v1
kind: Role
metadata:
  ...
rules:
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - batch
  attributeRestrictions: null
  resources:
  - cronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - batch
  attributeRestrictions: null
  resources:
  - jobs
  verbs:
  - create
  - delete
- apiGroups:
  - kubeapps.com
  attributeRestrictions: null
  resources:
  - apprepositories
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - kubeapps.com
  attributeRestrictions: null
  resources:
  - apprepositories/finalizers
  verbs:
  - get
  - list
  - update
  - watch
```

#### Issue 4: Port forward dies and k get pods returns connection refused  
When relying on a page that uses the Tiller proxy, the port-forward disconnects and even `kubectl get pods` returns that it can not connect to endpoint. we should look if the API server is crashing in a similar way it crashed here https://github.com/kubeapps/kubeapps/issues/676#issuecomment-431847392

TODO: Look if API server is crashing

**Comment by tommyreilly** [comment]
Hi all,

I'm trying to get kubeapps to run in OpenShift v3.11 running on GCP. I've seen the above observations and followed the suggestions from @migmartri and @prydonius. I think I'm close but I'm stuck with the below. I'm willing to work/test this if anyone else has further suggestions for me. I create routes for both the UI and the API and they both seem successful: 

**UI**

![image](https://user-images.githubusercontent.com/12903361/56083735-258fd800-5df7-11e9-95ec-e941467fdb1e.png)

The following javascript error(s) are referenced (unsure if they should be ignored):

![image](https://user-images.githubusercontent.com/12903361/56083818-05ace400-5df8-11e9-8657-fa5d587649a1.png)

**API**

![image](https://user-images.githubusercontent.com/12903361/56083674-3e4bbe00-5df6-11e9-8312-855fc93d9e83.png)

When I click on the catalog link, I get the spinning wheel (no javascript errors are reported):

![image](https://user-images.githubusercontent.com/12903361/56083671-2e33de80-5df6-11e9-8653-1444a7d91fc7.png)

When I click on the Service Instance (alpha) link, I get the following error message:

![image](https://user-images.githubusercontent.com/12903361/56083755-56700d00-5df7-11e9-8579-6eaea5346ac5.png)

The following javascript error(s) are referenced (unsure if they should be ignored):

![image](https://user-images.githubusercontent.com/12903361/56083797-e6ae5200-5df7-11e9-83a1-5920e4274a3e.png)

**Question 1: I assume I can use OpenShift routes (which uses a haproxy) and there is no dependency to use Ingress with a nginx/traefik ingress controller? Is there any specific annotations required for use with OpenShift routes that might be needed to be defined?** 

If you think that using an OpenShift router may be the problem I'm facing here and it is too much effort at this time to look into, should I consider using an nginx ingress controller (e.g. https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/openshift ** and use the following ingress in my ingress definition:

```
"nginx.ingress.kubernetes.io/rewrite-target": "/",
"nginx.ingress.kubernetes.io/ssl-redirect": "false"
```
I'd prefer to use standard OpenShift HAProxy router rather than to try the nginx ingress controller out, so asking the question first before going down this path.

Additional info - I have SecurityContext disabled in both the kubeapps and mongodb values.yaml and have rbac set to true in the kubeapps values.yaml.

I see all pods get successfully deployed and are running. I was seeing the same permission errors for the apprepository-controller as @migmartri mentioned in his Issue 3, but after using the suggested updated role, I see the initial apprepository sync(s) reporting success as follows:

```
W0413 17:32:33.750184       1 client_config.go:548] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
--
  | I0413 17:32:33.752709       1 controller.go:122] Setting up event handlers
  | I0413 17:32:33.752820       1 controller.go:164] Starting AppRepository controller
  | I0413 17:32:33.752833       1 controller.go:167] Waiting for informer caches to sync
  | I0413 17:32:33.853046       1 controller.go:172] Starting workers
  | I0413 17:32:33.853099       1 controller.go:178] Started workers
  | I0413 17:32:33.986050       1 controller.go:234] Successfully synced 'helm-kubeapps/incubator'
  | I0413 17:32:33.986675       1 event.go:221] Event(v1.ObjectReference{Kind:"AppRepository", Namespace:"helm-kubeapps", Name:"incubator", UID:"1d09444f-5e12-11e9-8801-42010a050509", APIVersion:"kubeapps.com/v1alpha1", ResourceVersion:"2705138", FieldPath:""}): type: 'Normal' reason: 'Synced' AppRepository synced successfully
  | I0413 17:32:34.052056       1 controller.go:234] Successfully synced 'helm-kubeapps/bitnami'
  | I0413 17:32:34.052526       1 event.go:221] Event(v1.ObjectReference{Kind:"AppRepository", Namespace:"helm-kubeapps", Name:"bitnami", UID:"1d0686ff-5e12-11e9-8801-42010a050509", APIVersion:"kubeapps.com/v1alpha1", ResourceVersion:"2705137", FieldPath:""}): type: 'Normal' reason: 'Synced' AppRepository synced successfully
  | I0413 17:32:34.099913       1 controller.go:234] Successfully synced 'helm-kubeapps/svc-cat'
  | I0413 17:32:34.100074       1 event.go:221] Event(v1.ObjectReference{Kind:"AppRepository", Namespace:"helm-kubeapps", Name:"svc-cat", UID:"1d0f3eed-5e12-11e9-8801-42010a050509", APIVersion:"kubeapps.com/v1alpha1", ResourceVersion:"2705140", FieldPath:""}): type: 'Normal' reason: 'Synced' AppRepository synced successfully
  | I0413 17:32:34.102320       1 controller.go:234] Successfully synced 'helm-kubeapps/stable'
  | I0413 17:32:34.102360       1 event.go:221] Event(v1.ObjectReference{Kind:"AppRepository", Namespace:"helm-kubeapps", Name:"stable", UID:"1d0c92d7-5e12-11e9-8801-42010a050509", APIVersion:"kubeapps.com/v1alpha1", ResourceVersion:"2705139", FieldPath:""}): type: 'Normal' reason: 'Synced' AppRepository synced successfully
  | W0413 17:40:34.861925       1 reflector.go:270] github.com/kubeapps/kubeapps/cmd/apprepository-controller/pkg/client/informers/externalversions/factory.go:74: watch of *v1alpha1.AppRepository ended with: The resourceVersion for the provided watch is too old.
  | W0413 17:42:15.880425       1 reflector.go:270] k8s.io/client-go/informers/factory.go:131: watch of *v1beta1.CronJob ended with: The resourceVersion for the provided watch is too old.
```

**Question 2: In the above log snippet, do I need to worry about either of:**

a) W0413 17:32:33.750184       1 client_config.go:548] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.

b) | W0413 17:40:34.861925       1 reflector.go:270] github.com/kubeapps/kubeapps/cmd/apprepository-controller/pkg/client/informers/externalversions/factory.go:74: watch of *v1alpha1.AppRepository ended with: The resourceVersion for the provided watch is too old.
  | W0413 17:42:15.880425       1 reflector.go:270] k8s.io/client-go/informers/factory.go:131: watch of *v1beta1.CronJob ended with: The resourceVersion for the provided watch is too old.

The only other error(s) I see in any of the other pod logs is in one of the two kubeapps that lists at the start:
```
Welcome to the Bitnami nginx container
--
  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-nginx
  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-nginx/issues
  |  
  | INFO  ==> nginx.conf not found. Applying bitnami configuration...
  | INFO  ==> Starting nginx...
  | 2019/04/13 17:32:40 [error] 26#0: *1 connect() failed (113: No route to host) while connecting to upstream, client: 10.127.2.1, server: _, request: "GET / HTTP/1.1", upstream: "http://172.30.239.163:8080/ ", host: "10.127.3.227:8080"
  | 10.127.2.1 - - [13/Apr/2019:17:32:40 +0000] "GET / HTTP/1.1" 502 173 "-" "kube-probe/1.11+"
  | 10.127.2.1 - - [13/Apr/2019:17:32:47 +0000] "GET / HTTP/1.1" 200 431 "-" "kube-probe/1.11+"
```

The other kubeapps pod shows no initial connection error:

```
Welcome to the Bitnami nginx container
--
  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-nginx
  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-nginx/issues
  |  
  | INFO  ==> nginx.conf not found. Applying bitnami configuration...
  | INFO  ==> Starting nginx...
  | 10.125.2.1 - - [13/Apr/2019:17:32:44 +0000] "GET / HTTP/1.1" 200 431 "-" "kube-probe/1.11+"
  | 10.125.2.1 - - [13/Apr/2019:17:32:54 +0000] "GET / HTTP/1.1" 200 431 "-" "kube-probe/1.11+"
```

**Question 3: Do I need to concern myself with the connection error in the first kubeapps pod above?**

I'm very keen to get this working and help others see kubeapps availability within an OpenShift cluster. Let me know if I can help in any way if there are further suggestions to try.

Thanks in advance

Tommy

**Comment by tommyreilly** [comment]
As an addendum to my prior comments, I've just realised that the UI is allowing access when any text is added into the token login screen.

Is something similar to https://github.com/kubeapps/kubeapps/issues/382 maybe happening for me also with the OpenShift router? The following is my OpenShift API router definition

![image](https://user-images.githubusercontent.com/12903361/56084392-87a10b00-5e00-11e9-815e-f48927a8b535.png)

I based my expectation of creating a router for the API too on the old monocular information. Looking at the ingress.yaml, I see only one rule defined. I assume, then, that I don't need to define a separate API router for kubeapps on OpenShift?

Thanks

Tommy

**Comment by tommyreilly** [comment]
Hi,

I'm trying to get kubeapps to run on OpenShift 3.11 on GCP. I've followed the information in this thread and the suggestions provided and made progress but am stuck now. I've very keen to get this working and thus if anyone has any suggestions, I'd be happy to try them out.

I have added the role suggestion by @migmartri as I was seeing the same errors as the listed Issue 3. It seems to do the trick. The log output I see is as follows:

```

W0413 21:16:01.626113       1 client_config.go:548] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
--
  | I0413 21:16:01.627725       1 controller.go:122] Setting up event handlers
  | I0413 21:16:01.627774       1 controller.go:164] Starting AppRepository controller
  | I0413 21:16:01.627785       1 controller.go:167] Waiting for informer caches to sync
  | I0413 21:16:01.728049       1 controller.go:172] Starting workers
  | I0413 21:16:01.728113       1 controller.go:178] Started workers
  | I0413 21:16:01.851480       1 controller.go:234] Successfully synced 'helm-kubeapps/incubator'
  | I0413 21:16:01.851960       1 event.go:221] Event(v1.ObjectReference{Kind:"AppRepository", Namespace:"helm-kubeapps", Name:"incubator", UID:"54a4cc76-5e31-11e9-88ba-42010a050408", APIVersion:"kubeapps.com/v1alpha1", ResourceVersion:"2748267", FieldPath:""}): type: 'Normal' reason: 'Synced' AppRepository synced successfully
  | I0413 21:16:01.853125       1 controller.go:234] Successfully synced 'helm-kubeapps/bitnami'
  | I0413 21:16:01.853275       1 event.go:221] Event(v1.ObjectReference{Kind:"AppRepository", Namespace:"helm-kubeapps", Name:"bitnami", UID:"54a09321-5e31-11e9-88ba-42010a050408", APIVersion:"kubeapps.com/v1alpha1", ResourceVersion:"2748266", FieldPath:""}): type: 'Normal' reason: 'Synced' AppRepository synced successfully
  | I0413 21:16:01.900043       1 controller.go:234] Successfully synced 'helm-kubeapps/svc-cat'
  | I0413 21:16:01.900164       1 event.go:221] Event(v1.ObjectReference{Kind:"AppRepository", Namespace:"helm-kubeapps", Name:"svc-cat", UID:"54ab456f-5e31-11e9-88ba-42010a050408", APIVersion:"kubeapps.com/v1alpha1", ResourceVersion:"2748269", FieldPath:""}): type: 'Normal' reason: 'Synced' AppRepository synced successfully
  | I0413 21:16:01.903700       1 controller.go:234] Successfully synced 'helm-kubeapps/stable'
  | I0413 21:16:01.903737       1 event.go:221] Event(v1.ObjectReference{Kind:"AppRepository", Namespace:"helm-kubeapps", Name:"stable", UID:"54a830ba-5e31-11e9-88ba-42010a050408", APIVersion:"kubeapps.com/v1alpha1", ResourceVersion:"2748268", FieldPath:""}): type: 'Normal' reason: 'Synced' AppRepository synced successfully
  | W0413 21:25:43.773846       1 reflector.go:270] k8s.io/client-go/informers/factory.go:131: watch of *v1beta1.CronJob ended with: The resourceVersion for the provided watch is too old.
```

**Question 1: Is the following message at the top of that log output a concern?**

W0413 21:16:01.626113       1 client_config.go:548] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.

**Question 2:  Is the following message at the top of that log output a concern?**

| W0413 21:25:43.773846       1 reflector.go:270] k8s.io/client-go/informers/factory.go:131: watch of *v1beta1.CronJob ended with: The resourceVersion for the provided watch is too old.

I don't see any errors in any other pod logs. However, when I access the UI via the OpenShift router I have created (pointing at the kubeapps service which is running on the default serviceport 80 as defined in the default values.yaml), I get a "There was an error connecting to the Kubernetes API. Please check that your token is valid." error message (see below). For testing purposes, I have defined a cluster-admin role as per the documentation and tried to login with either of the two secrets created for that user without success:

kubectl create serviceaccount kubeapps-operator
kubectl create clusterrolebinding kubeapps-operator --clusterrole=cluster-admin --serviceaccount=default:kubeapps-operator

![image](https://user-images.githubusercontent.com/12903361/56085442-63015f00-5e11-11e9-85e8-c519bd478284.png)

Any suggestions as to where I might go from here?

Thanks in advance.

Tommy

**Comment by tommyreilly** [comment]
Adding a bit more data to my prior comments.

When entering the (valid) kubeapps-operator token, the log output in the kubeapps pod is as follows:

```
10.126.2.1 - - [14/Apr/2019:21:50:03 +0000] "GET /api/kube/ HTTP/1.1" 200 4423 "https://kubeapps-helm-kubeapps.app.reito01.avengrsdev.cs.saas.ca.com/ " "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36"
10.126.2.1 - - [14/Apr/2019:21:50:03 +0000] "GET /api/kube/api/v1/namespaces HTTP/1.1" 200 16691 "https://kubeapps-helm-kubeapps.app.reito01.avengrsdev.cs.saas.ca.com/ " "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36"
10.126.2.1 - - [14/Apr/2019:21:50:03 +0000] "GET /api/tiller-deploy/v1/namespaces/default/releases HTTP/1.1" 401 217 "https://kubeapps-helm-kubeapps.app.reito01.avengrsdev.cs.saas.ca.com/ " "Mozilla/5.0 
```

So it seems that I was encountering a {"code":401,"message":"Unauthorized"} when the kubeapps pod code is trying to access /api/tiller-deploy/v1/namespaces/default/releases

So I got into the kubeapps pod and did a test:

```
$ pwd
cd /var/run/secrets/kubernetes.io/serviceaccount
$ ls
ca.crt  namespace  service-ca.crt  token
$ KUBE_TOKEN=`cat token`
$ curl -sSk -H "Authorization: Bearer $KUBE_TOKEN" https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_PORT_443_TCP_PORT/api/v1/namespaces/default/pods/$HOSTNAME
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "pods \"yodeling-snail-kubeapps-58d9bc9b96-j85r5\" is forbidden: User \"system:serviceaccount:helm-kubeapps:default\" cannot get pods in the namespace \"default\": no RBAC policy matched",
  "reason": "Forbidden",
  "details": {
    "name": "yodeling-snail-kubeapps-58d9bc9b96-j85r5",
    "kind": "pods"
  },
  "code": 403
}$
```

So, my interpretation here is that there is a need to provide the "default" serviceaccount in the namespace that I am deploying kubeapps to, appropriate rbac permissions to the "default" namespace. To simplify my investigation and save time in testing/debugging, I just created a cluster-admin ClusterRoleBinding for the default service account in my "helm-kubeapps" namespace.

I redeployed the app with this yaml in my updated chart and did the same test by getting into the kubeapps pod and validating that I can now access the default namespace with the curl command and thus run k8s API commands from the pod.

So I went to the UI and did the same test of using the valid kubeapps-operator token to login. However, my enthusiasm/optimism that it would now was temporary - the same "_There was an error connecting to the Kubernetes API_" error message was displayed and when I checked the kubeapps log, I saw the following:

```
10.126.2.1 - - [14/Apr/2019:23:25:31 +0000] "GET /api/kube/ HTTP/1.1" 200 4423 "https://kubeapps-helm-kubeapps.app.reito01.avengrsdev.cs.saas.ca.com/ " "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36"
10.126.2.1 - - [14/Apr/2019:23:25:31 +0000] "GET /api/kube/api/v1/namespaces HTTP/1.1" 200 16691 "https://kubeapps-helm-kubeapps.app.reito01.avengrsdev.cs.saas.ca.com/ " "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36"
10.126.2.1 - - [14/Apr/2019:23:25:31 +0000] "GET /api/tiller-deploy/v1/namespaces/default/releases HTTP/1.1" 401 217 "https://kubeapps-helm-kubeapps.app.reito01.avengrsdev.cs.saas.ca.com/ " "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36"_**
```
 
So looking into this latest 401 error from within the kubeapps pod:

```
$ curl -sSk -H "Authorization: Bearer $KUBE_TOKEN" https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_PORT_443_TCP_PORT/api/tiller-deploy/v1/namespaces/default/releases
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "the server could not find the requested resource",
  "reason": "NotFound",
  "details": {

  },
  "code": 404
}
```

i.e. there is no such endpoint _/api/tiller-deploy/v1/namespaces/default/releases_ . Am I missing something obvious? e.g. is there an _/api/tiller-deploy_ extension missing in my deployment?

```
curl -sSk -H "Authorization: Bearer $KUBE_TOKEN" https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_PORT_443_TCP_PORT
{
  "paths": [
    "/api",
    "/api/v1",
    "/apis",
    "/apis/",
    "/apis/admissionregistration.k8s.io",
    "/apis/admissionregistration.k8s.io/v1beta1",
    "/apis/apiextensions.k8s.io",
    "/apis/apiextensions.k8s.io/v1beta1",
    "/apis/apiregistration.k8s.io",
    "/apis/apiregistration.k8s.io/v1",
    "/apis/apiregistration.k8s.io/v1beta1",
    "/apis/apps",
    "/apis/apps.openshift.io",
    "/apis/apps.openshift.io/v1",
    "/apis/apps/v1",
    "/apis/apps/v1beta1",
    "/apis/apps/v1beta2",
    "/apis/authentication.k8s.io",
    "/apis/authentication.k8s.io/v1",
    "/apis/authentication.k8s.io/v1beta1",
    "/apis/authorization.k8s.io",
    "/apis/authorization.k8s.io/v1",
    "/apis/authorization.k8s.io/v1beta1",
    "/apis/authorization.openshift.io",
    "/apis/authorization.openshift.io/v1",
    "/apis/autoscaling",
    "/apis/autoscaling/v1",
    "/apis/autoscaling/v2beta1",
    "/apis/batch",
    "/apis/batch/v1",
    "/apis/batch/v1beta1",
    "/apis/build.openshift.io",
    "/apis/build.openshift.io/v1",
    "/apis/certificates.k8s.io",
    "/apis/certificates.k8s.io/v1beta1",
    "/apis/events.k8s.io",
    "/apis/events.k8s.io/v1beta1",
    "/apis/extensions",
    "/apis/extensions/v1beta1",
    "/apis/image.openshift.io",
    "/apis/image.openshift.io/v1",
    "/apis/kubeapps.com",
    "/apis/kubeapps.com/v1alpha1",
    "/apis/metrics.k8s.io",
    "/apis/metrics.k8s.io/v1beta1",
    "/apis/monitoring.coreos.com",
    "/apis/monitoring.coreos.com/v1",
    "/apis/network.openshift.io",
    "/apis/network.openshift.io/v1",
    "/apis/networking.k8s.io",
    "/apis/networking.k8s.io/v1",
    "/apis/oauth.openshift.io",
    "/apis/oauth.openshift.io/v1",
    "/apis/policy",
    "/apis/policy/v1beta1",
    "/apis/project.openshift.io",
    "/apis/project.openshift.io/v1",
    "/apis/quota.openshift.io",
    "/apis/quota.openshift.io/v1",
    "/apis/rbac.authorization.k8s.io",
    "/apis/rbac.authorization.k8s.io/v1",
    "/apis/rbac.authorization.k8s.io/v1beta1",
    "/apis/route.openshift.io",
    "/apis/route.openshift.io/v1",
    "/apis/scheduling.k8s.io",
    "/apis/scheduling.k8s.io/v1beta1",
    "/apis/security.openshift.io",
    "/apis/security.openshift.io/v1",
    "/apis/servicecatalog.k8s.io",
    "/apis/servicecatalog.k8s.io/v1beta1",
    "/apis/storage.k8s.io",
    "/apis/storage.k8s.io/v1",
    "/apis/storage.k8s.io/v1beta1",
    "/apis/template.openshift.io",
    "/apis/template.openshift.io/v1",
    "/apis/user.openshift.io",
    "/apis/user.openshift.io/v1",
    "/healthz",
    "/healthz/autoregister-completion",
    "/healthz/etcd",
    "/healthz/log",
    "/healthz/ping",
    "/healthz/poststarthook/apiservice-openapi-controller",
    "/healthz/poststarthook/apiservice-registration-controller",
    "/healthz/poststarthook/apiservice-status-available-controller",
    "/healthz/poststarthook/authorization.openshift.io-bootstrapclusterroles",
    "/healthz/poststarthook/authorization.openshift.io-ensureopenshift-infra",
    "/healthz/poststarthook/bootstrap-controller",
    "/healthz/poststarthook/ca-registration",
    "/healthz/poststarthook/generic-apiserver-start-informers",
    "/healthz/poststarthook/image.openshift.io-apiserver-caches",
    "/healthz/poststarthook/kube-apiserver-autoregistration",
    "/healthz/poststarthook/oauth.openshift.io-startoauthclientsbootstrapping",
    "/healthz/poststarthook/openshift.io-restmapperupdater",
    "/healthz/poststarthook/openshift.io-startinformers",
    "/healthz/poststarthook/openshift.io-webconsolepublicurl",
    "/healthz/poststarthook/project.openshift.io-projectauthorizationcache",
    "/healthz/poststarthook/project.openshift.io-projectcache",
    "/healthz/poststarthook/quota.openshift.io-clusterquotamapping",
    "/healthz/poststarthook/rbac/bootstrap-roles",
    "/healthz/poststarthook/scheduling/bootstrap-system-priority-classes",
    "/healthz/poststarthook/security.openshift.io-bootstrapscc",
    "/healthz/poststarthook/start-apiextensions-controllers",
    "/healthz/poststarthook/start-apiextensions-informers",
    "/healthz/poststarthook/start-kube-aggregator-informers",
    "/healthz/ready",
    "/metrics",
    "/oapi",
    "/oapi/v1",
    "/openapi/v2",
    "/swagger-2.0.0.json",
    "/swagger-2.0.0.pb-v1",
    "/swagger-2.0.0.pb-v1.gz",
    "/swagger.json",
    "/swaggerapi",
    "/version",
    "/version/openshift"
  ]
}
```

Thanks

Tommy

**Comment by andresmgot** [comment]
Hi @tommyreilly,

To clarify, when doing the request to `/api/tiller-deploy/v1/namespaces/default/releases` it will use the token that you set in the UI so it will be using the `kubeapps-operator` account, not the default one. I think that the issue you may be hitting is this: https://github.com/kubeapps/kubeapps/issues/676#issuecomment-431847392

To answer your specific question about the `404` that you are seeing, you need to use as hostname and port the one of the Ingress Controller in your cluster, not the hostname of the Kubernetes API server. It should be something like `curl -sSk -H "Authorization: Bearer $KUBE_TOKEN" https://kubeapps.local/api/tiller-deploy/v1/namespaces/default/releases`.

**Comment by tommyreilly** [comment]
Thanks @andresmgot for the speedy response. Let me dig in a bit deeper and confirm I'm hitting the same issue as that #676 and explore myself. If so, is there enough interest and patience at getting this issue resolved (i.e. has anyone else looked into this issue in any detail since it was raised). My company are locked into using OpenShift but we are getting a lot of asks from our end users for support of Helm charts. We can do this without the UI interface but for gaining more traction across stakeholders, we are keen to visualise kubeapps via our end users OpenShift cluster(s).

**Comment by treilly1969** [comment]
Wondering if this OpenShift issue/PR may be relevant?

https://github.com/openshift/ansible-service-broker/issues/427

https://github.com/openshift/ansible-service-broker/pull/995
