### ISSUE TITLE
Avoid default RBAC roles errors

### ISSUE THREAD

**Issue by andresmgot** [kubeapps/kubeapps#680]
Right now we have hardcoded in several places the required RBAC roles for the component we are rendering:

https://github.com/kubeapps/kubeapps/blob/24b840f735ca668122c24a0e7761b541c92d7a34/dashboard/src/components/Config/AppRepoList/index.tsx#L23

The current error handling for `Forbidden` errors are:

 - If the body of the error is a JSON blob parseable as a `RBACRole[]` use those roles. This happens for example with responses from tiller-proxy.
 - In other case, use the default RBAC roles hardcoded.

The problem with that approach is that we cannot assure that the hardcoded roles are actually the cause of the error (we don't know if the user already has those roles either). My suggestion is:

 - When the `Forbidden` error is not related to a K8s resource don't show any additional information in the error apart than "You don't have sufficient permissions to ... "
 - In other case, throw a valid `RBACRole[]` as the body of the error. If the server doesn't reply with a parseable format (for example when requesting k8s resources) we can obtain the required information from the request URL. For example a HTTP request to  `GET /api/kube/apis/kubeapps.com/v1alpha1/namespaces/kubeapps/apprepositories` indicates:

   - It's a K8s resource (since it starts with `/api/kube/`)
   - The API version is `kubeapps.com/v1alpha1`
   - The namespace is `kubeapps`
   - The verb is `get`
   - The resource requested is `apprepositories`

That way we ensure that the message shown to the user is really a role required.

The problem is that we would lose the ability to group required roles. For example, if a view request pods, deployments and services, the last one updating the redux store for the error is the one that will be shown to the user. In any case, that's a problem generic for the application and maybe it should be handled using `push` notifications. IMO that'd be out of the scope of this issue.

**Comment by prydonius** [comment]
> When the Forbidden error is not related to a K8s resource don't show any additional information in the error apart than "You don't have sufficient permissions to ... "

What Forbidden errors are not related to K8s resources?

> The problem is that we would lose the ability to group required roles. For example, if a view request pods, deployments and services, the last one updating the redux store for the error is the one that will be shown to the user.

One other option to look into here is using the SelfSubjectRulesReview API to pre-check for certain permissions before fetching things in specific views (e.g. in the apps view we could pre-check for ability to watch deployments, services, etc.) https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#selfsubjectrulesreview-v1beta1-authorization-k8s-io

**Comment by andresmgot** [comment]
> What Forbidden errors are not related to K8s resources?

At this point we don't have any, but there may be the case that a call to an external service returns a 503 (e.g. imagine that the `chartsvc` returns a 503 if the user tries to access a restricted repository). 

> One other option to look into here is using the SelfSubjectRulesReview API to pre-check ...

I see two problems trying to use `SelfSubjectRulesReview`:

 - We would need to reverse resolve the permissions to know if the user is able to perform a set of actions. This resolution is not trivial since we would need to resolve different API versions, wildcards, non-namespaced objects ... It's likely that we wouldn't get that right in the first try (unless we find an official library to do so which I think it's not available for javascript).
 - We would need to hardcode anyway the resources we think we need to use. That's also prompt to errors. For example, when creating an app repository we would check if the user has permissions to create an `apprepository` and a `secret` but actually the secret is not needed if the user doesn't specify the token. We can add logic to avoid that kind of situations but I think that is something complex to manage.

**Comment by absoludity** [comment]
This appears to have been implemented in the axios instance.
