### ISSUE TITLE
listing all classes, plans, instances and bindings in multiple views

### ISSUE THREAD

**Issue by prydonius** [kubeapps/kubeapps#683]
We are requesting all the Service Catalog API endpoints on a few of the pages even when they are not required and it would be enough to retrieve just the things we need (e.g. in the case below, just the Service Instances).

![screen shot 2018-09-05 at 16 30 32](https://user-images.githubusercontent.com/1544861/46110542-cccd5a80-c198-11e8-8e5b-2c50bec15ef9.png)

The reason for this is we are using the `getCatalog` action quite a bit instead of requesting individual resources: https://github.com/kubeapps/kubeapps/blob/master/dashboard/src/actions/catalog.ts#L212. We should remove this in favour of being more explicit.

**Comment by andresmgot** [comment]
The components that use the action `getCatalog` are: 

 - [ ] InstanceListView
 - [ ] ServiceList
 - [ ] InstanceView

Let's revamp each one of those in different PRs.
