### ISSUE TITLE
Service catalog card design doesn't match applications list

### ISSUE THREAD

**Issue by prydonius** [kubeapps/kubeapps#685]
![screen shot 2018-09-05 at 16 42 44](https://user-images.githubusercontent.com/1544861/46110654-3188b500-c199-11e8-9db1-7f30b0fd6e0d.png)

We should have a more consistent card layout

**Comment by andresmgot** [comment]
I am working on this (WIP). @prydonius what do you think of having it like:

<img width="918" alt="screen shot 2018-10-11 at 17 22 40" src="https://user-images.githubusercontent.com/4025665/46815675-aa803300-cd7b-11e8-85e4-3fa555e463ab.png">

The second tag is the latest status received (status.reason).

**Comment by prydonius** [comment]
@andresmgot lgtm, can we map those to better names though - e.g. Provisioning, Provisioned, Failed?

**Comment by arapulido** [comment]
It looks great! I agree with @prydonius' comment about using better names (and +1 with his suggestions)

**Comment by andresmgot** [comment]
I can use the same logic that sets the color to green/red to do that (but it's based in a regex)
