### ISSUE TITLE
Make Service instances page look more like the apps view

### ISSUE THREAD

**Issue by prydonius** [kubeapps/kubeapps#688]
![screen shot 2018-09-05 at 16 47 22](https://user-images.githubusercontent.com/1544861/46110841-c68bae00-c199-11e8-9be3-b4ecb121066d.png)

We should align it more with the Application view page

**Comment by andresmgot** [comment]
@prydonius can you send a mock of how you would like that to look like?

**Comment by prydonius** [comment]
@andresmgot feel free to be creative here, we would want to align it to how the same layout that the AppView page has.
