### ISSUE TITLE
Add an App Repository error

### ISSUE THREAD

**Issue by shibd** [kubeapps/kubeapps#690]
my kubeapps install namespace: kubeapps
but when my add an app repository 404, url:
http://10.116.18.145:30815/api/kube/apis/kubeapps.com/v1alpha1/namespaces/kubeapps1/apprepositories

nemespace error : kubeapps1
![image](https://user-images.githubusercontent.com/33416836/46142360-4a709380-c289-11e8-9298-96af8cca6cf9.png)

**Comment by andresmgot** [comment]
Hi @shibd,

The namespace in which Kubeapps is installed is stored in a ConfigMap in the namespace of Kubeapps. To retrieve what's the value stored there you can execute `kubectl get configmap -n kubeapps -o yaml <release_name>-internal-dashboard-config`. There there is a section with the configured namespace:

```
  config.json: |-
    {
      "namespace": "kubeapps"
    }
```

If that information is not correct, to try to reproduce the issue, have you upgraded/reinstalled Kubeapps changing the namespace?

**Comment by andresmgot** [comment]
I am glad you fixed that. I am closing this issue, please reopen it if you find any other issue.
