### ISSUE TITLE
Check support for Microsoft Edge

### ISSUE THREAD

**Issue by prydonius** [kubeapps/kubeapps#693]
File any issues that come up

**Comment by wojciechka** [comment]
@prydonius I'm happy to check it tomorrow

**Comment by wojciechka** [comment]
I went through Kubeapps in Edge and I did not find any issues with it. I used it to deploy a few things in a fresh cluster and everything was working properly.

**Comment by andresmgot** [comment]
thanks a lot @wojciechka! Closing this issue now then. Please reopen it if you find any issue.
