### ISSUE TITLE
Version mismatch between AppList and AppView pages

### ISSUE THREAD

**Issue by migmartri** [kubeapps/kubeapps#704]
![selection_722](https://user-images.githubusercontent.com/24523/46533532-39d1a600-c8a5-11e8-9883-67401bf8a05a.png)

**Comment by andresmgot** [comment]
Not sure if the same issue. I found a similar issue. After several upgrades, in the AppView and in the UpgradeForm I see the version `0.6.1` (marked as "current"). The real version and the one showed in the AppList view is 0.6.2.

**Comment by andresmgot** [comment]
My two cents is that at some point an upgrade didn't go well and tiller-proxy is returning that one that is "PENDING_UPGRADE" instead of the latest:

```
13      	Fri Oct  5 15:20:46 2018	PENDING_UPGRADE	kubeapps-0.6.1	Preparing upgrade
...
23      	Fri Oct  5 16:31:01 2018	SUPERSEDED     	kubeapps-0.6.1	Upgrade complete
24      	Fri Oct  5 16:32:57 2018	DEPLOYED       	kubeapps-0.6.2	Upgrade complete
```

**Comment by prydonius** [comment]
Hmm, also it looks like for the AppView ChartInfo we use the Helm Release object to get the version, whereas for the AppList we get it from the AppOverview object passed down from tiller-proxy (although tiller-proxy internally gets it from the Helm Release object also). So maybe as @andresmgot suggests, the release we're actually fetching is differing from ListReleases and GetRelease in the tiller-proxy. Good catch @migmartri!
