### ISSUE TITLE
Error 502 (Bad Gateway error) when upgrading Kubeapps

### ISSUE THREAD

**Issue by andresmgot** [kubeapps/kubeapps#705]
When upgrading Kubeapps using Kubeapps UI, if there is a change in the tiller-proxy image, the tiller-proxy pod is terminated before the upgrade action finishes. This causes Nginx to return a 502 (Bad Gateway error). After a refresh the application is upgraded.

We should avoid to terminate the `tiller-proxy` pod if there is a request in progress.

**Comment by prydonius** [comment]
We should look into making Tiller Proxy and asynchronous service, which should help us fix this issue also (created #710).
