### ISSUE TITLE
asynchronous operations in tiller-proxy

### ISSUE THREAD

**Issue by prydonius** [kubeapps/kubeapps#710]
Currently, each potentially long-running operation in tiller-proxy is synchronous (e.g. installing/upgrading/deleting charts). This requires the connection to be open long enough for an operation to be completed, which can take an indeterminate amount of time depending on the hooks a chart runs.

As a result, we haven't set any timeout settings in the axios http client (https://github.com/kubeapps/kubeapps/issues/619) and it also is not possible to have a good upgrade experience of Kubeapps from within Kubeapps as the tiller-proxy pod gets replaced and the connection is lost (https://github.com/kubeapps/kubeapps/issues/705).

If we moved to making these operations in tiller-proxy asynchronous, we would be able to have shorter request times to start and status operations. Also, since we will be polling for status, we won't have to rely on a single instance of tiller-proxy and so this should solve for #705.

In order to keep track of asynchronous operations, the operations and their state will need to be stored somewhere. We may also want to keep around historical operations for audit purposes, meaning a cache store may not be the best place for this. We have the option of storing this state in CRDs or in MongoDB. Another option is that tiller-proxy could start a Job for each operation, that way we can use Kubernetes and labels to track the operations without having to build a custom solution. We should consider:

- Are CRDs acceptable for storing this kind of state? There would be an object for each operation, and this could grow quite a lot
- If we opt for MongoDB, we may no longer claim it is a cache, and we may want to re-enable persistence
- If the operation is still handled inside tiller-proxy (i.e. instead of performed as a separate Job), how do we deal with ensuring a current operation is completed before a tiller-proxy instance is terminated?

What do you think @kubeapps/maintainers?

**Comment by andresmgot** [comment]
thanks @prydonius for taking the time to write this down!

I think we don't need to take care of storing the state of the operation. When an installation/upgrade/deletion takes place, the configmap (or secret) storing the data of the release includes the current status (`release.Status_DELETING`, `release.Status_PENDING_INSTALL`, `release.Status_PENDING_UPGRADE`). We can just show that status in the AppView.

**Comment by andresmgot** [comment]
> it will always wait for hooks to complete. Is this possible with the gRPC client?

You are right. I thought there was an option to just send the request and don't wait but it doesn't seem possible: https://github.com/helm/helm/issues/3427. We could close the connection ourselves and that will work but we wouldn't know if there is an error with the request (since error details are not stored in the release info). Spinning a job per install/upgrade/deletion would be a bit difficult as well since it would need to handle the TLS connection/Network policies if they exist. I don't really like none of those options.

I think the less-bad approach would be:
 - In tiller-proxy: have a timeout of 30s (default grace period) for connections with tiller. That's time more than enough to discover if there are errors with the request. After that period we could return a `204 No Content` to the user.
 - In tiller-proxy: avoid to end the process if there is a connection open. We can do that catching the TERM signal.
 - In the dashboard (optional): If the tiller-proxy returns a 204 maybe we should show a warning message: "the request is taking too long"?

**Comment by andresmgot** [comment]
> That said, external Jobs are going to be more difficult to manage

Yes, that's what I mean. It's something possible but I don't really like the idea because it's too complex.

> Will Tiller cancel/fail an operation if the gRPC connection is closed mid-way?

It won't. You can check that running `helm install bitnami/kubeapps` and then `Control+C`. The connection is closed but the chart is properly installed.

**Comment by migmartri** [comment]
Thank you both for the writeup and discussion.

There are a couple of things that I'd like to dig into, one of them is for simplicity sake to try to separate the discussion per service(s) interaction, dashboard<->Tiller proxy / Tiller-proxy<->Tiller.

The other thing that I'd like to understand better is why tiller-proxy exists almost instantly when it receives SIGTERM, if we change this behavior so it does not exits instantly but only once the current operation is finished (or gets SIGKILL), we will potentially not have the downtime described here https://github.com/kubeapps/kubeapps/issues/705.

Note that the signal handling change is orthogonal to make the communication async, and even applying it to only ` dashboard<->Tiller proxy` is an improvement in my opinion (assuming that the dashboard will ask for the status of a release and the ConfigMap was updated with a transient status `release.Status_PENDING_INSTALL` as @andresmgot suggested)

**Comment by prydonius** [comment]
We should look into adding a terminationGracePeriod or something in tiller-proxy to allow it to properly finish processes.

**Comment by andresmgot** [comment]
> We should look into adding a terminationGracePeriod or something in tiller-proxy to allow it to properly finish processes.

Yes, but that would be a different issue, should we rename this one or create a different one?

**Comment by andresmgot** [comment]
Oh, I see that #705 is already there. I guess it's fine for now.
