### ISSUE TITLE
We need an easy way to edit the values.yaml of the chart dependencies

### ISSUE THREAD

**Issue by arapulido** [kubeapps/kubeapps#733]
When deploying a chart through Kubeapps, there is a very visual way to edit the values.yaml for the main chart, but nothing for the dependencies.

It would be good to be able to edit the values.yaml of the dependencies in the same way.

We would need to think the best UX for this

**Comment by absoludity** [comment]
This is possible in [helm itself](https://helm.sh/docs/chart_template_guide/subcharts_and_globals/#overriding-values-from-a-parent-chart) as well as with simple forms.
