### ISSUE TITLE
Error: namespaces "kubeapps" is forbidden: User "system:serviceaccount:kube-system:default" ...

### ISSUE THREAD

**Issue by natiki** [kubeapps/kubeapps#736]
Hi,

I am sure this a noob question :-). I have now moved off Minikube and am trying to get KubeApps going on an Ubuntu install. I installed the master node using the following https://blog.alexellis.io/your-instant-kubernetes-cluster/ in Ubuntu 18.04.1 LTS.

I installed helm using the standard installation instructions from Helm namely:

```
$ curl https://raw.githubusercontent.com/helm/helm/master/scripts/get > get_helm.sh
$ chmod 700 get_helm.sh
$ ./get_helm.sh
$ helm init
```
However as soon as I run:

`helm install --name kubeapps --namespace kubeapps bitnami/kubeapps`

I get the following error:

> Error: namespaces "kubeapps" is forbidden: User "system:serviceaccount:kube-system:default" cannot get resource "namespaces" in API group "" in the namespace "kubeapps"

Now to my knowledge I have not installed Helm securely. So how do I get around the above error?

**Comment by andresmgot** [comment]
@natiki your cluster has RBAC enabled and the default user doesn't have permissions enough to create resources in other namespaces. You should be able to install Kubeapps if you initialize helm with a privileged service account. Check this thread for a possible solution: https://github.com/kubeapps/kubeapps/issues/667#issuecomment-423663944

**Comment by bshetti** [comment]
I am also getting "Error: namespaces "default" is forbidden: User "system:serviceaccount:kube-system:default" cannot get resource "namespaces" in API group "" in the namespace "default"" But I am using AKS - how do I add a Privileged service account into AKS cluster to make this work?

**Comment by absoludity** [comment]
Hi there @bshetti . Creating a privileged service account for tiller in an AKS cluster should not be any different than it is for other clusters - which is what the related [Microsoft docs also seem to say](https://docs.microsoft.com/en-us/azure/aks/kubernetes-helm#create-a-service-account)?

Let me know if you are following those instructions from MS for helm on AKS? If you can still reproduce with those instructions, I'll try to reproduce here and dig some more. Hope that helps!

**Comment by andresmgot** [comment]
Closing this already due to inactivity
