### ISSUE TITLE
Document tiller installation issues in chart troubleshoot section

### ISSUE THREAD

**Issue by migmartri** [kubeapps/kubeapps#737]
Add a section in the Kubeapps chart troubleshoot that covers issues with tiller installation due to RBAC miss configuration, see https://github.com/kubeapps/kubeapps/issues/731

**Comment by prydonius** [comment]
There is already a section that references the "attempt to grant extra privileges" error (https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps#forbidden-error-while-installing-the-chart) which currently suggests turning off RBAC. We can extend it to have 2 solutions based on whether the cluster has RBAC enabled or not. If RBAC is enabled, we can explain how to install Tiller with a service account (or just point to the Helm Tiller RBAC docs), and describe the `rbac.create=false` option if RBAC is disabled.

**Comment by andresmgot** [comment]
I think we can assume that RBAC is always enabled. Ideally we should point to the helm docs but I think they are a bit long. A TLDR section just setting the service account and the role binding would help.

**Comment by migmartri** [comment]
I agree that we can re-use that section but as @andresmgot  assume that the most common case is RBAC enabled and show something like https://gist.github.com/mgoodness/bd887830cd5d483446cc4cd3cb7db09d at the top.

I am ok adding at the bottom that there is also the possibility that RBAC is not enabled and the chart needs to be installed taking that into account.
