### ISSUE TITLE
View values file used for application release

### ISSUE THREAD

**Issue by dac88** [kubeapps/kubeapps#739]
Hi,

When clicking on an application release, it would be useful to be able to view the current values that were used to deploy the chart.

For a user browsing a production enviornment, being able to view the values file that was used to deploy the chart would be informative for checks and debugging.

Thanks,
Dean.

**Comment by andresmgot** [comment]
Hi @dac88, thank you for your suggestion, we will evaluate it.

Apart from that, you can achieve what you want if you click in "Upgrade" button. In the menu that lets you select a version, when the current one is selected you can see the values of the current release. It's not meant to be used that way but at least you have a way to see that.

**Comment by prydonius** [comment]
@dac88 would you be able to provide some more info about your usecase here? Does the upgrade page solve it?
