### ISSUE TITLE
Refactor/test remaining Service Catalog code

### ISSUE THREAD

**Issue by andresmgot** [kubeapps/kubeapps#743]
The following code should be refactored and at least covered by some basic unit tests before 1.0:

- Actions:
  - [X] catalog
- Components:
  - Config
    - [x] ServiceBrokerList
    - [x] ServiceCatalog
  - [X] ServiceClassList
  - ServiceClassView
    - [x] ProvisionButton
    - [x] ServiceClassView
  - ServiceInstanceList
    - [X] ServiceInstanceCard
    - [X] ServiceInstanceList
  - ServiceInstanceView
    - [x] AddBindingButton
    - [x] DeprovisionButton
    - [X] ServiceInstanceView
- Containers (unit testing is not required):
   - [X] ServiceCatalogContainer
   - [X] ServiceClassListContainer
   - [x] ServiceClassViewContainer
   - [X] ServiceInstanceListContainer
   - [X] ServiceInstanceViewContainer

**Comment by andresmgot** [comment]
Regarding remaining items in the list. The most important items left are `ServiceClassView` and `ServiceClassViewContainer`. For those components, apart than writing unit test we should do similar changes than in #746. We should:

 - Add the loading wrapper (to wait until the classes are loaded)
 - Use the ErrorSelector to represent errors.
 - Change the format of the cards to be consistent with the rest (using `InfoCard`)

For the rest of components:

 - `ProvisionButton` and `AddBindingButton` require to use the ErrorSelector.
 - `DeprovisionButton` only requires unit tests.

**Comment by andresmgot** [comment]
All the components have now a minimum coverage and include the latest common components. Closing this.

**Comment by prydonius** [comment]
woot, great work @andresmgot!
