### ISSUE TITLE
How to display service information under the details list

### ISSUE THREAD

**Issue by shibd** [kubeapps/kubeapps#747]
![image](https://user-images.githubusercontent.com/33416836/47200437-bfc31600-d3a8-11e8-9d8e-d6ff2ce699ef.png)
After I posted a chart, why doesn't the service information appear under my details list?
Thanks!

**Comment by shibd** [comment]
How do I need to write charts to see this service information?

**Comment by shibd** [comment]
The picture above is the official website.

**Comment by shibd** [comment]
![image](https://user-images.githubusercontent.com/33416836/47200674-aff80180-d3a9-11e8-94d8-6ea671ab7239.png)
Is my kubeapps have problems

**Comment by migmartri** [comment]
hi @shibd,

I am not sure I fully understand the question, is the issue that the `clusterIP` column shows "None"? (see attached image)

![selection_726](https://user-images.githubusercontent.com/24523/47205541-824d9100-d386-11e8-87d1-5e8214aa6c39.png)

In that case, at least in my installation, it seems that K8s is not provisioning a cluster IP for those services:

```bash
$kubectl get svc -l app=aerospike
NAME                                    TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)             AGE
miguel-test-aereospike-aerospike        ClusterIP   None         <none>        3000/TCP,3002/TCP   10m
miguel-test-aereospike-aerospike-mesh   ClusterIP   None         <none>        3002/TCP            10m
```

Could you verify that's your case?

Thanks!

**Comment by shibd** [comment]
Thank you very much for your answer.I am not expressing it right.
Is my own configured proxy is not equipped with websocket.
So the page connection error, can not see the service and other information

**Comment by andresmgot** [comment]
Hi @shibd, 

In the "Details" section you will see "Services", "Deployments" and "Other resources". Those are parsed from the Chart manifest so as far as a Chart has one of those resources you should be able to see them in the UI.

The web socket error is something different. Apparently you don't have permissions to `watch` those resources in your cluster. In any case that's not mandatory, the only thing that happens with that is that you won't see changes in the "Details" section until you refresh the page.

**Comment by shibd** [comment]
Thanks, It's because I changed the error caused by kubeapps chart definition,I have solved it,This problem can be closed.

**Comment by andresmgot** [comment]
I'm glad you solved the issue. Closing this!
