### ISSUE TITLE
Clicking on a deleted application, that shares part of the name with a deployed app, goes to the one that is not deleted

### ISSUE THREAD

**Issue by arapulido** [kubeapps/kubeapps#756]
Steps to reproduce:

* Create a release called `wordpress`. Deploy and delete it (without purging)
* Create a release called `wordpress2`. Deploy it.
* Go to Applications, and click on `Show deleted apps`
* Click on the one called `wordpress`

Expected results:
It shows the application view of the app called `wordpress`

Actual results:
It shows the application view of the app called `wordpress2`

<img width="842" alt="screen shot 2018-10-23 at 11 01 36 am" src="https://user-images.githubusercontent.com/925437/47349576-310a0e00-d6b4-11e8-85f0-7f799755673b.png">

**Comment by andresmgot** [comment]
Closing this as a dup of #765
