### ISSUE TITLE
Add icon/text indicating app format in card views

### ISSUE THREAD

**Issue by prydonius** [kubeapps/kubeapps#762]
Add an icon or text for Helm and Service Instances that appears in the cards so users can easily distinguish between them. This will become important if we merge the Service Instances into the Apps list and Classes in the Catalog list.

**Comment by prydonius** [comment]
@arapulido I think this can probably way till post-1.0, what do you think?

**Comment by arapulido** [comment]
I agree

**Comment by absoludity** [comment]
Already done in the new UI.
