### ISSUE TITLE
Remove Service Binding pane in deployment/upgrade forms

### ISSUE THREAD

**Issue by prydonius** [kubeapps/kubeapps#763]
The Service Binding pane in the deployment/upgrade forms is confusing and promotes a specific workflow for using the Service Catalog that we are not sure is correct. It was added for making Service Catalog demos easier with the charts we have today, but as we move to a more stable product, it no longer makes sense to include this workaround.

**Comment by prydonius** [comment]
@arapulido do you think we can include this in the 1.0 milestone?

**Comment by arapulido** [comment]
Yes, I think we should remove it from 1.0. Let's add it
