### ISSUE TITLE
New app deployment not updating 

### ISSUE THREAD

**Issue by migmartri** [kubeapps/kubeapps#766]
The application deployment page stays in "Deploying" state and also shows a stale view of the deployment table as shown below.

![selection_731](https://user-images.githubusercontent.com/24523/47425641-41d98300-d78b-11e8-857b-3b025753b417.png)

We need to check the websocket watchers in that and other pages.

**Comment by andresmgot** [comment]
Yes, at some point the web socket that is supposed to receive updates gets stuck, we should investigate why.

**Comment by migmartri** [comment]
It seems that the websockets connection closes (finishes) after 1 minute.

![selection_746](https://user-images.githubusercontent.com/24523/48102101-4c116d80-e1de-11e8-8a9e-871ed519f8e7.png)
