### ISSUE TITLE
Formatting Error - "You need to enable JavaScript to run this app"

### ISSUE THREAD

**Issue by dac88** [kubeapps/kubeapps#768]
Hi,

Occasionally the Kubeapps page will not display correctly, the formatting seems to lose it's style sheet.

In the chrome tools i see this message;

```<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no"><meta name="theme-color" content="#000000"><link rel="manifest" href="/manifest.json"><link rel="icon" type="image/png" href="/favicon-196x196.png" sizes="196x196"/><link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32"/><link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16"/><link rel="icon" type="image/png" href="/favicon-128.png" sizes="128x128"/><title>Kubeapps Dashboard</title><link href="/static/css/main.9dfddeab.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div><script type="text/javascript" src="/static/js/main.0a79f720.js"></script></body></html>```

Has anybody seen this problem before?

Thanks,
Dean.

**Comment by andresmgot** [comment]
Hi @dac88,

It seems that it's not properly redirecting some resources. How are you accessing the application? Are you exposing it with an ingress object or directly with a port-forward?
