### ISSUE TITLE
Search does not display all charts

### ISSUE THREAD

**Issue by gintautassulskus** [kubeapps/kubeapps#779]
Search for a `jenkins` chart in https://hub.kubeapps.com/charts.
The search result will contain only one jenkins chart  from bitnami although there is jenkins  from `stable` as well.

**Comment by prydonius** [comment]
This was a bug in [http://github.com/helm/monocular](Monocular) that is now fixed. We plan to update Kubeapps Hub soon, but in the meantime you can use the search in the stable repo page: https://hub.kubeapps.com/charts/stable.

FYI the correct repo to file issues related to the Hub is in https://github.com/kubeapps/hub, feel free to re-file this issue there until we update it to the new release of Monocular.

**Comment by gintautassulskus** [comment]
Thanks, @prydonius. Closing this issue and reopening a new one in https://github.com/kubeapps/hub
