### ISSUE TITLE
Remove namespace from tiller-proxy API routes

### ISSUE THREAD

**Issue by migmartri** [kubeapps/kubeapps#783]
Once https://github.com/kubeapps/kubeapps/pull/782 is landed, the namespace passed to tiller-proxy in the route is not longer used so we can remove.

We need to update those routes and remove the namespace fragment.

**Comment by migmartri** [comment]
It seems that the namespace is actually used in all cases but there are places in which the namespace can be inferred from the release.

For example, during upgrade, instead of 1) Checking that we can upgrade in the passed namespace and 2) the namespace of the release is the same one than the one passed, we can just assume that the namespace in where you are going to upgrade is the one where the release is deployed on.

That said, I do not think this is important since it does not affect the current functionality.

**Comment by absoludity** [comment]
> That said, I do not think this is important since it does not affect the current functionality.

And more importantly, having the namespace in the route is useful for navigating directly to certain namespaces in Kubeapps from a link (ie. not depending on state).
