### ISSUE TITLE
Start using HEx-react package

### ISSUE THREAD

**Issue by Angelmmiguel** [kubeapps/kubeapps#789]
Yesterday we've released [HEx v4.0.0](https://github.com/bitnami/hex/releases/tag/v4.0.0). It comes with a new [hex-react](https://www.npmjs.com/package/@bitnami/hex-react) package. Currently, it only includes the most basic component, but we will be adding more components.

You can find the documentation in <https://design.bitnami.com/react/>. However, it's still under heavy development.

**Comment by absoludity** [comment]
No longer using hex.
