### ISSUE TITLE
kubeapps dashboard cmd misc improvements

### ISSUE THREAD

**Issue by migmartri** [kubeapps/kubeapps#79]
If you run `kubeapps dashboard` before kubeapps has been initialized, the message you get is:

```
$ kubeapps dashboard
ERRO[0000] nginx ingress controller pod not found, run kubeapps up first 
```

In my opinion this message should be more user friendly, hiding the implementation details on how we detect it. So just say something like `kubeapps not initialized, run kubeapps up first`

The second issue is that checking that a pod with label `name=nginx-ingress-controller` in that namespace might not be enough to decide if kubeapps is initialized and running or not. We could think on having some kind of healthcheck or even relying on the existing ones. That could also help to achieve #45 if we want to.

**Comment by prydonius** [comment]
Yeah I think this is a good idea. I was also thinking that we could ship our own default backend so we could have a loading message even when the ingress controller is ready but the UI isn't.

**Comment by prydonius** [comment]
Closing as not too relevant/important. We'll soon be moving to a Helm chart based install.
