### ISSUE TITLE
Ingress controller

### ISSUE THREAD

**Issue by migmartri** [kubeapps/kubeapps#80]
Is there any way to configure the ingress controller service to for example be exposed via ELB/NodePort at deployment time? If not, what's the recommended way to do it?

Would it make sense to allow user to choose an existing an existing ingress controller?

**Comment by prydonius** [comment]
Currently no, but we will make it configurable later, but IMO we should wait until we have a good authentication model.

Using an existing ingress controller is an interesting idea, the only issue is that some controllers don't fully support the annotations we might need. How useful do you think this would be?

**Comment by prydonius** [comment]
Closing as we no longer use an Ingress controller and just deploy a single nginx pod.
