### ISSUE TITLE
Review upgrading AppRepository CRD version to v1

### ISSUE THREAD

**Issue by prydonius** [kubeapps/kubeapps#803]
It is currently at v1alpha1 and the 1.0 release might be a good time to bump this to v1.

**Comment by prydonius** [comment]
We're going to push this back for the 1.0 release as it's not vital. We should be able to include it in a future minor release. Regardless of the current version, the AppRepository spec can be considered stable.

**Comment by prydonius** [comment]
We should figure out how much of an impact this would be for users to upgrade.

**Comment by andresmgot** [comment]
Closing this in favor of #814. I will post my findings there.
