### ISSUE TITLE
Cannot list cronjobs.batch at the cluster scope

### ISSUE THREAD

**Issue by SilenceHVK** [kubeapps/kubeapps#805]
According to the official documentation to install kubeapps-0.9.5, the following problems occur:

```
k8s.io/client-go/informers/factory.go:131: Failed to list *v1beta1.CronJob: cronjobs.batch is forbidden: User "system:serviceaccount:kubeapps:kubeapps-internal-apprepository-controller" cannot list cronjobs.batch at the cluster scope
```

I don't kown how to solve it.

**Comment by SilenceHVK** [comment]
resolved

**Comment by prydonius** [comment]
@SilenceHVK what was the issue in the end? kubeapps-0.9.5 should not require the cluster scope for cronjobs, as it should just be watching the kubeapps namespace.

**Comment by prydonius** [comment]
Reopening and this looks like a bug, the cluster scope should no longer be required. Looking into it.

**Comment by prydonius** [comment]
@SilenceHVK just released a new version of the chart that should fix this (0.9.7), can you give it a try?

**Comment by SilenceHVK** [comment]
OK

**Comment by SilenceHVK** [comment]
@prydonius I have changed the 0.9.7 version and this problem has not occurred. Thank you very much.

**Comment by andresmgot** [comment]
Thanks for confirming! Closing this issue now.
