### ISSUE TITLE
Refactor ServiceInstanceView/ServiceClassView to only fetch relevant ClusterServiceClass and ClusterServicePlan

### ISSUE THREAD

**Issue by prydonius** [kubeapps/kubeapps#806]
Currently, we are fetching all classes and plans in the ServiceInstanceView component and filtering them by the currently selected ServiceInstance:

https://github.com/kubeapps/kubeapps/blob/e85450e9695a985e97422f3c44074f057df70531/dashboard/src/components/ServiceInstanceView/ServiceInstanceView.tsx#L88-L89

https://github.com/kubeapps/kubeapps/blob/e85450e9695a985e97422f3c44074f057df70531/dashboard/src/components/ServiceInstanceView/ServiceInstanceView.tsx#L141-L148

https://github.com/kubeapps/kubeapps/blob/e85450e9695a985e97422f3c44074f057df70531/dashboard/src/components/ServiceInstanceView/ServiceInstanceView.tsx#L153-L159

If we have the clusterServiceClassRef and clusterServicePlanRef, we should just be able to make a direct call to the k8s API for the specific class and plan we need to display, reducing the scope needed for the API call and making the processing simpler on the frontend.

**Comment by prydonius** [comment]
It looks like we're also fetching all instances, when we should just be fetching the requested instance.

**Comment by andresmgot** [comment]
Modified the title to also include the ServiceClassView that present the same issue.
