### ISSUE TITLE
Documentation for uninstall or update

### ISSUE THREAD

**Issue by obeyler** [kubeapps/kubeapps#807]
During update version 0.8 to 0.9.5 
the update failed due to config map existance :
![image](https://user-images.githubusercontent.com/23224162/48406031-c9cffe80-e733-11e8-9ef3-3aa25de6d5f5.png)

helm upgrade --install  --debug --version=0.9.5 --namespace kubeapps kubeapps bitnami/kubeapps  -f kubeapps.yml
Error: configmaps "kubeapps-internal-apprepository-jobs-bootstrap" already exists   

May you should add a warning into the documentation for updating or deleting helm chart
that we also need to delete the config map

![image](https://user-images.githubusercontent.com/23224162/48406292-5e3a6100-e734-11e8-9ab5-dd87dbec202d.png)

**Comment by prydonius** [comment]
@obeyler hmm, that configmap should not exist if the bootstrap completed successfully the first time (it has the `helm.sh/hook-delete-policy: hook-succeeded` annotation which will cause Tiller to delete it **if** it succeeded). Perhaps it didn't complete successfully the first time?

It might make sense to add this to the troubleshooting section though: https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps#troubleshooting
