### ISSUE TITLE
kubeapps dashboard dynamic local port allocation

### ISSUE THREAD

**Issue by migmartri** [kubeapps/kubeapps#82]
Instead of relying on a hardcoded port 8002 for port forwarding, we might want to detect a free local port. I've seen this approach implemented [here](https://github.com/kubernetes/helm/blob/16571305bbe9496635ad518d643c1a8a8f3e2c18/pkg/kube/tunnel.go#L106)

**Comment by prydonius** [comment]
I picked 8002 because `kubectl proxy` uses 8001, but I agree that picking a free port might be better. Thanks for the pointer.

**Comment by ngtuna** [comment]
I agree with @migmartri That would be better to dynamically assign an available local port. Kubeless used to do it before
