### ISSUE TITLE
Add e2e GKE test for k8s 1.11

### ISSUE THREAD

**Issue by prydonius** [kubeapps/kubeapps#822]
We should test on 1.11 in addition to 1.9 and 1.10. We should also update our docs to mention what we support (1.9, 1.10, 1.11)

**Comment by prydonius** [comment]
It looks like the 1.10 branch is actually picking up a 1.11 cluster (that's what we saw when we SSH'd in the circle node)

**Comment by andresmgot** [comment]
> It looks like the 1.10 branch is actually picking up a 1.11 cluster (that's what we saw when we SSH'd in the circle node)

TIL that when using a number `1.10` in a YAML file is considered a decimal so it's translated to `1.1`:

```
> yaml.safeLoad("a: 1.10")
{ a: 1.1 }
```
