### ISSUE TITLE
OpenShift: Get service account login token instructions are invalid

### ISSUE THREAD

**Issue by migmartri** [kubeapps/kubeapps#842]
In our instructions to retrieve the kubeapps-operator login we state

```bash
$ kubectl get secret $(kubectl get serviceaccount kubeapps-operator -o jsonpath='{.secrets[].name}') -o jsonpath='{.data.token}' | base64 --decode
```

This, in the case of OS does not return anything because the service account actually has two secrets associated and the first one IS NOT a pointer to the token

```bash
$ kubectl get serviceaccount kubeapps-operator -o jsonpath='{.secrets[*].name}'
=> kubeapps-operator-dockercfg-rr6hm kubeapps-operator-token-hvnfh
```

We can try to get the proper one by using jsonpath + regexp although it is only supported in jsonpath 1.12+. We could also try to get the last one instead of the first one.

The last resort could be to document the difference.

**Comment by absoludity** [comment]
jsonpath + regexp isn't supported in kubectl - https://github.com/kubernetes/kubernetes/issues/61406

but templating to output the secrets on multiple lines together with grep works fine. I'll do a quick PR with that after verifying it works fine with plain k8s.
