### ISSUE TITLE
Refactor table views

### ISSUE THREAD

**Issue by andresmgot** [kubeapps/kubeapps#848]
We have several views in which we render tables like the Services, Deployments, Secrets, etc. of the AppView or the bindings in the ServiceView. Each of them has mostly the same component that represents the table but changing the columns content. We can create a generic component out of it.

I think we should also review the representation, I think that having a single box with different tabs for showing the different tables will provide a better UX in some cases (like the app resources).

**Comment by prydonius** [comment]
I also think we may want to revisit whether we want tables in certain cases, there may be better ways to display some of the information we're showing.

**Comment by andresmgot** [comment]
Yes, but probably to display better information we may need more metadata from the chart (like knowing which secrets are credentials). In any case, I think that having raw information about all the resources for an app is something useful. Advanced users/developers can use that to see what's going on.

**Comment by prydonius** [comment]
> Advanced users/developers can use that to see what's going on.

Potentially, but I would see that level of detail as a cluster operator concern, not an app dev concern. I think it's useful to have it in a different tab for advanced info, but it should not be in the default view. Anyway, I think I'm getting away from the point of this issue, which is to create a common component we can reuse for similar views, which I do think is valuable for when we do want to show tabular information.

We may want to look at if there are any React components out there that make showing tabular data easier.

**Comment by lindhe** [comment]
My Secrets table looks broken. Does this belong here, or should I open a new issue?

It seems to be some trouble with the flex class, but I know little about HTML/CSS...

![Screenshot from 2019-08-02 15-05-35](https://user-images.githubusercontent.com/7773090/62372194-1d3ee280-b537-11e9-8098-9dabd43a18be.png)

**Comment by andresmgot** [comment]
yes @lindhe, that seems like a bug. Do you mind opening a different PR? we can fix the style there.

**Comment by absoludity** [comment]
New UI has app resources in a standard table with tabs.
