### ISSUE TITLE
Kubeapps v1 dashboard "Sorry! Something went wrong" when going into Configuration

### ISSUE THREAD

**Issue by trenb** [kubeapps/kubeapps#851]
Installed version 1 with the instructions at https://github.com/kubeapps/kubeapps

All the pods are running properly:
```
# kubectl get pods -n kubeapps
NAME                                                          READY   STATUS      RESTARTS   AGE
apprepo-sync-bitnami-l7fdr-dkjvl                              0/1     Completed   2          21m
apprepo-sync-incubator-wx87k-gw4td                            0/1     Completed   2          21m
apprepo-sync-stable-jcjq2-hhss4                               0/1     Completed   2          21m
apprepo-sync-svc-cat-c8kcm-ztmzj                              0/1     Completed   2          21m
kubeapps-769bc4c7b6-bl7st                                     1/1     Running     0          21m
kubeapps-769bc4c7b6-l8smm                                     1/1     Running     0          21m
kubeapps-internal-apprepository-controller-7b954598b9-5wdj5   1/1     Running     0          21m
kubeapps-internal-chartsvc-8b95b497f-lkwvb                    1/1     Running     2          21m
kubeapps-internal-chartsvc-8b95b497f-mlzkf                    1/1     Running     2          21m
kubeapps-internal-dashboard-64c7586bd7-hgbxm                  1/1     Running     0          21m
kubeapps-internal-dashboard-64c7586bd7-vhk8t                  1/1     Running     0          21m
kubeapps-internal-tiller-proxy-54b5f87545-kdrxq               1/1     Running     0          21m
kubeapps-internal-tiller-proxy-54b5f87545-m5gcj               1/1     Running     0          21m
kubeapps-mongodb-89c57f6f9-4s7bx                              1/1     Running     0          21m
```
I don't see any errors in any of the containers. I've exposed kubeapps service as a NodePort
```
# kubectl get services -n kubeapps
NAME                             TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
kubeapps                         NodePort    10.106.239.71   <none>        80:31595/TCP   22m
kubeapps-internal-chartsvc       ClusterIP   10.100.136.47   <none>        8080/TCP       22m
kubeapps-internal-dashboard      ClusterIP   10.97.195.25    <none>        8080/TCP       22m
kubeapps-internal-tiller-proxy   ClusterIP   10.110.23.111   <none>        8080/TCP       22m
kubeapps-mongodb                 ClusterIP   10.98.188.88    <none>        27017/TCP      22m
```
I am able to login to the UI, but I have the following issues:
1) I do not see a "Charts" tab on the top of the UI. Only "Applications", "Catalog", "Service Instances (alpha)". Clicking on Catalog or Service Instances, I just get a pulsing blue dot.
2) Clicking "Configuration" and then either "App Repositories" or "Service Brokers" and I get "Sorry! Something went wrong".

If I go into Chrome's developer console, when I click the Configuration options above, I see the following error from React:
```
TypeError: Cannot read property 'map' of undefined
    at t.render (AppRepoList.tsx:80)
    at Jo (react-dom.production.min.js:156)
    at Yo (react-dom.production.min.js:155)
    at ti (react-dom.production.min.js:162)
    at Di (react-dom.production.min.js:192)
    at Pi (react-dom.production.min.js:193)
    at fa (react-dom.production.min.js:205)
    at ca (react-dom.production.min.js:204)
    at Bi (react-dom.production.min.js:200)
    at Object.enqueueSetState (react-dom.production.min.js:130)
```
I've removed and re-installed kubeapps a bunch of times now, and am not sure where to go from here. 

Basic info:

Kubernetes: v1.12.2

Anything else you need, please let me know!

Thanks!

**Comment by trenb** [comment]
So I tracked the issue down to haproxy. I run haproxy with SSL in front of the nodePort exposed. That causes the breakages. Is kubeapps not meant to be run via SSL in the browser?

**Comment by andresmgot** [comment]
Hi @trenb,

>I do not see a "Charts" tab on the top of the UI. Only "Applications", "Catalog", "Service Instances (alpha)". Clicking on Catalog or Service Instances, I just get a pulsing blue dot.

Yes, the item "Charts" has been replaced by "Catalog". We are updating the screenshots, sorry for the confusion.

> So I tracked the issue down to haproxy. I run haproxy with SSL in front of the nodePort exposed. That causes the breakages. Is kubeapps not meant to be run via SSL in the browser?

In theory the HAProxy shouldn't be an issue as far as it doesn't remove the Authorization header or something like that. How have you configured it? Can we reproduce it somehow? 

Are you able to properly use Kubeapps if you don't use the proxy? From the error you posted, it seems that there was an issue creating the `AppRepositories` of the application but if you find errors like that in other views the cause may be other. Can you list the repositories executing:

```
kubectl get apprepositories -n kubeapps
```

**Comment by trenb** [comment]
I don't have haproxy configured to remove any headers. The config I'm using is quite simple:
```
frontend K8S-DEV-ADMIN-2443
    bind 192.168.1.13:2443 ssl crt /etc/haproxy/certs/wildcard.XXX.com/wildcard.XXX.com_gd_bundle_key.crt

    default_backend K8S-DEV-KUBEAPPS

backend K8S-DEV-KUBEAPPS
    balance source
    hash-type consistent
    server k8s-worker-1.dev.XXX.lan  k8s-worker-1.dev.XXX.lan:31595 check
    server k8s-worker-2.dev.XXX.lan  k8s-worker-2.dev.XXX.lan:31595 check
    server k8s-worker-3.dev.XXX.lan  k8s-worker-3.dev.XXX.lan:31595 check
    server k8s-worker-4.dev.XXX.lan  k8s-worker-4.dev.XXX.lan:31595 check
    server k8s-worker-5.dev.XXX.lan  k8s-worker-5.dev.XXX.lan:31595 check
```
I login with the same token, but nothing works as mentioned above.  Once I switch from https to http on the front end, everything works perfectly in the kubeapps web ui. I'm currently running the haproxy frontend like this:
```
frontend K8S-DEV-ADMIN-2888
    bind 192.168.1.13:2888

    default_backend K8S-DEV-KUBEAPPS
```
And once I stop doing SSL termination at haproxy, the webui works properly, no issues at all. 

To answer your last question, the apprepositories seem to be working fine as well
```
# kubectl get apprepositories -n kubeapps
NAME        AGE
bitnami     2d
incubator   2d
stable      2d
svc-cat     2d
```
Thanks for getting back to me. Please let me know if you need any more information!

**Comment by prydonius** [comment]
@trenb can you see what the responses are from the API in the network tab of your Chrome dev console whilst going through the app? That might give us a better idea of what's going on when you're accessing things over HTTPS.

**Comment by prydonius** [comment]
@trenb no worries, whenever you get around to it! Thanks!

**Comment by sumanbasuli** [comment]
Hi, I just faced the same issue I have switched to the network tab in chrome dev tools and recorded the HAR file of the error.

You can download the  .har file here. [https://drive.google.com/open?id=15VYiYaHVRIN2ce5TN-Eb4EJJb9V-a9-g](url)

**Comment by andresmgot** [comment]
Hi @sumanbasuli,

In your case, it seems that it's a RBAC issue:

```
{"code":500,"message":"Unable to list helm releases: rpc error: code = Unknown desc = configmaps is forbidden: User \"system:serviceaccount:kube-system:default\" cannot list resource \"configmaps\" in API group \"\" in the namespace \"kube-system\""}
```

It seems that you have deployed Helm `tiller` with the default service account. See this troubleshooting section (the error is similar):

https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps#forbidden-error-while-installing-the-chart

**Comment by trenb** [comment]
Well, I'm not sure what to say. I tested today and https is working flawlessly. The only difference, is we've deployed repos and apps now, where the previous tests were on a brand new install. Strange. I'm going to close this for now.

Thanks for your assistance!

**Comment by migmartri** [comment]
Thanks @trenb for getting back to us. Keep us posted if you run into any other problems!

Thanks!
