### ISSUE TITLE
Add a pod security policy

### ISSUE THREAD

**Issue by obeyler** [kubeapps/kubeapps#863]
feature request:
like we can see on several chart, put the opportunity to add a pod security policy in the helm chart.

**Comment by obeyler** [comment]
/reopen
the security context works for pods but not for jobs
![image](https://user-images.githubusercontent.com/23224162/49583653-22707100-f959-11e8-8a5c-c9b4fb89d1d1.png)

**Comment by andresmgot** [comment]
thanks @obeyler, we will discuss this in #872
