### ISSUE TITLE
Does not work On GKE - Error: Chart incompatible with Tiller v2.6.2

### ISSUE THREAD

**Issue by nigel-dewar** [kubeapps/kubeapps#875]
Install does not work on fresh install of GKE

Here is the error after running: ./helm install --name kubeapps --namespace kubeapps bitnami/kubeapps

Error: Chart incompatible with Tiller v2.6.2

**Comment by andresmgot** [comment]
Hi @nigel-dewar,

You need to upgrade Helm (and Tiller). In order to install Kubeapps you need at least the version 2.10.

**Comment by arapulido** [comment]
We are going to close this one. @nigel-dewar please, reopen if upgrading to Helm 2.10 doesn't fix your issue.
