### ISSUE TITLE
Look into jwt authentication header use instead of Bearer

### ISSUE THREAD

**Issue by migmartri** [kubeapps/kubeapps#881]
It seems that the k8s dashboard accepts service account secret token during login but then a jwt is actually used during calls.

Actually, a refresh stage happens before every call as you can see in the screenshots below.
![selection_785](https://user-images.githubusercontent.com/24523/50036279-a14e5500-ffbc-11e8-8718-1b6007db765b.png)

![selection_784](https://user-images.githubusercontent.com/24523/50036277-9a274700-ffbc-11e8-9b04-c66e4a3be161.png)

This approach is interesting because that way we are not exposing the permanent secret but a temporary derived jwt.

**Comment by migmartri** [comment]
Note that this seems to require a backend and has some overlap with our future efforts on improving authentication support https://github.com/kubeapps/kubeapps/issues/385 so I'd not implement this standalone but just take it into account in future designs.

**Comment by absoludity** [comment]
We now recommend OIDC which uses short-lived JWT tokens for auth which carry the relevant user/group data trusted by the k8s api server. Closing.
