### ISSUE TITLE
Authentication improvements (design doc)

### ISSUE THREAD

**Issue by migmartri** [kubeapps/kubeapps#883]
One of our main items for the next Kubeapps releases is to improve the authentication/authorization usability and supported options.

Currently, we require users to input an auth token in a login form, token that has been previously provided by a Kubeapps administrator. We want to simplify this flow by leveraging single sign on if the user has it set it up for their organization.

Roughly speaking this might mean:

Features

* Leverage existing OIDC setup to authenticate users https://github.com/kubeapps/kubeapps/issues/385
* Offer an easy way to setup their own single sign on authentication flow without requiring to modify the api-server flags. This means that it should work in any k8s cluster and pointing to any oidc provider.
* Ideally, be ready to support additional auth methods like SAML, LDAP.  

Implementation improvements

* Look into using jwt instead of bearer tokens https://github.com/kubeapps/kubeapps/issues/881 

This task is about writing a design document that outlines possible solutions to discuss.

**Comment by migmartri** [comment]
I am working on this design doc, although it is not completed, feel free to skim through it https://docs.google.com/document/d/1YZzLtIbS2copQJgspFiMd0eAhpyt8u19MUSDEvH2X4g/edit?usp=sharing

**Comment by migmartri** [comment]
The doc has been update and is ready for review

**Comment by davidkarlsen** [comment]
Interesting issue.
We are on ICP:  IBM Cloud Private, https://www.ibm.com/support/knowledgecenter/en/SSBS6K_3.1.1/user_management/auth_onboard.html
via the cmd line tool "cloudctl" I login with my corp username and pw, and it returns an JWT (extractable at https://jwt.io/) - I can simply paste this token into the kubeapps UI and I'm in - so what I am looking for is some integration mechanism where I can do SSO/integration with ICP transparently when already logged into ICP. 

I haven't debugged kubeapps, but if I jump in with the token in a http header "Authorization: <thejwt>" - would it work as of today?

**Comment by davidkarlsen** [comment]
> Hi @davidkarlsen,
> 
> First of all sorry, I just noticed that the doc was not fully public.
Thanks - I had a look at the doc - and it looks well founded and though-through!

> I am not familiar with how OIDC is configured in ICP but if you have access to the OIDC `discovery_uri`, `client_id` and `secret` used to configure the k8s API then you will meet what I called the [Scenario 1](https://docs.google.com/document/d/1YZzLtIbS2copQJgspFiMd0eAhpyt8u19MUSDEvH2X4g/edit#heading=h.vzb180e3ldio) (the simplest scenario)

I am a bit new to ICP myself (started in Dec) - but it seems to support this: https://www.ibm.com/support/knowledgecenter/en/SSBS6K_3.1.1/user_management/auth_onboard.html 

> I do not think I fully understand you question. Are you asking if you access Kubeapps with a Auth Header you will get transparently logged in (hiding the login page)? If that's the case, the answer is no.
OK

> Actually in my doc I did not even contemplated that option since I am putting a proxy that will take care of the whole Oauth2(OIDC) roundtrip for you (so no need to get the token from `cloudctl`), would that work for you better?
I think what is outlined there seems the most usual and sane to do.

Thanks for reaching out in this open manner!

**Comment by davidkarlsen** [comment]
Is there an ETA for this? I think it's quite an important issue, since the somewhat fumbling login makes it a bit hard to sell-in.

**Comment by andresmgot** [comment]
Hi @davidkarlsen, this is in our roadmap but we don't have an ETA yet. Thank you for your feedback, it's really appreciated :smile:

**Comment by prydonius** [comment]
See #931 for the follow up to this

**Comment by ITBlogger** [comment]
I'm guessing this would allow us to login via rancher as well? With rancher all user authentication goes through the rancher master cluster. Users cannot login to a k8s cluster directly.

**Comment by prydonius** [comment]
@ITBlogger interesting, do you have a link to some documentation on how this works with Rancher?

**Comment by andresmgot** [comment]
@prydonius https://rancher.com/docs/rancher/v2.x/en/admin-settings/authentication/

**Comment by prydonius** [comment]
@andresmgot oh cool, so it looks like Rancher can both be it's own OIDC provider, or configure your cluster with external ones. I've added it to the list to checkout in #948.

**Comment by ITBlogger** [comment]
Yes, sorry, forgot to get back to your request. Yes, in our case we're using github for SSO with rancher. But all requests still flow through the rancher cluster and rancher provides each user with their own token to use in .kube/config

**Comment by prydonius** [comment]
Thanks for the info @ITBlogger!
