### ISSUE TITLE
Offline (Disconnected) Installation?

### ISSUE THREAD

**Issue by robotica72** [kubeapps/kubeapps#89]
This isnt uncommon for newer products, but my installation must be done offline.  I can pull containers and push them into my local Registry, but I don't see a parameter that can be passed to the installer for the registry location.   Is there any consideration in adding an option to change the pull location for the containers?

I havent looked at the source version yet, just tried the compiled for a quick test - so Ill see what I can hack together to get it up - but I was curious if an add on option to pass a registry location was being considered.

**Comment by ngtuna** [comment]
@robotica72 thanks for the feedback. That's good idea to support other registries than the default one. Right now it's not configurable. The kubeapps right now deploys components declared at a embedded static yaml file which should be dynamically configured. We will discuss about that and get back to you soon.

**Comment by ngtuna** [comment]
this can be solved somehow via #95

**Comment by ngtuna** [comment]
@robotica72 We've added a support for generating the deployment manifest for kubeapp with this command `kubeapps up --dry-run -o yaml`. So somehow you can generate and modify the manifest to add your private registry images. Let me know if that fixes your issue
