### ISSUE TITLE
[Feature request] [Design] Notify chart updates

### ISSUE THREAD

**Issue by andresmgot** [kubeapps/kubeapps#901]
Child task of  #588

Create design a document for implementing the notification system for updates requested in #588

**Comment by andresmgot** [comment]
@prydonius @migmartri I have gathered some proposals in the document below. I believe that "option 3" is the right way to go here and that's why I have detailed that option further. Let me know if you agree or if you have a different proposal. In case that you agree and if it's needed, I can open a PR for the `proposals/` folder with even more detailed implementation instructions for the desired option.

https://docs.google.com/document/d/1oG9nerd5CurWSIwH33kKCsOCtkSFMgcm8SuTJyuSnxs/

**Comment by prydonius** [comment]
I agree with @migmartri's conclusion above in general.

> I am ok accepting that in some cases might not work 100 accurate although I'd like to research a little bit about how common these scenarios are.

+1, I'm confident that with the info we do have from the release artifact, we will be able to extract the repository quite reliably (depending on how much of that info we use, e.g. we could compare each field in the chart version). The likelihood of two different WordPress charts having the exact same description, for example, is low. Maintainers listed in the chart are also generally unique across repositories. The only place this could become an issue is in repositories that have mirrored charts, (e.g. bitnami and stable). This is a somewhat specific case though (and will eventually go away once charts are removed from stable), and I doubt it will happen often in other scenarios.

Then there's also the issue of charts that are installed from a directory and don't exist in a repository, in this case we won't have a matching repository and can just inform the user -- if it wasn't installed through a repository the user isn't using Kubeapps to install/upgrade that release anyway, so I don't think it will be an issue.

**Comment by migmartri** [comment]
> Then there's also the issue of charts that are installed from a directory and don't exist in a repository, in this case we won't have a matching repository and can just inform the user -- if it wasn't installed through a repository the user isn't using Kubeapps to install/upgrade that release anyway, so I don't think it will be an issue.

But this is an issue in all options no? If there is no repository to match against it does not really matter if we do it via an API call from the frontend or via a controller no?

**Comment by prydonius** [comment]
> But this is an issue in all options no?

Yes, but just pointing out that in this case it might not really be an issue since the user is likely not intending to manage it through Kubeapps. In the CRD case we might ask the user to "migrate" the chart and we create the CR for it, which might be confusing.

**Comment by andresmgot** [comment]
@migmartri @prydonius I have updated the document to elaborate further the option 1, please let me know if you have more comments. I like the idea of having an endpoint in the chart-svc that returns if a chart is up to date.

**Comment by andresmgot** [comment]
As a summary for the doc linked before we have decided to do a request from the Dashboard to the chart-svc that should determine if a `Chart.yaml` is up to date. This is detailed in the option 1 (b) in the document. The changes needed are:
 - Tiller proxy should return the chart metadata when listing applications (AppOverview)
 - A new endpoint (`/charts/check_updates`) for the chart-svc should be implemented.
 - The Dashboard will contact the chart-svc to get possible updates. The result should be stored with Redux.
