### ISSUE TITLE
installation options?

### ISSUE THREAD

**Issue by chino** [kubeapps/kubeapps#91]
Would be nice to offer a `--storage-class` option?  In my particular setup I require a storage class name for Heketi to launch a volume.

Is there a recommended setup/transition for users who are already running Helm/Tiller on their own?

**Comment by ngtuna** [comment]
@chino Right now we deploy Tiller on a different namespace than the official one. So in theory, both can coexist

**Comment by prydonius** [comment]
> Would be nice to offer a --storage-class option? In my particular setup I require a storage class name for Heketi to launch a volume.

I agree that this should be an option, I think in general we need to go through the manifests and identify what things should be made configurable (and how).

> Is there a recommended setup/transition for users who are already running Helm/Tiller on their own?

To expand on what @ngtuna said, we deploy Tiller as a sidecar to the Dashboard API pod and it is configured to store Helm release data in the `kubeapps` namespace. A typical Tiller is installed in the `kube-system` namespace as a `tiller-deploy` deployment and is configured to store Helm release data in the `kube-system` namespace. So, a default Tiller install will act completely independently to the Kubeapps Tiller. This also means that the release history isn't shared, i.e. if you install a chart with the Helm CLI, you won't see it in the Kubeapps Dashboard and vice-versa.

**Comment by chino** [comment]
Ok thanks for the info.

The storage-class was a bit of a problem as I had to identify the issue and then recreate the pvc before the container gave up trying to mount the volume.

**Comment by chino** [comment]
Another issue is the need to pass `$no_proxy` and `$http_proxy` if you're forced to reach the internet via proxy.

The UI was hanging for me until I edited the deploy to add the env vars and restarted the pods.

**Comment by prydonius** [comment]
@chino interesting, I think that specific problem might be better solved by a [PodPreset](https://kubernetes.io/docs/tasks/inject-data-application/podpreset/).

**Comment by chino** [comment]
Yea, I agree with that.  Although it's not enabled by default in most clusters and especially in Bootkube it's not even an option yet?  I do wonder though how many other little tweaks might be needed in time?

Are you planning to make chart options available in the UI during install?

I didn't see anything in the instructions explaining how to point helm cli at the kubeapps install?

**Comment by chino** [comment]
I will note that you can also solve the original storage class issue by enabling a default storage class in the cluster.  That however is a great example of something you might want to tweak.

**Comment by prydonius** [comment]
You're right, PodPreset is still in alpha... we may need to make the proxy configurable, although I believe a lot of charts don't have this option either so your best option would be to enable the alpha feature.

> Are you planning to make chart options available in the UI during install?

If you mean values.yaml options, then yes that's certainly on the roadmap.

> I didn't see anything in the instructions explaining how to point helm cli at the kubeapps install?

It currently isn't possible, though the main reason is that the name of the deployment object Helm looks for is hardcoded to `tiller-deploy`. I'm considering patching Helm to make that configurable which would allow it to discover the Monocular with Tiller sidecar deployment instead.

**Comment by prydonius** [comment]
> I will note that you can also solve the original storage class issue by enabling a default storage class in the cluster. That however is a great example of something you might want to tweak.

Yeah, I do agree that this should be tweakable, all charts have this option to.

**Comment by chino** [comment]
I was wondering if it's possible/easy to make kubeapps dump all the required yaml to stdout so you can tweak all of these things before pushing?

**Comment by prydonius** [comment]
@chino that's actually in progress in #98 and will be part of the next release within the next week!

**Comment by prydonius** [comment]
@chino #98 just got merged, so if you want to try this out you can work from master

**Comment by arapulido** [comment]
@prydonius what else is needed here?

**Comment by prydonius** [comment]
I'm going to close this for now since Kubeapps no longer requires any persistence, and the Helm chart allows for more configuration.
