### ISSUE TITLE
Improve AppRepository authentication input for Basic and Bearer token auth

### ISSUE THREAD

**Issue by prydonius** [kubeapps/kubeapps#911]
The two most common Authorization headers to set for a repository are Basic auth and Bearer token auth. Currently we expect users to specify the whole Authorization header, including the Basic/Bearer prefix, which can be error prone (#908). We could improve the experience by having a dropdown of options and different form inputs to deal with each case:

- Basic
  - Show a username and password field
- Bearer
  - Show a field for the token
- Custom
  - Show the full custom Authorization header (e.g. as we have it today)

Selecting a different option would change the fields shown on the form. For Basic auth, the correct header will be calculated from the username and password input. For Bearer auth, the `Bearer` prefix will be prepended to the user-supplied token. For the Custom input, the full Authorization header will be sent as is (this will be useful for protocols other than Bearer and Basic).

**Comment by ligc** [comment]
This improvement will be really useful, have been strugging with the authentication error caused by the missing "-n" flag with "echo username:password" for several hours util see https://github.com/kubeapps/kubeapps/issues/908.
