### ISSUE TITLE
Revisit keys used in the Kube redux state to simplify access

### ISSUE THREAD

**Issue by prydonius** [kubeapps/kubeapps#912]
Currently, we are using the full request URI as a key for resources we're caching in the IKubeState: https://github.com/kubeapps/kubeapps/blob/c8bb6ea82c7304783835a79476f08c51a324c5c4/dashboard/src/actions/kube.tsx#L30. Whilst this ensures the keys are unique, and is a simple way of storing it, it makes it more difficult to retrieve specific items. Today, we're iterating through keys to find keys with a portion of the URI relating to a resource: https://github.com/kubeapps/kubeapps/blob/c8bb6ea82c7304783835a79476f08c51a324c5c4/dashboard/src/containers/SecretsTableContainer/SecretsTableContainer.tsx#L15-L19.

For example, we search for a match for `/secrets/`. The problem with this approach is that it won't reliably find the resources we're looking for. This URI match will return results if a namespace or resource is named "secrets", for example. It also will return "Secret" kinds in different API groups. For example:
- `/api/v1/namespaces/default/secrets/my-secret`
- `/api/v1/namespaces/secrets/pods/my-pod`
- `/apis/bettersecrets.com/v1alpha1/namespaces/default/secrets/my-better-secret`

All of the URIs will match for `/secrets/`, but we only actually want the first one in this case. Whilst we can construct a regex match to fix this issue, I think we can improve the way we store and retrieve resources in IKubeState. I propose we move to a hierarchical structure with the API version and kind at the top-level. This will allow us to more easily navigate resource kinds. For example:

- items
  - v1/secrets
    - namespace/default (the namespace/ prefix is not necessary)
      - my-secret
    - namespace/test
      - test-password
  - v1/pods
    - namespace/secrets
      - my-pod
  - bettersecrets.com/v1alpha1/secrets
    - namespace/default
      - my-better-secret

(kind -> namespace -> name)

This way, we're able to get all the v1/secrets in O(1) time by simply accessing `items["v1/secrets"]`. We can then further filter for namespace, or extract all Secrets across all namespaces.

When making this change, we should also be able to implement the allIDs/byID pattern as captured by #865.

**Comment by prydonius** [comment]
With this structure, we can then access resources like so:

- Direct access:
  - `items["v1/secrets"]["default"]["my-secret"]`
- By kind:
  - `items["v1/secrets"]`
- By kind and namespace:
  - `items["v1/secrets"]["default"]`
- Cluster-scoped resources:
  - `items["apiextensions.k8s.io/v1beta1/customresourcedefinitions"]["_"]` (where underscore denotes that a resource is unscoped)

**Comment by arapulido** [comment]
@prydonius @andresmgot  is this still relevant?

**Comment by andresmgot** [comment]
Since we are no longer filtering items doing `k.indexOf(`/${type}/`)` (instead we are matching against the full URL) I think this is less relevant.

Also, AFAIK we don't use list of resources anywhere (we use `*Refs` instead) so there is no a major reason to refactor the keys structure. 

IMO I would close this issue, do you agree @prydonius ?

**Comment by prydonius** [comment]
I don't think we need this today, but at some point we likely will want to consolidate to storing all resource types in the kube state (e.g. AppRepositories, Service Catalog resources), and in these cases we will want to be able to get list of resources for kinds and namespaces (see #977).

I think we should leave this open so we can revisit this when we want to work on the above.
