### ISSUE TITLE
Workaround CI error

### ISSUE THREAD

**Issue by migmartri** [kubeapps/kubeapps#915]
Sporadically we get the following error during our integration tests in the CI. They seem to be related to a race condition with the fact that the CRD has not been fully registered.

We should double check if Helm has already a built-in solution for this but otherwise, as a workaround we could add a retry mechanism via either delete+install or upgrade.  

> Error: validation failed: [unable to recognize "": no matches for kind "AppRepository" in version "kubeapps.com/v1alpha1", unable to recognize "": no matches for kind "AppRepository" in version "kubeapps.com/v1alpha1", unable to recognize "": no matches for kind "AppRepository" in version "kubeapps.com/v1alpha1", unable to recognize "": no matches for kind "AppRepository" in version "kubeapps.com/v1alpha1"]
Exited with code 1

Refs https://circleci.com/gh/kubeapps/kubeapps/5468

**Comment by arapulido** [comment]
Right now it doesn't happen too often. Let's close it for now.

**Comment by jairov4** [comment]
happening in 2021

**Comment by absoludity** [comment]
@jairov4 We'll need more information about your steps to reproduce the issue if you want to look into it.

In particular, what version of k8s, which kubeapps chart, which helm version, the steps to reproduce etc. Thanks!
