### ISSUE TITLE
Improve the base64 decoding command in the documentation

### ISSUE THREAD

**Issue by kfox1111** [kubeapps/kubeapps#917]
Very minor tweak. in the docs, rather then this:
-o jsonpath='{.data.token}' | base64 --decode

you can do:
-o go-template='{{.data.token | base64decode}}'

It should work on all platforms as its built into kubectl now.

**Comment by prydonius** [comment]
thanks for the tip, do you know what version of kubectl added this? I think we didn't document `kubectl port-forward svc/kubeapps` because it required kubectl 1.9+

**Comment by kfox1111** [comment]
I don't remember. I think is was 1.11, but don't quote me. :)

If your worried about 1.9+, then its a no go.

**Comment by prydonius** [comment]
I think at that point we cared about 1.8 support because the supported versions were 1.8-1.10. With 1.13, it wouldn't necessarily be bad to require 1.11+, especially since `kubectl` is pretty good with backwards/forwards compatibility.

**Comment by prydonius** [comment]
Thanks for confirming! cc @kubeapps/maintainers, what do you think?

**Comment by andresmgot** [comment]
We can fix this now. Kubernetes 1.11 has been out for a while.
