### ISSUE TITLE
configure custom CA cert and authorization header for initialRepos in chart

### ISSUE THREAD

**Issue by obeyler** [kubeapps/kubeapps#919]
![image](https://user-images.githubusercontent.com/23224162/50972686-8b628000-14e7-11e9-9f93-99c3bfdc4af6.png)
private certificate can be set for repository by the UI but not by the value.xml file.

**Comment by obeyler** [comment]
@andresmgot 
 Sorry for my late answer : in value.yaml we can set initial repository
 ''' initialRepos:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
  - name: incubator
    url: https://kubernetes-charts-incubator.storage.googleapis.com
  - name: svc-cat
    url: https://svc-catalog-charts.storage.googleapis.com
  - name: bitnami
    url: https://charts.bitnami.com/bitnami '''

what is the format for the CA ?
Thanks by advance

**Comment by andresmgot** [comment]
Oh, you meant `values.yaml`. That's still not supported (setting the CA there).

**Comment by andresmgot** [comment]
@obeyler this should be ready using the chart 1.4.0, can you give it a try?
