### ISSUE TITLE
Dashboard static file request failed, such as js css

### ISSUE THREAD

**Issue by jsDuan** [kubeapps/kubeapps#923]
I have deployed kubeapps and can request Service and Pod and succeed, but no response to static resources.

- Service
```sh
[root@k8s-master ~]# kubectl get service --namespace kubeapps -o wide
NAME                             TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE     SELECTOR
kubeapps                         LoadBalancer   10.96.82.164    <pending>     80:32150/TCP   4m36s   app=kubeapps,release=kubeapps
kubeapps-internal-chartsvc       ClusterIP      10.97.236.83    <none>        8080/TCP       4m36s   app=kubeapps-internal-chartsvc,release=kubeapps
kubeapps-internal-dashboard      ClusterIP      10.109.64.128   <none>        8080/TCP       4m36s   app=kubeapps-internal-dashboard,release=kubeapps
kubeapps-internal-tiller-proxy   ClusterIP      10.103.209.98   <none>        8080/TCP       4m36s   app=kubeapps-internal-tiller-proxy,release=kubeapps
kubeapps-mongodb                 ClusterIP      10.104.72.69    <none>        27017/TCP      4m36s   app=mongodb,release=kubeapps
```
- Pod
```sh
[root@k8s-master ~]# kubectl get pod --namespace kubeapps -o wide | grep dashboard
kubeapps-internal-dashboard-866b6dcb8f-5bh9v                 1/1     Running     0          13m   192.168.1.83   k8s-node1   <none>           <none>
kubeapps-internal-dashboard-866b6dcb8f-sfmnx                 1/1     Running     0          13m   192.168.1.82   k8s-node1   <none>           <none>
```

- request service
```sh
[root@k8s-master ~]# curl 10.96.82.164
<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no"><meta name="theme-color" content="#000000"><link rel="manifest" href="./manifest.json"><link rel="icon" type="image/png" href="./favicon-196x196.png" sizes="196x196"/><link rel="icon" type="image/png" href="./favicon-32x32.png" sizes="32x32"/><link rel="icon" type="image/png" href="./favicon-16x16.png" sizes="16x16"/><link rel="icon" type="image/png" href="./favicon-128.png" sizes="128x128"/><title>Kubeapps Dashboard</title><link href="./static/css/main.0b9c5300.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div><script type="text/javascript" src="./static/js/main.afbfe96d.js"></script></body></html>
```

- request pod
```sh
[root@k8s-master ~]# curl 192.168.1.83:8080
<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no"><meta name="theme-color" content="#000000"><link rel="manifest" href="./manifest.json"><link rel="icon" type="image/png" href="./favicon-196x196.png" sizes="196x196"/><link rel="icon" type="image/png" href="./favicon-32x32.png" sizes="32x32"/><link rel="icon" type="image/png" href="./favicon-16x16.png" sizes="16x16"/><link rel="icon" type="image/png" href="./favicon-128.png" sizes="128x128"/><title>Kubeapps Dashboard</title><link href="./static/css/main.0b9c5300.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div><script type="text/javascript" src="./static/js/main.afbfe96d.js"></script></body></html>[root@k8s-master ~]#
```
- request pod static file ,logs have records  ，but no response
```
[root@k8s-master ~]# curl 192.168.1.83:8080/static/css/main.0b9c5300.css
[root@k8s-master ~]# kubectl logs kubeapps-internal-dashboard-866b6dcb8f-5bh9v -n kubeapps

192.168.0.1 - - [13/Jan/2019:18:53:58 +0000] "GET /static/css/main.0b9c5300.css HTTP/1.1" 200 15046 "-" "curl/7.29.0"
```

**Comment by jsDuan** [comment]
> Hi @jsDuan,
> 
> The Dashboard is a ReactJS application. To run it, it's necessary to use a web browser. That's why you are getting the message `You need to enable JavaScript to run this app` when requesting the service with `curl`.

I want to use nginx to proxy the internal ip, but found that only index.html can be requested, js and css did not respond, so I tried the local server to use curl request and found the result is the same.

**Comment by jsDuan** [comment]
> Hi @jsDuan,
> 
> The Dashboard is a ReactJS application. To run it, it's necessary to use a web browser. That's why you are getting the message `You need to enable JavaScript to run this app` when requesting the service with `curl`.

May be my problem, because I tried other similar services, the result is the same, thank you, I will continue to investigate

**Comment by andresmgot** [comment]
> I want to use nginx to proxy the internal ip, but found that only index.html can be requested

Yes, that's expected. The application gets downloaded and the different routes are handled within the application. We include in the chart an optional ingress object that you can also use to proxy requests:

https://github.com/kubeapps/kubeapps/blob/master/chart/kubeapps/values.yaml#L11

Hope that helps.

**Comment by jsDuan** [comment]
> @jsDuan I think you might be trying to use the wrong Pod to port-forward to here, Kubeapps should be accessed from the `kubeapps` Deployment and not from the internal `kubeapps-internal-dashboard` Deployment. The `kubeapps` Deployment acts as an ingress to route requests to the various different services behind Kubeapps (dashboard, chartsvc, tiller-proxy). What happens if you try your port-forward with the `kubeapps` Pods instead of `kubeapps-internal-dashboard`?

Thank you very much, according to my idea, using the reverse proxy (system nginx on master) proxy internal service port should be accessible externally but not very easy to use, but using inress (traefik ingress, nginx ingress) proxy is fine.

**Comment by prydonius** [comment]
@jsDuan were you able to get this working for you then?

**Comment by arapulido** [comment]
@jsDuan We are closing this now, but feel free to reopen it if you are still having issues. We would be happy to help
