### ISSUE TITLE
Error: stat /home/user/.kube/config: no such file or directory

### ISSUE THREAD

**Issue by yangboz** [kubeapps/kubeapps#93]
After 
```
sudo curl -L https://github.com/kubeapps/installer/releases/download/v0.0.2/kubeapps-linux-amd64 -o /usr/local/bin/kubeapps && sudo chmod +x /usr/local/bin/kubeapps
```
Then
```
kubeapps up
```
But it thrown errors:
```
user@user:~$ /usr/local/bin/kubeapps up
Error: stat /home/user/.kube/config: no such file or directory
```

**Comment by ngtuna** [comment]
@yangboz kubeapps relies on kubeconfig to interact with the k8s cluster. Do you have kubeconfig file locates somewhere on your environment ?

**Comment by ngtuna** [comment]
If yes, consider to export KUBECONFIG envvar to your kubeconfig file. That should work.

**Comment by yangboz** [comment]
@ngtuna Does minikube also works well? Thanks.

**Comment by ngtuna** [comment]
@yangboz Yes it works really well. Can you give it a try ?

**Comment by haroon3rd** [comment]
Same issue with k3s on the cloud
F1218 16:58:56.817838    7821 keadm.go:27] Failed to build config, err: stat /root/.kube/config: no such file or directory

export KUBECONFIG=/etc/rancher/k3s/k3s.yaml does not help.
