### ISSUE TITLE
kubeapps dashboard can not access  in Browser

### ISSUE THREAD

**Issue by Blue-Skies-firststar** [kubeapps/kubeapps#934]
kubectl port-forward -n kubeapps kubeapps-cdb69fc8f-m9z5h  8888:8080

 curl  http://127.0.0.1:8888/ 
<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no"><meta name="theme-color" content="#000000"><link rel="manifest" href="./manifest.json"><link rel="icon" type="image/png" href="./favicon-196x196.png" sizes="196x196"/><link rel="icon" type="image/png" href="./favicon-32x32.png" sizes="32x32"/><link rel="icon" type="image/png" href="./favicon-16x16.png" sizes="16x16"/><link rel="icon" type="image/png" href="./favicon-128.png" sizes="128x128"/><title>Kubeapps Dashboard</title><link href="./static/css/main.0b9c5300.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div><script type="text/javascript" src="./static/js/main.afbfe96d.js"></script></body></html>

but curl http://192.168.1.62:8888/
curl: (7) Failed connect to 192.168.1.62:8888; Connection refused
and   http://192.168.1.62:8888/  can not  Access by browser

**Comment by andresmgot** [comment]
@Blue-Skies-firststar That's expected, you need to access Kubeapps with a web browser using the URL http://127.0.0.1:8888. It is not possible to request the application with `curl`.

**Comment by Blue-Skies-firststar** [comment]
Thank you, I can open it through the browser through the proxy.
