### ISSUE TITLE
Avoid importing the entire lodash library in components

### ISSUE THREAD

**Issue by Angelmmiguel** [kubeapps/kubeapps#939]
I found several imports in the code like the following one:

```
import * as _ from "lodash";
```

[Lodash](https://lodash.com/) is a collection of utilities, but most of the time only a few of them are used. However, importing the entire library is causing webpack to include all the functions in the code. It increases the bundle site ~70Kb. 

There're several ways to reduce the lodash size in the final bundle. You can do it manually by importing the specific files or using any specific plugin for webpack or babel. You've more information in https://www.blazemeter.com/blog/the-correct-way-to-import-lodash-libraries-a-benchmark.

**Comment by prydonius** [comment]
There may also be cases where we can replace lodash for built-ins (e.g. `_.each` or `_.map`)
