### ISSUE TITLE
git clone doesn't work on windows

### ISSUE THREAD

**Issue by ngtuna** [kubeapps/kubeapps#94]
```
C:\GoPath\src\github.com\kubeapps>git clone https://github.com/kubeapps/kubeapps
Cloning into 'kubeapps'...
remote: Counting objects: 9445, done.
remote: Total 9445 (delta 0), reused 0 (delta 0), pack-reused 9445
Receiving objects: 100% (9445/9445), 16.86 MiB | 42.00 KiB/s, done.
Resolving deltas: 100% (3869/3869), done.
fatal: cannot create directory at 'vendor/github.com/docker/distribution/contrib/docker-integration/generated_certs.d/localregistry:5440': Invalid argument
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

Reason: https://github.com/docker/distribution/issues/1690

Somehow increase revision of `github.com/docker/distribution` will fix the issue, but we don't want to break up the dependencies as that package hasn't been imported directly from glide. It's auto revisioned from other packages (probably client-go or api-machinery)

**Comment by prydonius** [comment]
@wojciechka confirmed git clone works on his Windows setup, so I believe this is no longer an issue. Feel free to reopen if you still run into this.
