### ISSUE TITLE
Service Classes with a broken icon should be replaced with the default Kubeapps icon

### ISSUE THREAD

**Issue by arapulido** [kubeapps/kubeapps#944]
Azure Service Broker has now broken icons. I have reported this upstream: https://github.com/Azure/open-service-broker-azure/issues/666

When this happens, we should replace it in Kubeapps with the default Kubeapps logo, instead of showing the default browser broken icon icon, as it shows today:

![screen shot 2019-01-29 at 2 18 06 pm](https://user-images.githubusercontent.com/925437/51911130-4daf9380-23d1-11e9-8d8d-4765f52ea68c.png)

**Comment by prydonius** [comment]
We can use a component like https://github.com/socialtables/react-image-fallback to achieve this.

**Comment by absoludity** [comment]
No longer supporting service-broker.
