### ISSUE TITLE
access URL still shows pending after deploy on local machine. 

### ISSUE THREAD

**Issue by dgmdevelopment** [kubeapps/kubeapps#946]
Not sure why URL still shows pending after deploy of wordpress. tested a few other apps and do the same thing.  New to this, thanks!

![image](https://user-images.githubusercontent.com/188736/52013889-372a3a80-24ac-11e9-949a-ccbc7bc3a9b1.png)

**Comment by andresmgot** [comment]
@dgmdevelopment so the issue is that Minikube doesn't populate that information because it's not able to provide a public IP. For Minikube, that field will always be "Pending". See: 

https://kubernetes.io/docs/tutorials/hello-minikube/#create-a-service

**Comment by dgmdevelopment** [comment]
@andresmgot thank you, i did not find that info on minikube earlier.  I appreciate it, you may close this issue.

**Comment by andresmgot** [comment]
You are welcome, please reopen it if you find any other issue!

**Comment by earnubs** [comment]
Running `minikube tunnel` solved this for me.

See https://github.com/kubernetes/minikube/blob/master/docs/tunnel.md for more.

**Comment by prydonius** [comment]
Yep, `minikube tunnel` will need to be used to populate that field. See https://github.com/kubernetes/minikube/blob/master/docs/networking.md#loadbalancer-emulation-minikube-tunnel

**Comment by andresmgot** [comment]
should we reopen this issue? We can add a question mark icon to link to some documentation explaining this

**Comment by prydonius** [comment]
@andresmgot I'm open to discussing how we can improve the UX on this. We can create a separate issue.
