### ISSUE TITLE
Documentation on how to setup an OIDC proxy with Kubeapps

### ISSUE THREAD

**Issue by prydonius** [kubeapps/kubeapps#947]
Related to #385, #931 and dependent on #945. We should add documentation on how someone can make use of #945 by configuring a compliant OIDC proxy to authenticate with Kubeapps.

We can assume that the user already has OIDC configured with the Kubernetes apiserver, and just needs to configure a proxy with the same client id/secret.

**Comment by andresmgot** [comment]
from @arapulido:

> @andresmgot pusher has agreed to take over oauth2 proxy: https://github.com/pusher/oauth2_proxy and they have a new release (3.0) and this new version seems to have OIDC token support: https://github.com/pusher/oauth2_proxy/blob/master/providers/oidc.go
> 
> Also, this new pusher fork has already a Bitnami image: https://github.com/bitnami/bitnami-docker-oauth2-proxy

**Comment by prydonius** [comment]
@andresmgot oh nice! @migmartri if you have a moment, it would be great if you could have a brieft look into this new version of oauth2_proxy to see if it matches our requirements.
