### ISSUE TITLE
Add support for configuring an OIDC proxy for Kubeapps in the chart

### ISSUE THREAD

**Issue by prydonius** [kubeapps/kubeapps#949]
Related to #385, #931 and dependent on #945 and #947. We can help automate the setup of #947 by adding configurable options in the chart to set your OIDC URL, client ID and secret. This will then setup a proxy in front of Kubeapps capable of performing the OIDC dance and returning a token that Kubeapps can use to authenticate users.

**Comment by stormmore** [comment]
I currently do this using a kubectl plugin to login and a kubectl command to get the token out of my .kube/config. This would be super useful

**Comment by andresmgot** [comment]
Once we implement this, we need to add to Nginx:

For keycloak-gatekeeper, to allow the dashboard to access the Authorization header:

```
`add_header Authorization $http_authorization;`
```

For oauth2_proxy, to be able to include the required headers:

```
    nginx.ingress.kubernetes.io/proxy-buffer-size: 256k
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
```
