### ISSUE TITLE
Add ability to edit the kubernetes manifests

### ISSUE THREAD

**Issue by sameersbn** [kubeapps/kubeapps#95]
It would be nice if the user was able to inspect/modify the manifests deployed with the `kubeapps up` command. A possible solution is to introduce a `kubeapps dump` command to dump the complete manifest yaml which could be then edited and deployed using `kubectl`.

This would be helpful in getting kubeapps installed on clusters where the default kubeapps manifest doesn't "just work".

Sample usage:

```bash
$ kubeapps dump | kubectl create -f -
```

**Comment by ngtuna** [comment]
@sameersbn I like this idea. This also provides the manual step to upgrade kubeapps components to newer versions. Consider flag `-o` for json/yaml format.

```
$ kubeapp dump -o yaml > manifest.yaml
```

**Comment by prydonius** [comment]
I would suggest having using `kubeapps up --dry-run -o yaml`.
