### ISSUE TITLE
Improve UX/docs for why Services might be stuck in pending state

### ISSUE THREAD

**Issue by prydonius** [kubeapps/kubeapps#953]
Related to #946.

Sometimes, cloud provisioners can take a long time to provision and IP address for a Service LoadBalancer. Even when an application appears to be deployed (pods are running), the Service can stay in a pending state for a while and this causes confusion for Kubeapps users.

Additionally, for those testing Kubeapps on Minikube, the provisioner will never assign an IP address unless `minikube tunnel` is running.

We can look at improving the UX here by either adding an explanatory tooltip next to the pending state explaining that LoadBalancer Services can take some time to provision and to enable the Minikube tunnel if using Minikube.

**Comment by arapulido** [comment]
We can add a note in the getting started guide: https://github.com/kubeapps/kubeapps/blob/master/docs/user/getting-started.md
