### ISSUE TITLE
No Auth Provider found for name "oidc" 

### ISSUE THREAD

**Issue by chrisfelix82** [kubeapps/kubeapps#96]
I am getting this error `ERRO[0000] can't get Kubernetes client: No Auth Provider found for name "oidc"` . Does the cluster have to have OIDC RBAC?

**Comment by prydonius** [comment]
Looks like we need to import "k8s.io/client-go/plugin/pkg/client/auth/oidc" similar to what we're doing with GCP: https://github.com/kubeapps/kubeapps/blob/master/cmd/root.go#L44
