### ISSUE TITLE
Refactor AppView component

### ISSUE THREAD

**Issue by prydonius** [kubeapps/kubeapps#962]
from #959 

I noticed a few strange things, like keeping the manifest in the state, and the use of IPartialAppViewState. I think this component can be further refactored to improve readability and become more functional.

**Comment by prydonius** [comment]
See https://github.com/prydonius/kubeapps/commit/499ed26514fd515787ad0cb32cec7edd24098f92 for a WIP of this refactor

**Comment by absoludity** [comment]
App view has been reworked with the 2.0 design.
