### ISSUE TITLE
AccessURLTable refactor: Individual Service/Ingress loading in AccessURLItem

### ISSUE THREAD

**Issue by prydonius** [kubeapps/kubeapps#963]
In AccessURLTable we fetch all Ingresses and Services and then render AccessURLItems. We should instead follow the architecture of ServicesTable/DeploymentsTable and have the Item components be in charge of fetching and rendering the resources.

One issue is that Services that are not LoadBalancer types shouldn't be shown in the AccessURLTable, currently these are filtered out in this component, however they are still fetched. I think we can have a AccessURLServiceItem component render nothing if a Service is not of a LoadBalancer type. We may also be able to reuse the ServiceItem component from the ServicesTable.

**Comment by andresmgot** [comment]
Services are already fetched/watched in the ServiceTable component so we can just remove the fetching from the AccessURLTable.
