### ISSUE TITLE
kubeapps falsely states "no readme found"

### ISSUE THREAD

**Issue by davidkarlsen** [kubeapps/kubeapps#966]
I have README.md in my chart, but kubeapps says it can't find it: "NO README FOUND" on the main page for the chart.

```
tar tzvf /Users/et2448/projects/tac/charts/charts/fsjetty/fsjetty-0.2.0.tgz
-rwxr-xr-x  0 0      0         643 Feb 19 23:14 fsjetty/Chart.yaml
-rwxr-xr-x  0 0      0        2348 Feb 19 23:14 fsjetty/values.yaml
-rwxr-xr-x  0 0      0        1384 Feb 19 23:14 fsjetty/templates/NOTES.txt
-rwxr-xr-x  0 0      0        3604 Feb 19 23:14 fsjetty/templates/_helpers.tpl
-rwxr-xr-x  0 0      0         256 Feb 19 23:14 fsjetty/templates/configmap.yaml
-rwxr-xr-x  0 0      0        4577 Feb 19 23:14 fsjetty/templates/deployment.yaml
-rwxr-xr-x  0 0      0         221 Feb 19 23:14 fsjetty/templates/icp-imagepullsecret.yaml
-rwxr-xr-x  0 0      0         248 Feb 19 23:14 fsjetty/templates/imagepullsecret.yaml
-rwxr-xr-x  0 0      0         773 Feb 19 23:14 fsjetty/templates/ingress.yaml
-rwxr-xr-x  0 0      0         546 Feb 19 23:14 fsjetty/templates/pdb.yaml
-rwxr-xr-x  0 0      0         199 Feb 19 23:14 fsjetty/templates/role.yaml
-rwxr-xr-x  0 0      0         397 Feb 19 23:14 fsjetty/templates/rolebinding.yaml
-rwxr-xr-x  0 0      0         360 Feb 19 23:14 fsjetty/templates/secret.yaml
-rwxr-xr-x  0 0      0         484 Feb 19 23:14 fsjetty/templates/service.yaml
-rwxr-xr-x  0 0      0         310 Feb 19 23:14 fsjetty/templates/serviceaccount.yaml
-rwxr-xr-x  0 0      0         339 Feb 19 23:14 fsjetty/.helmignore
-rwxr-xr-x  0 0      0         173 Feb 19 23:14 fsjetty/README.md
-rwxr-xr-x  0 0      0        1071 Feb 19 23:14 fsjetty/ci/test-values.yaml
-rwxr-xr-x  0 0      0          32 Feb 19 23:14 fsjetty/test.env
```

**Comment by prydonius** [comment]
Weird, you can see how `chart-repo` extracts README's here: https://github.com/helm/monocular/blob/master/cmd/chart-repo/utils.go#L365. Can you see anything in the repository sync pod logs?

**Comment by andresmgot** [comment]
There can be two possible causes:
 - As @prydonius says the import may have failed, you should see the error "README.md not found" in the sync job for your chart repository if that's the case.
- The dashboard fails to fetch it. In this case you should see an error in the web browser console or a 404 when trying to access `api/chartsvc/v1/assets/fsjetty/versions/0.2.0/README.md`.

**Comment by davidkarlsen** [comment]
I see this in the sync job:
```
 kubectl -n kubeapps logs apprepo-sync-local-charts-1550660400-wzgg7 |grep fsjet
time="2019-02-20T11:00:14Z" level=error msg="failed to import icon" error="Get https://www.evry.com/contentassets/ca5fbbb8427142a9af697b34f70dea04/evry-logo_rgb.png: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" name=fsjetty
time="2019-02-20T11:00:14Z" level=error msg="failed to import files" error="Get https://icp-global.finods.com:8443/helm-repo/requiredAssets/fsjetty-0.2.0.tgz: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" name=fsjetty version=0.2.0
time="2019-02-20T11:00:24Z" level=error msg="failed to import files" error="Get https://icp-global.finods.com:8443/helm-repo/requiredAssets/fsjetty-0.1.4.tgz: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" name=fsjetty version=0.1.4
time="2019-02-20T11:00:24Z" level=error msg="failed to import files" error="Get https://icp-global.finods.com:8443/helm-repo/requiredAssets/fsjetty-0.1.3.tgz: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" name=fsjetty version=0.1.3
time="2019-02-20T11:00:34Z" level=error msg="failed to import files" error="Get https://icp-global.finods.com:8443/helm-repo/requiredAssets/fsjetty-0.1.2.tgz: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" name=fsjetty version=0.1.2
time="2019-02-20T11:00:34Z" level=error msg="failed to import files" error="Get https://icp-global.finods.com:8443/helm-repo/requiredAssets/fsjetty-0.1.1.tgz: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" name=fsjetty version=0.1.1
time="2019-02-20T11:00:34Z" level=error msg="failed to import files" error="Get https://icp-global.finods.com:8443/helm-repo/requiredAssets/fsjetty-0.1.0.tgz: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" name=fsjetty version=0.1.0
Davids-Work-MacBook-Pro:manifests et2448$ 
```

but the chart is displaying fine (except for the readme) and I can deploy it etc.

**Comment by davidkarlsen** [comment]
I see a 404 for the GET in the dash:
```
kubeapps/kubeapps-6db6fbc46b-j9vqp[nginx]: 10.200.15.121 - - [20/Feb/2019:11:44:58 +0000] "GET /api/chartsvc/v1/assets/local-charts/fsjetty/versions/0.2.0/README.md HTTP/1.1" 404 19 "https://kubeapps.icp-proxy-aot-global.finods.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36"
```

**Comment by davidkarlsen** [comment]
For the logo this is related: https://github.com/kubeapps/kubeapps/issues/696

**Comment by andresmgot** [comment]
Can be possible that the README was added to the version 0.2.0 after the first sync of Kubeapps? Right now it seems that it's not able to download the chart so it cannot update the information:

```
time="2019-02-20T11:00:14Z" level=error msg="failed to import files" error="Get https://icp-global.finods.com:8443/helm-repo/requiredAssets/fsjetty-0.2.0.tgz: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" name=fsjetty version=0.2.0
```

So you may be seeing outdated information in Kubeapps.

**Comment by davidkarlsen** [comment]
No. Readme has been there the whole time. I'll dig a bit more. I think the chart repo hands out some external refs to the actual chart which fails download but Chart.yaml can be fetched. The strange thing is that an actual deployment via kubeapps works just fine.

**Comment by andresmgot** [comment]
> The strange thing is that an actual deployment via kubeapps works just fine (probably because it is then fetched with my login credentials)

Those are two different flows. For deploying a chart `tiller-proxy` is the one that downloads the chart but for showing the information in the dashboard (like the README.md) the `chartsvc` is the one downloading that. Do you have any proxy setup in `tiller-proxy` that allows you to reach `https://icp-global.finods.com:8443/helm-repo...`?

**Comment by davidkarlsen** [comment]
Dug a bit deeper.

I downloaded the index.yaml (which is successfully downloaded), and it's contents is:
```
apiVersion: v1
entries:
  cleaner-daemon:
  - apiVersion: v1
    appVersion: "1.0"
    ...
    icon: https://www.evry.com/contentassets/ca5fbbb8427142a9af697b34f70dea04/evry-logo_rgb.png
    ...
    urls:
    - https://icp-global.finods.com:8443/helm-repo/requiredAssets/cleaner-daemon-0.3.6.tgz
    version: 0.3.6
```

which explains why meta-data is OK, but not the actual chart-contents.

The way it works in ICP is:
management ingress (requires auth tokens) -> service -> pods

So in hope of avoiding the auth stuff I've pointed it at the service - but that doesn't work entirely out as the actual index file contains reference to the ingress url. Not all nodes have access to the ingress endpoint, and I see that there is no way to control where the apprepo-sync-local-charts-* cronjob pod will land with affinity/node-selectors - and unfortunately it lands on a node which does not have access.

**Comment by andresmgot** [comment]
I see, right now there is not an easy way to modify the pod template that the apprepository controller uses to create the jobs/cronjobs. We could add a configuration option to be able to define a template for those but it's not trivial. The problem with your manual change is that it will get lost whenever the controller detects a change with the apprepository since the controller will update that CronJob.

**Comment by davidkarlsen** [comment]
@andresmgot I tried adding http_proxy (and no_proxy) to get the icon downloaded - but it didn't seem to be picked up - should it have?

I think I'll create a new issue for the templating of the cronjob to make it cleaner and refer to this for the background?

**Comment by prydonius** [comment]
@davidkarlsen this might actually be related to an issue with the sync tool not using proxy environment vars: https://github.com/helm/monocular/pull/602. This was just fixed and available in `quay.io/helmpack/chart-repo:v1.4.0` but Kubeapps is using an older version by default. You could try manually setting that tag with `--set apprepository.syncImage.tag=v1.4.0`. I'll update the Kubeapps chart to use this version.

**Comment by davidkarlsen** [comment]
Closing in favour of follow-up issue in #970

**Comment by prydonius** [comment]
thanks @davidkarlsen, did this work for you with the new version and updating cronjobs to set the proxy env vars?

**Comment by davidkarlsen** [comment]
@prydonius I though I'd wait for the chart to be updated and retest then.
