### ISSUE TITLE
Unable to start a GKE cluster for k8s 1.10

### ISSUE THREAD

**Issue by andresmgot** [kubeapps/kubeapps#972]
Build: https://circleci.com/gh/kubeapps/kubeapps/6455

It's not possible to choose 1.10 as version when creating a cluster with `gcloud`:

```
ERROR: (gcloud.container.clusters.create) ResponseError: code=400, message=No valid versions with the prefix "1.10" found.
```

If we want to keep testing that branch we would need to change the way we are selecting the version.

**Comment by arapulido** [comment]
Yes, 1.10 has been deprecated in GKE. We should just start skipping 1.10 in GKE

**Comment by andresmgot** [comment]
okay, let's remove that branch and wait until they add support for 1.12
