### ISSUE TITLE
Auto-refresh OIDC token

### ISSUE THREAD

**Issue by andresmgot** [kubeapps/kubeapps#974]
Follow up from https://github.com/kubeapps/kubeapps/pull/961#issuecomment-463675313:

> Also, I tried to see what would happen if the tokens expired. I set the token expiration in Keycloak to 1 minute and saw that expired tokens don't reinitiate the OAuth flow when clicking around the app, AJAX requests are getting 307 redirects to start the OAuth flow, but it is blocked by CORS. Despite this, resources seem to load... Not sure what to do here or if we need to do anything, can you investigate?
>>
>>I have reduced the expiration time and I have tried 3 things:
>> - Wait until the token expires: When doing this, when changing the location (for example from the app list to a specific app) I get momentarily redirected to the `/login` page and the token gets refreshed and I am redirected again to the page I was meant to visit. I think that's the expected behavior:
>>![screenshot from 2019-02-14 16-31-40](https://user-images.githubusercontent.com/4025665/52797390-15b57b00-3076-11e9-8715-97a57d722c0d.png)
>> - Close the session of the user from keycloak: I can navigate the application until the token expires, then I start receiving 403 errors from the application but I don't get redirected. The application claims that I don't have sufficient permissions to request the resources. When reloading the page I get redirected again to the login page of keycloak:
>>![screenshot from 2019-02-14 16-33-23](https://user-images.githubusercontent.com/4025665/52797549-62995180-3076-11e9-8716-dfbc037a05c3.png)
>> - Delete the user from keycloak: The same behavior than above.

I am no longer seeing the behavior above (I am not sure what changed). When a token expires I see the following error in the console:

```
Access to XMLHttpRequest at 'https://login.windows.net/9c701005-1e88-41d9-bc41-44f1c95615bd/oauth2/authorize?client_id=1f255319-3791-486b-bfbf-edc2c341bab9&redirect_uri=https%3A%2F%2Fkubeapps.local%2Foauth%2Fcallback&response_type=code&scope=openid+email+profile&state=42688e6d-0340-46d0-9f12-fd4b8450f8fc' (redirected from 'https://kubeapps.local/api/tiller-deploy/v1/namespaces/default/releases') from origin 'https://kubeapps.local' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

And the application crashes when trying to load most of the resources. Refreshing the page or going to `/login` fixes the issue but we should improve the UX there.

**Comment by prydonius** [comment]
> I am not sure what changed

I think you said that last time your IdP was on the same domain? If that was the case, CORS was not an issue. It's pretty likely that a user's IdP will not be on the same domain, though.

The application crashing is pretty bad, we should try and detect failed requests, though it doesn't look like it'll be easy/possible: https://stackoverflow.com/questions/19325314/how-to-detect-cross-origin-cors-error-vs-other-types-of-errors-for-xmlhttpreq https://stackoverflow.com/questions/31312703/whenever-a-cors-http-request-fails-the-response-returned-is-always-0

**Comment by andresmgot** [comment]
I was thinking on having a expiration time for the token in case Kubeapps is using an OIDC token. If after X minutes (that can be configurable) we discard the token and we redirect users to `/login` again, the token should be refreshed and the users won't see the app crash.

**Comment by prydonius** [comment]
That's an interesting solution, but feels like a last resort to me. We should first investigate:

- Is there a way we can figure out from a failed request that the OIDC token might be expired and we need to restart the OAuth flow?
- We're not using Keycloak Gatekeeper's ability to automatically refresh tokens because we bypass the whole `/api/kube` path, since WebSockets don't work correctly when going through the proxy. Is there another workaround to this that will fix the WebSocket issue but still allow us go through the proxy?

Actually, now that I think about it, with `/api/kube` whitelisted in Keycloak Gatekeeper, we shouldn't need to start the OAuth flow for Kubernetes API requests. They're bypassed and should go right through. We should check again if this is still an issue. Perhaps we just need to whitelist `/api` or `/` entirely to allow all requests to not require auth.

**Comment by andresmgot** [comment]
I have spent a bit of time reproducing the issue and gathering info.

> Is there a way we can figure out from a failed request that the OIDC token might be expired and we need to restart the OAuth flow?

As far as I can tell there is not a way to know this, When the token needs refreshing we receive an error with `code: undefined`, `response: undefined`, `config.xsrfCookieName: "XSRF-TOKEN"` and message `Network Error`. We could assume that with that if an error matches those files, the token may require refreshing but we cannot be sure.

> We're not using Keycloak Gatekeeper's ability to automatically refresh tokens because we bypass the whole /api/kube path, since WebSockets don't work correctly when going through the proxy. Is there another workaround to this that will fix the WebSocket issue but still allow us go through the proxy?

We are detecting errors not only with the path `/api/kube/*` but with all the request like `/api/tiller-deploy/v1/namespaces/default`. Actually if you refresh (re-requesting the app) the page that gets the error, it gets automatically redirected to the `/login` page, it gets a new token, and the application successfully shows the target page again.

What it's interesting is that if we remove the token from the store in Kubeapps and we navigate to `/login` (without refreshing the app) it's not able to refresh the token. The HEAD request to `/` fails with the following errors:

```
> Access to XMLHttpRequest at 'https://keycloak.devlocal/auth/realms/k8s/protocol/openid-connect/auth?client_id=oidckube&redirect_uri=http%3A%2F%2Fkubeapps.local%2Foauth%2Fcallback&response_type=code&scope=openid+email+profile&state=Lw%3D%3D' (redirected from 'http://kubeapps.local/') from origin 'http://kubeapps.local' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
> Cross-Origin Read Blocking (CORB) blocked cross-origin response https://keycloak.devlocal/auth/realms/k8s/protocol/openid-connect/auth?client_id=oidckube&redirect_uri=http%3A%2F%2Fkubeapps.local%2Foauth%2Fcallback&response_type=code&scope=openid+email+profile&state=Lw%3D%3D with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.
> createError.js:16 Uncaught (in promise) Error: Network Error
    at createError (createError.js:16)
    at XMLHttpRequest.handleError (xhr.js:87)
```

So firstly we need to figure out a way of refreshing a token without having to reload the whole application. This may be not possible and one possible solution is redirect to the proper URL so we trigger the authentication flow. Note that if not only the token has expired but the SSO session has as well, the user will be redirected to the OIDC provider login page to reintroduce its credentials.

Once we figure out that we can either:
 - Try to detect if an error is because of an invalid token
 - Set an interval in Kubeapps to check if the token is still valid. It seems this may be possible if we implement this as a middleware. See this post: http://nmajor.com/posts/access-and-refresh-token-handling-with-redux#automatic-token-refreshing

**Comment by prydonius** [comment]
> Actually if you refresh (re-requesting the app) the page that gets the error, it gets automatically redirected to the /login page, it gets a new token, and the application successfully shows the target page again.

So this is without refreshing the browser or not?

> What it's interesting is that if we remove the token from the store in Kubeapps and we navigate to /login (without refreshing the app) it's not able to refresh the token. The HEAD request to / fails with the following errors:

When is it possible for the token to be removed from the store? If it's something that has to happen manually (i.e. messing around in the development console), then we don't need to worry about that case, right?

**Comment by andresmgot** [comment]
>> Actually if you refresh (re-requesting the app) the page that gets the error, it gets automatically redirected to the /login page, it gets a new token, and the application successfully shows the target page again.

> So this is without refreshing the browser or not?

This is refreshing the browser (F5).

> When is it possible for the token to be removed from the store? If it's something that has to happen manually (i.e. messing around in the development console), then we don't need to worry about that case, right?

What I wanted to mean is that if we know the token is no longer valid we (kubeapps) can just remove it from the store and navigate to `/login` to trigger the process to obtain a new one. That didn't work in my tests because I wasn't being redirected to the IdP. That's what we need to fix first.

**Comment by prydonius** [comment]
> What I wanted to mean is that if we know the token is no longer valid we (kubeapps) can just remove it from the store and navigate to /login to trigger the process to obtain a new one. That didn't work in my tests because I wasn't being redirected to the IdP. That's what we need to fix first.

Ah, I see, ok - thanks.
