### ISSUE TITLE
Need more details for OIDC w/ Azure AD  

### ISSUE THREAD

**Issue by mpalumbo7** [kubeapps/kubeapps#975]
This is a request for advice and/or improved documentation in [using-an-OIDC-provider](https://github.com/kubeapps/kubeapps/blob/master/docs/user/using-an-OIDC-provider.md). Will open a PR to enhance docs once I get this working.

## Description
Even after reading #948, I cant get Azure AD with keycloak-gatekeeper working using the [bitnami kubeapps helm chart](https://github.com/bitnami/charts/tree/master/bitnami/kubeapps). It seems like @andresmgot was able to get it working, but the details of the Azure AD configuration are not given.

 After I login to Azure, I get redirected back to the kubeapps dashboard, but I receive an error:

```
There was an error connecting to the Kubernetes API. Please check that your token is valid.
```

Strangely, even after I try to paste my kubectl access-token into the dashboard, I get a `You don't have sufficient permissions to list Applications in the default namespace`. Maybe pasting in the token is not supported when using keycloak-gatekeeper.

When I disable keycloak-gatekeeper, and do an upgrade via helm, I can paste in my kubectl access-token and everything works.

## auth-proxy Logs
Notice the warning:

```
unable to parse the access token, using id token only   {"error": "malformed JWS, only 1 segments"}
```

Full logs:
```
$ kubectl -n kubeapps logs -f kubeapps-7f64457c5f-cswg9  auth-proxy
1.550942951733407e+09   info    starting the service    {"prog": "keycloak-gatekeeper", "author": "Keycloak", "version": "4.8.1 (git+sha: e5bd7e6-dirty, built: 19-12-2018)"}
1.5509429517336717e+09  info    attempting to retrieve configuration discovery url      {"url": "https://sts.windows.net/{tenantId}/","timeout": "30s"}
1.5509429520594022e+09  info    successfully retrieved openid configuration from the discovery
1.5509429520845747e+09  info    enabled reverse proxy mode, upstream url        {"url": "http://localhost:8080/"}
1.5509429520846813e+09  info    using session cookies only for access and refresh tokens
1.550942952084721e+09   info    adding a default denial into the protected resources
1.550942952084728e+09   info    protecting resource     {"resource": "uri: /api/kube/*, white-listed"}
1.5509429520847523e+09  info    protecting resource     {"resource": "uri: /*, methods: DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT,TRACE, required: authentication only"}
1.550942952084922e+09   info    keycloak proxy service starting {"interface": "0.0.0.0:3000"}
1.5509430298884387e+09  error   session expired and access token refreshing is disabled {"client_ip": "10.244.4.134:56424", "email": "", "expired_on": "2019-02-23 00:36:13 +0000 UTC"}
1.550943031070579e+09   warn    unable to parse the access token, using id token only   {"error": "malformed JWS, only 1 segments"}
1.5509430310973651e+09  info    issuing access token for user   {"email": "", "expires": "2019-02-23T18:30:30Z", "duration": "59m58.902635926s"}
1.5509430524155443e+09  error   no session found in request, redirecting for authorization      {"error": "authentication session not found"}
1.5509430771854181e+09  warn    unable to parse the access token, using id token only   {"error": "malformed JWS, only 1 segments"}
1.5509430771857057e+09  info    issuing access token for user   {"email": "", "expires": "2019-02-23T18:31:17Z", "duration": "59m59.814302581s"}
```

## Helm Values
```yaml
authProxy:
  enabled: true
  clientID: {clientId}
  clientSecret: "{secret}"
  discoveryURL: https://sts.windows.net/{tenantId}/
  additionalFlags:
    - --secure-cookie=false
    - --redirection-url=https://kubeapps.example.com
```

## Azure App Registration
Redacted manifest for the k8s server app in Azure AD:
```json
{
	"name": "k8s-api",
	"appId": "{clientId}",
	"acceptMappedClaims": null,
	"accessTokenAcceptedVersion": null,
	"allowPublicClient": false,
	"appRoles": [],
	"oauth2AllowUrlPathMatching": false,
	"groupMembershipClaims": "SecurityGroup",
	"oauth2AllowIdTokenImplicitFlow": true,
	"oauth2AllowImplicitFlow": true,
	"oauth2RequirePostResponse": false,
	"optionalClaims": null,
	"replyUrlsWithType": [
		{
			"url": "https://kubeapps.example.com/oauth/callback",
			"type": "Web"
		}
	],
	"tokenEncryptionKeyId": null
}
```

**Comment by mpalumbo7** [comment]
I think this is because I used the aks-engine, instead of the AKS managed service.

The aks-engine configurs the apiserver per the following:

```
   "--oidc-client-id": "spn:{clientId}",
   "--oidc-groups-claim": "groups",
   "--oidc-issuer-url": "https://sts.windows.net/{tenantId}/",
   "--oidc-username-claim": "oid"
```

When I looked at the apiserver logs, I noticed the following:

```
$ k -n kube-system logs  kube-apiserver-k8s-master-XXXXXXX-0 | grep aud
E0223 23:15:41.300808       1 authentication.go:62] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, oidc: verify token: oidc: expected audience "spn:{clientId}" got ["{clientId}"]]]
```

So, I'm not an expert here, but the problem appears to be that the AKS-engine uses `aud: spn:{clientId}` and keycloak is generating tokens with `aud:{clientId}`. 

The go code in the Azure auth-provider for `kubectl` has `spn:{clientId}` baked into at on [azure.go#L255](https://github.com/kubernetes/client-go/blob/dbd11fce0f2e8da137f09b53d8a59cecc8e85dc8/plugin/pkg/client/auth/azure/azure.go#L255). It is using the Azure AD v1.0 endpoint and the `resource` option whereas the [v2.0 endpoint works with scopes](https://docs.microsoft.com/en-us/azure/active-directory/develop/azure-ad-endpoint-comparison#scopes-not-resources).

Moving the v2.0 endpoint is not really an option right now. I have heard rumor that the v2.0 endpoint will be compatible with the vanilla OIDC auth-provider, but I'm gonna have to do a lot of testing to see if it works.

So, I guess my question boils down to: can anybody lend me some advice on how to use keycloak-gatekeeper to use the v1.0 endpoint to get `aud` field to have `spn:{clientId}`? I tried playing around with the `--scopes` argument, but it doesn't do anything on the v1.0 endpoint.

**Comment by andresmgot** [comment]
hi @mpalumbo7,

I indeed made it work but following the step by step guide made by azure using a new cluster: https://docs.microsoft.com/en-us/azure/aks/aad-integration. Maybe you can try with that and look for differences? That way we can be sure that the error is related to the prefix and not something else.

> So, I guess my question boils down to: can anybody lend me some advice on how to use keycloak-gatekeeper to use the v1.0 endpoint to get `aud` field to have `spn:{clientId}`? I tried playing around with the `--scopes` argument, but it doesn't do anything on the v1.0 endpoint.

AFAIK it's not something that can be specified in keycloak-gatekeeper. I know that for setting a prefix in the API server it's needed to set a flag with the prefix. Something like:

```
    --extra-config=apiserver.oidc-username-prefix="oidc:" \
    --extra-config=apiserver.oidc-groups-prefix="oidc:" \
```

Are those flag also set with `aks-engine`? Maybe it's possible to configure how the API server is started?

**Comment by arapulido** [comment]
@mpalumbo7 were you able to re-try following the guide @andresmgot pointed at?

**Comment by arapulido** [comment]
@mpalumbo7 We are closing this issue. Feel free to reopen if you need anything else.
