### ISSUE TITLE
Unable to listen on port 8080

### ISSUE THREAD

**Issue by Tanoh-Hermann** [kubeapps/kubeapps#981]
Hello dear developers 

I am new in using kubeapps. This is my first post on GitHub. I encounter a problem that can be trivial, but that I can not solve after reading several forums. Can anyone help me?

I followed the installation procedure of kubeapps, but I hit this step: PORT-FORWARD

`~$  kubectl port-forward --namespace kubeapps kubeapps-759775c988-pj9td 8080:8080

Unable to listen on port 8080: Listeners failed to create with the following errors: [Unable to create listener: Error listen tcp4 127.0.0.1:8080: bind: address already in use Unable to create listener: Error listen tcp6 [::1]:8080: bind: address already in use]
error: Unable to listen on any of the requested ports: [{8080 8080}]
`

kubeapps service is exposed as Cluster IP:
`kubeapps                         ClusterIP   10.245.198.227   <none>        80/TCP      16h
`

I work on Minikube locally, and the cluster is deployed on Digitalocean Kubernetes on Debian do-kube-1.13.2. I already have kubernetes dashboard installed. I had Nginx installed on the default namespace, but I deleted it. However, the problem still remains. Would there be any link to this information?

**Comment by Tanoh-Hermann** [comment]
Proposition of a solution

In trying to find the origin of the problem, I tried:

`~$ lsof -n | grep TCP | grep LISTEN | grep 8080`

I then noticed that Microk8s installed locally, was involved. So I uninstalled it, and everything works fine now.
Was this the right solution? In any case, it worked for me.

**Comment by andresmgot** [comment]
Hi @Tanoh-Hermann,

Indeed the problem was that you tried to forward the port 8080 that was already being used by a different process. As you did you can stop the process that is running in the port 8080 but you can also use a different port to forward the connection. For example, if you want to use the port 8081 you can execute:

```
kubectl port-forward --namespace kubeapps kubeapps-759775c988-pj9td 8081:8080
```

Then you should be able to access Kubeapps with the URL `http://localhost:8081`.

**Comment by Tanoh-Hermann** [comment]
Thank you very much for the answer @andresmgot . That would have helped me a lot from the beginning of my research. But it's also a good thing to have uninstalled an app that did not really serve me.
Thank you so much!

**Comment by prydonius** [comment]
Glad you were able to get this working, @Tanoh-Hermann!
