### ISSUE TITLE
catalog list is empty

### ISSUE THREAD

**Issue by obeyler** [kubeapps/kubeapps#996]
Context :

I've got an "Internal" chart repository with chartmuseum.
I change the podsecuritypolicy to avoid local storage (ie I remove emptydir from the allowed list of volume) so the pod of chartumuseum refuse to launch.

Kubeapp launch well but it wasn't able anymore to list chart from other repository. It doesn't discover anymore if there is a new chart version.

As I can see, the only deployment  who failed is "kubeapps-internal-chartsvc"
and all job of sync are failed

I don't know if the root cause is the Internal repository unavaliable or if the sync job need local storage.

PS I don't allow local storage because when I need to drain node It blocks the drain so I'm not able to update the K8S automaticaly

**Comment by andresmgot** [comment]
Hi @obeyler,

The chartsvc should not be affected by a failed repository. The logs of the pod will show where is the error. The most common issue is that it's not able to connect to MongoDB, can you check if that's the case?

**Comment by prydonius** [comment]
I think @andresmgot is on the right track that the issue might be with MongoDB. We actually disable the persistent volume in the MongoDB chart by default (https://github.com/kubeapps/kubeapps/blob/master/chart/kubeapps/values.yaml#L254), which will make it use an emptyDir (https://github.com/helm/charts/blob/master/stable/mongodb/templates/deployment-standalone.yaml#L212). That might be why MongoDB isn't working correctly?

**Comment by arapulido** [comment]
@obeyler Any updates on this?

**Comment by andresmgot** [comment]
Closing this issue as inactive, let me know if you still find this issue and I will reopen it.
